CAD制图
无锡兰桂医疗股份有限公司
五险一金年底双薪绩效奖金加班补助餐补定期体检员工旅游节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
加班补助
餐补
定期体检
员工旅游
节日福利
**********
职位月薪：4000-5000元/月 
工作地点：无锡-无锡新区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：CAD设计/制图
**********
岗位职责：
1、主要负责产品的CAD制图排版。
2、领导交代的其他工作。
任职要求：
1、大专以上学历，应届生也可。
2、有工作经验者优先考虑。
3、待遇可面议。

工作地址：
无锡市新区新洲路210号
查看职位地图
**********
无锡兰桂医疗股份有限公司
公司规模：
20-99人
公司性质：
股份制企业
公司行业：
医疗设备/器械
公司地址：
无锡市新区新洲路210号
**********
品质工程师
无锡钧弘自动化科技有限公司
五险一金绩效奖金加班补助全勤奖餐补带薪年假免费班车节日福利
**********
福利:
五险一金
绩效奖金
加班补助
全勤奖
餐补
带薪年假
免费班车
节日福利
**********
职位月薪：4000-6000元/月 
工作地点：无锡-北塘区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：质量管理/测试主管
**********
岗位职责：
（1）完成日常质量检验、验证工作，质量监控及结果上报工作；
（2）参与维护、监督质量体系的运行、组织和管理内部质量审核工作；
（3）运用质量统计工具对质量数据进行分析，对生产过程中出现的质量问题进行分析改进。
（4）编制检验指导书。
（5）对于新品试制以及小批生产过程中的工程和质量问题进行有效整改和持续跟踪。
（6）质量投诉的处理以及纠正措施的制定和持续跟踪实施。

任职要求：
（1）机械工程类相关专业，英语4级以上。
（2）接受过质量管理、加工制造、数据统计等方面知识培训，了解TS16494体系，五大工具
（3）有良好的表达能力；具备加工制造行业质量管理经验，现场品质管理经验
（4）学习能力强，并具备一定管理能力。

工作地址：
无锡市光电园会北路28-94号
**********
无锡钧弘自动化科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
仪器仪表及工业自动化
公司主页：
www.exmek.com
公司地址：
无锡市光电园会北路28-94号
查看公司地图
**********
研发中级工程师
圆容生物医药无锡有限公司
五险一金绩效奖金年终分红股票期权交通补助弹性工作
**********
福利:
五险一金
绩效奖金
年终分红
股票期权
交通补助
弹性工作
**********
职位月薪：6001-8000元/月 
工作地点：无锡
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：医疗器械研发
**********
岗位职责：
 1、高分子材料专业或机械设计相关专业，本科及以上学历；
2、从事产品开发工作2年以上，有医疗器械产品开发背景的优先；
3、具备较强的时间管理和分析问题能力；
4、具备较强的3D建模及2D图纸设计能力；
5、具备中英文文献检索、查阅能力；
6、具有较强的团队合作精神和抗压能力；
7、具备较强的分析问题和解决问题的能力。
任职要求：
 掌握一种3D软件
工作地址：
无锡市新区长江南路35号生命科技园C栋二楼
**********
圆容生物医药无锡有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
医疗设备/器械
公司地址：
无锡市新区长江南路35号生命科技园C栋
查看公司地图
**********
市场部 市场推广人员
基恩科技
五险一金年底双薪绩效奖金通讯补贴定期体检高温补贴节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
通讯补贴
定期体检
高温补贴
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：无锡
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：市场专员/助理
**********
1、大专以上学历
2、有市场医药产品推广经历者优先(2年以上工作经验者)
3、医学或医学检验专业
4、能经常出差
5、有较强的口头表达能力
6、工作地点：江苏省
工作地址：
江苏
**********
基恩科技
公司规模：
20-99人
公司性质：
民营
公司行业：
医药/生物工程
公司地址：
上海浦东新区金海路1000号26号楼2楼A座
查看公司地图
**********
网络推广/SEO
无锡市时盛激光科技有限公司
五险一金年底双薪绩效奖金全勤奖交通补助餐补带薪年假加班补助
**********
福利:
五险一金
年底双薪
绩效奖金
全勤奖
交通补助
餐补
带薪年假
加班补助
**********
职位月薪：8001-10000元/月 
工作地点：无锡
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：不限
招聘人数：6人
职位类别：SEO/SEM
**********
技能要求：1. 深入了解百度、Google、yahoo等搜索引擎的工作原理，熟悉这些搜索引擎的排名机制和优化原则；对google、百度排名算法有一定的了解；2. 熟悉站内优化，站外优化；3. 制定优化方案，根据流量制定优化报表及调整优化策略；4. 熟悉HTML，DIV+CSS,对脚本语言有一定了解；岗位职责：1. 对网站进行整体优化，挑选合适关键词，合理布局关键词；2. 优化代码，优化连接，检查错误页面；3. 分析竞争对手，做出相应对策；工作时间：周一至周六；夏季：（5月1日至9月30日）8:00-12：00——1:30-5:30；冬季（10月1日至4月30日）：8:00-12:00——1:00-5:00法定节假日。工作地址：无锡市滨湖区钱姚路88号龙山文博工业园二号楼三层 联系人：金玲联系电话：18961723576
工作地址：
无锡市滨湖区钱姚路龙山文博工业园2号楼3层
查看职位地图
**********
无锡市时盛激光科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
仪器仪表及工业自动化
公司主页：
www.jszdfg.com
公司地址：
无锡市滨湖区钱姚路龙山文博工业园2号楼3层
**********
网页设计
无锡市时盛激光科技有限公司
五险一金年终分红加班补助餐补交通补助通讯补贴
**********
福利:
五险一金
年终分红
加班补助
餐补
交通补助
通讯补贴
**********
职位月薪：6001-8000元/月 
工作地点：无锡
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：3人
职位类别：网页设计/制作/美工
**********
技能要求：
1.      精通美学，有独特审美能力,能独立完成美术视觉设计排版；
2.      熟练掌握photoshop（PS），FLASH，dreamwaver（DW）等网站制作软件；
3.      能独立设计公司网站及B2B网站页面风格；
4.      熟悉公众号，移动WAP页面设计；
岗位职责：
1.      负责公司网站的用户体验效果；
2.      配合程序员实现网站建设；
3.      负责公司网站的日常更新维护；

工作地址：
无锡市滨湖区钱姚路龙山文博工业园2号楼3层
查看职位地图
**********
无锡市时盛激光科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
仪器仪表及工业自动化
公司主页：
www.jszdfg.com
公司地址：
无锡市滨湖区钱姚路龙山文博工业园2号楼3层
**********
区域销售经理
无锡莱姆顿科技有限公司
五险一金绩效奖金全勤奖带薪年假补充医疗保险定期体检员工旅游节日福利
**********
福利:
五险一金
绩效奖金
全勤奖
带薪年假
补充医疗保险
定期体检
员工旅游
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：无锡
发布日期：最新
工作性质：全职
工作经验：无经验
最低学历：大专
招聘人数：2人
职位类别：销售代表
**********
岗位职责：
1、负责一个区域内的警用、医疗实验室项目的销售，具备独立开发市场的能力；
2、经公司培训，能较快独立完成项目，包括项目挖掘，项目推进，预算申请，招投标工作，合同签订，项目回款等；
3、树立良好的公司形象，执行公司相关规章政策。

任职要求：
1、年龄在21-30周岁，大专及以上学历，男女不限（其它方面优秀的可适当放宽条件）；
2、有一年以上的销售经验，销售对象为政府或医疗机构者优先，同时欢迎优秀应届生；
3、诚实守信，勤奋努力，热爱销售工作，愿意挑战高薪；
5、乐观大方，有亲和力，有较高的情商和良好的沟通技巧；
6、能适应出差；
7、形象气质佳。

基本待遇：
1、公司有成熟的销售薪酬制度，基本模式为底薪+提成+其他奖励；
2、按国家规定缴纳相关社会保险、住房公积金；
3、销售团队成员年薪定位为10-30万；
4、享受所有法定假期；
5、有明确的职业发展方向，给每个销售员一个稳定的中长期成长计划。
工作地址：
无锡市滨湖区绣溪路53号旭天科技园30#单元第一、第二层
查看职位地图
**********
无锡莱姆顿科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
医疗设备/器械
公司主页：
www.lamoton.cn
公司地址：
无锡市滨湖区绣溪路53号旭天科技园30#单元第一、第二层
**********
软件工程师
无锡正和医药有限公司
五险一金定期体检员工旅游节日福利带薪年假
**********
福利:
五险一金
定期体检
员工旅游
节日福利
带薪年假
**********
职位月薪：4001-6000元/月 
工作地点：无锡
发布日期：最新
工作性质：全职
工作经验：1年以下
最低学历：大专
招聘人数：1人
职位类别：软件工程师
**********
岗位职责：负责公司电子设备系统维护、升级、管理等相关工作；
任职要求：  
1、大专及以上学历，计算机及相关专业毕业；
2、做事认真、细心、负责，能够专心学习技术；
3、有良好的工作态度和团队合作精神；
4、有一年左右工作经验，待遇从优
工作地址：
无锡
查看职位地图
**********
无锡正和医药有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医药/生物工程
公司地址：
无锡市滨湖区鸿桥路801号现代国际工业设计大厦1312
**********
网站美工/网页设计
无锡市时盛激光科技有限公司
五险一金绩效奖金全勤奖包住交通补助餐补房补加班补助
**********
福利:
五险一金
绩效奖金
全勤奖
包住
交通补助
餐补
房补
加班补助
**********
职位月薪：6001-8000元/月 
工作地点：无锡
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：3人
职位类别：网站编辑
**********
网站美工/网页设计技能要求：1. 精通美学，有独特审美能力,能独立完成美术视觉设计排版；2. 熟练掌握photoshop（PS），FLASH，dreamwaver（DW）等网站制作软件；3. 能独立设计公司网站及B2B网站页面风格；4. 熟悉公众号，移动WAP页面设计；岗位职责：1. 负责公司网站的用户体验效果；2. 配合程序员实现网站建设；3. 负责公司网站的日常更新维护；工作时间：周一至周六；夏季：（5月1日至9月30日）8:00-12：00——1:30-5:30；冬季（10月1日至4月30日）：8:00-12:00——1:00-5:00法定节假日。工作地址：无锡市滨湖区钱姚路88号龙山文博工业园二号楼三层 联系人：金玲联系电话：18961723576
工作地址：
无锡市滨湖区钱姚路龙山文博工业园2号楼3层
查看职位地图
**********
无锡市时盛激光科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
仪器仪表及工业自动化
公司主页：
www.jszdfg.com
公司地址：
无锡市滨湖区钱姚路龙山文博工业园2号楼3层
**********
销售工程师 Sales Engineer
无锡迅朗科技有限公司
五险一金绩效奖金年终分红交通补助通讯补贴带薪年假员工旅游节日福利
**********
福利:
五险一金
绩效奖金
年终分红
交通补助
通讯补贴
带薪年假
员工旅游
节日福利
**********
职位月薪：6000-12000元/月 
工作地点：无锡
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：销售工程师
**********
概述：
负责公司技术在食品加工业、医疗机构、酒店后厨、连锁餐饮后厨、中小学幼儿园高校食堂、企事业单位食堂、大型团膳机构、中央厨房、公共机构领域的销售。公司核心技术技术在海外已经广泛应用，目前该设备在中国尚处在市场推广期，属于市场蓝海。由于其极高的性价比和产品应用价值，具有广阔的应用空间。该职位需要组织有效的市场资源，开展系统的市场推广活动，建立稳定的销售资源来推进产品的销售覆盖

工作职责：
1、全面负责公司产品在食品工业、医疗机构、中央厨房、大型团膳机构、以及企事业单位中央厨房业务拓展；
2、组建销售团队，建立销售网络，规范销售流程，完成销售目标；
3、制定与实施各产品线体系营销策略、地区覆盖策略及开拓计划，并组织相关人员培训；
4、拓展公司的市场策略，把握公司在行业中的发展方向，完成公司在行业中的市场定位，及时提供市场反馈；
5、负责对区域销售进行评估、跟踪及管理；

任职要求：
1、食品工程相关专业大专以上学历优先考虑；
2、有消毒产品和消毒设备销售经验者优先考虑
3、1年以上工作经验，有项目制销售管理经验和能力者优先考虑
4、有较强的独立工作能力及良好的团队协作精神；
5、有良好的沟通协调能力及社交技巧；
6、有责任心、诚信度，有良好的抗压能力和心理素质；

工作地址：
无锡市新区纺城大道深港亚太中心9号楼
查看职位地图
**********
无锡迅朗科技有限公司
公司规模：
100-499人
公司性质：
合资
公司行业：
仪器仪表及工业自动化
公司主页：
http://www.xunlangtech.com/
公司地址：
无锡市新区纺城大道深港亚太中心9号楼
**********
网页设计/美工
无锡市时盛激光科技有限公司
五险一金年底双薪全勤奖交通补助餐补房补通讯补贴加班补助
**********
福利:
五险一金
年底双薪
全勤奖
交通补助
餐补
房补
通讯补贴
加班补助
**********
职位月薪：5000-10000元/月 
工作地点：无锡
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：5人
职位类别：网站编辑
**********
技能要求：
1.      精通美学，有独特审美能力,能独立完成美术视觉设计排版；
2.      熟练掌握photoshop（PS），FLASH，dreamwaver（DW）等网站制作软件；
3.      能独立设计公司网站及B2B网站页面风格；
4.      熟悉公众号，移动WAP页面设计；
岗位职责：
1.      负责公司网站的用户体验效果；
2.      配合程序员实现网站建设；
3.      负责公司网站的日常更新维护；

工作时间：
周一至周六；8:00-11:30,1:30-5:30；法定节假日。
工作地址：
无锡市滨湖区钱姚路龙山文博工业园2号楼3层
**********
无锡市时盛激光科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
仪器仪表及工业自动化
公司主页：
www.jszdfg.com
公司地址：
无锡市滨湖区钱姚路龙山文博工业园2号楼3层
查看公司地图
**********
内勤
无锡正和医药有限公司
带薪年假定期体检员工旅游节日福利不加班
**********
福利:
带薪年假
定期体检
员工旅游
节日福利
不加班
**********
职位月薪：2800-3500元/月 
工作地点：无锡
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：2人
职位类别：助理/秘书/文员
**********
岗位职责：
1、负责各类销售报表的统计、档案管理工作，协助进行单据的编制并及时向主管领导报送；
2.负责协助销售业务人员做好客户接待与客户关系维护工作；
3.负责本部门文件的收发工作及部门资料的档案管理工作；
4.完成领导交办的其他事务工作。
任职要求：
1、会基本的计算机操作；
2、男女不限，应届毕业生也可以；
3、人品端正、有很强的敬业精神和责任感；
4、勤奋刻苦能坚持、有韧劲
5、有会计上岗证的优先。

工作地址：
无锡市滨湖区鸿桥路801号现代国际工业设计大厦1312
查看职位地图
**********
无锡正和医药有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医药/生物工程
公司地址：
无锡市滨湖区鸿桥路801号现代国际工业设计大厦1312
**********
采购员
无锡正和医药有限公司
五险一金绩效奖金年终分红带薪年假定期体检员工旅游节日福利
**********
福利:
五险一金
绩效奖金
年终分红
带薪年假
定期体检
员工旅游
节日福利
**********
职位月薪：2800-3800元/月 
工作地点：无锡
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：2人
职位类别：内勤人员
**********
岗位职责：
一、负责公司经营药品的采购工作，根据销售进度合理拟定采购计划。
二、规范、协调采购政策，把握进货渠道的合法性。保证药品质量优质，价格合理。  
三、了解药品信息及价格，正确执行药品价格政策，退入库手续清楚，单据齐全。文件、单据妥善保存。  
四、与公司相关职能部门沟通，做好库存积压药品、缺货药品、破损药品、效期药品的协调工作。  
五、负责药品信息及价格的维护，保证其准确性。
六、完成其他采购相关事宜，处理日常办公事务。
任职要求：
1、有一年以上药品采购工作经验，能独立完成药品采购的全部流程。
2、相关医药类专业。

工作地址：
无锡
查看职位地图
**********
无锡正和医药有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医药/生物工程
公司地址：
无锡市滨湖区鸿桥路801号现代国际工业设计大厦1312
**********
网络推广
无锡市时盛激光科技有限公司
五险一金年底双薪绩效奖金全勤奖交通补助餐补带薪年假
**********
福利:
五险一金
年底双薪
绩效奖金
全勤奖
交通补助
餐补
带薪年假
**********
职位月薪：6001-8000元/月 
工作地点：无锡
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：5人
职位类别：SEO/SEM
**********
技能要求：
1. 深入了解百度、Google、yahoo等搜索引擎的工作原理，熟悉这些搜索引擎的排名机制和优化原则；对google、百度排名算法有一定的了解；
2. 熟悉站内优化，站外优化；
3. 制定优化方案，根据流量制定优化报表及调整优化策略；
4. 熟悉HTML，DIV+CSS,对脚本语言有一定了解；
岗位职责：
1. 对网站进行整体优化，挑选合适关键词，合理布局关键词；
2. 优化代码，优化连接，检查错误页面；
3. 分析竞争对手，做出相应对策；
工作时间：周一至周六；法定节假日。
工作地址：无锡市滨湖区钱姚路88号龙山文博工业园二号楼三层 
联系人：金玲
联系电话：18961723576
工作地址：
无锡市滨湖区钱姚路龙山文博工业园2号3层
查看职位地图
**********
无锡市时盛激光科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
仪器仪表及工业自动化
公司主页：
www.jszdfg.com
公司地址：
无锡市滨湖区钱姚路龙山文博工业园2号楼3层
**********
网站编辑
无锡市时盛激光科技有限公司
五险一金绩效奖金全勤奖包住交通补助餐补房补
**********
福利:
五险一金
绩效奖金
全勤奖
包住
交通补助
餐补
房补
**********
职位月薪：6001-8000元/月 
工作地点：无锡
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：5人
职位类别：网页设计/制作/美工
**********
技能要求：
1.      精通美学，有独特审美能力,能独立完成美术视觉设计排版；
2.      熟练掌握photoshop（PS），FLASH，dreamwaver（DW）等网站制作软件；
3.      能独立设计公司网站及B2B网站页面风格；
4.      熟悉公众号，移动WAP页面设计；
岗位职责：
1.      负责公司网站的用户体验效果；
2.      配合程序员实现网站建设；
3.      负责公司网站的日常更新维护；

工作地址：
滨湖区钱姚路龙山文博工业园2号3楼
查看职位地图
**********
无锡市时盛激光科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
仪器仪表及工业自动化
公司主页：
www.jszdfg.com
公司地址：
无锡市滨湖区钱姚路龙山文博工业园2号楼3层
**********
客户经理
东软医疗系统有限公司
五险一金绩效奖金交通补助采暖补贴带薪年假补充医疗保险定期体检节日福利
**********
福利:
五险一金
绩效奖金
交通补助
采暖补贴
带薪年假
补充医疗保险
定期体检
节日福利
**********
职位月薪：6000-8000元/月 
工作地点：无锡
发布日期：最近
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：销售工程师
**********
岗位职责：
 1、制定年度销售计划，并按计划完成销售指标，参与投标项目或重大销售项目的策划；
2、负责分销商信息的收集、整理以及分销商的挖掘发展、关系维护，确保分销渠道持续、健康的发展；
3、负责市场信息、项目信息的收集，依据区域销售计划，组织分销渠道进行区域市场推广活动；
4、负责提供分销商销售项目的支持(包括销售业绩预测/回款/发机的监控；区域竞争对手的情况;所辖区域行业专家网络的建立和维护；分销商的培训、销售能力提升等)。
任职要求：
1、本科及以上学历，至少3年以上影像设备销售经验；
2、掌握影像设备行业动态、了解影像产品知识，并具备以下能力中2项以上能力：
-具有独立运作高端客户项目能力，具有问题解决与建立关系能力，可以独立拓展新客户
-具备合同管理法律法规、市场营销及项目管理知识
-具有销售计划管理、资源协调及商务谈判能力
-具备较强的面向渠道的产品培训能力、建立关系能力。
  工作地址：
沈阳市浑南区创新路177-1号
查看职位地图
**********
东软医疗系统有限公司
公司规模：
1000-9999人
公司性质：
合资
公司行业：
医疗设备/器械
公司主页：
medical.neusoft.com
公司地址：
沈阳市浑南区创新路177-1号
**********
测试工程师（培训生）
捷普科技(上海)有限公司
五险一金年底双薪绩效奖金带薪年假定期体检免费班车
**********
福利:
五险一金
年底双薪
绩效奖金
带薪年假
定期体检
免费班车
**********
职位月薪：2001-4000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：无经验
最低学历：大专
招聘人数：10人
职位类别：测试/可靠性工程师
**********
岗位职责：
1. 分产品测试和测试站维护两大板块
2. 测试程序优化、调试
任职要求：
1. 微电子、电子信息工程、通信工程等专业优先
2. 2018届应届毕业生
3. 大学英语4级通过，读写良好
个人简历可以投递至Rikki_fan@jabil.com
工作地址：
新吴区出口保税区J9J10地块 捷普电子（无锡）有限公司
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
HR supervisor
Antal International
**********
福利:
**********
职位月薪：10000-15000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：人力资源主管
**********
1, Support GM to improve and develop the organization according to the company strategy and drive HR functional excellence, initiating continuous improvements;
2, Modify and update handbook and all related HR & Admin policy.
3, Responsible for HR budget and control labor cost.
4, Recruitment: Define appropriate recruitment channel according to different position, select qualified candidates and arrange interview with hiring manager. Ensure offer process is in compliance with company policy.
5, Compensation & Benefit: Manage salary planning and monthly payroll in timely and accurate manner. Handle all the social insurance/housing fund/ incoming tax issues. Initiate and maintain compensation and benefit process in compliance with company policy
6, Set up monthly performance bonus system for workshop employees and annual bonus policy for office staff. Maintenance and update company's benefit policy.
7, Conduct salary survey to ensure equity to external market.
8, Performance Management: Assist to set the target of performance for every department, communicate with all relevant aspects to evaluate the performance, which linked to annual bonus.
9, Training: Conduct annual training needs analysis and establish annual training plan under HR budget accordance to Company’s strategy, and follow up accordingly.
10, Employee Relationship: Responsible for internal communication channels and improve its effectiveness, create a positive working environment and improve atmosphere.
11, Ensure all HR activities are under China's labor law.
12, Responsible for yearly ISO audit.
13, Other daily work, like employee's physical check, commercial insurance and so on.
14, Admin Services: Responsible for the organizing, coordinating and arranging logistics services, such as vehicles & drivers (including shuttle buses), canteen, security, cleaning, etc., in order to ensure the smooth operation of the Company.
15, Admin warehouse management, cost control.
16, All the foreigners working permit/ passport/visa issue.
17, Annual dinner and other holiday benefit.
工作地址：
Suite 1102A, Tower D, DRC Office Building, No.19 Dongfangdonglu, Chaoyang District,Beijing
**********
Antal International
公司规模：
100-499人
公司性质：
外商独资
公司行业：
专业服务/咨询(财会/法律/人力资源等)
公司主页：
www.antal.com
公司地址：
Suite 1102A, Tower D, DRC Office Building, No.19 Dongfangdonglu, Chaoyang District,Beijing
**********
(ID66687)质量管理售后助理（汽车电子）
任仕达企业管理(上海)有限公司
五险一金餐补带薪年假
**********
福利:
五险一金
餐补
带薪年假
**********
职位月薪：4001-6000元/月 
工作地点：无锡-滨湖区
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：机械工程师
**********
公司主要从事汽油发动机管理系统、变速箱控制系统、车身电子、混合动力和电力驱动控制系统的开发、生产和销售。2016年，公司销售额突破200亿元人民币，员工人数约8000多人。公司拥有强大的专业技术团队，综合考虑车辆的性能，根据客户要求定制软硬件，提供完整的系统解决方案，从而满足不同客户的需求。
 工作描述：
1、针对售后零件进行简单测量分析
2、将零件信息进行登记
3、数据汇总，报表制作
 岗位要求：
1、大专及以上学历，机械或电子专业优先考虑
2、能简单看懂图纸
3、有相关工作经验优先考虑
 工作时间：周一至周五8：30-17：30
 工作地点：无锡长江路15号

薪资福利：工资+免费工作餐+年终奖
工作地址：
无锡市长江路
**********
任仕达企业管理(上海)有限公司
公司规模：
500-999人
公司性质：
外商独资
公司行业：
专业服务/咨询(财会/法律/人力资源等)
公司主页：
https://www.randstad.cn
公司地址：
上海静安区梅园路77号上海人才大厦22楼
**********
精益专员
捷普科技(上海)有限公司
免费班车员工旅游节日福利包住五险一金年底双薪绩效奖金包吃
**********
福利:
免费班车
员工旅游
节日福利
包住
五险一金
年底双薪
绩效奖金
包吃
**********
职位月薪：6001-8000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：2人
职位类别：工业工程师
**********
岗位职责：
1.根据工厂年度精益指标，明确所负责LSS相关指标并制定切实可行的实施计划（铜牌认证、Shopfloor认证、VSM活动、Kaizen Event改善周活动）；
2.及时完成并跟进所负责各个部门的各项LSS指标；
3.参与工厂各部门精益生产的推进，并与各部门有效沟通LSS指标达成情况，以达到LSS推进计划的有效实施；
4.与团队一起开展LSS相关培训（Shopfloor培训，A3问题解决培训、VSM价值流培训、IE工具和方法培训）
5.与团队一起促进厂内“改善提案活动”的展开；
6.与生产相关负责人有效沟通，了解生产制程，能及时发现改善点并参与改善；
7.针对生产一线员工提出的改善，及时进行确认并采取有效的激励措施；
8.定期更新并制作系统相关报告及文件；
9.与各部门有些沟通，及时完成日常其它工作事项。
任职要求：
1. 本科学历，机械、IE、管理等相关专业；
2. 3年及以上工作经验；
3.具备一定的制造业经验；
4.良好的沟通及团队协作能力；
5.语言表达和沟通协调能力佳；具有一定的英语读写能力；
6.熟练应用office等办公软件。

工作地址：
江苏无锡
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
Sr mgr supply chain sewing experience
捷普科技(上海)有限公司
五险一金年底双薪免费班车
**********
福利:
五险一金
年底双薪
免费班车
**********
职位月薪：20000-40000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：1人
职位类别：供应链经理/主管
**********
This position have to have sewing experience

JOB SUMMARY
Responsible for the materials strategy in assigned region. Includes responsibility for situational analysis, Strategy development & guidance in implementation for the functional disciplines of supply chain development, risk mitigation, negotiation, procurement, planning & inventory control. These strategies should support the individual customer’s needs & be complementary to overall Supply Chain Management (SCM) goals.
ESSENTIAL DUTIES AND RESPONSIBILITIES
？ Staff the functional area of responsibility to meet divisional objectives.
？ Establish & communicate expectations of each position in terms of mission & goals.
？ Identify individual & team strengths & development needs on an ongoing basis.
？ Create &/or validate training curriculum in functional area of responsibility.
？ Coach & mentor team members to deliver excellence to every customer.
？ Assist with creation and management of succession plans.
？ Establish clear measurable goals & objectives to determine individual & team results (ie SCM metrics, knowledge of operational roles & responsibilities, personal development goals).
？ Solicit ongoing feedback from Business Unit Management, Commodity Management, Materials Management, Development Engineering, Quality Assurance, peers & team on team's contribution(s).
？ Influence and assist in performing team member performance evaluations.
？ Drive individuals and team to continuously improve key strategic metrics and achievement of divisional goals and objectives.
？ Influence and assist with ensuring employee recognition and rewards are managed fairly and consistently.
？ Provide a communication forum for the exchange of ideas and information.
？ Know and understand both the corporation’s and division’s strategic direction.
？ Analyze customer’s needs & develop appropriate materials strategy that is in alignment with organizational and divisional goals.
？ Examine current supply chain models & identify & implement best proactive business to meet needs.
？ Develop supply base/chain models that meet the needs of High, Mid & Low Volume Market business. .
？ Identify creative ways to reduce cost by streamlining processes & systems (ie modification of responsibilities, elimination of non-value-added processes or complete reengineering of processes & systems).
？ Define, develop & make effective use of cost analysis and risk mitigation tools.
？ Provide feedback to staff on cost & cost trends.
？ Develop senior level supply base relationships in region that will ensure assurance of supply, preferred terms set, pricing & etc.
？ Develop & implement initiatives for region that will enhance cash cycle & improve margin.
？ Communicate customer’s needs to Commodity Management, NPI Supply Chain Project Managers, Operations Materials Management to ensure that Jabil provides supply chain solutions that foster success.
？ Implement and/or participate in Design Incentive Agreement negotiation and ensure DIA registration is on time.
？ Ensure the required system tools (SAP, Windchill, JIS, In-Control tools, etc.) are utilized effectively within the team.
？ Focus on achievement of SCM financial & operational goals.
？ Serve as escalation point for customer issues that cannot be resolved in a timely manner within the functional area.
？ Adhere to safety & health rules & regulations and company security policy.

MANAGEMENT & SUPERVISORY RESPONSIBILITIES
Jd, Sr Manager Supply Chain Page 2 of 4
？ Typically reports to Management. Direct supervisor job title(s) typically include: Director Supply Chain Development
？ Job is directly responsible for managing other employees (e.g., hiring/termination and/or pay decisions, performance management).

JOB QUALIFICATIONS KNOWLEDGE REQUIREMENTS
？ Ability to read, analyze, interpret and communicate regarding common scientific and/or technical journals, financial reports, and legal documents.
？ Ability to respond to common inquiries or complaints from customers, regulatory agencies, or members of the business community.
？ Ability to effectively present information to Business Unit Management, Customer, and other members of the Jabil materials community. Advanced PC skills, including training and knowledge of Jabil’s software packages.
？ Ability to calculate figures and amounts such as discounts, interest, commissions, proportions, percentages, area, circumference, and volume.
？ Ability to apply concepts of basic algebra and geometry.
？ Ability to solve practical problems and deal with a variety of concrete variables in situations where only limited standardization exists.
？ Ability to interpret a variety of instructions furnished in written, oral, diagram, or schedule form. EDUCATION & EXPERIENCE REQUIREMENTS
？ Bachelor’s degree in Business Administration, Materials Logistics Mgmt or related discipline
？ Ten years related experience in negotiation, cost reduction activities & materials planning
？ Domestic & international travel is required

工作地址：
无锡新区高浪东路高新区综合保税区
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
C&B Specialist
捷普科技(上海)有限公司
五险一金年底双薪包吃带薪年假免费班车
**********
福利:
五险一金
年底双薪
包吃
带薪年假
免费班车
**********
职位月薪：6001-8000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：薪酬福利专员/助理
**********
Responsibility 
1.Collection of payroll related document, maintain and file it to ensure its integrality 
2.Calculate the monthly salary accurately, issue the payment on time
3.Provide the accurately and effective labor cost report and the related payroll data 
4.Support to Management: such as providing various labors cost budget reference solution as well as some payroll figures. 

Requirements 
1.Bachelor degree with 1-3 years of HR related experiences, especially in C&amp;B part. 
2.Good computer skills and data analysis, especially for Excel skill 
3.Excellent English skills, both of oral and written English 
4.Good communication skills and team spirit
工作地址：
无锡市江苏无锡新区高浪东路高新区综合保税区，J9，J10地块
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
Planning Manager
捷普科技(上海)有限公司
五险一金绩效奖金加班补助免费班车定期体检节日福利补充医疗保险
**********
福利:
五险一金
绩效奖金
加班补助
免费班车
定期体检
节日福利
补充医疗保险
**********
职位月薪：15000-23000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：5-10年
最低学历：大专
招聘人数：1人
职位类别：生产计划
**********
岗位职责：
1. Reconcile the Master Production Schedule to customer Purchase Order coverage weekly to ensure that Jabil is not exposed over and above Purchase Order coverage. 2. Assess production schedules, revise when necessary, optimize run quantities, minimize changeovers and achieve 100% on-time delivery. 
3 Update and maintain the Master Production Schedule as changes are identified in order for the MRP to reflect accurate, up-to-date information. 
4 Conduct regular cycle count at the production floor to maximizes inventory accuracy and minimizes disruption on the floor. Ensure Production declare their attrition of materials regularly
5 Resolve all excess issues to Production and investigate the reasons for excess issues and create systems to minimize recurrence. 
6 Co-ordinate and drive to conclusion all material purges to eliminate escapees. Investigate any unsuccessful purge and institute long-term preventive action. 
7 Co-ordinate and resolve outstanding materials issues with the buyers to eliminate surprises material shortages.
工作地址：
高新区综合保税区（新区海关，原出口加工区，J9,J10地块（一号门）
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
成本控制/成本分析
捷普科技(上海)有限公司
14薪五险一金年底双薪加班补助包吃包住免费班车节日福利
**********
福利:
14薪
五险一金
年底双薪
加班补助
包吃
包住
免费班车
节日福利
**********
职位月薪：4000-7000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：3人
职位类别：成本会计
**********
岗位职责：
负责生产计划的成本控制、成本分析
任职要求：
1、3年以上成本分析相关工作经验；
2、熟悉生产运营成本管控；
3、能够适应一定强度的加班。
工作地址：
薛点路9号
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
供应链管理
捷普科技(上海)有限公司
14薪年底双薪五险一金包住餐补弹性工作带薪年假免费班车
**********
福利:
14薪
年底双薪
五险一金
包住
餐补
弹性工作
带薪年假
免费班车
**********
职位月薪：10001-15000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：5-10年
最低学历：大专
招聘人数：1人
职位类别：供应链经理/主管
**********
职位职责：
1.接收订单并release到厂内，
2.追踪厂内生产达成状况并与客户保持紧密的工作，
3.处理出货异常及客户端的异常处理，
4.异常及时反馈并寻求解决方案。
职位要求：
1.具备一定的生产计划和企划能力
2.有SAP/ERP使用经验，数据敏感度高，
3.英文四级以上，擅长沟通交流。

工作地址：
薛点路9号
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
Global commodity manager - Mechanicals
捷普科技(上海)有限公司
五险一金年底双薪免费班车
**********
福利:
五险一金
年底双薪
免费班车
**********
职位月薪：20000-40000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：1人
职位类别：采购经理/主管
**********
Job Summary
To effectively develop and lead a team a Global Team of Commodity Managers to ensure excellence. To drive technical excellence within the commodity Management Team by developing tools, metrics and strategies that meet the business needs. The development, implementation and measurement of a Global Business plan that fully meets the needs of our business sectors (i.e. commodity strategies, supply base development, Global infrastructure, price management etc.)

 Essential Duties & Responsibilities
SUPPLY CHAIN MANAGEMENT RESPONSIBILITIES Business Strategy and Direction:
 - Know and understand the Corporations strategic direction.
- Define, develop and implement a strategy, which contributes to the Corporate strategic direction.
- Develop an understanding of each Workcell business strategy as it pertains to Supply Chain Management and Commodity Management.
 - Provide regular updates to BUM, Materials Management, Supply Chain Management and Operations Management on execution of the strategy.
- Develop a Business plan for assigned commodities. Cost Management:
 - Identify creative ways to reduce cost by streamlining processes and systems (i.e. modification of responsibilities or consolidation of tasks, elimination of non-value-added processes or complete re-engineering of processes and systems).

TECHNICAL MANAGEMENT RESPONSIBILITIES
 - Demonstrate expertise in assigned commodities and fully competent in all aspects of supply chain Management including commodities not directly assigned.
 - Develop a Global Commodity infrastructure that supports Jabil’s business and growth plans. - Develop, monitor and implement Global Commodity Strategies
 - Develop the supply base to exceed the goals and objectives of Jabil and the supply chain management team
 - Market Jabil’s Supply Chain Management expertise both internally and externally
- Define, Develop and implement supply chain models to meet Jabil’s business needs.
 - Analyze market conditions and implement supply chain strategies to assure supply and price competitiveness
 - Be a leader in ensuring that Jabil maximizes our purchase leverage for the best total cost of ownership
 - Influence Jabil’s current and potential new customers
- Develop effective relationships with Business Unit Management to ensure that Supply Chain Management is fully involved with new business opportunities.
- Drive continuous improvement through trend reporting analysis and metrics management.
- Assure that procedures and work instructions are efficient and not redundant.
- Offer new, innovative and entrepreneurial ideas and suggestions for improvement. Identify and implement new practices and processes that are “best in field.”
 - Demonstrate a commitment to customer service; anticipate, meet, and exceed expectations by solving problems quickly and effectively; making customer issues a priority. - Periodically “get down in the trenches” to rehabilitate troubled plants. Foster a “back to basics” mentality during these times. Lead by example; “Walk the talk.”
 - Establish new measurement systems if/where appropriate.
 - Ensure the efficient and timely exchange of knowledge and information within the Jabil Corporation to ensure best practices are shared throughout the Jabil organization.
- Ensure 100% adherence to all company policies and procedures (i.e. Health and Safety, Quality).
 - Ensure all sensitive and confidential information is handled appropriately.

Education & Experience Requirements
- Bachelor’s degree in Business Administration, Materials Logistics Management, or related discipline.
 - Five years related experience in electronics manufacturing, materials management, negotiation, cost reduction activities and materials planning.
- Domestic and international travel is required.
- Or a combination of education, experience and/or training.

工作地址：
无锡市无锡新区综合保税区J9 J10地块
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
Line Manager
捷普科技(上海)有限公司
五险一金年底双薪加班补助包吃带薪年假补充医疗保险免费班车
**********
福利:
五险一金
年底双薪
加班补助
包吃
带薪年假
补充医疗保险
免费班车
**********
职位月薪：10001-15000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：1人
职位类别：生产项目经理/主管
**********
JOB DESCRIPTION:
1 .Maximize product throughput, quality and efficiency 
2.Track production and ensure all deadlines and schedules are met
3.Maximize employee output, dedication and job satisfaction. 
4.Maintain a clean and neat working area. Jabil Circuit (Wuxi) Ltd. Printed Document is Reference Only Jabil Proprietary and Confidential 
5.Work overtime as required. 
6.Perform other duties as directed by Manufacturing Manager.

PREREQUISITES:
1. 3 years experience in volume production, enclosure assemblies and a degree in engineering or science discipline.
2 .3 years of supervisory experience.
3. Good understanding and fluency speaking in English.
4 .Able to manage a minimum of three manufacturing lines on a 3 shifts operation.
5 .Preferable industry experience:

工作地址：
无锡新区综合保税区J9，J10地块
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
培训专员
捷普科技(上海)有限公司
14薪五险一金年底双薪加班补助包吃包住免费班车节日福利
**********
福利:
14薪
五险一金
年底双薪
加班补助
包吃
包住
免费班车
节日福利
**********
职位月薪：4000-6000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：培训专员/助理
**********
职位描述
1、负责员工入职培训；
2、负责培训活动组织；
3、负责其他培训相关工作
职位要求：
1. 大专以上学历，愿意长期从事培训工作；
2. 一年以上培训相关工作经验；
3. 个人表达能力、沟通能力佳，执行能力强

工作地址：
薛点路9号
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
Sr. Planner
捷普科技(上海)有限公司
**********
福利:
**********
职位月薪：7000-14000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：1人
职位类别：生产计划
**********
SUMMARY
Manage all planning activities for the dedicated assigned workcell and mentor the Production Planners and Document Coordinators in the workcell.
 ESSENTIAL DUTIES AND RESPONSIBILITIES include the following.  Other duties may be assigned.
 · Ensure 100% on-time delivery.
· Establish build readiness.
· Maintain efficiency of capacity and customer sizing.
· Maintain accurate revenue forecasting.
· Maintain material control and liability.
· Develop Master Production Schedule (MPS) and load into Jabil’s ERP system, including Purchase Order (PO) coverage.
· Reconcile the MPS to customer PO coverage weekly to ensure that Jabil is not exposed over and above customer PO coverage or other authorized customer demand.
· Ensure the MPS is always 100% accurate and achievable.
· Achieve and maintain 95% MPS goal.
· Own production planning, BOM and document control with or without additional support.
· Analyze material and capacity requirements and communicate constraints to the Workcell and customer based on accurate customer demand.
· Maintain the workcell’s capacity planning model; drive resolution on uneven capacity utilization that keeps Jabil focused on the customer but efficiently utilizing manufacturing resources.
· Meet daily with the Workcell and manufacturing team to assess production schedules, (adjust as necessary based on production results) optimize run quantities, and minimize changeovers to help achieve 100% on time delivery.
· Maintain the customers’ latest contract on file at all times and be familiar with the terms and conditions of the contract regarding customer liability of material planning and production scheduling. This includes the liability window for Jabil material purchase order placement, purchase price for components, and liability for any in-house materials (purchased and manufactured).
· Be the workcell’s “expert” on all planning activities by supporting the Production Planner goal of never starting to build product without having a valid PO, adequate material quantities, and accurate BOM and an accurate routing.
· Lead the Workcell on the creation of Bills of Material (BOMs) and routings that allows accurate tracking of WIP assemblies and accurate inventory movement transactions.
· End-of Life (EOL) management should include chairing a meeting 30 days prior to the last planned build date to create tactics to support the EOL strategy. The Master Planner would own the build schedule, corrections and resolution of MPS to customer demand, planned tactics on deadlines for assemblies out of the various work areas on the floor, deadline for last shipment, and support plan for potential RMAs.
· Manage Jabil purge process for internal Workcell purges.
· Adhere to all safety and health rules and regulations associated with this position and as directed by supervisor.
· Comply and follow all procedures within the company security policy.
 MINIMUM REQUIREMENTS
High School Diploma or equivalent required and two years of planning experience; Bachelor’s degree preferred.  APICS certification and Supervisor experience also preferred.  Thorough knowledge of MRP, lead times for specific component types, internal run rates, test development lead times, machine programming lead times and complete understanding of the chronological sequence of events that must occur in order to build a product.
  LANGUAGE SKILLS
Advanced PC skills, including training and knowledge of Jabil’s software packages. Ability to read and interpret documents such as safety rules, operating and maintenance instructions, and procedure manuals. Ability to write routine reports and correspondence. Ability to speak effectively before groups of customers or employees of organization.
 MATHEMATICAL SKILLS
Ability to add, subtract, multiply, and divide in all units of measure, using whole numbers, common fractions, and decimals. Ability to compute rate, ratio, and percent and to draw and interpret bar graphs.
 
工作地址：
近海关
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
测试维修技术员（RF/射频分析方向）
捷普科技(上海)有限公司
五险一金年底双薪绩效奖金带薪年假定期体检免费班车
**********
福利:
五险一金
年底双薪
绩效奖金
带薪年假
定期体检
免费班车
**********
职位月薪：6001-8000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：中专
招聘人数：1人
职位类别：电子工程师/技术员
**********
岗位职责：
1. 能够熟练使用仪器进行PCB板维修
2. 有RF/射频方面分析能力的优先考虑（射频板维修经验）
任职要求：
1. 中专以上
2. 吃苦耐劳，学习能力强
3. 有团队合作精神
4. 能够接受12小时倒班制
工作地址：
新吴区综合保税区J9J10地块 捷普电子（无锡）有限公司
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
LSS精益工程师
捷普科技(上海)有限公司
14薪每年多次调薪五险一金年底双薪包吃包住免费班车员工旅游
**********
福利:
14薪
每年多次调薪
五险一金
年底双薪
包吃
包住
免费班车
员工旅游
**********
职位月薪：6001-8000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：工业工程师
**********
岗位职责：
 1.根据工厂年度精益指标，明确所负责LSS相关指标并制定切实可行的实施计划（铜牌认证、Shopfloor认证、VSM活动、Kaizen Event改善周活动）；
2.及时完成并跟进所负责各个部门的各项LSS指标；
3.参与工厂各部门精益生产的推进，并与各部门有效沟通LSS指标达成情况，以达到LSS推进计划的有效实施；
4.与团队一起开展LSS相关培训（Shopfloor培训，A3问题解决培训、VSM价值流培训、IE工具和方法培训）
5.与团队一起促进厂内“改善提案活动”的展开；
6.与生产相关负责人有效沟通，了解生产制程，能及时发现改善点并参与改善；
7.针对生产一线员工提出的改善，及时进行确认并采取有效的激励措施；
8.定期更新并制作系统相关报告及文件；
9.与各部门有些沟通，及时完成日常其它工作事项。
任职要求：
1. 本科学历，机械、IE、管理等相关专业；
2. 1年及以上工作经验；
3.具备一定的制造业经验；
4.良好的沟通及团队协作能力；
5.语言表达和沟通协调能力佳；具有一定的英语读写能力；
6.熟练应用office等办公软件。
工作地址：
无锡高新区薛典路9号
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
Inventory Analyst(库存分析)
捷普科技(上海)有限公司
五险一金年底双薪加班补助包吃带薪年假免费班车补充医疗保险
**********
福利:
五险一金
年底双薪
加班补助
包吃
带薪年假
免费班车
补充医疗保险
**********
职位月薪：4001-6000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：3人
职位类别：其他
**********
Job Description：
1. Obtains, organizes, analyzes, and interprets data related to WIP processes, and provides high-quality responses to all WIP related issues.
2.Identifies root cause of errors and implements process improvements as preventative measures, when necessary. 
3.Continuously focuses on improving the Inventory Control operations.
4.Ensures WIP personnel accurately perform necessary tasks.
5.Ensures all transactions are completely posted and processed accurately.
6.Responsible for and maintains the accuracy of all materials within the assigned areas. Identifies accurate materials and replenishment quantities necessary for Manufacturing processes. Ensures manufacturing areas are replenished with the materials when required.
7.Accurately backflushes material in the ERP system.
8.Complete material disposition report forms.
Job Requirements：
1.College degree is a must ,but should be accompanied with related warehouse/material
experience, and bachelor’s degree in related field (Supply Chain, Materials Management, or an equivalent) is strongly recommended.
2.1-2 years of related experience; and/or 1-2 years of experience within or relating to Inventory Control.
3.Good verbal and written communication in English.
4.Good Business analysis ability.
5.Ability to make process development continually.
6.Administration & Mathematics.
7.Investigative thought process.
8.High attention to detail.
9.Experience with the current ERP system is preferable.

工作地址：
无锡新区综合保税区J9，J10地块
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
测试/电子技术员
捷普科技(上海)有限公司
五险一金年底双薪绩效奖金带薪年假定期体检免费班车
**********
福利:
五险一金
年底双薪
绩效奖金
带薪年假
定期体检
免费班车
**********
职位月薪：3500-6500元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：电子工程师/技术员
**********
岗位职责：
1. 熟悉PCBA测试、维修流程，能够独立完成Debug

任职要求：
1. 制造业经验优先考虑
2. 能够接受倒班
工作地址：
新吴区综合保税区J9J10地块 捷普电子（无锡）有限公司
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
成本会计
捷普科技(上海)有限公司
免费班车
**********
福利:
免费班车
**********
职位月薪：4001-6000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：成本会计
**********
1)Performs individual cost runs and ensure that costs and their accounting are correct.
2)Do Inventory report and inventory aging report
3)Analyzes cost variance such as PPVs,buckflush,reval,subcontracting,RMAs,MRB,RTVs and scrap.
4)Calculate CILO and do posting.
5)Reviews reports on excesses and obsoletes monthly and quarterly.
6)PII(I/C) report to Corporate team
7)Physically audits the warehouse based on cycle counts.
8)Financial report explaination on costing portion

Qualifications and required skills:
1)Bachelor of accounting.
2)At least 2+years accounting experience.
3)Chasing Costing work experience.
4)Good in written and spoken English.
5)Possess a high level of integrity and positive working attitude.
6)Good communication with external and internal contact

工作地址：
近海关
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
数据统计专员
捷普科技(上海)有限公司
**********
福利:
**********
职位月薪：4001-6000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：统计员
**********
1. 2017年应届毕业生， 本科学历
2. 较强的数据分析及管理能力，对数字敏感
3. 英语书面能力强

公司福利：
五险一金，年终奖，季度奖，班车，宿舍，免费工作餐

工作地址：
无锡薛典路9号
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
AR 应收会计
捷普科技(上海)有限公司
五险一金包吃带薪年假免费班车
**********
福利:
五险一金
包吃
带薪年假
免费班车
**********
职位月薪：3500-4500元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：会计/会计师
**********
岗位职责：
1)Prepare and analysis AR aging report weekly and monthly. Make sure the due AR can be received.
2)Be responsible for daily receipts including domestic and overseas business.
3)VAT invoice issuance.
4)Bank voucher s preparation.
5)Reconciliation with customer.
6)Chasing AR to meet AR overdue target.
7)AR month end closing
8)Prepare AR reports

任职要求：
1)Bachelor of accounting.
2)At least 1+years accounting experience.
3)Chasing AR work experience.
4)Good in written and spoken English.
5)Possess a high level of integrity and positive working attitude.
6)Good communication with external and internal customers.

工作地址：
无锡新区高浪东路高新区综合保税区（海关，原出口加工区）J9, J10地块 捷普电子（无锡）有限公司
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
Java & WEB前端软件开发工程师
捷普科技(上海)有限公司
五险一金年底双薪包吃补充医疗保险定期体检免费班车
**********
福利:
五险一金
年底双薪
包吃
补充医疗保险
定期体检
免费班车
**********
职位月薪：7000-10000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：软件工程师
**********
*工作地點: Wuxi
*需求人數: 2員
*條件:
1. 資訊(工科)背景
2. 工作經驗 1.5年以上(助工程師等級) 專業

技術要求:
* 熟練使用c# 或Java.
* 熟悉XML、HTML/XHTML、CSS、Javascript、AJAX、JSON等Web页面技术.
*具有MySQL/MSSQL等关系型数据库开发经验.
*PTC Thingworx開發經驗尤佳
工作地址：
无锡新区高浪东路高新区综合保税区（海关，原出口加工区）J9, J10地块 捷普电子（无锡）有限公司 1号门
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
EIT 管培生
捷普科技(上海)有限公司
五险一金年底双薪加班补助带薪年假免费班车
**********
福利:
五险一金
年底双薪
加班补助
带薪年假
免费班车
**********
职位月薪：2001-4000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：无经验
最低学历：本科
招聘人数：1人
职位类别：测试/可靠性工程师
**********
岗位职责：
负责3C产品的研发，制造或Support等相关工作；
 任职要求：
2017/2018年应届本科/研究生，CET4(必须）；
机械/自动化/模具/电子/人力资源/英语/会计/工业工程等相关专业；
学习能力及沟通能力佳；

工作地址：
薛典路9号
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
税务会计（tax accountant）
捷普科技(上海)有限公司
五险一金年底双薪免费班车
**********
福利:
五险一金
年底双薪
免费班车
**********
职位月薪：6001-8000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：2人
职位类别：税务专员/助理
**********
1)      VAT invoice issuance.
2)      Familiar with export tax rebates process.
3)      Know the knowledge of SAFE foreign exchange receipts and payments
4)      Assist audit firm calculate income tax.
5)      Ensure that the tax calendar is current, the work product is timely and meets the needs of the end user
 Qualifications and required skills:
1)      Bachelor of accounting.
2)      At least 3+years tax experience.
3)      Familiar with the final settlement process and notes
4)      Good in written and spoken English.
5)      Possess a high level of integrity and positive working attitude.
6)      Good communication with external and internal customers.
  工作地址：
无锡新区高浪东路高新区综合保税区
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
生产计划
捷普科技(上海)有限公司
五险一金年底双薪加班补助包吃包住免费班车员工旅游节日福利
**********
福利:
五险一金
年底双薪
加班补助
包吃
包住
免费班车
员工旅游
节日福利
**********
职位月薪：4600-8000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：5-10年
最低学历：不限
招聘人数：10人
职位类别：生产计划
**********
要求：
1.具备一定的生产计划经验，电子机械，工业工程专业尤佳；


职位描述：
1.负责两周生产计划，日计划安排，工令开立，结案生产排配跟进及前期产能规划；
2.每日跟进生产进度及异常处理，根据MPC制定各项目标进行日常control;
3.依据生产计划展开新案资源规划及进度跟踪。

工作地址：
薛点路9号
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
MRO Buyer
捷普科技(上海)有限公司
五险一金年底双薪包吃补充医疗保险定期体检免费班车
**********
福利:
五险一金
年底双薪
包吃
补充医疗保险
定期体检
免费班车
**********
职位月薪：7000-10000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：1人
职位类别：采购专员/助理
**********
JOB SUMMARY

Responsible for managing MRP to ensure that materials supply equals demand and to support optimization of overall cost of
materials.

ESSENTIAL DUTIES AND RESPONSIBILITIES

· Develop supply base and Supply Chain strategies that are unique to customer or for Business Unit Strategic materials.
· Support customer’s business needs using standard process where possible and customized solutions where necessary.
Collaborate with Purchasing manager and SCM to determine the best approach to meet the customer needs. Influence
customer’s supply chain strategies to leverage those of Jabil.
· Communicate Jabil expectations to the suppliers. Conduct supplier audit / visits, certifications, and performance reviews to
develop and continuously improve supply base. Obtain feedback from Materials Planners on suppliers’ delivery, quality, and
service performance.
· Support, execute, and provide inputs to improve Jabil SCM initiatives and strategies.
· Quote new and existing materials. Work with Materials Quotation Analyst if applicable. Frequently re-quote and negotiate to
capitalize on cost reduction opportunities.
· Make sourcing decisions based on overall cost and benefit including price, duty, freight, flexibility, service, performance,
quality, and terms & conditions.
· Negotiate terms and conditions that protect the best interest of Jabil and its customers. Negotiate liability terms, special stocking
arrangements, and other agreements that are outside of standard Jabil terms and conditions.
· Ensure execution of Jabil pricing and terms & conditions agreements such as World Wide Purchasing Agreements that are
negotiated and agreed to by Jabil.
· Improve sourcing options by working with Jabil’s internal resources and customers to add Jabil preferred and/or strategic
suppliers to customer’s Approved Manufacturer’s List (AML).
· Analyze and project component purchase prices that accurately reflect the inventory value for a financial period in Standard
Costing process.
· Provide input to determine Quoted Cost to the Customer that is competitive yet maximizes the amount of Materials Price
Variance (MPV).
· Continuously optimize MPV by reducing the cost of materials and by limiting unfavorable PPV/MPV. Work with BUM to
obtain customers’ authorization for additional expenses such as premiums on materials or freight and tooling charges incurred
on customers’ behalf.
· Collaborate with Materials Planners and monitor, track, and provide feedback on suppliers’ performance for continuous
improvement.
· Work with Materials Planners to ensure that suppliers support overall business needs of Jabil.
· Adhere to all safety and health rules and regulations associated with this position and as directed by supervisor.
· Comply and follow all procedures within the company security policy.
· May perform other duties and responsibilities as assigned.


MANAGEMENT & SUPERVISORY RESPONSIBILITIES

· Typically reports to Management. Direct supervisor job title(s) typically include: Purchasing Manager
· Job is NOT directly responsible for managing other employees (e.g., hiring/termination and/or pay decisions, performance
management).




JOB QUALIFICATIONS
KNOWLEDGE REQUIREMENTS

· Ability to calculate figures and amounts such as discounts, interest, commissions, proportions, percentages, area, circumference,
and volume.
· Ability to apply concepts of basic algebra and geometry.
· Ability to effectively present information and respond to questions from groups of managers, clients, customers, and the general
public.
· Ability to define problems, collect data, establish facts, and draw valid conclusions.
· Ability to operate a personal computer including using a Windows based operating system and related software.
· Advanced PC skills, including training and knowledge of Jabil’s software packages.
· Ability to write simple correspondence. Read and understand visual aid.
· Ability to apply common sense understanding to carry out simple one- or two-step instructions.
· Ability to deal with standardized situations with only occasional or no variables.
· Ability to read and comprehend simple instructions, short correspondence, and memos.
· Ability to add, subtract, multiply, and divide in all units of measure, using whole numbers, common fractions, and decimals.
· Ability to compute rate, ratio, and percent and to draw and interpret graphs.


EDUCATION & EXPERIENCE REQUIREMENTS

· HS Diploma or equivalent
· Three to five years related experience.
· Bachelor's degree and certification by related professional organizations (such as APICS and NAPM) is preferred.
· Or an equivalent combination of education, training or experience.

工作地址：
高浪东路，近海关
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
薪酬专员（C&B)
捷普科技(上海)有限公司
五险一金年底双薪绩效奖金加班补助包吃包住带薪年假节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
加班补助
包吃
包住
带薪年假
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：1人
职位类别：薪酬福利专员/助理
**********
1. 3年以上大型制造相关薪酬工作经验；
2. 熟练使用SAP系统及office办公软件；
3. CET4及以上；
4. 性格开朗，逻辑思维清晰，并具有良好的数据处理能力；

工作地址：
薛点路9号
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
美资500强 账务经理/Ops Finance Manager
捷普科技(上海)有限公司
**********
福利:
**********
职位月薪：20001-30000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：1人
职位类别：财务经理
**********
Job Summary
The Operation Finance Manager is to provide accurate and timely reporting of actual monthly costing, weekly indicator and forecasts. Explain the components that represent the difference between actual and forecast. Work with the Business Unit and Workcell managers to provide accurate analytical tools and reviews, provide detailed analysis to drive operations improvement Monitor operation dashboard & KPI by providing solution for improvement.

Essential Duties & Responsibilities
 - Know and understand the campus strategic directions
- Define, develop and implement a Finance strategy, which contributes to the campus strategic directions
- Develop an understanding of the workcell business strategy as it pertains to Finance
- Provide regular updates to Plant Controller and Finance VP
Cost Management:
- Identify creative ways to reduce cost by streamlining processes and systems (eg. modification of responsibilities or consolidation of tasks, elimination of non-value-added processes or complete re-engineering of processes and systems)
- Utilize tools available to monitor departmental cost and cost trends, striving continuously to improve value
- Provide feedback to peers (BUMs, WCMs, Functional Managers (FMs)) on cost and cost trends
Forecast Development and Accuracy:
- Prepare timely forecasts for the department
- Compare forward forecast results to historical actual results for trend assessment and analysis

 Education & Experience Requirements
- Bachelor’s Degree in Accounting or Finance
- CPA Certificate or MBA degree is preferred
- Must have 5 years of diversified experience in Forecasting, Cost Accounting, A/P, A/R, and Corporate Reporting in a Standard cost-manufacturing environment
- At least 2 years experience in a supervisory or management role within Finance department
- Or a combination of education, experience and/or training
工作地址：
薛典路9号
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
EHS工程师
捷普科技(上海)有限公司
14薪五险一金年底双薪加班补助包吃包住免费班车节日福利
**********
福利:
14薪
五险一金
年底双薪
加班补助
包吃
包住
免费班车
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：环境/健康/安全工程师
**********
1.EHS工作经验4年以上；
2.熟悉现行EHS相关政策和法律法规；
3.大专以上学历；


工作地址：
薛点路9号
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
仓库管理师
捷普科技(上海)有限公司
**********
福利:
**********
职位月薪：4001-6000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：中专
招聘人数：2人
职位类别：仓库/物料管理员
**********
职位描述：
1. 负责仓库收发料、物料上架及SAP系统帐务作业；
2. 有较强的库存分析能力，确保帐，卡，物一致；
3. 根据生产计划工单，完成成品、半成品工单发料作业；
4. 辅助出货完成相关包装及装卸货作业。

岗位要求：
1.大专以上学历；
2.有叉车作业证及相关仓储物流工作经验；
3.熟练SAP系统或ERP系统；
4.有良好的团队协作能力、耐压能力好、有责任心；
5.能适应倒班工作。
工作地址：
薛典路9号
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
夹治具设计
捷普科技(上海)有限公司
**********
福利:
**********
职位月薪：6001-8000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：3人
职位类别：夹具工程师
**********
任职要求：
1.机械工程类专业，大专3年以上相关工作经验；
2.对常用夹具结构有清楚认识,熟悉夹、治具结构佳；
3.对公差与配合有充分理论功底,有足够的误差分析能力；
4.熟练运用UG和PRO-E等绘图软件；
5.熟练运用办公软件(Word/Excell/PPT);
6.熟悉3C数码产品CNC类工序，组装类工序，表面类工序治具设计者优先；
7.有非标自动化设备设计经验者优先.
工作地址：
无锡市薛典路9号
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
夹治具设计工程师
捷普科技(上海)有限公司
五险一金年底双薪带薪年假免费班车
**********
福利:
五险一金
年底双薪
带薪年假
免费班车
**********
职位月薪：6001-8000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：2人
职位类别：夹具工程师
**********
岗位职责：
1、负责夹、治具的设计
2、参与产品前期治具方案检讨
3、参与治具回厂确认及现场验证
4、后期治具的检讨和优化
任职要求：
1、熟悉Pore等设计软件‘
2、大专以上学历
3、机械工程类相关专业
4、熟悉治具设计开发流程，拥有设计管理两年以上工作经验
5、熟悉最新现代化气动夹、治具功能和应用

工作地址：
薛典路9号
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
产品组装工程师
捷普科技(上海)有限公司
**********
福利:
**********
职位月薪：6001-8000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：3人
职位类别：机械结构工程师
**********
岗位要求：
机械相关专业，大专以上学历

岗位职责：
1.DFM制作检讨,组装生产工艺制定，熟悉镭雕，镭焊，点胶，小组装，自动化等相关制程；
2. DOE规划、跟进、报告汇总；
3.组装段图面确认，检讨发行，组件规格检讨确认；
4.机构小零件开发与规格确认
工作地址：
无锡新区薛典路9号
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
员工关系或培训专员
捷普科技(上海)有限公司
五险一金年底双薪加班补助包吃包住免费班车员工旅游节日福利
**********
福利:
五险一金
年底双薪
加班补助
包吃
包住
免费班车
员工旅游
节日福利
**********
职位月薪：3500-4500元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：员工关系/企业文化/工会
**********
1、制造型企业工作背景，一年以上工作经验；
2、擅长文案编辑，有活动策划经验；
3、逻辑清晰，表达能力佳；
4、熟悉PPT和Excel使用。

工作地址：
薛点路9号
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
Admin Specialist
捷普科技(上海)有限公司
五险一金绩效奖金加班补助补充医疗保险定期体检免费班车节日福利带薪年假
**********
福利:
五险一金
绩效奖金
加班补助
补充医疗保险
定期体检
免费班车
节日福利
带薪年假
**********
职位月薪：4001-6000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：行政专员/助理
**********
岗位职责：To ensure satisfied service of food, transportation; 
To manage the dorm area if any; 
To be in responsible of keeping sample meal with clinic nurse; 
To ensure the 5S of cafeteria, locker area, etc. 
To lower down the admin cost quarterly base. 
To distribute and recycle ESD smoker and shoes.

任职要求：
A college/associate’s degree or above in HRM or its equivalent 
1 years or above related working experience 
Good English skills, CET-4 is a must for English level 
Good PC skills in Word, Excel, Outlook.
工作地址：
无锡新区高浪东路高新区综合保税区（海关，原出口加工区）J9，J10地块
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
Tooling program manager - Metal&Plastic
捷普科技(上海)有限公司
五险一金年底双薪免费班车
**********
福利:
五险一金
年底双薪
免费班车
**********
职位月薪：15000-30000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：1人
职位类别：模具工程师
**********
JOB SUMMARY

The Regional Tooling Program Manager (RTPM) will successfully manage the engineering, technical and budgetary aspects of tool development projects, from inception to end of life. The RTPM will develop forecast and budgets.

ESSENTIAL DUTIES AND RESPONSIBILITIES

? Develop and manage a staff of engineers capable of meeting the tool creation demand for said region. This person will liaise with customers, vendors and all internal functional groups associated with tool development projects.
? Further, the RTPM will also be required execute the role of Tooling Project Engineer by using established processes and procedures, and is responsible for design input and approval, fabrication and qualification of plastic injection molds and sheet metal dies by outside vendors.
? Familiarity with all aspects of a tooling shop and a thorough understanding of the operation of all the machine tools and other tools used in the process of fabricating molds and dies is also necessary. The RTPM should have a thorough understanding of the tool making process, from start to finish, and have experience managing this process.
? Manage quoting, new project entry and maintenance in Jabil Projects, monthly time tracking and monthly program forecasting.
? Monitor team member support and identify key factors that can be improved.
? Identify individual and team strengths and development needs on an ongoing basis.
? Provide ongoing feedback to designated managers, supervisors, peers and team members on team member’s contribution to the team. Express pride in staff and encourage them to feel good about their accomplishments. Mentor where needed.
? Drive individuals and the team to continuously improve in key operational metrics and the achievement of the organizational goals.
? Provide communication forum for the exchange of ideas and information with the team.
? Ask questions; encourage input from team members.
? Know and understand the business strategic direction.
? Develop and communicate an understanding of the business strategy as it pertains to the team.
? Provide regular updates to appropriate managers.
? Identify creative ways to reduce cost by streamlining processes and systems (i.e. modification of responsibilities or consolidation of tasks, elimination of non-value added processes, or complete re-engineering of processes and systems).
? Utilize tools to monitor project cost and cost trends, striving continuously to improve value.
? Provide feedback to peers and appropriate managers.
? Work independently to develop quotations and schedules for development programs of tools.
? Work concurrently with Jabil CAD Services, Business Unit Management, Manufacturing, Test, Purchasing, and Quality departments throughout the design phase of a program.   Strive to provide a design that not only meets the customer’s criteria, Jabil’s manufacturability requirements, but is also of high quality, and cost effective.
? Be familiar with all aspects of molded plastic and sheet metal parts and be knowledgeable in troubleshooting mold issues and die issues.
? Estimate part cost for sheet metal and injection molded parts.
? Assess the suitability of a particular mold or die shop to the needs of a particular job.
? Stay abreast of the latest technology and techniques to provide input and approval of designs that are competitive and cost effective.
? Exercise good judgment within defined procedures and practices to determine appropriate action.
? May perform other duties and responsibilities as assigned.

JOB QUALIFICATIONS
KNOWLEDGE REQUIREMENTS

? Ability to effectively present information and respond to questions from groups of managers, clients, customers, and the general public.
? Ability to define problems, collect data, establish facts, and draw valid conclusions.
? Ability to operate a personal computer including using a Windows based operating system and related software.
? Advanced PC skills, including training and knowledge of Jabil’s software packages.
? Ability to write simple correspondence.  Read and understand visual aid.
? Ability to apply common sense understanding to carry out simple one- or two-step instructions.
? Ability to deal with standardized situations with only occasional or no variables.
? Ability to read and comprehend simple instructions, short correspondence, and memos.
? Ability to add, subtract, multiply, and divide in all units of measure, using whole numbers, common fractions, and decimals.
? Ability to compute rate, ratio, and percent and to draw and interpret graphs.
EDUCATION & EXPERIENCE REQUIREMENTS

? Accredited Four year Tool and Die apprenticeship program;
? Plus a minimum of 5 years experience on the bench and have achieved the status of Class A journeyman.
? Demonstrated experience in managing people and budgets.
? Possess project management skills including scheduling and resource allocation forecasting.
? Or an equivalent combination of education, training or experience.

工作地址：
无锡市无锡新区综合保税区J9 J10地块
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
初级计划
捷普科技(上海)有限公司
五险一金年底双薪带薪年假免费班车
**********
福利:
五险一金
年底双薪
带薪年假
免费班车
**********
职位月薪：2001-4000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：物流专员/助理
**********
岗位职责：
1、负责部门生产计划安排；
2、依据计划展开固化与进度跟踪&检讨；
3、系统中维护物料清单的准确性；
任职要求：
1、大专以上学历；
2、1年以上生产计划工作经验；
3、能够配合加班者优先。

工作地址：
无锡市无锡新区综合保税区J9 J10地块
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
部门助理
捷普科技(上海)有限公司
五险一金年底双薪带薪年假免费班车
**********
福利:
五险一金
年底双薪
带薪年假
免费班车
**********
职位月薪：3500-4000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：助理/秘书/文员
**********
岗位职责：
1. 处理日常行政工作；
2. 负责接待客户；
3. 上级交代的其他事务等；

任职要求：
1.英语专业，大专及以上学历；
2.乐观开朗，吃苦耐劳
工作地址：
无锡新区薛典路9号
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
CSR 英语客户服务专员
捷普科技(上海)有限公司
**********
福利:
**********
职位月薪：5000-10000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：1人
职位类别：客户服务专员/助理
**********
JOB SUMMARY

Jabil’s Customer Satisfaction Coordinator is responsible for the coordination of various customer satisfaction related projects that support Jabil’s business needs. Position reports to the Communications Manager and works closely with members of the Business Development, Operations, and Quality teams.

ESSENTIAL DUTIES AND RESPONSIBILITIES

Maintains an up-to-date, comprehensive database of Jabil’s customer contacts and their customer satisfaction and loyalty scores
Analyzes customer loyalty survey data (prepares reports, graphs, presentations) and tracks actions taken to address customer issues
Ensures on-time quarterly customer satisfaction score collection and quarterly customer review meeting summaries from all business units, reviews scores and translations, flags errors, works with Risk & Assurance on completing score audits, and prepares quarterly communications to the Quality and executives
Prepares site specific presentations listing the quarterly customer satisfaction results and shares them with all sites; manages workcell customer satisfaction recognition 
Develops customer satisfaction content for Jabil’s internal website including customer satisfaction and loyalty scores, customer award information and testimonials, and best practices 
Supports the development of a customer satisfaction dashboard for measuring and reporting drivers for customer loyalty, identifying areas that require improvements, tracking corrective actions, and reporting status to senior leaders; later, manages the database
Supports development of the customer service workshops and training programs 
Provides additional customer satisfaction related support as needed
May perform other duties and responsibilities as assigned.

MANAGEMENT & SUPERVISORY RESPONSIBILITIES

Typically reports to Management.  Direct supervisor job title(s) typically include: Communications Manager
Job is NOT directly responsible for managing other employees (e.g., hiring/termination and/or pay decisions, performance management).   


JOB QUALIFICATIONS
KNOWLEDGE REQUIREMENTS

Required Qualifications:
Ability to manage multiple projects in a fast-paced environment
Interpersonal skills to work with a wide range of individuals/groups from culturally diverse audience
Extreme proficiency in Microsoft Office (specializing in Word, PowerPoint, Excel, Access). 
Experience in quantitative market research, including use of online survey and analytical tools.
Candidate must possess superior organizational skills, problem solve and meet deadlines.
Key Competencies:
Ability to read, analyze, interpret and communicate in English 
Detail-oriented, creative thinking, and exceptional analytical skills 
Critical thinking and problem solving skills
Self-motivated and self-directed
Planning and organizing
Communication skills, teamwork and adaptability
Required Project Coordination Skills:
Plan and schedule project timelines
Track project deliverables 
Regularly monitor and report on progress of the project to stakeholders
Project evaluations and assessment of results
Ability to effectively present information and respond to questions from groups of managers, clients, customers, and the general public.
Ability to define problems, collect data, establish facts, and draw valid conclusions. 
Ability to operate a personal computer including using a Windows based operating system and related software. 
Advanced PC skills, including training and knowledge of Jabil’s software packages. 
Ability to write simple correspondence.  Read and understand visual aid. 
Ability to apply common sense understanding to carry out simple one- or two-step instructions.  
Ability to deal with standardized situations with only occasional or no variables.
Ability to read and comprehend simple instructions, short correspondence, and memos.  
Ability to add, subtract, multiply, and divide in all units of measure, using whole numbers, common fractions, and decimals.  
Ability to compute rate, ratio, and percent and to draw and interpret graphs.

EDUCATION & EXPERIENCE REQUIREMENTS

Bachelor’s degree in marketing or statistics.
1-3 years of experience in the relative field.
Or an equivalent combination of education, training or experience.
工作地址：
近海关
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
税务经理/TAX Manager
捷普科技(上海)有限公司
**********
福利:
**********
职位月薪：20001-30000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：10年以上
最低学历：本科
招聘人数：1人
职位类别：税务经理/主管
**********
Job Summary
Responsible for the management of the day to day tax accounting, and tax accounting functions of the Tax Department.

Essential Duties & Responsibilities
- Review the timely and accurate preparation of all federal and state income tax returns, including estimated tax payments; specified other tax returns; and Current and Deferred income tax provision calculations under FASB 109; and journal entries
- Manage all federal, state and consult as to international tax audits
- Manage the integration of acquisitions and green field plants including the merger and restructuring in local jurisdictions
- Prioritize the multiple responsibilities of the Tax Department
- Keep up to date on changes in tax law, administrative and judicial decisions, and other relevant items through current technical reading
- May manage lower level professional accountants or clerks through subordinate supervisor

Education & Experience Requirements
- Master's Degree in Accounting or Taxation OR CPA certificate
- Plus 10 years of tax-related experience, including at least 3 years experience in a supervisory or management role within a Tax department
- Strong analytical expertise, a solid tax technical background, excellent written and oral communication skills and the ability to handle multiple tasks simultaneously in a fast paced work environment
工作地址：
薛典路9号
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
测试工程师
捷普科技(上海)有限公司
年底双薪绩效奖金加班补助包住
**********
福利:
年底双薪
绩效奖金
加班补助
包住
**********
职位月薪：6001-8000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：5-10年
最低学历：大专
招聘人数：5人
职位类别：测试/可靠性工程师
**********
大专以上，测试或机械相关专业；
5年左右相关LCM/OLED测试经验；
沟通协调能力佳；
熟悉OLED产品新产品导入；

工作地址：
薛典路9号
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
Logistics Coordinator - 物流专员
捷普科技(上海)有限公司
五险一金年底双薪加班补助包吃带薪年假补充医疗保险免费班车
**********
福利:
五险一金
年底双薪
加班补助
包吃
带薪年假
补充医疗保险
免费班车
**********
职位月薪：4000-7000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：物流专员/助理
**********
SUMMARY
Responsible for process development, training and support of logistics systems, tools and processes

ESSENTIAL DUTIES AND RESPONSIBILITIES include the following.  Other duties may be assigned.

？Serve as the functional expert for all logistics related systems and tools.
？Support other users in typical and advanced questions that require research to solve.
？Coordinate and facilitate training for the plant in terms of new hires, new functionality, and upgrades.
？Track and communicate all changes/enhancements to existing planning systems including upgrades to current systems.
？Understand standardized departmental functions, processes, procedures, and systems.
？Evaluate business systems and troubleshoot areas of concern.
？Introduce and support corporate provided/designed tools.
？Evaluate and monitor the current processes and tools to determine their ability to meet the department’s business needs.
？Provide support for the plant for all system tools and related issues.
？Identify opportunities for enhancements.
？Detail requirements for enhancements with respect to a Business Development Request submitted by a functional area.
？Provide initial functional specifications.
？Assist in the testing, validation, and rollout processes for new functionality, to include plant level training.
？Define and/or document business processes, policies and work instructions.
？Adhere to all safety and health rules and regulations associated with this position and as directed by supervisor.
？Comply and follow all procedures within the company security policy.
？Assist Customs Broker with clearance issues
？Review commercial invoices to ensure proper information is documented
？Approve inbound/outbound freight invoices for the Florida campus
？End of month allocation of freight charges
？Nightly support for delayed inbound shipments
？Constant contact with carriers and customs broker to ensure proper service.
？Overall problem solving for inbound/outbound shipments to support production
？Approval of service level for all International carriers based on Buyers lead time and response.
？Adhere to all safety and health rules and regulations associated with this position and as directed by supervisor.
？Comply and follow all procedures within the company security policy.

MINIMUM REQUIREMENTS
High School diploma required and three years related experience and/or training; Bachelor's degree preferred; Certification by related professional organizations is preferred.

LANGUAGE SKILLS
Advanced PC skills, including training and knowledge of Jabil’s software packages.  Ability to read and interpret documents such as safety rules, operating and maintenance instructions, and procedure manuals.  Ability to write routine reports and correspondence. Ability to speak effectively before groups of customers or employees of organization.

MATHEMATICAL SKILLS
Ability to calculate figures and amounts such as discounts, interest, commissions, proportions, percentages, area, circumference, and volume.  Ability to apply concepts of basic algebra and geometry.

REASONING ABILITY
Ability to apply common sense understanding to carry out instructions furnished in written, oral, or diagram form.  Ability to deal with problems involving several concrete variables in standardized situations.

工作地址：
无锡市新区出口加工区J9,J10地块
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
销售经理
北京仁桥心脑血管病防治研究所
五险一金年底双薪绩效奖金加班补助餐补通讯补贴定期体检节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
加班补助
餐补
通讯补贴
定期体检
节日福利
**********
职位月薪：6000-10000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：3人
职位类别：销售代表
**********
工作职责：
1、负责我司产品（预适应训练仪）在泰州地区的经销商、医院、养老院客户的开发拓展
2、根据公司的销售计划完成指定地区的销售任务以及回款任务
3、根据公司的营销方案，协调客户，配合完成营销方案的执行
4、组织或协助举办区域市场内经销商订货会议
5、建立并保持客户关系
6、负责区域市场内客户的订货、出货、换货、退货服务，并通过与公司各部门沟通及时处理和解决客户的问题，树立客户对公司及产品的信心
7、收集市场反馈，并根据反馈结果对公司的产品、服务提出合理性建议
任职要求：
1、有医疗相关行业或者面向中高端客户的销售经验
2、有丰富的销售经验和团队管理经验
3、责任心强，敬业，吃苦耐劳，进取心以及团队精神
4、具有一定文档编写能力
5、全职或者兼职均可

待遇：面议

工作地址：
江苏，上海
**********
北京仁桥心脑血管病防治研究所
公司规模：
20-99人
公司性质：
民营
公司行业：
医药/生物工程
公司地址：
中国医药城
**********
人事专员
捷普科技(上海)有限公司
五险一金年底双薪带薪年假免费班车
**********
福利:
五险一金
年底双薪
带薪年假
免费班车
**********
职位月薪：2001-4000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：无经验
最低学历：本科
招聘人数：1人
职位类别：员工关系/企业文化/工会
**********
该职位针对2016,2017,2018届毕业生。
To make a draft of job advertisement and choose proper recruiting channel to fill out the requested vacancies upon the detailed requirements related to company development and mentioned by hiring managers.

2) To conduct the first screening of resumes and arrange interviews.

3) To send thanks letter to unsuccessful candidates and communicate with selected candidates for their health check up and other commencement arrangement.

4) To be fully responsible for indirect labor’s recruiting issues, including contacting related job agencies to find suitable candidates and set up long-term relationship for back up use of indirect labor.

5) To handle related new hire employment issues and related resignation issues related to labor bureau.

6) To conduct daily routine work of staffing function.

7) To complete and update HR reports related to recruiting, staffing.

8) To provide full support and assistance to HR dept when there is any requirement

GENERAL REQUIREMENT

1) Basic computer skill, PC usage in office software, Word, Excel and Outlook, etc.

2) Good team player and high responsibility;

3) Good relationship with all kinds of recruiting channels and labor bureau;

4) Can work under pressure and overtime

5) Ability to read, write and interpret documents, rules and policies and report skills for routine mails and correspondence;

工作地址：
无锡市无锡新区综合保税区J9 J10地块
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
IT技术员Helpdesk（美资500强）
捷普科技(上海)有限公司
加班补助
**********
福利:
加班补助
**********
职位月薪：3000-4500元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：Helpdesk
**********
岗位职责：
公司的IT系统的管理，服务器管理，公司相关IT工作的对应，公司软件硬件问题的对应及其处理，公司的相关系统的跟进。
工作内容以电话、电脑、网络维护为主，协助整个工厂。

任职资格：
具备IT技能
拥有较好的沟通能力、协调能力和团队协助能力
动手能力强，适应能力强，能接受翻班工作（不是非常频繁的翻班）
基础的英语能力即可
0~2年工作经验，可考虑应届生

以下是职位描述：
Essential Duties & Responsibilities
- Procuring and ordering any needed hardware/software requirements.
- Be present and available for major meetings to ensure equipment works properly
- Work closely with the other IT groups to provide first line technical support, ensuring assigned calls are responded to, diagnosed and resolved swiftly and effectively in line with operational level agreements and service level agreements.
- Test any new major rollout with other IT groups. This is either approve or disapprove any change that could mean downtime for Executive Staff.
- Work closely with our video conference provider to aid in the planning and support of high level video conferences
- Work using own initiative and work within a team environment.
- Maintain an up-to-date level of knowledge with regards to technology
- The role holder would be expected to develop a comprehensive knowledge of the company’s business plans and organization, including key users of technology and their needs.
- Document actions, alterations and procedures to ensure an accurate and accessible record of the current state of the system.
- Assist other members of the team when appropriate to complete tasks in the necessary timescale.
- Keep abreast of trends in technology and its application to understand current best practice, possible alternative solutions and to support problem solving.
- Manage own time to fulfil tasks efficiently, in the correct priority and to the required level of quality, within the context of the objectives supplied by manager.
- Ensure technology supports meets the customer requirements as defined in the Service Level Agreements.
- Ensure 100% adherence to all company policies and procedures (i.e. Health, Safety and Quality).
- Maintain discretion and confidentiality in all areas pertaining to data and proprietary information, whether internal to Jabil or customer specific.
- Maintain discretion and confidentiality in all areas pertaining to the IT systems.
- May perform other duties and responsibilities as assigned.

Education & Experience Requirements 岗位要求：
- 0-2 years experience in PC building, rebuilding & maintenance.
- Good communicaton, service orientented attitude, customer focus, sence of urgency, professional demeanor, time managements skills, anaytical thinker.
- All Microsoft apps/utilities.
- Provide on call support .

工作地址：
无锡市新区薛典路9号
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
人事考勤专员
捷普科技(上海)有限公司
**********
福利:
**********
职位月薪：4001-6000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：人力资源专员/助理
**********
任职要求：
本科及以上相关学历;
有至少2年以上大型制造HR考勤相关经验；
熟悉SAP系统，有较强的数据处理能力；
工作地址：
薛典路9号
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
员工活动&培训专员（2017年应届生）
捷普科技(上海)有限公司
五险一金年底双薪加班补助包吃包住免费班车员工旅游节日福利
**********
福利:
五险一金
年底双薪
加班补助
包吃
包住
免费班车
员工旅游
节日福利
**********
职位月薪：3500-4500元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：1人
职位类别：员工关系/企业文化/工会
**********
1、新闻或者汉语言文学专业；
2、擅长文案编辑，有活动策划经验；
3、逻辑清晰，表达能力佳；
4、能够独立使用PPT进行展示，使用Excel进行数据比对。
工作地址：
振发一路8号
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
c#开发工程师
捷普科技(上海)有限公司
五险一金年底双薪包吃补充医疗保险定期体检免费班车
**********
福利:
五险一金
年底双薪
包吃
补充医疗保险
定期体检
免费班车
**********
职位月薪：5000-7000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：软件工程师
**********
1. 資訊(工科)背景
2. 工作經驗 1.5年以上(助工程師等級)
專業技術要求:
3. 熟練使用c#.
4. 熟悉XML、HTML/XHTML、CSS、Javascript、AJAX、JSON等Web页面技术.
5.具有MySQL/MSSQL等关系型数据库开发经验.
6.PTC Thingworx開發經驗尤佳

工作地址：
无锡国家高新产业开发区97地块（海关出口加工区，高浪东路3号）
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
训练导师
杭州竞思教育科技有限公司
年底双薪绩效奖金全勤奖餐补定期体检员工旅游节日福利
**********
福利:
年底双薪
绩效奖金
全勤奖
餐补
定期体检
员工旅游
节日福利
**********
职位月薪：8001-10000元/月 
工作地点：无锡
发布日期：最近
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：幼教
**********
岗位职责：
1、形象气质佳，普通话标准，有耐心，动手能力强，有耐心管理顽皮好动的孩子，身体健康；
2、有教师工作经验、教育培训工作经验者优先，心理学，教育学专业类毕业优先，如：拥有一年以上青少年儿童教学或类似课后辅导托管等从业经验，能有效管理儿童、培养学生学习生活和良好习惯养成，促进学生之间融洽的相处优先考虑；
3、富有亲和力、爱心、责任心，通晓少儿心理，富有感染力。善于调动儿童学习积极性和吸引儿童注意力，具有团队合作精神和组织协调能力、良好的语言表达能力和人际沟通能力；
4、有创新意识和钻研精神，能吃苦耐劳，学习能力强；

主要职责范围：
1、负责学员的培训教育工作，让顽皮好动的孩子能静下心来训练，做好训练记录。

2、对于训练结果能够及时与训练中心负责人沟通。

3、负责与学员家长的训练结果的交流工作。

4、做好训练的记录，及相关文件的整理，做到井井有条。

5、完成上级下达的任务。

工作时间：周一周二休息，周三至周五上班时间13:30-20:00；周六周天：9:20-19:30 午休1小时

薪资福利：底薪+课时费用+续费提成+年终奖+五险+定期旅游活动         
工作地址可就近选择：
无锡市崇安区县前西街7号 竞思       
 联系人：刘老师：15355094750

工作地址：
无锡市崇安区县前西街7号 竞思
查看职位地图
**********
杭州竞思教育科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
教育/培训/院校
公司主页：
www.jingsiedu.com
公司地址：
杭州西湖区学院路131-3号三楼人力资源部（学院路与文二路交叉口）
**********
销售经理
江苏硕世生物科技股份有限公司
五险一金绩效奖金交通补助通讯补贴带薪年假弹性工作员工旅游定期体检
**********
福利:
五险一金
绩效奖金
交通补助
通讯补贴
带薪年假
弹性工作
员工旅游
定期体检
**********
职位月薪：5000-7000元/月 
工作地点：无锡
发布日期：最近
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：1人
职位类别：销售经理
**********
岗位职责： 
1.完成负责区域内的代理商寻找、洽谈及管理工作，协助代理商进行终端客户的开发。 
2.维护负责区域内的重点客户。 
3. 根据公司制定的销售计划，完成月、季度及全年的销售任务，及相应的回款任务。 
4. 积极协助公司策划产品营销推广活动，并参加公司组织的相关活动。 
5. 收集和理解市场信息及竞争者信息,维护和更新客户数据及市场材料。 
6. 接受并按时完成公司或上级领导分派的各项临时或常规性工作。 

岗位要求： 
1.三年以上相关区域医疗行业销售工作经验。 在临床妇科、检验科有资源。
2.对销售有浓厚兴趣，坚强有毅力，敢于面对挑战和压力。 
3.有较强的客户开发能力及沟通能力。
工作地址：
无锡
**********
江苏硕世生物科技股份有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
医药/生物工程
公司主页：
www.s-sbio.com
公司地址：
江苏省泰州市药城大道1号G19三楼
查看公司地图
**********
PLM系统开发
捷普科技(上海)有限公司
加班补助
**********
福利:
加班补助
**********
职位月薪：7000-12000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：软件工程师
**********
1. 1~5年工作经验，IT相关学科毕业。
2. 熟练掌握Java或C程序开发，具面向对象观念(Object-oriented).
3. 具Windchill经验更佳。

工作职责:
1. 负责PLM系统的开发(含系统设定及二次开发)。

工作地址：
无锡市无锡新区薛典路9号
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
Supplier program manager - Plastic/metal
捷普科技(上海)有限公司
五险一金年底双薪免费班车
**********
福利:
五险一金
年底双薪
免费班车
**********
职位月薪：10000-20000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：1人
职位类别：项目经理/主管
**********
SUMMARY
Operate as the General Manager of Jabil Circuit’s Custom Mechanical supply base. Drive and coordinate all of the necessary resources required for the successful launch of new products within Jabil Circuit’s Custom Mechanical supply base and be responsible for the optimum operational performance of the Custom Mechanical supply base throughout the product life cycle.
ESSENTIAL DUTIES AND RESPONSIBILITIES include the following. Other duties may be assigned.
Project / Technical Management
？ Act as single point contact to co-ordinate supply chain activities for all phases of new project introduction including quotation assist, management of DFM, quality, risk mitigation, execution, qualification and ramp.
？ Document and maintain project action log ensuring critical items are identified, prioritized and managed to ensure compliance to meet project cost, quality and timeline requirements.
？ Apply expertise and knowledge on key mechanical commodities Inc Plastics, Metals & Packaging covering materials, tooling, processing, costing and capacity calculations to ensure project success.
？ Demonstrate mechanical credibility and competence within our Business Units and as well as our Customers
？ Liaise with Global and Workcell Engineering and Quality teams to provide solutions to supplier manufacturing problems and escalations throughout product life cycle.
？ Manage execution of Engineering Change Notices (ECN) within mechanical supply chain from all perspectives, inventory, obsolescence, cost etc.
？ Comply and follow corporate Supply Chain “Materials” procedures and supply chain deliverables within “Quality” and “Design” procedures.
Assurance of Supply
？ Act as technical escalation point when supply assurance comes under threat
？ Ensure that Supplier employs best practice techniques
？ Ensure that Jabil has sufficient Machine Capacity reserved and Management Prioritization inside supplier
？ Ensure that supplier has correct manning availability and capability (Training)
？ Liaise with Tooling and / or Quality Engineers to manage day to day issues inside supplier during tool / process qualifications and start up
？ Liaise with Jabil work cells and act as communication link between BU and Supplier
？ Mitigate risk where supplier selection necessitates use of a supplier whose audit / performance shows significant deficiencies. Install in-process inspection, process audits as required.
Cost Management
？ Manages the periodic material quotation activities, assist in execution of RFQ as appropriate for the program
？ Material Management & process yield continuous improvement programs.
？ Identify creative ways to reduce cost by streamlining process and systems
？ Develop MPV generation recommendations
Process Improvements
？ Optimize and Harmonize processes to maximize yields and eliminate waste.
？ Cycle time reduction program.
？ Assembly operation efficiency improvement.
Capacity Expansion
？ Liaise with BU’s, determine future capacity requirements.
？ Oversee installation, trial and qualification of additional manufacturing lines.
Supplier Performance
？ Provide supplier performance feedback to RCM and BU.
MINIMUM REQUIREMENTS
A Bachelor’s degree in Mechanical Engineering, or an equivalent proven track record in an EMS or similar environment is required. A minimum of five years related experience is required. Experience in the custom mechanical supply chain industry
is essential, either from within the supply chain itself or from within an EMS or OEM environment. A technical background Mechanical Engineering is a plus. A solid understanding of custom mechanical manufacturing and materials management is required, as well as a proven track record in negotiation, cost reduction activities, operational and program management. Strong leadership skills are required. Domestic, regional and international travel will be required to support business needs.

工作地址：
无锡市无锡新区综合保税区J9 J10地块
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
Plastic/metal tooling program engineer
捷普科技(上海)有限公司
五险一金年底双薪免费班车
**********
福利:
五险一金
年底双薪
免费班车
**********
职位月薪：8000-16000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：1人
职位类别：模具工程师
**********
SUMMARY
Using established processes and procedures, the Tooling Project Engineer is responsible for support of the Lead Tooling Project Engineer (LTPE), as assigned, for the design, fabrication and qualification of plastic injection molds and sheet metal dies by outside vendors. The Tooling Engineer should be familiar with all aspects of a tooling shop and have a thorough understanding of the operation of all the machine tools and other tools used in the process of fabricating molds and dies. Should also have a thorough understanding of the tool making process from start to finish and have experience managing this process.
ESSENTIAL DUTIES AND RESPONSIBILITIES include the following. Other duties may be assigned.
? Publish weekly tool tracking reports
? Participation in design failure modes effects analysis (DFMA)
? Development of quotation criteria
? Establishment of tool design and build timelines in collaboration with vendor to develop plans for timely execution
? Act as technical point of contact - Customer’s, Jabil’s and Vendor’s - for tool related issues
? Review of preliminary tool designs to insure compliance with Customer and/or Jabil tooling standards, Part drawing requirements, and Manufacturing volume requirements
? Review and approval of final tool designs
? Creation of tool maintenance plan and development of spare parts proposal
? Drive progress against established timelines
? Oversee the implementation of product related engineering change orders
? Drive vendor readiness around raw material supply, secondary operations, and production jigs and fixtures
? Manage tool samples from vendor
? Evaluate first article inspection reports
? Execute tool and part approval via Jabil Production Part Approval Process (JPPAP)
? Oversee production qualification tool runs
? Work under the direction of the LTPE in order to develop quotations and schedules for development programs of tools
? Work concurrently with Jabil CAD Services, Business Unit Management, Manufacturing, Test, Purchasing, and Quality departments throughout the design phase of a program. Strive to provide a design that not only meets the customer’s criteria, Jabil’s manufacturability requirements, but is also of high quality, and cost effective.
? Be familiar with all aspects of molded plastic and sheet metal parts and be knowledgeable in troubleshooting mold issues and die issues
? Estimate part cost for sheet metal and injection molded parts
? Assess the suitability of a particular mold or die shop to the needs of a particular job
? Stay abreast of the latest technology and techniques to provide input and approval of designs that are competitive and cost effective
? Exercise good judgment within defined procedures and practices to determine appropriate action
? Adhere to all safety and health rules and regulations associated with this position and as directed by supervisor
? Comply and follow all procedures within the company employee policy
MINIMUM REQUIREMENTS
Accredited Four year Tool and Die apprenticeship program; and a minimum of five years experience on the bench and have achieved the status of Class A journeyman. Possess project management skills including scheduling and resource allocation forecasting. Periodic travel to customer, vendor and/or Jabil sites is required - Anticipated amount of travel to be 50% ; Must be willing to travel internationally

工作地址：
无锡市无锡新区综合保税区J9 J10地块
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
Manufacturing Engineer工程师
捷普科技(上海)有限公司
五险一金年底双薪带薪年假免费班车
**********
福利:
五险一金
年底双薪
带薪年假
免费班车
**********
职位月薪：4001-6000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：中专
招聘人数：5人
职位类别：夹具工程师
**********
岗位职责：
-主要负责CNC类，组装类，表面类，组装类治具设计;
-参与产品前期治具方案检讨，评估；
-参与治具回厂确认及现场验证，治具问题点的处理；
-量产治具检讨及优化；
任职要求：
-机械工程类专业毕业,本科,两年以上相关工作经验或大专三年以上相关工作经验；
-对常用夹具结构有清楚认识,熟悉夹、治具结构佳；
-对公差与配合有充分理论功底,有足够的误差分析能力；
-熟悉运用UG和PRO-E等绘图软件；
-熟练运用办公软件(Word/Excell/PPT);
-有强烈的团队合作意识，服从上级的安排管理

工作地址：
薛典路9号
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
BA需求分析工程师 - ERP方向
捷普科技(上海)有限公司
五险一金年底双薪包吃补充医疗保险定期体检免费班车
**********
福利:
五险一金
年底双薪
包吃
补充医疗保险
定期体检
免费班车
**********
职位月薪：7000-10000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：1人
职位类别：需求工程师
**********
主要开发技能：C#、ASP.NET、SQL Server，HTML、JavaScript
Office visio

要求：
计算机信息系统或商务信息管理相关专业和至少3年的项目管理经验。
对商业需求有一定的认知和分析能力。
有生产控制系统/制造系统相关经验。
熟练使用Office visio和Microsoft project
工作能力突出并拥有良好的上下级沟通能力。
熟悉关系型数据库开发方式。
能够读懂业务需求和识别变化因素,有创意和创造力。
熟悉服务器、网络、终端、操作系统等
流利的英语听说读写能力。
能独立解决问题。
优秀的故障诊断技术。
能应付工作压力。
较强的组织能力。
拥有与客户沟通的技巧。
擅长用报告形式总结工作。
优秀的语言表达能力。

欢迎有意从程序开发转型到需求分析的技术型IT踊跃投递！

工作地址：
薛典路9号
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
市场业务
上海名媛医疗美容门诊部有限公司
五险一金年底双薪绩效奖金包住带薪年假
**********
福利:
五险一金
年底双薪
绩效奖金
包住
带薪年假
**********
职位月薪：15001-20000元/月 
工作地点：无锡
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：中专
招聘人数：5人
职位类别：销售代表
**********
职位名称：市场销售经理
岗位要求：
1.有医疗美容专业线渠道销售经验者优先；
2.对江浙沪美容行业专业线市场熟悉者；
3.不怕吃苦，勤奋好学，有团队精神者；
4.有3年以上美容行业工作经验，具有一定的开发合作店工作经验；
5、心态好、能下到市场踏实务实，一切以结果为导向的有志之士。
联系电话：18018396618袁
工作地址：
江苏无锡 梁溪区世茂首府天域景园23号1704
查看职位地图
**********
上海名媛医疗美容门诊部有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医疗/护理/美容/保健/卫生服务
公司主页：
www.royallife.cc
公司地址：
上海市杨浦区佳木斯路353号白玉兰广场A楼一至三层
**********
PD（CNC/成型/抛光/喷漆/镭焊/冲压）
捷普科技(上海)有限公司
**********
福利:
**********
职位月薪：6001-8000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：5人
职位类别：机械结构工程师
**********
CNC制程开发：    
1、大专及其以上学历，至少3年以上CNC制程开发经验（熟悉Apple   iphone，iPad等开发经验者优先）:    
2、能独立完成DFM/DOE/Flowchart等的相关评估和制定；    
3、能通过mail的方式和Apple客户进行技术沟通（英语听/说/读/写能力强者优先）；  
4、能熟练使用PRO/E,UG,AUTOCAD，PPT    
5、能独立设计夹治具，具有编程，刀具设计能力  
成型制程开发：   
1.   熟悉塑胶件新产品开发流程（产品开发或者模具开发均可看看）（insert molding)  
2.   具热压成型经验，了解热压成型材料(硅胶/橡胶/等等)，了解热压成型模具设计    
3.   CET-4及以上，有很强的英语听/说/读写能力    
4.   大专及其以上学历  
抛光制程开发：    
1、大专及其以上学历，3年以上抛光打磨相关制程产品开发经验（有Apple产品开发经验者优先）    
2、英文听说读写能力强；    
3.   能熟练使用3D绘图软件PRO/E or UG； 
喷漆制程开发：    
1、大专及其以上学历，3年以上喷漆制程产品开发经验（有Apple产品开发经验者优先）    
2、英文听说读写能力强；    
3.   能熟练使用3D绘图软件PRO/E or UG；
镭焊制程开发：    
1、大专及其以上学历，至少有3年以上镭焊制程开发经验（熟悉apple   iphone开发经验者优先）:    
2、能独立完成DFM/DOE/Flowchart等的相关评估和确定；    
3、能通过mail的方式和Apple客户进行技术沟通（英语听/说/读/写能力强者优先）；  
4、能熟练使用PRO/E,UG,AUTO-CAD；   
冲压制程开发    
1、大专及其以上学历，三年以上冲压产品开发经验（有apple手机冲压件开发经验者优先）    
2、英语良好    
3、有冲压模具设计经验者优先    
4、熟练使用3D绘图软件PRO/E   or UG.    
5、良好的团队合作意识；    
6、对工作认真负责,   要有很强的责任心及执行力以及沟通协调能力.    
 

       
  
  

工作地址：
薛典路9号
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
系统管理员
捷普科技(上海)有限公司
五险一金年底双薪包吃补充医疗保险定期体检免费班车
**********
福利:
五险一金
年底双薪
包吃
补充医疗保险
定期体检
免费班车
**********
职位月薪：5000-6000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：IT技术支持/维护工程师
**********
要求：
1. 精通系统调试，信息安全网络架搭建，终端服务设备管理
2. 有数据库或软件测试/编程经验优先
3. 有大型工厂的IT经验者（ERP, MES）优先

任职资格：
1. 全日制专科以上学历，2年以上IT相关经验
2. 有基本的英语阅读能力

以下是详细版职位描述：
   Serve as the primary interface with Functional Management, Project Managers and or Program Managers for functional or site specific projects categorized as a normal change or minor project.
*          Commitment to practice and deliver Project Management processes defined within IT.
*          Provides Project Management reporting and status updates to all stakeholders and project sponsor(s).
*          Collect and summarize current project information and milestone status.
*          Coordinate the efforts of other functional team members to develop a project plan for functional related tasks.
*          Drive and or complete functional tasks to completion in accordance with the project schedule.
*          Identify and communicate any risk associated with tasks and the overall project plan.
*          Identifies potential problem areas within the project plan.  Identify and implements alternative solutions to minimize risks.
*         Complete a Post-Implementation Reviews for functional and site projects.
*          Identify best cost solutions for processes and tasks related to the functional area and to support the efficiency of the project.
*          Participate in the exchange of ideas and information within the department and with other Jabil facilities to ensure best practices are shared throughout the company.
*          Drive continuous improvement through trend reporting analysis and metrics management
*          Demonstrate a commitment to customer service; anticipate, meet and exceed expectations by solving problems quickly and effectively; making customer issues a priority.
*          Confer with reporting manager and/or  project manager on complex or unusual situations
*          Ensure 100% adherence to all company policies and procedures (i.e. EHS, Quality, Security, Change Management etc)
*          Maintain discretion and confidentiality in all areas pertaining to data and proprietary information, whether internal to Jabil or customer specific
*          Maintain discretion and confidentiality in all areas pertaining to the IT systems
*          Understand and embrace the business and IT strategic direction
*          Adhere to all safety and health rules and regulations associated with this position and as directed by supervisor.
*          Comply and follow all procedures within the company security policy.
工作地址：
薛典路
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
2017/2018届本科毕业生
捷普科技(上海)有限公司
年底双薪绩效奖金加班补助包住
**********
福利:
年底双薪
绩效奖金
加班补助
包住
**********
职位月薪：2001-4000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：无经验
最低学历：本科
招聘人数：1人
职位类别：助理/秘书/文员
**********
岗位职责：
负责跟进欧美客户用餐及派车事宜；
负责部门相关Report及翻译相关文件；
负责跟催设备进厂进度；
 任职要求：
本科，CET6（必须）；
英语，文秘，行政等相关专业；
可配合公司加班；
工作地址：
综合保税区
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
机械设计工程师（非标自动化）
捷普科技(上海)有限公司
**********
福利:
**********
职位月薪：8001-10000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：7人
职位类别：机械设计师
**********
1. 大专及其以上学历，至少3年以上非标自动化设计经验；
2. 熟悉产线自动化设备设计及评估，有点胶机，自动上料机，清洗机等设备设计经验优先
3. 熟悉CAD/Solidworks/PROE/UG等绘图软件
工作地址：
薛典路9号
查看职位地图
**********
捷普科技(上海)有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.jabil.com
公司地址：
田林路600号
**********
外贸助理
无锡南驰医疗科技有限公司
五险一金绩效奖金年终分红房补带薪年假定期体检员工旅游节日福利
**********
福利:
五险一金
绩效奖金
年终分红
房补
带薪年假
定期体检
员工旅游
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：无锡-北塘区
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：不限
招聘人数：5人
职位类别：外贸/贸易专员/助理
**********
岗位职责：
利用各种社交网站开发客户，并在阿里巴巴国际网站上回复客户邮件，与客户交流、沟通、报价，无需外出寻找客户。

任职资格：
1.较强的英语读写能力，大专及以上学历。
2.热爱销售工作。1年以上电子商务或相关互联网推广销售经验
3.有外贸经验、熟悉进出口贸易流程
4.精通阿里巴巴国际站平台操作。

公司平台：企业网站+展会+国际站阿里巴巴+毅冰和料神培训课程+外土司培训课程

工作时间：每天8小时工作制，双休，五险一金
薪资福利：底薪+提成+绩效奖励+额外奖励+团队奖金+团队活动+节假日福利+年终旅游



工作地址：
无锡市北塘区凤宾路100号（联东U谷18-502 503室）
**********
无锡南驰医疗科技有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
贸易/进出口
公司主页：
www.emsrun.com
公司地址：
无锡市北塘区凤宾路100号（联东U谷18-502 503室）
**********
注意力训练老师/幼教/小学老师/双休有课时费
杭州竞思教育科技有限公司
五险一金年底双薪绩效奖金全勤奖带薪年假定期体检员工旅游节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
全勤奖
带薪年假
定期体检
员工旅游
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：无锡-崇安区
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：4人
职位类别：小学教师
**********
任职要求：

1、形象气质佳，普通话标准，动手能力强、身体健康，有耐心管理顽皮好动的孩子，培养学生学习生活和良好习惯养成，促进学生之间融洽的相处；

2、教育学、心理学专业类毕业优先考虑，想从事教育行业的优秀应届生亦可；

3、富有亲和力、爱心、责任心，通晓少儿心理，富有感染力。善于调动儿童学习积极性和吸引儿童注意力，具有团队合作精神和组织协调能力、良好的语言表达能力和人际沟通能力；

4、有创新意识和钻研精神，能吃苦耐劳，学习能力强；

主要职责范围：

1、负责学员的培训教育工作，让顽皮好动的孩子能静下心来训练，做好训练记录。

2、对于训练结果能够及时与训练中心负责人沟通。

3、协助负责人做好训练的记录及相关文件的整理，做到井井有条。

4、完成上级下达的任务。

工作时间：周一周二休息两天，周三--周五：13:30-20:00；周六周天：9:30-19:30

工作地点可自行选择：三阳广场中心、滨湖中心。
薪资福利：底薪+课时费用+续费提成+年终奖+五险+定期旅游活动
晋升渠道：助教老师-教育培训老师-中心主任-区域监管
   工作地址：
无锡市崇安区县前西街7号
**********
杭州竞思教育科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
教育/培训/院校
公司主页：
www.jingsiedu.com
公司地址：
杭州西湖区学院路131-3号三楼人力资源部（学院路与文二路交叉口）
**********
SEO/推广优化/平台运营/竞价
无锡南驰医疗科技有限公司
五险一金绩效奖金年终分红带薪年假员工旅游
**********
福利:
五险一金
绩效奖金
年终分红
带薪年假
员工旅游
**********
职位月薪：4001-6000元/月 
工作地点：无锡-北塘区
发布日期：最近
工作性质：全职
工作经验：1-3年
最低学历：不限
招聘人数：1人
职位类别：SEO/SEM
**********
一、岗位职责:
1.阿里巴巴国际站平台运营与管理；
2.关键词搜集、筛选、分类、组合标题；
3.产品的发布与优化，建立新品详情页模板；
4.P4P直通车账户的管理、操作与维护；
5.数据分析,每天记录店铺运营数据， 每周、每月定期对数据进行分析，问题诊断与总结，制定调整方案；


二、任职资格:  
1、喜欢互联网营销、网络推广，对电子商务岗位有兴趣；
2、会简单操作office文档，会使用Photoshop,AI,Coreldraw,ID等工具的优先
3、大专以上，性别不限。电子商务、市场营销、外语等相关专业优先；
4、认真、勤奋、学习能力强，具有较强的团队合作精神，责任心强，有良好的文字沟通能力。
5、熟悉电子商务平台的营销、运营和管理规则。
6、有工作经验者优先。
双休，五险一金，带薪年假，欢迎有志之士加入我们！
邮箱：2853502575@qq.com
工作地址
无锡市北塘区凤宾路100号（联东U谷18-502 503室）


工作地址：
无锡市北塘区凤宾路100号（联东U谷18-502 503室）
**********
无锡南驰医疗科技有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
贸易/进出口
公司主页：
www.emsrun.com
公司地址：
无锡市北塘区凤宾路100号（联东U谷18-502 503室）
**********
外贸专员
无锡南驰医疗科技有限公司
五险一金绩效奖金年终分红房补带薪年假定期体检员工旅游节日福利
**********
福利:
五险一金
绩效奖金
年终分红
房补
带薪年假
定期体检
员工旅游
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：无锡-北塘区
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：不限
招聘人数：5人
职位类别：外贸/贸易专员/助理
**********
岗位职责：
1.、利用公司提供的渠道（阿里巴巴等）或自己寻找的网络平台进行推广，通过EMAIL等方式寻找海外客户进行沟通交流，整理和回复询盘并做好后期跟进工作；
2、保持与客户良好的沟通，维护好老客户关系的同时，借助行业平台开发新客户，负责产品国外市场的销售；
3、负责与客户的谈判,协助客户完成项目付款；
4、收集业务信息，掌握市场动态，及时向领导汇报行情；
5、协助做好售后的服务工作。

任职资格：
1、为人正直，品行端正，责任心强，工作态度佳。耐得住寂寞，守得到订单。
2、大专以上学历，英语4级及以上且可以用英语完成基本日常和商务交流，国际贸易、商务英语类相关专业。
3、有一年以上出口操作经验，独立取得过订单者优先。

公司平台：企业网站+展会+国际站阿里巴巴+毅冰和料神培训课程

工作时间：每天8小时工作制，双休，五险一金
薪资福利：底薪+提成+绩效奖励+额外奖励+团队奖金+团队活动+节假日福利+年终旅游

这里做好了销售可以做主管
这里做好了主管可以做经理
这里做好了经理可以做合伙人
是的，这里是南驰医疗！

地址：无锡市北塘区联东U谷18栋502 503
联系方式：15852839208 顾女士
邮箱：2853502575@qq.com

工作地址：
无锡市北塘区凤宾路100号（联东U谷18-502 503室）
**********
无锡南驰医疗科技有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
贸易/进出口
公司主页：
www.emsrun.com
公司地址：
无锡市北塘区凤宾路100号（联东U谷18-502 503室）
**********
网络推广、SEO推广优化
无锡南驰医疗科技有限公司
五险一金绩效奖金带薪年假定期体检员工旅游
**********
福利:
五险一金
绩效奖金
带薪年假
定期体检
员工旅游
**********
职位月薪：4001-6000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：不限
招聘人数：2人
职位类别：SEO/SEM
**********
一、岗位职责:
1.阿里巴巴国际站平台运营与管理；
2.关键词搜集、筛选、分类、组合标题；
3.产品的发布与优化，建立新品详情页模板；
4.P4P直通车账户的管理、操作与维护；
5.数据分析,每天记录店铺运营数据， 每周、每月定期对数据进行分析，问题诊断与总结，制定调整方案；


二、任职资格:  
1、喜欢互联网营销、网络推广，对电子商务岗位有兴趣；
2、会简单操作office文档，会使用Photoshop,AI,Coreldraw,ID等工具的优先
3、中专以上，性别不限。电子商务、市场营销、外语等相关专业优先；
4、认真、勤奋、学习能力强，具有较强的团队合作精神，责任心强，有良好的文字沟通能力。
5、熟悉电子商务平台的营销、运营和管理规则。
6、有工作经验者优先。

工作地址：
无锡市北塘区凤宾路100号（联东U谷18-502 503室）
**********
无锡南驰医疗科技有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
贸易/进出口
公司主页：
www.emsrun.com
公司地址：
无锡市北塘区凤宾路100号（联东U谷18-502 503室）
**********
江浙沪区域销售经理
江苏达实久信医疗科技有限公司
五险一金绩效奖金交通补助通讯补贴节日福利
**********
福利:
五险一金
绩效奖金
交通补助
通讯补贴
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：销售经理
**********
1、负责整个区域市场的开发，需有医疗工程或者大型医疗设备的工作经历，不能频繁更换工作，有特殊背景的可以优先考虑；
2、熟知区域内的医院动态，能单独与院长、副院长、护士长或者科室主任进行沟通交流，并达成项目；
3、本岗位待遇丰厚，但要求也高，请在投简历时仔细研读第一和第二条。非诚勿扰。
上市公司深圳达实旗下子公司江苏久信欢迎你的

工作地址：
常州市新北区汉江西路103号
**********
江苏达实久信医疗科技有限公司
公司规模：
500-999人
公司性质：
股份制企业
公司行业：
房地产/建筑/建材/工程
公司主页：
http://www.jxmed.com
公司地址：
常州市新北区汉江西路103号
查看公司地图
**********
外贸业务员（英语）
无锡南驰医疗科技有限公司
五险一金绩效奖金年终分红房补带薪年假定期体检员工旅游节日福利
**********
福利:
五险一金
绩效奖金
年终分红
房补
带薪年假
定期体检
员工旅游
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：无锡-北塘区
发布日期：最近
工作性质：全职
工作经验：1-3年
最低学历：不限
招聘人数：5人
职位类别：外贸/贸易经理/主管
**********
职位要求 ：
1.及时回复阿里询盘
2.会用Google和社交工具如Linkedin,Facebook等开发新客户
3.有效跟进客户，能和国外客户顺利的口语交流
4.熟悉外贸基本流程，能处理各种突发事件，比如客诉，客户拒付尾款等
5.领导安排的其他事宜

岗位工作内容：
1.寻找整理目标客户资源。
2.使用公司平台发布更新产品。
3.联系客户，维护客户，跟进订单。

工作时间：每天8小时工作制，双休，五险一金

薪资福利：底薪+提成+绩效奖励+额外奖励+团队奖金+团队活动+节假日福利+年终旅游+国外展会+国外客户拜访
免费培训：毅冰+料神米课+外土司培训

这里做好了销售可以做主管
这里做好了主管可以做经理
这里做好了经理可以做合伙人
是的，这里是南驰医疗！



工作地址：
无锡市北塘区凤宾路100号（联东U谷18-502 503室）
**********
无锡南驰医疗科技有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
贸易/进出口
公司主页：
www.emsrun.com
公司地址：
无锡市北塘区凤宾路100号（联东U谷18-502 503室）
**********
医疗事业合伙人
江苏宇星工贸有限公司
五险一金年底双薪绩效奖金包吃通讯补贴定期体检节日福利高温补贴
**********
福利:
五险一金
年底双薪
绩效奖金
包吃
通讯补贴
定期体检
节日福利
高温补贴
**********
职位月薪：10001-15000元/月 
工作地点：无锡
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：销售经理
**********
岗位职责：
1、公司提供广阔的平台及个人发展空间
2、公司给予充分的自由及发挥空间；
3、负责所辖区域内的客户资源的开发和维护；
任职要求：
1、对销售工作有激情，有责任心，善于动脑。
2、具备一定的市场分析及判断能力，良好的客户服务意识；
3、有责任心，能承受较大的工作压力；
4、年薪15W以上，待遇优厚，其他福可面议。

工作地址：
江苏省宜兴经济技术开发区红塔东路99号
查看职位地图
**********
江苏宇星工贸有限公司
公司规模：
500-999人
公司性质：
股份制企业
公司行业：
石油/石化/化工
公司主页：
www.yuxingcn.cn
公司地址：
江苏省宜兴经济技术开发区红塔东路99号
**********
外贸单证助理
无锡南驰医疗科技有限公司
五险一金绩效奖金年终分红房补带薪年假定期体检员工旅游节日福利
**********
福利:
五险一金
绩效奖金
年终分红
房补
带薪年假
定期体检
员工旅游
节日福利
**********
职位月薪：3500-5000元/月 
工作地点：无锡-北塘区
发布日期：最近
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：2人
职位类别：外贸/贸易专员/助理
**********
一、要求：
1.女性，25-32周岁，具有外贸行业相关工作经验（外贸业务，外贸跟单，货代等）
2.诚实守信、品德优良、吃苦耐劳、积极进取和良好的团队合作精神；良好地书面及口头表达能力和与人沟通的能力，工作认真、积极负责、 有敬业精神；熟练运用使用Office及其它办软件，熟悉中英文电子文档的制作，熟悉网络应用及电子商务。具有扎实的文档制作的基础，有一定的英语基础。
 
二、岗位要求：
按公司要求配合公司人员处理日常外贸单证工作，数据统计整理，处理邮件，联系跟进国外客户，接待客户，资料翻译整理。（有外贸业务员工作经验1-3年者优先）

工作时间：每天8小时工作制，双休，五险一金
薪资福利：底薪+提成+绩效奖励+额外奖励+团队奖金+团队活动+节假日福利+年终旅游

工作地址：
无锡市北塘区凤宾路100号（联东U谷18-502 503室）
**********
无锡南驰医疗科技有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
贸易/进出口
公司主页：
www.emsrun.com
公司地址：
无锡市北塘区凤宾路100号（联东U谷18-502 503室）
**********
业务员
江苏宇星工贸有限公司
五险一金年底双薪绩效奖金包吃高温补贴节日福利员工旅游定期体检
**********
福利:
五险一金
年底双薪
绩效奖金
包吃
高温补贴
节日福利
员工旅游
定期体检
**********
职位月薪：8001-10000元/月 
工作地点：无锡-宜兴市
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：3人
职位类别：医疗器械销售
**********
岗位职责：
1、负责公司产品的销售及推广；
2、在经理的指导下，执行公司销售政策；
3、负责所辖区域内的客户资源的开发和维护，提高公司的市场份额；
4、开拓新市场,发展新客户,增加产品销售范围；有效地将客户进行管理，根据需要拜访客户，了解客户的情况，合理安排拜访频率、正确的传递公司信息，完成及超越完成公司的销售指标；
5、及时准确的反馈市场信息；
 任职要求：
1、大专以上学历，有销售经验者优先；
2、能适应经常性出差；
3、有良好的语言表达能力、沟通协调能力和团队合作精神；
4、具备一定的市场分析及判断能力，良好的客户服务意识；
5、有责任心，能承受较大的工作压力；
6、薪资面议，待遇优厚

工作地址：
江苏省宜兴经济技术开发区红塔东路99号
查看职位地图
**********
江苏宇星工贸有限公司
公司规模：
500-999人
公司性质：
股份制企业
公司行业：
石油/石化/化工
公司主页：
www.yuxingcn.cn
公司地址：
江苏省宜兴经济技术开发区红塔东路99号
**********
招聘外贸业务员
无锡南驰医疗科技有限公司
五险一金绩效奖金年终分红房补带薪年假定期体检员工旅游节日福利
**********
福利:
五险一金
绩效奖金
年终分红
房补
带薪年假
定期体检
员工旅游
节日福利
**********
职位月薪：3000-5500元/月 
工作地点：无锡-北塘区
发布日期：最近
工作性质：全职
工作经验：1-3年
最低学历：不限
招聘人数：3人
职位类别：外贸/贸易专员/助理
**********
岗位职责：
1.体验国际交流的乐趣，开拓视野，广交五洲朋友；
2.体会从前期交流到成单，获得丰硕果实的成就感；
3、独立开发客户（包括EMAIL联系，电话联系）；
4、独立操作阿里巴巴后台，外贸直通车P4P；给客户询盘报价、议价；
5、制作合同文件，跟踪订单的交期进展，确保订单顺利完成；
6、处理客户反馈问题，配合团队成员完成团队里的事务性工作。

任职资格：
1、大专及以上学历，国际贸易、商务英语等类似专业者优先考虑；
2、有较好的英语听说读写能力，与客户交谈毫无障碍；
3、具备良好的沟通、协调和执行能力，性格稳重，有团队合作精神；
4、对外贸感兴趣及有外贸相关行业经验者优先考虑。

公司平台：企业网站+展会+国际站阿里巴巴+毅冰和料神培训课程+外土司培训课程

工作时间：每天8小时工作制，双休，五险一金
薪资福利：底薪+提成+绩效奖励+额外奖励+团队奖金+团队活动+节假日福利+年终旅游

这里做好了销售可以做主管
这里做好了主管可以做经理
这里做好了经理可以做合伙人
是的，这里是南驰医疗！


工作地址：
无锡市北塘区凤宾路100号（联东U谷18-502 503室）
**********
无锡南驰医疗科技有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
贸易/进出口
公司主页：
www.emsrun.com
公司地址：
无锡市北塘区凤宾路100号（联东U谷18-502 503室）
**********
国内销售主管
无锡祥生医疗科技股份有限公司
五险一金绩效奖金包吃带薪年假免费班车节日福利
**********
福利:
五险一金
绩效奖金
包吃
带薪年假
免费班车
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：3人
职位类别：销售主管
**********
此职位工作地点：无锡新区

岗位职责：
1.负责分管区别的市场开拓、意向挖掘工作，达成业绩指标。
2.负责执行区域内各项市场活动。
3.负责对目标客户的开发和维护，协助经销商市场开拓。
4.完成公司要求的各项培训，及其它考核指标。
5.负责本区域市场需求信息、同类产品信息、产品改进信息等收集、分析、呈报工作。

任职资格：
1、经验要求：2-3年销售经验，有医疗器械行业销售经验优先录用。
2、技能要求：独立完成区域内代理商渠道开发和维护、意向采集、跟进、签单工作；具备协助代理商完成招投标等工作的能力。
3、优先录用条件：具有超声产品销售经验两年以上，渠道资源丰富者优先。
4、学历、专业：大专及以上，专业不限。

薪资构成：基本工资+绩效考核+业绩提成+出差补贴，免费班车及工作餐，双休。

如果您肯吃苦耐劳、愿意学习、喜欢和人打交道、不怕挫折、想成就一番事业、并且通过自己的努力获得丰厚的收入，有强烈的追求高品质生活的愿望和动力，那么这对你是一个千载难逢的成就自我的良机！

工作地址：
无锡新区新辉环路9号
**********
无锡祥生医疗科技股份有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医疗设备/器械
公司主页：
www.chison.com.cn
公司地址：
无锡新区新辉环路9号
查看公司地图
**********
外贸业务员（熟悉阿里巴巴）
无锡南驰医疗科技有限公司
五险一金绩效奖金年终分红房补带薪年假定期体检员工旅游节日福利
**********
福利:
五险一金
绩效奖金
年终分红
房补
带薪年假
定期体检
员工旅游
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：无锡-北塘区
发布日期：最近
工作性质：全职
工作经验：1-3年
最低学历：不限
招聘人数：5人
职位类别：外贸/贸易专员/助理
**********
岗位职责：
1、负责客户的开发与维护,处理客户订单；
2、负责解答客户咨询,促进订单的形成；
3、与客户在线,了解客户需求，保证客户满意；
4、熟练和灵活的运用各种方式推广和宣传。
5、良好的交际能力和沟通能力。工作认真负责，有耐心，能吃苦，服从上司安排；
 任职要求：
1、英语四级以及以上；
2、国际贸易专业毕业者或有外贸经验者优先考虑；
3、具备良好的英文听、说、读、写能力，能与国外人无障碍沟通；
4、能克服国际时差，及时与客户沟通；
5、能熟悉阿里巴巴国际站的运用；
6、热爱外贸，具备良好的客户服务意识和团队合作意识，能吃苦耐劳，可塑性强者；
7、勇于挑战高薪,吃苦耐劳,勤奋务实,良好的团队合作精神。

公司平台：企业网站+展会+国际站阿里巴巴+毅冰和料神培训课程+外土司培训

五险一金，双休，法定假日带薪休假！
地址：无锡市北塘区联东U谷18栋502 503
联系方式：15852839208 顾女士
邮箱：2853502575@qq.com
工作地址：
无锡市北塘区凤宾路100号（联东U谷18-502 503室）
**********
无锡南驰医疗科技有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
贸易/进出口
公司主页：
www.emsrun.com
公司地址：
无锡市北塘区凤宾路100号（联东U谷18-502 503室）
**********
质量工程师（康复）
蝶和科技(中国)有限公司
五险一金绩效奖金交通补助餐补通讯补贴带薪年假
**********
福利:
五险一金
绩效奖金
交通补助
餐补
通讯补贴
带薪年假
**********
职位月薪：7000-10000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：1人
职位类别：质量管理/测试工程师
**********
岗位职责：
1.负责设计开发阶段的质量策划，并从质量保证的视角监督设计验证、阶段性评审及设计确认工作的落实；
2  负责零部件技术交底及首件验证工作的落实，保证项目小批量生产使用的零部件都已经过样品评估确认；
3  负责生产转移过程涉及的质量策划及试产验证工作；
4  负责无锡康复项目日常质量控制工作，包括但不限于策划并实施及执行进货检验规范、过程控制、成品检验规范等；
5  负责组织不合格品的处理，跟进不合格处理进度、纠正、预防措施的落实，并提出改进建议，制定纠正预防措施方案；
6  负责和实施及售后服务部门系统性的监视上市产品的质量表现，驱动在设计、制造、实施和维保环节的持续改进；
7  负责无锡工厂的文控管理工作，及时将项目技术文件包括但不限于图纸、PSP、设计变更上传SVN，保证现场使用的三级文件处于受控状态，收发记录清晰、可追溯；
8  参与质量体系内审、外审的实施工作。


 职位要求：
1  机电一体化、电气工程及自动化、机械工程、电子科学与技术等相关专业专科（含）以上学历
2  具有基础测量能力和识图能力，能够独立完成理解和阅读技术文件包括机械、电路图纸，了解各类物料的测试方法和测量设备；
3  三年以上产品质量保证相关工作经验，具有项目质量管理及ISO 13485内审证者优先考虑；
4  具有独立推进和解决问题的能力；
5  性格开朗、团队意识强、沟通能力强、对待工作积极主动、认真负责。

工作地址：
菱湖大道200号G8栋
**********
蝶和科技(中国)有限公司
公司规模：
500-999人
公司性质：
外商独资
公司行业：
医疗设备/器械
公司主页：
null
公司地址：
北京市丰台区丰茂路汉威国际广场6号楼7层
**********
会计经理
无锡祥生医疗科技股份有限公司
**********
福利:
**********
职位月薪：10001-15000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：1人
职位类别：财务分析经理/主管
**********
任职资格：
1、财务管理相关专业本科及以上专业；本科学历至少7年以上工作经验
2、具备良好的组织协调与沟通能力
3、良好的成本控制意识和决算能力
4、在资本运作、税务规划、成本控制等方面有丰富的操作经验
5、良好的职业道德与操守
6、具备较强的综合管理、团队协作能力和职业敏感度。
岗位职责： 
1、完善财务管控体系，包括但不限于会计核算、成本分析、税务筹划及处理、成本及费用控制、财务分析、财务报表及管理报告。
2、进行高效的资金管理及完善运作体系。
3、配合ERP实施运行，及时准确收集财务信息，为管理层决策提供及时有效的数据支持。

工作地址：
无锡新区新辉环路9号
**********
无锡祥生医疗科技股份有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医疗设备/器械
公司主页：
www.chison.com.cn
公司地址：
无锡新区新辉环路9号
查看公司地图
**********
人力资源专员
无锡安之卓医疗机器人有限公司
创业公司包吃免费班车不加班五险一金年底双薪节日福利
**********
福利:
创业公司
包吃
免费班车
不加班
五险一金
年底双薪
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：无锡-惠山区
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：2人
职位类别：人力资源经理
**********
岗位职责：
1、曾就职于科技型公司，有非标结构设计人才渠道及软件开发人才渠道者优先；
2、统筹规划人力资源开发及战略管理，制定人力资源规划；
3、开发并完善各区域人力资源管理体系和总务后勤管理体系，研究、设计人事、行政管理模式（包含招聘、绩效、培训、薪酬、员工发展和行政后勤等体系的全面建设），制订和完善行政人事管理制度；
4、负责部门团队管理，熟知各类招聘渠道，擅长各类中高级人才的甄别和选拔，完善公司人才储备和梯队建设；
5、构建和逐步完善人事共享平台，在薪酬福利、员工关系等方面推进，负责公司行政后勤建设规划的制定，为企业的正常运作和发展提供支持。
6、设计公司组织结构和岗位编制，最大限度地开发人力资源，为实现公司经营发展战略目标提供人力保障。
 7、本区域内业务人员绩效考核制度制定、跟踪、分析、反馈。
任职资格：
1.本科及以上学历
2.人力资源相关专业优先，取得人力资源管理师证书优先
3.一年以上行政及人力资源相关工作经验
4.有极强的责任心，做事公平公正，刚正不阿
5.性格开朗、做事积极主动、踏实，有较强的沟通能力及语言表达能力；
6.具有团队合作精神，学习能力强，熟练操作office办公软件；


工作地址：
无锡惠山经济开发区锦惠路10号
**********
无锡安之卓医疗机器人有限公司
公司规模：
100-499人
公司性质：
合资
公司行业：
医药/生物工程
公司地址：
无锡惠山经济开发区锦惠路10号
查看公司地图
**********
设备调试
无锡安之卓医疗机器人有限公司
每年多次调薪五险一金包吃免费班车
**********
福利:
每年多次调薪
五险一金
包吃
免费班车
**********
职位月薪：4001-6000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：1人
职位类别：机械维修/保养
**********
任职要求：
1.有非标设备调试经验3-5年
2.能看懂电气图纸、机械调试
3.能适应出差者优先
工作地址：
无锡惠山经济开发区锦惠路10号
查看职位地图
**********
无锡安之卓医疗机器人有限公司
公司规模：
100-499人
公司性质：
合资
公司行业：
医药/生物工程
公司地址：
无锡惠山经济开发区锦惠路10号
**********
材料会计
无锡祥生医疗科技股份有限公司
**********
福利:
**********
职位月薪：4001-6000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：1人
职位类别：会计/会计师
**********
工作职责：
1、负责审核最终供应商主数据建立，审核客户的国别/地址/币种/控制科目是否一致。
2、负责初审采购请款单，SAP信息与请款单信息是否一致，审核无误后，复印发票、SAP中及时过账。
3、负责付款后及时在系统中销账、核对往来账。
4、及时跟踪SAP已收货未开票情况，分析未开票原因，大致有账期时间、订单是否完全收货、是否有不良品等因素影响，针对不同的情况催促采购尽快处理。
5、负责清理应付/预付款项的历史账务，按月及时装订AP凭证。
6、负责每月编制应付账款账龄分析表。
7、负责每月编制采购价格变动表。
8、配合审计部门的审核、上级领导安排的其它工作。
任职要求：
1、在机械设备、汽车零部件、电子制造型行业有5年以上工作经验，3年以上材料、成本方面的经验，
大学本科毕业，熟悉ERP软件，Excel 技能精通，
2、性格开朗，善于思考，愿意吃苦，诚实愿意接受挑战，有独立完成工作的能力。

工作地址：
无锡新区新辉环路9号
查看职位地图
**********
无锡祥生医疗科技股份有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医疗设备/器械
公司主页：
www.chison.com.cn
公司地址：
无锡新区新辉环路9号
**********
儿童注意力培训导师
杭州竞思教育科技有限公司
创业公司全勤奖餐补年底双薪节日福利
**********
福利:
创业公司
全勤奖
餐补
年底双薪
节日福利
**********
职位月薪：8001-10000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：3人
职位类别：幼教
**********
任职要求：
1、形象气质佳，普通话标准，有耐心，动手能力强，有耐心管理顽皮好动的孩子，身体健康；
2、有教师工作经验优先，教育培训工作经验者优先，心理学，教育学专业类毕业优先，如：拥有一年以上青少儿教学或类似课后辅导托管等从业经验，能有效管理儿童、培养学生学习生活和良好习惯养成，促进学生之间融洽的相处优先考虑；
3、富有亲和力、爱心、责任心，通晓少儿心理，富有感染力。善于调动儿童学习积极性和吸引儿童注意力，具有团队合作精神和组织协调能力、良好的语言表达能力和人际沟通
能力；
4、有创新意识和钻研精神，能吃苦耐劳，学习能力强；
5、能适应非周末休息。

主要职责范围：
1、负责学员的培训教育工作，让顽皮好动的孩子能静下心来训练，做好训练记录。
2、对于训练结果能够及时与训练中心负责人沟通。
3、负责与学员家长的训练结果的交流工作。做好与学员及学员家长的沟通，定期电话回访家长，做好线上远程咨询服务，能够让学员及学员家长真正地感受到变化。
4、做好训练的记录，及相关文件的整理，做到井井有条。
5、完成上级下达的任务。



更多详情请登陆竞思官方主页：www.talegenes.com

南京市鼓楼区广州路37号江苏科技大厦23楼2312（近中山路，珠江路地铁站1号出口）
工作地址：
江苏省无锡市滨湖区蠡溪路171号
查看职位地图
**********
杭州竞思教育科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
教育/培训/院校
公司主页：
www.jingsiedu.com
公司地址：
杭州西湖区学院路131-3号三楼人力资源部（学院路与文二路交叉口）
**********
ERP系统维护员
无锡钧弘自动化科技有限公司
五险一金绩效奖金通讯补贴带薪年假定期体检免费班车员工旅游节日福利
**********
福利:
五险一金
绩效奖金
通讯补贴
带薪年假
定期体检
免费班车
员工旅游
节日福利
**********
职位月薪：5000-7000元/月 
工作地点：无锡
发布日期：最近
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：1人
职位类别：信息技术专员
**********
岗位职责：
1、负责公司局域网络维护，网络系统安全，所有IT设备管理，处理网络及计算机故障；
2、负责内部信息系统建设、维护；域名、数据、邮箱、服务器管理。
3、公司ERP系统的运营维护
4、协助其他行政管理事务
5、请在微信公众号中寻找“无锡钧弘”， 可以了解更加详细信息。

任职要求：
1、计算机或IT相关专业优先，2年以上的网络管理、服务器网管工作经验；
2、工作细致负责认真，具有较强的学习能力，良好的沟通能力
3、熟悉路由器，交换机、防火墙的网络设备的设置与管理；
4、了解操作系统，熟悉WEB、FTP、MAIL服务器的维护；
5、精通数据库管理，有企业ERP运维经验，优秀应届生也可以。

工作地址：
无锡市光电园会北路28-94号
**********
无锡钧弘自动化科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
仪器仪表及工业自动化
公司主页：
www.exmek.com
公司地址：
无锡市光电园会北路28-94号
查看公司地图
**********
医用感控产品销售代表
南京巨鲨显示科技有限公司
五险一金包吃交通补助餐补通讯补贴
**********
福利:
五险一金
包吃
交通补助
餐补
通讯补贴
**********
职位月薪：6001-8000元/月 
工作地点：无锡
发布日期：最近
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：销售代表
**********
岗位职责：
1、负责巨鲨自主研发的科倍洁感控类产品在医院供应室、手术室等科室的推广与销售；
2、开发各地经销商和终端用户等合作伙伴，提高产品在对应区域市场份额；
3、执行公司各项销售政策，完成季度、年度销售任务。
任职要求：
1、本科及以上学历，医学相关专业优先；
2、1年以上销售工作经验，有医疗行业销售经验者优先；
3、良好的内外沟通技能和执行力，具有独立处理问题能力；
4、坚韧、诚信、有工作责任感；
5、能吃苦，适应出差。

工作地址：
江苏无锡
查看职位地图
**********
南京巨鲨显示科技有限公司
公司规模：
500-999人
公司性质：
民营
公司行业：
医疗设备/器械
公司主页：
cn.jusha.com.cn
公司地址：
江苏省南京市汉中门大街301号南京国际服务外包大厦1幢8楼
**********
3D数字化排牙工程师
上海时代天使医疗器械有限公司
五险一金年底双薪绩效奖金包住带薪年假定期体检节日福利包吃
**********
福利:
五险一金
年底双薪
绩效奖金
包住
带薪年假
定期体检
节日福利
包吃
**********
职位月薪：4001-6000元/月 
工作地点：无锡-惠山区
发布日期：最近
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：30人
职位类别：实习生
**********
3D数字化排牙工程师
招聘人数  30名  
工作职责
1、牙颌模型诊断测量分析；
2、辅助设计医生进行病例的计算机模拟矫治设计；
3、进行必要的临床医生电话沟通，及时响应客户需求，达到医生满意；
4、分析客户临床案例，进行数据统计和总结分析；
任职资格
1、大专及以上学历，口腔工艺技术、口腔医学、计算机等相关专业背景；
2、熟练使用计算机办公软件，熟练使用三维软件者优先
 人员要求 Requirement
1、有良好的沟通、协调和学习能力，思维严谨；
2、工作态度积极踏实，有责任心，具有良好的团队合作精神；
3、勤奋好学，能吃苦耐劳，三观端正；
 发展机会 Job Opportunity
1、公司提供全面专业的实习期培训及教练辅导, 使员工迅速适应工作和职场生活；
2、公司提供持续丰富的岗位在职培训，不断提升员工综合素质和能力，育“材”为“才”;
3、管理岗，技术岗，培训师的三向人才培养通道，激发每个员工潜能。
 工资福利  Compensation & Benefit
员工工资：实习期内：2000-3000元，提供工作餐和免费住宿
毕业后按岗位绩效方案计薪，4000-8000元/月
社会保险：五险一金必须有
年休假： 入职满一年享受5天带薪年假，每增加一年加一天
年终奖：入职满一年享受1-3个月工资为基数的年终奖
健康体检：年度体检少不了，父母的担心就是我们的关注
节日问候：端午、中秋、春节，生日会，每个特别的日子都有惊喜
娱乐活动：旅游、聚餐、拓展，丰富的娱乐活动等着你
总裁开放日：让所有员工都可以与总裁面对面畅所欲言
天使基金：表彰团队及个人对公司作出特殊贡献、弘扬企业文化理念的行为，最高奖励5万元。
员工持股：朝阳行业拟上市公司，为技术类等重点岗位员工提供持股计划
学习计划：定期与各类大咖进行技术交流、学习；丰富的专业培训期待你快速成长
员工成长：鼓励创新，鼓励内部提拔和培养


工作地址：
无锡市惠山区惠山大道1619号2号楼1层（惠山生命科技产业园内）
查看职位地图
**********
上海时代天使医疗器械有限公司
公司规模：
100-499人
公司性质：
外商独资
公司行业：
医疗设备/器械
公司主页：
http://www.shidaits.com/
公司地址：
上海市杨浦区淞沪路333号创智天地三期5层
**********
销售代表
山东朱氏药业集团有限公司
**********
福利:
**********
职位月薪：4001-6000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：8人
职位类别：销售代表
**********
1.负责在指定区域内开展公司产品的推广活动,实现公司产品的销售增长及市场占有率的提高。
2.根据年度销售目标，分解为季度目标和月度目标，按期完成制定销售目标和客户拓展目标。
3.负责走访医生，提升开单业务量。
4.定期拜访客户，协调与客户的关系,解决实际问题，扩大公司产品覆盖率，提高产品销量。
5.向客户提供专业的产品服务，进行产品推广，维护公司形象。
6.负责收集、整理、汇报市场信息及竞争对手信息，做好市场调研报告，及时向上级反馈情况。
7.按照公司要求建立、健全和更新客户约案，做好客户资源管理工作。
8.根据市场状况，协助公司开展区域推广与宣传活动。
9.及时反馈医院使用本公司产品的相关信息。




工作地址：
单县开发区樊楼路南
**********
山东朱氏药业集团有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
医药/生物工程
公司地址：
单县开发区樊楼路南
查看公司地图
**********
机械设计工程师
无锡安之卓医疗机器人有限公司
交通补助餐补通讯补贴弹性工作
**********
福利:
交通补助
餐补
通讯补贴
弹性工作
**********
职位月薪：10000-20000元/月 
工作地点：无锡-惠山区
发布日期：最近
工作性质：全职
工作经验：5-10年
最低学历：大专
招聘人数：5人
职位类别：机械工程师
**********
岗位职责：
 
1.负责产品设计开发、执行开发和设计计划。
2.负责生产转化、技术规范制定工作。
3.收集积累产品和技术发展动态。
4.持续改进产品性能。
5.产品设计、技术转化和制造技术交底工作。
 
任职要求：
 
1.本科以上学历；机械工程、机电一体化或相关专业。
2. 5年以上医疗、工业自动化等行业产品设计经验。
3.精通机械结构和传动。具备静力学和动力学计算的能力。
4.能独立进行电气元件选型。
5.具有一定的抗压能力；有较强的沟通能力，具有团队协作精神，认同公司文化。
6.有过医疗自动化设备设计经验者优先。

薪酬待遇面议

工作地址：
无锡惠山经济开发区锦惠路10号
**********
无锡安之卓医疗机器人有限公司
公司规模：
100-499人
公司性质：
合资
公司行业：
医药/生物工程
公司地址：
无锡惠山经济开发区锦惠路10号
查看公司地图
**********
客户经理
江苏星脉智能科技有限公司
创业公司每年多次调薪绩效奖金弹性工作
**********
福利:
创业公司
每年多次调薪
绩效奖金
弹性工作
**********
职位月薪：5000-10000元/月 
工作地点：无锡
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：客户经理
**********
岗位职责：开拓市场，发展经销商，并维护市场和经销商

任职要求：符合公司价值，有团队合作精神，能接收公司指派的合理任务并积极的完成。不断学习，在工作中进步自己并帮助团队进步。无不良嗜好，无重大疾病史，会使用常用通讯及办公软件，有正确的价值观和社会观，年龄20-45岁之间，男女不限。
工作地址：
江苏无锡
**********
江苏星脉智能科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
互联网/电子商务
公司地址：
上海市长宁区
**********
SQE品质工程师
无锡钧弘自动化科技有限公司
五险一金绩效奖金餐补通讯补贴定期体检免费班车员工旅游节日福利
**********
福利:
五险一金
绩效奖金
餐补
通讯补贴
定期体检
免费班车
员工旅游
节日福利
**********
职位月薪：4000-5000元/月 
工作地点：无锡
发布日期：最近
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：供应商/采购质量管理
**********
岗位要求：
1.机械类专业毕业，熟悉直流/无刷电机。
2.有2年项目管理工作经验。
3.能熟练使用CAD等软件，根据客户产品需要及规格完成项目任务书。
4.根据开发计划督导各生产协作部门完成开发任务。
5.具有一定的谈判沟通技巧。
6.具有较强的团队合作精神及敬业精神，善于协调与其他部门关系。

工作职责：
1.与供应商密切沟通联系，关注掌控电机新品开发项目的进展。
2.与客户/供应商就产品的开发过程中的质量/技术/工艺/生产等问题进行跟踪。
3.对电机的对外出口销售进行全方位的技术支持。

工作地址：
无锡市光电新材料科技园会北路28-94号
查看职位地图
**********
无锡钧弘自动化科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
仪器仪表及工业自动化
公司主页：
www.exmek.com
公司地址：
无锡市光电园会北路28-94号
**********
医疗器械（医药）销售代表 宜兴市
浙江殷欣生物技术有限公司
绩效奖金包吃通讯补贴带薪年假定期体检员工旅游高温补贴节日福利
**********
福利:
绩效奖金
包吃
通讯补贴
带薪年假
定期体检
员工旅游
高温补贴
节日福利
**********
职位月薪：5000-10000元/月 
工作地点：无锡-宜兴市
发布日期：最近
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：2人
职位类别：销售代表
**********
医院、体检中心、诊断中心病理领域体外诊断产品的销售：如宫颈癌相关产品。
岗位职责：
1、负责产品的市场渠道开拓与销售工作，执行并完成公司产品年度销售计划；
2、根据公司市场营销战略，提升销售价值，控制成本，扩大产品在所负责区域的销售，积极完成销售量指标，扩大产品市场占有率；
3、与客户保持良好沟通，实时把握客户需求，为客户提供主动、热情、满意、周到的服务；
4、定期向公司提供市场分析及预测报告和个人工作周报；
5、维护和开拓新的销售渠道和新客户，自主开发及拓展上下游用户，尤其是终端用户；
6、收集一线营销信息和用户意见，对公司营销策略、售后服务、等提出参考意见。
7、每周六回公司参加销售会议。
任职要求：
1、医学、检验、药物分析、护理、生物等相关专业优先，大专及以上学历，欢迎应届生投递；
2、有医疗器材、耗材、药品销售经验者优先；
2.热爱医疗器械销售行业，敬业、负责、勤快、稳重，能承受一定的工作压力，勇于开拓、敢于竞争。
4、具有较强的独立工作能力和社交技巧，较好的沟通能力、协调能力和团队合作能力；
5、身体健康，具有独立分析和解决问题的能力。
6、要求能胜任出差

发展前景：销售代表→销售经理→大区经理→营销总监
培训机会：入职培训、上岗培训、产品培训、技术培训等
公司福利：国定假期，节假日礼品，购买五险，年底奖金，员工宿舍，提供员工餐，生日派对，带薪年假，员工病假礼品慰问，夏季饮品福利，提供下午茶点心，季度团建活动，年度优秀员工奖励,合格年度销售冠军可赢得欧洲游学机会。
工作地址：
江苏宜兴地区
**********
浙江殷欣生物技术有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
医疗设备/器械
公司地址：
余杭区新颜路22号
查看公司地图
**********
HR Supervisor
费森尤斯卡比（中国）
五险一金交通补助餐补通讯补贴高温补贴节日福利
**********
福利:
五险一金
交通补助
餐补
通讯补贴
高温补贴
节日福利
**********
职位月薪：10001-15000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：1人
职位类别：人力资源主管
**********
Responsibility:
Accountable for HR relevant responsible deliverable from Business Services, assure that all operating targets and financial objectives are achieved related to the processes, internal controls are strictly executed as required.
-Prioritize daily work load to meet companies and Corporate goals
-Understand overall business goals and how HR daily processes supports these goals
-In charge of employee’s compensation & benefits, incentive & annual bonus calculation and payment release timely & accurately.
- Ensure procession of social insurance, housing fund etc. employee welfare are aligned with local regulations and company policies.
-Ensure various compensation & benefits data analysis and reports deliverables.
- Manage employee master data maintenance and leave application procedure.
-Manage case handling of employee’s inquires and requests.
-Achieve performance KPI and pursue continuous improvements.
Requirements:
• Well-versed in China labor laws, business practices and government operations.
• Familiar with human resources strategies and policies and strong in the implementation.
• Exposure in pharm manufactory industry will be advantage.
• Proficiency in MS Office Application including Word, Excel, Power Point.
• Stable employment track record is required.
Good people management skill, strong execution ability and experienced engagement skillset with stakeholders.
• Excellent organization, problem solving, communication, presentation skillset.
• Good team player, highly motivated, flexible, strong sense of responsibility.
• Fluent in both written and oral English
工作地址：
无锡
查看职位地图
**********
费森尤斯卡比（中国）
公司规模：
1000-9999人
公司性质：
外商独资
公司行业：
医药/生物工程
公司主页：
https://www.fresenius-kabi.com/cn/index
公司地址：
北京市朝阳区太阳宫中路16号院冠捷大厦17层;
**********
口腔医疗器械销售代表
上海沪鸽医疗器械有限公司
绩效奖金五险一金交通补助通讯补贴弹性工作节日福利
**********
福利:
绩效奖金
五险一金
交通补助
通讯补贴
弹性工作
节日福利
**********
职位月薪：4000-8000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：销售代表
**********
1.本科及以上学历，1年及以上医疗行业销售经验，有口腔医疗产品销售经验者可放宽至大专学历。
2.反应敏捷、表达能力强，具有较强的沟通能力及交际技巧，具有亲和力；
3.具备一定的市场分析及判断能力，良好的客户服务意识；
4.主动积极的工作态度，良好的承压能力。
福利待遇：
1.五险一金，双休，享受交通补贴，通讯补贴，带薪年假，生日福利及节假日福利；
2.良好的职业发展规划，晋升机制和培训机制。
工作地址：
无锡市
查看职位地图
**********
上海沪鸽医疗器械有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医疗设备/器械
公司地址：
上海市浦东新区东方路818号众城大厦9层
**********
生产主管
蝶和科技(中国)有限公司
五险一金加班补助交通补助餐补带薪年假
**********
福利:
五险一金
加班补助
交通补助
餐补
带薪年假
**********
职位月薪：4001-6000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：生产主管/督导/组长
**********
工作职责：
1.组织实施产线的生产计划，确保下达的生产计划顺利完成；
2.生产过程的监督和指导，落实质量管控要求；
3.组织新产品的试生产和批量生产的导入过程；
4.组织技能和业务培训，对公司精神传达，活动，纪律等日常宣导，配合HR部门做好考勤等事宜；
5.协调和其它部门联系，沟通解决生产过程中发生的异常事件；为现场实施，售后提供一定的技术和人员支持；
6.统计分析生产情况（质量、效率、成本），寻求改善，并形成报告；
7.安全、6S、标准化的执行、设备的维护等；
8.完成领导交付的其它任务。

岗位要求：
1.大专或以上学历，机电一体化专业优先；
2.有3年以上生产团队主管工作经验，设备装配行业或生产制造型企业经验优先；
3.具有一定机械、电气常识和制图方面的知识；
4.熟练word、excel等办公软件；
5.出色的协调沟通和团队管理能力。

工作地址：
菱湖大道200号G8栋
**********
蝶和科技(中国)有限公司
公司规模：
500-999人
公司性质：
外商独资
公司行业：
医疗设备/器械
公司主页：
null
公司地址：
北京市丰台区丰茂路汉威国际广场6号楼7层
**********
供应商开发工程师
蝶和科技(中国)有限公司
五险一金绩效奖金交通补助餐补通讯补贴
**********
福利:
五险一金
绩效奖金
交通补助
餐补
通讯补贴
**********
职位月薪：6001-8000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：1人
职位类别：供应商开发
**********
岗位职责：
1.识别所负责的金属结构类物料的潜在供应商，组织联席评审；
2.组织新结构件的开发，包括询价、比价、技术交底、工艺评审直至初期生产批准；
3.定期回顾供应商绩效以不断优化供应商表现水平；
4.组织定期的采购策略回顾以响应当前的业务发展需要，并落实响应的供应资源优化行动，包括专注的质量/交期/成本改善、新供应商开发、供应商整合等；
5.采集、分析并发布所负责的专项物料相关的市场信息；
6.持续寻找降本机会并建立具体的项目，包括和研发部门合作进行设计优化。

任职要求：
1.大专以上学历，理工科教育背景；
2.3年以上相关工作经验，熟悉采购流程；
3.熟悉金属机加工，钣金，焊接制造工艺，具备优秀的谈判能力；具备良好的沟通协调能力； 有医疗器械类生产企业采购工作经验优先考虑。
工作地址：
菱湖大道200号G8栋
**********
蝶和科技(中国)有限公司
公司规模：
500-999人
公司性质：
外商独资
公司行业：
医疗设备/器械
公司主页：
null
公司地址：
北京市丰台区丰茂路汉威国际广场6号楼7层
**********
医药代表（麻醉）
费森尤斯卡比（中国）
五险一金交通补助餐补通讯补贴
**********
福利:
五险一金
交通补助
餐补
通讯补贴
**********
职位月薪：8001-10000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：医药代表
**********
工作职责：
1.负责公司产品在医院的宣传和推广活动，完成销售指标；
2.掌握有效的销售技巧，开发新客户及拜访客户。准确无误地向客户传达产品信息，建立公司专业、负责的良好形象；
3.负责组织区域内科内会、城市会等。确保在实现销售目标的同时，建立公司产品在客户心目中的定位；
4.参与制订并执行经主管确认的医院销售推广计划，在市场发生变化时，及时向上级主管反馈信息，分析问题，提出初步的解决方案，并申请必要的支持；
5.完成书面报告：周计划、周总结、月度报告，每日填写SMMS系统，医院客户情况、医院库存表及产品效期等。
职位要求：
工作经验：有1年以上相关岗位工作经验。
学历：正规大学医药专业专科以上学历。
专业及行业知识：熟悉医药行业
其它知识和技能：有承受压力，接受挑战性工作的能力。有独立工作、良好的沟通、协调能力和团队合作精神。
工作地址：
无锡
查看职位地图
**********
费森尤斯卡比（中国）
公司规模：
1000-9999人
公司性质：
外商独资
公司行业：
医药/生物工程
公司主页：
https://www.fresenius-kabi.com/cn/index
公司地址：
北京市朝阳区太阳宫中路16号院冠捷大厦17层;
**********
人力资源专员（薪酬福利方向）
费森尤斯卡比（中国）
五险一金交通补助餐补通讯补贴
**********
福利:
五险一金
交通补助
餐补
通讯补贴
**********
职位月薪：6001-8000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：人力资源专员/助理
**********
Responsibility:
-Prioritize daily work load to meet Department and Corporate goals
-Understand overall business goals and how HR daily processes supports these goals
-Process employee compensation & benefits, incentive & annual bonus calculation and payment release.
- Ensure procession of social insurance, housing fund etc. employee welfare are aligned with local regulations and company policies.
-Provide various compensation & benefits data analysis and report.
- Handling employee master data maintenance and leave application procedure.
-As a primary point of contact for employees for information on benefit plans, payroll related matters.
-Achieve performance KPI and pursue continuous improvements
Requirements:
University degree，in HR/ Economics /Statistics Major
Proven record of at least 2 years on HR solid experience
Well-versed in China labour laws, business practices and government operations.
Familiar with human resources strategies and policies and strong in the implementation.
Proficiency in MS Office Application including Word, Excel, Power Point.
Excellent organization, problem solving & attention to details skills
Fluent in both written and oral English
Team player, highly motivated, flexible , strong sense of responsibility, good skills of coordinating and communication
工作地址：
无锡
查看职位地图
**********
费森尤斯卡比（中国）
公司规模：
1000-9999人
公司性质：
外商独资
公司行业：
医药/生物工程
公司主页：
https://www.fresenius-kabi.com/cn/index
公司地址：
北京市朝阳区太阳宫中路16号院冠捷大厦17层;
**********
开发质量经理
无锡祥生医疗科技股份有限公司
五险一金绩效奖金带薪年假免费班车
**********
福利:
五险一金
绩效奖金
带薪年假
免费班车
**********
职位月薪：20000-25000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：5-10年
最低学历：大专
招聘人数：1人
职位类别：质量管理/测试经理
**********
工作职责：
1、 负责设计过程的全面质量控制，从风险分析、设计输入到设计过程、设计输出、设计验证以及设计转生产各阶段的流程执行的监督，产品维护期的设计变更审核控制；
2、 指导和审核设计过程的各类活动、批准产品设计发放生产；
3、 公司内部相关部门的体系、流程培训和执行情况监督；
4、 配合法规部进行内部体系、流程审核，并推进审核发现问题的整改和效果评估；
5、 推进设计相关的质量缺陷问题CAPA分析和修改，审核CAPA的措施并监督执行效果；
6、制定测试计划、编写和执行测试用例、记录产品设计缺陷、追踪并验证设计缺陷解决情况、提交产品测试报告。
7、 负责超声产品系列的项目管理工作，包括所涉及的开发内部资源分配以及跨部门的沟通协调等。
要求：
1、理工科背景，本科及以上学历；
2、有硬件、软件设计开发优先；熟练使用办公软件。
3、5年以上工作经验，3年以上项目管理工作经验，有医疗器械产品相关经验优先；
4、积极主动、严谨，良好的团队凝聚力和团队合作精神，良好的学习能力和沟通能力。
工作地址：
无锡新区新辉环路9号
**********
无锡祥生医疗科技股份有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医疗设备/器械
公司主页：
www.chison.com.cn
公司地址：
无锡新区新辉环路9号
查看公司地图
**********
硬件工程师
无锡祥生医疗科技股份有限公司
**********
福利:
**********
职位月薪：10001-15000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：1人
职位类别：硬件工程师
**********
工作职责：
1.负责超声产品硬件系统的开发工作；
2.负责单板测试及整机联调；
3.负责硬件系统的可靠性测试工作
岗位要求：
1. 本科以上学历，电子，通信，计算机，生物医学相关专业；
2. 三年以上硬件开发经验；
3. 有较好的硬件相关基础知识（数字电路、模拟电路、信号处理、嵌入式系统等），
在模拟电路设计、PC硬件设计、FPGA硬件设计、嵌入式系统硬件设计等某一方面有深入的了解和相关的开发经验；
4. 熟练使用原理图/PCB等EDA开发工具，对PCB布局布线、高速信号完整性等有一定的了解；
5. 具有强烈的责任心及团队合作精神，具有较好的沟通及协调能力；
6. 具有手机行业经验者优先，具有知名企业工作经验者优先。"

工作地址：
无锡新区新辉环路9号
**********
无锡祥生医疗科技股份有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医疗设备/器械
公司主页：
www.chison.com.cn
公司地址：
无锡新区新辉环路9号
查看公司地图
**********
成本主管
无锡祥生医疗科技股份有限公司
**********
福利:
**********
职位月薪：8001-10000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：1人
职位类别：成本经理/主管
**********
任职要求：
1）在机械设备、汽车零部件、电子制造型行业
2）有5年以上工作经验，3年以上材料、成本方面的经验，
3）大学本科毕业，熟悉MRP 软件，Excel 技能精通，
4）性格开朗，善于思考，愿意吃苦，诚实愿意接受挑战，有独立完成工作的能力。
 工作职责：
1） 材料成本核算，跟踪材料入库、领用的差异；
2） 每周与仓库管理部门实地盘点存货，确保A 类物资在原材料库位账实相符；
3） 与采购、计划和生产部门密切联系，督促供应商及时开具发票，严格控制材料暂估入库的金额，确保材料暂估余额在理合的范围内；
4） 加强对委外加工产品的出库、入库的监管，跟踪每一个委外加工订单，确保公司财产安全；
5） 加强对现场在产品的管理，正确核算在产品成本；
6） 加强和工程技术部门、生产部门之间的沟通，纠正生产零用与BOM之间的差异，确保BOM的正确；
7） 月末和仓库管理人员去实地盘点：原材料货到未入库，产成品出库未发运的数量；
8） 与生产部门、仓库部门一起监督废品出售的过程。

工作地址：
无锡新区新辉环路9号
**********
无锡祥生医疗科技股份有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医疗设备/器械
公司主页：
www.chison.com.cn
公司地址：
无锡新区新辉环路9号
查看公司地图
**********
（高级）医药代表/专员--EN--无锡
费森尤斯卡比（中国）
五险一金绩效奖金交通补助餐补通讯补贴弹性工作补充医疗保险节日福利
**********
福利:
五险一金
绩效奖金
交通补助
餐补
通讯补贴
弹性工作
补充医疗保险
节日福利
**********
职位月薪：10001-15000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：医药代表
**********
岗位职责：
1.     客户管理：
1)     建立完善的客户档案，与客户保持良好的关系；
2)     提高客户服务质量；
3)     制订拜访计划，每月保证拜访规定数量的目标客户；
4)     配合上级管理者及公司管理部门的协同拜访；
2.     数据报告管理：
1)     按照公司规定提供相应报告，并对报告中的数据真实性负责；
2)     工作符合公司合规要求，及时、准确执行报告系统，按照区域要求汇报工作的进展；
3)     及时反馈市场信息；
3.     学术活动组织与支持：
1)     组织产品科室推广会和临床试验；
2)     配合公司大型学术活动；
3)     参与和完成上级要求的开发工作；
4.     其他工作：
1)     保持与商业合作伙伴的良好沟通，并及时反馈渠道畅通信息；
2)     上级临时交派的其他工作。
任职要求：
1.     国家承认的高等教育大专及以上学历
2.     医学、药学相关专业
3.     二年及以上医药产品临床推广或销售相关经验 工作地址：
无锡
查看职位地图
**********
费森尤斯卡比（中国）
公司规模：
1000-9999人
公司性质：
外商独资
公司行业：
医药/生物工程
公司主页：
https://www.fresenius-kabi.com/cn/index
公司地址：
北京市朝阳区太阳宫中路16号院冠捷大厦17层;
**********
（高级）医药代表/专员--EN--无锡
费森尤斯卡比（中国）
五险一金绩效奖金交通补助餐补通讯补贴弹性工作补充医疗保险节日福利
**********
福利:
五险一金
绩效奖金
交通补助
餐补
通讯补贴
弹性工作
补充医疗保险
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：3人
职位类别：医药代表
**********
岗位职责：
1.     客户管理：
1)     建立完善的客户档案，与客户保持良好的关系；
2)     提高客户服务质量；
3)     制订拜访计划，每月保证拜访规定数量的目标客户；
4)     配合上级管理者及公司管理部门的协同拜访；
2.     数据报告管理：
1)     按照公司规定提供相应报告，并对报告中的数据真实性负责；
2)     工作符合公司合规要求，及时、准确执行报告系统，按照区域要求汇报工作的进展；
3)     及时反馈市场信息；
3.     学术活动组织与支持：
1)     组织产品科室推广会和临床试验；
2)     配合公司大型学术活动；
3)     参与和完成上级要求的开发工作；
4.     其他工作：
1)     保持与商业合作伙伴的良好沟通，并及时反馈渠道畅通信息；
2)     上级临时交派的其他工作。
任职要求：
1.     国家承认的高等教育大专及以上学历
2.     医学、药学相关专业
3.     二年及以上医药产品临床推广或销售相关经验 工作地址：
北京市朝阳区太阳宫中路16号院冠捷大厦17层;
查看职位地图
**********
费森尤斯卡比（中国）
公司规模：
1000-9999人
公司性质：
外商独资
公司行业：
医药/生物工程
公司主页：
https://www.fresenius-kabi.com/cn/index
公司地址：
北京市朝阳区太阳宫中路16号院冠捷大厦17层;
**********
采购助理
无锡安之卓医疗机器人有限公司
五险一金股票期权包吃带薪年假定期体检免费班车员工旅游节日福利
**********
福利:
五险一金
股票期权
包吃
带薪年假
定期体检
免费班车
员工旅游
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：无锡
发布日期：最近
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：2人
职位类别：采购专员/助理
**********
岗位职责：
1、负责所有物料类物品采购
2、负责设备类合同建立流程
3、负责所有采购项目的到况
4、跟进采购物品对账及付款；

任职要求：
1.大专以上学历，两年以上中小型企业采购助理经验。
2.略懂弱电、电子、电路、线路板。
工作地址：
无锡惠山经济开发区锦惠路10号
**********
无锡安之卓医疗机器人有限公司
公司规模：
100-499人
公司性质：
合资
公司行业：
医药/生物工程
公司地址：
无锡惠山经济开发区锦惠路10号
查看公司地图
**********
模拟电路-硬件工程师
无锡祥生医疗科技股份有限公司
**********
福利:
**********
职位月薪：8001-10000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：1人
职位类别：硬件工程师
**********
岗位职责：
1.负责超声新产品模拟前端电路(ECG、超声发射接收等电路)的评估和预研工作                 
2.负责超声新产品的开发和设计工作          
3.负责超声新产品的调试和测试工作
岗位要求：
1. 本科以上学历，电子，通信，计算机，生物医学相关专业；
2. 有较好的模拟电路基础，熟悉ADC/DAC/OPA/LDO/DC-DC等器件的工作原理和性能指标，在模拟电路设计和调试方面有深入的了解和相关的开发经验；
3. 熟练使用原理图/PCB等EDA开发工具，对PCB布局布线、高速信号完整性等有一定的了解；
4. 具有强烈的责任心及团队合作精神，具有较好的沟通及协调能力；
5. 具有超声行业经验者优先，具有知名企业工作经验者优先。
工作地址：
无锡新区新辉环路9号 无锡新区硕放香楠路8号
**********
无锡祥生医疗科技股份有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医疗设备/器械
公司主页：
www.chison.com.cn
公司地址：
无锡新区新辉环路9号
查看公司地图
**********
地区销售经理（江苏常州、盐城）
北京博邦佳远医药科技发展有限公司
五险一金绩效奖金全勤奖餐补通讯补贴定期体检员工旅游节日福利
**********
福利:
五险一金
绩效奖金
全勤奖
餐补
通讯补贴
定期体检
员工旅游
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：2人
职位类别：销售经理
**********
一、地区经理
常住地：常州、盐城各1名；
 二、岗位职责：
1、负责区域代理商的开发、维护、协调沟通和考核工作；
2、对产品在区域医院的销售进行跟踪，协助代理商开发上量；
3、负责完成公司下达的销售任务；
4、负责管辖区域的招投标、销售回款、销售网络建立、销售服务等工作； 
5、及时反馈市场的动态及各类报表的收集和填报；
6、按照上级领导的要求，完成安排的工作。

 三、任职要求：

1、男女不限，大专及以上学历； 
2、年龄25-35岁；
3、专业不限，有一定的医药行业工作经验，特别是心脑血管药品招商经验；
4、优秀的沟通、表达能力，良好的团队合作意识、客户服务意识；
5、责任心强，抗压能力强；
6、具有良好的当地医药市场网络资源者优先。 

四、薪酬福利：五险一金+高额提成+节假日福利+旅游+年假+婚假+晋升空间+半年奖励+年终奖
 联系人：郭经理
联系电话：135-0516-3605

工作地址：
常州、盐城
查看职位地图
**********
北京博邦佳远医药科技发展有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医药/生物工程
公司主页：
http://www.21bobang.com
公司地址：
北京市朝阳区建国路93号万达广场
**********
区域经理（江苏省内）
北京博邦佳远医药科技发展有限公司
五险一金绩效奖金年终分红定期体检员工旅游节日福利
**********
福利:
五险一金
绩效奖金
年终分红
定期体检
员工旅游
节日福利
**********
职位月薪：8001-10000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：药品市场推广经理/主管
**********
一、工作地点：江苏省内
 
   江苏省目前需要地区经理5名，驻地：南京，苏州、南通、扬州、徐州

          
二、工作职责 ：

1、负责公司市场开发工作；
 
2、负责包辖区域的招商宣传、销售回款、销售网络建立、销售服务等工作；
 
3、 负责所辖省区的招投标工作；

4、所按照上级领导的要求，及时汇报工作。

 
三、任职要求：

1、22-35 岁，大专及以上学历；

2、专业不限，有一定的医药行业工作经验，特别是心脑血管药品招商经验；

3、良好的沟通、表达能力；
 
4、吃苦耐劳、良好的自我管理能力。

 
四、薪酬福利：五险一金+高额提成+节假日福利+旅游+婚假+晋升空间+半年奖励+年终奖
 联系人：郭经理
联系电话：135-0516-3605
  工作地址：
北京市朝阳区建国路93号万达广场
查看职位地图
**********
北京博邦佳远医药科技发展有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医药/生物工程
公司主页：
http://www.21bobang.com
公司地址：
北京市朝阳区建国路93号万达广场
**********
PMO
江苏曼荼罗软件股份有限公司
绩效奖金包住交通补助通讯补贴带薪年假弹性工作定期体检员工旅游
**********
福利:
绩效奖金
包住
交通补助
通讯补贴
带薪年假
弹性工作
定期体检
员工旅游
**********
职位月薪：6001-8000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：2人
职位类别：项目专员/助理
**********
 岗位职责：
1、协助管理各项目进度及风险，收集项目执行过程数据（进度，成本，质量等），分析项目执行状态，对发现的项目问题和风险，协调推动相关干系人解决问题，化解或规避风险；
2、整理发布项目报告，召开项目会议，发布会议纪要；
3、负责收集整理项目知识和经验，形成项目最佳实践等，并不断完善项目管理规范体系，开展项目管理相关培训等活动；
4、协助指导、讲解PMO发布的相关流程、规范、模版；

任职要求：
1.大学本科及以上，二年以上工作经验；
2.良好的跨部门沟通能力和团队协作能力，具有一定的数据分析能力，掌握各种办公工具软件；
3.有优秀的人际沟通能力和团队合作精神；
4.工作积极主动、认真负责，有较强的学习和适应能力，能承受一定的工作压力和挑战；
工作地址：
无锡市新区菱湖大道200号创新园F区5号楼
**********
江苏曼荼罗软件股份有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
计算机软件
公司主页：
www.mandalat.com.cn
公司地址：
无锡市新区菱湖大道200号创新园F区5号楼
**********
销售代表
山东朱氏药业集团有限公司
**********
福利:
**********
职位月薪：4001-6000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：4人
职位类别：销售代表
**********
1.负责在指定区域内开展公司产品的推广活动,实现公司产品的销售增长及市场占有率的提高。
2.根据年度销售目标，分解为季度目标和月度目标，按期完成制定销售目标和客户拓展目标。
3.负责走访医生，提升开单业务量。
4.定期拜访客户，协调与客户的关系,解决实际问题，扩大公司产品覆盖率，提高产品销量。
5.向客户提供专业的产品服务，进行产品推广，维护公司形象。
6.负责收集、整理、汇报市场信息及竞争对手信息，做好市场调研报告，及时向上级反馈情况。
7.按照公司要求建立、健全和更新客户约案，做好客户资源管理工作。
8.根据市场状况，协助公司开展区域推广与宣传活动。
9.及时反馈医院使用本公司产品的相关信息。




工作地址：
济南市中心绿地中心
**********
山东朱氏药业集团有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
医药/生物工程
公司地址：
单县开发区樊楼路南
查看公司地图
**********
FPGA初级工程师
无锡祥生医疗科技股份有限公司
**********
福利:
**********
职位月薪：4000-6000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：1人
职位类别：其他
**********
工作职责：
1.负责简单模块开发
2.负责测试模块的完善
职位要求：
1. 本科学历，学习过数字电子，信号与系统课程；
2. 有1～2年的工作经验，优秀应届毕业生也可，
   知道FPGA的开发流程
   熟悉EDA工具，如仿真，综合工具

工作地址：
无锡新区新辉环路9号
**********
无锡祥生医疗科技股份有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医疗设备/器械
公司主页：
www.chison.com.cn
公司地址：
无锡新区新辉环路9号
查看公司地图
**********
海外销售
凯思轩达医疗科技无锡有限公司
**********
福利:
**********
职位月薪：6001-8000元/月 
工作地点：无锡
发布日期：最近
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：销售行政专员/助理
**********
1、公司产品的海外宣传与推广，制作说明手册的英文版；
2、登陆国际各大购物平台，注册公司账号，对公司的产品和服务进行销售推广以及日常咨询的应答；
3、了解全球国家对二手医疗设备的政策和法律法规；
4、联系各国当地经销商，渠道商，推广凯思的机器和维保服务；
5、完成销售相关合同制作，进出口手续，报关手续，费用回收等等；
6、与意向合作者进行沟通谈判，涉及合适的合作方式；
7、协调采购与销售的各个环节；
任职要求：
1、有外贸工作经验优先；
2、有国际电商经验优先；
3、英文四级以上，能够熟练应答电话，回复邮件；

工作地址：
江苏省无锡市新吴区天安智慧城2-608
**********
凯思轩达医疗科技无锡有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医疗设备/器械
公司地址：
广州天河区五山路246号金山大厦南塔28楼
**********
测试工程师
无锡祥生医疗科技股份有限公司
五险一金带薪年假免费班车年底双薪包吃
**********
福利:
五险一金
带薪年假
免费班车
年底双薪
包吃
**********
职位月薪：3000-4000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：测试/可靠性工程师
**********
工作职责：
1、负责探头温升测试以及探头声输出测试
2、负责测试设备维护保养工作
任职要求：
1、专科及以上学历，电子电气、物理或微电子、信息等相关专业
2、有一定的测试工作经验
3、对测试流程有一定了解
4、具有一定的分析问题、解决问题的能力

工作地址：
无锡新区新辉环路9号
查看职位地图
**********
无锡祥生医疗科技股份有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医疗设备/器械
公司主页：
www.chison.com.cn
公司地址：
无锡新区新辉环路9号
**********
软件测试工程师
无锡祥生医疗科技股份有限公司
五险一金绩效奖金带薪年假包吃免费班车节日福利年底双薪
**********
福利:
五险一金
绩效奖金
带薪年假
包吃
免费班车
节日福利
年底双薪
**********
职位月薪：4001-6000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：3人
职位类别：质量管理/测试工程师
**********
职位需求：
1. 软件功能验证
2. 注册标准核对
3. 测试作业指导书编写
要求：
1、大专以上学历，计算机、通讯、信息工程等相关专业。
2、1年以上软件测试工作经验，通讯、医疗或互联网相关行业。
3、测试用例编写、执行，测试报告总结。
4、医疗行业优先考虑，有自动化测试相关经验优先考虑。

工作地址：
新辉环路9号
查看职位地图
**********
无锡祥生医疗科技股份有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医疗设备/器械
公司主页：
www.chison.com.cn
公司地址：
无锡新区新辉环路9号
**********
声学工程师
无锡祥生医疗科技股份有限公司
五险一金年底双薪带薪年假免费班车包吃
**********
福利:
五险一金
年底双薪
带薪年假
免费班车
包吃
**********
职位月薪：8001-10000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：1人
职位类别：医疗器械研发
**********
任职要求：
1. 本科以上学历，声学、材料、通信等相关专业；优秀应届毕业生亦可；
2. 优先条件：对声学设计和工艺有较好的了解，熟悉探头开发材料，对胶水等有了解；具有超声行业经验者优先；
3. 具有强烈的责任心及团队合作精神，具有较好的沟通及协调能力。
工作职责：
1、负责部分探头开发设计工作；
2、负责部分材料工艺改进工作；
3、负责新产品调研开发工作。

备注：水声学
工作地址：
无锡新区新辉环路9号
查看职位地图
**********
无锡祥生医疗科技股份有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医疗设备/器械
公司主页：
www.chison.com.cn
公司地址：
无锡新区新辉环路9号
**********
课程顾问 高收入
杭州竞思教育科技有限公司
五险一金年底双薪餐补定期体检员工旅游节日福利
**********
福利:
五险一金
年底双薪
餐补
定期体检
员工旅游
节日福利
**********
职位月薪：8001-10000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：培训/招生/课程顾问
**********
岗位职责：
1、在线接待及电话接待前来咨询的意向客户，并为客户提供专业的咨询；
2、在做好意向客户的咨询解答和引导工作的同时，能最终引导其带孩子上门进行测评体验； 3、针对测评结果进行专业分析，并提供针对性的课程方案，继而引导客户签单，达成销售，完成销售任务；
4、维护客情关系，能与学员和家长保持长期良好的关系； 
岗位优势与特点： 
1、公司提供客户资源：市场部和推广部会同时进行线下线上推广，为销售部吸引潜在客户。 
2、可根据个人能力特点，设置不同的岗位底薪和提成模式，可满足优秀销售人才的高薪需要。
3、公司提供一人一间的独立装修的办公室，并配有电脑、沙发、茶几和植物，方便接待客户。
4、工作时间说明：下午1点半上班，晚上8点下班，周六周日是接待高峰期要上班，休息安排在周一、周二或周三，保证双休
5、上班地址：2个中心自由选择1中南路中心2循礼门中心
任职要求： 
1、高中以上学历，有一年以上销售经验，有教育、培训行业工作经验优先； 
2、善于与人交流，口齿伶俐、表达清晰、气质优雅； 
5、具备积极的态度，能够在压力下进行自我调节，独立完成工作； 
6、能适应异地的远程管理与指导，并能自律自觉地完成工作任务

我们的要求：
仪表整洁，谈吐得体，具有专业精神和个人风格, 诚实守信
具备合作精神，乐观的态度，良好的服务意识，高度的责任感和信任感
教育专业优先选择
有教育行业工作经验优先录取
地址：无锡市崇安区县前西街7号 竞思       

工作地址：
无锡市崇安区县前西街7号 竞思
查看职位地图
**********
杭州竞思教育科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
教育/培训/院校
公司主页：
www.jingsiedu.com
公司地址：
杭州西湖区学院路131-3号三楼人力资源部（学院路与文二路交叉口）
**********
医药代表
东方艾特(北京)医疗科技有限公司
五险一金节日福利员工旅游不加班
**********
福利:
五险一金
节日福利
员工旅游
不加班
**********
职位月薪：10001-15000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：医药代表
**********
岗位职责：
（1）完成公司制定的市场推广目标和销售任务，达到预期销售目标；
（2）开拓潜在的渠道客户，并对既有的客户进行维护；
（3）能够准确地向目标客户提供产品的特点、疗效及注意事项等资料信息；
（4）适应团队建设，保持与同事的团结合作。
（5）及时向上级主管反映竟争对手的情况及市场动态、提出合理化建议；
（6）熟悉药品流通渠道，掌握基本的药品销售技巧；
（7）接受并按时完成公司分派的各项临时性的工作

任职要求：
（1） 专科及以上学历；
（2） 医学、药学、市场营销等相关专业毕业；
（3） 具有1年以上大型医药企业销售工作经验者优先选择。
（4） 了解有关医药的政策法规及医药方面的专业知识；
（5） 具备较强的沟通、协调能力，以及分析、判断能力。

工作地址：
北京市双桥东路华文国际大厦
查看职位地图
**********
东方艾特(北京)医疗科技有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
医疗/护理/美容/保健/卫生服务
公司地址：
北京市双桥东路华文国际大厦
**********
项目经理
江苏曼荼罗软件股份有限公司
绩效奖金包住交通补助通讯补贴带薪年假弹性工作定期体检员工旅游
**********
福利:
绩效奖金
包住
交通补助
通讯补贴
带薪年假
弹性工作
定期体检
员工旅游
**********
职位月薪：8001-10000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：1人
职位类别：项目经理/项目主管
**********
工作职责：
1. 作为研究团队成员，参与和承担医疗服务审核以及相关延伸业务领域的研究工作; 
2. 参与或支持相关研究的设计和数据采集、负责数据处理和统计分析;
3. 参与或负责研究产品的测试、统计分析和评价;
4. 参与或负责标准和模型生成流程设计、配置、监管控制、分析诊断、优化和管理，协助对这些流程进行标准化、规范化、工程化和计算机化;
5. 参与或支持医院CDA数据库建设；
6. 参与或支持医院质控脚本库建设；
任职资格：
1.大专及以上学历，计算机、软件开发相关专业；
2.重点：熟练sqlserver、Oracle语法运用
3.有Xslt脚本编写经验优先
4.有相关医疗软件实施经验，比如EMR、HIS、LIS、公卫系统等，行业经验2年以上优先
5.集成过医院CDA数据优先
6.独立实施过医疗项目。

工作地址：
无锡市新区菱湖大道200号创新园F区5号楼
**********
江苏曼荼罗软件股份有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
计算机软件
公司主页：
www.mandalat.com.cn
公司地址：
无锡市新区菱湖大道200号创新园F区5号楼
**********
结构工程师
无锡祥生医疗科技股份有限公司
**********
福利:
**********
职位月薪：6001-8000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：1人
职位类别：技术研发工程师
**********
工作职责：
1、新产品开发
2、领导安排的其他工作
任职要求：
1、能够熟练使用相关设计软件：proe、 CAD
2、了解钣金成型及模具，塑胶成型及模具，压铸成型及模具
3、能够英文阅读相关的资料
4、对产品的开发流程有一定的了解，比如组建BOM,EC,包装设计等等
5、有做个整机设的经验的优先，特别是手机，笔记本类型的小产品

工作地址：
无锡新区新辉环路9号
**********
无锡祥生医疗科技股份有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医疗设备/器械
公司主页：
www.chison.com.cn
公司地址：
无锡新区新辉环路9号
查看公司地图
**********
采购专员
蝶和科技(中国)有限公司
五险一金绩效奖金交通补助餐补通讯补贴
**********
福利:
五险一金
绩效奖金
交通补助
餐补
通讯补贴
**********
职位月薪：4001-6000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：1人
职位类别：采购专员/助理
**********
岗位职责：
1.根据需求组织生产物资的采购，包括固定资产、MRO等。
2.负责销售项目配套物资的采购。
3.追踪已下达订单的进度，协调日常订单交付中的问题，包括但不限于收货差异、质量问题、发票确认等。
4.供应商基础信息管理，包括评审资料、协议、绩效考评信息等。
5.组织评价供应商综合表现，包括质量、交付、服务及降本方面的表现。
6.部分新品导入项目（NPI）的采购工作。
7.执行采购主管安排的其它任务，当有必要时，后备其他同事的工作。


任职要求：
1. 全日制大专以上
2. 2~3年采购工作经验 理工科优先 
3.有项目管理经验；国贸经验。    

工作地址：
新吴区菱湖大道200号G8栋
**********
蝶和科技(中国)有限公司
公司规模：
500-999人
公司性质：
外商独资
公司行业：
医疗设备/器械
公司主页：
null
公司地址：
北京市丰台区丰茂路汉威国际广场6号楼7层
**********
计算机/设计类实习生
上海时代天使医疗器械有限公司
五险一金年底双薪绩效奖金包吃包住带薪年假定期体检节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
包吃
包住
带薪年假
定期体检
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：无锡-惠山区
发布日期：最近
工作性质：全职
工作经验：无经验
最低学历：大专
招聘人数：30人
职位类别：平面设计
**********
工作职责
1、牙颌模型诊断测量分析；
2、使用三维软件进行病例的计算机模拟矫治方案设计；
3、与临床医生电话沟通，及时响应客户需求；
4、分析客户临床案例，进行数据统计和总结分析；

任职资格
1、大专及以上学历，计算机、设计类相关专业背景；
2、计算机软件操作熟练

人员要求 Requirement
1、有良好的沟通、协调和学习能力，思维严谨； 
2、工作态度积极踏实，有责任心，具有良好的团队合作精神；
3、勤奋好学，能吃苦耐劳，三观端正；

发展机会 Job Opportunity
1、公司提供全面专业的实习期培训及教练辅导, 使员工迅速适应工作和职场生活；
2、公司提供持续丰富的岗位在职培训，不断提升员工综合素质和能力，育“材”为“才”;
3、管理岗，技术岗，培训师的三向人才培养通道，激发每个员工潜能。

工资福利  Compensation & Benefit
员工工资：实习期内2000-3000元，提供工作餐和免费住宿
毕业后按岗位绩效方案计薪，4000-8000元/月
社会保险：五险一金必须有
年休假： 入职满一年享受5天带薪年假，每增加一年加一天
年终奖：入职满一年享受1-3个月工资为基数的年终奖
健康体检：年度体检少不了，父母的担心就是我们的关注
节日问候：端午、中秋、春节，生日会，每个特别的日子都有惊喜
娱乐活动：旅游、聚餐、拓展，丰富的娱乐活动等着你
总裁开放日：让所有员工都可以与总裁面对面畅所欲言
天使基金：表彰团队及个人对公司作出特殊贡献、弘扬企业文化理念的行为，最高奖励5万元。
员工持股：朝阳行业拟上市公司，为技术类等重点岗位员工提供持股计划
学习计划：定期与各类大咖进行技术交流、学习；丰富的专业培训期待你快速成长
员工成长：鼓励创新，鼓励内部提拔和培养

招聘流程 Recruitment Process
招聘会/宣讲会/网站投递简历——简历收集——简历筛选——笔试——面试——复试——实习——签订就业协议

应聘须知 Matters Need Attention
1、网上简历投递的邮件标题格式为“姓名-学校-专业-应聘岗位-电话”;
2、现场投递简历的，请在简历上注明应聘职位；
3、笔试或面试将以短信或电话形式通知，请保持通讯畅通；
4、参加笔试者需携带身份证、2B铅笔、橡皮和水笔；
5、参加面试者需携带以下资料:个人简历（现场投递简历的不必重复提交）。

联系我们 Contact Us
公司地址：无锡市惠山区惠山大道1619号2号楼1层（惠山生命科技产业园内）
联系方式：0510-83599517
公司网站：www.angelalign.com
面试简历投递邮箱： wxhr@angelalign.com

工作地址：
无锡市惠山区惠山大道1619号生命科技园EA时代天使
查看职位地图
**********
上海时代天使医疗器械有限公司
公司规模：
100-499人
公司性质：
外商独资
公司行业：
医疗设备/器械
公司主页：
http://www.shidaits.com/
公司地址：
上海市杨浦区淞沪路333号创智天地三期5层
**********
FPGA工程师
无锡祥生医疗科技股份有限公司
五险一金免费班车年底双薪包吃带薪年假
**********
福利:
五险一金
免费班车
年底双薪
包吃
带薪年假
**********
职位月薪：7000-10000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：集成电路IC设计/应用工程师
**********
工作职责：
1.负责模块开发
2.负责测试模块完善
职位要求：
1. 学历本科及以上，电子类专业如电子信息工程，微电子，电子信息科学与技术，生物医学工程等；
2. 1~3年的工作经验，
   熟悉FPGA的开发流程
   熟悉EDA工具，如仿真，综合工具

工作地址：
无锡新区新辉环路9号
查看职位地图
**********
无锡祥生医疗科技股份有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医疗设备/器械
公司主页：
www.chison.com.cn
公司地址：
无锡新区新辉环路9号
**********
医药代表
北京万生药业有限责任公司
全勤奖交通补助通讯补贴带薪年假员工旅游节日福利
**********
福利:
全勤奖
交通补助
通讯补贴
带薪年假
员工旅游
节日福利
**********
职位月薪：8001-10000元/月 
工作地点：无锡-宜兴市
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：销售代表
**********
岗位职责：
1、负责所在区域医院内对公司的产品进行推广与宣传活动；
2、遵循公司的政策、目标去管理所辖的区域；
3、在权责范围内开展各种销售活动；
4、制定并执行销售计划，完成既定的销售目标。
任职要求：
1、大学本科以上学历，药学、临床、医护、营销等相关专业优先； 
2、从事一年以上销售工作经验；
3、熟悉产品相关的医药知识及市场营销学基本知识；
4、具有较强的沟通与拓展能力。

工作地址：
江苏-无锡-宜兴市
**********
北京万生药业有限责任公司
公司规模：
1000-9999人
公司性质：
股份制企业
公司行业：
医药/生物工程
公司主页：
http://www.wansheng.com.cn
公司地址：
北京市通州工业开发区广源东街8号
**********
质量工程师
蝶和科技(中国)有限公司
五险一金绩效奖金交通补助餐补通讯补贴
**********
福利:
五险一金
绩效奖金
交通补助
餐补
通讯补贴
**********
职位月薪：6001-8000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：1人
职位类别：质量管理/测试工程师
**********
岗位职责：
1.参与供应商评审，包括对关键外包过程的过程控制；对供应商交付质量进行统计、分析、反馈和汇报，督促供应商积极改善，跟踪改善结果；
2.新产品先期质量策划，根据产品实际情况制定IQC、OQC检验规范并监督执行；督促跟进供应商首样检测及预生产批准；
3.负责监控厂内质控过程的有效性；负责对进货、制程、客诉问题组织分析推动供应商以及公司内部各部门持续整改，不断提高产品质量水平，降低质量成本；
4.对检验员进行检验作业指导书的相关培训；根据实际生产的结果以及反馈，随时对检验作业指导书进行修正；
5.参与全面质量管理中涉及的跨职能体系建设；
6.基于业务需求建设内外部测量测试资源；
7.完成领导交付的其他工作。

任职要求：
1.机械相关专业本科及以上学历；
2.具备在机械装配相关行业3年以上工作经历；
3.熟悉钣金、机加、焊接、注塑等加工工艺；熟悉机械原理，具备读图能力；熟悉运用质量管理工具及方法；熟练使用各类测量量具；熟悉ISO9001或者ISO13485质量体系；
4.熟练使用AUTOCAD等绘图工具；熟练使用各类办公软件；
5.具备较强的品质、责任观念和意识，并能够根据当前实际情况灵活应变的能力。
工作地址：
菱湖大道200号G8栋
**********
蝶和科技(中国)有限公司
公司规模：
500-999人
公司性质：
外商独资
公司行业：
医疗设备/器械
公司主页：
null
公司地址：
北京市丰台区丰茂路汉威国际广场6号楼7层
**********
测试工程师/技工
TCL医疗放射技术（北京）有限公司
五险一金年底双薪餐补通讯补贴带薪年假弹性工作补充医疗保险定期体检
**********
福利:
五险一金
年底双薪
餐补
通讯补贴
带薪年假
弹性工作
补充医疗保险
定期体检
**********
职位月薪：4001-6000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：医疗器械维修/保养
**********
岗位职责：
负责医疗器械商品生产、组装、调试、成品检验

任职要求：
1、有医疗设备生产经验者优先
2、有大型机械生产制造经验者优先

工作地址：
无锡市新区清源路20号立业楼B301
查看职位地图
**********
TCL医疗放射技术（北京）有限公司
公司规模：
100-499人
公司性质：
合资
公司行业：
医疗设备/器械
公司地址：
北京市经济技术开发区博兴5路10号柏瑞安办公楼4层
**********
业务经理
北京志翔领驭科技有限公司
五险一金高温补贴节日福利包住带薪年假年底双薪
**********
福利:
五险一金
高温补贴
节日福利
包住
带薪年假
年底双薪
**********
职位月薪：6001-8000元/月 
工作地点：无锡
发布日期：最近
工作性质：全职
工作经验：1-3年
最低学历：中专
招聘人数：1人
职位类别：销售代表
**********
 业务方向：①针对连锁药店、零售药店提供符合GSP认证标准的阴凉陈列柜、冷藏柜；②针对医药经营企业提供温湿度监测设备及系统服务。
岗位职责：
1、有效实施销售计划，完成销售指标；
2、通过电话销售、目标客户现场拜访洽谈等，达成合作；
3、制定及实施每月营销计划；
4、完成区域经理安排的其他各项工作。
任职资格：
1、市场营销/药学/贸易等相关专业优先考虑；
2、对医药咨询行业有一定的了解；
3、有良好的沟通能力及技巧，有一定的抗压能力；
4、能够接受公司外出安排。
本公司为员工提供最佳的行业发展平台和良好的晋升机制，愿挑战高薪者积极加入公司团队。
公司福利待遇：
1、基本薪资+提成或奖金+补助；
2、提供五险；
3、实行8小时工作制，享受法定假期；
4、提供新员工入职培训、专业培训及良好的晋升渠道。
  工作地址：
无锡
**********
北京志翔领驭科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
专业服务/咨询(财会/法律/人力资源等)
公司主页：
www.gsprz.com
公司地址：
北京市丰台区总部基地海鹰路1号院2号楼12层
**********
国内销售经理
无锡祥生医疗科技股份有限公司
五险一金绩效奖金带薪年假免费班车
**********
福利:
五险一金
绩效奖金
带薪年假
免费班车
**********
职位月薪：6001-8000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：1人
职位类别：销售经理
**********
岗位要求：
1、大专以上学历
2、具备医疗设备五年以上销售经历，有电活销售模式经历者优先
3、有影像设备类电话销售经验和团队管理经验者优先考虑
4、有时需要出差
5、工作地点：无锡

岗位职责：
1、电话销售团队日常管理，对团队销售结果负责
2、制定区域市场销售方案，管理销售过程
3、培训、指导、帮助团队成员实现销售目标

工作地址：
无锡新区新辉环路9号
**********
无锡祥生医疗科技股份有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医疗设备/器械
公司主页：
www.chison.com.cn
公司地址：
无锡新区新辉环路9号
查看公司地图
**********
装配调试工程师（NPI）
无锡祥生医疗科技股份有限公司
五险一金年底双薪带薪年假免费班车包吃
**********
福利:
五险一金
年底双薪
带薪年假
免费班车
包吃
**********
职位月薪：5000-6000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：版图设计工程师
**********
任职资格：
1、本科以上学历，电子电气、物理或微电子、信号专业等相关专业；
2、具有模电和数电基础，熟悉常用电子元件，如接插件、高压开关等相关器件；
3、熟悉电路板设计工具，有过FPC和PCB实际设计制作经验的优先；
4、有PCB调试装配工作经验者优先，会手焊。
岗位职责：
1、研发样品探头调试和装配；
2、在线和返回品不良品分析；
3、部分FPC和PCB设计；
4、相关BOM工作。
工作地址：
无锡新区新辉环路9号
查看职位地图
**********
无锡祥生医疗科技股份有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医疗设备/器械
公司主页：
www.chison.com.cn
公司地址：
无锡新区新辉环路9号
**********
外贸业务营销专员
无锡钧弘自动化科技有限公司
五险一金绩效奖金餐补带薪年假节日福利员工旅游定期体检免费班车
**********
福利:
五险一金
绩效奖金
餐补
带薪年假
节日福利
员工旅游
定期体检
免费班车
**********
职位月薪：2001-4000元/月 
工作地点：无锡
发布日期：最近
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：销售运营专员/助理
**********
岗位职责：
1.负责微特电机的国际市场营销以及客户开发、维护、跟踪。
2.协助业务经理进行各个销售平台、渠道的维护和管理。
3.请在微信公众号中关注 “无锡钧弘”， 了解更多招聘信息。

任职要求：
1.英语4级以上
2.从事微特电机等工控自动化产品的国际市场营销
3.勤奋踏实，能够进行独立的新客户开发。
4.熟练掌握办公软件使用以及有一定的外贸工作经验。

工作地址：
无锡市光电园会北路28-94号
**********
无锡钧弘自动化科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
仪器仪表及工业自动化
公司主页：
www.exmek.com
公司地址：
无锡市光电园会北路28-94号
查看公司地图
**********
（高级）医药代表/专员--PN--宜兴
费森尤斯卡比（中国）
五险一金绩效奖金交通补助通讯补贴带薪年假补充医疗保险高温补贴节日福利
**********
福利:
五险一金
绩效奖金
交通补助
通讯补贴
带薪年假
补充医疗保险
高温补贴
节日福利
**********
职位月薪：10001-15000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：医药代表
**********
制订医院拜访计划，每月保证拜访规定数量的目标客户，认真填写医院拜访报告；
组织产品科室推广会和临床试验；
配合公司大型学术活动和销售活动；
完成销售目标，并扩大目标科室、增加目标医生从而增加公司产品的销量；
参与和完成上级要求的新的医院开发工作；
每月一次书面报告所负责的医院公司产品的消化量和库存量，并对数据的真实性负责；
建立完善的客户档案，与客户保持良好的关系；
按公司规定合理使用各项费用，及时、准确执行报告系统（医院、费用、行政），及时汇报工作的进展；
保持与商业代表的良好沟通，并及时反馈渠道畅通信息；
及时反馈市场信息 （客户、产品、竞争对手、招标、医保等）；
配合大区经理、地区经理、销售主管的协同拜访；
提高客户服务质量；
协助大区经理做好当地医保目录工作；
高级医药代表有责任协助医药代表完成销售工作，并指导新代表的医院拜访工作。
工作地址：
江苏-宜兴
查看职位地图
**********
费森尤斯卡比（中国）
公司规模：
1000-9999人
公司性质：
外商独资
公司行业：
医药/生物工程
公司主页：
https://www.fresenius-kabi.com/cn/index
公司地址：
北京市朝阳区太阳宫中路16号院冠捷大厦17层;
**********
机械工程师
无锡钧弘自动化科技有限公司
五险一金绩效奖金通讯补贴带薪年假定期体检免费班车员工旅游节日福利
**********
福利:
五险一金
绩效奖金
通讯补贴
带薪年假
定期体检
免费班车
员工旅游
节日福利
**********
职位月薪：3500-4500元/月 
工作地点：无锡
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：1人
职位类别：机械工程师
**********
岗位职责：
1.与客户/供应商就产品的开发过程中的质量/技术/工艺/生产等问题进行跟踪。
2.与供应商密切沟通联系，关注掌控电机新品开发项目的进展。
3.对电机的对外出口销售进行全方位的技术支持。
4.请在微信公众号中关注 “无锡钧弘”， 了解更多招聘信息。

任职要求：
1.机械类专业毕业，熟悉或了解直流/无刷电机。
2.能熟练使用CAD等及Solidworks软件。
3.熟悉机械零件的材料性能和加工工艺。
4.根据开发计划督导各生产协作部门完成开发任务。
5.具有一定的沟通能力。
6.具有较强的团队合作精神及敬业精神，善于协调与其他部门关系。

工作地址：
无锡市光电园会北路28-94号
查看职位地图
**********
无锡钧弘自动化科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
仪器仪表及工业自动化
公司主页：
www.exmek.com
公司地址：
无锡市光电园会北路28-94号
**********
体系工程师
无锡祥生医疗科技股份有限公司
**********
福利:
**********
职位月薪：6001-8000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：1人
职位类别：认证/体系工程师/审核员
**********
体系专员
岗位职责：
1、  负责公司质量管理体系、环境体系运行、维护，法律、法规收集传递的控制工作；
2、  负责国内、欧盟、美国、加拿大等国家与地区医疗器械有关法规的获取确认，并能够实时转换为公司的质量体系文件；
3、  负责组织环境目标指标及管理方案制定，并负责监督检查；
4、  负责组织内审员内部运行体系的的审核以及审核前后相关文件的编制与汇总；
5、  负责组织各部门完成各级药监局、CMD、CE、FDA等第三方机构的外部审核，产品认证及体系认证的换证工作；
6、  负责组织并指导公司各部门完成外审、内审发现不合格的整改工作；
7、  负责对各种运行体系文件进行评审，对不符合运行实际情况的进行补充改进；
8、  协助管理者代表处理不良事件、警戒体系、MDR事件的相关工作；
9、  负责法律法规以及质量体系的培训与考核工作；
10、领导交代的其他工作。
任职要求：
1、  本科（含）以上学历，生物医学工程、计算机、电子类等相关专业优先，3年以上质量体系管理工作经验。英语水平良好；
2、  熟悉ISO9001，ISO13485和ISO14001管理体系，熟练编写质量体系文件，具有ISO9001，ISO13485和ISO14001内审员证书；
3、工作认真负责，严谨细致，有较强的分析解决问题能力；
4、良好的文字功底及良好的计划、组织、协调、沟通能力；
5、熟练使用办公软件；
6、做事客观、严谨负责、踏实、敬业；
7、工作细致认真，谨慎细心、责任心强，具有良好的职业道德和职业操守；
8、具有很强的人际沟通协调能力，团队意识强。

工作地址：
无锡新区新辉环路9号
查看职位地图
**********
无锡祥生医疗科技股份有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医疗设备/器械
公司主页：
www.chison.com.cn
公司地址：
无锡新区新辉环路9号
**********
.Net软件工程师
无锡祥生医疗科技股份有限公司
五险一金绩效奖金包吃带薪年假免费班车
**********
福利:
五险一金
绩效奖金
包吃
带薪年假
免费班车
**********
职位月薪：8000-13000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：6人
职位类别：软件工程师
**********
岗位职责：
1、主要负责设计、开发Windows操作系统下的超声应用软件
2、开发相关的单元测试代码
3、撰写相关的开发文档等
任职资格：
1、2年及以上工作经验
2、熟练使用Microsoft .NET，C#，WPF等技术开发软件
3、有DICOM相关工作经验，或者医疗设备开发相关经验优先考虑
4、大专及以上，计算机专业

工作地址：
无锡新区新辉环路9号
**********
无锡祥生医疗科技股份有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医疗设备/器械
公司主页：
www.chison.com.cn
公司地址：
无锡新区新辉环路9号
查看公司地图
**********
科技服务事业部渠道销售
微分(上海)基因科技有限公司
创业公司五险一金交通补助通讯补贴带薪年假节日福利定期体检
**********
福利:
创业公司
五险一金
交通补助
通讯补贴
带薪年假
节日福利
定期体检
**********
职位月薪：6001-8000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：硕士
招聘人数：5人
职位类别：销售代表
**********
岗位职责：
1、渠道客户挖掘及客户关系维护；
2、根据客户需求提供项目解决方案，负责项目签订；
3、跟进项目进展，促进项目顺利进行
4、积极了解并反馈市场需求、产品竞争等情况；
5、能够独立完成销售回款任务。
任职资格：
1、硕士学历，生物、农学、医学相关专业，有高通量测序销售经验者优先；
2、学习过遗传学、分子生物学、基因工程原理等相关课程，有分子生物学实验经验；
3、性格开朗，亲和力强，反应敏捷，具备较强的沟通表达能力，抗压能力强；
4、执行力强，工作认真负责，具备团队协作精神
公司地址：
上海：宝山区同济支路199号3号楼501室
北京：丰台区宋家庄扑满山2号楼1806
安徽：巢湖市经济技术开发区半汤镇龙泉路未名医药园C楼
工作地点：全国

工作地址：
全市
查看职位地图
**********
微分(上海)基因科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医药/生物工程
公司地址：
上海市宝山区同济支路3号楼501室
**********
销售代表
无锡钧弘自动化科技有限公司
五险一金绩效奖金餐补带薪年假定期体检免费班车节日福利
**********
福利:
五险一金
绩效奖金
餐补
带薪年假
定期体检
免费班车
节日福利
**********
职位月薪：3000-5000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：2人
职位类别：大客户销售代表
**********
岗位职责：
1.从事微特电机产品的OEM项目销售，客户维护，项目沟通；
2.勤奋踏实，能适应高效快节奏的工作，有团队合作精神。

岗位要求：
1.年龄不限，机械类或者电机专业；
2.具备基本的机械加工知识，有机械电子类产品的项目销售经验；
2.熟练掌握各种办公软件的使用，有外贸专业知识的优先；

工作地址：
胡埭联合路10号
查看职位地图
**********
无锡钧弘自动化科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
仪器仪表及工业自动化
公司主页：
www.exmek.com
公司地址：
无锡市光电园会北路28-94号
**********
江浙沪区域销售总监
江苏达实久信医疗科技有限公司
五险一金绩效奖金
**********
福利:
五险一金
绩效奖金
**********
职位月薪：6001-8000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：区域销售总监
**********
1、负责整个区域市场的开发，需有医疗工程或者大型医疗设备的工作经历，不能频繁更换工作，有特殊背景的可以优先考虑；
2、熟知区域内的医院动态，能单独与院长或者副院长进行沟通交流，并达成项目；
3、本岗位待遇丰厚，但要求也高，请在投简历时仔细研读第一和第二条。
上市公司深圳达实旗下子公司江苏久信欢迎你的加入。

工作地址：
常州市新北区汉江西路103号
**********
江苏达实久信医疗科技有限公司
公司规模：
500-999人
公司性质：
股份制企业
公司行业：
房地产/建筑/建材/工程
公司主页：
http://www.jxmed.com
公司地址：
常州市新北区汉江西路103号
查看公司地图
**********
电源工程师
无锡祥生医疗科技股份有限公司
**********
福利:
**********
职位月薪：15000-20000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：1人
职位类别：硬件工程师
**********
岗位职责：
1.负责超声产品DC-DC电源的开发工作；
2.负责电源单板测试及整机联调；
3.负责电源的可靠性测试工作。
4.负责电池和适配器的选型和测试工作"

岗位要求：
1. 本科以上学历，电子，通信，计算机，生物医学相关专业；
2. 三年以上硬件开发经验；
3. 有较好的硬件相关基础知识（数字电路、模拟电路），对BUCK/BOOST开关电源具有深入的研究和一定的开发经验；
4.熟悉电池充放电电路和电池安全和可靠性测试
5. 熟悉低噪声电源设计方法和电源噪声测试设备，有高压DC-DC电源、高压LDO设计经验者尤佳；
6. 熟练使用原理图/PCB等EDA开发工具，对PCB布局布线、电源回路控制等有一定的了解；
7. 具有强烈的责任心及团队合作精神，具有较好的沟通及协调能力；
8. 具有超声行业经验者优先，具有知名企业工作经验者优先。"

工作地址：
无锡新区新辉环路9号
**********
无锡祥生医疗科技股份有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医疗设备/器械
公司主页：
www.chison.com.cn
公司地址：
无锡新区新辉环路9号
查看公司地图
**********
软件工程师
无锡安之卓医疗机器人有限公司
交通补助餐补通讯补贴弹性工作
**********
福利:
交通补助
餐补
通讯补贴
弹性工作
**********
职位月薪：15000-30000元/月 
工作地点：无锡
发布日期：最近
工作性质：全职
工作经验：5-10年
最低学历：大专
招聘人数：2人
职位类别：软件工程师
**********
职位描述：
1、负责机器人控制软件的系统设计、架构设计和模块设计；
2、编写软件总体设计方案、模块设计方案、测试大纲等开发文档；
3、负责软件代码编写、验证及优化；
4、分析并解决软件相关的问题并优化系统性能；

任职要求：
1、具有较强的产品前瞻性，能够独立设计机器人控制软件；
2、具有5年以上机器人或自动化控制软件设计和开发经验；
3、熟练应用CanOpen、Modbus、XMPP、MQTT等通信协议；
4、精通基于Linux的C\C++开发嵌入式软件开发；
5、熟练使用QT、Gcc+Gdb+Vim等开发环境；
6、有嵌入式软件开发经验者优先考虑；
7、有医疗设备信息化经验者优先。

工作地址：
无锡惠山经济开发区锦惠路10号
**********
无锡安之卓医疗机器人有限公司
公司规模：
100-499人
公司性质：
合资
公司行业：
医药/生物工程
公司地址：
无锡惠山经济开发区锦惠路10号
查看公司地图
**********
外贸主管（工作地：上海）
武汉协卓卫生用品有限公司
五险一金绩效奖金带薪年假员工旅游节日福利
**********
福利:
五险一金
绩效奖金
带薪年假
员工旅游
节日福利
**********
职位月薪：15001-20000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：5人
职位类别：外贸/贸易经理/主管
**********
任职要求：
1、英语，俄语，西班牙语，阿拉伯语，国际贸易，市场营销，医疗器械等专业大学专科及以上学历；
2、一年以上外贸业务实操经验，良好的商务英语基础，口语流利，优秀应届毕业生也可以放宽条件；
3、医疗器械/耗材、医药，保健品，医用敷料，快速消费品，日用品，零售外贸行业经验者优先；
4、熟练操作电子商务平台，熟悉各种外贸平台的使用及推广工具；
5、较强的业务沟通和谈判能力，能主动寻找资源开发客户并挖掘客户的潜在需求；
6、工作积极主动，善于学习，做事有良好的计划性和条理性；
7、良好的沟通和谈判协调能力，有团队合作精神。
岗位职责：
1、根据公司及部门规划，完成年度销售目标；
2、具备独立的营销思路，负责国外市场的开拓、客户开发、订单管理，参加国内外展会；
3、负责对目标市场及产品进行相关的市场分析及评估，提出销售策略，并为公司新产品开发提出合理的指引和建议。
4、优化公司贸易业务的操作流程及管理制度
Job requirements:
1, English, Russian, Spanish, Arabic, international trade, marketing, medical equipment and other professional college degree and above;
2, More than one year experience in foreign trade business, a good business English foundation, fluent in spoken language, outstanding graduates can also relax the conditions;
3, Medical equipment / supplies, medicine, health care products, medical dressings, fast moving consumer goods, daily necessities, retail trade experience is preferred;
4, Skilled operation of e-commerce platform, familiar with the use of various foreign trade platform and promotional tools;
5, Strong business communication and negotiation ability, can take the initiative to find resources to develop customers and tap the potential needs of customers;
6,The work of a proactive, good at learning, doing things have a good planning and rational;
7, Good communication and negotiation coordination ability, team spirit.
Job Responsibilities:
1, According to the company and department planning, to complete the annual sales target;
2, With independent marketing ideas, responsible for the development of foreign markets, customer development, order management, to participate in domestic and international exhibitions;
3, Responsible for the target market and product related market analysis and assessment, put forward sales strategy, and for the company's new product development and put forward reasonable guidelines and recommendations.
4, To optimize the company's business operations and management system management system

工作地址：
上海普陀武宁路501号鸿运大厦
**********
武汉协卓卫生用品有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
农/林/牧/渔
公司地址：
武汉市江汉区沿江大道69号长航大厦1803室
**********
OTC销售经理
民康医疗科技(天津)有限公司
五险一金绩效奖金交通补助餐补通讯补贴定期体检员工旅游节日福利
**********
福利:
五险一金
绩效奖金
交通补助
餐补
通讯补贴
定期体检
员工旅游
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：不限
招聘人数：3人
职位类别：渠道/分销专员
**********
岗位职责：
1、负责区域内的市场开发、客户维护和销售管理等工作；
2、负责区域内的产品宣传、推广和销售，完成销售的任务指标；
3、制定自己的销售计划，并按计划拜访客户和开发新客户；
4、搜集与寻找客户资料，建立客户档案；
5、协助区域销售经理制定销售策略、销售计划，以及量化销售目标；
6、接待来访客户，以及综合协调日常销售事务。
 任职要求：
1、大专以上学历，生物医药专业背景优先；
2、工作勤奋主动，具有良好的团队合作意识；
3、热爱销售行业，有激情，勤奋，能够有效开发客户资源；
 无责任底薪，试用期三个月，销售提成另计，公司提供岗前培训、五险、双休.
餐补、交通补助按公司销售制度执行.

工作地址：
天津市经济技术开发区海云街80号17号融通大厦4层
**********
民康医疗科技(天津)有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医疗设备/器械
公司主页：
http://www.minkangyiliao.com/
公司地址：
天津市经济技术开发区海云街80号17号融通大厦4层
查看公司地图
**********
销售代表/渠道
安派科生物医学科技(上海)有限公司
五险一金绩效奖金节日福利定期体检
**********
福利:
五险一金
绩效奖金
节日福利
定期体检
**********
职位月薪：5000-8000元/月 
工作地点：无锡-宜兴市
发布日期：最近
工作性质：全职
工作经验：1-3年
最低学历：不限
招聘人数：1人
职位类别：销售代表
**********
岗位职责：
1、在辖区内医院进行公司产品的推广销售，完成销售任务；
2、根据需要拜访医护人员，向客户推广产品，不断提高产品市场份额；
3、开拓潜在的医院渠道客户，并对既有的客户进行维护；
4、充分了解市场状态，及时向上级主管反映竟争对手的情况及市场动态、提出合理化建议；
5、制定并实施辖区医院的推销计划，组织医院内各种推广活动；
6、树立公司的良好形象， 对公司商业秘密做到保密。
任职资格：
1、专科及以上学历，医药、营销类相关专业；
2、2年以上销售工作经验，有医疗器材、耗材、药品销售经验者优先；
3、有医院销售经验，熟悉医院工作流程，拥有良好的医院资源和销售渠道，热爱药品销售服务工作；
4、具有较强的独立工作能力和社交技巧，较好的沟通能力、协调能力和团队合作能力；
5、身体健康，具有独立分析和解决问题的能力。

工作地址：
宜城街道
查看职位地图
**********
安派科生物医学科技(上海)有限公司
公司规模：
20-99人
公司性质：
合资
公司行业：
医药/生物工程
公司主页：
null
公司地址：
上海市张江高科技园区芳春路400号1幢301-346室
**********
区域销售（江苏）
北京思创贯宇科技开发有限公司
每年多次调薪五险一金绩效奖金年终分红带薪年假
**********
福利:
每年多次调薪
五险一金
绩效奖金
年终分红
带薪年假
**********
职位月薪：8001-10000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：区域销售专员/助理
**********
主要职责：
1、负责公司全线产品在本区域内医院终端销售工作；
2、通过对终端的直接拜访，客户演示体验，激发和收集客户原始需求，并将客户需求直接反馈到公司销售运营部；
3、对本区域内大客户的发掘、销售工作负总责，要求和目标客户建立良好关系，挖掘客户对公司产品线的需求，高效、灵活地完成销售任务。

任职要求：
1、专科以上学历，医学或市场营销相关专业，
2、有医疗器械行业销售经验，影像类产品销售经验者优先；
3、具有一定的项目销售经验，有成功大项目经验者优先；
4、对销售具有高度热情，勤奋，真诚，抗压能力强。
工作地址：
江苏
查看职位地图
**********
北京思创贯宇科技开发有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医疗设备/器械
公司主页：
http://www.crealifemed.com
公司地址：
北京海淀区紫竹院路81号北方地产大厦二层
**********
软件实施工程师
蝶和科技(中国)有限公司
五险一金交通补助餐补带薪年假
**********
福利:
五险一金
交通补助
餐补
带薪年假
**********
职位月薪：4001-6000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：售前/售后技术支持工程师
**********
岗位职责：
1.独立完成项目的实施，包括设备的安装，调试，软件接口联调，培训以及问题处理；
2.了解和掌握客户需求，与团队人员沟通甚至独立完成需求调研、需求分析、解决方案的编制；
3.实时把控项目进度，处理客户的服务请求，解答客户疑问，维护客户关系，提高客户满意度；
4.工作积极主动，具有团队合作精神；
5.定期总结项目遇到的问题，做到及时反馈。
   
任职要求：
1.大专及以上学历；
2.软件实施两年及以上工作经验；
3.算机、软件工程相关专业，熟悉Mysql，SqlServer，Oracle数据库开发，能建立视图、存储过程、函数等各类数据库对象，熟悉C#语言优先考虑；
4.团队意识强，工作积极主动，能承受较大压力；能适应出差。

工作地址：
菱湖大道200号G8栋
**********
蝶和科技(中国)有限公司
公司规模：
500-999人
公司性质：
外商独资
公司行业：
医疗设备/器械
公司主页：
null
公司地址：
北京市丰台区丰茂路汉威国际广场6号楼7层
**********
华东大区总监（CEMS/VOCS/水质监测）
安徽皖仪科技股份有限公司
五险一金绩效奖金包吃
**********
福利:
五险一金
绩效奖金
包吃
**********
职位月薪：15001-20000元/月 
工作地点：无锡
发布日期：最近
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：销售总监
**********
中高层销售管理岗位：
岗位职责：
1、负责所管辖区域（省份）关键客户的开发及重大项目管理；
2、负责所管辖区域（省份）的市场规划、营销模式的建立； 
3，制定所管辖区域（省份）营收规划和损益分析；
4，负责区域团队得管理；
5，负责区域目标的分解，并按周、月进行校验；
6、全面负责区域的业务管理，确保该区域业务KPI的达成。

任职要求：
1、本科及以上学历，专业不限； 
2、八年以上销售管理经验，有环保产品销售经验及环保局相关资源优先； 
3、很强的客户公关能力和市场开拓能力； 
4、有很强的全局观，市场分析规划能力及营销管理能力； 
5、具备一定的经营管理能力和团队管理经验； 
6、具备良好的职业操守和综合素质，极强的责任心和端正的工作态度。
年薪：50W
工作地址：
安徽省合肥市高新区文曲路8号
**********
安徽皖仪科技股份有限公司
公司规模：
500-999人
公司性质：
民营
公司行业：
仪器仪表及工业自动化
公司主页：
http://www.wayee.cn
公司地址：
安徽省合肥市高新区文曲路8号
**********
汽车零部件供应商-项目经理
普梅尔森管理咨询(北京)有限公司
**********
福利:
**********
职位月薪：10001-15000元/月 
工作地点：无锡
发布日期：最近
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：1人
职位类别：项目经理/项目主管
**********
我的客户是一家汽车行业公司，主要生产汽车注塑机，合作的客户包括麦格纳、泽等汽车行业厂商，目前公司办公地点在江苏镇江，主要客户以海外汽车客户为主。现由于业务的快速增长，急需一位项目经理，要求英文流利，能和国外客户沟通。
岗位职责：
1、组织进行新产品、新项目前期的可行性分析并输出可行性研究报告；
3、管理项目团队，制定项目计划并进行全过程监控，包括进度、成本、质量、干系
4、控制内外部提出的变更需求；
5、对重点项目和产品在生产、应用中反映出来的问题，组织进行优化立项。

任职要求：
1、全日制本科及以上学历；
2、汽车行业项目管理工作经验2年以上，熟悉16949，APQP
3、流利的英文能力，需要和国外客户对接

工作地址：
江苏镇江
**********
普梅尔森管理咨询(北京)有限公司
公司规模：
20人以下
公司性质：
股份制企业
公司行业：
专业服务/咨询(财会/法律/人力资源等)
公司主页：
www.thepromotion.com.cn
公司地址：
北京市朝阳区国贸桥光华东里8号院中海广场南楼12层
查看公司地图
**********
江苏省销售经理（无菌产品）
南京天纵易康生物科技股份有限公司
五险一金绩效奖金年终分红交通补助餐补通讯补贴带薪年假弹性工作
**********
福利:
五险一金
绩效奖金
年终分红
交通补助
餐补
通讯补贴
带薪年假
弹性工作
**********
职位月薪：4001-6000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：2人
职位类别：销售代表
**********
岗位职责：
1、负责执行公司销售政策及策略，完成指定的销售指标.
2、制定年度重点客户的发展战略，参与重点客户年度合作协议的谈判。协调处理客户间的关系。
3、负责管理对代理商的遴选与评估工作，督促销售进度，并为代理商提供销售支持和服务；
任职要求：
1、市场营销、医药相关专业大专以上学历，有1年以上皮肤科产品销售经验；
2、熟悉所管辖内的医疗器械市场运营特点。
3、具有较强的沟通能力和组织协调能力。
4、热爱销售工作，责任心强，具有敬业精神及团队精神。
5、优秀的管理能力和敏锐的市场洞察力。
工作地址：
江苏苏南
查看职位地图
**********
南京天纵易康生物科技股份有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医药/生物工程
公司主页：
www.njtzone.com
公司地址：
南京浦口高新区星火路10号人才大厦1-3层
**********
会计主管
无锡祥生医疗科技股份有限公司
**********
福利:
**********
职位月薪：8001-10000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：1人
职位类别：会计经理/主管
**********
岗位职责
1、  负责公司日常财务核算和处理，按规定及时进行报税工作；
2、  负责相关税收优惠的备案；
3、  负责工资核算、费用报销，银行账户、发票等管理；
4、  负责对公司向项目票据、资产盘点机财务制度执行情况的检查；
5、  负责财务以及各类统计表表的编制与会计档案的管理，向财务经理提供必要的财务分析；
6、  负责配合各类审计工作；
7、  领导交办的其他事项。
岗位要求
1. 统招类财务、会计专业本科学历，2年以上会计主管管理经验；
2. 熟练使用新中大及SAP财务软件；
3. 具有独立工作和学习的能力，工作认真细心；
4. 良好的组织、协调、沟通能力和团队协作精神，能承受较大的工作压力；
5. 英语能力较好。

工作地址：
无锡新区新辉环路9号
**********
无锡祥生医疗科技股份有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医疗设备/器械
公司主页：
www.chison.com.cn
公司地址：
无锡新区新辉环路9号
查看公司地图
**********
生产组长（康复）
蝶和科技(中国)有限公司
五险一金绩效奖金交通补助餐补通讯补贴
**********
福利:
五险一金
绩效奖金
交通补助
餐补
通讯补贴
**********
职位月薪：4001-6000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：中专
招聘人数：1人
职位类别：生产主管/督导/组长
**********
岗位职责：
1.根据生产计划，合理优化人力分配，有效利用资源完成生产任务。
2.熟悉产品的工艺流程，遵守及监督员工按照生产工艺要求进行作业，确保所负责产品线的质量、交期符合客户需求。
3.按照作业指导书和工艺过程控制卡进行设备的装配，并做好相应的记录，确保生产过程符合质量体系要求。
4.参与质量体系内审、外审、产品注册审核等，确保通过各项审核工作。
5.参与新产品导入过程中的设备试装，并能够进行学习，为批量生产做准备；在大批量生产的时候能够快速的培训员工并带领团队完成产能扩充。
6.参与持续改进活动，包括能够对产品提出工艺改善意见、工装夹具的改善、流程改善、提升组装效率等等。
7.完成上级安排的其它任务。

岗位要求：
1. 中专或以上学历，三年以上机电一体化设备的生产或测试工作经验，一年以上同岗位经验。
2. 有医疗设备工作经验优先。
3. 有外企工作经验优先。
4. 熟悉ISO9001、ISO13485质量体系。
5. 具有机械基础知识，包括识图、公差配合、测量等。
6. 能够根据机械装配图纸独立进行装配。
7. 能够根据电子装配接线图独立进行电子电路板的装配。
8. 熟悉生产管理流程。

工作地址：
新吴区菱湖大道200号G8栋
**********
蝶和科技(中国)有限公司
公司规模：
500-999人
公司性质：
外商独资
公司行业：
医疗设备/器械
公司主页：
null
公司地址：
北京市丰台区丰茂路汉威国际广场6号楼7层
**********
高级采购专员
无锡祥生医疗科技股份有限公司
**********
福利:
**********
职位月薪：6001-8000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：采购专员/助理
**********
一、岗位要求：
1、具有大专及以上学历，工科背景优先；
2、5年以上采购相关工作经验，能够适应质量和交期问题出差到供应商车间现场跟线；
3、熟悉MRO和注塑件的采购流程，能看懂CAD图纸；
4、熟悉ERP采购流程，有SAP使用经历优先。
5、具有一定的成本概率，工作责任心强，团队意识强，协调能力好，具有分析能力和独立处理问题能力。
6、具有良好的个人与商业道德。
二、职位描述：
1、主要负责公司的MRO、非标设备、注塑件的采购，以及结构件质量和交期问题出差到供应商车间现场跟线；
2、与供应商进行日常工作交流与沟通，保证物料正常供应满足生产需求，协助相关人员解决物料检验或者使用中出现的质量问题，对不合格品进行退货处理。
3、根据月生产计划，周生产计划，跟踪物料进、存、销情况，月底统计生产、采购执行情况向主管汇报工作进程；
4、按月对采购相关文件进行整理归档，包括采购合同、采购计划、采购订单、检验通知单、退货通知单等；
5、月底前跟供应商做好对账工作，保证当月发生的业务当月开票进账。
6、积极完成上级领导布置相关工作。

工作地址：
无锡新区新辉环路9号
**********
无锡祥生医疗科技股份有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医疗设备/器械
公司主页：
www.chison.com.cn
公司地址：
无锡新区新辉环路9号
查看公司地图
**********
生产计划专员/主管
蝶和科技(中国)有限公司
五险一金加班补助交通补助餐补带薪年假
**********
福利:
五险一金
加班补助
交通补助
餐补
带薪年假
**********
职位月薪：6001-8000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：生产计划
**********
岗位职责：
1.根据公司的销售目标，合理安排生产计划和物料采购，以保证产品的及时供应；
2.协同生产车间，进行产能规划与分析；平衡需求与供应；
3.处理和应对紧急或突发情况；
4.优化与改善库存，保证库存处于合理水平；
5.供应商管理，协同优化和改善采购零件的采购期。

任职要求：
1.大专及以上学历，理工背景优先；
2.5年以上PMC工作经验；
3.能够熟练运用ERP系统；
4.熟练运用Excel、Word等办公软件；
5.英语读写良好；
6.有较好的部门间沟通协调能力；
7.有日韩企业工作经验者尤佳。

工作地址：
菱湖大道200号G8栋
**********
蝶和科技(中国)有限公司
公司规模：
500-999人
公司性质：
外商独资
公司行业：
医疗设备/器械
公司主页：
null
公司地址：
北京市丰台区丰茂路汉威国际广场6号楼7层
**********
高级网络工程师
普梅尔森管理咨询(北京)有限公司
**********
福利:
**********
职位月薪：10000-17000元/月 
工作地点：无锡
发布日期：最近
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：网络工程师
**********
国内著名光伏产品和光伏解决方案提供商，全球新能源企业500强排名前20。目前招聘BI高级工程师，待遇从优。
注：该职位办公地点位于常州

工作职责：
1、企业内部网络建设和管理；进行网络架构的规划、设计、调整、性能优化；
2、网络设备的配置，管理；网络环境的管理、配置、排错、维护，提供网络设备维护方案；；
3、网络项目的实施、协调、管理；
4、负责全球公司及工厂的网络核心设备及接入设备的日常运维管理
5、建立完整的网络系统文档；
6、网络安全，网络质量及网络设备的监控；
7、完成部门主管要求的各项工作，协助其他部门完成相应的工作任务

任职要求：
1、5年以上大、中型企业网络管理维护经验                   
2、精通思科45、65系列核心交换布署及配置    
3、精通OSPF、BGP等路由协议  
4、精通思科防火墙及无线控制器的配置维护
5、具有IT相关项目的管理经验              
6、计算机专业本科学历
7、英文能够满足日常交流
8、具有思科CCNP证书优先考虑

工作地址：
江苏常州
**********
普梅尔森管理咨询(北京)有限公司
公司规模：
20人以下
公司性质：
股份制企业
公司行业：
专业服务/咨询(财会/法律/人力资源等)
公司主页：
www.thepromotion.com.cn
公司地址：
北京市朝阳区国贸桥光华东里8号院中海广场南楼12层
查看公司地图
**********
产品工程师-IT-江苏
中建材信息技术股份有限公司
五险一金年底双薪交通补助通讯补贴补充医疗保险定期体检员工旅游节日福利
**********
福利:
五险一金
年底双薪
交通补助
通讯补贴
补充医疗保险
定期体检
员工旅游
节日福利
**********
职位月薪：8001-10000元/月 
工作地点：无锡
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：5人
职位类别：售前/售后技术支持工程师
**********
岗位职能描述：
发掘项目、根据客户需求，匹配华为服务器、存储、云计算等产品优势，提供最佳解决方案、以及售前测试、技术交流、投标，对客户培训赋能，市场宣传推广相关产品和方案。与销售搭档配合完成市场销售任务目标。

素质技能要求：
1. 需具备本科学历（有同行业丰富经验者可适当降低到大专学历），必须具备所属产品线基本知识和通过相关技术考核，具备HCNA\HCNP认证优先；
2. 有良好的客户沟通、需求分析能力，能够根据客户需求撰写相关产品技术方案，；
3. 有积极乐观的工作态度和生活态度、责任心强，有良好的敬业精神，合作态度和团队精神；
4. 了解主流厂商的技术、产品、方案，熟悉华为IT产品者优先。

联系人
chenfengting@cnbmtech.com;hanjun@cnbmtech.com
工作地址：
江苏各个地市
查看职位地图
**********
中建材信息技术股份有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
计算机硬件
公司主页：
http://www.cnbmtech.com/
公司地址：
北京市海淀区首体南路9#主语商务中心4号楼18层1801
**********
机械工程师 (无锡）
法国液化空气集团
五险一金餐补带薪年假补充医疗保险定期体检节日福利绩效奖金
**********
福利:
五险一金
餐补
带薪年假
补充医疗保险
定期体检
节日福利
绩效奖金
**********
职位月薪：7000-9000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：1人
职位类别：机械工程师
**********
工作内容 Job Responsibilities： 
1. Responsible for daily Equipment operation and troubleshooting on site 
保证工厂日常机器设备的正常运行，及时解决故障 
2. Establish PM and ensure the PM complete in time 
维修计划的制定和执行 
3. Maintain, update, analyze maintenance records then try to improve the efficiency. 
维护、更新、分析维修数据，改进维修效率； 
4. Study and analyze troubleshooting cases to remove the root cause and avoid reappearance 
分析故障根本原因并预防再次发生； 
5. Responsible for monitoring the workload and work quality of subcontractor. 
管理供应商； 
6. Spare Parts management; keep adequate spare parts and consumable 
备品备件管理，保证有足够的备品备件。 
7. Responsible for SHE 
保证安全生产无事故 

要求 Job Requirement： 
1. 自动化 / 机电类专业大专以上学历； 
College degree or above and major in mechanical or related
2. 5年以上设备维修领域维修维护经验，3年以上化工行业工厂工作经验，了解气体行业优先； 
About 5 years working experiences in equipment maintenance, At least 3 years maintenance experience in chemical industry, know about gas industry will be a plus 
3. 了解国家相关法律法规，并具备相应资格证； 
Know about related policy and have related certificate 
4. 较强的学习能力，分析能力，计划和执行能力； 
With strong learning, analytical ability, well planning and executive capability
5. 英文良好； 
Good in English both written and reading

工作地址：
无锡新区出口加工区
查看职位地图
**********
法国液化空气集团
公司规模：
1000-9999人
公司性质：
外商独资
公司行业：
石油/石化/化工
公司主页：
http://www.airliquide.com
公司地址：
上海市古美路1515号18号楼
**********
技术员
蝶和科技(中国)有限公司
五险一金绩效奖金交通补助餐补通讯补贴带薪年假
**********
福利:
五险一金
绩效奖金
交通补助
餐补
通讯补贴
带薪年假
**********
职位月薪：3800-4500元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：中专
招聘人数：1人
职位类别：技工
**********
岗位职责：
1.独立完成产品的生产装配，符合工艺要求；
2.在生产过程中严格执行工艺和质量规程的要求，符合质量控制标准；
3.对现场的异常情况及时反映及上报；
4.执行6S管理规定，做好日常6S保持工作；
5.完成领导交付的其它任务。
常白班，双休，有餐贴、车贴

任职要求：
1.中专或以上学历，机电一体化专业优先；
2.有2年以上工作经验，设备装配行业或生产制造型企业经验优先；
3.具有一定机械、电气常识和制图方面的知识；
4.工作认真负责，吃苦耐劳及服从安排。

工作地址：
菱湖大道200号G8栋
**********
蝶和科技(中国)有限公司
公司规模：
500-999人
公司性质：
外商独资
公司行业：
医疗设备/器械
公司主页：
null
公司地址：
北京市丰台区丰茂路汉威国际广场6号楼7层
**********
CT维修工程师
凯思轩达医疗科技无锡有限公司
五险一金绩效奖金交通补助通讯补贴补充医疗保险节日福利
**********
福利:
五险一金
绩效奖金
交通补助
通讯补贴
补充医疗保险
节日福利
**********
职位月薪：6000-12000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：医疗器械维修/保养
**********
维修保养公司在保客户（医院）的大型设备CT（东芝、西门子），保证机器正常运行。
岗位要求：
1、大专以上学历，计算机、电器工程及其自动化、电子信息技术工程等与电子、医用电子仪器维修、医学影像工程、机械相关的工科类专业，有经验者优先录用；
2、熟悉计算机软硬件的操作，英语熟练；
3、服从公司分配，根据公司需要出差，诚实、好学、勤奋。

工作地址：
广州天河区五山路246号金山大厦南塔28楼
**********
凯思轩达医疗科技无锡有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医疗设备/器械
公司地址：
广州天河区五山路246号金山大厦南塔28楼
**********
BI高级工程师
普梅尔森管理咨询(北京)有限公司
**********
福利:
**********
职位月薪：10000-17000元/月 
工作地点：无锡
发布日期：最近
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：1人
职位类别：数据库开发工程师
**********
国内著名光伏产品和光伏解决方案提供商，全球新能源企业500强排名前20。目前招聘BI高级工程师，待遇从优。

注：该职位办公地点位于常州

工作职责：
1. 负责BI报表的开发和维护，满足客户业务部门各种需求；
2. 参与数据挖掘分析、整理、建模等工作；
3. 参与EDW数据模型设计；
4. 参与大数据平台ETL等相关开发工作；
5. 完成大数据平台的日常管理及运维、业务用户培训、应用推广等；
6. 完成上级临时指派的其他工作；

任职要求：
1. 本科及以上学历，2年以上工作经验有BI项目的需求分析、设计、开发经验；
2. 精通QlikView、Tableau、BO、Cognos 等至少一种BI工具；
3. 精通至少一种主流数据库（Oracle、Mysql、DB2等），SQL基础扎实；
4. 精通数据仓库概念和数据仓库项目的实施流程者优先；
5. 有大数据工具(Hadoop, Hive，Hbase、Spark等)和数据建模经验者优先；
6. 有ETL开发经验优先；
7.有BI项目经验
8. 具备较强的数学和数据挖掘功底，统计学、应用数学相关专业优先。
9. 对数据敏感，思维逻辑清晰，具有良好的数据分析能力；
10. 具有良好的沟通表达能力，能够和业务人员高效沟通；
工作地址：
江苏常州
**********
普梅尔森管理咨询(北京)有限公司
公司规模：
20人以下
公司性质：
股份制企业
公司行业：
专业服务/咨询(财会/法律/人力资源等)
公司主页：
www.thepromotion.com.cn
公司地址：
北京市朝阳区国贸桥光华东里8号院中海广场南楼12层
查看公司地图
**********
项目经理
无锡祥生医疗科技股份有限公司
五险一金绩效奖金带薪年假免费班车包吃
**********
福利:
五险一金
绩效奖金
带薪年假
免费班车
包吃
**********
职位月薪：7000-9000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：3人
职位类别：项目经理/项目主管
**********
工作职责：
1、项目前期的预研；
2、负责新产品项目进行过程中的进度、成本控制等，项目进展过程中问题汇总以及跟踪解决；
3、配合产品注册相关工作；
4、完成产品的研发阶段、设计转生产的工作。

要求：
1、电子专业背景，本科学历；
2、熟练使用办公软件，了解硬件设计开发优先；
3、5年以上工作经验，有2年项目参与、管理工作经验，有医疗器械产品相关经验优先；
4、积极主动、严谨，良好的团队凝聚力和团队合作精神，良好的学习能力和沟通能力；
5、良好的英文读写能力，口语优秀者优先

工作地址：
无锡新区新辉环路9号
**********
无锡祥生医疗科技股份有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医疗设备/器械
公司主页：
www.chison.com.cn
公司地址：
无锡新区新辉环路9号
查看公司地图
**********
Linux软件工程师
无锡祥生医疗科技股份有限公司
五险一金免费班车节日福利年底双薪带薪年假
**********
福利:
五险一金
免费班车
节日福利
年底双薪
带薪年假
**********
职位月薪：8000-15000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：5人
职位类别：软件工程师
**********
要求：
1）计算机科学相关专业本科及以上学历，有Linux操作系统下软件项目编程的工作经验，或者比较优秀的应届毕业生也可
2）对嵌入式Linux操作系统比较熟悉，对Linux操作系统的内核有一定的理解
3）对于Qt或者Gtk+等GUI开发库能够熟练运用，或者熟悉其它嵌入式Linux下GUI开发工具也可
4）对医学影像软件和DICOM通信标准有一定的了解的可优先考虑
任职要求：
1. 大专及以上计算机相关专业，3年及以上工作经验；
2. 对嵌入式Linux操作系统及相关开发有深入理解；对面向对象、设计模式及C++语言有深入的理解；对Qt应用程序开发有实际的工作经验；
3. 有DICOM相关工作经验，或者医疗设备开发相关经验优先考虑。

备注：开发工具: C++、QT

工作地址：
无锡新区新辉环路9号
**********
无锡祥生医疗科技股份有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医疗设备/器械
公司主页：
www.chison.com.cn
公司地址：
无锡新区新辉环路9号
查看公司地图
**********
软件驱动工程师
无锡祥生医疗科技股份有限公司
五险一金绩效奖金带薪年假免费班车
**********
福利:
五险一金
绩效奖金
带薪年假
免费班车
**********
职位月薪：10000-14000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：软件工程师
**********
要求：
1）计算机科学相关专业本科及以上学历，有两年以上的驱动开发经验
2）熟悉Linux和Windows操作系统的驱动模型
3）对嵌入式Linux操作系统比较熟悉，对Linux操作系统的内核有一定的理解
4）有过USB或者PCIE驱动开发经验的可优先考虑

工作地址：
无锡新区新辉环路9号
**********
无锡祥生医疗科技股份有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医疗设备/器械
公司主页：
www.chison.com.cn
公司地址：
无锡新区新辉环路9号
查看公司地图
**********
国内销售总监助理
无锡祥生医疗科技股份有限公司
五险一金绩效奖金包吃带薪年假免费班车
**********
福利:
五险一金
绩效奖金
包吃
带薪年假
免费班车
**********
职位月薪：6001-8000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：1人
职位类别：其他
**********
岗位职责：
配合国销售总监完成销售管理、支持和监督工作，提高国内销售体系运作效率，有效推进总监工作安排。
一、市场营销中心工作量管控和人员培训：
1、 负责市场营销中心团队工作量统计、核定，反映员工工作量；
2、 对市场营销中心工作量统计结果进行关键行为对应分析，向总监提出员工工作改进建议和重点关注人员；
3、 执行总监下达的人员培训、改进或提升工作；
二、 意向和回款工作相关：
1、每周五对销售意向表进行录入、更新、反馈和完善，汇报给业务主管和国内销售总监，接收并监督业务主管执行国内销售总监反馈意见；
2、 每月5号前做出回款计划，并实时督促后续回款情况；
分析回款执行过程中的问题点或风险点及时向国内商务经理和国内销售总监反馈，确保回款工作顺利完成；
三、部门关键工作推进跟踪督促：
每周一次向总经理呈报部门关键工作执行情况报表，组织部门各种业务沟通、协调会议。
任职要求：
1、 经验要求：具备市场营销相关岗位（商务管理、销售管理、市场支持等）五年以上工作经历。
2、 技能要求：熟练应用office系统；具备有效推进管理手段的实施、关键信息反馈、改进措施执行管控能力；具备组织、协调销售人员各项培训所需资源的能力。
3、 优先录用条件：具备销售团队管理经验优先。
4、 学历、专业：本科及以上。专业不限

工作地址：
无锡新区新辉环路9号
**********
无锡祥生医疗科技股份有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医疗设备/器械
公司主页：
www.chison.com.cn
公司地址：
无锡新区新辉环路9号
查看公司地图
**********
数字化实习生
上海时代天使医疗器械有限公司
五险一金年底双薪绩效奖金包住餐补带薪年假定期体检节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
包住
餐补
带薪年假
定期体检
节日福利
**********
职位月薪：2001-4000元/月 
工作地点：无锡-惠山区
发布日期：最近
工作性质：实习
工作经验：无经验
最低学历：大专
招聘人数：28人
职位类别：实习生
**********
岗位职责：
1.负责按照SOP，标准操作；
2.负责根据排产的牙颌三维模型数据处理（STL修整，对咬合，牙齿切分）等；
3.负责三维数据处理内部的质量的把控。
4.负责按照要求填写的记录；
5.负责组内所涉及设备的日常维护保养
6.根据主管或组长的要求，参与新员工的培训及考核工作；
7.负责日常环境的维持及清扫
8.协助生产内部及相关部门的研发、工艺改进等工作；

任职要求：
1.计算机/数控/设计/电气/机械等理工类专业，大专及以上学历
2.有一定电脑操作基础

薪资：
2000元/月，加班费另算，包午餐，包住宿。
毕业后4-7k

工作时间：
上午：8:30-11:00 下午：12:00-17:00 双休，法定节假日休息

实习时间到毕业，毕业后符合岗位要求即可留用，毕业转正后福利：
13薪,相比同行业高出20%
入职后即享受社保、公积金
工作满一年享受5天带薪年假，每增1年加1天
不定期组织各种特色活动，烧烤、羽毛球都在“你的脑海里”
端午、中秋、春节，每个节日都有惊喜
工作满一年享受健康体检
正式员工可在10万元的天使
基金奖励池里捞取奖励基金
总裁开放日让你跟总裁面对面畅所欲言
。。。。。。。。。。。

EA.INC期待你的加入！

工作地址：
无锡市惠山区惠山大道1619号生命科技园EA时代天使
查看职位地图
**********
上海时代天使医疗器械有限公司
公司规模：
100-499人
公司性质：
外商独资
公司行业：
医疗设备/器械
公司主页：
http://www.shidaits.com/
公司地址：
上海市杨浦区淞沪路333号创智天地三期5层
**********
机电自动化实习生
上海时代天使医疗器械有限公司
五险一金年底双薪绩效奖金包住餐补带薪年假定期体检节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
包住
餐补
带薪年假
定期体检
节日福利
**********
职位月薪：4000-8000元/月 
工作地点：无锡-惠山区
发布日期：最近
工作性质：实习
工作经验：无经验
最低学历：大专
招聘人数：26人
职位类别：实习生
**********
无锡时代天使医疗器械科技有限公司校招简章
 时代天使简介 Angelalign Profile
时代天使医疗器械集团（网址：www.angelalign.com）成立于2003年，是一家专业从事口腔隐形正畸技术研发、隐形矫治器生产及销售的高新技术企业集团。时代天使见证并推动了中国隐形矫治行业发展的17个年头，长期占据中国隐形矫治市场第一的位置，在全球口腔正畸服务领域也稳居第二。
公司总部位于上海，设立研发中心、市场中心，医学中心，并建有无锡、北京生产基地，在成都设立研发分中心，在广州、武汉等地建有办事处，积极布局海外，在美国、德国等地建有公司。
无锡时代天使医疗器械科技有限公司作为集团生产基地，拥有目前中国最大的3D打印生产车间。今年，公司自主研研发的全自动生产线集MES系统、CRM、OPM于一体实现了全
流程智能制造，该产线的正式启用需要一批具备相关理论基础的人才加入，与公司共同迈进“工业4.0”时代。
 招聘岗位 Positions
岗位一 自动化生产储干
招聘人数：26名               
工作职责
1、全面参与新自动化产线的生产运营管理，设备测试和软件测试等工作
2、全面学习掌握自动化生产流程，工序及相关专业知识
3、制定和完善自动化产线生产管理体系，作业标准和流程，并贯彻实施
4、全面参与车间日常管理，从人机料法环五方面推进5S管理和精益生产
5、协调好生产和其他各部门的配合工作
任职资格
1、机电、电气、自动化、计算机等理工科专业，大专及以上学历
2、有较好地理论基础，学习能力强，富有创新思维
3、脚踏实地，有上进心和职业抱负，有在医疗行业生产管理和技术岗持续发展的意向
 岗位二  三维图像处理员
招聘人数  28名  
工作职责
1、负责排产的牙颌三维模型的数据处理        
2、协助生产内部及相关部门进行研发、工艺改进等工作
任职资格
1、计算机、设计、机电、电气等相关理工科专业，大专及以上学历
2、有平面或三维绘图软件操作基础优先
 发展机会 Job Opportunity
1、公司提供全面专业的实习期培训及教练辅导, 使员工迅速适应工作和职场生活；
2、公司提供持续丰富的岗位在职培训，不断提升员工综合素质和能力，育“材”为“才”;
3、管理岗，技术岗，培训师的三向人才培养通道，激发每个员工潜能。
 工资福利  Compensation & Benefit
员工工资：实习期内2000-3000元，提供工作餐和免费住宿
毕业后按岗位绩效方案计薪，4000-8000元/月
社会保险：五险一金必须有
年休假： 入职满一年享受5天带薪年假，每增加一年加一天
年终奖：入职满一年享受1-3个月工资为基数的年终奖
健康体检：年度体检少不了，父母的担心就是我们的关注
节日问候：端午、中秋、春节，生日会，每个特别的日子都有惊喜
娱乐活动：旅游、聚餐、拓展，丰富的娱乐活动等着你
总裁开放日：让所有员工都可以与总裁面对面畅所欲言
天使基金：表彰团队及个人对公司作出特殊贡献、弘扬企业文化理念的行为，最高奖励5万元。
员工持股：朝阳行业拟上市公司，为技术类等重点岗位员工提供持股计划
学习计划：定期与各类大咖进行技术交流、学习；丰富的专业培训期待你快速成长
员工成长：鼓励创新，鼓励内部提拔和培养

招聘流程 Recruitment Process
招聘会/宣讲会/网站投递简历——简历收集——简历筛选——笔试——面试——复试——实习——签订就业协议
 应聘须知 Matters Need Attention
1、网上简历投递的邮件标题格式为“姓名-学校-专业-应聘岗位-电话”;
2、现场投递简历的，请在简历上注明应聘职位；
3、笔试或面试将以短信或电话形式通知，请保持通讯畅通；
4、参加笔试者需携带身份证、2B铅笔、橡皮和水笔；
5、参加面试者需携带以下资料:个人简历（现场投递简历的不必重复提交）。
 

工作地址：
无锡市惠山区惠山大道1619号2号楼1层（惠山生命科技产业园内）
查看职位地图
**********
上海时代天使医疗器械有限公司
公司规模：
100-499人
公司性质：
外商独资
公司行业：
医疗设备/器械
公司主页：
http://www.shidaits.com/
公司地址：
上海市杨浦区淞沪路333号创智天地三期5层
**********
电气装配工
无锡安之卓医疗机器人有限公司
五险一金每年多次调薪包吃免费班车
**********
福利:
五险一金
每年多次调薪
包吃
免费班车
**********
职位月薪：3500-4000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：普工/操作工
**********
任职要求：
能看懂电气图纸，有设备整体接线经验
工作地址：
无锡惠山经济开发区锦惠路10号
查看职位地图
**********
无锡安之卓医疗机器人有限公司
公司规模：
100-499人
公司性质：
合资
公司行业：
医药/生物工程
公司地址：
无锡惠山经济开发区锦惠路10号
**********
软件需求分析工程师
无锡祥生医疗科技股份有限公司
五险一金绩效奖金包吃带薪年假免费班车
**********
福利:
五险一金
绩效奖金
包吃
带薪年假
免费班车
**********
职位月薪：5000-6000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：需求工程师
**********
岗位要求：
1. 大专及以上生物医学工程相关专业，1年及以上工作经验，特别优秀的应届毕业生也可以考虑；
2. 熟练使用Excel、Word等办公软件，了解常用的需求分析与管理软件工具；对超声机器或者软件有一定的熟悉；具备一定的超声影像临床知识；
3. 有医学影像相关工作经验的优先。
工作职责：
1、主要负责需求的分析，与其他部门合作，将市场需求转换为详细的技术需求；
2、负责需求的整理、录入、变更以及跟踪维护；
3、撰写相关的文档等。

工作地址：
无锡新区新辉环路9号
**********
无锡祥生医疗科技股份有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医疗设备/器械
公司主页：
www.chison.com.cn
公司地址：
无锡新区新辉环路9号
查看公司地图
**********
国际工程师（驻地泰州）
江苏泽成生物技术有限公司
带薪年假定期体检员工旅游高温补贴节日福利餐补全勤奖
**********
福利:
带薪年假
定期体检
员工旅游
高温补贴
节日福利
餐补
全勤奖
**********
职位月薪：4000-7000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：2人
职位类别：售前/售后技术支持管理
**********
岗位职责：
1、为国际客户提供产品培训；
2、参加工作测试小组，协助研发和工艺测试试剂项目；
3、协调国际部在泰州的其他工作；

任职要求：
1.计算机、医疗器械、测控技术与仪器、医学检验、电子类、生物类相关专业；
2.具有良好的沟通能力和客户服务意识，责任心强，富有团队合作精神
3.需要英文工作，英文4级以上，会PS优先考虑，理解能力强，能主动学习，沟通能力良好
4、优先的应届毕业生可考虑

工作地址：
泰州中国医药城
**********
江苏泽成生物技术有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医疗设备/器械
公司主页：
http://www.zechengbio.com
公司地址：
江阴市东盛西路6号
查看公司地图
**********
电机设计工程师
无锡钧弘自动化科技有限公司
五险一金绩效奖金交通补助餐补通讯补贴带薪年假员工旅游节日福利
**********
福利:
五险一金
绩效奖金
交通补助
餐补
通讯补贴
带薪年假
员工旅游
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：无锡
发布日期：最近
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：机械设计师
**********
岗位职责：
1.从事无刷电机以及驱动产品的设计，熟悉小电机的机械结构的设计；
2.独立开发设计直流电机的派伸产品。

任职要求：
1．性别不限，电机或者自动化/机械等专业专科以上学历
2．勤奋塌实，能适应高效快节奏的工作。有团队合作精神。 
3．有扎实的电机设计的理论知识，有直流或者无刷电机设计经验。

工作地址：
无锡市光电园会北路28-94号
**********
无锡钧弘自动化科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
仪器仪表及工业自动化
公司主页：
www.exmek.com
公司地址：
无锡市光电园会北路28-94号
查看公司地图
**********
生产主管（康复）
蝶和科技(中国)有限公司
五险一金绩效奖金交通补助餐补通讯补贴
**********
福利:
五险一金
绩效奖金
交通补助
餐补
通讯补贴
**********
职位月薪：6001-8000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：1人
职位类别：生产主管/督导/组长
**********
岗位职责：
1、根据生产计划，合理优化人力分配，有效利用资源完成生产任务。
2、监控生产效率，与PE一起合理优化工艺流程，提升生产效率。
3、熟悉产品的工艺流程，本人遵守以及监督员工按照生产工艺要求进行作业，确保所负责产品线的质量、交期符合客户需求。
4、按照作业指导书和工艺过程控制卡进行设备的装配，并做好相应的记录，确保生产过程符合质量体系要求。
5、参与质量体系内审、外审、产品注册审核等，负责生产相关事宜，确保通过各项审核工作。
6、组织新产品导入过程中的设备试装，并能够进行学习，为批量生产做准备；在大批量生产的时候能够快速的培训员工并带领团队完成产能扩充。
7、组织持续改进活动，包括能够对产品提出工艺改善意见、工装夹具的改善、流程改善等等。
8、控制生产物料耗损，对超耗材料做分析并采取预防措施，减少物料耗损。
9、完成上级安排的其它任务。

任职要求：
1、全日制本科或以上，机电一体化，机械制造，电气自动化专业。
2、五年以上机电一体化设备的生产经验，一年以上同岗位的经验。
3、有医疗设备工作经验优先。
4、有外企工作经验优先。
5、熟悉ISO9001、ISO13485质量体系。
6、具有机械基础知识，包括识图、公差配合、测量等。
7、能够根据机械装配图纸独立进行装配。
8、能够根据电子装配接线图独立进行电子电路板的装配。
9、熟悉生产管理流程。

工作地址：
新吴区菱湖大道200号G8栋
**********
蝶和科技(中国)有限公司
公司规模：
500-999人
公司性质：
外商独资
公司行业：
医疗设备/器械
公司主页：
null
公司地址：
北京市丰台区丰茂路汉威国际广场6号楼7层
**********
石膏精修技工（口腔专业）
上海时代天使医疗器械有限公司
五险一金年底双薪绩效奖金加班补助包住餐补带薪年假补充医疗保险
**********
福利:
五险一金
年底双薪
绩效奖金
加班补助
包住
餐补
带薪年假
补充医疗保险
**********
职位月薪：4001-6000元/月 
工作地点：无锡-惠山区
发布日期：最近
工作性质：全职
工作经验：不限
最低学历：中技
招聘人数：10人
职位类别：技工
**********
岗位职责：
1、负责按照SOP标准操作；
2、负责根据排产完成技工室的相关工作（灌模、修整、模型翻制、硅橡胶脱模，模型拍照等）；
3、负责生产内部及相关部门的研发、工艺改进等工作；
4、负责技工室产品质量的把控。
5、负责按照要求填写的记录；

任职资格：
1、 口腔专业，中专及以上学历；
2、 熟悉办公软件的操作；
3、 从事过模型的翻制以及活动义齿的制作、排牙工作者优先。

工作时间：
长白班8:30-17:00，双休。

薪资：
实习生2000元/月，毕业后4000-6000元/月，提供中餐和免费住宿

转正后福利
13薪,相比同行业高出20%
入职后即享受社保、公积金
工作满一年享受5天带薪年假，每增1年加1天
不定期组织各种特色活动，烧烤、羽毛球都在“你的脑海里”
端午、中秋、春节，每个节日都有惊喜
工作满一年享受健康体检
正式员工可在10万元的天使
基金奖励池里捞取奖励基金
总裁开放日让你跟总裁面对面畅所欲言
。。。。。。。。。。。
EA.INC期待你的加入！

联系我们  
公司地址：无锡市惠山区惠山大道1619号2号楼1层（惠山生命科技产业园内）
联系方式：0510-83591717-245
公司网站：www.angelalign.com
面试简历投递邮箱： wxhr@angelalign.com

工作地址：
无锡市惠山区惠山大道1619号2号楼1层（惠山生命科技产业园内）
查看职位地图
**********
上海时代天使医疗器械有限公司
公司规模：
100-499人
公司性质：
外商独资
公司行业：
医疗设备/器械
公司主页：
http://www.shidaits.com/
公司地址：
上海市杨浦区淞沪路333号创智天地三期5层
**********
国内销售助理
无锡祥生医疗科技股份有限公司
五险一金绩效奖金带薪年假免费班车节日福利
**********
福利:
五险一金
绩效奖金
带薪年假
免费班车
节日福利
**********
职位月薪：2001-4000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：7人
职位类别：客户代表
**********
任职资格：
a)       大专或以上学历；
b)       半年以上工作经验，有电话销售经验者优先；
c)       表达清晰、理解力强、沟通有逻辑性；
d)       工作态度积极，较好的执行力。

此岗位： 无责任底薪2500起；周末双休+五险一金+带薪培训+免费午餐+免费厂车+岗位奖金；

工作地址：
无锡新区新辉环路9号
**********
无锡祥生医疗科技股份有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医疗设备/器械
公司主页：
www.chison.com.cn
公司地址：
无锡新区新辉环路9号
查看公司地图
**********
技术服务工程师-江苏
深圳市新产业生物医学工程股份有限公司
五险一金年底双薪交通补助弹性工作补充医疗保险节日福利
**********
福利:
五险一金
年底双薪
交通补助
弹性工作
补充医疗保险
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：无锡
发布日期：最近
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：1人
职位类别：医疗器械维修/保养
**********
工作职责
1、负责新产品的安装、升级管理、应用培训等售后服务工作；
2、负责产品问题的跟踪、反馈、投诉解决及相关问题的处理；
3、协助销售和市场推广，提供必要的技术支持；
4、收集并反馈客户在使用过程中的产品问题，并协助研发及生产部门改进产品品质；
5、为客户提供良好的技术服务，提升客户满意度。
 任职资格
1、本科学历，生物医学工程、生物技术、医学检验、免疫学等相关专业毕业；
2、具备良好的语言表达及沟通能力，较强的学习能力及判断能力；
3、热爱技术服务工作，有责任心，能承受一定的工作压力，能适应出差（省内）；
4、具有团队合作及吃苦耐劳精神；
5、一年或以上医疗器械的技术服务经验者、具有化学发光技术服务经验者优先录取。
工作地址：
江苏
**********
深圳市新产业生物医学工程股份有限公司
公司规模：
1000-9999人
公司性质：
股份制企业
公司行业：
医疗设备/器械
公司主页：
www.snibe.com
公司地址：
深圳市南山区科园路1008号软件产业基地1栋A座19-21层
**********
注册专员
蝶和科技(中国)有限公司
五险一金交通补助餐补通讯补贴带薪年假
**********
福利:
五险一金
交通补助
餐补
通讯补贴
带薪年假
**********
职位月薪：4001-6000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：项目专员/助理
**********
岗位职责：
1. 负责医疗器械相关产品的注册，牵头撰写及审核相关申报资料； 
2. 负责资料的提交、样品检验、评审及审批的跟进； 
3. 负责与审批中心及检测中心的咨询与沟通； 
4. 跟进相关国家政策及法规的更新，并对企业内部人员进行培训； 
5. 负责其他质量体系认证的相关认证及复核工作； 
6. 定期汇报工作进展，协助领导开展其他工作。 

任职要求：
1.医学、临床检验、生物工程、结构工程等相关专业，本科或以上学历； 
2.熟悉医疗器械相关法律法规政策； 
3.具有1年以上医疗器械注册相关工作经验。

工作地址：
菱湖大道200号G8栋
**********
蝶和科技(中国)有限公司
公司规模：
500-999人
公司性质：
外商独资
公司行业：
医疗设备/器械
公司主页：
null
公司地址：
北京市丰台区丰茂路汉威国际广场6号楼7层
**********
机械工程师
江苏宇星工贸有限公司
五险一金绩效奖金包吃定期体检节日福利
**********
福利:
五险一金
绩效奖金
包吃
定期体检
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：无锡
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：2人
职位类别：机械工程师
**********
岗位描述：
1、负责或参与产品机械部分的设计、出图、选材、选型、跟产、试验、采购等工作；
2、参与新产品总体方案设计，并对产品的功能进行改进；
3、负责外协加工厂的跟产、协调、跟踪、进度控制，负责产品机械部分的质量控制；
4、编制产品机械部分技术方案、产品使用手册、专利等内容；
5、工作经验不限。
任职要求：
1、机械、机电一体化全日制大专以上学历；非标设备设计，机械设备设计！
2、熟悉掌握机械原理、机械制图、尺寸与公差、加工工艺等知识；
3、熟练掌握一种机械三维设计软件（Solidworks、Pro/E、CATIA、UG、AutoCAD等），精通二维制图；
4、具备良好的沟通能力，积极的心态，有较强的责任心，良好的团队协作精神；
5、薪资面议，待遇优厚。

工作地址：
宜兴市红塔东街99号
查看职位地图
**********
江苏宇星工贸有限公司
公司规模：
500-999人
公司性质：
股份制企业
公司行业：
石油/石化/化工
公司主页：
www.yuxingcn.cn
公司地址：
江苏省宜兴经济技术开发区红塔东路99号
**********
国际销售经理
江苏宇星工贸有限公司
五险一金包吃高温补贴节日福利
**********
福利:
五险一金
包吃
高温补贴
节日福利
**********
职位月薪：20001-30000元/月 
工作地点：无锡-宜兴市
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：8人
职位类别：销售经理
**********
外贸经理任职要求：
1、具备较强的销售知识和能力，有一年及以上外贸相关工作经验。
     2、本科及以上学历，八级英语（条件优秀的可以考虑六级）。
      3、熟悉销售流程；熟悉制单流程；具备一定的沟通协调能力与行政文书能力熟练操作电脑和办公软件。
      4、具备较强的领导、组织、理解及执行能力。
      5、具备较强的责任心与团队协作能力。
待遇：年薪25万以上，根据销售业绩，上不封顶。
岗位责任与工作内容：
  1、遵守制度，服从管理，执行公司销售有关的各项规章制度；
  2、完成分配的销售计划，确保销售业绩达标；
  3、维护老客户，独立开发新客户；
  4、熟悉公司产品，能够准确表达产品的特色与卖点，能有针对性的报价；
  5、落实国际销售合同的确立、签署、执行及跟踪；
  6、准确统计销售数据，编制相关报表并建立销售台账；
  7、积极参与业务员的相关业务素质培训，提升销售技巧；
  8、根据国际客户要求，协助销售管理部进行集装箱的物流运输；
  9、跟进收款情况，确保应收款及时回笼；
  10、妥善处理主办业务过程中发生的争议和问题，维护公司品牌形象；
  11、完成上级领导临时交办的其他事宜。

工作地址：
江苏省宜兴经济技术开发区红塔东路99号
查看职位地图
**********
江苏宇星工贸有限公司
公司规模：
500-999人
公司性质：
股份制企业
公司行业：
石油/石化/化工
公司主页：
www.yuxingcn.cn
公司地址：
江苏省宜兴经济技术开发区红塔东路99号
**********
算法工程师
无锡祥生医疗科技股份有限公司
五险一金年底双薪包吃带薪年假免费班车
**********
福利:
五险一金
年底双薪
包吃
带薪年假
免费班车
**********
职位月薪：15000-25000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：5人
职位类别：算法工程师
**********
岗位职责：
1.主要负责深度学习算法的研究和开发，并将其应用于超声成像设备中
2.撰写相关的技术文档、论文等
任职要求：
1、经验要求
2年及以上深度学习算法的研发经验，或者优秀的计算机专业或者应用数学专业的应届毕业生，硕士以上学位。
2、技能要求
--数学基本功扎实
--对常用深度学习软件框架有透彻的理解，有过相关的项目经验
--Python或者C++能够熟练应用
3、优先录用条件
参加各种机器学习竞赛获得过比较好的名次；或者参与过医学影像深度学习相关项目的优先录用；
4、学历、专业
硕士及以上，计算机或者应用数学专业

工作地址：
无锡新区新辉环路9号
**********
无锡祥生医疗科技股份有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医疗设备/器械
公司主页：
www.chison.com.cn
公司地址：
无锡新区新辉环路9号
查看公司地图
**********
财务
无锡盈沛贸易有限公司
五险一金绩效奖金包吃包住带薪年假定期体检员工旅游节日福利
**********
福利:
五险一金
绩效奖金
包吃
包住
带薪年假
定期体检
员工旅游
节日福利
**********
职位月薪：2001-4000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：成本会计
**********
工作内容：
1、生产结算单核算
2、业务员付款审核
3、部门人员报销管理
4、订单汇总
5、客户付款确认
6、部门费用统计
7、部门内勤兼做人事管理

工作要求：
1、有财务知识
2、有一定的沟通能力
3、服从管理，有团队合作精神

薪资:面议
工作地址：
无锡市南长区五爱路56号五爱人家写字楼2号门10楼
查看职位地图
**********
无锡盈沛贸易有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
贸易/进出口
公司地址：
无锡运河东路150号园园工业小区17号三楼
**********
焊 接 工
无锡贝尔森影像技术有限公司
五险一金绩效奖金包吃带薪年假定期体检免费班车高温补贴节日福利
**********
福利:
五险一金
绩效奖金
包吃
带薪年假
定期体检
免费班车
高温补贴
节日福利
**********
职位月薪：2001-4000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：中技
招聘人数：2人
职位类别：普工/操作工
**********
女性，中技以上学历，会电子线路的焊接工作，工作中仔细、认真，有一年以上相关工作经验。
工作地址：
无锡马山生物医药园团结路15号
**********
无锡贝尔森影像技术有限公司
公司规模：
20-99人
公司性质：
合资
公司行业：
医疗设备/器械
公司地址：
无锡马山生物医药园团结路15号
**********
讲师/讲师助理
武汉共享健康科技股份有限公司无锡分公司
五险一金绩效奖金年底双薪股票期权全勤奖包住员工旅游交通补助
**********
福利:
五险一金
绩效奖金
年底双薪
股票期权
全勤奖
包住
员工旅游
交通补助
**********
职位月薪：4001-6000元/月 
工作地点：无锡
发布日期：最近
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：培训师/讲师
**********
一、任职要求
1、医药、生物、化工类专业本科及以上学历，经验不限
2、逻辑思维清晰，善于表达，喜欢演讲，有志从事于培训岗位
3、体能较好，气场足，能接受全国出差，有营销培训经验优先

二、岗位职责
1、负责公司营销模式的宣导
2、负责公司企业文化的宣导
3、负责支持所培训的市场提升营销业绩

三、公司福利
1、严格按照国家法定节假日休息；
2、全体员工可以享受到春节福利、中秋福利、婚假、产假福利，包括生日贺礼、结婚贺礼、妇女节礼物；
3、司龄满一年的员工还将享受到每月工龄补贴100元；
4、公司更重视孝亲文化的传承，对于表现突出的员工公司还将奖励员工个人及父母国内外旅游的机会；
5、公司坚持培训是最大的福利，重视员工的学习和成长，为员工提供发展型培训、帮带式培训、交流式培训、奖励性培训、名师内训等，每年员工有到沈阳总部学习晋升的机会，优秀骨干还将获得到共享学院进行深造；
6、每个月的员工大会我们还将进行隆重表彰，优秀员工将获得笔记本电脑、照相机、冰箱、彩电、洗衣机、微波炉等等，真正实现白领化的生活；
7、公司为员工提供住宿。

工作地址：
南长区槐古豪庭15号楼中威大厦6楼
查看职位地图
**********
武汉共享健康科技股份有限公司无锡分公司
公司规模：
10000人以上
公司性质：
股份制企业
公司行业：
医疗/护理/美容/保健/卫生服务
公司主页：
http://www.share-group.com.cn/
公司地址：
学前东路与解放东路交口 槐古豪庭15号六楼（市政公用大厦旁边）
**********
储备销售经理
无锡中领康迈科技发展有限公司
五险一金餐补带薪年假节日福利高温补贴员工旅游定期体检通讯补贴
**********
福利:
五险一金
餐补
带薪年假
节日福利
高温补贴
员工旅游
定期体检
通讯补贴
**********
职位月薪：6001-8000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：5人
职位类别：销售经理
**********
岗位职责
1、参与公司提供的专业知识、销售技能及销售管理的培训及考核；
2、搜寻潜在目标客户群、潜在客户的接洽及项目跟进并完成销售；
3、项目推进过程中与客户进行技术沟通并解答疑问；
4、与公司内部设计、工程部门的项目衔接；
5、销售渠道的搜索及接洽，建立并维护稳固合作关系，以取得目标客户；
6、销售优秀且具备管理能力晋升销售经理，组建团队并管理。
任职资格
1、专科及以上学历，男女不限，有较大发展潜力的人员，愿意培养应届毕业生；
2、工作积极主动、逻辑思维清晰，较强进取心，能承受工作压力；
3、具备较强的客户沟通能力和较高的商务处理能力，具有良好的团队协作精神；
4、具备销售管理能力；
5、学习能力强，有挑战精神。

工作地址：
无锡市梁溪区塘南路星汇天地30A10楼
查看职位地图
**********
无锡中领康迈科技发展有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
医疗设备/器械
公司地址：
无锡市梁溪区塘南路星汇天地30A10楼
**********
软件工程师（图像处理）
无锡安之卓医疗机器人有限公司
五险一金股票期权包吃带薪年假定期体检免费班车员工旅游节日福利
**********
福利:
五险一金
股票期权
包吃
带薪年假
定期体检
免费班车
员工旅游
节日福利
**********
职位月薪：10000-20000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：1人
职位类别：软件工程师
**********
岗位职责：
负责图像处理和软件开发

任职要求：
1.大专以上学历，计算机相关专业；
2.精通Linux环境C、C++开发。
3.熟练使用QT,Vim+Gcc+Gdb等开发环境。
4.有丰富的OpenCV开发经验。
5.有丰富的QT界面开发经验。
6.熟练使用Linux,并能对系统剪裁。

工作地址：
无锡惠山经济开发区锦惠路10号
**********
无锡安之卓医疗机器人有限公司
公司规模：
100-499人
公司性质：
合资
公司行业：
医药/生物工程
公司地址：
无锡惠山经济开发区锦惠路10号
查看公司地图
**********
销售经理
无锡铭安安全设备有限公司
绩效奖金包吃交通补助通讯补贴节日福利员工旅游每年多次调薪
**********
福利:
绩效奖金
包吃
交通补助
通讯补贴
节日福利
员工旅游
每年多次调薪
**********
职位月薪：8001-10000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：3人
职位类别：销售代表
**********
1、负责公司产品的销售和推广以及区域内对经销商的沟通与指导；
2、开拓新市场，发展新客户，扩大产品的销售范围；
3、维护客户关系，制定与客户间的长期战略合作计划；
4、负责市场信息的收集与分析；
5、根据市场营销计划，完成部门销售指标。
任职要求：
1、热爱销售岗位，对工作有热情，认真负责；
2、性格开朗，反应敏捷，表达能力强，具有较强的沟通能力及交际技巧；
3、具备一定的市场分析、判断能力以及良好的客户服务意识；
4、能够吃苦耐劳，承受工作压力，具备良好的团队协作精神；
5、有大中院校产品销售经验者优先考虑，男女不限，年龄25-35岁。

工作地址：
无锡市惠山区长安春惠路568-7
查看职位地图
**********
无锡铭安安全设备有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
加工制造（原料加工/模具）
公司地址：
无锡市惠山区长安春惠路568-7
**********
销售代表
无锡中领康迈科技发展有限公司
五险一金餐补通讯补贴带薪年假高温补贴员工旅游定期体检节日福利
**********
福利:
五险一金
餐补
通讯补贴
带薪年假
高温补贴
员工旅游
定期体检
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：中专
招聘人数：5人
职位类别：销售工程师
**********
岗位职责
1、在上级的领导和监督下定期完成量化的工作要求，并能独立处理和解决所负责的任务；
2、维修好客户关系，完成销售任务；
3、了解和发掘客户需求及购买愿望，介绍自己产品的优点和特色；
4、对客户提供专业的咨询；
5、收集潜在客户资料；
任职资格
1、专科及以上学历，男女不限；
2、性格外向、反应敏捷、表达能力强，具有较强的沟通能力及交际技巧，具有亲和力；
3、有责任心，能承受较大的工作压力。

工作地址：
无锡市梁溪区塘南路星汇天地30A10楼
查看职位地图
**********
无锡中领康迈科技发展有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
医疗设备/器械
公司地址：
无锡市梁溪区塘南路星汇天地30A10楼
**********
管理培训生
武汉共享健康科技股份有限公司无锡分公司
五险一金年底双薪绩效奖金股票期权全勤奖弹性工作带薪年假员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
股票期权
全勤奖
弹性工作
带薪年假
员工旅游
**********
职位月薪：2001-4000元/月 
工作地点：无锡
发布日期：最近
工作性质：全职
工作经验：无经验
最低学历：大专
招聘人数：2人
职位类别：培训生
**********
岗位职责及要求：
1、熟悉公司基本的运作及管理流程，实行轮岗锻炼，从基础岗位做起（前期带薪在岗培训）；
2、职位凭能力业绩和提升，没有排资论辈的说法（每一位事业伙伴都配备资深干部一对一指导）；
3、德、才、勤、绩是我们选拔人的基础条件；
4、公司提供各类专业技能及管理培训，给大家营造各种积极向上的学习环境；
5、我们不看中学历，只在乎学力（学习能力）。

事业及职位优势：
1、你将得到专业和前沿的培训机会；
2、你将得到最有竞争力的薪酬和福利；
3、你将在事业平台上获得低风险的学习锻炼成长机会；
4、如果你有足够的野心还将可以成为我们的股东和事业合伙人。

薪资福利：
1、无责任底薪+绩效奖金+年中及年终奖金+工龄补贴+其他各类现金及物质奖励；
文职类职位年薪：4-10万（根据级别有差异）
业务及管理类职位年薪：30万（根据级别有差异）
2、实现：三年车、五年房的财富自由机会；
3、上市之前加入公司共享上市时人人持股的财富机会。
4、提供免费培训、免费住宿（空调、洗衣机、网络）；
5、专业的职业导师一对一辅导；
6、透明、公平、公正、公开的晋升机制；
7、严格按照国家法定节假日休息；
8、一年多次的省内旅游、一年2次的国内外旅游。


工作地址：
南长区槐古豪庭15号楼中威大厦6楼
查看职位地图
**********
武汉共享健康科技股份有限公司无锡分公司
公司规模：
10000人以上
公司性质：
股份制企业
公司行业：
医疗/护理/美容/保健/卫生服务
公司主页：
http://www.share-group.com.cn/
公司地址：
学前东路与解放东路交口 槐古豪庭15号六楼（市政公用大厦旁边）
**********
有发展　企划主持人（提供住宿+五险）
武汉共享健康科技股份有限公司无锡分公司
五险一金包住节日福利全勤奖股票期权绩效奖金
**********
福利:
五险一金
包住
节日福利
全勤奖
股票期权
绩效奖金
**********
职位月薪：3000-5000元/月 
工作地点：无锡
发布日期：最近
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：会展策划/设计
**********
岗位职责：
1、协助部门负责人进行会议流程的制定，包括协调整合各方资源，确认和执行活动方案，对活动全流程进行组织管理；
2、处理会议推广过程的具体事务，并协助完成活动组织与沟通协调的具体工作；
3、通过会场各项工作的配合，推动产品销售；
4、会议的前期准备，会中的主持和会后总结。
任职要求：
1、专科以上学历，广告传媒、新闻主持、市场营销及相关专业优秀毕业生；
2、熟悉会务、展览的执行流程；
3、具备良好的沟通技巧和人际交往能力，认真、细致、有责任心。
4、形象气质佳，普通话标准，有良好的处理突发事件的能力。
薪资福利：
1、基本薪资（2500-3000）+岗位补助+年中及年终奖金+工龄补贴+孝亲工资+其他各类现金及物质奖励；文职类职位年薪：4-5万（根据级别有差异）
2、免费住宿（空调、洗衣机、网络）；
3、上市之前加入公司共享上市时人人持股的财富机会；
4、提供免费培训，专业的职业导师一对一辅导；
5、透明、公平、公正、公开的晋升机制；
6、一年两次（8月为期1周、春节为期2周）的特殊孝亲年假；
7、一年多次的省内旅游、一年2次的国内外旅游；
8、公司提供五险。

工作地址：
南长区槐古豪庭15号楼中威大厦6楼
查看职位地图
**********
武汉共享健康科技股份有限公司无锡分公司
公司规模：
10000人以上
公司性质：
股份制企业
公司行业：
医疗/护理/美容/保健/卫生服务
公司主页：
http://www.share-group.com.cn/
公司地址：
学前东路与解放东路交口 槐古豪庭15号六楼（市政公用大厦旁边）
**********
产品经理
江苏曼荼罗软件股份有限公司
绩效奖金包住交通补助通讯补贴带薪年假弹性工作定期体检员工旅游
**********
福利:
绩效奖金
包住
交通补助
通讯补贴
带薪年假
弹性工作
定期体检
员工旅游
**********
职位月薪：10001-15000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：1人
职位类别：IT项目经理/主管
**********
工作职责：
1. 参与构建临床医疗知识库，分析临床活动过程及内在规律，建设应用规则;
2.参与病种模型建设，负责对医生进行调研，分析和筛选病种模型元素;
3.参与医疗数据清洗、分析等工作；
4.协助部门其他产品或项目的医学相关工作。
任职要求：
1.本科及以上学历，临床医学、流行病学、全科医学专业背景;
2.临床经验3年以上；
3.熟悉医疗数据，参与过医疗信息化项目优先；
4.有很强责任心，做事认真、严谨。能独立开展工作并承受较强的工作压力，适应经常加班。
5.具有较强的组织、协调能力和团队协作精神。

工作地址：
无锡市新区菱湖大道200号创新园F区5号楼
**********
江苏曼荼罗软件股份有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
计算机软件
公司主页：
www.mandalat.com.cn
公司地址：
无锡市新区菱湖大道200号创新园F区5号楼
**********
C#开发工程师/上位机设备
上海时代天使医疗器械有限公司
五险一金加班补助交通补助餐补通讯补贴弹性工作节日福利
**********
福利:
五险一金
加班补助
交通补助
餐补
通讯补贴
弹性工作
节日福利
**********
职位月薪：10001-15000元/月 
工作地点：无锡-惠山区
发布日期：最近
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：软件研发工程师
**********
工作职责
1、   与供应商合作，在MES项目中负责PCS中上位机软件的开发与集成。
2、   根据需求进行相应的软件开发设计及编写技术文档
3、   对自己开发的功能进行相关测试并进行性能、代码优化；
  任职资格
1、   本科及以上，计算机及相关专业，3年以上相关工作经验优先
2、   精通C#开发
3、   精通socket或 WCF,熟悉多线程编程、web service、DB开发优先
4、   较强的沟通能力、学习能力、分析问题和解决问题的能力，能独立承担任务，有很强的团队合作精神
5、   有MES，网络通讯，web service项目经验优先。


     
工作地址：
上海市杨浦区淞沪路333号创智天地三期5层
查看职位地图
**********
上海时代天使医疗器械有限公司
公司规模：
100-499人
公司性质：
外商独资
公司行业：
医疗设备/器械
公司主页：
http://www.shidaits.com/
公司地址：
上海市杨浦区淞沪路333号创智天地三期5层
**********
自动化生产技术员（储干类）
上海时代天使医疗器械有限公司
五险一金年底双薪绩效奖金包住餐补带薪年假定期体检节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
包住
餐补
带薪年假
定期体检
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：无锡-惠山区
发布日期：最近
工作性质：全职
工作经验：无经验
最低学历：大专
招聘人数：26人
职位类别：储备干部
**********
无锡时代天使医疗器械科技有限公司校招简章
 时代天使简介 Angelalign Profile
时代天使医疗器械集团（网址：www.angelalign.com）成立于2003年，是一家专业从事口腔隐形正畸技术研发、隐形矫治器生产及销售的高新技术企业集团。时代天使见证并推动了中国隐形矫治行业发展的17个年头，长期占据中国隐形矫治市场第一的位置，在全球口腔正畸服务领域也稳居第二。
公司总部位于上海，设立研发中心、市场中心，医学中心，并建有无锡、北京生产基地，在成都设立研发分中心，在广州、武汉等地建有办事处，积极布局海外，在美国、德国等地建有公司。
无锡时代天使医疗器械科技有限公司作为集团生产基地，拥有目前中国最大的3D打印生产车间。今年，公司自主研研发的全自动生产线集MES系统、CRM、OPM于一体实现了全
流程智能制造，该产线的正式启用需要一批具备相关理论基础的人才加入，与公司共同迈进“工业4.0”时代。
 招聘岗位 Positions
岗位一 自动化生产储干
招聘人数：26名               
工作职责
1、全面参与新自动化产线的生产运营管理，设备测试和软件测试等工作
2、全面学习掌握自动化生产流程，工序及相关专业知识
3、制定和完善自动化产线生产管理体系，作业标准和流程，并贯彻实施
4、全面参与车间日常管理，从人机料法环五方面推进5S管理和精益生产
5、协调好生产和其他各部门的配合工作
任职资格
1、机电、电气、自动化、计算机等理工科专业，大专及以上学历
2、有较好地理论基础，学习能力强，富有创新思维
3、脚踏实地，有上进心和职业抱负，有在医疗行业生产管理和技术岗持续发展的意向
 岗位二  三维图像处理员
招聘人数  28名  
工作职责
1、负责排产的牙颌三维模型的数据处理        
2、协助生产内部及相关部门进行研发、工艺改进等工作
任职资格
1、计算机、设计、机电、电气等相关理工科专业，大专及以上学历
2、有平面或三维绘图软件操作基础优先
 发展机会 Job Opportunity
1、公司提供全面专业的实习期培训及教练辅导, 使员工迅速适应工作和职场生活；
2、公司提供持续丰富的岗位在职培训，不断提升员工综合素质和能力，育“材”为“才”;
3、管理岗，技术岗，培训师的三向人才培养通道，激发每个员工潜能。
 工资福利  Compensation & Benefit
员工工资：实习期内2000-3000元，提供工作餐和免费住宿
毕业后按岗位绩效方案计薪，4000-8000元/月
社会保险：五险一金必须有
年休假： 入职满一年享受5天带薪年假，每增加一年加一天
年终奖：入职满一年享受1-3个月工资为基数的年终奖
健康体检：年度体检少不了，父母的担心就是我们的关注
节日问候：端午、中秋、春节，生日会，每个特别的日子都有惊喜
娱乐活动：旅游、聚餐、拓展，丰富的娱乐活动等着你
总裁开放日：让所有员工都可以与总裁面对面畅所欲言
天使基金：表彰团队及个人对公司作出特殊贡献、弘扬企业文化理念的行为，最高奖励5万元。
员工持股：朝阳行业拟上市公司，为技术类等重点岗位员工提供持股计划
学习计划：定期与各类大咖进行技术交流、学习；丰富的专业培训期待你快速成长
员工成长：鼓励创新，鼓励内部提拔和培养

招聘流程 Recruitment Process
招聘会/宣讲会/网站投递简历——简历收集——简历筛选——笔试——面试——复试——实习——签订就业协议
 应聘须知 Matters Need Attention
1、网上简历投递的邮件标题格式为“姓名-学校-专业-应聘岗位-电话”;
2、现场投递简历的，请在简历上注明应聘职位；
3、笔试或面试将以短信或电话形式通知，请保持通讯畅通；
4、参加笔试者需携带身份证、2B铅笔、橡皮和水笔；
5、参加面试者需携带以下资料:个人简历（现场投递简历的不必重复提交）。
 

工作地址：
无锡市惠山区惠山大道1619号2号楼1层（惠山生命科技产业园内）
查看职位地图
**********
上海时代天使医疗器械有限公司
公司规模：
100-499人
公司性质：
外商独资
公司行业：
医疗设备/器械
公司主页：
http://www.shidaits.com/
公司地址：
上海市杨浦区淞沪路333号创智天地三期5层
**********
质量经理
蝶和科技(中国)有限公司
五险一金交通补助餐补通讯补贴带薪年假
**********
福利:
五险一金
交通补助
餐补
通讯补贴
带薪年假
**********
职位月薪：8001-10000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：1人
职位类别：医疗器械生产/质量管理
**********
岗位职责：
1.组织制定详细的质量管理制度、规范和标准，并经领导审批同意后负责实施;
2.负责组织实施质量计划以及质量管理规范，监督产品或者工程质量问题;
3.按照规定审核用于生产的原材料和生产设备的质量，保证原材料及设备达到企业生产要求;
4.对产品或工程实施质量监督，负责及时发现并解决施工过程中的质量问题;对质量事故进行调查分析并撰写质量事故调查报告;
5.组织质量部门人员完成质量认证工作;
6.负责质量部门的日常工作，负责人员工作安排，保证工作能及时完成;
7.负责部门人员的培训和业绩考核工作。

任职要求：
1.五年以上大中型企业同等职位工作经验，有中大型工厂质量管理经验者优先；
2.熟悉质量管理工作相关工作流程，熟悉ISO9001、ISO14001和OHSAS18001体系要求；
3.办事沉稳、细致，思维活跃，有创新精神，良好的团队合作意识；
4.优秀的品行和职业素质，强烈的敬业精神与责任感，工作原则性强；
5.英文口语流利者优先。

工作地址：
菱湖大道200号G8栋
**********
蝶和科技(中国)有限公司
公司规模：
500-999人
公司性质：
外商独资
公司行业：
医疗设备/器械
公司主页：
null
公司地址：
北京市丰台区丰茂路汉威国际广场6号楼7层
**********
线圈调试工程师
凯思轩达医疗科技无锡有限公司
**********
福利:
**********
职位月薪：6000-12000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：医疗器械维修/保养
**********
岗位职责：
1、大型医疗设备线圈调试和故障分析处理；
2、完成领导交待的其它工作。
任职资格：
1、大专以上学历，三年以上相关工作经验
2、有较强的责任心和耐心，具备良好的语言沟通、表达能力，具备良好的团队合作意识，工作条理清晰；
3、动手能力强；
4、偶尔需要出差支持现场维修工程师。
 待遇：
1、 五天工作制，享受国家法定节假日；工作满一年，享受带薪年休假；
2、 底薪+绩效工资+餐补+全勤奖金+话费补+五险一金+维修奖金；
3、 年终奖金等其它福利。

工作地址：
无锡
查看职位地图
**********
凯思轩达医疗科技无锡有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医疗设备/器械
公司地址：
广州天河区五山路246号金山大厦南塔28楼
**********
装配技工
蝶和科技(中国)有限公司
五险一金绩效奖金交通补助餐补通讯补贴带薪年假
**********
福利:
五险一金
绩效奖金
交通补助
餐补
通讯补贴
带薪年假
**********
职位月薪：3800-4500元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：中专
招聘人数：1人
职位类别：技工
**********
岗位职责：
1.严格按照生产工艺要求进行作业，确保所负责产品线的质量、交期符合客户需求；
2.按照作业指导书和工艺过程控制卡进行设备的装配，并做好相应的记录，确保生产过程符合质量体系要求；
3.参与质量体系内审、外审、产品注册审核等；
4.参与新产品导入过程中的设备试装，并能够进行学习，为批量生产做准备；
5.参与持续改进活动，包括能够对产品提出工艺改善意见、工装夹具的改善、流程改善、提升组装效率等等；
6.完成上级安排的其它任务。


任职要求：
1.中专及以上，三年以上机电一体化设备的生产或测试工作经验；
2.熟悉ISO9001、ISO13485质量体系，具有机械基础知识，包括识图、公差配合、测量等；
3.能够根据机械装配图纸独立进行装配，能够根据电子装配接线图独立进行电子电路板的装配；
4.熟悉生产管理流程。

公司目前处于业务规模急速发展的阶段，装配技师需要具有很强的学习能力，能够快速学习，并在未来承担所负责的产品线从试产到量产的全流程生产管理工作，公司提供这样的上升通道。

工作地址：
菱湖大道200号G8栋
**********
蝶和科技(中国)有限公司
公司规模：
500-999人
公司性质：
外商独资
公司行业：
医疗设备/器械
公司主页：
null
公司地址：
北京市丰台区丰茂路汉威国际广场6号楼7层
**********
省区经理（江苏）
广东冠丰医药有限公司
**********
福利:
**********
职位月薪：10001-15000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：不限
招聘人数：1人
职位类别：医疗器械销售
**********
岗位职责：
1.负责区域内医疗耗材产品的销售招商管理工作；
2.有效执行各类销售政策和遵守各类规章制度；
3.配合市场部，高效开展各类销售及学术活动；
4.建立和管理销售队伍，完成销售目标；
5.分析和开发市场并做好售后服务工作；
6.有效管理经销商，对代理商进行产品培训，提供学术支持及售后服务，达成销售目标。

任职要求：
1.大专以上学历；
2.3年以上医药销售行业管理经验，并有带团队经验；如有医疗耗材销售经验优先；
3.出色的市场分析洞察能力、具备全面深刻营销知识和技能；
4.具备一定的管理领导能力和沟通协调能力。

工作地址：
江苏
**********
广东冠丰医药有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
医疗设备/器械
公司主页：
http://www.gdgfyy.com/index.html
公司地址：
湛江市开发区人民大道中26号工业大厦第七层
查看公司地图
**********
生产部经理
北京仁桥心脑血管病防治研究所
五险一金年底双薪绩效奖金加班补助餐补通讯补贴定期体检节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
加班补助
餐补
通讯补贴
定期体检
节日福利
**********
职位月薪：10001-15000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：1人
职位类别：生产经理/车间主任
**********
岗位职责：
1、大专以上学历，电气、电子、计算机、生物医学工程等相关专业。    
2、熟悉电子产品及电路原理，精通精益生产管理及成本控制。    
3、三年以上医疗器械行业生产管理工作经验。    
4、熟悉ISO13485的管理流程。    
5、熟悉医疗器械安全法律法规。    

任职要求：
工作地址：
中国医药城
**********
北京仁桥心脑血管病防治研究所
公司规模：
20-99人
公司性质：
民营
公司行业：
医药/生物工程
公司地址：
中国医药城
**********
现场应用专家（FAS）
安诺优达基因科技(北京)有限公司
五险一金年底双薪餐补补充医疗保险定期体检节日福利
**********
福利:
五险一金
年底双薪
餐补
补充医疗保险
定期体检
节日福利
**********
职位月薪：9000-12000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：硕士
招聘人数：1人
职位类别：生物工程/生物制药
**********
岗位职责：
1. 公司IVD产品进行售前技术支持，展示公司产品优势，吸引客户购买兴趣。
2. 对购买公司IVD产品的客户进行技术培训，保证客户可以正确使用公司IVD产品。
3. 对公司IVD产品进行售后技术支持，并记录整理相关信息。
4. 发展并维护与指定地区客户之间的良好合作关系。
5. 通过技术讲解和示范来协助维持并提高产品的使用，以及提高日常销售业绩。
6. 为市场营销和产品研发团队提供具有战略性和竞争性的客户反馈。
7. 开发有助于我们完成构建世界一流客户支持组织这一使命的重要公司流程。
8. 公司安排的其它工作事项
任职资格：
1.硕士及以上学历，分子生物学或医学检验相关专业毕业；
2.1年以上二代测序研究工作或技术支持经验；
3.熟练操作分子生物学相关实验；
4.良好的沟通能力及处理问题能力。

工作地点（4选一）：江苏/上海，义乌，广州，北京
工作地址：
北京经济技术开发区科创六街（北京亦庄生物医药园B2栋）
**********
安诺优达基因科技(北京)有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
医药/生物工程
公司主页：
www.annoroad.com
公司地址：
北京经济技术开发区科创六街（北京亦庄生物医药园B2栋）
**********
投标专员
江苏曼荼罗软件股份有限公司
五险一金绩效奖金包住带薪年假弹性工作免费班车员工旅游节日福利
**********
福利:
五险一金
绩效奖金
包住
带薪年假
弹性工作
免费班车
员工旅游
节日福利
**********
职位月薪：4000-8000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：其他
**********
岗位职责 
1、组织参与招标文件的书写；
2、重要项目的文案及客户提案的书写； 
3、稿件思路清晰，能够完成稿件写作思路规划； 
4、协助部门经理进行提案制作，保证工作的顺利推进； 
5、独立撰写各类稿件（标书、方案）、报告等 

任职资格 
1、新闻学、传播学、中文、经济管理类相关专业，大学本科以上学历； 
2、熟悉计算机行业，一年以上市场策划及文案工作经验； 
3、能够准确捕捉产品亮点，具备恰如其分的文字表现能力； 
4、熟悉专业创意方法，思维敏捷，洞察力强，文字功底扎实，语言表达能力强； 
5、能独立完成项目等文案的撰写。
工作地址：
无锡市新区菱湖大道200号创新园F区5号楼
**********
江苏曼荼罗软件股份有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
计算机软件
公司主页：
www.mandalat.com.cn
公司地址：
无锡市新区菱湖大道200号创新园F区5号楼
**********
项目经理/项目主管
南京福康通健康产业有限公司
五险一金绩效奖金年终分红股票期权全勤奖交通补助餐补节日福利
**********
福利:
五险一金
绩效奖金
年终分红
股票期权
全勤奖
交通补助
餐补
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：无锡
发布日期：最近
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：销售代表
**********
公司业务发展，建立苏州分中心，业务辐射南通、上海、无锡，现招募以上及周边城市地区项目经理。

工作内容：
1、负责项目从售前跟踪到售后交付全过程管理；包括项目交接、计划管理问题反馈、收集整理及协调处理、项目验收等工作。
2、与客户保持密切沟通，建立良好的客户关系。
3、负责协调项目成员间及各个部门间的沟通与协作。
4、协助团队完成售前交流或者投标的工作。

任职要求：
1. 市场营销、医疗器械，项目管理等相关专业本科及以上学历；经验丰富或能力突出者专科亦可。
2.具有较强的逻辑思维能力、判断力与决策能力、交际与沟通力、计划与执行力；业务学习能力、团队协作能力、项目推动能力。
3.要求能熟练操作办公软件
4.有驾照、有相关销售工作经验优先考虑。

底薪+丰厚提成+股权激励
完善的培训，广阔的前景。
如果您够洞察到行业未来的发展趋势，欢迎您加入我们，早一步耕耘，早一步收获！

工作地址：
南京福康通健康产业有限公司
查看职位地图
**********
南京福康通健康产业有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
医疗设备/器械
公司地址：
南京福康通健康产业有限公司
**********
省区经理（江苏）
广东冠丰医药有限公司
**********
福利:
**********
职位月薪：10001-15000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：不限
招聘人数：1人
职位类别：医疗器械销售
**********
岗位职责：
1.负责区域内医疗耗材产品的销售招商管理工作；
2.有效执行各类销售政策和遵守各类规章制度；
3.配合市场部，高效开展各类销售及学术活动；
4.建立和管理销售队伍，完成销售目标；
5.分析和开发市场并做好售后服务工作；
6.有效管理经销商，对代理商进行产品培训，提供学术支持及售后服务，达成销售目标。

任职要求：
1.大专以上学历；
2.3年以上医药销售行业管理经验，并有带团队经验；如有医疗耗材销售经验优先；
3.出色的市场分析洞察能力、具备全面深刻营销知识和技能；
4.具备一定的管理领导能力和沟通协调能力。

工作地址：
江苏省
**********
广东冠丰医药有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
医疗设备/器械
公司主页：
http://www.gdgfyy.com/index.html
公司地址：
湛江市开发区人民大道中26号工业大厦第七层
查看公司地图
**********
OTC事业部省区/区域KA经理（江苏）
美宝国际
五险一金绩效奖金交通补助餐补带薪年假定期体检员工旅游节日福利
**********
福利:
五险一金
绩效奖金
交通补助
餐补
带薪年假
定期体检
员工旅游
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：销售总监
**********
薪资4000-8000元/月

岗位职责：
1、 负责所辖区域OTC终端推广工作，根据所辖区域的年度销售目标制定相应的实施方案
2、 完成所辖区域的销售目标，协助公司完成整体销售任务；
3、 优化OTC战略合作连锁客户布局建设；
4、 督导、协助KA店形象店的打造，与管理；
5、 负责组织战略合作连锁客户的药学知识主题培训及落实终端主题宣传促销活动；
6、 做好市场控销维价工作，严格监督产品流向；确保所辖连锁客户执行全国统一零售价。
任职要求：
1、 医药学、市场营销等相关专业大专以上学历；
2、 有相关区域KA经理工作经验；
3、 性格外向、反应敏捷，具有较强的沟通能力及交际技巧；
4、 具有较强团队合作精神及责任心，能承受较大的工作压力。

工作地址：
江苏各省区
查看职位地图
**********
美宝国际
公司规模：
500-999人
公司性质：
民营
公司行业：
医药/生物工程
公司主页：
www.mebo.com
公司地址：
北京朝阳区东大桥路8号尚都国际中心A-31
**********
普药代表-无锡
北京万生药业有限责任公司
绩效奖金交通补助通讯补贴弹性工作高温补贴节日福利
**********
福利:
绩效奖金
交通补助
通讯补贴
弹性工作
高温补贴
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：无锡
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：2人
职位类别：销售代表
**********
岗位职责：
1、主要负责公司产品在商业平台的推广工作，以开票员，采购人员为工作对象
2、区域市场调研,确定区域内一级商业公司及二级商业并与之签订销售协议
3、 一级商业的发货回款,按月上报流向,跟踪库存,避免断货/滞销退货
4、二级商业的分销调拨及促销,按月流向上报
任职要求：
1、专科以上学历，1年以上相关工作经验
2、医学、药学、生物、化工或市场营销等相关专业
3、熟知药品销售技巧、沟通技巧；产品知识的掌握

工作地址：
无锡
**********
北京万生药业有限责任公司
公司规模：
1000-9999人
公司性质：
股份制企业
公司行业：
医药/生物工程
公司主页：
http://www.wansheng.com.cn
公司地址：
北京市通州工业开发区广源东街8号
**********
医疗器械招商经理（江苏）
北京阳光普仁医疗器械有限公司
五险一金绩效奖金带薪年假
**********
福利:
五险一金
绩效奖金
带薪年假
**********
职位月薪：6001-8000元/月 
工作地点：无锡
发布日期：最近
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：区域销售经理/主管
**********
岗位职责：

1. 负责公司产品在所负责区域的销售和市场拓展工作；
2. 根据所负责区域的市场状况，制定市场推广计划并负责推进和落实；
3. 负责区域内代理商的招募和管理；
4. 负责或协助公司产品在所负责区域的招投标、物标和医保工作；
5. 负责区域市场内重点医院、专家网络的建设及维护；
6. 对代理商进行业务知识和产品知识培训；
7. 定期提交公司要求的各类报表及公司安排的其他工作
 任职资格：
1. 医药相关专业专科以上学历；
2. 一年以上药品/器械耗材销售或招商经验；


工作地址：
北京朝阳区朝阳北路103号金泰国益大厦1006
**********
北京阳光普仁医疗器械有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
医药/生物工程
公司地址：
北京朝阳区朝阳北路103号金泰国益大厦1006
查看公司地图
**********
软件工程师
TCL医疗放射技术（北京）有限公司
五险一金年底双薪餐补通讯补贴带薪年假弹性工作补充医疗保险定期体检
**********
福利:
五险一金
年底双薪
餐补
通讯补贴
带薪年假
弹性工作
补充医疗保险
定期体检
**********
职位月薪：15001-20000元/月 
工作地点：无锡-无锡新区
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：1人
职位类别：医疗器械研发
**********
岗位职责：
1 协助完成项目的开发计划、需求分析、系统设计
2 协助测试工程师完成项目的软件测试计划
3 根据项目开发计划完成软件模块的概要设计、详细设计、编码和单元测试
4 按照质量体系要求编制相应软件产品的设计文件和过程文档，并归档
5 修改已有软件产品的BUG

任职要求：
1. 本科及以上计算机，电子，生物医电等相关专业
2. 3年以上软件开发工作经验
3.（1）深厚的计算机基础知识
  （2）精通C/C++,熟悉面向对象的软件开发
  （3）熟悉CMM，掌握现代软件工程技术
  （4）了解图象处理、DICOM基本知识
4. 技熟练掌握VC++、C++Builder等软件开发工具，具备基本的网络知识，较强的英语读写能力

工作地址：
无锡市新区清源路20号传感网大学科技园立业楼B301
**********
TCL医疗放射技术（北京）有限公司
公司规模：
100-499人
公司性质：
合资
公司行业：
医疗设备/器械
公司地址：
北京市经济技术开发区博兴5路10号柏瑞安办公楼4层
查看公司地图