人事经理
天津兴宇互联信息技术有限公司
绩效奖金全勤奖交通补助带薪年假弹性工作不加班
**********
福利:
绩效奖金
全勤奖
交通补助
带薪年假
弹性工作
不加班
**********
职位月薪：4001-6000元/月 
工作地点：天津
发布日期：2018-03-11 19:43:20
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：人力资源经理
**********
工作职责：
1、在公司人力资源战略、政策和指引的框架下，建立并实施人力资源方针和行动计划，以支持公司达到预期经营目标；
2、负责组织起草、修改和完善人力资源相关管理制度和工作流程；
3、负责招聘、培训、薪酬、考核、员工关系等人力资源日常管理事宜；
4、负责组织编写各部门职位说明书；
5、定期进行人力资源数据分析，提交公司人力资源分析报告；
6、根据行业和公司发展状况，协助制定公司薪酬体系、激励体系并负责实施；
7、协助监督控制各部门绩效评价过程并不断完善绩效管理体系；
8、协助推动公司理念及企业文化的形成；
9、协助制定公司人力资源整体战略规划；
10、负责部门的日常事务管理工作，协助完成本部门员工工作考核、激励及部门资金的预算和控制等工作，公司安排的其他工作。
任职资格：
1、人力资源、管理或相关专业本科及以上学历；
2、2年以上相关工作经验，1年以上人力资源经理工作经验；
3、对现代企业人力资源管理模式有系统的了解和丰富的实践经验；
4、对人力资源管理各个职能模块均有深入的认识，能够指导各个职能模块的工作；
5、熟悉国家、地区及企业关于合同管理、薪金制度、用人机制、保险福利待遇、培训等方面的法律法规及政策；
6、具有战略、策略化思维，有能力建立、整合不同的工作团队；
7、具有解决复杂问题的能力；很强的计划性和实施执行的能力；
8、很强的激励、沟通、协调、团队领导能力，责任心、事业心强。
工作地址：河西区马场道59号平安大厦A座2901室
工作地址：
天津市河西区马场道59号平安大厦A座2901-02
**********
天津兴宇互联信息技术有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
互联网/电子商务
公司地址：
天津市河西区马场道59号平安大厦A座2901-02
查看公司地图
**********
人事主管
天津兴宇互联信息技术有限公司
绩效奖金全勤奖交通补助带薪年假弹性工作不加班
**********
福利:
绩效奖金
全勤奖
交通补助
带薪年假
弹性工作
不加班
**********
职位月薪：4001-6000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：人力资源主管
**********
【岗位职责】：
1、独立负责事业部各岗位的招聘工作，满足用人部门招聘需求；
2、负责招聘工作实施，简历筛选、面试接待安排、录用沟通等；
3、通过主动和管理层、员工的互动，建立有效和多样化的渠道，保证组织中信息的通畅；
4、与所在区域部门搭档，了解业务战略并促进人力资源战略在所在区域的有效规划和实施
5、协助管理者有效管理团队：团队建设，绩效管理、文化宣导和融合，帮助发现和诊断存在的问题并协助解决
6、定期为业务团队提供人员数据分析并根据问题沟通解决方案；
 【任职资格】：
1、人力资源、企业管理相关专业专科及以上学历；
2、熟悉各类招聘渠道,熟悉HRBP模式有校招经验优先；
3、责任心强，较好的协调能力和团队协作精神；
4、做事认真，踏实稳重，上进心强，有较好的交际、沟通能力。
5、因业务发展需求，公司不断开拓新的城市，后期可接受外调。
工作地点：河西区马场道59号平安大厦A座2901室
工作地址：
天津市河西区马场道59号平安大厦A座2901-02
**********
天津兴宇互联信息技术有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
互联网/电子商务
公司地址：
天津市河西区马场道59号平安大厦A座2901-02
查看公司地图
**********
咨询经理助理
天津优嘉教育科技有限公司
五险一金绩效奖金包住通讯补贴带薪年假弹性工作员工旅游节日福利
**********
福利:
五险一金
绩效奖金
包住
通讯补贴
带薪年假
弹性工作
员工旅游
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津-和平区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：10人
职位类别：大客户销售代表
**********
岗位职责：
协助咨询经理完成日常工作，对客户资料进行整理、回访、跟踪、邀约。
任职要求：
1.市场营销或相关专业大专以上学历，有无工作经验均可。
2.对咨询工作有较深刻了解，了解统计软件的使用；
3.熟练操作办公软件和办公自动化设备。
4.坦诚、自信，高度的工作热情；
5.有良好的团队合作精神，有敬业精神；
6.较强的观察力和应变能力，良好的判断力和沟通能力。

工作地址：
天津市和平区鞍山道50号邮政大厦3楼优嘉教育
查看职位地图
**********
天津优嘉教育科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
教育/培训/院校
公司地址：
**********
高中教师
天津优嘉教育科技有限公司
五险一金绩效奖金包住通讯补贴带薪年假弹性工作员工旅游节日福利
**********
福利:
五险一金
绩效奖金
包住
通讯补贴
带薪年假
弹性工作
员工旅游
节日福利
**********
职位月薪：8001-10000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：1年以下
最低学历：本科
招聘人数：50人
职位类别：高中教师
**********
    教师的主要工作是授课和陪读以及制定各项教学文件（黄金周期计划表，个性化教学计划、个性化教案、授课反馈单、工作总结）；
    教师要爱护公司的财物，本着节约的原则，不浪费办公用印及纸张，保持教室和自己工位的整洁；
    教师按规定填写好授课记录单，保证在授课周周末投单，并在授课周后的次周周三前在课时查询机上核实自己上周课时记录，发现问题按程序及时更正；
    教师要紧密配合各部门的工作，对所授学生出现的问题做到早发现，早联系，早解决。积极参加学管部、咨询部组织的学生分析会议。
    教师要在授课中，严格管理学生，不得出现学生破坏公物和随意在工位桌壁上乱涂乱画的情况。
    教师对于上交的各种文件和表格要认真填写，做到数据准确，上交及时。
    教师要配合教研组长工作，积极参加教研组的各项教研活动，并完成教研组长交办的各项任务。按要求积极参加公司、校区、部门以及教研组的各种会议。按时、保质地完成其他工作（完成上级下达的任务）
    教师在授课期间不得做与上课无关的事情，如打电话、发短信、吃食物等。更不得随意离开学生，擅自离岗属于严重的授课事故。
    教师要遵守授课教室授课纪律，维护授课秩序，遵守各项教室管理制度。正班期间严格按照课表上课，上课期间不得随意走动。
    教师要严格遵守薪金保密制度、购书申报制度、请假制度、考勤制度，做到不迟到、不早退。
工作地址：
天津和平区鞍山道与山西路交口邮电大厦3楼
**********
天津优嘉教育科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
教育/培训/院校
公司地址：

查看公司地图
**********
咨询师
天津优嘉教育科技有限公司
五险一金绩效奖金包住通讯补贴带薪年假弹性工作员工旅游节日福利
**********
福利:
五险一金
绩效奖金
包住
通讯补贴
带薪年假
弹性工作
员工旅游
节日福利
**********
职位月薪：8001-10000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：20人
职位类别：培训/招生/课程顾问
**********
职位描述：
1、负责天津优嘉相关课程的销售工作；
2、通过来访登记、电话等方式，约请有意向学员及家长到教学区咨询；
3、接待来访学员，根据学员测试水平和预期学习目标推介适合的课程；
4、建立与学员之间的良好关系，确保学员满意度并达成学习目标，维护学校形象；
5、保证咨询质量，完成部门制定的招生计划。

任职要求：
1、高度认同优嘉企业文化；
2、大专本科以上学历，一年以上销售经验，有过教育行业经验者优先考虑；
3、形象气质佳，普通话标准口齿伶俐；
4、热爱销售事业，能适应强度高高挑战的工作；
5、具备高速、高效、灵活工作的能力，高度的责任感，极强的沟通能力。
工作地址：
天津和平区鞍山道与山西路交口邮电大厦3楼
查看职位地图
**********
天津优嘉教育科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
教育/培训/院校
公司地址：
**********
招聘 销售主管 月薪过万
天津兴宇互联信息技术有限公司
绩效奖金定期体检节日福利弹性工作员工旅游交通补助
**********
福利:
绩效奖金
定期体检
节日福利
弹性工作
员工旅游
交通补助
**********
职位月薪：8001-10000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：销售主管
**********
岗位职责：
1、团队管理职位，负责其功能领域内主要目标和计划；
2、制定、参与或协助上层执行相关的政策和制度；
3、负责团队的日常管理工作及团队员工的管理、指导、培训及评估;
4、负责团队的销售运作，包括计划、组织、进度控制和检讨，公司提供有意向的客户资源，完成后期业务跟单；
5、建立和管理销售队伍，完成销售目标；
6、客户维护和再开发；
7、对意向客户咨询提供专业的答复，向客户介绍自己产品的优势进一步拓展市场。
任职要求：
1、大专以上学历；
2、1年以上金融行业团队管理经验；
3、出色的市场分析洞察能力、具备全面深刻营销知识和技能；
4、具备一定的团队管理领导能力和沟通协调能力；
5、心态积极向上，喜欢销售工作，拥有成就事业的愿望，有敬业精神和团队精神。
工作地址：天津河西区小白楼平安大厦A座2901室
电话:18812577167
  工作地址：
天津市河西区马场道59号平安大厦A座2901-02
**********
天津兴宇互联信息技术有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
互联网/电子商务
公司地址：
天津市河西区马场道59号平安大厦A座2901-02
查看公司地图
**********
人事专员
天津兴宇互联信息技术有限公司
交通补助全勤奖带薪年假弹性工作不加班绩效奖金
**********
福利:
交通补助
全勤奖
带薪年假
弹性工作
不加班
绩效奖金
**********
职位月薪：2001-4000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：人力资源专员/助理
**********
岗位职责：
1.组织制定公司人事规章制度，并督促、检查制度的贯彻执行；
2.根据公司人力资源规划，协助领导建立完善公司各项相关制度；
3.利用公司各种有利资源，组织开拓和完善各种人力资源招聘渠道，发布招聘信息，补充相关部门人员；
4.新入职员工的报到及解聘手续的办理，接待引领新进员工；
5.负责员工考勤管、纪律监察以及员工工资及流水的核算；
6.完成领导安排其他日常工作；
任职要求：
1.年龄20~27岁，1年以上人力资源工作经验，优秀可放宽；
2.性格外向，具有良好的协调及沟通能力，亲和力强；
3.良好的抗压能力，能独立完成本职及领导临时交待的工作；
4.熟练使用相关办公软件，具备基本的网络知识；
工作时间：上午9:00-下午18:00（午休12:00-13:30）
工作地址：河西区小白楼平安大厦A座
工作地址：
天津市河西区马场道59号平安大厦A座2901-02
**********
天津兴宇互联信息技术有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
互联网/电子商务
公司地址：
天津市河西区马场道59号平安大厦A座2901-02
查看公司地图
**********
销售精英 实现两年买车房 出国旅游
天津兴宇互联信息技术有限公司
五险一金绩效奖金加班补助交通补助通讯补贴定期体检员工旅游节日福利
**********
福利:
五险一金
绩效奖金
加班补助
交通补助
通讯补贴
定期体检
员工旅游
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：5人
职位类别：销售代表
**********
岗位职责：
1.负责掌握公司产品知识、业务运作模式及发展要求；
2.负责定位目标客户群，并对客户进行划分归类；
3.负责主动预约客户将客户预约到公司，并对客户提出的问题给予正确、满意的答复；
4.负责合理利用公司提供的资源，充分把握客户需求、发掘潜在客户；
5.负责不断开发新客户，维护老客户；通过多种销售渠道，完成个人销售目标；
6.负责与团队合作，协助上级负责人完成公司下达的业绩指标；
7.负责参加公司安排的各项业务和技能提升培训；
8.负责完成上级交办的临时性工作。
薪酬福利：
1、有全面专业的培训；
2、基本工资+绩效考核+业绩提成+五险一金；
3、朝九晚六，双休及所有国家规定的法定节假日，年假等假期；
4、员工旅游及丰富多彩的员工活动；
5、和谐的工作环境以及广阔的晋升空间；
不用外跑奔波，不用风吹日晒，只要你有明确的赚钱欲望，轻松实现你的高薪梦，兴宇互联诚邀你的加入！
 工作地址：
天津市河西区马场道59号平安大厦A座2901-02
面试时间：周一至周五上午10:00--下午2:30可来公司面试
面试电话：18812577167 
      座机：022-58531560
工作地址：
天津市河西区马场道59号平安大厦A座2901-02
**********
天津兴宇互联信息技术有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
互联网/电子商务
公司地址：
天津市河西区马场道59号平安大厦A座2901-02
查看公司地图
**********
金融实习生
天津兴宇互联信息技术有限公司
无试用期每年多次调薪绩效奖金交通补助弹性工作定期体检员工旅游节日福利
**********
福利:
无试用期
每年多次调薪
绩效奖金
交通补助
弹性工作
定期体检
员工旅游
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津
发布日期：最新
工作性质：校园
工作经验：无经验
最低学历：大专
招聘人数：3人
职位类别：储备干部
**********
岗位职责：
1、参加定期的公司培训，熟悉公司产品；
2、能够与客户进行良好沟通，推荐适合产品，面销成单；
3、学习销售技能，努力完成周月销售计划；
4、维护客户关系，提升售后服务，与客户保持长久合作关系。
任职要求：
1、17-18应届生，优秀条件可放宽；
2、对金融行业充满热情，并打算长期发展；
3、有无工作经验均可。
温馨提示：
多投一次简历，多一次面试机会，您投递后我们会在第一时间与您沟通，请保持手机畅通，谢谢配合！
我希望 能找到 志同道合的战友  一起去帮助所有中小企业解决资金问题  用心的去服务每个客户  做到：诚 信 亲 和 力 ！
不用外跑奔波，不用风吹日晒，只要你赚钱欲望，轻松实现你的高薪梦，兴宇诚邀你的加入。
 工作地址：
天津市河西区马场道59号平安大厦A座2901-02
面试时间：周一至周五上午10:00--下午2:30可来公司面试
面试电话：18812577167
      座机：022-58531560
工作地址：
天津市河西区马场道59号平安大厦A座2901-02
**********
天津兴宇互联信息技术有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
互联网/电子商务
公司地址：
天津市河西区马场道59号平安大厦A座2901-02
查看公司地图
**********
办公室文员+双休+五险一金
天津金珑基科技有限责任公司
五险一金加班补助餐补
**********
福利:
五险一金
加班补助
餐补
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：2人
职位类别：助理/秘书/文员
**********
岗位职责：
1、熟练操作办公软件。
2、负责办理各类文件的收发、登记、整理、归档、
3.完成领导交办的其它工作。
应聘条件：
1、能够尽快入职(或者一个月左右能够到岗工作)；
2、能长期稳定工作；
3、年龄18-30岁之间，经验不限，专业不限；
4、美国上市集团总公司——注重个人综合素质及能力，目前正在招收应届生及实习生。
待遇：
1、底薪+奖金=3000-6000（根据个人能力提升）；
2、五险一金，带薪年假，双休，节日福利，有餐补等；
3、可提供住宿或者就近安排工作地点；
4、试用期1-3个月（根据个人能力）转正后享有平均月薪不低于3000元/月收入。
工作时间：
1、国家法定作息时间；
2、周末双休，上9:00下6:00，中午一小时午休时间。
公司招揽综合素质能力贤才，组织完善培训计划，工作经验不足者有老员工培养，并且公司提供全方位的办公环境和设施设备。
待遇优厚，试用期三个月，试用期间上五险一金，周末双休，有餐补，办公环境优越，节日福利，法定节假日~！有良好的发展及晋升空间。
应聘者可投递简历，人事部将在3个工作日内安排面试时间,或在右下角在线预约面试时间，并留下你的姓名+学历+年龄+电话，谢谢合作。

工作地址：
天津塘沽外滩
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
综合文员（4000+奖金+双休）
天津金珑基科技有限责任公司
每年多次调薪五险一金绩效奖金餐补节日福利不加班
**********
福利:
每年多次调薪
五险一金
绩效奖金
餐补
节日福利
不加班
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：2人
职位类别：助理/秘书/文员
**********
岗位职责：
1、 负责办公室的全面工作，对办公室、行政以及人事等综合工作进行辅助
2、 协助其他部门完成相应工作
3、 完成领导临时交代的任何工作

任职要求：
1、熟练操作常用办公软件，如word，excel等
2、有很好的信息收集、归纳、整理能力和良好的沟通、协调、表达能力
3、能够服从公司安排，重视团队合作；责任心强、为人正直、保密意识强
4、有强烈的责任心和工作主动性
福利待遇：
1、底薪+奖金=4000-6000（根据个人能力）
2、试用期1-3个月，试用期期间给上五险一金
3、转正后带薪年假，节日福利，餐补 
工作时间：
1、国家法定作息时间
2、9:00-18:00，中午午休1小时，双休


工作地址：
天津市塘沽区营口道
查看职位地图
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
后勤文员+五险一金+双休
天津金珑基科技有限责任公司
五险一金加班补助包住餐补弹性工作节日福利
**********
福利:
五险一金
加班补助
包住
餐补
弹性工作
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：3人
职位类别：助理/秘书/文员
**********
岗位职责：
1、 负责公司资产管理、办公用品采购及劳保用品的管理工作,避免公司资产流失和浪费；
2、 负责书刊资料印刷、快递、物流及办公室的其他事情；
3、 负责对外联络与接待工作包括联系各种场地等；
应聘条件：
1、能够尽快入职(或者一个月左右能够到岗工作)；
2、能长期稳定工作；
3、年龄18-30岁之间，经验不限，专业不限；
4、美国上市集团总公司——注重个人综合素质及能力，目前正在招收应届生及实习生。
待遇：
1、底薪+奖金=3000-6000（根据个人能力提升）；
2、五险一金，带薪年假，双休，节日福利，有餐补等；
3、可提供住宿或者就近安排工作地点；
4、试用期1-3个月（根据个人能力）转正后享有平均月薪不低于3000元/月收入。
工作时间：
1、国家法定作息时间；
2、周末双休，上9:00下6:00，中午一小时午休时间。
公司招揽综合素质能力贤才，组织完善培训计划，工作经验不足者有老员工培养，并且公司提供全方位的办公环境和设施设备。
待遇优厚，试用期三个月，试用期间上五险一金，周末双休，有餐补，办公环境优越，节日福利，法定节假日~！有良好的发展及晋升空间。

工作地址：
天津塘沽外滩
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
课程顾问
天津优嘉教育科技有限公司
每年多次调薪五险一金绩效奖金年终分红加班补助全勤奖创业公司节日福利
**********
福利:
每年多次调薪
五险一金
绩效奖金
年终分红
加班补助
全勤奖
创业公司
节日福利
**********
职位月薪：5000-10000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：20人
职位类别：培训/招生/课程顾问
**********
职位描述：
1、负责天津优嘉相关课程的销售工作；
2、通过来访登记、电话等方式，约请有意向学员及家长到教学区咨询；
3、接待来访学员，根据学员测试水平和预期学习目标推介适合的课程；
4、建立与学员之间的良好关系，确保学员满意度并达成学习目标，维护学校形象；
5、保证咨询质量，完成部门制定的招生计划。

任职要求：
1、高度认同优嘉企业文化；
2、大专本科以上学历，一年以上销售经验，有过教育行业经验者优先考虑；
3、形象气质佳，普通话标准口齿伶俐；
4、热爱销售事业，能适应强度高高挑战的工作；
5、具备高速、高效、灵活工作的能力，高度的责任感，极强的沟通能力。
工作地址：
和平区鞍山道与山西路交口 优嘉教育
查看职位地图
**********
天津优嘉教育科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
教育/培训/院校
公司地址：
**********
招聘 金融产品销售 信贷专员 五险一金 双休
天津兴宇互联信息技术有限公司
五险一金绩效奖金加班补助交通补助通讯补贴定期体检员工旅游节日福利
**********
福利:
五险一金
绩效奖金
加班补助
交通补助
通讯补贴
定期体检
员工旅游
节日福利
**********
职位月薪：8001-10000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：5人
职位类别：电话销售
**********
岗位职责：
1、负责访客、来宾的登记、接待、引见；
2、负责客人来访迎送等招待工作;
3、协助上级主管对各项人事行政事务的安排及执行; 
4、完成上级交给的其它事务性工作。

任职资格：
  1、年龄在18-26岁之间，形象好气质佳，身高160cm以及上；
  2、性格活泼开朗，普通话标准；
  2、有亲和力，良好的沟通协调能力，有相关工作经验优先 ；
  3、具有饱满的工作热情和认真的工作态度；
  4、能完成上级交代的一些行政事务。
 工作地址：
天津市河西区马场道59号平安大厦A座2901-02
面试时间：周一至周五上午10:00--下午2:30可来公司面试
面试电话：18812577167
       座机：022-58531560
工作地址：
天津市河西区马场道59号平安大厦A座2901-02
**********
天津兴宇互联信息技术有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
互联网/电子商务
公司地址：
天津市河西区马场道59号平安大厦A座2901-02
查看公司地图
**********
平面设计助理（五险一金）
天津望京玻璃制品贸易有限公司
每年多次调薪五险一金绩效奖金餐补带薪年假节日福利不加班
**********
福利:
每年多次调薪
五险一金
绩效奖金
餐补
带薪年假
节日福利
不加班
**********
职位月薪：3001-5000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：2人
职位类别：平面设计
**********
岗位职责： 
1、查找相关资料等，协助平面设计师的工作； 
2、能按质按量按时完成设计操作工作； 
3、良好的沟通表达能力、有责任心、勤奋乐观、为人正直、有团队精神。 
任职资格： 
1、大专及以上学历，平面设计专业优先； 
2、一般掌握使用平面设计软件（PSAI）和办公软件； 
3、18-30周岁，有无经验均可。 
待遇： 
1、入职即上五险，转正缴纳一金； 
2、带薪年假，节日福利，有餐补等； 
3、试用期1-3个月，转正后享有平均月薪不低于4000元/月收入 
工作时间： 
1、国家法定作息时间 
2、周末双休，上9:00下6:00，中午一小时午休时间。
工作地址：
天津市滨海新区营口道
查看职位地图
**********
天津望京玻璃制品贸易有限公司
公司规模：
500-999人
公司性质：
上市公司
公司行业：
贸易/进出口
公司地址：
天津市
**********
平面设计
天津优视展示制作有限公司
年底双薪五险一金加班补助全勤奖交通补助餐补员工旅游带薪年假
**********
福利:
年底双薪
五险一金
加班补助
全勤奖
交通补助
餐补
员工旅游
带薪年假
**********
职位月薪：4001-6000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：不限
招聘人数：3人
职位类别：平面设计
**********
1：熟练使用相关软件。
2：为固定客户提供设计服务

工作地址：
天津市和平区昆明路与宜昌道交口清华园5-1602
查看职位地图
**********
天津优视展示制作有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市
**********
4k新媒体运营+可实习双休
天津金珑基科技有限责任公司
每年多次调薪五险一金绩效奖金餐补节日福利不加班
**********
福利:
每年多次调薪
五险一金
绩效奖金
餐补
节日福利
不加班
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：5人
职位类别：新媒体运营
**********
岗位职责：
1、18-32岁，男女不限；
2、对互联网行业有一定了解，网络营销、电子商务专业优先；
3、良好的沟通协调能力及创新意识，有良好的活动策划能力；
4、执行力好，工作用心，勤奋踏实，学习能力强，态度良好，有上进心；

福利待遇
1、五险一金，转正薪资3500-4000元+奖金；
2、带薪年假，节日礼金，季度优秀员工旅游；
3、朝九晚六，双休，法定节假日按国家规定执行；
4、发放生活补贴、住宿补贴、话费补贴、车费补贴！

工作时间：
1、国家法定作息时间；
2、周末双休，上9:00下6:00，中午一小时午休时间。
欢迎各位应届生前来面试！
2017年，我们公司正处于快速发展期！待遇优厚，欢迎有经验、优秀的有志青年投身加入！
多一次简历投递，多一次面试机会！
工作地址：
天津市塘沽区营口道
查看职位地图
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
办公室文员+待遇优双休
天津望京玻璃制品贸易有限公司
每年多次调薪五险一金绩效奖金餐补带薪年假节日福利不加班
**********
福利:
每年多次调薪
五险一金
绩效奖金
餐补
带薪年假
节日福利
不加班
**********
职位月薪：2001-4000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：3人
职位类别：内勤人员
**********
岗位描述：
1、想获得一份长期稳定且有发展前景的工作。
2、好学、细心，有强烈的责任心和上进心。
3、要求熟悉基本的计算机操作，办公软件的使用。
4、可无经验，有晋升空间！
待遇：
1、底薪+奖金=3000-6000（根据个人能力提升）；
2、五险一金，带薪年假，双休，节日福利，有餐补等；
3、可提供住宿或者就近安排工作地点；
4、试用期1-3个月（根据个人能力）转正后享有平均月薪不低于3000元/月收入。
工作时间：
1、国家法定作息时间；
2、周末双休，上9:00下6:00，中午一小时午休时间。
工作地址：
天津市塘沽区塘沽大剧院旁
**********
天津望京玻璃制品贸易有限公司
公司规模：
500-999人
公司性质：
上市公司
公司行业：
贸易/进出口
公司地址：
天津市
**********
销售经理(天津地铁广告媒体)
天津雅铁广告传媒有限公司
五险一金绩效奖金通讯补贴采暖补贴带薪年假定期体检高温补贴节日福利
**********
福利:
五险一金
绩效奖金
通讯补贴
采暖补贴
带薪年假
定期体检
高温补贴
节日福利
**********
职位月薪：4000-8000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：5人
职位类别：广告客户代表
**********
岗位职责：
1. 熟悉内外部资源市场，利用媒体及客户资源，按时完成个人销售任务、业绩评估考核；
2. 积极开发客户，同时维护良好的客户关系；
3. 整合客户需求，为客户制定媒体方案，协调好媒体投放过程中的事项；
4. 签订合同并跟进后期发布，确保客户的账款在账期内正常回款；
5. 领导交办的其他事宜。
任职要求：
1. 3年以上销售经验或2年以上广告媒体销售经验，1年以上销售团队管理经验，有户外广告行业销售经验优先考虑；
2. 大专及以上学历，市场营销相关专业为佳；
3. 具备优秀的销售能力及销售技巧，能够充分利用公司资源和平台高效完成销售目标；
4. 具备较强的市场开拓及领导团队能力，出色的协调及处理事务能力，卓越的市场策划及运作能力；
5. 诚信、负责，沟通能力强，思维敏捷，用于接受挑战。

工作地址：
天津和平区大沽北路新华国金中心
查看职位地图
**********
天津雅铁广告传媒有限公司
公司规模：
20-99人
公司性质：
合资
公司行业：
广告/会展/公关
公司主页：
http://www.asiaray.com
公司地址：
天津和平区大沽北路72号
**********
信息审核员双休待遇高
天津金珑基科技有限责任公司
每年多次调薪五险一金年终分红餐补带薪年假节日福利不加班
**********
福利:
每年多次调薪
五险一金
年终分红
餐补
带薪年假
节日福利
不加班
**********
职位月薪：2001-4000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：3人
职位类别：电脑操作/打字/录入员
**********
岗位职责：
1、档案资料整理：编页、排序；
2、数据录入：打字录入；
3、档案扫描：使用扫描仪进行扫描工作等；
任职资格：
1、经验不限，专业不限。
2、计算机操作熟练，office办公软件使用熟练。
3、性格要求沉稳、隐忍，善于倾听，有同理心，乐观、积极。
福利待遇：
1、五险一金，带薪年假，双休，节日福利，餐补等；
2、可提供住宿或者就近安排工作地点；
3、试用期1-3个月，转正后享有平均月薪不低于3000元/月收入。
工作时间：
周一至周五；法定节假日休息，上九下六，8小时上班时间

工作地址：
天津塘沽新村街营口道
查看职位地图
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
招聘专员
天津兴宇互联信息技术有限公司
无试用期每年多次调薪绩效奖金交通补助弹性工作定期体检员工旅游节日福利
**********
福利:
无试用期
每年多次调薪
绩效奖金
交通补助
弹性工作
定期体检
员工旅游
节日福利
**********
职位月薪：2001-4000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：3人
职位类别：招聘专员/助理
**********
岗位职责
1、专业人员职位，在上级的领导和监督下定期完成量化的工作要求，并能独立处理和解决所负责的任务；
2、了解掌握各部门的用人需求；
3、实施招聘工作，发布招聘广告、进行简历筛选、评估候选人并提供初步面试报告；
4、管理、开发招聘渠道；
5、维护人才储备库。

任职资格
1、一年以上相关工作经验；
2、有人力资源招聘的实务操作经验，熟悉国家相关法律法规；
3、性格温和、有耐心、积极主动，为人正直，忠诚守信，工作严谨，具有很好的语言文字表达能力；
4、熟练使用办公软件。
工作地址：河西区马场道小白楼平安大厦A座2901室
联系电话：18812577167
工作地址：
天津市河西区马场道59号平安大厦A座2901-02
**********
天津兴宇互联信息技术有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
互联网/电子商务
公司地址：
天津市河西区马场道59号平安大厦A座2901-02
查看公司地图
**********
销售经理
天津鸿源信息技术有限公司
五险一金绩效奖金年终分红加班补助交通补助餐补房补通讯补贴
**********
福利:
五险一金
绩效奖金
年终分红
加班补助
交通补助
餐补
房补
通讯补贴
**********
职位月薪：6001-8000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：3人
职位类别：公关经理/主管
**********
销售代表

岗位职责： 
1、熟知公司网站广告，通过恰当的方式向潜在客户销售公司广告产品，完成一定的销售任务； 
2、服从公司领导的安排，配合商务经理完成本部门广告任务； 
3、能够与其他同事共同协作，充分把握客户需求，发掘潜在客户，共同完成部门销售目标； 
4、欢迎工作态度积极进取，具有强烈想成功的欲望，挑战高薪的人加入。 
职位要求： 
1、大专以上学历，市场营销专业优先考虑； 
2、具备优秀的电话沟通技巧、表达技巧和销售技巧，普通话标准流利； 
3、富有开拓精神和良好的团队合作意识，有很强的学习和沟通能力，良好的协调能力； 
4、.熟悉计算机和互联网络，有较强服务意识； 
5、具有敬业精神，有强烈的竞争意识，能积极面对工作挑战； 
6、有良好的职业素质、合作意识及团队精神。 

工作地址：
天津市河东区新开路与华兴道交口南侧创智大厦1-811
查看职位地图
**********
天津鸿源信息技术有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
互联网/电子商务
公司主页：
//www.worldpp.cn
公司地址：
天津市河东区新开路与华兴道交口南侧创智大厦1-811
**********
文案编辑
天津古天文化传播有限公司
五险一金绩效奖金弹性工作
**********
福利:
五险一金
绩效奖金
弹性工作
**********
职位月薪：3000-6000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：2人
职位类别：广告文案策划
**********
岗位职责：
1、负责配合策划进行运营类文案编辑、策划、撰写工作；
2、负责新闻、微信公众号等公共平台的内容制作及编辑；
3、热爱互联网营销推广工作，对网络营销经典案例有强烈的超越欲望；
4、具有良好的团队精神，细心、正直、积极、责任心强；

任职资格：
1、具有极强的文字功底，良好的审美能力；（创造不限于软文、贴文、新闻等，风格屌丝、文艺、高大上）
2、具有地产广告相关的文案策划 或 网络创意 经验者优先；

工作地址：
天津市河西区小白楼凯德国贸C座
查看职位地图
**********
天津古天文化传播有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
互联网/电子商务
公司地址：
天津市经济技术开发区六大街徽山路23号
**********
网站项目主管
天津鸿源信息技术有限公司
五险一金绩效奖金加班补助交通补助餐补通讯补贴带薪年假节日福利
**********
福利:
五险一金
绩效奖金
加班补助
交通补助
餐补
通讯补贴
带薪年假
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津-河东区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：WEB前端开发
**********
岗位职责：
1. 负责Web产品的前端表现层与后端交互的设计和开发，保证页面浏览的兼容性和流畅浏览；
2. 负责Javascript程序模块的开发，通用类库和框架的编写；
3. 负责配合产品经理、后端开发人员实现产品界面和性能需求；
4. 负责制定产品前端代码的规范，最大限度地实现代码的可重用性；
5. 快速响应产品迭代以及优化升级，持续优化前端体验，并保持良好兼容性，提升友好和易用性。
6.对现有系统的不足进行分析，找到目前系统的瓶颈，改进系统算法，提高系统性能
7.完成网站的开发及线上服务稳定性保障

任职要求：
任职要求：
1. 扎实的计算机专业相关知识和理论基础；
2. 熟悉Linux环境下进行软件开发和服务器环境配置，有CentOS使用经验优先；
3. 精通PHP，熟练使用至少一种常用PHP服务器端程序框架，有CodeIgniter、Wordpress使用经验优先；
4. 熟悉web前端技术，包括：Html/Javascript/CSS等，有网站建设经验优先；
5. 熟悉MySQL数据库，能够根据需求编写和优化查询；
以下技能为加分项：
6. 熟悉至少一种脚本语言，有Python使用经验优先；
7. 熟悉阿里云相关产品，有ECS/RDS/OSS/SLB或其他服务使用经验优先。

工作地址：
天津市河东区新开路与华兴道交口南侧创智大厦1-811
**********
天津鸿源信息技术有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
互联网/电子商务
公司主页：
//www.worldpp.cn
公司地址：
天津市河东区新开路与华兴道交口南侧创智大厦1-811
查看公司地图
**********
客户执行AE
天津古天文化传播有限公司
五险一金绩效奖金弹性工作
**********
福利:
五险一金
绩效奖金
弹性工作
**********
职位月薪：3000-6000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：广告制作执行
**********
岗位职责：
1、负责跟进客户、提案、拟订修改合同、催收项目款项、项目的事务衔接，
2、负责项目的整体服务及协调工作，及时准确的与客户沟通并完成客户需求。
3、有效衔接并协调公司内部各部门在项目实施过程中的密切配合；
4、独立收集、整理客户以及行业相关信息和数据资料。
 任职资格：
1、性格开朗、有强烈的进取心，头脑清晰、反应机敏，具备良好的组织、沟通协调能力；
2、有强烈的时间观念和服务意识，适应和学习能力强，乐于接受新鲜事务；
3、有广告/房地产AE工作经验者优先录考虑。
 福利待遇：底薪+奖金+社保+年终奖
双休，享受国家法定节假日

工作地址：
天津市河西区小白楼凯德国贸C座
查看职位地图
**********
天津古天文化传播有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
互联网/电子商务
公司地址：
天津市经济技术开发区六大街徽山路23号
**********
项目经理
天津市美业广告有限公司
绩效奖金加班补助包吃餐补
**********
福利:
绩效奖金
加班补助
包吃
餐补
**********
职位月薪：5000-10000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：不限
招聘人数：2人
职位类别：广告/会展项目管理
**********
任职要求：
1.有相关特装公司和装饰公司监理经验和展览展示，美术陈列，会展布展，公关活动经验，熟悉特装工艺。
2.对汽车行业，家电行业，地产行业，快消品行业有所了解
3.具有较强的工作能力，具备独立思考，独立解决问题的能力，抗压能力，有责任心
4.有展会、展览、展示等现场执行工作经验优先
 岗位职责：
具有良好的沟通和组织协调能力，能带动团队为客户提供优质高效的服务
有进取心，能适应较强的工作压力，有较强的责任心
与企业客户关系良好并擅长协调和维护客户关系
 条件优秀者可相应放宽。不符合条件者勿扰
入职后签订劳动就业合同，上五险+单休法定假日,有良好的晋升空间


工作地址：
天津市河东区六纬路与九经路交口祥云名苑
**********
天津市美业广告有限公司
公司规模：
20-99人
公司性质：
股份制企业
公司行业：
广告/会展/公关
公司主页：
null
公司地址：
河东十一经路万隆太平洋大厦
查看公司地图
**********
文案编辑
天津古天文化传播有限公司
五险一金绩效奖金
**********
福利:
五险一金
绩效奖金
**********
职位月薪：4001-6000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：2人
职位类别：广告文案策划
**********
岗位职责：
1、负责配合策划进行运营类文案编辑、策划、撰写工作；
2、负责新闻、微信公众号等公共平台的内容制作及编辑；
3、热爱互联网营销推广工作，对网络营销经典案例有强烈的超越欲望；
4、具有良好的团队精神，细心、正直、积极、责任心强；

任职资格：
1、具有极强的文字功底，良好的审美能力；（创造不限于软文、贴文、新闻等，风格屌丝、文艺、高大上）
2、具有地产广告相关的文案策划 或 网络创意 经验者优先；

工作地址：
天津市河西区小白楼凯德国贸
**********
天津古天文化传播有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
互联网/电子商务
公司地址：
天津市经济技术开发区六大街徽山路23号
查看公司地图
**********
策划
跬步(天津)网络科技有限公司
创业公司五险一金全勤奖弹性工作不加班节日福利绩效奖金
**********
福利:
创业公司
五险一金
全勤奖
弹性工作
不加班
节日福利
绩效奖金
**********
职位月薪：8001-10000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：1人
职位类别：品牌策划
**********
职位描述

工作职责： 
1、建立和完善公司的企业文化、产品包装、品牌文化和管理文化体系； 
2、企宣策划：负责公司企业宣传及项目宣传等工作，负责企划方案的撰写和统筹，整体策划创意，设计与提报，并组织实施； 
3、品牌管理：研究制定公司品牌策划方案，负责企业形象与品牌管理； 
4、营销策划：编制公司推广策划方案，制作宣传品，选择传播媒体，进行业务推广工作等。 
5、活动推广：负责活动创意与推广策略的制定； 制订年度、季度、月度推广方案； 
6、产品包装：负责公司产品的视觉设计与规范，提高产品包装的独特性和审美。 

任职资格： 
1、能够独立组织制定企业宣传策划、市场推广、产品包装等工作；具备较强的市场策划能力、文案撰写能力和市场推广组织实施能力； 
2、具备相当成熟的视觉表现手段以及制作执行的经验，对视觉作品具备高度把控与指导能力； 
3、统筹协调业务推广、品牌策划活动全流程；有过大型公司或大型活动品宣、企划方案的成功案列优先； 
4、出色的协调能力、沟通能力，知识面广、思维活跃。 

教育背景： 
广告、市场营销、传媒、中文、美术设计等相关专业本科以上学历。

工作地址：
红桥区宝能创业中心B座701
查看职位地图
**********
跬步(天津)网络科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
互联网/电子商务
公司主页：
http://www.wschuangke.com
公司地址：
南开区慧谷大厦1518室
**********
副总经理
天津优视展示制作有限公司
五险一金年底双薪绩效奖金年终分红
**********
福利:
五险一金
年底双薪
绩效奖金
年终分红
**********
职位月薪：10001-15000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：不限
招聘人数：1人
职位类别：副总裁/副总经理
**********
负责广告公司业务开展。
协助进行公司行政管理。
工作地址：
天津市和平区昆明路与宜昌道交口清华园5-1602
查看职位地图
**********
天津优视展示制作有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市
**********
客户经理|销售业务|商务代表|客户代表|业务代表|大客户销售代表
天津三五互联科技有限公司
五险一金交通补助通讯补贴带薪年假员工旅游
**********
福利:
五险一金
交通补助
通讯补贴
带薪年假
员工旅游
**********
职位月薪：4001-6000元/月 
工作地点：天津-南开区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：销售代表
**********
岗位要求：
1.口齿清晰、性格外向、开朗自信，有比较强的语言表达能力和与人沟通能力；
2.市场营销、电子商务、计算机等相关专业，基本掌握计算机操作以及相关办公软件的操作；
3.熟悉电话销售模式，有电话销售经验者优先；
4.敬业踏实，有强烈的竞争欲望，能积极面对挑战；
5.对销售工作有较高的热情，具有一定的抗压力。

薪资构成：
底薪3000+提成（最高20%）+月度绩效奖金+年度奖金+各项激励奖金；月薪5k-30k
每2-3个月有一次晋升加薪的机会；

为什么要加入三五互联：
加入我们，你将得到——
1.广阔的发展空间：作为一家在全国有23家分公司的上市企业，我们不拘一格降人才，90%的高级岗位都是从内部一线员工中产生晋升，在这里没有资历限制，更没有学历限制，只有能力之别；
2.良好的工作环境：天津分公司地处繁华的鞍山西道时代数码广场、时代数码广场信诚大厦，交通方便，办公环境幽雅；
3.人性化的工作时间：公司严格按照国家标准执行八小时工作制，享受所有国家法定节假日并按照工龄相应享有年假；
4.完善的福利制度：为了保障员工的福利，我们执行5险；
5.自身素质的提升：我公司为新进员工提供7天带薪岗前培训（入职后发放），让新员工能最大程度尽快了解本集团的企业文化、公司产品，并进行职业是生涯规划，让新员工能明确自己的职业方向，入职后的新人，将提供每月1-2次的培训，用以提升销售技能和专业技能；
6.企业文化活动：定期组织旅游，拓展等活动；
7.员工转正后公司为员工提供工作专属170电话卡并报销相应话费。

晋升方向：
见习商务代表-商务代表-高级商务代表-资深商务代表
见习商务代表-商务代表-高级商务代表-储备经理-见习经理-商务经理

工作地址：
天津市南开区鞍山西道时代广场信诚大厦1-1807

工作地址：
天津市南开区鞍山西道时代广场信诚大厦1-1807
**********
天津三五互联科技有限公司
公司规模：
1000-9999人
公司性质：
上市公司
公司行业：
互联网/电子商务
公司主页：
www.35.com
公司地址：
天津市南开区鞍山西道时代广场信诚大厦1-1807
查看公司地图
**********
京东客服经理
天津益康天下电子商务有限公司
五险一金年底双薪绩效奖金全勤奖带薪年假定期体检节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
全勤奖
带薪年假
定期体检
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：天津-河西区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：客户服务经理
**********
岗位职责：
1、部门组织结构的制订和优化，客服部门业务操作规范；
2、负责业务流程的制定、优化、以及监督和执行；
3、负责业绩考核、奖惩制度的制订和落实公司考核指标；
4、负责或安排人员进行线上系统的功能可用性定期检测、汇总和上报；
5、负责客服部投诉和内部处罚的处理；
6、落实部门协调和各项推广活动的配合；
7、人员日常管理，人员培训，人员招聘等工作；
8、配合结算部门对差错订单进行退款和原因查找并进行解决；
9、客户流失率分析与报告。

任职资格：
1、大专及以上学历，懂得公关礼仪、管理学等业务知识；
2、沟通能力强，具有团队合作精神；
3、善于对业务流程进行优化，不断追求提高服务效率和服务质量；
工作时间：8:30—16:30  周末双休
 其他福利待遇： 
1、合理优厚的薪金：基本工资（4200元/月）+绩效奖金+补贴+年终奖+优秀员工激励奖金；
 2、完善的假期组合：带薪年假、带薪病假及法定假期；
 3、齐全的福利体系：养老保险、医疗保险+补充医疗保险、生育保险、 工伤保险、失业保险及住房公积金；
 4、丰富多彩的员工活动：员工聚餐、节日晚会、旅游活动、优秀员工表彰活动等；
 5、多元化培训课程：带薪岗前培训，在职个人提升计划。
工作地址：
天津市河东区双赢大厦（天津站后广场）
**********
天津益康天下电子商务有限公司
公司规模：
20人以下
公司性质：
其它
公司行业：
互联网/电子商务
公司地址：
天津市河东区双赢大厦（天津站后广场）
**********
电话销售
天津百思道商务咨询有限公司
五险一金全勤奖节日福利带薪年假绩效奖金
**********
福利:
五险一金
全勤奖
节日福利
带薪年假
绩效奖金
**********
职位月薪：4001-6000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：电话销售
**********
岗位职责：
1、在公司原有客户资源的基础之上，根据网络及媒体平台收集目标客户资料；
2、通过已有资源发掘潜在客户，通过电话进行渠道开发和业务拓展；
3、收集、记录客户反馈信息，进行分析，挖掘客户需求，跟踪销售；
4、协同销售部门进行文档、客户资料的管理。
任职要求：
1、专科或以上学历，一年以上相关工作背景；
2、擅于沟通、思维灵敏、表述能力强、口齿清晰、富有亲和力；
3、有责任心、能承受工作压力，有团队合作精神。

工作地址：
天津市和平区吉林路38号轻纺大厦409室
查看职位地图
**********
天津百思道商务咨询有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
专业服务/咨询(财会/法律/人力资源等)
公司地址：
天津市和平区吉林路38号轻纺大厦409室
**********
宣传文案
正大煜恒文化传播(天津)有限公司
**********
福利:
**********
职位月薪：4001-6000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：1人
职位类别：文案策划
**********
职位要求：
1、 负责各宣传片影视项目的定位与策划案的撰写；
2、 了解商业宣传片市场，及时把握新动态、新趋势，为公司提供有效的市场信息等；
3、清晰项目目标，了解客户需求.负责项目具体内容撰写，为推广软文、新闻稿、软文、微博、微信进行文字、图片等多种形式的内容产出，结合活动及热点等策划微博、微信营销文案；
4、支持项目阶段性的线上活动创意、文案撰写等工作，对项目日常运营中的内容、活动创意负责；
岗位要求：
1、良好的方案撰写能力，活动策划执行推广能力，大学本科以上 学历；
2、3年以上有影视公司宣传，新闻发布活动策划，娱乐媒体等工作经验；
4、热爱影视行业，关注影视宣传，思维活跃；
工作地址：
天津鞍山西道
查看职位地图
**********
正大煜恒文化传播(天津)有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
媒体/出版/影视/文化传播
公司地址：
天津河西梅江新闻中心旁
**********
行政主管/经理
天津益康天下电子商务有限公司
五险一金年底双薪加班补助全勤奖包吃包住补充医疗保险员工旅游
**********
福利:
五险一金
年底双薪
加班补助
全勤奖
包吃
包住
补充医疗保险
员工旅游
**********
职位月薪：6001-8000元/月 
工作地点：天津-河东区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：行政经理/主管/办公室主任
**********
岗位职责 
Ø  业务主管职位，独立负责工作小组，给下级成员提供指导或支持并监督他们的日常活动； 
Ø  配合部门经理制定公司行政管理制度并监督执行； 
Ø  为公司所有业务部门提供必要的办公设施及其他后勤支持； 
Ø  负责公司车辆、设备、设施等固定资产的调配及管理； 
Ø  负责行政、招聘、薪酬、企业活动等人力资源日常管理事宜；主要侧重行政、薪酬、企业活动三个方面；
Ø  协助推动公司理念及企业文化的形成，负责组织企业文化活动，具体包括员工活动的策划，组织实施；
Ø  负责公司员工日常薪酬福利计算、提成的核算发放；
Ø  全面负责公司行政管理工作，为公司的正常运作提供优质的服务和后勤保障；
任职资格 
1、大专及以上学历（行政管理、企业管理等相关专业优先考虑）； 
2、两年以上行政工作经验； 
3、熟悉行政工作流程，办公用品采购流程，企业资产管理； 
4、较强的责任心和敬业精神，良好的组织协调能力及沟通能力，较强的分析、解决问题能力； 
5、熟练使用办公软件和办公自动化设备。
薪资待遇：
 1. 合理优厚的薪金：基本工资（5500元/月）+绩效奖金+补贴+年终奖+优秀员工激励奖金等,
 2. 完善的假期组合：带薪年假、带薪病假及法定假期；
 3. 优厚的福利体系：养老保险、医疗保险+补充医疗保险、生育保险、工伤保险、失业保险及住房公积金；
 4. 丰富多彩的员工活动：员工聚餐、年度体检、节日晚会、旅游活动、运动会、优秀员工表彰活动等；
 5. 多元化培训课程：带薪岗前培训，在职个人提升计划；
 6. 良好晋升机会：内部转职（横向发展）、纵向提升；
 7. 舒适工作环境。

工作地址：
天津-河东区
**********
天津益康天下电子商务有限公司
公司规模：
20人以下
公司性质：
其它
公司行业：
互联网/电子商务
公司地址：
天津市河东区双赢大厦（天津站后广场）
**********
课程顾问（五险一金）
天津思佳美育教育信息咨询有限公司
五险一金绩效奖金年终分红全勤奖不加班
**********
福利:
五险一金
绩效奖金
年终分红
全勤奖
不加班
**********
职位月薪：5000-10000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：培训/招生/课程顾问
**********
工作职责： 
   -与顾客建立良好的关系，完成每月的销售指标 
   -参与和支援相关销售和市场活动，配合中心总监完成各项团队工作 
   -发展客户关系并且对其进行维护 
   -对儿童的发展和进步给予咨询意见 
   -负责客户接待、课程咨询、签约等相关工作
   -邀约家长到店参加体验课程并且完成销售流程。
入职要求： 
   -大专以上学历，有培训机构课程销售经验者优先，条件优秀者学历可放宽
   -有销售等工作经验优先 
   -良好最终用户的销售经验 
   -充满活力，个性开朗，积极乐观
   -优秀的沟通及演示技巧
   -主动个性，良好的人际沟通能力 
   -热爱儿童事业，有耐心和爱心 
   -有较强的抗压能力
   -有1-3年工作经验者优先
   -欢迎优秀应届生投递

工作地址：
天津市河东区爱琴海公园3楼
**********
天津思佳美育教育信息咨询有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
教育/培训/院校
公司地址：
天津市河东区爱琴海公园3楼
查看公司地图
**********
人力资源专员
精锐世纪(天津)会展有限公司
五险一金绩效奖金餐补带薪年假节日福利员工旅游
**********
福利:
五险一金
绩效奖金
餐补
带薪年假
节日福利
员工旅游
**********
职位月薪：4001-6000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：人力资源专员/助理
**********
岗位职责：
1、招聘与培训体系的建立并按体系运作。
2、人力需求的分析与招聘计划的制定。
3、提供个部门所需的人员，保障公司各项工作的顺利开展。
4、负责对招聘后试用人员的评估工作。
5、负责内部人员的选拔工作。
6、负责新进员工的入职教育工作。
7、人员档案管理、合同续签的工作；
8、公司人员的入职、离职管理工作；
9、全公司人员的保险、公积金、人才引进等办理工作；
10、协助人力资源部经理建立和完善公司的员工关系管理体系；
任职要求：
大专以上学历，人力资源专业优先；
相关招聘工作1年以上经验，同时熟悉河西区人社局相关政策；
沟通能力良好，具有优秀的组织协调能力；

工作地址：
天津市西青华鼎高新技术产业园区创新六路华鼎新区一号17号楼
查看职位地图
**********
精锐世纪(天津)会展有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
广告/会展/公关
公司主页：
www.jrexpo.cn
公司地址：
天津市西青华鼎高新技术产业园区创新六路华鼎新区一号17号楼
**********
业务代表
天津鸿源信息技术有限公司
五险一金年底双薪绩效奖金餐补带薪年假节日福利交通补助包吃
**********
福利:
五险一金
年底双薪
绩效奖金
餐补
带薪年假
节日福利
交通补助
包吃
**********
职位月薪：4001-6000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：3人
职位类别：业务拓展专员/助理
**********
岗位要求：
1、具有一年或以上丰富的互联网网络公司或报刊、媒体广告销售、并有良好的业绩；
2、具有良好的沟通能力和优秀的团队合作能力；
3、具有极强的客户拓展能力；
4、具有极强的沟通判断能力，能适应快速的工作节奏；
5、具有较强的市场洞查能力和销售职业素质，善于听取和总结客户需求；
6、具有良好的团队意识，善于与他人沟通与合作。
7、应届毕业生需要积极上进、踏实肯干、认真负责、勤奋敬业的工作态度，讲诚信、负责任、有毅力、有抱负、有热情；
8、资深业务人员需要具有丰富的互联网文字链相关销售经验，并具有丰富的市场资源和公共关系者优先；
岗位职责
1、开发客户市场，完成公司每月下达的招商指标。
2、维护公司与客户的良好关系。
3、负责网站入驻的招商服务工作，不断提高服务质量。



工作地址
天津市河东区新开路与华兴道交口南侧创智大厦1-811

工作地址：
天津市河东区新开路与华兴道交口南侧创智大厦1-811
**********
天津鸿源信息技术有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
互联网/电子商务
公司主页：
//www.worldpp.cn
公司地址：
天津市河东区新开路与华兴道交口南侧创智大厦1-811
查看公司地图
**********
兼职(3分钟98元)秘书助理设计驾驶客服经理
南京天鹰图新测控技术有限公司
五险一金年底双薪绩效奖金年终分红加班补助全勤奖弹性工作节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
年终分红
加班补助
全勤奖
弹性工作
节日福利
**********
职位月薪：15001-20000元/月 
工作地点：天津
发布日期：最新
工作性质：兼职
工作经验：不限
最低学历：不限
招聘人数：28人
职位类别：兼职
**********
【全国招聘】 兼或全职时间自由：可以在家，在外，在公司，在任何地方，用手机或者电脑操作，简单方便。时间灵活，工作自由。
【公司承诺】免费兼或全职：非职介,不收押金,不收取任何费用。

急招兼或全职：一个任务酬劳为15元-1000元不等，操作达到要求并且完成任务可立即发放工资。
工资一个任务一结算,不拖欠且安全无忧！但是工资的变动取决于您投入时间长短决定，您的收获和付出成正比。
想工作，请联系企业客服张珊QQ：512512318

我们不希望错过任何人才，希望您不要错过任何工作机会。

任职要求：
①自己有上网条件，对网络操作熟练；
②学历不限，在职或学生或者待业人员皆可；
③对网店和网购有一定的兴趣；
④有一定淘宝购物经验者优先

岗位职责：
①工作细心、勤奋、认真负责；
②吃苦耐劳，诚实守信；
③性格开朗，擅长沟通与人际交往，表达清晰流利。


我们不会收您钱，但我们会教您如何在网上挣钱。
本公司的招聘信息已经过工商等相关部门审核认证，请放心兼或全职。
 
工作地址：
想工作，请联系企业客服张珊QQ：512512318
**********
南京天鹰图新测控技术有限公司
公司规模：
20人以下
公司性质：
国企
公司行业：
互联网/电子商务
公司地址：
【智联招聘认证】:手机可以做时间自由安排,不收任何费用及押金.应聘的加企业客服QQ：512512318
**********
平面设计助理待遇优厚
天津望京玻璃制品贸易有限公司
五险一金加班补助包住餐补带薪年假定期体检节日福利不加班
**********
福利:
五险一金
加班补助
包住
餐补
带薪年假
定期体检
节日福利
不加班
**********
职位月薪：4001-6000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：中技
招聘人数：2人
职位类别：平面设计
**********
岗位职责：
1、负责完成公司日常任的务安排,包括平面广告的设计、网页设计、静态页面素材搜集等工作。 
2、负责公司对外日常工作宣传及广告、产品、活动的平面设计。 
3、协助平面设计师，按规定完成策划主题的视觉执行工作。
任职要求：
1、能够尽快入职(或者一个月左右能够到岗工作)
2、能长期稳定工作（不招兼职）。
3、年龄18-30岁之间，经验不限，专业不限
待遇
1、底薪+奖金=3000-6000（根据个人能力提升）
2、五险一金，带薪年假，双休，节日福利，有餐补等；
3、可提供住宿或者就近安排工作地点
4、试用期1-3个月，转正后享有平均月薪不低于3000元/月收入
工作时间：
1、国家法定作息时间
2、周末双休，上9:00下6:00，中午一小时午休时间。
公司招揽综合素质能力贤才，组织完善培训计划，工作经验不足者有老员工培养，并且公司提供全方位的办公环境和设施设备。
待遇优厚，试用期三个月，试用期间上五险一金，周末双休，有餐补，办公环境优越，节日福利，法定节假日~！有良好的发展及晋升空间。
应聘者可投递简历，人事部将在3个工作日内安排面试时间,或在右下角在线预约面试时间，并留下你的姓名+学历+年龄+电话，谢谢合作。

工作地址：
天津市南开区南开大学西门
**********
天津望京玻璃制品贸易有限公司
公司规模：
500-999人
公司性质：
上市公司
公司行业：
贸易/进出口
公司地址：
天津市
**********
电话销售
天津鸿源信息技术有限公司
五险一金带薪年假弹性工作节日福利不加班每年多次调薪包吃员工旅游
**********
福利:
五险一金
带薪年假
弹性工作
节日福利
不加班
每年多次调薪
包吃
员工旅游
**********
职位月薪：6001-8000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：10人
职位类别：电话销售
**********
岗位职责： 
1、通过培训熟知公司互联网产品，通过电话的方式向潜在客户销售公司产品，完成一定的销售任务； 
2、服从公司领导的安排，配合商务经理完成本部门各项产品销售任务； 
3、能够与其他同事共同协作，充分把握客户需求，发掘潜在客户，共同完成部门销售目标； 
4、欢迎工作态度积极进取，具有强烈想成功的欲望，挑战高薪的人加入。 
职位要求： 
1、大专以上学历，市场营销专业优先考虑； 
2、具备优秀的电话沟通技巧、表达技巧和销售技巧，普通话标准流利； 
3、富有开拓精神和良好的团队合作意识，有很强的学习和沟通能力，良好的协调能力； 
4、.熟悉计算机和互联网络，有较强服务意识； 
5、具有敬业精神，有强烈的竞争意识，能积极面对工作挑战； 
6、有良好的职业素质、合作意识及团队精神。 

以上职位一经录用，公司将提供广阔的发展空间和完善的福利待遇： 
1、薪酬：固定底薪+高额提成+奖金 
2、福利：社会保险+带薪年假+节日福利+各项法定假日+各项培训+不定期员工活动 
3、晋升：每两个月一次级别晋升及加薪机会 
4、员工职业发展空间：销售代表―高级销售代表-团队经理
工作地址
天津市河东区新开路与华兴道交口南侧创智大厦1-811

工作地址：
天津市河东区新开路与华兴道交口南侧创智大厦1-811
查看职位地图
**********
天津鸿源信息技术有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
互联网/电子商务
公司主页：
//www.worldpp.cn
公司地址：
天津市河东区新开路与华兴道交口南侧创智大厦1-811
**********
flash动画师
正大煜恒文化传播(天津)有限公司
**********
福利:
**********
职位月薪：4001-6000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：不限
招聘人数：2人
职位类别：多媒体/动画设计
**********
岗位职责：
1.有创造力，具备一定的插画设计能力，构图能力；
2.有较好的造型色彩控制能力；
3.热爱动画制作事业，有良好的沟通能力和团队合作精神，有责任心。

任职资格：
热爱动漫游戏，有创造力，熟悉动画；
1、18-28周岁，大专以上学历，身体健康。
2、具备良好的沟通协调能力，有一定的美术功底，能够熟练的独立制作flash动画熟练使用各种专业软件及周边辅助工具。拥有独立成熟作品。
4、工作踏实、稳定。

.薪资待遇:入职五险一金 周末双休 实习3000-5000 转正4000-6000.
福利待遇:季度和年终奖、五险一金及补充医疗险、餐补、车贴和带薪年假
工作地址：
天津鞍山西道
查看职位地图
**********
正大煜恒文化传播(天津)有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
媒体/出版/影视/文化传播
公司地址：
天津河西梅江新闻中心旁
**********
招标商务经理/助理
北京某国有展览广告公司
五险一金绩效奖金交通补助餐补通讯补贴采暖补贴带薪年假高温补贴
**********
福利:
五险一金
绩效奖金
交通补助
餐补
通讯补贴
采暖补贴
带薪年假
高温补贴
**********
职位月薪：5000-10000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：2人
职位类别：项目招投标
**********
中国邮电器材集团公司（以下简称为邮电器材）成立于1964年，先后归属于邮电部、信息产业部、中央企业工委、国务院国有资产监督管理委员会管理，现为中国通用技术(集团)控股有限责任公司的全资子公司。邮电器材业务涉及通信终端产品及配件销售、零售维修、物流、展览、贸易、招投标、电信增值业务和电子商务等领域，总部设在北京，现有数十家全资子企业、控股企业、合资企业、参股企业。
国际贸易部是邮电器材的二级部门，拥有机电产品国际招标机构甲级资格、通信建设项目招标代理机构甲级资格和政府采购代理机构甲级资格，专业从事国内外贸易和国内外招标代理等业务，长期为电信运营商提供设备采购国际招标、集中采购招标、进口代理和国内项目采购商务代理等服务，与电信运营商和设备制造商建立了紧密的合作关系，通过发展逐步成为"运营商的服务商"。
国际贸易部拥有一支有多年专业经验的高素质职工队伍，其中研究生以上学历的占24%，大学本科以上占92%。我们愿充分利用在进出口及招投标业务上的经验优势，与社会各界真诚合作，不断提高服务水平，以优质高效的服务和优良的商业信誉，为合作各方提供最佳服务，实现共赢。
岗位职责：
1.主要工作是为电信运营商提供物资、服务采购环节的综合商务服务，负责按采购或招标流程组织各个环节的工作，包括但不限于拟定招标方案，编制招标文件，负责发布招标公告，发售招标文件，并进行资质审核，负责组织开评标等活动，组织专家评审，编写评标报告等；
2. 使用Office软件编制采购环节各阶段所需文件，并进行数据汇总、整理和分析撰写相关文件；
3. 为用户提供采购环节有关法律法规及相关政策的咨询服务，提供合理的建议；
4. 负责采购环节各阶段会议的会务服务工作；
5. 收集、保存采购各环节相关文档及领导安排的其他工作。
任职资格：
1.须全日制本科以上学历，理工科或国际贸易类专业，一年以上工作经验；
2.从事过移动、联通、电信等运营商通信招标代理经验的优先考虑；取得招标师资质或中级职称的人员优先录取。
任职要求：
1.熟练使用office办公软件（尤其是excel）；
2.性格开朗，吃苦耐劳，认真负责，服务意识强，沟通协调能力强，能承受较强的工作和心理压力；
3.党员优先。
工作地址：
河北省石家庄市
查看职位地图
**********
北京某国有展览广告公司
公司规模：
20-99人
公司性质：
国企
公司行业：
广告/会展/公关
公司地址：
北京市西城区复兴门
**********
推广专员
天津光度文化活动策划有限公司
五险一金绩效奖金弹性工作创业公司
**********
福利:
五险一金
绩效奖金
弹性工作
创业公司
**********
职位月薪：2001-4000元/月 
工作地点：天津
发布日期：最新
工作性质：校园
工作经验：无经验
最低学历：本科
招聘人数：2人
职位类别：活动策划
**********
岗位职责：
负责线上线下推广方案的制定 实施 以及执行
岗位要求：
1、市场营销管理类或相关专业专科以上学历；
2、优秀的文案功底，有较强的创造性思维能力、创意概念及良好的沟通能力；
3、有一定的组织实施经验，监督、指导、落实促销活动的执行，有成功的策划案例者优先；
4、有综合运用包括广告策划、软文宣传、公关活动等在内的各种营销方式进行市场宣传、品牌推广的能力；
5、熟练操作办公软件。
工作地址：
天津市西青华鼎智地
**********
天津光度文化活动策划有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市南开区红旗南路观景里3-2-703
查看公司地图
**********
平面设计
天津市美业广告有限公司
绩效奖金包吃加班补助
**********
福利:
绩效奖金
包吃
加班补助
**********
职位月薪：5000-10000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：不限
招聘人数：3人
职位类别：平面设计
**********
岗位职责：
1、有广告公司业务经验的优先
2、较强的创意、策划能力，良好的文字表达能力，思维敏捷；
3、熟练使用Photoshop、Flash、fireworks、Dreamweaver、CorelDRAW软件3D软件等常用设计制作软件；条件优秀者可相应放宽，不符合条件者勿扰；
4、工作认真，有责任心，踏实肯干，富有团队精神；
5、具备良好的美术基础，良好的创意构思能力。
6、广告行业工艺平面设计师 了解标识制作工艺流程  明白裁切工艺
任职要求：
1、能够尽快入职、长期稳定工作。
2、大专及大专以上学历
3、具有较强的逻辑分析和独立解决问题能力

入职后签订劳动就业合同，上五险+单休法定假日,有良好的晋升空间


工作地址：
天津市河东区六纬路与九经路交口祥云名苑
**********
天津市美业广告有限公司
公司规模：
20-99人
公司性质：
股份制企业
公司行业：
广告/会展/公关
公司主页：
null
公司地址：
河东十一经路万隆太平洋大厦
查看公司地图
**********
咨询顾问
天津尚道智库企业管理咨询有限公司
五险一金绩效奖金房补带薪年假免费班车节日福利
**********
福利:
五险一金
绩效奖金
房补
带薪年假
免费班车
节日福利
**********
职位月薪：5000-8000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：硕士
招聘人数：10人
职位类别：咨询顾问/咨询员
**********
岗位职责：
  （1）根据项目需求从事区域发展规划、区域经济政策研究、人力资源、企业运作、品牌营销、财务投资等任一方向的管理咨询项目；
   （2）根据项目需求独立进行行业研究、案例分析和标杆研究等；
   （3）根据客户需求开展企业内部访谈、调研，参与咨询方案设计，撰写项目报告；
   （4）在项目经理指导下协助客户推进咨询方案的实施。
任职要求：
 （1）985、211硕士及以上学历，法律、经济、公共管理、情报学、社会经济、区域发展规划类专业优先；
   （2）适应不定时工作；
   （3）良好的逻辑思维能力和数理分析能力；
   （4）出色的交流沟通能力和团队协作能力；
   （5）出色的中英文口头表达和书面表达能力；
   （6）熟练操作电脑，精通Office、WPS等办公软件，尤其擅长PPT制作与讲演；
   （7）学生干部、有相关工作经验的优先。

工作地址：
天津市生态城中天大道2018号生态科技园办公楼14号楼（3B）1楼101室-4
查看职位地图
**********
天津尚道智库企业管理咨询有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
专业服务/咨询(财会/法律/人力资源等)
公司地址：
天津市生态城中天大道2018号生态科技园办公楼14号楼（3B）1楼101室-4
**********
大客户代表AE
天津古天文化传播有限公司
五险一金绩效奖金
**********
福利:
五险一金
绩效奖金
**********
职位月薪：3000-5000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：2人
职位类别：大客户销售代表
**********
岗位职责：
1、负责跟进客户、提案、拟订修改合同、催收项目款项、项目的事务衔接，
2、负责项目的整体服务及协调工作，及时准确的与客户沟通并完成客户需求。
3、有效衔接并协调公司内部各部门在项目实施过程中的密切配合；
4、独立收集、整理客户以及行业相关信息和数据资料。
 任职资格：
1、性格开朗、有强烈的进取心，头脑清晰、反应机敏，具备良好的组织、沟通协调能力；
2、有强烈的时间观念和服务意识，适应和学习能力强，乐于接受新鲜事务；
3、有广告/房地产AE工作经验者优先录考虑。
 福利待遇：底薪+奖金+社保+年终奖
双休，享受国家法定节假日

工作地址：
天津市河西区小白楼凯德国贸
**********
天津古天文化传播有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
互联网/电子商务
公司地址：
天津市经济技术开发区六大街徽山路23号
查看公司地图
**********
电气工程师助理(可实习)双休五险一金包住宿
天津望京玻璃制品贸易有限公司
五险一金包住餐补带薪年假定期体检节日福利不加班
**********
福利:
五险一金
包住
餐补
带薪年假
定期体检
节日福利
不加班
**********
职位月薪：4001-6000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：1年以下
最低学历：大专
招聘人数：2人
职位类别：电气工程师
**********
岗位职责：
1、熟悉电气基本内容，能够绘制基本电气图；
2、协助电气工程设计师进行电气施工图纸绘制、电气产品选用等；解决电气技术问题；
3、协助电气工程师配合现场工作；
4、在电气工程师指导下完成电气施工图设计。
任职要求：
1、能够尽快入职(或者一个月左右能够到岗工作)
2、能长期稳定工作（不招兼职）。
3、年龄18-30岁之间，经验不限，专业不限
待遇
1、底薪+奖金=3000-6000（根据个人能力提升）
2、五险一金，带薪年假，双休，节日福利，有餐补等；
3、可提供住宿或者就近安排工作地点
4、试用期1-3个月，转正后享有平均月薪不低于3000元/月收入
工作时间：
1、国家法定作息时间
2、周末双休，上9:00下6:00，中午一小时午休时间。
公司招揽综合素质能力贤才，组织完善培训计划，工作经验不足者有老员工培养，并且公司提供全方位的办公环境和设施设备。
待遇优厚，试用期三个月，试用期间上五险一金，周末双休，有餐补，办公环境优越，节日福利，法定节假日~！有良好的发展及晋升空间。
应聘者可投递简历，人事部将在3个工作日内安排面试时间,或在右下角在线预约面试时间，并留下你的姓名+学历+年龄+电话，谢谢合作。

工作地址：
天津市南开区白堤路地铁六号线一中心医院站附近
**********
天津望京玻璃制品贸易有限公司
公司规模：
500-999人
公司性质：
上市公司
公司行业：
贸易/进出口
公司地址：
天津市
**********
兼职(3分钟98元)普工营销采购护士司机教师
南京重道信息技术有限公司
五险一金年底双薪绩效奖金年终分红加班补助全勤奖弹性工作节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
年终分红
加班补助
全勤奖
弹性工作
节日福利
**********
职位月薪：15001-20000元/月 
工作地点：天津
发布日期：最新
工作性质：兼职
工作经验：不限
最低学历：不限
招聘人数：28人
职位类别：兼职
**********
【全国招聘】 兼或全职时间自由：可以在家，在外，在公司，在任何地方，用手机或者电脑操作，简单方便。时间灵活，工作自由。
【公司承诺】免费兼或全职：非职介,不收押金,不收取任何费用。

急招兼或全职：一个任务酬劳为15元-1000元不等，操作达到要求并且完成任务可立即发放工资。
工资一个任务一结算,不拖欠且安全无忧！但是工资的变动取决于您投入时间长短决定，您的收获和付出成正比。
想工作，请联系企业客服张珊QQ：512512318

我们不希望错过任何人才，希望您不要错过任何工作机会。

任职要求：
①自己有上网条件，对网络操作熟练；
②学历不限，在职或学生或者待业人员皆可；
③对网店和网购有一定的兴趣；
④有一定淘宝购物经验者优先

岗位职责：
①工作细心、勤奋、认真负责；
②吃苦耐劳，诚实守信；
③性格开朗，擅长沟通与人际交往，表达清晰流利。


我们不会收您钱，但我们会教您如何在网上挣钱。
本公司的招聘信息已经过工商等相关部门审核认证，请放心兼或全职。
 
工作地址：
想工作，请联系企业客服张珊QQ：512512318
**********
南京重道信息技术有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
IT服务(系统/数据/维护)
公司地址：
【智联招聘认证】:手机可以做时间自由安排,不收任何费用及押金.应聘的加企业客服QQ：512512318
**********
机电工程师助理+五险一金
天津望京玻璃制品贸易有限公司
五险一金包住餐补带薪年假定期体检节日福利不加班
**********
福利:
五险一金
包住
餐补
带薪年假
定期体检
节日福利
不加班
**********
职位月薪：4001-6000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：2人
职位类别：机电工程师
**********
岗位职责：
1、负责从设备调试开始到设备的大故障维修的履历管理，内容包括设备基本情况、维修书、改善报告书等相关文件组织填写、归档存位，定期整理工作。 
2、对图纸、说明书、产品样本进行分类管理，测绘备件、修改图纸并确认与会签。 
3、指导、协调生产部操作员工对设备进行日常操作、保养、维修活动，以取得机器设备的优化利用。 
任职要求：
1、招聘长期稳定工作（不招兼职）。
2、年龄要求在18-30岁之间 ，有无经验均可。
3、美国上市集团总公司———注重个人综合素质及能力，目前正在招收应届生及实习生。
待遇： 
1、底薪+奖金=3000-6000，有无经验均可； 
2、五险一金，带薪年假，节日福利，可提供住宿，有餐补等； 
3、试用期1-3个月（试用期上五险，转正后缴纳一金），转正后享有平均月薪不低于4000元/月收入。 
工作时间： 
1、国家法定作息时间 
2、周末双休，上9:00下6:00，中午一小时午休时间。
备注：
公司招揽综合素质能力贤才，组织完善培训计划，工作经验不足者有老员工培养，并且公司提供全方位的办公环境和设施设备。

工作地址：
天津市南开区白堤路地铁六号线一中心医院站附近
**********
天津望京玻璃制品贸易有限公司
公司规模：
500-999人
公司性质：
上市公司
公司行业：
贸易/进出口
公司地址：
天津市
**********
电话业务内勤
天津鸿源信息技术有限公司
五险一金年底双薪绩效奖金加班补助餐补带薪年假节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
加班补助
餐补
带薪年假
节日福利
**********
职位月薪：2001-4000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：内勤人员
**********
岗位职责：
1、负责搜集企业名录的相关信息；
2、根据公司提供的企业顾客名录进行电访及回访，提高世界品牌网的知名度和受众率；
3、维护老客户的业务，挖掘客户的潜力；
4、客户追访、回访，维护客户关系，活动邀约及跟进，为客户提供专业的咨询，收集潜在客户资料，管理客户关系；
5、完成量化的工作要求，并能独立处理上级安排的其他的工作。
任职要求：
1、对销售内勤工作有较高的热情；有工作经验优先；
2、普通话标准，具有良好的沟通表达能力，语音富有感染力。
3、为人踏实，品德良好，综合素质休养佳，能吃苦耐劳，责任心强。
4、有自信心、乐观向上，工作态度积极认真，具有团队合作精神。
5、乐于接受挑战性的工作，有较高的敬业精神，喜欢电话销售工作。

任职要求：男女不限，大专或本科学历，年龄20-35岁，性格开朗，健谈，应变能力强
工作地址：
天津市河东区新开路与华兴道交口南侧创智大厦1-811
**********
天津鸿源信息技术有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
互联网/电子商务
公司主页：
//www.worldpp.cn
公司地址：
天津市河东区新开路与华兴道交口南侧创智大厦1-811
查看公司地图
**********
文员（设计部）+五险一金双休
天津望京玻璃制品贸易有限公司
五险一金包住餐补带薪年假定期体检节日福利不加班
**********
福利:
五险一金
包住
餐补
带薪年假
定期体检
节日福利
不加班
**********
职位月薪：4001-6000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：中专
招聘人数：1人
职位类别：助理/秘书/文员
**********
岗位描述：
1、负责部门电脑文档的编号、打印、排版和归档；
2、报表的收编以及整理，以便更好的贯彻和落实工作；
3、协助项目经理从事相关文案类工作（含计算机 ps）；
4、协助项目经理进行创意提案，保证工作的顺利推进。
应聘条件：
1.具备良好的沟通和学习能力，逻辑思维能力较强，专业不限；
2.有无相关基础均可，对设计感兴趣，学习能力强，工作热情高，负有责任感；
3.欢迎应届毕业生前来应聘，带薪岗前实习。
薪资构成：基本工资3000起+奖金+岗位津贴+丰厚年终奖
社会保险：入职即上五险一金
休息时间：5天8小时工作制、朝九晚六，周末双休，法定节假日休息，带薪年假，带薪病假，带薪产假，带薪婚丧假
节日贺礼：传统佳节派发节日礼品以增添节日气氛。
生日派对：过生日的员工，有公司生日派对以表祝福
生活关怀：定期体检，公司设有员工休息室，提供微波炉、饮水机等便捷设备。办公环境：办公环境优美，可提供住宿或者就近安排工作地点。
应聘者可投递简历，人事部将在3个工作日内安排面试时间

工作地址：
天津市南开区西南角地铁2号线
查看职位地图
**********
天津望京玻璃制品贸易有限公司
公司规模：
500-999人
公司性质：
上市公司
公司行业：
贸易/进出口
公司地址：
天津市
**********
资深平面设计
天津市北岛广告发展有限公司
**********
福利:
**********
职位月薪：4001-6000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：1人
职位类别：广告创意/设计师
**********
1.有2-3年以上的广告平面设计从业经验
2.熟练使用各种设计软件，能独立完成平面创意，完成设计任务
3.工作热情勤恳，有持久的责任心和团队精神
4.善于学习，思维活跃，视野开阔，对新鲜事有浓厚兴趣
工作地址：
天津市南开区水上公园东路翠泽园9号楼1门
查看职位地图
**********
天津市北岛广告发展有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市南开区水上公园东路翠泽园9号楼1门
**********
平面设计
天津市北岛广告发展有限公司
**********
福利:
**********
职位月薪：4001-6000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：5人
职位类别：平面设计
**********
职位要求：
1.有1年以上的广告平面设计从业经验
2.熟练使用各种设计软件，能独立完成平面创意，完成设计任务
3.工作热情勤恳，有持久的责任心和团队精神
4.善于学习，思维活跃，视野开阔，对新鲜事有浓厚兴趣

工作地址：
天津市南开区水上东路 翠泽园9-1
**********
天津市北岛广告发展有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市南开区水上公园东路翠泽园9号楼1门
查看公司地图
**********
node.js小程序程序员
天津鸿源信息技术有限公司
无试用期绩效奖金弹性工作五险一金
**********
福利:
无试用期
绩效奖金
弹性工作
五险一金
**********
职位月薪：6001-8000元/月 
工作地点：天津-河东区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：软件工程师
**********
岗位职责：
小程序程序编写
任职要求：
本科以上学历，有一年工作经历
工作地址：
天津市河东区新开路与华兴道交口南侧创智大厦1-811
**********
天津鸿源信息技术有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
互联网/电子商务
公司主页：
//www.worldpp.cn
公司地址：
天津市河东区新开路与华兴道交口南侧创智大厦1-811
查看公司地图
**********
平面设计
天津百思道商务咨询有限公司
五险一金全勤奖节日福利
**********
福利:
五险一金
全勤奖
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：平面设计
**********
岗位职责：
1.负责品牌的设计、平面应用设计工作。
2.负责商品的包装、宣传品设计工作，负责品牌的LOGO及VI设计工作。
3.负责品牌宣传及营销推广活动中的宣传品（广告，图片，海报等）的设计制作工作。
4、宣传手册、单页设计、企业文化宣传、内/外部刊物设计、广告板、海报设计、公司微信公众号设计等等。
任职要求：
1、平面设计、艺术设计类相关专业或一年以上相关工作经验者优先考虑；
2、掌握或精通PHOTOSHOP、Illustrator 、Indesign，Acrobat 等平面设计软件，熟悉Powerpoint软件；
3、具有较强的审美能力，优秀的平面构图、排版、色彩及设计能力，善于快速学习、领悟；
4、随和、谦虚、认真、细致、负责、主观能动性强、工作效率高，具有良好的沟通能力和团队合作精神；

工作地址：
天津市和平区吉林路38号轻纺大厦409室
查看职位地图
**********
天津百思道商务咨询有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
专业服务/咨询(财会/法律/人力资源等)
公司地址：
天津市和平区吉林路38号轻纺大厦409室
**********
出纳/财务 底薪4500+五险一金
天津益康天下电子商务有限公司
五险一金年底双薪全勤奖餐补房补带薪年假员工旅游节日福利
**********
福利:
五险一金
年底双薪
全勤奖
餐补
房补
带薪年假
员工旅游
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：无经验
最低学历：不限
招聘人数：1人
职位类别：出纳员
**********
岗位职责：
1、及时进行国、地税纳税申报；
2、能够准确进行成本核算；
3、协调处理与税务、工商等机关的关系；
4、年度预算盘点。

任职要求：
1、熟悉会计法规和税法，应届生优先；
2、工作细致、责任感强，为人正直诚信；
3、具有较强的表达和沟通能力,保密意识强。

薪资福利：
1、当月薪资构成：基本工资4000+岗位津贴800+餐补900+打车报销80%+周末双休+五险一金+交通补助；
2、员工生日会，团队建设聚餐，员工入职欢迎会；
3、享受标准社会五险及住房公积金。

上班时间：朝九晚六 周末双休 法定节假日公休
  工作地址：
天津市河东区双赢大厦（天津站后广场）
**********
天津益康天下电子商务有限公司
公司规模：
20人以下
公司性质：
其它
公司行业：
互联网/电子商务
公司地址：
天津市河东区双赢大厦（天津站后广场）
**********
财务经理
天津市镜界广告有限公司
五险一金绩效奖金全勤奖带薪年假员工旅游节日福利
**********
福利:
五险一金
绩效奖金
全勤奖
带薪年假
员工旅游
节日福利
**********
职位月薪：8001-10000元/月 
工作地点：天津-河西区
发布日期：最新
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：1人
职位类别：财务经理
**********
岗位职责：
1、建立、健全财务管理体系制度，资金运作等进行总体规划。
2、审核公司财务报表、核对关联往来，合并报表并进行财务分析；有效的监督检查财务制度，预算和执行情况以及及时适当的进行调整，对公司重大投资等经营活动提供建议和决策支持。
3、日常核算、会计凭证、出纳、税务工作的审核；
4、依据费用管理规定，合理控制费用支出；
5、定期组织检查会计政策执行情况，严控操作风险，解决存在问题；
6、领导交办其他事宜。

任职要求：
1、年龄35岁以上；
2、会计、财务、审计或相关专业本科及以上学历；
3、5年以上相关岗位工作经验，中级会计师职称优先；
4、精通国家财税法律规范、财务核算、财务管理、财务分析、财务预测等财务制度和业务；
5、熟悉国家会计法规，了解税务法规和相关税收政策。
工作地址：
天津市河西区洞庭路香年广场A座402
查看职位地图
**********
天津市镜界广告有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市河西区洞庭路香年广场A座402
**********
广告AE
天津市镜界广告有限公司
五险一金年底双薪绩效奖金全勤奖节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
全勤奖
节日福利
**********
职位月薪：3000-6000元/月 
工作地点：天津-河西区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：广告客户代表
**********
岗位职责：
做好客户后续衔接与公司相关执行工作；有效传达客户需求，确保工作顺利进行；完成其他上级主管交付的工作。
任职要求：
1年以上广告公司经验，了解地产广告行业，有地产广告服务经验的优先；具有良好的沟通能力、理解能力及谈判能力强；开朗、热情、有责任心、具有团队合作精神，能接受工作中的压力。

工作地址：
天津市河西区洞庭路香年广场A座402
查看职位地图
**********
天津市镜界广告有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市河西区洞庭路香年广场A座402
**********
互联网运营销售
天津鸿源信息技术有限公司
五险一金包吃交通补助通讯补贴带薪年假
**********
福利:
五险一金
包吃
交通补助
通讯补贴
带薪年假
**********
职位月薪：4001-6000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：3人
职位类别：客户主管
**********
岗位职责：
1、品牌网站线上运营活动策划宣传及执行；
2、与大中小企业联系网站品牌会员入驻，小程序业务的开发等。

任职要求：男女不限，有强烈的工作热情，身体健康，语言表达能力强，有较好的人际应变能力，有互联网或电子商务营销业务工作经验者优先考虑，你的能力汇报=高底薪+高提成+双休+五险，本公司欢迎你的加入
工作地址：
天津市河东区新开路与华兴道交口南侧创智大厦1-811
**********
天津鸿源信息技术有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
互联网/电子商务
公司主页：
//www.worldpp.cn
公司地址：
天津市河东区新开路与华兴道交口南侧创智大厦1-811
查看公司地图
**********
会务专员
天津百思道商务咨询有限公司
五险一金全勤奖带薪年假节日福利
**********
福利:
五险一金
全勤奖
带薪年假
节日福利
**********
职位月薪：2001-4000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：会务专员/助理
**********
岗位职责：
1、根据公司会议需要，联系选择会务酒店，了解掌握会务信息，制订服务方案。
2、懂得运用合理统筹，确定会议主题，拟定会议策划案和具体操作方案，执行与协调现场活动的相关工作。
3、制定会议预算，包括交通费用、住宿、会议室厅费用、餐饮等费用。
4、邀请适合的客户参加，与客户沟通联络，调配会务专用车辆，派车接机。
5、完成项目活动的收尾工作，费用结算清单。
任职要求
1、1-3年以上会务专员工作经验，能够维持现场活动秩序，进行有效的流程把控。
2、需要具备大型活动及品牌策划和规划经验。
3、能够独立完成的策划方案，策划、组织并实施过大型市场活动。
4、熟悉会议、市场活动策划流程和实施过程。
5、沟通应变能力强的应届毕业生亦可。
 
工作地址：
天津市和平区吉林路38号轻纺大厦410室
查看职位地图
**********
天津百思道商务咨询有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
专业服务/咨询(财会/法律/人力资源等)
公司地址：
天津市和平区吉林路38号轻纺大厦409室
**********
兼职(3分钟98元)财务出纳审计税务会计文秘
南京天鹰图新测控技术有限公司
五险一金年底双薪绩效奖金年终分红加班补助全勤奖弹性工作节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
年终分红
加班补助
全勤奖
弹性工作
节日福利
**********
职位月薪：15001-20000元/月 
工作地点：天津
发布日期：最新
工作性质：兼职
工作经验：不限
最低学历：不限
招聘人数：28人
职位类别：兼职
**********
【全国招聘】 兼或全职时间自由：可以在家，在外，在公司，在任何地方，用手机或者电脑操作，简单方便。时间灵活，工作自由。
【公司承诺】免费兼或全职：非职介,不收押金,不收取任何费用。

急招兼或全职：一个任务酬劳为15元-1000元不等，操作达到要求并且完成任务可立即发放工资。
工资一个任务一结算,不拖欠且安全无忧！但是工资的变动取决于您投入时间长短决定，您的收获和付出成正比。
想工作，请联系企业客服张珊QQ：512512318

我们不希望错过任何人才，希望您不要错过任何工作机会。

任职要求：
①自己有上网条件，对网络操作熟练；
②学历不限，在职或学生或者待业人员皆可；
③对网店和网购有一定的兴趣；
④有一定淘宝购物经验者优先

岗位职责：
①工作细心、勤奋、认真负责；
②吃苦耐劳，诚实守信；
③性格开朗，擅长沟通与人际交往，表达清晰流利。


我们不会收您钱，但我们会教您如何在网上挣钱。
本公司的招聘信息已经过工商等相关部门审核认证，请放心兼或全职。
 
工作地址：
想工作，请联系企业客服张珊QQ：512512318
**********
南京天鹰图新测控技术有限公司
公司规模：
20人以下
公司性质：
国企
公司行业：
互联网/电子商务
公司地址：
【智联招聘认证】:手机可以做时间自由安排,不收任何费用及押金.应聘的加企业客服QQ：512512318
**********
财务主管
博科乐骏(天津)企业管理咨询有限公司
五险一金绩效奖金采暖补贴带薪年假定期体检员工旅游高温补贴节日福利
**********
福利:
五险一金
绩效奖金
采暖补贴
带薪年假
定期体检
员工旅游
高温补贴
节日福利
**********
职位月薪：4000-8000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：1人
职位类别：财务主管/总帐主管
**********
岗位职责：
1. 制定并建立财务管控体系、流程，制订公司内部财务、会计制度和工作程序，组织实施并监督执行，提高运营效率；
2. 依据公司发展目标,编制年度、月度财务预算和执行预算，参与拟订资金筹措和使用方案，确保资金的有效使用；
3. 审阅财务专题报告和会计报表，对重大的财务收支计划、经济合同进行会签；
4. 审查公司对外提供的会计资料，随时检查公司财务系统账目的准确性和及时性；
5. 检查财务报表的准确性，并根据《财务报表》制作财务分析；
6. 负责对费用、往来、资金、资产的帐务处理和监控管理，定期参与对本部资产进行清理，使之帐实相符，按印鉴管理规定保管、使用财务印鉴；
7. 精通工商、税务的办事流程，衔接处理公司内关于工商、税务等事宜；
8. 完成公司交办的其他工作。 
任职要求：
1.年龄30-45周岁，财务、审计、金融等相关专业大学本科以上学历；
2.具备5年以上财务管理经验，具有会计资格证；
3.熟悉财务各模块的核算流程，具备优秀的职业判断能力和较强的实际操作能力，熟悉国家财税法律规范及当地相关法律法规；
4.具有较强的成本、服务意识和高度的责任心，强烈的事业心；
5.具有良好的管理能力、沟通能力和人际交往能力、组织协调和承压能力，为人正直。
福利待遇：
1.较市场具有竞争力薪酬待遇；
2.签订正式劳动合同，正式员工编制，五险齐全；
3.享受国家法定节假日，带薪年假、长期服务津贴等丰厚的员工福利；
4.提供良好的晋升通道和完善的培训提升系统，有机会参加公司旅游；
5.团队文化：优秀吸引优秀，在这里你可以与更多优秀的人共同成长。
  工作地址：
天津市南开区宜宾道鼎泰丰产业园
**********
博科乐骏(天津)企业管理咨询有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
专业服务/咨询(财会/法律/人力资源等)
公司地址：
天津市南开区宜宾道鼎泰丰产业园
**********
会务执行主管
天津百思道商务咨询有限公司
五险一金带薪年假绩效奖金节日福利
**********
福利:
五险一金
带薪年假
绩效奖金
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：会务经理/主管
**********
岗位职责：
1、 深度挖掘重点客户的潜在需求，为客户提供满意的会务解决方案；根据特定客户需求制定解决方案与建议；
2、制定会议实施进度表；定时组织人员召开会务工作协调会，根据每阶段工作进行横向、纵向沟通；
3、会议现场总协调；会议资料汇总归档；跟进文宣资料制作；
4、负责会后市场效果的跟踪、反馈、总结并撰写总结报告；
5、会议现场负责重点客户的沟通、方案讲解、合同的签订；
6、负责会务部人员的管理工作，监督员工的工作进程与进度

任职要求：
1、有2年以上会议开发、活动、组织、运作经验，具有一年以上的相关岗位的管理工作；
2、有强烈的进取心，能吃苦，富有开拓精神；
3、熟悉计算机和互联网络，有较强服务意识；
4、具有敬业精神，有强烈的竞争意识，能积极面对工作挑战。

工作地址：
天津市和平区吉林路38号轻纺大厦409室
查看职位地图
**********
天津百思道商务咨询有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
专业服务/咨询(财会/法律/人力资源等)
公司地址：
天津市和平区吉林路38号轻纺大厦409室
**********
策划经理
天津市镜界广告有限公司
五险一金绩效奖金全勤奖带薪年假员工旅游节日福利
**********
福利:
五险一金
绩效奖金
全勤奖
带薪年假
员工旅游
节日福利
**********
职位月薪：5000-8000元/月 
工作地点：天津-河西区
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：1人
职位类别：店面/展览/展示/陈列设计
**********
岗位职责：
1、三年以上策略专业相关经历，一年以上经理职位经验；
2、广告房地产相关行业3年以上服务经验；
3、精于市场分析，视野开阔，策略思考严谨缜密；
4、富有创新意识，擅长策略性思考；
5、具备出色的沟通能力、流程控制能力、良好的提案能力、技巧和执行力。

任职要求：
1、对公司创作策略方案进行负责，管理文案创作，指导企划创作小组的日常工作；
2、主要任务是指导和完成策略创意，即给每个项目制定详细的推广策略和文案创意；
3、和设计部门一起领导文案和美术指导一起，根据客户部给予的创意简报对所负责项目的广告给予策略方向并指导创作小组进行创作；
4、协助客户部对创作流程进行推动，控制创意过程中的创意方向策略执行；

工作地址：
天津市河西区洞庭路香年广场A座402
查看职位地图
**********
天津市镜界广告有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市河西区洞庭路香年广场A座402
**********
3D设计
天津市美业广告有限公司
绩效奖金加班补助包吃
**********
福利:
绩效奖金
加班补助
包吃
**********
职位月薪：5000-10000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：不限
招聘人数：4人
职位类别：三维/3D设计/制作
**********
岗位职责：
 1. 负责公司与公关活动相关的展览展示设计、舞台美术设计、会务设计、活动设计（如发布会、年会等）的3D视觉表现。
2. 
与特装工厂沟通并制作施工图纸，跟进项目执行，根据施工状况及时调整设计，控制成本选择合适的材料。
3. 
熟练使用3DMAX、AUTOCAD、PHOTOSHOP、LLLUSTRATOR、VRAY等行业软件；
4. 
具备良好的沟通交流能力，工作主动、积极，责任心强，具有团队合作精神，能在压力下高效工作；能适应紧张工作节奏及加班，工作认真、踏实肯干。
 条件优秀者可相应放宽。不符合条件者勿扰

工作地址：
天津市河东区六纬路与九经路交口祥云名苑
**********
天津市美业广告有限公司
公司规模：
20-99人
公司性质：
股份制企业
公司行业：
广告/会展/公关
公司主页：
null
公司地址：
河东十一经路万隆太平洋大厦
查看公司地图
**********
会展专员
天津光度文化活动策划有限公司
五险一金绩效奖金弹性工作节日福利
**********
福利:
五险一金
绩效奖金
弹性工作
节日福利
**********
职位月薪：2001-4000元/月 
工作地点：天津
发布日期：最新
工作性质：校园
工作经验：无经验
最低学历：本科
招聘人数：1人
职位类别：广告/会展业务拓展
**********
1组织筛选有关行业的会展资料，收集、分析和整理展会信息；
2.收集、整理客户信息，并开发、维护客户；
3.联系、组织、安排展会（如报名、定制展位、宣传）等工作；
4.协助策划会务、活动、展览等，编制项目计划书并执行项目
要求：良好的沟通能力和语言表达能力 亲和力强

工作地址：
天津市西青华鼎智地
**********
天津光度文化活动策划有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市南开区红旗南路观景里3-2-703
查看公司地图
**********
美术编辑
天津凤凰空间文化传媒有限公司
五险一金包吃节日福利员工旅游定期体检交通补助通讯补贴餐补
**********
福利:
五险一金
包吃
节日福利
员工旅游
定期体检
交通补助
通讯补贴
餐补
**********
职位月薪：4001-6000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：2人
职位类别：美术编辑/美术设计
**********
职位描述：
1.图书封面和内页设计；
2.图书制版排版；
3.对外排稿件的整理及改排工作；
4.展会、广告、名片等设计；

岗位要求：
1.本科、研究生在校大学生优先；
2.熟练使用indesign或illustrator等排版设计软件；
3.良好的美术功底和鉴赏能力，具备出色的视觉创造能力；
4.沟通能力强，抗压能力强
5.热爱图书出版行业，有相关经验者优先录用
6.从事过图书出版行业，兼职也可以

工作地址：
南开区大学道199号天铁科贸大厦
查看职位地图
**********
天津凤凰空间文化传媒有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
媒体/出版/影视/文化传播
公司地址：
天津市南开区大学道199号天铁科贸大厦5F
**********
空乘形体教师
南昌美航信息技术有限公司
创业公司无试用期绩效奖金交通补助弹性工作
**********
福利:
创业公司
无试用期
绩效奖金
交通补助
弹性工作
**********
职位月薪：6001-8000元/月 
工作地点：天津
发布日期：最新
工作性质：兼职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：培训/招生/课程顾问
**********
岗位职责：空乘形体培训

任职要求：因公司在当地开设培训基地（形体），能联系培训场地和教授形体训练，有空乘经验的优先。
工作地址：
南昌高新开发区高新创业大厦
**********
南昌美航信息技术有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
中介服务
公司地址：
南昌高新开发区高新创业大厦
查看公司地图
**********
总经理助理
天津百思道商务咨询有限公司
五险一金全勤奖带薪年假节日福利
**********
福利:
五险一金
全勤奖
带薪年假
节日福利
**********
职位月薪：2001-4000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：总裁助理/总经理助理
**********
岗位职责：  
1、负责起草会议纪要及会议决定事项的传达、催办落实与信息反馈。  
2、负责协调总经理出席会议、重要活动的安排。 
3、协助总经理做好日常接待、来信、来访等有关事宜。 
4、负责为总经理管理好日常用的各种文件和资料。
5、完成总经理交办的其它工作。
任职要求：
1、男女不限，大专及以上学历，熟练应用Office等办公软件。
2、具备良好的职业道德和人品，有强烈的事业心和责任感，性格外向开朗。
3、具有良好的沟通协调能力、计划和执行能力，思维清晰、有条理。
4、有驾照,连续驾龄2年以上,可以适应短时间出差。
 
工作地址：
天津市和平区吉林路38号轻纺大厦410室
查看职位地图
**********
天津百思道商务咨询有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
专业服务/咨询(财会/法律/人力资源等)
公司地址：
天津市和平区吉林路38号轻纺大厦409室
**********
业务经理
创想未来(天津)工程设计股份有限公司
绩效奖金年终分红股票期权员工旅游
**********
福利:
绩效奖金
年终分红
股票期权
员工旅游
**********
职位月薪：10001-15000元/月 
工作地点：天津-南开区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：6人
职位类别：销售代表
**********
任职资格：
1.本科及以上学历，有至少1年以上相关行业销售工作经验（优秀人才可适当放宽）；
2.具备建筑装饰类、广告会展行业经验者优先；
3.有大客户销售经验或有相关行业资源者优先；
4.具备高度的工作热情、良好的沟通协调能力、市场开拓能力和较强的学习能力。

岗位职责：
1、负责与展馆、展厅等相关创意及后期制作有关的解决方案销售；
2、收集和甄别市场有效信息，开发潜在目标客户；
3、跟进和拜访目标客户，深度挖掘客户需求清单；
4、完成公司下达的销售指标、客户指标等目标任务；
5、负责商务谈判、投标、合同签订、回收账款等商务执行工作；
6、与公司其他部门（策划部、设计部、工程部）工作中内部协调。
公司经过二十多年的发展积淀，伴随着在OTC市场顺利挂牌的东风，公司法人治理结构逐步完善，公司管理流程逐步细化明确，近两年公司经营业绩取得翻一番的巨大进步。目前公司立足天津、面向全国，急需区域销售经理及产品销售经理。
公司作为行业内优势且极具潜力的平台，提供良好的施展舞台以及完善且极具同行业竞争力的绩效、薪酬、福利管理体系！


工作地址：
天津市南开区奥城商业广场C7北座613
查看职位地图
**********
创想未来(天津)工程设计股份有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
广告/会展/公关
公司主页：
www.newideafuture.cn
公司地址：
天津市南开区奥城商业广场C7北座613
**********
兼职(3分钟98元)文员行政人力人事后勤贸易
南京重道信息技术有限公司
五险一金年底双薪绩效奖金年终分红加班补助全勤奖弹性工作节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
年终分红
加班补助
全勤奖
弹性工作
节日福利
**********
职位月薪：15001-20000元/月 
工作地点：天津
发布日期：最新
工作性质：兼职
工作经验：不限
最低学历：不限
招聘人数：28人
职位类别：兼职
**********
【全国招聘】 兼或全职时间自由：可以在家，在外，在公司，在任何地方，用手机或者电脑操作，简单方便。时间灵活，工作自由。
【公司承诺】免费兼或全职：非职介,不收押金,不收取任何费用。

急招兼或全职：一个任务酬劳为15元-1000元不等，操作达到要求并且完成任务可立即发放工资。
工资一个任务一结算,不拖欠且安全无忧！但是工资的变动取决于您投入时间长短决定，您的收获和付出成正比。
想工作，请联系企业客服张珊QQ：512512318

我们不希望错过任何人才，希望您不要错过任何工作机会。

任职要求：
①自己有上网条件，对网络操作熟练；
②学历不限，在职或学生或者待业人员皆可；
③对网店和网购有一定的兴趣；
④有一定淘宝购物经验者优先

岗位职责：
①工作细心、勤奋、认真负责；
②吃苦耐劳，诚实守信；
③性格开朗，擅长沟通与人际交往，表达清晰流利。


我们不会收您钱，但我们会教您如何在网上挣钱。
本公司的招聘信息已经过工商等相关部门审核认证，请放心兼或全职。
 
工作地址：
想工作，请联系企业客服张珊QQ：512512318
**********
南京重道信息技术有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
IT服务(系统/数据/维护)
公司地址：
【智联招聘认证】:手机可以做时间自由安排,不收任何费用及押金.应聘的加企业客服QQ：512512318
**********
活动策划
天津光度文化活动策划有限公司
五险一金绩效奖金弹性工作节日福利带薪年假
**********
福利:
五险一金
绩效奖金
弹性工作
节日福利
带薪年假
**********
职位月薪：2001-4000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：活动策划
**********
岗位要求
1、专科以上学历；
2、有相关工作经验者优先； 
3、熟悉活动运营和各类型活动策划技巧 有较强的语言和文字表达能力； 
4、有较强的观察力和应变能力，优秀的人际交往和协调能力，较强的执行力；
5、熟练的操作办公软件； 
6、高度的工作热情，良好的团队合作精。
工作内容
1、根据项目实际情况制定相应的活动计划及方案； 
2、负责市场活动文案的策划，创意，撰写； 
3、负责各类活动的组织，执行，跟踪，总结； 
4、制定各类活动的策划计划及活动策略。

工作地址：
天津市西青区华鼎智地
查看职位地图
**********
天津光度文化活动策划有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市南开区红旗南路观景里3-2-703
**********
软件工程师
天津鸿源信息技术有限公司
五险一金绩效奖金餐补年终分红
**********
福利:
五险一金
绩效奖金
餐补
年终分红
**********
职位月薪：6001-8000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：1年以下
最低学历：本科
招聘人数：2人
职位类别：软件工程师
**********
软件编辑：APP,微信小程序
本科以上学历
有互联网项目经历
工作地址：
天津市河东区新开路与华兴道交口南侧创智大厦1-811
查看职位地图
**********
天津鸿源信息技术有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
互联网/电子商务
公司主页：
//www.worldpp.cn
公司地址：
天津市河东区新开路与华兴道交口南侧创智大厦1-811
**********
网站客服
天津鸿源信息技术有限公司
无试用期绩效奖金弹性工作
**********
福利:
无试用期
绩效奖金
弹性工作
**********
职位月薪：1000-2000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：不限
招聘人数：100人
职位类别：网店客服
**********
岗位职责： 
1、负责世界品牌网的本地站点设计维护。
2、开发本地品牌客户； 
3、为客户提供完整准确的方案及信息，解决客户问题，提供高质量服务; 
4、良好的工作执行力，严格按规范及流程进行工作或相关操作; 
岗位要求： 
1、具有良好的服务意识、工作责任心和沟通协调能力；热爱客服工作； 
2、普通话标准，口齿清楚，良好的语言表达能力； 
3、大专以上学历，专业不限。 
4、熟练操作计算机，熟练使用office等办公软件； 
5、性别不限。

工作地址：
河东区卫国道189号帅越科技园415室
**********
天津鸿源信息技术有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
互联网/电子商务
公司主页：
//www.worldpp.cn
公司地址：
天津市河东区新开路与华兴道交口南侧创智大厦1-811
查看公司地图
**********
招聘主管
博科乐骏(天津)企业管理咨询有限公司
五险一金绩效奖金采暖补贴带薪年假定期体检员工旅游高温补贴节日福利
**********
福利:
五险一金
绩效奖金
采暖补贴
带薪年假
定期体检
员工旅游
高温补贴
节日福利
**********
职位月薪：3000-6000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：1人
职位类别：招聘经理/主管
**********
岗位职责：
1. 根据公司业务发展需要及人员需求，协调、统计各项目的招聘需求，编制年度人员招聘计划；目前项目为招募大都会人寿销售经理；
2. 充分了解和掌握各岗位人员编制情况；
3. 建立和完善公司的招聘流程和招聘体系；
4. 利用各类招聘渠道发布招聘广告，开拓招聘渠道；
5. 对初试、复试考官进行面试培训；
6. 执行招聘、甄选、面试、推选、安置工作；
7. 进行聘前测试和简历甄选工作；
8. 负责电话邀约人员的初次面试及筛选工作；
9. 负责对电话招聘专员的管理与考核工作；
10.定期进行人力资源内外部数据分析，适时提出工作合理化改进建议；
11.完成部门交办的其他工作。
任职要求：
1.年龄25-45周岁，性别不限，具备3年以上企业招聘工作经验；
2.人力资源、管理或相关专业大学本科以上学历；
3.对人力资源管理事务性工作有娴熟的处理技巧；
4.熟悉企业的招聘流程及各种招聘渠道；
5.熟悉计算机操作办公软件及相关的人事管理软件；
6.人际关系良好，具备很强的责任感和事业心，良好的职业道德和职业操守；
7.较高的敏感度及一定的判断能力，擅于沟通与协调，具有良好的团队合作意识。
福利待遇：
1.较市场具有竞争力薪酬待遇；
2.签订正式劳动合同，正式员工编制，五险齐全；
3.享受国家法定节假日，带薪年假、长期服务津贴等丰厚的员工福利；
4.提供良好的晋升通道和完善的培训提升系统，有机会参加公司旅游；
5.团队文化：优秀吸引优秀，在这里你可以与更多优秀的人共同成长。
工作地址：
天津市南开区宜宾道鼎泰丰产业园
**********
博科乐骏(天津)企业管理咨询有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
专业服务/咨询(财会/法律/人力资源等)
公司地址：
天津市南开区宜宾道鼎泰丰产业园
**********
销售经理（图书发行）急招
天津凤凰空间文化传媒有限公司
五险一金绩效奖金年终分红交通补助通讯补贴带薪年假定期体检节日福利
**********
福利:
五险一金
绩效奖金
年终分红
交通补助
通讯补贴
带薪年假
定期体检
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：5人
职位类别：销售经理
**********
职位描述：
1.负责片区的主渠道业务；
2.制定全年回款计划，完成回款任务；
3.定期进行客户拜访，及时了解客户需求，建立并维护良好的客户关系；
4.根据不同的门店跟地域区别，及时将我社的新书进行推荐；
5.及时跟踪客户图书到货情况；
6.做好市场调查，了解市场定位；
7.与客户对账，检查发、退货准确率保证公司利益。
 岗位要求：
1.专科及以上学历，热爱图书行业，适应短期出差，热爱图书行业，有相关工作经验者优先；
2.良好的人际沟通、协调、组织能力；
3.工作责任心强，有良好的分析、解决问题能力，思路清晰，考虑问题细致；
4.良好的团队合作精神。

 福利待遇：
工资构成=基本工资+岗位工资+职务工资+考勤工资+交通补助+话费补助
提供午餐，双休，节假日正常，定期体检，员工旅游

工作地址：
天津市南开区大学道199号天铁科贸大厦
**********
天津凤凰空间文化传媒有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
媒体/出版/影视/文化传播
公司地址：
天津市南开区大学道199号天铁科贸大厦5F
查看公司地图
**********
人力主管
博科乐骏(天津)企业管理咨询有限公司
五险一金绩效奖金采暖补贴带薪年假定期体检员工旅游高温补贴节日福利
**********
福利:
五险一金
绩效奖金
采暖补贴
带薪年假
定期体检
员工旅游
高温补贴
节日福利
**********
职位月薪：4000-8000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：1人
职位类别：人力资源主管
**********
岗位职责：
 1. 根据公司发展战略，组建管理人事部门，编制企业人力资源工作计划与预算方案；
2. 组织制定、执行、监督和完善公司人力资源管理各项规章制度；
3. 参与制定公司的组织架构、岗位编制和职责分工，并制定相应的工作要求和业绩考核标准；
4. 制定公司绩效考核制度，组织实施绩效考核，并对各部门绩效管理过程监督控制，不断完善的绩效管理体系；
5. 制定和完善薪酬、福利以及相关的激励保证制度；
6. 员工招聘、入职、转正、离职流程的完善及执行，员工档案的管理；
7. 组织进行员工职业发展规划，负责制定后备人才选拔和人才储备机制；
8. 制定并实施公司年度培训计划，组织新员工入职培训及岗位培训；
9. 与员工积极沟通，推动企业文化建设，建立积极的工作环境；
10.公司交办的其他工作。
任职要求：
1.年龄25-45周岁，人力资源、管理或相关专业大学本科以上学历；
2.具备5年以上人力资源管理经验，熟悉人力资源管理各模块的工作流程和业务知识，具备较强的实际操作能力，熟悉国家及当地相关法律法规；
3.熟悉计算机操作办公软件及相关的人事管理软件；
4.有较高的专业素养和职业精神，为人正直，办事公正，思想敏捷，性格沉稳，善于沟通和决断，心态平和、理智；
5.具有较强的成本、服务意识和高度的创业精神，强烈的事业心；
6.较高的敏感度及一定的判断能力，擅于沟通与协调，具有良好的团队合作意识。
福利待遇：
1.较市场具有竞争力薪酬待遇；
2.签订正式劳动合同，正式员工编制，五险齐全；
3.享受国家法定节假日，带薪年假、长期服务津贴等丰厚的员工福利；
4.提供良好的晋升通道和完善的培训提升系统，有机会参加公司旅游；
5.团队文化：优秀吸引优秀，在这里你可以与更多优秀的人共同成长。
  工作地址：
天津市南开区宜宾道鼎泰丰产业园
**********
博科乐骏(天津)企业管理咨询有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
专业服务/咨询(财会/法律/人力资源等)
公司地址：
天津市南开区宜宾道鼎泰丰产业园
**********
诚聘LOGO设计师
易艾斯科技发展（天津）有限公司
五险一金绩效奖金加班补助节日福利
**********
福利:
五险一金
绩效奖金
加班补助
节日福利
**********
职位月薪：8001-10000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：2人
职位类别：平面设计
**********
岗位职责：
1、主要承担VI中的LOGO 设计任务包括图形、配色和文字搭配等
2、参与VI设计中的方向性定位策划，给出建设性意见。
3、参与公司安排的其它平面设计工作


任职要求：
1、具有丰富的logo设计及平面设计经验，脑袋里有东西。
2、有创意、有策划能力，可根据不同客户需求独立完成设计方案
3、有责任心，荣誉感，肯下苦心；
4、简历发送至邮箱 iistj@iistj.com  并附本人相关LOGO设计案例。


岗位待遇：
1、薪资构成：底薪+绩效+加班补助；
2、工作时间：早8:30-晚17：30，双休；
3、福利待遇：五险一金，法定假日；
4、发展空间：设计公司，扁平化管理，发展前景广阔；
5、办公环境：年轻化团队，公司地处繁华地段，交通便利。



工作地址：
天津河东区新开路华云大厦8层
查看职位地图
**********
易艾斯科技发展（天津）有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
广告/会展/公关
公司主页：
http://www.iistj.com/
公司地址：
天津市河东区新开路华云大厦8层
**********
兼职(3分钟98元)临时工大学生实习销售代表
南京天鹰图新测控技术有限公司
五险一金年底双薪绩效奖金年终分红加班补助全勤奖弹性工作节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
年终分红
加班补助
全勤奖
弹性工作
节日福利
**********
职位月薪：15001-20000元/月 
工作地点：天津
发布日期：最新
工作性质：兼职
工作经验：不限
最低学历：不限
招聘人数：68人
职位类别：兼职
**********
【全国招聘】 兼或全职时间自由：可以在家，在外，在公司，在任何地方，用手机或者电脑操作，简单方便。时间灵活，工作自由。
【公司承诺】免费兼或全职：非职介,不收押金,不收取任何费用。

急招兼或全职：一个任务酬劳为15元-1000元不等，操作达到要求并且完成任务可立即发放工资。
工资一个任务一结算,不拖欠且安全无忧！但是工资的变动取决于您投入时间长短决定，您的收获和付出成正比。
想工作，请联系企业客服张珊QQ：512512318

我们不希望错过任何人才，希望您不要错过任何工作机会。

任职要求：
①自己有上网条件，对网络操作熟练；
②学历不限，在职或学生或者待业人员皆可；
③对网店和网购有一定的兴趣；
④有一定淘宝购物经验者优先

岗位职责：
①工作细心、勤奋、认真负责；
②吃苦耐劳，诚实守信；
③性格开朗，擅长沟通与人际交往，表达清晰流利。


我们不会收您钱，但我们会教您如何在网上挣钱。
本公司的招聘信息已经过工商等相关部门审核认证，请放心兼或全职。
 
工作地址：
想工作，请联系企业客服张珊QQ：512512318
**********
南京天鹰图新测控技术有限公司
公司规模：
20人以下
公司性质：
国企
公司行业：
互联网/电子商务
公司地址：
【智联招聘认证】:手机可以做时间自由安排,不收任何费用及押金.应聘的加企业客服QQ：512512318
**********
会计
天津市镜界广告有限公司
绩效奖金全勤奖带薪年假员工旅游节日福利五险一金
**********
福利:
绩效奖金
全勤奖
带薪年假
员工旅游
节日福利
五险一金
**********
职位月薪：4001-6000元/月 
工作地点：天津-河西区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：会计/会计师
**********
岗位职责：
1.  负责公司正常记账报税工作，合同发票规整等工作，完成公司财务目标。
2.   正确进行会计核算，填制和审核会计凭证，登记明细账和总账，对款项的收付，财务的收发、增减和使用，收费收支进行核算。
3.   与财政、税务、银行等相关部门及会计师事务所等相关中介机构建立并保持良好的合作关系，并按时完成税务申报，发票管理等工作。
4.   正确计算收入、费用、成本，正确计算和处理财务成果，具体负责编制公司月度、年度财务报表。
5.   根据规定的成本、费用开支范围标准，负责公司各类费用的审核报销。
6.  及时做好会计凭证、财册、报表等财会资料的归集建档工作。
7.   负责公司各种核算和其他业务往来账工作。
8.  负责公司各项债权债务的清理结算工作。
9.   熟练掌握财务岗位工作要点，具备应变各种问题的解决能力。

任职要求：
1.  会计、财务相关专科以上学历；
2. 一年以上独立财务管理工作经验；
3. 精通国家财税政策规范，具备足够财会分析处理能力；
4. 熟悉财务、税务、审计等相关法规政策；
5. 具有会计职称等相关资格证书。
工作地址：
天津市河西区洞庭路香年广场A座402
查看职位地图
**********
天津市镜界广告有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市河西区洞庭路香年广场A座402
**********
文字编辑
天津凤凰空间文化传媒有限公司
五险一金绩效奖金年终分红全勤奖通讯补贴带薪年假定期体检节日福利
**********
福利:
五险一金
绩效奖金
年终分红
全勤奖
通讯补贴
带薪年假
定期体检
节日福利
**********
职位月薪：3000-5000元/月 
工作地点：天津-南开区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：3人
职位类别：文字编辑/组稿
**********
岗位职责：
1.图书责编工作，把握编辑流程中的各个环节，避免失误保证高质量高效率的出书；
2.图书文字审校工作，确保各环节质量达标；
3.配合其他部门做好图书合同、书号、CIP的申请工作；
4.配合图书宣传工作；
5.完成领导交予的其他任务。
任职要求：
1.本科及以上学历；中文、汉语言、英语专业，一年以上工作经验
2.文字功底扎实，保证图书的编审质量；
3.熟悉出版法律法规；
4.良好的人际沟通、协调、组织能力；
5.工作责任心强，思路清晰，考虑问题细致；
6.良好的团队合作精神。



工作地址：
天津市南开区大学道199号天铁科贸大厦5F
**********
天津凤凰空间文化传媒有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
媒体/出版/影视/文化传播
公司地址：
天津市南开区大学道199号天铁科贸大厦5F
查看公司地图
**********
底薪3800聘仓库管理员
天津世尊进出口贸易有限公司
14薪五险一金年底双薪年终分红餐补房补
**********
福利:
14薪
五险一金
年底双薪
年终分红
餐补
房补
**********
职位月薪：6001-8000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：仓库/物料管理员
**********
岗位职责： 
1、执行公司库房货物进、销、存管理，确保仓库作业顺利进行； 
2、负责仓库日常物资的验收、入库、码放、保管、盘点、对账等工作； 
3、负责仓库日常物资的拣选、复核、装车及发运工作； 
4、负责相关单证的保管与存档； 
5、仓库数据的统计、存档、帐务和系统数据的输入。
任职资格： 
1、大专及以上学历，接受优秀实习生； 
2、有相关领域实际业务操作经验者优先考虑； 
3、学习能力强，熟悉电脑办公软件操作； 
4、积极耐劳、责任心强、具有合作和创新精神。
工作地址：
天津-滨海新区
**********
天津世尊进出口贸易有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
互联网/电子商务
公司地址：
天津杰领天下科技发展有限公司
**********
美陈制作经理
天津市镜界广告有限公司
五险一金绩效奖金加班补助全勤奖带薪年假弹性工作员工旅游节日福利
**********
福利:
五险一金
绩效奖金
加班补助
全勤奖
带薪年假
弹性工作
员工旅游
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：天津-河西区
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：1人
职位类别：店面/展览/展示/陈列设计
**********
任职要求：
1.三年以上地产、商业行业美陈制作类工程公司工作经验；
2.能独立接洽客户需求、指导设计方向、确认材质工艺和预算、完成施工图和整体报价单；
3.大专及以上学历，熟练掌握CAD等工程设计类软件及各类办公电子软件。

工作地址：
天津市河西区洞庭路香年广场A座402
查看职位地图
**********
天津市镜界广告有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市河西区洞庭路香年广场A座402
**********
图片美工
天津鸿源信息技术有限公司
五险一金年底双薪绩效奖金加班补助交通补助餐补
**********
福利:
五险一金
年底双薪
绩效奖金
加班补助
交通补助
餐补
**********
职位月薪：4001-6000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：美术编辑/美术设计
**********
岗位职责：
电子商务美工岗位职责
1、店铺装修:负责公司旗下官网、淘宝商城页面整体规划设计;
2、产品处理:对上架商品的图片进行抠图、拼接、颜色调整、背景处理、产品描述美化等;
3、品牌推广:根据每月制定的促销计划、活动策划，设计相关广告logo、banner、海报等;
4、产品包装盒、包装袋的UI设计等
任职要求：
工作地址：
天津市河东区新开路与华兴道交口南侧创智大厦1-811
**********
天津鸿源信息技术有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
互联网/电子商务
公司主页：
//www.worldpp.cn
公司地址：
天津市河东区新开路与华兴道交口南侧创智大厦1-811
查看公司地图
**********
业务员
天津凤凰空间文化传媒有限公司
绩效奖金五险一金包吃交通补助通讯补贴节日福利员工旅游每年多次调薪
**********
福利:
绩效奖金
五险一金
包吃
交通补助
通讯补贴
节日福利
员工旅游
每年多次调薪
**********
职位月薪：3000-5000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：6人
职位类别：销售代表
**********
1.负责片区的主渠道图书销售业务及回款跟进
2.定期进行客户拜访，及时了解客户需求，建立并维护良好的客户关系；
3.根据不同的门店跟地域区别，及时将我社的新书进行推荐；
4.及时跟踪客户图书到货情况；
5.做好市场调查，了解市场定位；
6.与客户对账，检查发、退货准确率保证公司利益。
 
岗位要求：
1.专科及以上学历，热爱图书行业，适应短期出差，22-30岁
2.良好的人际沟通、协调、组织能力；
3.工作责任心强，有良好的分析、解决问题能力，思路清晰，考虑问题细致；
4.良好的团队合作精神。

本岗位升职空间大，底薪3-5k，奖金上不封顶，五险一金。
基本工资、岗位工资、职务工资、话补、交通补助、餐补，提供午餐，双休
工作地点：南开区白堤路附近

工作地址：
南开区大学道199号天铁科贸大厦
**********
天津凤凰空间文化传媒有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
媒体/出版/影视/文化传播
公司地址：
天津市南开区大学道199号天铁科贸大厦5F
查看公司地图
**********
销售经理
博科乐骏(天津)企业管理咨询有限公司
五险一金绩效奖金采暖补贴带薪年假定期体检员工旅游高温补贴节日福利
**********
福利:
五险一金
绩效奖金
采暖补贴
带薪年假
定期体检
员工旅游
高温补贴
节日福利
**********
职位月薪：8001-10000元/月 
工作地点：天津-和平区
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：5人
职位类别：销售经理
**********
岗位职责：
1. 制定并建立销售管控体系、流程，制订公司内部销售、销售制度和工作程序，组织实施并监督执行，提高运营效率；
2. 依据公司发展目标,编制年度、月度销售预算和执行预算，参与拟订资金筹措和使用方案，确保资金的有效使用；
3. 审阅销售专题报告和会计报表，对重大的财务收支计划、经济合同进行会签；
4. 审查公司对外提供的会计资料，随时检查公司财务系统账目的准确性和及时性；
5. 检查销售报表的准确性，并根据《销售报表》制作财务分析；
6. 负责对费用、往来、资金、资产的帐务处理和监控管理，定期参与对本部资产进行清理，使之帐实相符，按印鉴管理规定保管、使用财务印鉴；
7. 精通工商、税务的办事流程，衔接处理公司内关于工商、税务等事宜；
8. 完成公司交办的其他工作。 
任职要求：
1.年龄30-45周岁，财务、审计、金融等相关专业大学本科以上学历；
2.具备5年以上财务管理经验，具有会计资格证；
3.熟悉财务各模块的核算流程，具备优秀的职业判断能力和较强的实际操作能力，熟悉国家财税法律规范及当地相关法律法规；
4.具有较强的成本、服务意识和高度的责任心，强烈的事业心；
5.具有良好的管理能力、沟通能力和人际交往能力、组织协调和承压能力，为人正直。
福利待遇：
1.较市场具有竞争力薪酬待遇；
2.签订正式劳动合同，正式员工编制，五险齐全；
3.享受国家法定节假日，带薪年假、长期服务津贴等丰厚的员工福利；
4.提供良好的晋升通道和完善的培训提升系统，有机会参加公司旅游；
5.团队文化：优秀吸引优秀，在这里你可以与更多优秀的人共同成长。
工作地址：
天津市南开区宜宾道鼎泰丰产业园
查看职位地图
**********
博科乐骏(天津)企业管理咨询有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
专业服务/咨询(财会/法律/人力资源等)
公司地址：
天津市南开区宜宾道鼎泰丰产业园
**********
淘宝客服(无地点限制)电脑手机均可+兼职√
南京重道信息技术有限公司
五险一金年底双薪绩效奖金年终分红加班补助全勤奖弹性工作节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
年终分红
加班补助
全勤奖
弹性工作
节日福利
**********
职位月薪：15001-20000元/月 
工作地点：天津
发布日期：最新
工作性质：兼职
工作经验：不限
最低学历：不限
招聘人数：28人
职位类别：兼职
**********
【全国招聘】 兼或全职时间自由：可以在家，在外，在公司，在任何地方，用手机或者电脑操作，简单方便。时间灵活，工作自由。
【公司承诺】免费兼或全职：非职介,不收押金,不收取任何费用。

急招兼或全职：一个任务酬劳为15元-1000元不等，操作达到要求并且完成任务可立即发放工资。
工资一个任务一结算,不拖欠且安全无忧！但是工资的变动取决于您投入时间长短决定，您的收获和付出成正比。
想工作，请联系企业客服张珊QQ：512512318

我们不希望错过任何人才，希望您不要错过任何工作机会。

任职要求：
①自己有上网条件，对网络操作熟练；
②学历不限，在职或学生或者待业人员皆可；
③对网店和网购有一定的兴趣；
④有一定淘宝购物经验者优先

岗位职责：
①工作细心、勤奋、认真负责；
②吃苦耐劳，诚实守信；
③性格开朗，擅长沟通与人际交往，表达清晰流利。


我们不会收您钱，但我们会教您如何在网上挣钱。
本公司的招聘信息已经过工商等相关部门审核认证，请放心兼或全职。
 
工作地址：
想工作，请联系企业客服张珊QQ：512512318
**********
南京重道信息技术有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
IT服务(系统/数据/维护)
公司地址：
【智联招聘认证】:手机可以做时间自由安排,不收任何费用及押金.应聘的加企业客服QQ：512512318
**********
面向全国聘礼仪模特.包住.报销路费
江西维娜传媒有限公司
无试用期包住交通补助弹性工作
**********
福利:
无试用期
包住
交通补助
弹性工作
**********
职位月薪：50000元/月以上 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：演员/模特
**********
招聘年龄:18-28周岁之间
招聘形象:女, 形象好，气质佳，五官端正，笑容甜美，时尚大气
招聘要求；
1 有上进心，热爱工作。
2 有团队合作精神，积极配合活动要求。
3 语言表达能力强，有亲和力。
4 有相关行业经验者优先。
工作内容：负责一些礼仪服务工作，工作环境优越，无任何费用，面试合格即可安排时间上岗（中介勿扰）
生活待遇:提供优质住宿，环境优雅，空调标准间，全新被褥，无线网，拎包入住！冷热水24小时洗澡，应有尽有。当天安排优质食宿。
（有经验者优先，无经验者公司提供免费培训)
面试须知：面试前必须先联系确认。以便安排面试时间和需要准备的资料，条件不符者勿扰时间宝贵.
工作地址：
青云谱区名爵公馆11楼
**********
江西维娜传媒有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
青云谱区名爵公馆11楼
查看公司地图
**********
网管兼司机
天津百思道商务咨询有限公司
五险一金全勤奖节日福利
**********
福利:
五险一金
全勤奖
节日福利
**********
职位月薪：2001-4000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：网络管理员
**********
岗位职责：
1、负责公司计算机、计算机外设等硬件的管理与维修。
2、保证公司计算机网络系统的正常运行。
3、负责公司办公计算机操作系统、办公软件、应用软件的安装与维护。
4、负责日常办公用品采购、发放、登记管理，办公室设备、固定资产管理。
5、负责公司打印机、传真机、电话等办公设备的维护与保养。
6、负责公司日常环境卫生的维护、监督、检查。
7、领导安排的其他工作。
任职要求：
1.专科以上学历，计算机相关专业。
2.本岗位工作1-3年工作经验，有驾照驾驶熟练。
3.动手能力强，思维敏捷，有责任心，关于分析思考。
4.对网络硬件及操作系统有较深入的了解。

工作地址：
天津市和平区吉林路38号轻纺大厦410室
查看职位地图
**********
天津百思道商务咨询有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
专业服务/咨询(财会/法律/人力资源等)
公司地址：
天津市和平区吉林路38号轻纺大厦409室
**********
国际（内）空乘
南昌美航信息技术有限公司
**********
福利:
**********
职位月薪：10001-15000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：航空乘务
**********
岗位职责：空乘服务
国际空乘任职要求：
a.年龄介于18岁-28岁（特别优秀者，可适当放宽）。
b.空姐身高在1.58米； 空少身高在1.65米以上。
c.五官端正，身材匀称，牙齿整洁，裸露处没有明显疤痕和纹身等。
d.大专以上学历，流利的英语听说能力(培训和工作语言为英语)。
职位简介：
由于国际航空公司大量开辟中国航线，急需大量懂华语的空乘服务人员， 受英国空乘培训中心委托，在亚太地区举办国际空乘招聘（委培）项目。现英国航空正在中国招聘，机会难得。
(1.英语不好，符合国内空乘体检条件的，可推荐国内航空公司直接招聘）
（2.高中或中专学历的学生，可参加一年制国际空乘留学大专班，包工作）

特色优势
一.聘用岗位多，就业率高
二.就业范围涵盖全球三十多家国际著名航空公司
三.收入是国内空乘人员工资的三倍
四.对身高和相貌要求不高
五.推荐特别优秀者直接就业
六.获国际通用空乘资格证
七.培训时间短，费用低，经培训后，初次面试成功率在50%以上
八.签无固定期限的长期合约并有机会获得绿卡

英国空乘培训中心是英国一家专事机舱乘务培训和推荐合格机舱乘务员给国际航空公司的专业机构。业务包括提供互动培训课帮助学员掌握机舱乘务工作的技能和经验，颁发国际通用的机舱乘务员资格证书，以便能受聘于全球各航空公司。
学员通过在线学习，成绩达标，推荐到英国航空公司培训基地进行国际空乘课程培训。在培训合格后，培训中心即安排有长期合作聘用关系的国际航空公司聘用毕业生。如被聘用，有6个月的带薪培训及试用期（月薪金3000美元左右），正式聘用后，可工作至55周岁。在欧美国家当空姐、空少，每月薪金3100美元起，还有其他收入。资深员工可达4000美元以上，且有机会获工作所在国家绿卡。本期学员20人(亚太区）。
拟就业的航空公司：
英国航空 加拿大航空 纽西兰航空 法国航空 南非航空
香港国泰 港龙航空 美国联合航空 美国西北航空 瑞士航空 德国汉莎，荷兰皇家航空，芬兰航空， 澳洲航空 文莱航空 葡萄牙航空 达美航空 阿联酋航空 沙特航空 卡塔尔航空 维珍航空 北欧航空等三十家国际著名航空公司和国内各大航空公司。
我公司在全国省会城市均设有培训基地，培训将采用面授和网上学习方式进行，学习时间灵活，培训时间短，费用低，经培训后，初次面试成功率在50%以上.
联系方式：报名及索取资料请发邮件至邮箱：
13870057048@qq.com
电话及微信号：13870057048  赵老师
注：如果投递简历后，二天没有收到邮件回复，邮件可能在垃圾邮箱或发送失败，请给我的邮箱发邮件反应，我们会重新发送。需要及时获得航空公司招聘消息的，请添加我微信。



工作地址
南昌高新开发区高新创业大厦

工作地址：
南昌高新开发区高新创业大厦
查看职位地图
**********
南昌美航信息技术有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
中介服务
公司地址：
南昌高新开发区高新创业大厦
**********
行政专员
天津林泉世纪实业集团有限公司
五险一金包住弹性工作节日福利餐补
**********
福利:
五险一金
包住
弹性工作
节日福利
餐补
**********
职位月薪：3000-4000元/月 
工作地点：天津-和平区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：行政专员/助理
**********
岗位职责：
1. 履行报销流程，综合办公单据审核录入；
2. 负责公司合同、各种办公资料归档等工作；
3. 办公环境的管理、维护工作；
4. 办公资料及耗材的部门汇总统计工作；
5. 协助财税管理中心外围辅助工作；
6. 来访客人的接待工作：
7. 日常行政事务，如车票、机票预订等；
8. 公司车辆管理；
9. 公司标书、合同起草，竞投标事宜；
10. 领导安排的其他事务。

任职要求：
-身高160公分以上；
-大专以上学历，文秘、行政管理等相关专业；
-在校生条件优秀者亦可以考虑；
-熟练使用电脑等办公设备及软件；
-性格开朗、活泼，形象气质佳，待人接物大方得体；
-人品端正、积极上进、性格开朗、细致、具有较强责任心。

工作地址：
天津市和平区汉口西道格普澜轩底商9号香港站
**********
天津林泉世纪实业集团有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
广告/会展/公关
公司主页：
//lqsjzw.8v8.cn/
公司地址：
天津市东丽区华明工业园区华丰路6号A座3号楼B6015室
**********
文案策划
天津林泉世纪实业集团有限公司
五险一金包住弹性工作节日福利餐补
**********
福利:
五险一金
包住
弹性工作
节日福利
餐补
**********
职位月薪：4001-6000元/月 
工作地点：天津-和平区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：广告文案策划
**********
岗位职责：
1. 参与重要项目的创意构思、文案及客户提案，给予前期提案、设计创意说明及后期结案报告等服务；
2. 主导项目创意完成，能够独立产出活动创意、亮点结合创意内容；
3. 与设计师等配合，执行所负责项目的创意构思和文案；
4. 协调整合各方资源，策划、执行活动方案；
5. 熟悉整体活动流程及特点，可将活动策划方案转化为具体的执行方案，细化工作流程，严格按照时间节点和质量要求完成工作；
6. 各类创意文案、互动网站、微信公众号文案、微博、H5等内容营销的策划，概念创意及卖点提炼进行话题营销。

任职要求：
-本科以上学历，有2-3年独立策划并参与执行大型项目的经验；
-开阔的思路，优秀的文案功底，出色的审美感，良好的沟通能力和语言表达能力；
-超强的诉求点提炼能力，具有活动策划和创新能力，思维逻辑清晰，考虑问题细致周到；
-优秀的PPT制作能力，可以独立完成活动方案的编辑撰写；
-有同行业公司工作经验，具有创造性的营销策划能力。

* 能写得出创意，也能编辑稳重；
* 能获得客户认可，也能进行品牌宣传；
* 文字既能灵动，也能规范；
* 有一颗活泼向上的心，也有学习尝试的冲动；
工作地址：
天津市和平区汉口西道格普澜轩底商9号香港站
**********
天津林泉世纪实业集团有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
广告/会展/公关
公司主页：
//lqsjzw.8v8.cn/
公司地址：
天津市东丽区华明工业园区华丰路6号A座3号楼B6015室
**********
设计部经理/主管
天津市冠旗广告有限公司
五险一金绩效奖金加班补助带薪年假弹性工作补充医疗保险高温补贴节日福利
**********
福利:
五险一金
绩效奖金
加班补助
带薪年假
弹性工作
补充医疗保险
高温补贴
节日福利
**********
职位月薪：5000-8000元/月 
工作地点：天津-河西区
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：1人
职位类别：平面设计经理/主管
**********
岗位职责：
1、全面负责设计部门的各项工作；
2、项目的全案操作，包括策划、创意、设计、制作；
3、日常设计项目的统筹计划与任务安排；
4、设计项目的完成时间与质量把控；
5、对下属设计师进行创意与技术指导，定期进行培训；
6、负责对下属设计师进行绩效考核；
7、对能力不足者有权提出辞退意见；
8、负责公司设计师的招聘工作；
9、制定合理有效的内部管理制度与业务流程。

任职要求：
经验丰富，设计水准高，善于管理，执行力强，责任心强，策划能力突出，有大局观，熟悉全案（策划、创意、设计、制作），善于沟通，领悟力极强，有良好的客户服务意识。
工作地址：
天津市河西区通达尚城31-301
**********
天津市冠旗广告有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市河西区通达尚城31-301
查看公司地图
**********
文案策划
天津市镜界广告有限公司
五险一金年底双薪绩效奖金全勤奖节日福利带薪年假
**********
福利:
五险一金
年底双薪
绩效奖金
全勤奖
节日福利
带薪年假
**********
职位月薪：4000-8000元/月 
工作地点：天津-河西区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：广告文案策划
**********
工作内容：  
从事地产行业（商业）文策工作。负责相关项目的营销推广方案、创意及宣传资料的文案撰写；根据客户需求制定活动方案；收集业内最新动态，营销案例等；参与负责项目新媒体平台的创意输出；跟进自己策划方案的创意执行。
任职要求：
新闻、广告学、中文、营销等相关专业毕业背景优先；有文案或策划工作经验，了解商业地产并有全案广告公司工作经验优先；能独立完成文案、策划方案的创作等；具有较强的团队协作能力；熟练应用word、excel、PowerPoint等办公软件。
工作地址：
天津市河西区洞庭路香年广场A座402
查看职位地图
**********
天津市镜界广告有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市河西区洞庭路香年广场A座402
**********
助教
天津百思道商务咨询有限公司
五险一金全勤奖节日福利员工旅游
**********
福利:
五险一金
全勤奖
节日福利
员工旅游
**********
职位月薪：4001-6000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：咨询顾问/咨询员
**********
岗位职责：
一、负责每个月企业家论坛举办前期的企业家邀约、会中服务、会后同小组下企业进行短期的调研
二、负责企业家俱乐部活动策划、包装、推广、服务
三、负责会员的定向服务支持、想其之所想，急其之所急
四、有效的协助主班教师授课，参与课程各个环节并严格保持教学质量，通过日常训练，不断继续提升教学质量
五、 根据主讲老师的需要提供教学帮助，如课堂互动、资料整理等，负责并整理教具库，确保教具完善
六、完成领导安排的其他临时性工作
任职要求：
一、为人正直、诚信、有爱心、有素养
二、自律、上进、力求完美
三、热爱学习，善于跟进国家各项政策、捕捉潜在的机会，有强烈的责任感，人生始终在坚定不移地追求

工作地址：
天津市和平区吉林路38号轻纺大厦409室
查看职位地图
**********
天津百思道商务咨询有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
专业服务/咨询(财会/法律/人力资源等)
公司地址：
天津市和平区吉林路38号轻纺大厦409室
**********
活动执行
天津市镜界广告有限公司
年底双薪绩效奖金全勤奖带薪年假员工旅游节日福利
**********
福利:
年底双薪
绩效奖金
全勤奖
带薪年假
员工旅游
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津-河东区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：2人
职位类别：广告制作执行
**********
工作职责：
1、公司各活动项目的落地执行工作；
2、独立完成活动的具体策划运营文案、协调部门内外各种资源，根据策划方案进行各种活动的组织、筹备、协调和执行；
3、线下活动物料安排、管理，保障活动顺利完成；
4、相关资源的对接，悉活动布展，有一定的布展经验，可对接公关公司对于布展制作的各种物料，以及设备舞台搭建、灯光和音效等非常熟悉。
5、各项活动的执行进度和效果反馈；
 
任职要求：
1、3年以上活动执行经验，熟悉整个流程；
2、吃苦耐劳，勤奋上进，有布展经验优先考虑；
3、有较强的沟通能力，有一定的创新能力、团队协作意识与执行能力；
4、为人正直诚信，善于沟通，具有高度的责任心，较强的学习能力和团队精神。
5、外地

工作地址：
天津市河西区洞庭路香年广场A座402
查看职位地图
**********
天津市镜界广告有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市河西区洞庭路香年广场A座402
**********
平面设计师
天津市镜界广告有限公司
五险一金年底双薪绩效奖金全勤奖节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
全勤奖
节日福利
**********
职位月薪：4000-7000元/月 
工作地点：天津-河西区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：广告创意/设计师
**********
工作内容：
商业地产全案设计，版式能力出众；熟悉项目品牌核心及产品调性并独立完成项目日常阶段工作内容。
任职要求：
艺术设计、视觉传达、广告设计、动画相关专业优先；熟练掌握PS、AI、CAD等制图软件；具备丰富的平面设计和广告创意能力。
欢迎审美洁癖者。

工作地址：
天津市河西区洞庭路香年广场A座402
查看职位地图
**********
天津市镜界广告有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市河西区洞庭路香年广场A座402
**********
园林设计 景观设计 设计助理 （接收实习生)
北京运旺时胜商贸有限公司
五险一金年底双薪包住包吃全勤奖加班补助带薪年假节日福利
**********
福利:
五险一金
年底双薪
包住
包吃
全勤奖
加班补助
带薪年假
节日福利
**********
职位月薪：5000-9000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：中专
招聘人数：6人
职位类别：园林/景观设计
**********
工作地点在北京

园林设计  景观设计  设计助理  （接收应届生）
岗位职责：
1. 负责在接到设计主管安排的任务之后，与甲方进行充分沟通，了解甲方的设计意向。根据方案要求搜索相关资料并整理。
2. 负责收集和整理景观工程管理的新思路、新方法、新技术和新工艺。
3. 负责根据所整理的资料和自己的思维绘制手绘稿，及时高效高质量完成。
4.  负责上色之后，施工图的绘制。施工图绘制过程中要与现场尺寸校对，并与工程部交流。
5. 设计方案须通过领导的审核通过之后，与甲方沟通协商。与甲方沟通协商之后，负责对甲方就设计内容提出的问题进行反复的修改、补充，直至方案一致通过。
6. 负责协助设计主管与工程部的沟通协商，将设计方案的落实。
7. 负责现场施工的同时跟进施工进度，随时完成补充方案。
8. 熟悉工程规范，管理景观施工现场，审核施工质量、监督施工进度，解决施工技术难题。
9. 遵守公司的各项规章制度，服从上级的工作分配与工作调动，认真完成工作任务。
10. 其他临时工作。

任职要求：
1.建筑规划、园林景观等相关专业本科及以上学历；
2.园林景观设计工作经验，能够熟练操作AUTOCAD、SKETCHUP、PHOTOSHOP、3DMAX、等专业绘图软件；
3.能独立组织景观项目的设计和施工工作，能有效的控制工期和景观实施效果；
4.在设计方面具有独特风格，熟悉设计流程、熟悉植物的绿化配植及灯光搭配效果；
5.具备良好的沟通交流能力，以及团队协助精神；
6.具备专业创新能力、掌握高效的工作方法，具备良好的协调能力，具有极强的敬业精神和责任心；
7.具有大型景观项目规划设计经验者优先。

工作地址：
北京市海淀区明光桥
查看职位地图
**********
北京运旺时胜商贸有限公司
公司规模：
100-499人
公司性质：
合资
公司行业：
媒体/出版/影视/文化传播
公司地址：
北京市海淀区明光桥
**********
文员
天津百思道商务咨询有限公司
五险一金全勤奖带薪年假节日福利
**********
福利:
五险一金
全勤奖
带薪年假
节日福利
**********
职位月薪：2001-4000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：后勤人员
**********
岗位职责：
1、业务数据的统计汇总及分析 。
2、负责接听、拨打服务热线所有来电，解答疑问，并做好记录。
3、负责公司合作伙伴的回访及售前售后服务跟踪。
4、工作资料的保存、分类、归档、保管。
 任职要求：
1、大专以上学历，年龄在22-24岁之间。
2、熟练掌握并使用电脑等办公设备，熟悉网络工作。
3、具有良好的道德品质和企业意识。
 
工作地址：
天津市和平区吉林路38号轻纺大厦410室
查看职位地图
**********
天津百思道商务咨询有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
专业服务/咨询(财会/法律/人力资源等)
公司地址：
天津市和平区吉林路38号轻纺大厦409室
**********
行政专员/助理/后勤
天津世尊进出口贸易有限公司
五险一金绩效奖金年终分红采暖补贴带薪年假补充医疗保险定期体检员工旅游
**********
福利:
五险一金
绩效奖金
年终分红
采暖补贴
带薪年假
补充医疗保险
定期体检
员工旅游
**********
职位月薪：4001-6000元/月 
工作地点：天津-和平区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：2人
职位类别：行政专员/助理
**********
岗位职责：
1. 对来访客人做好接待、登记、引导工作，及时通知被访人员。对无关人员、上门推销和无理取闹者应拒之门外。
2. 统计每日到访人数，编制日报。
3. 接听电话，按要求转接电话或记录信息，确保及时准确。
4.协助人事招聘、面试。
5. 监督员工每日考勤情况。负责每月统计公司员工的考勤情况，考勤资料存档。
6. 负责整理、分类、保管公司常用表格并依据实际使用情况进行增补。

任职要求：
1、专业不限，中专及以上学历，优秀者条件可适当放宽；
2、熟悉办公室行政管理知识及工作流程；
3、工作仔细认真、为人正直。具备较强的书面和口头表达能力。
工作地址：
天津-和平区
**********
天津世尊进出口贸易有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
互联网/电子商务
公司地址：
天津杰领天下科技发展有限公司
**********
平面设计
天津林泉世纪实业集团有限公司
每年多次调薪五险一金餐补弹性工作节日福利
**********
福利:
每年多次调薪
五险一金
餐补
弹性工作
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津-和平区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：平面设计
**********
岗位职责：
1. 能够独立完成设计创意工作的开展，包括品牌识别系统、平面、展览展示、画册、VI、平面印刷品等相关类别；
2. 负责公司日常宣传相关设计制作，企业形象系统的建立与维护，企业宣传资料的设计、制作与创新；
3. 对设计作品风格的准确把握，包括色调搭配、布局合理性等；
4. 基于客户的项目要求，精准完成项目设计中的创意工作和理念传达；
5. 利用自身的行业背景和知识，在设计和制作上有效地控制成本；
6. 设计项目交付后的修正完善总结工作。

任职要求：
-两年以上专业平面设计工作经验，美术设计类、艺术设计类相关专业，大专及以上学历；
-良好的视觉设计能力、色彩感觉和美术功底，有较强手绘能力；
-熟练运用Photoshop、Illustrator、AI等设计软件；
-熟悉设计输出、印刷、喷绘修图改图等后期制作工艺流程。

工作地址：
天津市和平区汉口西道格普澜轩底商9号香港站
**********
天津林泉世纪实业集团有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
广告/会展/公关
公司主页：
//lqsjzw.8v8.cn/
公司地址：
天津市东丽区华明工业园区华丰路6号A座3号楼B6015室
**********
库管员
天津市武清区伟健广告中心
每年多次调薪五险一金绩效奖金全勤奖包住通讯补贴员工旅游节日福利
**********
福利:
每年多次调薪
五险一金
绩效奖金
全勤奖
包住
通讯补贴
员工旅游
节日福利
**********
职位月薪：2001-4000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：2人
职位类别：后勤人员
**********
岗位职责：
1、负责仓库产品到货、验货。
2、负责公司库存商品、工具、办公用品的保管。
3、定期做好库存清点工作，做到日清月结，帐实符合。
4、做好库房的清算、整齐工作，做到库存标识清晰、堆放整洁 。
5、负责出入库物料管理，填写公司仓库物资动态管理台帐。
6、负责物料的安全、消防管理工作。
7、无审批手续或手续不全不得出入库。
8、每周至少清算库房一次,确保库房洁净、通道疏通、货物堆搁整洁。
9、公司领导交办的其他工作。

任职要求：
，年龄23--35，会基本电脑操作，有驾照，驾驶熟练；
性格外向，善于沟通，执行力强。
工作地址：
天津市武清区雍阳西道邮政局（过桥）向西100米道北天津广播电视报读者生活馆
查看职位地图
**********
天津市武清区伟健广告中心
公司规模：
20-99人
公司性质：
其它
公司行业：
广告/会展/公关
公司地址：
天津市武清区雍阳西道邮政局（过桥）向西100米道北天津广播电视报读者生活馆
**********
4S店索赔员
北京荣兴行汽车贸易有限公司
五险一金加班补助采暖补贴高温补贴节日福利
**********
福利:
五险一金
加班补助
采暖补贴
高温补贴
节日福利
**********
职位月薪：3000-6000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：汽车定损/车险理赔
**********
岗位职责：
1.掌握质量担保政策，按照索赔流程受理用户的担保申请； 
2. 按照索赔件管理标准对索赔件进行判定； 
3. 熟练掌握索赔鉴定标准，对索赔件按照标准进行鉴定；
4. 负责建立索赔申请并跟踪申请状态；
5. 索赔相关文件及数据资料的存档管理 ；
6.负责与服务顾问之间的交流来跟踪索赔进度。
 任职要求：
1、大专及以上学历。
2、熟悉轿车售后维修。
3、良好的服务意识。
4、熟知国家法律、法规和厂家的售后服务政策。

福利待遇：
1、福利完善：享受养老保险、医疗保险、工伤保险、失业保险、生育保险、公积金、各种补贴；
2、提供有竞争力的薪资：底薪+提成；
3、工作环境舒适。

如果你热爱汽车行业，拼搏向上，积极进取，欢迎加入我们！

工作地址：
北辰区铁东北路北方汽贸园C区1-6号
查看职位地图
**********
北京荣兴行汽车贸易有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
汽车/摩托车
公司主页：
null
公司地址：
北京市石景山区古城西路63号国际汽车贸易园区A区66号
**********
淘宝直播主播
山西中景华文化传媒有限公司
定期体检员工旅游节日福利股票期权绩效奖金无试用期每年多次调薪
**********
福利:
定期体检
员工旅游
节日福利
股票期权
绩效奖金
无试用期
每年多次调薪
**********
职位月薪：8001-10000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：10人
职位类别：视频主播
**********
岗位职责：
1、淘宝主播，购物分享；
2、配合公司相关活动安排；
3、进行淘宝直播；

任职资格：
1、聪明伶俐，会为人处事，形象气质佳；
2、熟悉各类网络交际平台，了解最新的时尚动态；
3、大专以上学历，艺术、媒体类院校毕业优先考虑；
4、有很强的人际沟通和交流能力，性格外向，有亲和力；
5、有很强的审美和包装能力，熟悉粉丝心理；

工作地址：
凯德大厦
查看职位地图
**********
山西中景华文化传媒有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
媒体/出版/影视/文化传播
公司地址：
太原亲贤街9号 双喜城 6栋 2502号
**********
编务
天津凤凰空间文化传媒有限公司
五险一金绩效奖金包吃全勤奖交通补助定期体检节日福利员工旅游
**********
福利:
五险一金
绩效奖金
包吃
全勤奖
交通补助
定期体检
节日福利
员工旅游
**********
职位月薪：3000-4000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：3人
职位类别：编辑出版
**********
岗位职责：
 一、负责图书选题申报、合同审核及管理、发稿、编校流程安排、协调成书质检等工作。
二、配合财务部、编辑部、发行部进行费用复核，收集、汇总，并整理其需要的数据和信息。
任职要求：
一、专业不限，年龄22-35岁
二、工作态度端正，严谨细致，抗压能力强，喜欢挑战
三、熟练运用办公软件Excel、Word、PPT
四、热爱出版工作，有类似从业经验者优先

福利待遇：五险一金，双休，超长假期，提供午餐
工作地址：
南开区大学道199号天铁科贸大厦
查看职位地图
**********
天津凤凰空间文化传媒有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
媒体/出版/影视/文化传播
公司地址：
天津市南开区大学道199号天铁科贸大厦5F
**********
灯光工程 助理
天津林泉世纪实业集团有限公司
每年多次调薪五险一金包住弹性工作节日福利
**********
福利:
每年多次调薪
五险一金
包住
弹性工作
节日福利
**********
职位月薪：3000-4000元/月 
工作地点：天津-和平区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：灯光师
**********
岗位职责：
1. 负责演艺活动灯光器材的布线、安装、调试工作；
2. 负责舞台灯光布置，执行演出过程中的灯光控制，确保舞台灯光的呈现效果；
3. 按照灯位图组织装台工作，根据演出的节奏完成各种演出的灯光操作；
4. 负责灯光设备的日常操作、调试、维护和保养工作； 
5. 演出灯光效果进行记录，定期汇总，适时调整、维修， 并及时跟踪，保障演出顺利  

任职要求：
-有无经验均可，集团将统一进行专业培训，帮助新员工胜任该岗位工作；
-欢迎热爱演出事业，喜欢激情、青春激荡演出现场的年轻人；

加入我们：
各大音乐节任你逛，
各场演唱会任你看，
明星近距离接触，
发布会、粉丝会，
想看的都能有，
世界那么大，
出去看了才知道。

工作地址：
天津市东丽区华明工业园区华丰路6号A座3号楼B6015室
**********
天津林泉世纪实业集团有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
广告/会展/公关
公司主页：
//lqsjzw.8v8.cn/
公司地址：
天津市东丽区华明工业园区华丰路6号A座3号楼B6015室
**********
活动执行
天津林泉世纪实业集团有限公司
五险一金包住弹性工作节日福利餐补
**********
福利:
五险一金
包住
弹性工作
节日福利
餐补
**********
职位月薪：4000-5000元/月 
工作地点：天津-和平区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：活动执行
**********
岗位职责：
1. 对接客户，协助分析活动业务，制定相关工作计划；
2. 负责活动现场的组织实施以及应急事件处理工作；
3. 负责活动过程中领导安排的相关环节工作，并做活动记录；
4. 协调活动现场布置及各项物料安排；
5. 与制作部门配合确保客户要求得以有效执行实施，提供价格预算、简单的方案预选等工作；
6. 负责活动现场组织、指挥、管理及监控活动执行状态，快速反应并处理执行工作任务；
7. 完成活动执行、维护、总结等相关后续工作；
8. 对接工程部，就工程部所产生的技术问题，与客户进行及时协调沟通。

任职要求：
-市场营销或相关专业大专以上学历；
-1年以上同行业大型广告、公关、会展公司工作经验，有较强的独立工作能力；
-有较好的形象和沟通协调能力，性格开朗大方，良好的表达、策划和领悟能力；
-有很强项目策划能力、现场掌控能力和应变能力，有相关活动现场施工、搭建经验者优先；
-有较强的时间管理能力，工作效率高，能够有效控制工作进度；
-具有良好的团队精神，能承受一定工作压力，适应一定程度的出差及加班。

工作地址：
天津市和平区汉口西道格普澜轩底商9号香港站
**********
天津林泉世纪实业集团有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
广告/会展/公关
公司主页：
//lqsjzw.8v8.cn/
公司地址：
天津市东丽区华明工业园区华丰路6号A座3号楼B6015室
**********
婚礼项目总监
众骧(天津)文化传播有限公司
绩效奖金年终分红全勤奖交通补助通讯补贴员工旅游
**********
福利:
绩效奖金
年终分红
全勤奖
交通补助
通讯补贴
员工旅游
**********
职位月薪：4001-6000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：1人
职位类别：婚礼/庆典策划服务
**********
岗位职责：
1、总体协调婚礼方案的制定和规划，负责对各个环节的监督；
2、超强的业务谈单能力和沟通能力，具备各种案例执行能力；
3、把控婚礼的整体定位、预算和可执行性；
4、根据公司安排在规定时间内推出相应宣传推广方案和促销方案；
5、良好的团队组织、协调和沟通能力；
6、曾经自己独立策划和执行过知名婚礼的高端婚礼策划人；
7、具有丰富的行业资源整合能力；
8、完成领导交办的其它工作。
任职要求：
1、 个人具备较好策划能力及宴会设计水平，对婚礼策划案及婚礼道具的风格、趋势具备较强的研发能力、评判能力，对国内各地婚礼文化、风俗、案例有深刻理解及研究；
2、 有较强事业心、组织协调能力、敬业精神、学习能力；
3、 对策划师有较强培训、培养能力及运营管理能力,至少管理过15人以上团队；
4、 婚礼行业工作经验五年以上，大专以上学历。
工作地址：
天津市南开区城厢西路鼓楼天街盛津园22-1
查看职位地图
**********
众骧(天津)文化传播有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
广告/会展/公关
公司主页：
http://www.weddingfashion.cc/
公司地址：
天津市南开区水上公园西路水云花园B16
**********
执行助理
天津光度文化活动策划有限公司
五险一金餐补房补定期体检高温补贴节日福利创业公司
**********
福利:
五险一金
餐补
房补
定期体检
高温补贴
节日福利
创业公司
**********
职位月薪：2001-4000元/月 
工作地点：天津-南开区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：2人
职位类别：活动执行
**********
1.协助部门经理负责活动管理 活动统筹 活动策划 活动执行等工作内容
2大专以上学历 具有良好的沟通能力 协调能力 亲和力强
  工作地址：
天津市西青区华鼎智地
查看职位地图
**********
天津光度文化活动策划有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市南开区红旗南路观景里3-2-703
**********
电话招聘专员
博科乐骏(天津)企业管理咨询有限公司
五险一金绩效奖金采暖补贴带薪年假定期体检员工旅游高温补贴节日福利
**********
福利:
五险一金
绩效奖金
采暖补贴
带薪年假
定期体检
员工旅游
高温补贴
节日福利
**********
职位月薪：2500-5000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：5人
职位类别：咨询顾问/咨询员
**********
岗位职责：
1.根据公司项目招募需求，在招聘网站寻找并筛选符合岗位要求的简历，目前项目为招募大都会人寿销售经理；
2.根据现有候选人名单进行电话招募与接洽工作，完成候选人的初试邀约；
3.对招募流程进行简单汇总统计并进行初步分析，追踪后续招聘效果；
4.完成团队交办的其他工作。 
任职要求：
1.年龄18-35周岁，性别不限，有招聘、销售或客服经验者优先；
2.本科及以上学历，有上述相关经验可放宽至大专；
3.口齿清晰，普通话标准，良好的沟通及语言表达能力；
4.乐于挑战高绩效收入，具有服务意识和责任心，工作勤奋主动，具有良好的团队合作精神
福利待遇：
1.较市场同类岗位更具竞争力的无责任底薪
2.高比例绩效奖金，上不封顶，平均绩效奖金可达5000元（不含底薪）
3.奖励多多：根据工作完成情况设立多种奖励
4.节日福利：带薪轮休假及法定节假日休息，丰厚的节日福利
5.上升空间：完善的岗前培训及岗位带教，提升职场技能，表现优异者将有优先承担管理职能
6.团队文化：优秀吸引优秀，与更多优秀的人共同成长
工作地址：
天津市南开区宜宾道鼎泰丰产业园
**********
博科乐骏(天津)企业管理咨询有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
专业服务/咨询(财会/法律/人力资源等)
公司地址：
天津市南开区宜宾道鼎泰丰产业园
**********
网站运营
天津鸿源信息技术有限公司
餐补五险一金
**********
福利:
餐补
五险一金
**********
职位月薪：6001-8000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：市场运营
**********
运营经理
 岗位职责：
1、根据公司对外合作计划完成相应合作指标。
2、负责公司产品与各互联网平台合作，带来稳定的流量和品牌合作
3、维护合作伙伴关系，协调解决合作中出现的各种问题
4、与相关联网站进行资源互换合作，维系日常合作关系客户
5、撰写项目合作方案，并进行谈判
任职要求：
1、具有互联网产品合作经验
2、具有一定的产品合作资源，尤其平台型网站资源优先
3、具有一定的沟通能力，谈判能力，协调能力。
4、有较强的服务意识和耐心、责任心，勤奋、不怕吃苦。

工作地址：
天津市河东区新开路与华兴道交口南侧创智大厦1-811
查看职位地图
**********
天津鸿源信息技术有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
互联网/电子商务
公司主页：
//www.worldpp.cn
公司地址：
天津市河东区新开路与华兴道交口南侧创智大厦1-811
**********
客服文员
天津百思道商务咨询有限公司
五险一金绩效奖金节日福利全勤奖
**********
福利:
五险一金
绩效奖金
节日福利
全勤奖
**********
职位月薪：4001-6000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：客户服务专员/助理
**********
岗位职责：
1、在公司原有客户资源的基础之上，根据网络及媒体平台收集目标客户资料；
2、通过已有资源发掘潜在客户，通过电话进行渠道开发和业务拓展；
3、收集、记录客户反馈信息，进行分析，挖掘客户需求；
4、协同销售部门进行文档、客户资料的管理。
任职要求：
1、专科或以上学历，一年以上相关工作背景；
2、擅于沟通、思维灵敏、表述能力强、口齿清晰、富有亲和力；
3、有责任心、能承受工作压力，有团队合作精神。

工作地址：
天津市和平区吉林路38号轻纺大厦409室
查看职位地图
**********
天津百思道商务咨询有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
专业服务/咨询(财会/法律/人力资源等)
公司地址：
天津市和平区吉林路38号轻纺大厦409室
**********
灯光工程
天津林泉世纪实业集团有限公司
每年多次调薪五险一金包住弹性工作节日福利
**********
福利:
每年多次调薪
五险一金
包住
弹性工作
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津-和平区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：灯光师
**********
岗位职责：
1. 负责演艺活动灯光器材的布线、安装、调试工作；
2. 负责舞台灯光布置，执行演出过程中的灯光控制，确保舞台灯光的呈现效果；
3. 按照灯位图组织装台工作，根据演出的节奏完成各种演出的灯光操作；
4. 负责灯光设备的日常操作、调试、维护和保养工作； 
5. 演出灯光效果进行记录，定期汇总，适时调整、维修， 并及时跟踪，保障演出顺利
6. 制定灯光操作的基本规范和流程，拟定设备使用和保养制度；
7. 对需要采购或更换的灯光设备及时填单上报。

任职要求：
-广播电视灯光制作专业、舞美、电子机械、机械等相关专业； 
-熟悉光源性质，灯具的特性，熟悉灯光和配件使用；
-有一定的灯光学习能力及艺术修养，感官功能良好； 
-有临场经验以及处理演出当中的各种复杂情况能力； 

特殊备注：
-如果是零基础，只要你有一颗上进和喜欢演出的心，集团会积极提供专业培训，帮助新员工胜任该岗位工作。
-退伍军人优先考虑。
-欢迎喜欢激情、喜欢演出现场的年轻人加入，无论有无经验，只要热情好学，最终我们都会培养员工成为技能型、实用型人才。

工作地址：
天津市东丽区华明工业园区华丰路6号A座3号楼B6015室
**********
天津林泉世纪实业集团有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
广告/会展/公关
公司主页：
//lqsjzw.8v8.cn/
公司地址：
天津市东丽区华明工业园区华丰路6号A座3号楼B6015室
**********
3D设计师
天津市镜界广告有限公司
五险一金绩效奖金年终分红加班补助全勤奖弹性工作员工旅游节日福利
**********
福利:
五险一金
绩效奖金
年终分红
加班补助
全勤奖
弹性工作
员工旅游
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：3人
职位类别：三维/3D设计/制作
**********
任职资格：
1、参与团队创意策略的研讨和制定，提供创意和富有想象力的设计方案；
2、能够按项目要求，独立完成3d人物、场景模型的设计和制作；根据原稿进行人物、场景的建模，以及贴图的绘制，保持高标准的还原度；
3、参与项目创意策划会，准确理解设计的风格和定位；
4、能独立设计、配合项目及设计部门领导完成高品质的创意设计；
5、平面设计师合作，将视觉设计与其他部分合为一体，如：场地合成等；
6、前期绘制3D设计图、施工图，后期跟进项目的制作、搭建执行等工作。

 
工作要求：
1、熟悉舞美、会展所设计的相关制作工艺和材料，对效果、成本的把控有一定掌握；
2、工作自发主动细致认真，吃苦耐劳，善于沟通，具备高度的责任心及团队协作能力，愿意接受挑战性的工作，能够及时高效完成任务。
3、良好的团队精神及工作稳定性，能够很好的按时完成工作；
4、熟练运用3Dmax、CAD、VR、Photoshop、Illustrator,等相关设计软件。
5.具有商业项目服务经验优先

工作地址：
天津市河西区洞庭路东江道交口香年广场A座912
查看职位地图
**********
天津市镜界广告有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市河西区洞庭路香年广场A座402
**********
销售经理
中联众邦(天津)科技有限公司
交通补助包住员工旅游绩效奖金五险一金节日福利带薪年假
**********
福利:
交通补助
包住
员工旅游
绩效奖金
五险一金
节日福利
带薪年假
**********
职位月薪：5000-10000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：6人
职位类别：销售经理
**********
1.销售经理，工作地点天津市区，主要面对天津中小学教育单位，要求：两年以上销售工作经验。熟悉政府采购流程和教学设备行业者优先。
2.销售助理，工作地点滨海新区或四郊五县中小学教育单位，要求：对销售有强烈的兴趣，愿意接受公司培养，能长期任职，享受助理奖金提成。
3.销售工程师，工作主要面对天津所有大学和高职院校，要求：两年以上销售工作经验。熟悉政府采购流程和教学设备行业者优先。
4.市场推广经理，主要宣传推广和销售新概念健康房的装修整体解决方案。工作地点全天津。要求：对营销有强烈的兴趣，略懂装修知识，能够吃苦耐劳。
公司简介：
中联众邦天津科技有限公司，从事教育装备行业和校园文化建设工程，主要承接有关教育系统的政府采购项目。目前具有市场优势的产品有：
1.趣味田径少儿体育器材，已列入教育部和天津市教委的教学标准配备目录，天津市已下发相关的音体美新标准补充采购的红头文件，今年是全面采购年。
2.液态金属及液态金属三d打印机，是全球唯一的技术，我公司是天津和上海的总代。习近平、李克强等中央国家领导人军队液态金属产品的成果转化和衍生产品深切关注，市场前景远大。
3.创客空间及其他创新实验室，我们在天津市近百所学校都有案例，坚持"课程+课件+实操+比赛"的理念，深获教育局和各个学校的好评。
具体面谈。

工作地址：
天津市中心商务区极地广场32栋3门601
查看职位地图
**********
中联众邦(天津)科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
教育/培训/院校
公司地址：
天津市中心商务区极地广场32栋3门601
**********
活动执行
天津光度文化活动策划有限公司
创业公司
**********
福利:
创业公司
**********
职位月薪：2001-4000元/月 
工作地点：天津-西青区
发布日期：最新
工作性质：校园
工作经验：不限
最低学历：大专
招聘人数：3人
职位类别：活动执行
**********
岗位职责：市场开发  活动现场管控

任职要求：要求沟通能力 协调能力 组织能力强
工作地址：
天津市西青区华鼎智地
**********
天津光度文化活动策划有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市南开区红旗南路观景里3-2-703
查看公司地图
**********
活动执行
天津光度文化活动策划有限公司
五险一金绩效奖金弹性工作节日福利创业公司
**********
福利:
五险一金
绩效奖金
弹性工作
节日福利
创业公司
**********
职位月薪：2001-4000元/月 
工作地点：天津-南开区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：3人
职位类别：活动执行
**********
岗位职责：
1、与客户就项目内容与细节确定进行良好有效的沟通，促进项目的落实与推进实施； 
2、完成各类活动项目的前期跟进、中期执行与项目后期制作工作；
3、完成策略、创意方案的撰写工作；
4、参与活动前期筹备（如与供应商沟通、与场地方谈判，准备及分发物料）；
5、参与活动现场的管理，解决突发问题，传达项目更新资料； 
6、负责项目各类文件、数据和照片的汇总、整理，生成报表报告。

任职要求：
具备优秀的人际沟通和语言表达能力、灵活机智的处事能力，及优秀的客户维护能力； 
2、有强烈的工作责任心和团队合作精神，能承担较大的工作压力； 
3、具有诚信的品格，工作细致、认真负责； 
4、熟练操作各种办公软件，如Word, Excel, PowerPoint等； 
5、具备良好的文字功底，具备活动方案的撰写及预算编制能力；
6、熟悉活动常用搭建材料及常用AV设备。

工作地址：
天津市西青华鼎智地
查看职位地图
**********
天津光度文化活动策划有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市南开区红旗南路观景里3-2-703
**********
图书实习美术编辑（兼职也可）急
天津凤凰空间文化传媒有限公司
五险一金绩效奖金交通补助餐补通讯补贴定期体检节日福利包吃
**********
福利:
五险一金
绩效奖金
交通补助
餐补
通讯补贴
定期体检
节日福利
包吃
**********
职位月薪：4001-6000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：1人
职位类别：美术编辑/美术设计
**********
职位描述：
1.图书封面和内页设计；
2.图书制版排版；
3.对外排稿件的整理及改排工作；
4.展会、广告、名片等设计；

岗位要求：
1.本科、研究生在校大学生优先；
2.熟练使用indesign或illustrator等排版设计软件；
3.良好的美术功底和鉴赏能力，具备出色的视觉创造能力；
4.沟通能力强，抗压能力强
5.热爱图书出版行业，有相关经验者优先录用


工作地址：
天津市南开区大学道199号天铁科贸大厦
查看职位地图
**********
天津凤凰空间文化传媒有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
媒体/出版/影视/文化传播
公司地址：
天津市南开区大学道199号天铁科贸大厦5F
**********
图书发行员
天津凤凰空间文化传媒有限公司
五险一金年底双薪全勤奖交通补助餐补通讯补贴定期体检员工旅游
**********
福利:
五险一金
年底双薪
全勤奖
交通补助
餐补
通讯补贴
定期体检
员工旅游
**********
职位月薪：2001-4000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：销售代表
**********
1.负责片区的主渠道业务；
2.根据汇款计划完成回款任务；
3.定期进行客户拜访，及时了解客户需求，建立并维护良好的客户关系；
4.根据不同的门店跟地域区别，及时将我社的新书进行推荐；
5.及时跟踪客户图书到货情况；
6.做好市场调查，了解市场定位；
7.与客户对账，检查发、退货准确率保证公司利益。
 
岗位要求：
1.专科及以上学历，热爱图书行业，适应短期出差，有相关工作经验者优先；
2.良好的人际沟通、协调、组织能力；
3.工作责任心强，有良好的分析、解决问题能力，思路清晰，考虑问题细致；
4.良好的团队合作精神。
本岗位升职空间大，底薪2-4k，奖金上不封顶，五险一金。
基本工资、岗位工资、职务工资、话补、交通补助、餐补，提供午餐，双休
工作地点：南开区白堤路附近

工作地址：
天津市南开区大学道199号天铁科贸大厦
**********
天津凤凰空间文化传媒有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
媒体/出版/影视/文化传播
公司地址：
天津市南开区大学道199号天铁科贸大厦5F
查看公司地图
**********
4S店销售顾问（铁东路）
北京荣兴行汽车贸易有限公司
五险一金绩效奖金加班补助餐补采暖补贴
**********
福利:
五险一金
绩效奖金
加班补助
餐补
采暖补贴
**********
职位月薪：5000-9000元/月 
工作地点：天津-北辰区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：5人
职位类别：汽车销售
**********
岗位职责：
1、 认真贯彻公司的销售政策，在展厅经理及销售组长的领导下，组织开展整车销售业务。
2、 严格执行公司各项规章制度（考勤、展车、6S、整车出入库、精品出库、按揭办理、保险、上牌），及风行汽车的接待流程、交车流程。
3、 负责销售统计及信息反馈。确保数据的准确性、及时性
4、 对客户满意度负责，端正工作态度和服务态度、提高销售能力和销售质量。
5、 积极参加各项培训，提高自身的专业技能和综合素养。
6、 配合公司开展的外展、外拓工作。
7、 完成领导交办的其他工作。
 任职要求：
1、大专以上学历，有销售经验者优先；
2、吃苦耐劳，抗压能力强；
3、有较强的团队精神；
4、有C1汽车驾驶资格证；

福利待遇：
1、福利完善：享受养老保险、医疗保险、工伤保险、失业保险、生育保险、公积金、各种补贴；
2、提供有竞争力的薪资：底薪+提成；
3、工作环境舒适；
4、有无汽车销售经验均可，可接受应届毕业生。

如果你热爱汽车行业，拼搏向上，积极进取，欢迎加入我们！
  工作地址：
天津市北辰区铁东北路北方汽贸园C区1-6号风行汽车4S店
查看职位地图
**********
北京荣兴行汽车贸易有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
汽车/摩托车
公司主页：
null
公司地址：
北京市石景山区古城西路63号国际汽车贸易园区A区66号
**********
塘沽驻场AE(客户执行)
天津精锐传承广告有限公司
每年多次调薪五险一金年底双薪全勤奖餐补带薪年假员工旅游
**********
福利:
每年多次调薪
五险一金
年底双薪
全勤奖
餐补
带薪年假
员工旅游
**********
职位月薪：4000-5000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：广告客户主管
**********
说在前头：驻场AE，出于作息考虑，家住塘沽区优先，离生态城越近越好
找AE
即客户执行，又不止执行
有条理，能说会道，有耐心，能屈能伸
坦诚、灵活、注重细节
团队意识与组织能力并重
 你可以直爽，也可以圆滑，最好百变
始终认真，保持清醒，冷静对话
因为
沟通，就是你的生产力
通晓文案、设计、策略的团队中枢，就是你的未来
 随时欢迎聊聊未来

关于放假，节假日依法办事，标配双休、带薪年假，附带国内外公费旅游
关于吃喝，午饭补助，老城厢商圈方便订餐，不定期聚餐改善伙食
关于薪资，绝对行业领先，年底分红不在话下，带你任性带你飞
能者多得，一切好说。未尽事宜，见面聊。

关于实习生
你准备好赢取明天的筹码了吗？
如果你站在门外
常闻广告圈怪谈乱象
却无法抑制内心的好奇
我们准备了一份实习工作
释放你头脑中的幺蛾子
让那些扑火的念头
破茧成蝶，点石成金

邮箱：176124533@qq.com

工作地址：
塘沽区
查看职位地图
**********
天津精锐传承广告有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市南开区红旗路192号赢寰大厦2门602
**********
3D设计
天津林泉世纪实业集团有限公司
五险一金每年多次调薪餐补弹性工作节日福利
**********
福利:
五险一金
每年多次调薪
餐补
弹性工作
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津-和平区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：三维/3D设计/制作
**********
岗位职责：
1. 根据策划和设定，制作所需的3D资源，把握整体风格的前提下，根据项目进行3D场景建模；
2. 模型的贴图绘制和渲染出图，适当的后期处理；
3. 一些通用场景素材的收集制作和整理；
4. 能独立完成项目的创意设计，现场进行场地测量，包括制作CAD图，效果图、立体图、平面图等；
5. 熟知商业展示的结构工艺及运作流程，具有三维空间创意能力，综合设计能力强，并富有创造力；
6. 正确领略公司总体规划理念和客户意图并准确完整地表达呈现设计思想；
7. 负责展览展示、演出舞台的设计，控制材质、灯光、色彩的组合运用及整体效果搭配。

任职要求：
-从事过2年以上的展览展示、展厅、舞台美术等大型设计，有室内外空间设计（工装、家装）经验；
-熟练掌握CAD和3D建模设计，熟悉AutoCAD、3DMAX、Photoshop等设计工具的使用；
-能够与项目人员保持良好的沟通协作，共同策划设计，成功服务客户；
-能独立完成展会、舞台设计方案，了解展览材料及舞台施工结构细节。

工作地址：
天津市和平区汉口西道格普澜轩底商9号香港站
**********
天津林泉世纪实业集团有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
广告/会展/公关
公司主页：
//lqsjzw.8v8.cn/
公司地址：
天津市东丽区华明工业园区华丰路6号A座3号楼B6015室
**********
图书印务
天津凤凰空间文化传媒有限公司
五险一金绩效奖金全勤奖交通补助餐补通讯补贴带薪年假定期体检
**********
福利:
五险一金
绩效奖金
全勤奖
交通补助
餐补
通讯补贴
带薪年假
定期体检
**********
职位月薪：3000-4000元/月 
工作地点：天津-南开区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：印刷排版/制版
**********
岗位职责：
1.图书工价核算及印厂印费结算。
2.图书进展及质量跟踪。
3.ERP系统数据录入。
4.给编辑提供装帧设计意见。
 任职要求：
1.熟悉图书出版流程，懂得图书成本核算，一年以上相关工作经验。
2.熟悉印前、印后工作流程，了解印刷装帧工艺
3.沟通表达能力良好，认真细致，工作稳定，忠诚度高。nan士有限

工作地址：
天津市南开区大学道199号天铁科贸大厦
查看职位地图
**********
天津凤凰空间文化传媒有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
媒体/出版/影视/文化传播
公司地址：
天津市南开区大学道199号天铁科贸大厦5F
**********
（上九下六 双休）电气设计助理/学徒
天津望京玻璃制品贸易有限公司
五险一金年底双薪绩效奖金加班补助包住餐补员工旅游节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
加班补助
包住
餐补
员工旅游
节日福利
**********
职位月薪：3000-6000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：电气设计
**********
任职资格：
1、有无经验均可，无专业限制；
2、接触过CAD、Office等计算机软件系统；
3、头脑灵活，思维活跃；
4、工作认真、细致、有责任心，具有团队合作精神及沟通协调能力；
5、学习能力强，适应性强，应变能力强。

福利待遇：社保、年休假、带薪培训（带员工带）、生日福利、生育礼金、过节福利、年度体检。
工作时间：
法定节假日休、上九下六   午休1小时
工作地址：
天津市南开
**********
天津望京玻璃制品贸易有限公司
公司规模：
500-999人
公司性质：
上市公司
公司行业：
贸易/进出口
公司地址：
天津市
**********
保洁员
天津精锐传承广告有限公司
**********
福利:
**********
职位月薪：1000元/月以下 
工作地点：天津
发布日期：最新
工作性质：兼职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：保洁
**********
1、年龄55岁以下，身体健康，品貌端正
2、工作时间，每天上午2小时；六日双休，节假日按照法定休息
3、月薪800
联系电话：27610067、15822074610
工作地址：
天津市南开区红旗路192号赢寰大厦2门602
查看职位地图
**********
天津精锐传承广告有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市南开区红旗路192号赢寰大厦2门602
**********
4S店销售经理（解放南路）
北京荣兴行汽车贸易有限公司
五险一金绩效奖金年终分红加班补助带薪年假员工旅游高温补贴节日福利
**********
福利:
五险一金
绩效奖金
年终分红
加班补助
带薪年假
员工旅游
高温补贴
节日福利
**********
职位月薪：8000-12000元/月 
工作地点：天津-河西区
发布日期：最新
工作性质：全职
工作经验：5-10年
最低学历：大专
招聘人数：1人
职位类别：4S店管理
**********
岗位职责：
全面负责解放南路4S店的销售管理：
1、负责市场调研和需求分析；
2、负责年度销售的预测，目标的制定及分解；
3、确定销售部门目标体系和销售配额；
4、制定销售计划和销售预算；
5、负责销售渠道和客户的管理；
6、组建销售队伍，培训销售人员；
7、评估销售业绩，建设销售团队。

任职资格：
1、专科及以上学历；
2、5年以上汽车销售行业工作经验，3年以上销售管理工作经验；
3、具有丰富的客户资源和客户关系者优先；
4、具备较强的市场分析、营销、推广能力和良好的人际沟通、协调能力，分析和解决问题的能力；
5、有较强的事业心，具备一定的领导能力。
 福利待遇：
1、福利完善：享受养老保险、医疗保险、工伤保险、失业保险、生育保险、公积金、各种补贴；
2、提供有竞争力的薪资；
3、良好的公司氛围，nice的老板，足够的发展空间。

如果你热爱汽车行业，拼搏向上，积极进取，欢迎加入我们！
工作地址：
河西区解放南路环渤海汽车城风行汽车4S店
查看职位地图
**********
北京荣兴行汽车贸易有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
汽车/摩托车
公司主页：
null
公司地址：
北京市石景山区古城西路63号国际汽车贸易园区A区66号
**********
电话销售专员（铁东路）
北京荣兴行汽车贸易有限公司
五险一金绩效奖金加班补助带薪年假员工旅游高温补贴节日福利
**********
福利:
五险一金
绩效奖金
加班补助
带薪年假
员工旅游
高温补贴
节日福利
**********
职位月薪：5000-7000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：汽车销售
**********
岗位职责：
(1)负责汽车4S店意向客户到店邀约；    
(2)负责公司网站（如有）营销信息、微博和微信的更新和维护；    
(3)在网电销经理的指导下，开展灵活的网电微营销活动；           
(4)负责收集和整理公司网站平台上意向客户线索，并邀约到店，转化成销售订单；   (5)对销售线索的跟进情况进行数据统计与整理，每周/月汇总报市场经理、网销经理、销售部。    

任职要求：
1、口齿灵利，有较强的沟通能力；
2、大专以上学历，有相关电话销售工作经验者优先；
3、熟练电脑办公软件操作，有团队合作精神；
4、能吃苦耐劳，有一定的抗压能力
 福利待遇：
1、福利完善：享受养老保险、医疗保险、工伤保险、失业保险、生育保险、公积金、各种补贴；
2、提供有竞争力的薪资：底薪+高提成；
3、工作环境舒适；
4、有无经验均可，可接收应届毕业生。
工作地址：
北辰区铁东北路北方汽贸园C区1-6号
查看职位地图
**********
北京荣兴行汽车贸易有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
汽车/摩托车
公司主页：
null
公司地址：
北京市石景山区古城西路63号国际汽车贸易园区A区66号
**********
4S店配件库管员
北京荣兴行汽车贸易有限公司
五险一金绩效奖金加班补助餐补采暖补贴
**********
福利:
五险一金
绩效奖金
加班补助
餐补
采暖补贴
**********
职位月薪：3000-6000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：汽车售后服务/客户服务
**********
岗位职责：
1、执行物资管理中与仓库有关的SOP，确保仓库作业顺利进行；
2、负责仓库日常物资的验收、入库、码放、保管、盘点、对账等工作；
3、负责保持仓内货品和环境的清洁、整齐和卫生工作；
4、负责相关单证的保管与存档；
5、仓库数据的统计、存档、帐务和系统数据的输入；
6、部门主管交办的其它事宜。

任职资格：
1、大专及以上学历优先；
2、1年以上相关领域实际业务操作经验优先；
3、熟悉仓库进出货操作流程，具备物资保管专业知识和技能；
4、熟悉电脑办公软件操作；
5、积极耐劳、责任心强、具有合作和创新精神。
6、能熟练驾驶汽车优先

福利待遇：
1、福利完善：享受养老保险、医疗保险、工伤保险、失业保险、生育保险、公积金、各种补贴；
2、提供有竞争力的薪资：底薪+提成；
3、工作环境舒适。

工作地址：
北辰区铁东北路北方汽贸园C区1-6号
查看职位地图
**********
北京荣兴行汽车贸易有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
汽车/摩托车
公司主页：
null
公司地址：
北京市石景山区古城西路63号国际汽车贸易园区A区66号
**********
淘宝客服广告类
天津唯克广告有限公司
创业公司全勤奖包住餐补
**********
福利:
创业公司
全勤奖
包住
餐补
**********
职位月薪：3000-5000元/月 
工作地点：天津-河东区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：2人
职位类别：客户代表
**********
公司提供住宿，发放餐补，设全勤奖，
工作满6个月可拿年终奖金，
工作满一年上五险，同时放节日福利
公司定期组织团队建设
工作时间：
早8:30-下午18:00，每周休息一天
工作内容：
1.淘宝客服，广告类产品
2.开单对接生产
3.追单对接客户
职位要求：
1.有淘宝客服经验者优先
2.熟练掌握OFFICE及聊天工具，打字熟练
3.要求会PS平面软件，公司提供培训
3.有强烈的服务和销售意识
4.熟练使用礼貌用语 有耐心
公司招募长期员工，薪资与工作职位和工作能力挂钩，每个岗位均
设置组长，总监职位，中层员工均从基层员工中选拔，提供员工阶
梯式职业发展空间。

工作地址：
天津市河东区居然之家旁
查看职位地图
**********
天津唯克广告有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市河东区居然之家
**********
土建工程师-恒大童世界（河北）
恒大旅游集团有限公司
五险一金年底双薪绩效奖金包吃包住带薪年假定期体检员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
包吃
包住
带薪年假
定期体检
员工旅游
**********
职位月薪：10000-15000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：10人
职位类别：土木/土建/结构工程师
**********
任职要求：
1、全日制统招本科及以上学历，工程类相关专业；
2、三年以上相关工作经验。

岗位职责:
负责恒大集团大型文旅项目沧州童世界工程现场管理工作，本岗位包吃包住。
工作地点：河北省沧州市南大港湿地公园景区（京津一小时生活圈）
项目情况：体量大（16000亩），业态多（主题乐园、会议会展中心、影视基地、商业中心、博物馆群、酒店群等几十个业态），开发周期8-10年。
沧州恒大童世界占地16000亩，总投资1000亿。恒大童世界是全球唯一的“全室内、全天候、全季节”大型主题乐园，面向2-15岁的少年儿童，以中国文化、中国历史、中国故事为核心内容，将打造出全球规模最大、档次最高、世界第一的童话神话主题乐园。

工作地址：
河北
**********
恒大旅游集团有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司地址：
广东省广州市天河区黄埔大道西78号恒大中心
**********
资金部经理
恒大旅游集团有限公司
五险一金包吃包住员工旅游节日福利
**********
福利:
五险一金
包吃
包住
员工旅游
节日福利
**********
职位月薪：10000-20000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：1人
职位类别：资产/资金管理
**********
工作地点：河北省沧州市南大港，不能接受者勿投。联系电话：孙女士 15128707118
任职要求：
第一学历统招本科及以上学历，五年以上工作经验，房地产行业优先
负责恒大集团大型文旅项目沧州童世界资金部管理工作，本岗位包吃包住。

项目情况：体量大（16000亩），业态多（主题乐园、会议会展中心、影视基地、商业中心、博物馆群、酒店群等几十个业态），开发周期8-10年。
恒大沧州童世界占地16000亩，总投资1000亿。恒大童世界是全球唯一的“全室内、全天候、全季节”大型主题乐园，面向2-15岁的少年儿童，以中国文化、中国历史、中国故事为核心内容，将打造出全球规模最大、档次最高、世界第一的童话神话主题乐园。
工作地点：河北沧州（能接受常驻沧州再进行简历投递，请勿重复投递）

工作地址：
河北
**********
恒大旅游集团有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司地址：
广东省广州市天河区黄埔大道西78号恒大中心
**********
人事经理
天九共享控股集团
五险一金绩效奖金交通补助餐补通讯补贴带薪年假弹性工作定期体检
**********
福利:
五险一金
绩效奖金
交通补助
餐补
通讯补贴
带薪年假
弹性工作
定期体检
**********
职位月薪：6001-8000元/月 
工作地点：天津-河北区
发布日期：最近
工作性质：全职
工作经验：3-5年
最低学历：不限
招聘人数：1人
职位类别：人力资源经理
**********
岗位职责：
1、 负责事业部人力资源管理工作，从业务角度出发，将集团的 HR 政策、制度、流程等在所属事业部落地实施与推动；
2、 负责所属事业部业务团队的招聘管理及招聘实施、招聘效果的评估等工作，保证招聘工作的顺利开展；
3、 集团幸福文化的宣导和传播，幸福关怀体系在事业部的落实推进工作；
4、 负责所属事业部员工录用、人事异动、HCM系统管理、考勤、日报、劳动合同、员工关系等人事管理相关工作，同时对地方子公司的人力工作进行指导、监督、检查。
5、 领导交办的人力资源相关工作
任职条件：
（1）本科及以上学历，人力资源专业；
（2）3年以上从事人力资源经验、对人力资源六大模块均有一定的经验；
（3）有人力资源招聘的实务操作经验，熟练掌握招聘流程与面试技巧；
（4）责任心强、敬业精神和团队合作意识、积极主动、工作严谨；
（5）具备良好沟通谈判能力，书面表达能力、思维敏捷，亲和力强；
（6）熟练使用EXCEL、PPT等办公软件。
工作地址：
天津市河北区进步道38号国银大厦A902
**********
天九共享控股集团
公司规模：
1000-9999人
公司性质：
民营
公司行业：
基金/证券/期货/投资
公司主页：
http://www.tjxfjt.com.cn
公司地址：
朝阳区北苑家园秋实路绣菊园7号
**********
采购部经理
恒大旅游集团有限公司
五险一金包吃包住员工旅游节日福利
**********
福利:
五险一金
包吃
包住
员工旅游
节日福利
**********
职位月薪：10000-20000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：1人
职位类别：采购经理/主管
**********
任职要求：
第一学历统招本科及以上学历，五年以上建筑采购工作经验，房地产行业优先
负责恒大集团大型文旅项目沧州童世界采购部管理工作，本岗位包吃包住。
工作地点：河北省沧州市南大港湿地公园景区（京津一小时生活圈）
项目情况：体量大（16000亩），业态多（主题乐园、会议会展中心、影视基地、商业中心、博物馆群、酒店群等几十个业态），开发周期8-10年。
恒大沧州童世界占地16000亩，总投资1000亿。恒大童世界是全球唯一的“全室内、全天候、全季节”大型主题乐园，面向2-15岁的少年儿童，以中国文化、中国历史、中国故事为核心内容，将打造出全球规模最大、档次最高、世界第一的童话神话主题乐园。
联系电话：13752360040（常女士）微信812453223
工作地点：河北沧州（能接受常驻沧州再进行简历投递，请勿重复投递）

工作地址：
河北
**********
恒大旅游集团有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司地址：
广东省广州市天河区黄埔大道西78号恒大中心
**********
销售总监
恒大旅游集团有限公司
五险一金包吃包住员工旅游节日福利
**********
福利:
五险一金
包吃
包住
员工旅游
节日福利
**********
职位月薪：10001-15000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：3人
职位类别：销售总监
**********
任职要求：
第一学历统招大专及以上学历毕业3年以上，3年以上房地产团队管理相关工作经验，精通房地产营销相关知识和技能，熟悉房地产营销的环节与流程，具备较强的业务领导力和团队领导力
工作地点：河北省沧州市南大港湿地公园景区（京津一小时生活圈）
项目情况：体量大（16000亩），业态多（主题乐园、会议会展中心、影视基地、商业中心、博物馆群、酒店群等几十个业态），开发周期8-10年。
恒大沧州童世界占地16000亩，总投资1000亿。恒大童世界是全球唯一的“全室内、全天候、全季节”大型主题乐园，面向2-15岁的少年儿童，以中国文化、中国历史、中国故事为核心内容，将打造出全球规模最大、档次最高、世界第一的童话神话主题乐园。
联系电话：13752360040（常女士）
工作地点：北京、天津、石家庄、沧州


工作地址：
河北沧州
**********
恒大旅游集团有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司地址：
广东省广州市天河区黄埔大道西78号恒大中心
**********
建筑设计师
恒大旅游集团有限公司
五险一金年底双薪绩效奖金包吃包住带薪年假定期体检员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
包吃
包住
带薪年假
定期体检
员工旅游
**********
职位月薪：10000-20000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：2人
职位类别：其他
**********
任职要求：
1、建筑学、环境艺术类相关专业统招本科及以上学历；
2、5年以上相关工作经验。
岗位职责:
负责恒大集团大型文旅项目沧州童世界建筑设计管理工作，本岗位包吃包住。
工作地点：河北省沧州市南大港湿地公园景区（京津一小时生活圈）
项目情况：省级重点项目，体量大（16000亩），业态多（主题乐园、会议会展中心、影视基地、商业中心、博物馆群、酒店群等几十个业态），开发周期8-10年。
恒大沧州童世界占地16000亩，总投资1000亿。恒大童世界是全球唯一的“全室内、全天候、全季节”大型主题乐园，面向2-15岁的少年儿童，以中国文化、中国历史、中国故事为核心内容，将打造出全球规模最大、档次最高、世界第一的童话神话主题乐园。

工作地址：
河北省沧州市南大港
**********
恒大旅游集团有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司地址：
广东省广州市天河区黄埔大道西78号恒大中心
**********
机电工程师-恒大童世界（沧州）
恒大旅游集团有限公司
五险一金年底双薪绩效奖金包吃包住带薪年假定期体检员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
包吃
包住
带薪年假
定期体检
员工旅游
**********
职位月薪：10000-15000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：10人
职位类别：智能大厦/布线/弱电/安防
**********
任职要求：
1、全日制统招本科及以上学历，机电相关专业；
2、三年以上相关工作经验。

岗位职责:
负责恒大集团大型文旅项目沧州童世界工程现场管理工作，本岗位包吃包住。
工作地点：河北省沧州市南大港湿地公园景区（京津一小时生活圈）
项目情况：体量大（16000亩），业态多（主题乐园、会议会展中心、影视基地、商业中心、博物馆群、酒店群等几十个业态），开发周期8-10年。
沧州恒大童世界占地16000亩，总投资1000亿。恒大童世界是全球唯一的“全室内、全天候、全季节”大型主题乐园，面向2-15岁的少年儿童，以中国文化、中国历史、中国故事为核心内容，将打造出全球规模最大、档次最高、世界第一的童话神话主题乐园。

工作地址：
河北
**********
恒大旅游集团有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司地址：
广东省广州市天河区黄埔大道西78号恒大中心
**********
电气设计师
恒大旅游集团有限公司
五险一金年底双薪绩效奖金包吃包住带薪年假定期体检员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
包吃
包住
带薪年假
定期体检
员工旅游
**********
职位月薪：10000-20000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：2人
职位类别：其他
**********
任职要求：
1、电气、智能化类相关专业统招本科及以上学历；
2、5年以上相关工作经验。
岗位职责:
负责恒大集团大型文旅项目沧州童世界电气设计管理工作，本岗位包吃包住。
工作地点：河北省沧州市南大港湿地公园景区（京津一小时生活圈）
项目情况：省级重点项目，体量大（16000亩），业态多（主题乐园、会议会展中心、影视基地、商业中心、博物馆群、酒店群等几十个业态），开发周期8-10年。
恒大沧州童世界占地16000亩，总投资1000亿。恒大童世界是全球唯一的“全室内、全天候、全季节”大型主题乐园，面向2-15岁的少年儿童，以中国文化、中国历史、中国故事为核心内容，将打造出全球规模最大、档次最高、世界第一的童话神话主题乐园。

工作地址：
河北省沧州市南大港
**********
恒大旅游集团有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司地址：
广东省广州市天河区黄埔大道西78号恒大中心
**********
行政主管
恒大旅游集团有限公司
五险一金绩效奖金包吃包住员工旅游节日福利
**********
福利:
五险一金
绩效奖金
包吃
包住
员工旅游
节日福利
**********
职位月薪：8000-15000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：1人
职位类别：行政经理/主管/办公室主任
**********
工作地点：河北省沧州市南大港湿地公园景区（京津一小时生活圈），不能接受者勿投。联系电话：孙女士 15128707118
任职要求：
1、行政类类相关专业统招本科及以上学历；
2、全日制本科3年以上相关工作经验；
岗位职责:
负责恒大集团大型文旅项目沧州童世界行政类工作，本岗位包吃包住。双休，五险一金。

项目情况：体量大（16000亩），业态多（主题乐园、会议会展中心、影视基地、商业中心、博物馆群、酒店群等几十个业态），开发周期8-10年。
恒大沧州童世界占地16000亩，总投资1000亿。恒大童世界是全球唯一的“全室内、全天候、全季节”大型主题乐园，面向2-15岁的少年儿童，以中国文化、中国历史、中国故事为核心内容，将打造出全球规模最大、档次最高、世界第一的童话神话主题乐园。
  工作地址：
广东省广州市天河区黄埔大道西78号恒大中心
**********
恒大旅游集团有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司地址：
广东省广州市天河区黄埔大道西78号恒大中心
**********
装修设计师
恒大旅游集团有限公司
五险一金年底双薪绩效奖金包吃包住带薪年假定期体检员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
包吃
包住
带薪年假
定期体检
员工旅游
**********
职位月薪：10000-20000元/月 
工作地点：天津
发布日期：2018-02-05 18:43:53
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：5人
职位类别：其他
**********
任职要求：
1、土木工程、设计类相关专业统招本科及以上学历；
2、5年以上相关工作经验。
岗位职责:
负责恒大集团大型文旅项目沧州童世界装修设计管理工作，本岗位包吃包住。
工作地点：河北省沧州市南大港湿地公园景区（京津一小时生活圈）
项目情况：省级重点项目，体量大（16000亩），业态多（主题乐园、会议会展中心、影视基地、商业中心、博物馆群、酒店群等几十个业态），开发周期8-10年。
恒大沧州童世界占地16000亩，总投资1000亿。恒大童世界是全球唯一的“全室内、全天候、全季节”大型主题乐园，面向2-15岁的少年儿童，以中国文化、中国历史、中国故事为核心内容，将打造出全球规模最大、档次最高、世界第一的童话神话主题乐园。

工作地址：
沧州南大港
查看职位地图
**********
恒大旅游集团有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司地址：
广东省广州市天河区黄埔大道西78号恒大中心
**********
给排水/暖通设计师
恒大旅游集团有限公司
五险一金年底双薪绩效奖金包吃包住带薪年假定期体检员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
包吃
包住
带薪年假
定期体检
员工旅游
**********
职位月薪：10000-20000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：10人
职位类别：其他
**********
任职要求：
1、给水排水、暖通类相关专业统招本科及以上学历；
2、5年以上相关工作经验。
岗位职责:
负责恒大集团大型文旅项目沧州童世界结给排水/暖通计管理工作，本岗位包吃包住。
工作地点：河北省沧州市南大港湿地公园景区（京津一小时生活圈）
项目情况：省级重点项目，体量大（16000亩），业态多（主题乐园、会议会展中心、影视基地、商业中心、博物馆群、酒店群等几十个业态），开发周期8-10年。
恒大沧州童世界占地16000亩，总投资1000亿。恒大童世界是全球唯一的“全室内、全天候、全季节”大型主题乐园，面向2-15岁的少年儿童，以中国文化、中国历史、中国故事为核心内容，将打造出全球规模最大、档次最高、世界第一的童话神话主题乐园。

工作地址：
沧州南大港
**********
恒大旅游集团有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司地址：
广东省广州市天河区黄埔大道西78号恒大中心
**********
装修监理工程师-恒大童世界（河北）
恒大旅游集团有限公司
五险一金年底双薪绩效奖金包吃包住带薪年假定期体检员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
包吃
包住
带薪年假
定期体检
员工旅游
**********
职位月薪：10000-15000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：10人
职位类别：室内装潢设计
**********
任职要求：
1、全日制统招本科及以上学历，土建、艺术类相关专业；
2、三年以上相关工作经验。

岗位职责:
负责恒大集团大型文旅项目沧州童世界工程现场管理工作，本岗位包吃包住。
工作地点：河北省沧州市南大港湿地公园景区（京津一小时生活圈）
项目情况：体量大（16000亩），业态多（主题乐园、会议会展中心、影视基地、商业中心、博物馆群、酒店群等几十个业态），开发周期8-10年。
沧州恒大童世界占地16000亩，总投资1000亿。恒大童世界是全球唯一的“全室内、全天候、全季节”大型主题乐园，面向2-15岁的少年儿童，以中国文化、中国历史、中国故事为核心内容，将打造出全球规模最大、档次最高、世界第一的童话神话主题乐园。

工作地址：
河北
**********
恒大旅游集团有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司地址：
广东省广州市天河区黄埔大道西78号恒大中心
**********
园林工程师-恒大童世界（河北）
恒大旅游集团有限公司
五险一金年底双薪绩效奖金包吃包住带薪年假定期体检员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
包吃
包住
带薪年假
定期体检
员工旅游
**********
职位月薪：10000-15000元/月 
工作地点：天津
发布日期：0002-01-01 00:00:00
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：10人
职位类别：市政工程师
**********
任职要求：
1、全日制统招本科及以上学历，园林相关专业；
2、三年以上相关工作经验。

岗位职责:
负责恒大集团大型文旅项目沧州童世界工程现场管理工作，本岗位包吃包住。
工作地点：河北省沧州市南大港湿地公园景区（京津一小时生活圈）
项目情况：体量大（16000亩），业态多（主题乐园、会议会展中心、影视基地、商业中心、博物馆群、酒店群等几十个业态），开发周期8-10年。
沧州恒大童世界占地16000亩，总投资1000亿。恒大童世界是全球唯一的“全室内、全天候、全季节”大型主题乐园，面向2-15岁的少年儿童，以中国文化、中国历史、中国故事为核心内容，将打造出全球规模最大、档次最高、世界第一的童话神话主题乐园。

工作地址：
河北
**********
恒大旅游集团有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司地址：
广东省广州市天河区黄埔大道西78号恒大中心
**********
测量工程师-恒大童世界（河北）
恒大旅游集团有限公司
五险一金年底双薪绩效奖金包吃包住带薪年假定期体检员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
包吃
包住
带薪年假
定期体检
员工旅游
**********
职位月薪：10000-15000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：10人
职位类别：建筑工程测绘/测量
**********
任职要求：
1、全日制统招本科及以上学历，测量相关专业；
2、三年以上相关工作经验。

岗位职责:
负责恒大集团大型文旅项目沧州童世界工程现场管理工作，本岗位包吃包住。
工作地点：河北省沧州市南大港湿地公园景区（京津一小时生活圈）
项目情况：体量大（16000亩），业态多（主题乐园、会议会展中心、影视基地、商业中心、博物馆群、酒店群等几十个业态），开发周期8-10年。
沧州恒大童世界占地16000亩，总投资1000亿。恒大童世界是全球唯一的“全室内、全天候、全季节”大型主题乐园，面向2-15岁的少年儿童，以中国文化、中国历史、中国故事为核心内容，将打造出全球规模最大、档次最高、世界第一的童话神话主题乐园。

工作地址：
河北
**********
恒大旅游集团有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司地址：
广东省广州市天河区黄埔大道西78号恒大中心
**********
结构设计师
恒大旅游集团有限公司
五险一金年底双薪绩效奖金包吃包住带薪年假定期体检员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
包吃
包住
带薪年假
定期体检
员工旅游
**********
职位月薪：10000-20000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：2人
职位类别：其他
**********
任职要求：
1、土木工程类相关专业统招本科及以上学历；
2、5年以上相关工作经验。
岗位职责:
负责恒大集团大型文旅项目沧州童世界结构设计管理工作，本岗位包吃包住。
工作地点：河北省沧州市南大港湿地公园景区（京津一小时生活圈）
项目情况：省级重点项目，体量大（16000亩），业态多（主题乐园、会议会展中心、影视基地、商业中心、博物馆群、酒店群等几十个业态），开发周期8-10年。
恒大沧州童世界占地16000亩，总投资1000亿。恒大童世界是全球唯一的“全室内、全天候、全季节”大型主题乐园，面向2-15岁的少年儿童，以中国文化、中国历史、中国故事为核心内容，将打造出全球规模最大、档次最高、世界第一的童话神话主题乐园。

工作地址：
河北省沧州市南大港
**********
恒大旅游集团有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司地址：
广东省广州市天河区黄埔大道西78号恒大中心
**********
给排水工程师-恒大童世界（河北）
恒大旅游集团有限公司
五险一金年底双薪绩效奖金包吃包住带薪年假定期体检员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
包吃
包住
带薪年假
定期体检
员工旅游
**********
职位月薪：10000-15000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：10人
职位类别：给排水/暖通/空调工程
**********
任职要求：
1、全日制统招本科及以上学历，给排水相关专业；
2、三年以上相关工作经验。

岗位职责:
负责恒大集团大型文旅项目沧州童世界工程现场管理工作，本岗位包吃包住。
工作地点：河北省沧州市南大港湿地公园景区（京津一小时生活圈）
项目情况：体量大（16000亩），业态多（主题乐园、会议会展中心、影视基地、商业中心、博物馆群、酒店群等几十个业态），开发周期8-10年。
沧州恒大童世界占地16000亩，总投资1000亿。恒大童世界是全球唯一的“全室内、全天候、全季节”大型主题乐园，面向2-15岁的少年儿童，以中国文化、中国历史、中国故事为核心内容，将打造出全球规模最大、档次最高、世界第一的童话神话主题乐园。

工作地址：
河北
**********
恒大旅游集团有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司地址：
广东省广州市天河区黄埔大道西78号恒大中心
**********
人力资源主管
恒大旅游集团有限公司
五险一金绩效奖金包吃包住员工旅游节日福利
**********
福利:
五险一金
绩效奖金
包吃
包住
员工旅游
节日福利
**********
职位月薪：8000-15000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：1人
职位类别：人力资源主管
**********
工作地点：河北省沧州市南大港湿地公园景区（京津一小时生活圈），不能接受者勿投。联系电话：孙女士 15128707118
任职要求：
1、人力资源类相关专业统招本科及以上学历；
2、全日制本科3年以上相关工作经验；
岗位职责:
负责恒大集团大型文旅项目沧州童世界人力资源工作，本岗位包吃包住。双休，五险一金。

项目情况：体量大（16000亩），业态多（主题乐园、会议会展中心、影视基地、商业中心、博物馆群、酒店群等几十个业态），开发周期8-10年。
恒大沧州童世界占地16000亩，总投资1000亿。恒大童世界是全球唯一的“全室内、全天候、全季节”大型主题乐园，面向2-15岁的少年儿童，以中国文化、中国历史、中国故事为核心内容，将打造出全球规模最大、档次最高、世界第一的童话神话主题乐园。
  工作地址：
广东省广州市天河区黄埔大道西78号恒大中心
**********
恒大旅游集团有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司地址：
广东省广州市天河区黄埔大道西78号恒大中心
**********
电气工程师-恒大童世界（河北）
恒大旅游集团有限公司
五险一金年底双薪绩效奖金包吃包住带薪年假定期体检员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
包吃
包住
带薪年假
定期体检
员工旅游
**********
职位月薪：10000-15000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：10人
职位类别：智能大厦/布线/弱电/安防
**********
任职要求：
1、全日制统招本科及以上学历，电气类相关专业；
2、三年以上相关工作经验。

岗位职责:
负责恒大集团大型文旅项目沧州童世界工程现场管理工作，本岗位包吃包住。
工作地点：河北省沧州市南大港湿地公园景区（京津一小时生活圈）
项目情况：体量大（16000亩），业态多（主题乐园、会议会展中心、影视基地、商业中心、博物馆群、酒店群等几十个业态），开发周期8-10年。
沧州恒大童世界占地16000亩，总投资1000亿。恒大童世界是全球唯一的“全室内、全天候、全季节”大型主题乐园，面向2-15岁的少年儿童，以中国文化、中国历史、中国故事为核心内容，将打造出全球规模最大、档次最高、世界第一的童话神话主题乐园。

工作地址：
河北
**********
恒大旅游集团有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司地址：
广东省广州市天河区黄埔大道西78号恒大中心
**********
造价工程师
恒大旅游集团有限公司
五险一金包吃包住员工旅游节日福利
**********
福利:
五险一金
包吃
包住
员工旅游
节日福利
**********
职位月薪：10001-15000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：5-10年
最低学历：大专
招聘人数：10人
职位类别：工程造价/预结算
**********
任职要求：
1、工程造价、工程管理类相关专业第一学历统招专科及以上；
2、3年以上相关工作经验；
岗位职责:
负责恒大集团大型文旅项目沧州童世界成本管理工作，本岗位包吃包住。
工作地点：河北省沧州市南大港湿地公园景区（京津一小时生活圈）
项目情况：体量大（16000亩），业态多（主题乐园、会议会展中心、影视基地、商业中心、博物馆群、酒店群等几十个业态），开发周期8-10年。
恒大沧州童世界占地16000亩，总投资1000亿。恒大童世界是全球唯一的“全室内、全天候、全季节”大型主题乐园，面向2-15岁的少年儿童，以中国文化、中国历史、中国故事为核心内容，将打造出全球规模最大、档次最高、世界第一的童话神话主题乐园。
联系电话：13752360040（常女士）
工作地点：河北沧州（能接受常驻沧州再进行简历投递，请勿重复投递）

工作地址：
河北
**********
恒大旅游集团有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司地址：
广东省广州市天河区黄埔大道西78号恒大中心
**********
合同管理部经理
恒大旅游集团有限公司
五险一金包吃包住员工旅游节日福利
**********
福利:
五险一金
包吃
包住
员工旅游
节日福利
**********
职位月薪：15000-25000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：1人
职位类别：法务经理/主管
**********
任职要求：
第一学历统招本科及以上学历，5年以上工作经验，房地产行业优先
工作地点：河北省沧州市南大港湿地公园景区（京津一小时生活圈）
项目情况：体量大（16000亩），业态多（主题乐园、会议会展中心、影视基地、商业中心、博物馆群、酒店群等几十个业态），开发周期8-10年。
恒大沧州童世界占地16000亩，总投资1000亿。恒大童世界是全球唯一的“全室内、全天候、全季节”大型主题乐园，面向2-15岁的少年儿童，以中国文化、中国历史、中国故事为核心内容，将打造出全球规模最大、档次最高、世界第一的童话神话主题乐园。
联系电话：13752360040（常女士）微信812453223
工作地点：河北沧州（能接受常驻沧州再进行简历投递，请勿重复投递）

工作地址：
河北
**********
恒大旅游集团有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司地址：
广东省广州市天河区黄埔大道西78号恒大中心
**********
工程机械销售（天津）J10382
铁甲
五险一金年底双薪绩效奖金年终分红交通补助通讯补贴
**********
福利:
五险一金
年底双薪
绩效奖金
年终分红
交通补助
通讯补贴
**********
职位月薪：10001-15000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：不限
招聘人数：999人
职位类别：区域销售经理/主管
**********
工作职责：
1、发展及维护当地工程机械市场目标客户；
2、全程用心服务买卖双方用户，协助其在铁甲二手机平台交易二手设备；
3、利用铁甲二手机平台上传及认证设备；
4、配合好其他部门同事工作，如地推、检测人员工作；
5、可能涉及组织当地甲友聚会、管理门店等工作；
6、省总安排的其他工作。

任职资格：
1、有车有电脑；
2、过往经历具有良好销售业绩，有工程机械行业销售经验者优先考虑；
3、在同一家公司服务超过3年；
4、有较强的亲和力、沟通能力，善于维护与客户的良好关系；
5、品行端正，吃苦耐劳，具有团队合作精神；
6、能熟练使用excel、word、ppt等日常办公软件，对互联网行业有一定的了解；
7、抗压能力强，能接受互联网公司快节奏的工作方式。
工作地址：
天津及周边
**********
铁甲
公司规模：
500-999人
公司性质：
合资
公司行业：
互联网/电子商务
公司主页：
铁甲二手机 ｜ www.tiebaobei.com;铁甲网 | www. cehome.com;铁甲论坛| bbs.cehome.com
公司地址：
北京市朝阳区麦子店街39号部落方舟2层
查看公司地图
**********
园林设计师
恒大旅游集团有限公司
五险一金年底双薪绩效奖金包吃包住带薪年假定期体检员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
包吃
包住
带薪年假
定期体检
员工旅游
**********
职位月薪：10000-20000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：5人
职位类别：园林景观设计师
**********
任职要求：
1、土木工程类、园林景观类相关专业统招本科及以上学历；
2、5年以上相关工作经验。
岗位职责:
负责恒大集团大型文旅项目沧州童世界园林设计管理工作，本岗位包吃包住。
工作地点：河北省沧州市南大港湿地公园景区（京津一小时生活圈）
项目情况：省级重点项目，体量大（16000亩），业态多（主题乐园、会议会展中心、影视基地、商业中心、博物馆群、酒店群等几十个业态），开发周期8-10年。
恒大沧州童世界占地16000亩，总投资1000亿。恒大童世界是全球唯一的“全室内、全天候、全季节”大型主题乐园，面向2-15岁的少年儿童，以中国文化、中国历史、中国故事为核心内容，将打造出全球规模最大、档次最高、世界第一的童话神话主题乐园。

工作地址：
沧州南大港
**********
恒大旅游集团有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司地址：
广东省广州市天河区黄埔大道西78号恒大中心
**********
置业顾问
恒大旅游集团有限公司
五险一金包吃包住员工旅游节日福利
**********
福利:
五险一金
包吃
包住
员工旅游
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：40人
职位类别：房地产销售/置业顾问
**********
学历不限，有1年以上房地产销售经验，近一年房地产销售平均业绩前5名的优先
工作地点：河北省沧州市南大港湿地公园景区（京津一小时生活圈）
项目情况：体量大（16000亩），业态多（主题乐园、会议会展中心、影视基地、商业中心、博物馆群、酒店群等几十个业态），开发周期8-10年。
恒大沧州童世界占地16000亩，总投资1000亿。恒大童世界是全球唯一的“全室内、全天候、全季节”大型主题乐园，面向2-15岁的少年儿童，以中国文化、中国历史、中国故事为核心内容，将打造出全球规模最大、档次最高、世界第一的童话神话主题乐园。
联系电话：13752360040（常女士）
工作地点：北京、天津、石家庄、沧州

工作地址：
河北沧州
**********
恒大旅游集团有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司地址：
广东省广州市天河区黄埔大道西78号恒大中心
**********
室内设计师
恒大旅游集团有限公司
五险一金年底双薪绩效奖金包吃包住带薪年假定期体检员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
包吃
包住
带薪年假
定期体检
员工旅游
**********
职位月薪：10000-20000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：2人
职位类别：其他
**********
任职要求：
1、美术、室内设计类相关专业统招本科及以上学历；
2、5年以上相关工作经验。
岗位职责:
负责恒大集团大型文旅项目沧州童世界软装设计管理工作，本岗位包吃包住。
工作地点：河北省沧州市南大港湿地公园景区（京津一小时生活圈）
项目情况：省级重点项目，体量大（16000亩），业态多（主题乐园、会议会展中心、影视基地、商业中心、博物馆群、酒店群等几十个业态），开发周期8-10年。
恒大沧州童世界占地16000亩，总投资1000亿。恒大童世界是全球唯一的“全室内、全天候、全季节”大型主题乐园，面向2-15岁的少年儿童，以中国文化、中国历史、中国故事为核心内容，将打造出全球规模最大、档次最高、世界第一的童话神话主题乐园。

工作地址：
河北省沧州市南大港
**********
恒大旅游集团有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司地址：
广东省广州市天河区黄埔大道西78号恒大中心
**********
渠道经理
恒大旅游集团有限公司
五险一金包吃包住员工旅游节日福利
**********
福利:
五险一金
包吃
包住
员工旅游
节日福利
**********
职位月薪：8001-10000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：5人
职位类别：渠道/分销经理/主管
**********
任职要求：
统招大专及以上学历，3年以上地产行业渠道管理工作经验，具有项目外拓行销，电call，目标区域客户深度挖掘等经验，有大型文旅项目渠道管理者经验者优先
工作地点：河北省沧州市南大港湿地公园景区（京津一小时生活圈）
项目情况：体量大（16000亩），业态多（主题乐园、会议会展中心、影视基地、商业中心、博物馆群、酒店群等几十个业态），开发周期8-10年。
恒大沧州童世界占地16000亩，总投资1000亿。恒大童世界是全球唯一的“全室内、全天候、全季节”大型主题乐园，面向2-15岁的少年儿童，以中国文化、中国历史、中国故事为核心内容，将打造出全球规模最大、档次最高、世界第一的童话神话主题乐园。
联系电话：13752360040（常女士）
工作地点：北京、天津、石家庄、沧州

工作地址：
河北沧州
**********
恒大旅游集团有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司地址：
广东省广州市天河区黄埔大道西78号恒大中心
**********
开发报建岗-恒大童世界（河北）
恒大旅游集团有限公司
五险一金年底双薪绩效奖金包吃包住带薪年假定期体检员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
包吃
包住
带薪年假
定期体检
员工旅游
**********
职位月薪：8000-15000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：1人
职位类别：房地产项目开发报建
**********
任职要求：
1、全日制统招本科及以上学历，土地资源管理等相关专业；
2、三年以上相关工作经验，有完整单项目开发报建管理经历；
3、形象气质佳；
4、有驾照会开车
5、联系微信：83860518

岗位职责:
负责恒大集团大型文旅项目沧州童世界工程开发报建管理工作，本岗位包吃包住。
工作地点：河北省沧州市南大港湿地公园景区（京津一小时生活圈）
项目情况：体量大（16000亩），业态多（主题乐园、会议会展中心、影视基地、商业中心、博物馆群、酒店群等几十个业态），开发周期8-10年。
沧州恒大童世界占地16000亩，总投资1000亿。恒大童世界是全球唯一的“全室内、全天候、全季节”大型主题乐园，面向2-15岁的少年儿童，以中国文化、中国历史、中国故事为核心内容，将打造出全球规模最大、档次最高、世界第一的童话神话主题乐园。

工作地址：
河北
**********
恒大旅游集团有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司地址：
广东省广州市天河区黄埔大道西78号恒大中心
**********
销售总监无责底薪8400元+提成+五险一金双休
天九共享控股集团
五险一金绩效奖金交通补助餐补通讯补贴带薪年假弹性工作定期体检
**********
福利:
五险一金
绩效奖金
交通补助
餐补
通讯补贴
带薪年假
弹性工作
定期体检
**********
职位月薪：8001-10000元/月 
工作地点：天津-河北区
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：5人
职位类别：销售总监
**********
岗位职责：
1、根据公司的战略计划，形成相应的项目合作策略，并确保有效执行；
2、针对天津以及周边地区商协会洽谈合作项目；
3、协助完成本团队人员的招募与甄选、辅导与管理；
4、与优质目标企业建立联系，不定时推送我公司合作企业甄选目录；
5、协助组织及配合市场部开展各类营销活动；
6、完成工作报告及相关的业务汇报工作。
任职要求：
专科以上文凭；
1、良好的个人职业形象、为人正直诚信，良好的人际关系能力与学习能力，有高端客户服务经验，能承受工作压力，绝对的执行力；
2、具备自我约束、激励并勇于承担、完成目标责任的能力，能在一定的压力下胜任工作；
3、诚实守信，为人谦虚、勤奋努力，具有高度的团队合作精神和高度的工作热情；
4、有强烈的创业意识和创新精神，愿与公司一同成长。
福利待遇：
1、岗前培训，入职后不定期提升性培训，实现提升你的个人价值；
2、基本工资+绩效提成+补贴+年终奖金（待遇可视能力面议）食、宿、交通、电话补助齐全。天津市作为销售岗位最高基础薪资。
3、五险一金（养老、失业、工伤、医疗、生育+加天津市住房公积金）让您的家人放心
4、国家法定假日公休，双休日+每天七小时制工作时间，带薪休假（年休假、产假、婚假、丧假等有薪休假）
5、国内外旅游（公司提供国内外旅游外派培训的机会）
6、良好的晋升机制；
7、不定期户外拓展培训
8、同行业极具竞争力的佣金提成以及年终奖励机制。
地址：天津市河北区进步道38号国银大厦A901-902
工作地址：
天津市河北区进步道38号国银大厦A901-902
**********
天九共享控股集团
公司规模：
1000-9999人
公司性质：
民营
公司行业：
基金/证券/期货/投资
公司主页：
http://www.tjxfjt.com.cn
公司地址：
朝阳区北苑家园秋实路绣菊园7号
**********
总经理秘书
天九共享控股集团
五险一金绩效奖金交通补助餐补通讯补贴带薪年假弹性工作定期体检
**********
福利:
五险一金
绩效奖金
交通补助
餐补
通讯补贴
带薪年假
弹性工作
定期体检
**********
职位月薪：6001-8000元/月 
工作地点：天津-河北区
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：2人
职位类别：助理/秘书/文员
**********
岗位职责：
岗位职责：
1、总经理办公室成员。
2、协助总经理做好企业家俱乐部（天九平台共享会）的本地区会员会籍管理工作：含会员档案管理、会员微信群管理等。
3、在总经理授权下，做好企业家俱乐部各种活动的内容策划、组织、主持、领队工作。4、陪同总经理出席和处理各类商务活动、外联活动、政府关系等。
5、在总经理授权下，做好office的行政管理工作：8S管理、行政采购管理、会议管理、团队文体活动策划与组织等。
6、协助总经理，对接集团总部各级领导的秘书，做好管理信息的搜集、传达、规整、服务工作，确保总经理及时获取有效信息。
胜任资格：
1、形象气质佳，应聘者请附生活照一张。
2、有各类企业家活动策划和主持经验／特长者优先：沙龙、座谈会、大型论坛活动、休闲旅游活动、头脑风暴活动、游学培训活动等。
3、优秀的职业素养、职业礼仪、行动力、学习力、抗压力。
4、善良、正直、热情、团队精神，是我们对该岗位伙伴的希望。
工作地址：
天津市河北区进步道38号国银大厦A902
**********
天九共享控股集团
公司规模：
1000-9999人
公司性质：
民营
公司行业：
基金/证券/期货/投资
公司主页：
http://www.tjxfjt.com.cn
公司地址：
朝阳区北苑家园秋实路绣菊园7号
**********
资料员（设计部）
恒大旅游集团有限公司
五险一金年底双薪绩效奖金包吃包住带薪年假定期体检员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
包吃
包住
带薪年假
定期体检
员工旅游
**********
职位月薪：4001-6000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：2人
职位类别：其他
**********
工作职责：
1、负责收集,编制设计施工技术资料,随工程进度及时整理；
2、负责工程项目进度计划的编制和动态管理，项目进度的监督，汇报；
3、按规定对工程文件档案及技术图纸进行编目,建档,保管有关工程文件档案,技术图纸等资料。

任职资格：
1、专科及以上,基本掌握建筑工程技术或建筑制图等专业知识；
2、具备1年及以上工程项目计划运营管理及设计资料管理经验；
3、熟悉建筑工程资料管理规程,熟练使用电脑办公软件。

工作地址：
沧州南大港
**********
恒大旅游集团有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司地址：
广东省广州市天河区黄埔大道西78号恒大中心
**********
QYJXSD-营销顾问（天津）-车商业务
易车公司
五险一金交通补助补充医疗保险定期体检节日福利
**********
福利:
五险一金
交通补助
补充医疗保险
定期体检
节日福利
**********
职位月薪：8001-10000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：业务拓展专员/助理
**********
工作内容：
1、根据总部下达的开拓任务，制定所在区域的商家开拓计划；将计划合理分配至所在区域其他城市的地推人员，并监督其按要求执行，保证开拓任务的完成；
2、负责所在区域其他地推人员的产品使用、开拓话术等培训工作；
3、负责所在区域的商家客情维系，保证区域用户在平台的活跃度，促进线上成交；
4、负责所在区域的车源及寻车需求信息，进行用户间的交易匹配；
5、根据公司业务发展需要，完成金融、物流、精品、直营车源等任务指标。

任职资格：
1、专科及以上学历；
2、汽车行业3年以上销售工作经验，有二网经验的优先；
3、优秀的房地产行业经纪人经验也可考虑；
4、熟悉汽车厂商；
5、具有较强的语言表达及沟通能力。


工作地址：
天津市南开区黄河道与广开四马路交口西南侧格调中心814室
**********
易车公司
公司规模：
1000-9999人
公司性质：
外商独资
公司行业：
互联网/电子商务
公司主页：
www.yiche.com
公司地址：
北京市海淀区首体南路6号新世纪饭店写字楼6层
**********
策划专员
恒大旅游集团有限公司
五险一金包吃包住员工旅游节日福利
**********
福利:
五险一金
包吃
包住
员工旅游
节日福利
**********
职位月薪：8001-10000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：5人
职位类别：市场策划/企划专员/助理
**********
任职要求：
25～35岁，市场营销等相关专业，第一学历本科毕业3年以上，2年以上地产策划工作经验，全程参与过知名地产企业营销策划工作优先
工作地点：河北省沧州市南大港湿地公园景区（京津一小时生活圈）
项目情况：体量大（16000亩），业态多（主题乐园、会议会展中心、影视基地、商业中心、博物馆群、酒店群等几十个业态），开发周期8-10年。
恒大沧州童世界占地16000亩，总投资1000亿。恒大童世界是全球唯一的“全室内、全天候、全季节”大型主题乐园，面向2-15岁的少年儿童，以中国文化、中国历史、中国故事为核心内容，将打造出全球规模最大、档次最高、世界第一的童话神话主题乐园。
联系电话：13752360040（常女士）
工作地点：北京、天津、石家庄、沧州

工作地址：
河北沧州
**********
恒大旅游集团有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司地址：
广东省广州市天河区黄埔大道西78号恒大中心
**********
4500+行政助理（双休）五险一金
天津金珑基科技有限责任公司
五险一金年底双薪餐补带薪年假节日福利不加班
**********
福利:
五险一金
年底双薪
餐补
带薪年假
节日福利
不加班
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：3人
职位类别：行政专员/助理
**********
岗位职责：
1、协助执行公司的各项规章制度和维护工作秩序； 
2、负责公司员工的考勤管理； 
3、负责公司全体员工的后勤保障工作，包括发放办公用品、印制名片、办理餐卡、定水、定票、复印、邮寄等事务；   
4、完成上级安排的其他工作任务。
任职要求：
1、中年龄18-28岁，有无经验均可。
2、考虑塘沽工作（公司可提供住宿）。
3、做事认真、负责，有一定学习能力。
福利待遇：
【工作时间】周一至周五，朝九晚六，周末双休；
【薪酬】富有竞争力的薪酬水平和项目提成；
【奖金】绩效奖金、项目奖金、年终奖金；
【社保】五险一金：医疗、生育、工伤、失业、养老保险及住房公积金；
【公司福利】节日福利、加班补贴、餐补、公司聚餐、年会等，活动丰富；
【假期福利】享受国家规定的带薪年假，法定节假日；
【成长进步】人性化的学习管理制度、一对一的指定帮助，让员工快速融入新环境并成长！

工作地址：
天津塘沽新村街营口道泛华国际大厦
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
履约工程师
恒大旅游集团有限公司
五险一金包吃包住员工旅游节日福利
**********
福利:
五险一金
包吃
包住
员工旅游
节日福利
**********
职位月薪：10001-15000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：项目计划合约专员
**********
任职要求：
1、工民建或建筑工程等相关专业本科及以上学历，第一学历统招本科毕业3年以上         2、熟悉工程现场管理及合同履约过程的维权取证

工作地点：河北省沧州市南大港湿地公园景区（京津一小时生活圈）
项目情况：体量大（16000亩），业态多（主题乐园、会议会展中心、影视基地、商业中心、博物馆群、酒店群等几十个业态），开发周期8-10年。
恒大沧州童世界占地16000亩，总投资1000亿。恒大童世界是全球唯一的“全室内、全天候、全季节”大型主题乐园，面向2-15岁的少年儿童，以中国文化、中国历史、中国故事为核心内容，将打造出全球规模最大、档次最高、世界第一的童话神话主题乐园。
联系电话：13752360040（常女士）
工作地点：河北沧州（能接受常驻沧州再进行简历投递，请勿重复投递）

工作地址：
河北沧州
**********
恒大旅游集团有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司地址：
广东省广州市天河区黄埔大道西78号恒大中心
**********
文档管理员+双休
天津金珑基科技有限责任公司
五险一金加班补助餐补
**********
福利:
五险一金
加班补助
餐补
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：文档/资料管理
**********
岗位职责：
1.负责公司内各部门档案文件的归档管理、维护工作；
应聘条件：
1、能够尽快入职(或者一个月左右能够到岗工作)；
2、能长期稳定工作；
3、经验不限，专业不限；
待遇：
2、五险一金，带薪年假，双休，节日福利，有餐补等；
3、可提供住宿或者就近安排工作地点；
4、试用期1-3个月（根据个人能力）转正后享有平均月薪不低于3000元/月收入。
工作时间：
1、国家法定作息时间；
2、周末双休，上9:00下6:00，中午一小时午休时间。
公司招揽综合素质能力贤才，组织完善培训计划，工作经验不足者有老员工培养，并且公司提供全方位的办公环境和设施设备。
待遇优厚，试用期三个月，试用期间上五险一金，周末双休，有餐补，办公环境优越，节日福利，法定节假日~！有良好的发展及晋升空间。
应聘者可投递简历，人事部将在3个工作日内安排面试时间
地址：天津塘沽外滩

工作地址：
天津塘沽外滩
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
部门行政助理+双休稳定
天津金珑基科技有限责任公司
五险一金加班补助餐补
**********
福利:
五险一金
加班补助
餐补
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：2人
职位类别：行政专员/助理
**********
岗位职责：
1、负责部门办公制度维护、管理。
2、要求熟悉基本的计算机操作，办公软件的使用。
3、帮助技术人员从事简单的计算机电脑操作，完成技术项目！
应聘条件：
1、能够尽快入职(或者一个月左右能够到岗工作)；
2、能长期稳定工作；
3、年龄18-30岁之间，经验不限，专业不限；
4、美国上市集团总公司——注重个人综合素质及能力，目前正在招收应届生及实习生。
待遇：
1、底薪+奖金=3000-6000（根据个人能力提升）；
2、五险一金，带薪年假，双休，节日福利，有餐补等；
3、可提供住宿或者就近安排工作地点；
4、试用期1-3个月（根据个人能力）转正后享有平均月薪不低于3000元/月收入。
工作时间：
1、国家法定作息时间；
2、周末双休，上9:00下6:00，中午一小时午休时间。
公司招揽综合素质能力贤才，组织完善培训计划，工作经验不足者有老员工培养，并且公司提供全方位的办公环境和设施设备。
待遇优厚，试用期三个月，试用期间上五险一金，周末双休，有餐补，办公环境优越，节日福利，法定节假日~！有良好的发展及晋升空间。
应聘者可投递简历，人事部将在3个工作日内安排面试时间,
天津塘沽外滩

工作地址：
天津塘沽外滩
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
操作工（雕刻技师)
天津市新艺林装饰有限公司
创业公司全勤奖餐补弹性工作员工旅游绩效奖金节日福利交通补助
**********
福利:
创业公司
全勤奖
餐补
弹性工作
员工旅游
绩效奖金
节日福利
交通补助
**********
职位月薪：4001-6000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：不限
招聘人数：1人
职位类别：普工/操作工
**********
职位要求：
1、两年以上广告制作公司相关工作经验。
2、能熟练操作雕刻，喷绘等广告制作机器。
3、有较强的学习能力和学习意识。
4、有责任心，能按时完成上级主管布置的工作任务。
5、有团队合作及补位意识
6、会开车，两年以上驾驶经验
岗位描述：
1、完成广告制作工作
2、完成上级主管布置的工作任务

工作地址：
天津市南开区咸阳路91号
查看职位地图
**********
天津市新艺林装饰有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市南开区长江道208号
**********
会计
恒大旅游集团有限公司
五险一金年底双薪绩效奖金包吃包住带薪年假定期体检员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
包吃
包住
带薪年假
定期体检
员工旅游
**********
职位月薪：8000-16000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：4人
职位类别：会计/会计师
**********
工作地点：河北省沧州市南大港，不能接受者勿投。联系电话：孙女士 15128707118
任职要求：
1、财务类相关专业统招本科及以上学历；
2、全日制本科3年以上相关工作经验；
岗位职责:
负责恒大集团大型文旅项目沧州童世界财务管理工作，本岗位包吃包住。

项目情况：体量大（16000亩），业态多（主题乐园、会议会展中心、影视基地、商业中心、博物馆群、酒店群等几十个业态），开发周期8-10年。
恒大沧州童世界占地16000亩，总投资1000亿。恒大童世界是全球唯一的“全室内、全天候、全季节”大型主题乐园，面向2-15岁的少年儿童，以中国文化、中国历史、中国故事为核心内容，将打造出全球规模最大、档次最高、世界第一的童话神话主题乐园。

工作地址：
河北省沧州市南大港
**********
恒大旅游集团有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司地址：
广东省广州市天河区黄埔大道西78号恒大中心
**********
采购员
恒大旅游集团有限公司
五险一金包吃包住员工旅游节日福利
**********
福利:
五险一金
包吃
包住
员工旅游
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：天津
发布日期：0002-01-01 00:00:00
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：采购专员/助理
**********
任职要求：
第一学历统招本科及以上学历，三年以上工作经验，房地产行业优先
负责恒大集团大型文旅项目沧州童世界采购工作，本岗位包吃包住。
工作地点：河北省沧州市南大港湿地公园景区（京津一小时生活圈）
项目情况：体量大（16000亩），业态多（主题乐园、会议会展中心、影视基地、商业中心、博物馆群、酒店群等几十个业态），开发周期8-10年。
恒大沧州童世界占地16000亩，总投资1000亿。恒大童世界是全球唯一的“全室内、全天候、全季节”大型主题乐园，面向2-15岁的少年儿童，以中国文化、中国历史、中国故事为核心内容，将打造出全球规模最大、档次最高、世界第一的童话神话主题乐园。
联系电话：13752360040（常女士）
工作地点：河北沧州（能接受常驻沧州再进行简历投递，请勿重复投递）

工作地址：
河北沧州
**********
恒大旅游集团有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司地址：
广东省广州市天河区黄埔大道西78号恒大中心
**********
合同管理员
恒大旅游集团有限公司
五险一金包吃包住员工旅游节日福利
**********
福利:
五险一金
包吃
包住
员工旅游
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：其他
**********
任职要求：
第一学历统招本科及以上学历，三年以上工作经验，房地产行业优先
负责负责部门资料以及合同管理工作，本岗位包吃包住。
工作地点：河北省沧州市南大港湿地公园景区（京津一小时生活圈）
项目情况：体量大（16000亩），业态多（主题乐园、会议会展中心、影视基地、商业中心、博物馆群、酒店群等几十个业态），开发周期8-10年。
恒大沧州童世界占地16000亩，总投资1000亿。恒大童世界是全球唯一的“全室内、全天候、全季节”大型主题乐园，面向2-15岁的少年儿童，以中国文化、中国历史、中国故事为核心内容，将打造出全球规模最大、档次最高、世界第一的童话神话主题乐园。
联系电话：13752360040（常女士）
工作地点：河北沧州（能接受常驻沧州再进行简历投递，请勿重复投递）
工作地址：
河北沧州
**********
恒大旅游集团有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司地址：
广东省广州市天河区黄埔大道西78号恒大中心
**********
销售主管
恒大旅游集团有限公司
五险一金包吃包住员工旅游节日福利
**********
福利:
五险一金
包吃
包住
员工旅游
节日福利
**********
职位月薪：8001-10000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：10人
职位类别：区域销售经理/主管
**********
任职要求：
第一学历统招大专毕业2年以上，2年以上房地产销售经验，精通房地产营销相关知识和技能，熟悉案场销售环节与流程，具备良好的沟通及销售团队管理能力
工作地点：河北省沧州市南大港湿地公园景区（京津一小时生活圈）
项目情况：体量大（16000亩），业态多（主题乐园、会议会展中心、影视基地、商业中心、博物馆群、酒店群等几十个业态），开发周期8-10年。
恒大沧州童世界占地16000亩，总投资1000亿。恒大童世界是全球唯一的“全室内、全天候、全季节”大型主题乐园，面向2-15岁的少年儿童，以中国文化、中国历史、中国故事为核心内容，将打造出全球规模最大、档次最高、世界第一的童话神话主题乐园。
联系电话：13752360040（常女士）
工作地点：北京、天津、石家庄、沧州

工作地址：
河北沧州
**********
恒大旅游集团有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司地址：
广东省广州市天河区黄埔大道西78号恒大中心
**********
收银员（石家庄、天津、北京、济南、沧州）
恒大旅游集团有限公司
五险一金年底双薪绩效奖金包吃包住带薪年假定期体检员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
包吃
包住
带薪年假
定期体检
员工旅游
**********
职位月薪：4001-6000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：10人
职位类别：其他
**********
工作地点：北京、天津、沧州南大港，不能接受者勿投。联系电话：孙女士 15128707118
任职要求：
1、财务类相关专业统招专科及以上学历；
2、1年以上相关工作经验；
岗位职责:
负责恒大集团大型文旅项目沧州童世界案场财务相关工作，本岗位包吃包住。
项目情况：体量大（16000亩），业态多（主题乐园、会议会展中心、影视基地、商业中心、博物馆群、酒店群等几十个业态），开发周期8-10年。
恒大沧州童世界占地16000亩，总投资1000亿。恒大童世界是全球唯一的“全室内、全天候、全季节”大型主题乐园，面向2-15岁的少年儿童，以中国文化、中国历史、中国故事为核心内容，将打造出全球规模最大、档次最高、世界第一的童话神话主题乐园。

工作地址：
沧州南大港、济南、北京、天津、石家庄
**********
恒大旅游集团有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司地址：
广东省广州市天河区黄埔大道西78号恒大中心
**********
行政专员/急聘/五险一金
天津金珑基科技有限责任公司
每年多次调薪五险一金绩效奖金餐补节日福利不加班
**********
福利:
每年多次调薪
五险一金
绩效奖金
餐补
节日福利
不加班
**********
职位月薪：3001-5000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：中专
招聘人数：3人
职位类别：行政专员/助理
**********
岗位职责：
1、起草和修改报告、文稿等
2、及时准确的更新员工通讯录；管理公司网络、邮箱
3、负责日常办公用品采购、发放、登记管理，办公室设备管理
4、订阅年度报刊杂志，收发日常报刊杂志及交换邮件
5、员工考勤系统维护、考勤统计及外出人员管理

任职要求：
1、文秘、行政管理等相关专业优先考虑，中专以上学历
2、熟悉办公室行政管理知识及工作流程，熟悉公文写作格式，具备基本商务信函写作能力，熟练运用OFFICE等办公软件
3、工作仔细认真、责任心强、为人正直，具备较强的书面和口头表达能力
4、招收应届毕业生，有无经验均可

福利待遇：
1、底薪+奖金=4000-6000（根据个人能力）
2、试用期1-3个月，试用期期间给上五险一金
3、转正后带薪年假，节日福利，餐补 

工作时间：
1、国家法定作息时间
2、9:00-18:00，中午午休1小时，双休

工作地址：
天津市塘沽区营口道
查看职位地图
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
无责底薪4800元五险一金双休 销售专员
天九共享控股集团
五险一金绩效奖金交通补助餐补通讯补贴带薪年假弹性工作定期体检
**********
福利:
五险一金
绩效奖金
交通补助
餐补
通讯补贴
带薪年假
弹性工作
定期体检
**********
职位月薪：6001-8000元/月 
工作地点：天津-河北区
发布日期：最近
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：10人
职位类别：销售代表
**********
（每周只上四天班，每天工作6小时的幸福企业）
三餐免费，看病吃药免费
岗位职责：
1、开发挖掘企业家客户并保持沟通及后期关系维护；
2、向客户介绍集团运营模式以及全国联营投资项目；
3、邀请客户参加天九共享投资洽谈会，并在活动现场协助领导谈判促成签约。
任职条件：
（1）有企业家资源或从事过企业家业务联络相关工作；
（2）1年及以上营销工作经验。
福利待遇：
1、岗前培训，入职后不定期提升性培训，实现提升你的个人价值；
2、基本工资+绩效提成+补贴+年终奖金（待遇可视能力面议）食、宿、交通、电话补助齐全。天津市作为销售岗位最高基础薪资。
3、五险一金（养老、失业、工伤、医疗、生育+加天津市住房公积金）让您的家人放心
4、国家法定假日公休，双休日+每天七小时制工作时间，带薪休假（年休假、产假、婚假、丧假等有薪休假）
5、国内外旅游（公司提供国内外旅游外派培训的机会）
6、良好的晋升机制；
7、不定期户外拓展培训
8、同行业极具竞争力的佣金提成以及年终奖励机制。
地址：天津市河北区进步道38号国银大厦A-901-902
工作地址：
天津市河北区进步道38号国银大厦A901-902
**********
天九共享控股集团
公司规模：
1000-9999人
公司性质：
民营
公司行业：
基金/证券/期货/投资
公司主页：
http://www.tjxfjt.com.cn
公司地址：
朝阳区北苑家园秋实路绣菊园7号
**********
前台文员（河北）
恒大旅游集团有限公司
五险一金年底双薪绩效奖金包吃包住带薪年假定期体检员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
包吃
包住
带薪年假
定期体检
员工旅游
**********
职位月薪：4000-5000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：行政专员/助理
**********
工作地点：河北省沧州市南大港，不能接受者勿投。联系电话：孙女士 15128707118
任职要求：
1、全日制统招大专及以上学历；
2、一年以上相关工作经验；
3、身高168以上，形象气质佳。
4、主要负责前台管理及部分行政管理工作，适合年轻人，锻炼成长机会多。
5、简历须附照片，否则不安排面试。
6、联系微信：83860518
岗位职责:
负责恒大集团大型文旅项目沧州童世界前台管理工作，本岗位包吃包住。

项目情况：体量大（16000亩），业态多（主题乐园、会议会展中心、影视基地、商业中心、博物馆群、酒店群等几十个业态），开发周期8-10年。
沧州恒大童世界占地16000亩，总投资1000亿。恒大童世界是全球唯一的“全室内、全天候、全季节”大型主题乐园，面向2-15岁的少年儿童，以中国文化、中国历史、中国故事为核心内容，将打造出全球规模最大、档次最高、世界第一的童话神话主题乐园。

工作地址：
河北
**********
恒大旅游集团有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司地址：
广东省广州市天河区黄埔大道西78号恒大中心
**********
销售内勤
恒大旅游集团有限公司
五险一金包吃包住员工旅游节日福利
**********
福利:
五险一金
包吃
包住
员工旅游
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：销售行政专员/助理
**********
第一学历本科毕业1年以上，1年以上相关岗位工作经验，熟悉购房合同签订、审核、按揭办理等流程，熟练操作EXCEL等办公软件
工作地点：河北省沧州市南大港湿地公园景区（京津一小时生活圈）
项目情况：体量大（16000亩），业态多（主题乐园、会议会展中心、影视基地、商业中心、博物馆群、酒店群等几十个业态），开发周期8-10年。
恒大沧州童世界占地16000亩，总投资1000亿。恒大童世界是全球唯一的“全室内、全天候、全季节”大型主题乐园，面向2-15岁的少年儿童，以中国文化、中国历史、中国故事为核心内容，将打造出全球规模最大、档次最高、世界第一的童话神话主题乐园。
联系电话：13752360040（常女士）
工作地点：北京、天津、石家庄、沧州

工作地址：
河北沧州
**********
恒大旅游集团有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司地址：
广东省广州市天河区黄埔大道西78号恒大中心
**********
急急急！CAD制图员（待遇丰厚）
天津金珑基科技有限责任公司
创业公司五险一金年底双薪绩效奖金加班补助全勤奖餐补节日福利
**********
福利:
创业公司
五险一金
年底双薪
绩效奖金
加班补助
全勤奖
餐补
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：CAD设计/制图
**********
岗位职责：
1、了解CAD软件及其他设计软件的应用；
2、配合工程和设计部门绘制项目最终施工图用于施工。
任职要求：
1、能够尽快入职(或者一个月左右能够到岗工作)
2、能长期稳定工作（不招兼职）。
3、年龄18-28岁之间，经验不限，专业不限
待遇
1、底薪+奖金=3000-6000（根据个人能力提升）
2、五险一金，带薪年假，双休，节日福利，有餐补等；
3、可提供住宿或者就近安排工作地点
4、试用期1-3个月，转正后享有平均月薪不低于3000元/月收入
工作时间：
1、国家法定作息时间
2、周末双休，上9:00下6:00，中午一小时午休时间。
公司招揽综合素质能力贤才，组织完善培训计划，工作经验不足者有老员工培养，并且公司提供全方位的办公环境和设施设备。
待遇优厚，试用期三个月，试用期间上五险一金，周末双休，有餐补，办公环境优越，节日福利，法定节假日~！有良好的发展及晋升空间。
应聘者可投递简历，人事部将在3个工作日内安排面试时间。

工作地址：
天津塘沽新村街营口道泛华国际大厦
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
无责底薪5400元+五险一金+双休+销售主管
天九共享控股集团
五险一金绩效奖金交通补助餐补通讯补贴带薪年假弹性工作定期体检
**********
福利:
五险一金
绩效奖金
交通补助
餐补
通讯补贴
带薪年假
弹性工作
定期体检
**********
职位月薪：6001-8000元/月 
工作地点：天津-河北区
发布日期：最近
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：5人
职位类别：销售主管
**********
（每周只上四天班，每天工作6小时的幸福企业）
三餐免费，看病吃药免费

岗位职责：
1、开发挖掘企业家客户并保持沟通及后期关系维护；
2、向客户介绍集团运营模式以及全国联营投资项目；
3、邀请客户参加天九共享投资洽谈会，并在活动现场协助领导谈判促成签约。
任职条件：
（1）有企业家资源或从事过企业家业务联络相关工作；
（2）2年以上营销工作经验；

福利待遇：1、岗前培训，入职后不定期提升性培训，实现提升你的个人价值；
2、基本工资+绩效提成+补贴+年终奖金（待遇可视能力面议）食、宿、交通、电话补助齐全。天津市作为销售岗位最高基础薪资。
3、五险一金（养老、失业、工伤、医疗、生育+加天津市住房公积金）让您的家人放心
4、国家法定假日公休，双休日+每天七小时制工作时间，带薪休假（年休假、产假、婚假、丧假等有薪休假）
5、国内外旅游（公司提供国内外旅游外派培训的机会）
6、良好的晋升机制；
7、不定期户外拓展培训
8、同行业极具竞争力的佣金提成以及年终奖励机制。

地址：天津市河北区进步道38号国银大厦A901-902
工作地址：
天津市河北区进步道38号国银大厦A901-902
**********
天九共享控股集团
公司规模：
1000-9999人
公司性质：
民营
公司行业：
基金/证券/期货/投资
公司主页：
http://www.tjxfjt.com.cn
公司地址：
朝阳区北苑家园秋实路绣菊园7号
**********
法务员
恒大旅游集团有限公司
五险一金年底双薪绩效奖金包吃包住带薪年假定期体检员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
包吃
包住
带薪年假
定期体检
员工旅游
**********
职位月薪：8000-15000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：3人
职位类别：法务专员/助理
**********
岗位职责：
1、严格审核报送合同，出具审核意见，及时报领导复核； 
2、就日常合同审核过程中发现的问题向相关部门出具法律意见； 
3、配合履约工程师开展合同解析及交底工作； 
4. 负责相关诉讼工作；
任职要求：
1、统招本科及以上学历，法律相关专业，3年以上合同管理相关工作经验，具有法律职业资格，熟悉房地产行业法律法规；                               
2、有地产公司工作经验及诉讼庭审经验；                                      
工作地点：河北沧州（能接受常驻沧州再进行简历投递，请勿重复投递）
联系电话：13752360040（常女士）

工作地址：
河北沧州
**********
恒大旅游集团有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司地址：
广东省广州市天河区黄埔大道西78号恒大中心
**********
集团营销总监/副总裁(职位编号：1)
东胜房地产开发集团有限公司
五险一金绩效奖金餐补带薪年假定期体检节日福利
**********
福利:
五险一金
绩效奖金
餐补
带薪年假
定期体检
节日福利
**********
职位月薪：50000-100000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：10年以上
最低学历：本科
招聘人数：1人
职位类别：副总裁/副总经理
**********
岗位职责：
1、根据公司发展战略，全面负责公司整体营销规划与战略，为重大营销决策提供建议和支持；
2、制定公司营销计划与渠道规划，监控各种销售渠道营销行为；
3、负责品牌推广及项目策划，组织建立系统的市场调查和分析机制，为公司发展提供决策支持； 
4、负责市场调研、产品分析、对竞争产品进行研究和监控，提供项目市场运作的建议和产品建议书；
5、塑造企业及产品品牌形象，落实外界媒介资源的整合及宣传工作；
6、负责公司与营销相关的危机处理，以及媒体公关处理。
任职要求：
1、35-42岁，市场营销、房地产、经济学等相关专业，本科及以上学历；
2、10年房地产相关的工作经验，5年以上大中型营销负责人经验；
3、具备卓越的营销才能，极强的市场策划与运作能力、业绩杰出。
工作地址：
石家庄市平安大街158号东胜紫晶广场1#楼A座25层 集团人力资源部
查看职位地图
**********
东胜房地产开发集团有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司主页：
www.orientvictory.com.cn
公司地址：
石家庄市平安大街158号 东胜紫晶广场1#楼A座25层 集团人力资源部
**********
Java开发实习生/助理（急招！！）
天津金珑基科技有限责任公司
每年多次调薪五险一金绩效奖金餐补节日福利不加班
**********
福利:
每年多次调薪
五险一金
绩效奖金
餐补
节日福利
不加班
**********
职位月薪：3001-5000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：5人
职位类别：Java开发工程师
**********
岗位职责：
1、协助java项目经理对各信息系统项目的立项、开发、实施、运维、升级等管理工作；
2、对公司系统进行实施与维护；
3、解决Java软件开发过程中的问题；
4、完成Java项目经理安排的其他事务。
任职资格：
1.年龄18-32岁，中专以上学历，善于与人交流，表达清晰、亲和力。
2.有优秀的学习能力，维护部门队伍。
3.有较强的组织、协调、执行、沟通能力及人际交往能力。
4.有志于从事高薪IT行业；具备良好的团队协作能力。
5.工作踏实稳重，可承担一定压力。
6.有无经验者均可。（应届生优先，退伍军人优先）
福利待遇：
1、按天津市标准缴纳五险一金；
2、快速晋升空间，有效地竞聘晋升制度；
3、签订正式劳动合同；
4、每季度员工聚会+员工生日会+节日礼物；
5、每年享受国家规定的带薪年假、法定节假日等福利；
6、本岗位双休（9：00-18：00，正常节假日放假，享受5天年假）
工作地址：
天津市塘沽区营口道
查看职位地图
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
高级展厅销售顾问+高提点+晋升快
天津典藏国一文化艺术交流有限公司
五险一金年底双薪绩效奖金年终分红带薪年假员工旅游节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
年终分红
带薪年假
员工旅游
节日福利
**********
职位月薪：10001-15000元/月 
工作地点：天津
发布日期：最近
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：5人
职位类别：销售代表
**********
客户资源均由公司提供，无需外跑寻找客户
岗位职责：
1.根据公司提供的客户，进行潜在客户的开发；
2.为客户建立、提供专业的资产管理咨询服务;；
3.负责贵宾客户维护提升工作，为贵宾客户提供专业化服务等。
职位要求：
1.有耐心，勤奋努力，热爱销售工作，年龄20-30岁；
2.有较好的团队意识和协作精神，强烈的进取精神；
3.责任心强，积极的工作态度；
4.思维敏捷，具备较强学习能力和沟通能力。
我们的招聘理念：
1、公司不是按资排辈的，只要你有能力，我们是无天花板的晋升，未来不管你想成为专业顾问，还是想负责团队管理，在典藏国一，心有多大，舞台就有多大；
2、提供带薪培训和15天的带薪年假（爽到爆），每年都有员工旅游的机会，生日福利神马的更不用说了；
3、我们都来自五湖四海，志趣相投聚在一起。我们可以为了一个目标共同努力，互相给予鼓励和帮助，分享经验，我们还有各种team building，一起吃喝玩乐，hold住小清新，也玩得了重口味，让你真正体验到开心工作，快乐成长。
工作时间:
上午9：00——18:30
工作地址：
天津市河东区万达广场C座
**********
天津典藏国一文化艺术交流有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市河东区万达广场
查看公司地图
**********
无责底薪3500+高提成（五险，带薪培训）
天津典藏国一文化艺术交流有限公司
五险一金年底双薪绩效奖金年终分红带薪年假员工旅游节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
年终分红
带薪年假
员工旅游
节日福利
**********
职位月薪：8001-10000元/月 
工作地点：天津
发布日期：最近
工作性质：全职
工作经验：1年以下
最低学历：不限
招聘人数：6人
职位类别：销售代表
**********
岗位职责：
1、客户来到公司负责接待，向客户讲解公司的产品知识； 
2、工作环境优越，无需外出；带薪培训，一对一帮带制度；
3、底薪3.5K+高提成，每单提成金额1000--60000之间，五险，公司不定期举行员工旅游，国家法定节假日均可享受带薪休假； 
4、优秀的晋升机制，公司提供股权激励；
5、120多家全国连锁机构，公司平台大，发展空间广阔。
任职要求：
1、男女不限，年龄在18—30岁，有一定承压能力； 
2、有无经验均可，应届毕业生亦可，要求吃苦耐劳；
3、具有亲和力，性格开朗，热情大方，热爱与人交流；
4、性格坚韧，思维敏捷，具备良好的应变和承压能力；
5、有敏锐的市场洞察力，有强烈的事业心、责任心和积极的工作态度，有销售工作经验者优先。
新员工入职1-2月均工资6000~8000元，上手后月收8000-10万以上（上不封顶）。
没有工作经验者，公司提供专业的带薪培训，我们不看中你的工作经验，只要你足够勤奋，有事业心和责任心，我司秉承态度第一、能力第二，对待新员工我们坚持传、帮、带的原则，让员工在这里找到家的感觉。
我们拥有最好的团队，期待不平凡的你加入！相信自己，一个电话，就会改变你的人生轨迹！


工作地址：
天津市河东区万达广场C座
**********
天津典藏国一文化艺术交流有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市河东区万达广场
查看公司地图
**********
经销商顾问/客户经理/销售代表(天津)
汽车之家
**********
福利:
**********
职位月薪：8001-10000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：1人
职位类别：销售代表
**********
工作内容：
1、服务所在地汽车之家合作的经销商；
2、宣传推广公司产品、品牌，负责老客户的维护与管理，并不断拓展开发新客户；
3、负责所在地的经销商平台、广告及相关产品的售卖与服务，完成公司制定的销售目标；
4、负责客户营销方案的制作和提报，以及销售合同的谈判、签订、收款；
5、组织所在地用户和经销商的培训及活动；
6、服务城市：天津
 
任职资格：
1、本科以上学历；
2、有互联网、汽车、媒体等相关行业者优先，有销售经验者优先；
3、做事坚持原则，有责任心，诚实正直，吃苦耐劳；
4、注重效率，能适应高强度、快节奏的工作环境，有强烈的团队协作意识；
5、热爱销售工作，有激情，积极主动，有较好的执行能力及抗压能力。
工作地址：
北京市海淀区北四环丹棱街3号中国电子大厦B座10层
查看职位地图
**********
汽车之家
公司规模：
1000-9999人
公司性质：
民营
公司行业：
互联网/电子商务
公司主页：
www.autohome.com.cn
公司地址：
北京市海淀区北四环丹棱街3号中国电子大厦B座10层
**********
开发/加盟经理、销售经理/专员(天津)
格林豪泰酒店（中国）有限公司
五险一金绩效奖金交通补助通讯补贴带薪年假补充医疗保险定期体检员工旅游
**********
福利:
五险一金
绩效奖金
交通补助
通讯补贴
带薪年假
补充医疗保险
定期体检
员工旅游
**********
职位月薪：8001-10000元/月 
工作地点：天津
发布日期：最近
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：10人
职位类别：销售经理
**********
【应聘流程】在线测试、初试、复试、背景调查、学历验证

【工作内容】
1 寻找有意向的加盟商并洽谈合作相关事宜；
2 寻找物业信息；如果租赁，与物业业主初步洽谈；如果加盟，与加盟投资人合作谈判；
3 负责现场调研物业的地理位置、周边市场条件、建筑结构、面积、业主情况、产权性质等信息；
4 编制项目投资预算报表，可行性分析；
5 调研周边酒店的房价、出租率、经营情况等信息；
6 上级交办的其他工作。
 
【任职资格】
1 22至35岁，大专及以上学历，市场营销、金融、经济类专业优先，欢迎优秀应届生应聘；
2 有1年以上大中型物业中介、地产、招商等工作经验，或2年以上销售工作经验者优先；
3 形象良好，诚信正直，有良好的团队合作精神和服务意识；
4 良好的表达能力，沟通协调能力，学习能力，执行力；
5 具有一定的谈判技巧，原则性强；
6 具有强烈的责任心和抗压能力；
7 认可企业核心价值观。

【薪资福利】
1 薪资收入由基本工资+项目提成构成，起薪3万元/年，平均年薪8万元；
具体项目指标如下：
基本工资3000元/月，自找项目指标4个/年，综合项目奖金20000-50000元/个；
基本工资3500元/月，自找项目指标5个/年，综合项目奖金20000-50000元/个；
基本工资4000元/月，自找项目指标6个/年，综合项目奖金20000-50000元/个；
入司之前需先签订项目指标确认书；
2 缴纳社会保险和公积金，补充商业意外险；
3 差旅报销、电话补助。

【培训与发展】
1 一对一带教，每周一次业务培训；
2 透明公正的晋升平台：开发专员→区域开发主管→区域经理→部门副总监→部门总监，（综合表现突出，半年就有机会晋升为区域开发主管，1年后通过选拔可以晋升为区域经理，3年可以晋升为部门副总监）。
工作地址：
天津市
查看职位地图
**********
格林豪泰酒店（中国）有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
酒店/餐饮
公司主页：
www.998.com
公司地址：
上海市长宁区虹桥路2451号
**********
【设计部】平面设计
天津市峻腾广告有限公司
五险一金绩效奖金加班补助交通补助餐补带薪年假员工旅游节日福利
**********
福利:
五险一金
绩效奖金
加班补助
交通补助
餐补
带薪年假
员工旅游
节日福利
**********
职位月薪：4000-6000元/月 
工作地点：天津
发布日期：最近
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：2人
职位类别：平面设计
**********
岗位职责：
1、 负责公司日常客户对接，完成客户广宣品设计及安排物料制作；
2、 负责对接公司品牌公关中心客户创意策划产品设计；
3、 负责对接新媒体部门日常设计需求；
4、 负责公司内部宣传品设计。
职位要求：
1、 大专以上学历，男女不限；
2、 具有广告行业设计工作经验不少于2年；
3、 能够吃苦耐劳，沟通能力及执行能力强；
4、 熟练使用illustrator，photoshop等设计软件；
5、 能够掌握3D设计者优先考虑；
6、 良好的团队协作和理解能力，具备认真、创新、敬业精神；
7、 具有服务意识，积极乐观，拥有工作激情。
注：面试时请携带您的个人作品！

工作地址：
天津市河东区万达写字楼1401
**********
天津市峻腾广告有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市河东区万达写字楼
查看公司地图
**********
酒店总经理/店长(天津)
格林豪泰酒店（中国）有限公司
五险一金绩效奖金包住交通补助通讯补贴补充医疗保险定期体检节日福利
**********
福利:
五险一金
绩效奖金
包住
交通补助
通讯补贴
补充医疗保险
定期体检
节日福利
**********
职位月薪：8001-10000元/月 
工作地点：天津
发布日期：最近
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：10人
职位类别：酒店管理
**********
【应聘流程】在线测试、视频面试、学历验证、背景调查
【工作内容】
1 全面负责酒店的经营管理，领导各部门员工完成酒店的各项计划目标；
2 围绕公司下达的利润指标和各项工作，编制酒店的预算和决算，严格控制经营成本和各种费用开支；
3 负责酒店团队的建立、培养和管理提高整个酒店的服务质量和员工素质；
4 根据市场变化和发展，制定切实可行的市场营销工作策略，并组织实施和有效控制；
5 全面负责安全管理，抓好食品卫生，治安安全等工作，确保客人和员工的人身、财产安全；
6 与公司、加盟业主进行日常的沟通协调工作，确保信息畅通、有效；
7 负责做好酒店与各界人士的公共关系，抓好重要客人的接待工作，塑造良好的内、外部形象；
8 关心员工思想和生活，不断改善员工的工作条件；
9 完成公司交办的其他工作。

【任职资格】
1 大专及以上学历，条件优秀者可放宽至中专；
2 有酒店行业1年及以上的全面管理经验、部门经理2年及以上的管理经验（前厅/客房/销售至少管理过两个部门），25-40岁，连锁酒店或高星级酒店经验者优先；
3 具有良好的职业道德，较强的沟通协调和应变能力，较强管理和团队建设能力；
4 原则性强，执行力较好；有良好的抗压能力，能出色完成公司下达的各项指标；
5 认同格林豪泰企业文化核心价值观，有很强的服务意识、学习能力和工作责任心；
6 能接受公司1至2年的外派，工作地点就近分配。
 【专业培训】
入职之后公司会提供为期6周的店长专业技能专项培训，培训的主要内容为如何成为一个合格酒店店长的基本知识。需签订为期2年的培训协议。
 【职业发展通道】
见习店长→店长→运营督导→城区经理→区域经理→运营总监
 【薪资框架】
1 一级见习店长：
要求：国内知名连锁品牌担任值班经理、部门经理岗位，且有轮岗前厅、客房、销售工作。 酒店工作1年半以上。 
基本工资4000+业绩奖金；
2二级见习店长：
要求：国内知名连锁品牌、单体酒店店助、店长，至少1年本岗岗龄；4星级酒店部门经理（前厅、客房、销售中两个部门及以上岗位管理经验）等职位。
基本工资4500+业绩奖金；
3 一级店长：
要求：国内知名连锁品牌担任高值、店助、运营经理等岗位；单体酒店店长职位；4星级及以上酒店部门总监职位；均1年以上本岗岗龄。
基本工资5000-5500+业绩奖金；
4 二级店长：
要求：国内知名连锁品牌担任店长岗位，1年及以上本岗岗龄；单体酒店店长职位，2年及以上本岗岗龄；4星级及以上酒店部门总监职位，且2年以上本岗岗龄。
基本工资5500-6000+业绩奖金；
5 三级店长
要求：国内知名连锁品牌担任店长岗位，2年及以上本岗岗龄；单体酒店店长职位，3年及以上本岗岗龄；4星级及以上酒店部门总监职位，且3年及以上本岗岗龄。。
基本工资6000-6500+业绩奖金；
6 四级店长
要求：国内知名连锁品牌担任店长岗位，3年及以上本岗岗龄；单体酒店店长职位，4年及以上本岗岗龄；4星级及以上酒店部门总监职位，且4年及以上本岗岗龄。
基本工资6500-7000+业绩奖金；
7五级店长
要求：国内知名连锁品牌担任店长岗位，4年及以上本岗岗龄；单体酒店店长职位，5年及以上本岗岗龄；4星级及以上酒店部门总监职位，且5年以上本岗岗龄。
基本工资7000-8000+业绩奖金；
8 青皮树一级店长
要求：在精品酒店、商务酒店担任店助；星级酒店房务经理；国内知名连锁品牌担任高值、店助、运营经理，均2年及以上本岗岗龄。
基本工资：5000-6000+业绩奖金；
9青皮树二级店长
要求：国内知名连锁品牌担任店长，1年及以上本岗岗龄，商务酒店、精品酒店店长职位，3年及以上本岗岗龄。
基本工资6000-7000+业绩奖金；
10青皮树三级店长
要求：国内知名连锁品牌担店长岗位，2年及以上本岗岗龄；商务酒店、精品酒店担任店长岗位，4年及以上本岗岗龄。
基本工资7000-8000+业绩奖金；
11格林东方一级店长
要求：4星级及以上酒店担任总经理职位，且有2年及以上本岗岗龄。
基本工资8000-9000+业绩奖金；
12格林东方二级店长
要求：4星级及以上酒店担任总经理职位，且有3年及以上本岗岗龄。
基本工资10000-15000+业绩奖金；
13格林东方三级店长
要求：4星级及以上酒店担任总经理职位，且有5年及以上本岗岗龄。
基本工资15000-20000+业绩奖金；
以上基本工资及业绩奖金视酒店房间体量大小及面试情况上下浮动。
 【员工福利】
车费补贴、电话补贴、保险、公积金、提供住宿、周年礼物、周年体检、酒店住宿折扣、带薪年假

工作地址：
格林豪泰酒店
查看职位地图
**********
格林豪泰酒店（中国）有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
酒店/餐饮
公司主页：
www.998.com
公司地址：
上海市长宁区虹桥路2451号
**********
无责任底薪3500+高提成急招店内销售
天津典藏国一文化艺术交流有限公司
五险一金年底双薪带薪年假员工旅游
**********
福利:
五险一金
年底双薪
带薪年假
员工旅游
**********
职位月薪：10001-15000元/月 
工作地点：天津
发布日期：最近
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：10人
职位类别：销售代表
**********
岗位职责： 
1、客户来到公司负责接待，向客户讲解公司的产品知识； 
2、工作环境优越，无需外出；
3、无责任底薪3500+高提成（综合工资8000-3w），每周单休，公司不定期举行员工旅游，国家法定节假日均可享受带薪休假。
4、负责销售区域内销售活动的策划和执行，完成销售任务； 
5、管理维护客户关系以及客户间的长期战略合作计划。 
任职资格： 
1、高中及以上学历，年龄：19—30岁，市场营销等相关专业者优先； 
2、从事过销售行业工作经者优先； 
3、具有亲和力，性格开朗，热爱和人交流；
4、具备一定的市场分析及判断能力，良好的客户服务意识； 
5、有团队协作精神，善于挑战。
工作地址
天津市河东区津滨大道万达广场写字楼C座16层

工作地址：
天津市河东区万达广场C座16层
**********
天津典藏国一文化艺术交流有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市河东区万达广场
查看公司地图
**********
客服专员
家有购物集团股份有限公司
五险一金绩效奖金年终分红包住餐补带薪年假补充医疗保险节日福利
**********
福利:
五险一金
绩效奖金
年终分红
包住
餐补
带薪年假
补充医疗保险
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津-武清区
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：中技
招聘人数：20人
职位类别：客户服务专员/助理
**********
【岗位职责】
1、负责接听产品的热线，技巧性的将产品介绍给顾客，促成订单；
2、统计每日的销售数量；
3、配合组长进行新员工的辅导，帮助组内成员共同完成并提高个人与团队的业绩指标；
4、收集、整理销售过程中，顾客所反应的问题，并协调处理。
【任职资格】
1、普通话标准，声音甜美；
2、谈吐礼貌，应变能力强；
3、具备一定的抗压能力，中英文打字熟练；
4、具有优良的服务意识和敬业精神；
5、有相关工作经验者优先。

工作地址：
天津市武清区国际企业社区
查看职位地图
**********
家有购物集团股份有限公司
公司规模：
1000-9999人
公司性质：
国企
公司行业：
广告/会展/公关
公司主页：
http://www.jyh.com
公司地址：
北京市朝阳区双柳北街38号天籁轩E座
**********
艺术品展厅销售
天津典藏国一文化艺术交流有限公司
五险一金绩效奖金带薪年假员工旅游节日福利
**********
福利:
五险一金
绩效奖金
带薪年假
员工旅游
节日福利
**********
职位月薪：10001-15000元/月 
工作地点：天津
发布日期：最近
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：10人
职位类别：大客户销售代表
**********
岗位职责： 
1、客户来到公司负责接待，向客户讲解公司的产品知识； 
2、工作环境优越，无需外出；
3、无责任底薪3500+高提成，综合工资在8000以上，每周单休，公司不定期举行员工旅游，国家法定节假日均可享受带薪休假。
4、负责销售区域内销售活动的策划和执行，完成销售任务； 
5、管理维护客户关系以及客户间的长期战略合作计划。 
任职资格： 
1、高中以上学历，年龄20-28岁，对销售工作有热情； 
2、从事过销售行业工作经者优先； 
3、具有亲和力，性格开朗，热爱和人交流；
4、具备一定的市场分析及判断能力，良好的客户服务意识； 
5、有团队协作精神，善于挑战。

工作地址：
天津市河东区津滨大道万达广场写字楼C座16层
**********
天津典藏国一文化艺术交流有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市河东区万达广场
查看公司地图
**********
行政助理、招聘助理
北京贝特展览服务有限公司
五险一金餐补
**********
福利:
五险一金
餐补
**********
职位月薪：4001-6000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：3人
职位类别：招聘经理/主管
**********
岗位职责：
 负责公司人力招聘工作，行政事务处理
任职要求：
1、统招本科学历
2、抗压力强，有良好的沟通能力和协调能力
3、有过电话销售经验或者招聘经验者优先
工作地址：
北京市朝阳区远洋商务61号楼
**********
北京贝特展览服务有限公司
公司规模：
500-999人
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
北京市朝阳区东恒时代c座502室
**********
高底薪+提成8000以上招聘销售精英
天津典藏国一文化艺术交流有限公司
五险一金年底双薪绩效奖金年终分红带薪年假员工旅游节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
年终分红
带薪年假
员工旅游
节日福利
**********
职位月薪：10001-15000元/月 
工作地点：天津
发布日期：最近
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：15人
职位类别：店员/营业员/导购员
**********
岗位职责： 
1、对到访客户公司负责接待，向客户讲解公司的产品知识； 
2、工作环境优越，无需外出，非电话销售；
3、无责任底薪3500+提成，综合工资在8000-3w，每周单休，公司不定期举行员工旅游，国家法定节假日均可享受带薪休假。
4、负责销售区域内销售活动的策划和执行，完成销售任务； 
5、管理维护客户关系以及客户间的长期战略合作计划。 
6、公司提供优质公平的发展晋升平台，为员工提供专业的培训及在职辅导，一对一带岗。
任职资格： 
1、形象好，气质佳，年龄在20—35之间，，市场营销等相关专业者优先； 
2、从事过销售行业工作经者优先； 
3、具有亲和力，性格开朗，热爱和人交流；
4、具备一定的市场分析及判断能力，良好的客户服务意识； 
5、有团队协作精神，善于挑战。
6、有激情，有目标，想赚钱，我们提供最优质的平台等你来施展自己的梦想！

工作地址：
天津市河东区万达广场
**********
天津典藏国一文化艺术交流有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市河东区万达广场
查看公司地图
**********
无责任底薪+高提成（高端艺品导购专员，无电销无外出）
天津典藏国一文化艺术交流有限公司
**********
福利:
**********
职位月薪：10001-15000元/月 
工作地点：天津-河东区
发布日期：最近
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：市场专员/助理
**********
岗位职责：
1、负责在公司展厅接待来访客户，讲解产品
2、维护新老客户关系
3、每年12天带薪病假，法定节假日带薪休假
4、高额提成，每单提成金额1000~60000之间
5、优秀的晋升机制，公司股权激励，员工旅游
6、客户量大，成单快
7、全国连锁机构，公司雄厚实力，而本公司在全国业绩排名第一，员工薪资相对同行业处于优厚位置。
无电销、外出性质，无邀约压力。客户主动上门，新客户开发不用愁

任职要求：
1、大专以上学历，条件优秀者学历可放宽
2、不矫情，有韧性、外地户口者优先录用
3、真正想要挣钱求发展的，混底薪勿扰
工作地址：
天津市河东区万达广场c座16层
**********
天津典藏国一文化艺术交流有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市河东区万达广场
查看公司地图
**********
上市集团15-20W年薪聘咨询主管
天津众云金泰科技有限公司
五险一金绩效奖金年终分红餐补员工旅游节日福利带薪年假每年多次调薪
**********
福利:
五险一金
绩效奖金
年终分红
餐补
员工旅游
节日福利
带薪年假
每年多次调薪
**********
职位月薪：10001-15000元/月 
工作地点：天津
发布日期：最近
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：培训/招生/课程顾问
**********
任职要求：
1、大专以上学历；
2、1年以上团队管理工作经验；
1、有较强的学习能力，具有正确的教育理念，教育背景者优先考虑；
2、仪表端庄，举止得体；口齿清晰，普通话标准；
3、工作条理性强，应变能力、协调、沟通控制以及抗压能力强。
岗位职责：
1、热爱教育事业，有很好的团队合作精神和职业素质；
2、有良好的团队管理，带队能力，培训能力及高效执行力；
3、有较强的市场分析能力和市场开拓能力。
4、制定团队中、长期培训计划，并负责监督落实执行。
5、带领团队，开展销售招生工作，完成团队项目业绩指标。

福利待遇：
1、底薪+提成+绩效奖金+年度绩效奖金＋年终分红＋5险1金+法定假日（年薪15W+）
2、签订正式劳动合同，完整合规的社会保险和住房公积金以及餐补；
3、每季度员工聚会+员工生日会+节日礼物；
4、每年享受国家规定的带薪年假、法定节假日等福利；
5、丰富的企业文化活动，打造快乐活力的工作氛围。

一号线地铁鞍山道A口出来右转直行100米即达！



工作地址：
天津市和平区劝业场街道南京路258号巨贝大厦A座7层701室
查看职位地图
**********
天津众云金泰科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
IT服务(系统/数据/维护)
公司地址：
天津市和平区劝业场街道南京路258号巨贝大厦A座7层701室
**********
广告设计专员4k 双休 五险一金
天津金珑基科技有限责任公司
创业公司五险一金年底双薪绩效奖金加班补助全勤奖餐补节日福利
**********
福利:
创业公司
五险一金
年底双薪
绩效奖金
加班补助
全勤奖
餐补
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：广告创意/设计师
**********
岗位描述：
1、有兴趣进入互联网、游戏、设计行业， 想获得一份长期稳定且有发展前景的工作。
2、好学、细心，有强烈的责任心和上进心。
3、注重团队合作，为人正直，富有创造力和责任感。
应聘条件：
1、招聘长期稳定工作。
2、年龄要求在18-30岁之间 。
3、美国上市集团总公司———注重个人综合素质及能力，目前正在招收应届生及实习生
待遇：
1、底薪+奖金=3000-6000（根据个人能力提升）
2、五险一金，带薪年假，节日福利，有餐补等；
  3、外地员工可提供住宿
4、试用期1-3个月，转正后享有平均月薪不低于3000元/月收入
工作时间：
1、国家法定作息时间
2、周末双休，上9:00下6:00，中午一小时午休时间。
备注：
公司招揽综合素质能力贤才，组织完善培训计划，工作经验不足者有老员工培养，并且公司提供全方位的办公环境和设施设备。
有良好的发展及晋升空间，欢迎广大应届毕业生实习生、有识之士加入共同实现梦想，创建美好明天。
面试人员较多，请应聘者先投递简历，人事部将在3个工作日内安排面试时间

工作地址：
天津塘沽新村街营口道泛华国际大厦
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
急聘展览设计师助理+双休+五险一金
天津金珑基科技有限责任公司
创业公司五险一金年底双薪绩效奖金加班补助全勤奖餐补节日福利
**********
福利:
创业公司
五险一金
年底双薪
绩效奖金
加班补助
全勤奖
餐补
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：助理/秘书/文员
**********
岗位职责：
1.根据客户需求，结合客户产品特点，完成设计图；
2.根据客户要求，对设计图进行修改；
3.参与临时项目组的设计，并提出有效意见；负责展览、活动、展厅项目创意、设计方案的制作；
4.完成领导临时交代的任务。 
任职资格：
1、年龄18-28岁，中专及以上学历；
2、有相关工作经验或文秘、行政管理等相关专业者优先考虑；
3、熟悉办公室行政管理知识及工作流程；
4、熟悉公文写作格式，熟练运用OFFICE等办公软件；
5、工作仔细认真、责任心强、为人正直。
上班时间：早九晚六，周六日双休，节假日正常放假休息。
薪资待遇：月薪3000起+福利补贴+奖金+五险一金+提供住宿+良好的工作环境
请保证手机联系方式的有效性，初审合格后，我公司将以短信或电子邮件的形式通知参加面试。

工作地址：
天津塘沽新村街营口道泛华国际大厦
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
PHP开发工程师助理（住宿+餐补）可应届
天津金珑基科技有限责任公司
五险一金绩效奖金加班补助包住餐补带薪年假节日福利
**********
福利:
五险一金
绩效奖金
加班补助
包住
餐补
带薪年假
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：PHP开发工程师
**********
岗位要求：
1、了解使用PHP MySQL Apache进行WEB开发；
2、了解掌握 HTML、JAVASCRIPT、jQuery、AJAX技术，熟悉DIV +CSS技术；
3、对主流开源系统进行二次开发，ecshop,dedecms,wordpress等；
4、应届毕业生可适当放宽条件；
任职资格：
1、年龄18-30岁，大专以上学历，善于与人交流，表达清晰、亲和力。
2、有优秀的学习能力，维护部门队伍。
3、有较强的组织、协调、执行、沟通能力及人际交往能力。
4、有志于从事高薪IT行业；具备良好的团队协作能力。 
5、工作踏实稳重，可承担一定压力。
6、有无经验者均可。（应届生优先）
福利待遇：
1、按天津市标准缴纳五险一金；
2、快速晋升空间，有效地竞聘晋升制度；
3、签订正式劳动合同；
4、每季度员工聚会+员工生日会+节日礼物；
5、每年享受国家规定的带薪年假、法定节假日等福利； 
6、本岗位双休（9：00-18：00，正常节假日放假）
工作地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
数据通信工程师助理（餐补+高薪）
天津金珑基科技有限责任公司
五险一金绩效奖金加班补助包住餐补带薪年假节日福利
**********
福利:
五险一金
绩效奖金
加班补助
包住
餐补
带薪年假
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：数据通信工程师
**********
一、岗位要求：
1、全日制大专及以上学历，计算机通信、计算机网络、网络工程、通信工程等相关专业毕业生；
2、熟悉计算机操作系统及数据库原理及TCP/IP技术；
3、有较强的动手能力，熟悉硬件设备安装，熟练掌握各种办公软件；
4、工作积极主动，有较强的沟通协调能力，对通信软件行业有较大的兴趣。

二、岗位描述：
1、负责数通设备的网络规划设计、调试、验收和割接入网；
2、负责本公司承载网的日常维护，数据开通；
3、掌握常用的软件工具，及时完成工作记录和报表汇总；
4、对于各种常见告警，可及时定位并进行判断和处理。

三、公司福利：
1、科学合理的绩效考核体系以及具有竞争优势的薪酬制度；
2、为员工购买五险一金，让员工无后顾之忧；
3、人性化的培训管理制度、一对一的指定帮助让员工快速融入新环境并成长；
4、五天八小时工作制、周末双休、法定节假日之外的带薪病假、年休假，让员工与家人共享美好生活；

四、工作时间：
1、常规工作时间：周一至周五，早上9:00-12:00，下午13:00-18:00，周末双休；
2、法定节假日正常休息；
3、连续工作满1年者享受5天带薪年假。
工作地址：
天津
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
Java开发工程师助理（可应届可实习）
天津金珑基科技有限责任公司
五险一金绩效奖金加班补助包住餐补带薪年假节日福利
**********
福利:
五险一金
绩效奖金
加班补助
包住
餐补
带薪年假
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：Java开发工程师
**********
岗位要求：
1、协助java项目经理对各信息系统项目的立项、开发、实施、运维、升级等管理工作；
2、对公司系统进行实施与维护；
3、解决Java软件开发过程中的问题；
4、完成Java项目经理安排的其他事务。
任职资格：
1、年龄18-32岁，大专以上学历，善于与人交流，表达清晰、亲和力。
2、有优秀的学习能力，维护部门队伍。
3、有较强的组织、协调、执行、沟通能力及人际交往能力。
4、有志于从事高薪IT行业；具备良好的团队协作能力。 
5、工作踏实稳重，可承担一定压力。
6、有无经验者均可。（应届生优先）
福利待遇：
1、按天津市标准缴纳五险一金；
2、快速晋升空间，有效地竞聘晋升制度；
3、签订正式劳动合同；
4、每季度员工聚会+员工生日会+节日礼物；
5、每年享受国家规定的带薪年假、法定节假日等福利； 
6、本岗位双休（9：00-18：00，正常节假日放假）
工作地址：
天津塘沽
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
急聘初级设计助理/双休
天津金珑基科技有限责任公司
每年多次调薪五险一金年终分红餐补带薪年假节日福利不加班
**********
福利:
每年多次调薪
五险一金
年终分红
餐补
带薪年假
节日福利
不加班
**********
职位月薪：3001-5000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：2人
职位类别：设计管理人员
**********
岗位职责：
1、前期协助设计师做一些日常资料收集等工作；
2、参与公司项目构思及取材工作
3、完成公司部分文案等工作
4、尽快完善自身能力，积极参与公司各项目的完成工作。
任职要求：
1、男女不限，往应届毕业生皆可；
2、对计算机、手机游戏、设计网站感兴趣，并想进入该行业；
3、具备良好学习能力，办公软件，良好的沟通协调能力；
4、为人诚恳踏实，具有良好的团队合作能力。
薪资待遇
公司人力资源部为所有岗位建立成长模式、提供系统化岗位技能提升渠道、提供职业发展通道，入职后每年有2次薪资考核提升机会，根据岗位能力与职责不同，当年年薪4W-6W。
薪资构成：基本工资3000起+奖金+岗位津贴+丰厚年终奖
社会保险：入职即上五险一金
休息时间：5天8小时工作制、朝九晚六，周末双休，法定节假日休息，带薪年假，带薪病假，带薪产假，带薪婚丧假
节日贺礼：传统佳节派发节日礼品以增添节日气氛。
生日派对：过生日的员工，有公司生日派对以表祝福
生活关怀：定期体检，公司设有员工休息室，提供微波炉、饮水机等便捷设备。办公环境：办公环境优美，可提供住宿或者就近安排工作地点。

工作地址：
天津塘沽新村街营口道
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
滨海新区网店运营+餐补+五险一金
天津金珑基科技有限责任公司
每年多次调薪五险一金年终分红餐补带薪年假节日福利不加班
**********
福利:
每年多次调薪
五险一金
年终分红
餐补
带薪年假
节日福利
不加班
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：3人
职位类别：网店运营
**********
岗位职责：（会有人带，踊跃尝试）
1、负责平台营销推广及网络广告的投放（直通车、钻展等），提高店铺有效流量；
2、负责收集市场和行业信息，提出店铺问题和解决方案；
3、提高公司网站上搜索引擎的点击率和排名，做营销数据统计。
任职要求：
1、年龄20-28周岁，有无经验均可；
2、考虑天津塘沽的办公地点，公司可以提供住宿；
3、好学、细心，有强烈的责任心和上进心。
福利待遇：
【工作时间】周一至周五，朝九晚六，周末双休；
【薪酬】富有竞争力的薪酬水平和项目提成；
【奖金】绩效奖金、项目奖金、年终奖金；
【社保】五险一金：医疗、生育、工伤、失业、养老保险及住房公积金；
【公司福利】节日福利、加班补贴、餐补、公司聚餐、年会等，活动丰富；
【假期福利】享受国家规定的带薪年假，法定节假日；
【成长进步】人性化的学习管理制度、一对一的指定帮助，让员工快速融入新环境并成长！

工作地址：
天津塘沽新村街营口道
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
软件测试员助理+五险一金双休
天津金珑基科技有限责任公司
五险一金加班补助全勤奖餐补
**********
福利:
五险一金
加班补助
全勤奖
餐补
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：2人
职位类别：软件工程师
**********
岗位职责：
1、学习能力强，善于思考总结，工作认真、责任心强； 
2、能有协助测试专员完成相关工作。 
应聘条件： 
1、能够尽快入职(或者一个月左右能够到岗工作)；
2、能长期稳定工作； 
3、年龄18-30岁之间，经验不限，专业不限；  
待遇：
1、底薪+奖金=3000-6000（根据个人能力提升）；
2、五险一金，带薪年假，双休，节日福利，有餐补等；
 3、可提供住宿或者就近安排工作地点；
 4、试用期1-3个月（根据个人能力）转正后享有平均月薪不低于3000元/月收入。
 工作时间：
 1、国家法定作息时间；
 2、周末双休，上9:00下6:00，中午一小时午休时间。
待遇优厚，试用期三个月，试用期间上五险一金，周末双休，有餐补，办公环境优越，节日福利，法定节假日~！有良好的发展及晋升空间。
地址：天津塘沽外滩
工作地址：
天津塘沽外滩
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
Web前端开发实习生双休+餐补
天津金珑基科技有限责任公司
每年多次调薪五险一金年终分红餐补带薪年假节日福利不加班
**********
福利:
每年多次调薪
五险一金
年终分红
餐补
带薪年假
节日福利
不加班
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：3人
职位类别：WEB前端开发
**********
岗位职责：
1.热爱互联网工作，要有一定的逻辑思维。
2.协助工程师完成公司后台的开发与维护。
3.完成领导交代的任务。
任职资格：
1.能够尽快入职，且长期稳定工作。
2.工作认真细致，有责任心。
3.年龄18-30周岁，经验不限，可接受应届毕业生。
工作时间：
早九晚六，周末双休，中午休息一小时。
福利待遇：
1、底薪+奖金=3000-5000（根据个人能力提升）
2、五险一金，带薪年假，季度旅游，双薪，有餐补等
3、可提供员工宿舍
4、签订正式劳动合同
5、每季度员工聚会+员工生日会+节日礼物
6、高薪收入，依据岗位不同，设立相应的绩效奖励激励机制
7、快速晋升空间，有效地竞聘晋升制度

工作地址：
天津塘沽新村街营口道
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
技术部助理+有无经验均可+双休
天津金珑基科技有限责任公司
创业公司五险一金年底双薪绩效奖金加班补助全勤奖餐补节日福利
**********
福利:
创业公司
五险一金
年底双薪
绩效奖金
加班补助
全勤奖
餐补
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：助理/秘书/文员
**********
岗位职责：
1、正常操作Office办公软件；包括Word，excel等。
2、在技术部门协助技术总监从事部门行政的工作，包括制度的制定执行管理；
3、在技术部门配合技术人员做些数据的统计，数据的分析，写数据分析报告
4、协助技术专员完成简单的计算机电脑操作，帮他们减轻工作量和工作负担；
任职要求：
1、对新知识有兴趣并有较强的学习能力；
2、能够尽快入职、长期稳定工作；
3、年龄18-30岁之间，条件优秀者可相应放宽。不符合条件者勿扰（非中介，非保险）；
工作时间：
1、上班9:00—下班6:00；
2、六日双休，五险一金，带薪年假，法定节假日等；
3、可提供住宿或就近安排分工作地点；
4、实习期一到三个月，转正后薪资4K--6K不等。

工作地址：
天津市南开区红旗路桂荷园22-4-201号科技园天津塘沽新村街营口道泛华国际大厦
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
上市公司/网络工程师助理（五险一金+双休）
天津金珑基科技有限责任公司
创业公司五险一金年底双薪绩效奖金加班补助全勤奖餐补节日福利
**********
福利:
创业公司
五险一金
年底双薪
绩效奖金
加班补助
全勤奖
餐补
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：2人
职位类别：助理/秘书/文员
**********
岗位职责：
1、负责公司内部局域网络维护；
2、进行日常打印机、投影仪、服务器、路由器等办公设备管理以及网络平台的运行监控和维护；
3、负责内部信息系统的维护，后台数据和OA管理；
4、负责公司内、外的信息传输和交流，做好数据维护、数据库管理及数据库备份。
应聘条件：
1、能够尽快入职(或者一个月左右能够到岗工作)；
2、能长期稳定工作（不招兼职）；
3、年龄18-30岁之间，经验不限，专业不限；
待遇：
1、底薪+奖金=3000-6000（根据个人能力提升）；
2、五险一金，带薪年假，双休，节日福利，有餐补等；
3、可提供住宿或者就近安排工作地点；
4、试用期1-3个月（根据个人能力）转正后享有平均月薪不低于4000元/月收入。
工作时间：
1、国家法定作息时间；
2、周末双休，上9:00下6:00，中午一小时午休时间。
待遇优厚，试用期一到三个月，试用期间上五险一金，周末双休，有餐补，办公环境优越，季度旅游,法定节假日~！有良好的发展及晋升空间
入职后：公司组织完善培训计划，新员工有老员工带领

工作地址：
天津塘沽新村街营口道泛华国际大厦
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
客服文员+五险一金+双休
天津金珑基科技有限责任公司
五险一金加班补助全勤奖餐补
**********
福利:
五险一金
加班补助
全勤奖
餐补
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：客户服务专员/助理
**********
岗位职责
1.负责公司现有客户及潜在客户的电话咨询及售前售后服务 ; 
2.负责公司合作伙伴的来电咨询; 
3.负责部分外呼回访工作，如新客户的满意度了解; 
应聘条件：
1、能够尽快入职(或者一个月左右能够到岗工作)；
2、能长期稳定工作；
3、经验不限，专业不限；
待遇：
2、五险一金，带薪年假，双休，节日福利，有餐补等；
3、可提供住宿或者就近安排工作地点；
4、试用期1-3个月（根据个人能力）转正后享有平均月薪不低于3000元/月收入。
工作时间：
1、国家法定作息时间；
2、周末双休，上9:00下6:00，中午一小时午休时间。
公司招揽综合素质能力贤才，组织完善培训计划，工作经验不足者有老员工培养，并且公司提供全方位的办公环境和设施设备。
待遇优厚，试用期三个月，试用期间上五险一金，周末双休，有餐补，办公环境优越，节日福利，法定节假日~！有良好的发展及晋升空间。
应聘者可投递简历，人事部将在3个工作日内安排面试时间
地址：天津塘沽外滩
：
工作地址：
天津塘沽外滩
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
C语言软件开发工程师助理+五险一金
天津金珑基科技有限责任公司
五险一金全勤奖包住餐补节日福利
**********
福利:
五险一金
全勤奖
包住
餐补
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：2人
职位类别：C语言开发工程师
**********
岗位职责：
1.负责项目的需求分析、技术调研、开发及解决问题；
2、团队协作共同完成项目，并及时与用户及其他相关部门沟通协作；
3、为市场、技术部提供相应的技术支持；
4.可零基础,喜爱IT行业 入职会有老员工带
任职要求：
1、能够尽快入职(或者一个月左右能够到岗工作)；
2、能长期稳定工作；
3、年龄18-30岁之间，经验不限，专业不限；
待遇：
1、底薪+奖金=3000-6000（根据个人能力提升）；
2、五险一金，带薪年假，双休，节日福利，有餐补等；
3、可提供住宿或者就近安排工作地点 交通便利；
4、试用期1-3个月（根据个人能力）转正后享有平均月薪不低于3000元/月收入。
工作时间：
1、国家法定作息时间；
2、周末双休，上9:00下6:00，中午一小时午休时间。

工作地址：
天津塘沽外滩
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
网络维护工程师助理+五险一金+双休
天津金珑基科技有限责任公司
五险一金加班补助全勤奖餐补
**********
福利:
五险一金
加班补助
全勤奖
餐补
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：3人
职位类别：网络工程师
**********
应聘条件：
1、能够尽快入职(或者一个月左右能够到岗工作)；
2、能长期稳定工作；
3、年龄18-30岁之间，经验不限，专业不限；
待遇：
1、底薪+奖金=3000-8000（根据个人能力提升）
2、五险一金，带薪年假，节日福利，有餐补等；
3、试用期1-3个月，转正后享有平均月薪不低于4000元/月收入
工作时间：
1、国家法定作息时间
2、周末双休，上9:00下6:00，中午一小时午休时间。
公司招揽综合素质能力贤才，组织完善培训计划，工作经验不足者有老员工培养，并且公司提供全方位的办公环境和设施设备。
待遇优厚，试用期三个月，试用期间上五险一金，周末双休，有餐补，办公环境优越，节日福利，法定节假日~！有良好的发展及晋升空间。
应聘者可投递简历，人事部将在3个工作日内安排面试时间,谢谢合作。
天津塘沽外滩
工作地址：
天津塘沽外滩
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
资料管理员（双休）餐补
天津金珑基科技有限责任公司
五险一金餐补带薪年假节日福利不加班年底双薪
**********
福利:
五险一金
餐补
带薪年假
节日福利
不加班
年底双薪
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：2人
职位类别：文档/资料管理
**********
岗位职责： 
1.公司资料录入与调出； 
2.文件材料整理、归档； 
3.工时的录入、整理； 
4.领导交办的其他事项。 
任职要求：
1.18-28周岁，中专以上学历； 
2.熟练操作办公软件； 
3.性格稳重，责任心强。
待遇：
1、底薪+奖金=3000-6000（根据个人能力提升）
2、五险一金，带薪年假，节日福利，可提供住宿，有餐补等；
3、试用期1-3个月，转正后享有平均月薪不低于4000元/月收入
工作时间：
1、国家法定作息时间
2、周末双休，上9:00下6:00，中午一小时午休时间。

工作地址：
天津塘沽新村街营口道泛华国际大厦
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
行政助理+五险一金
天津金珑基科技有限责任公司
五险一金加班补助餐补
**********
福利:
五险一金
加班补助
餐补
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：行政专员/助理
**********
岗位职责：
1.熟悉office等办公软件的使用；
2、有无相关基础均可，应届毕业生优先前期老员工代
应聘条件：
1、能够尽快入职(或者一个月左右能够到岗工作)；
2、能长期稳定工作；
3、年龄18-30岁之间，经验不限，专业不限；
4、美国上市集团总公司——注重个人综合素质及能力，目前正在招收应届生及实习生。
待遇：
1、底薪+奖金=3000-6000（根据个人能力提升）；
2、五险一金，带薪年假，双休，节日福利，有餐补等；
3、可提供住宿或者就近安排工作地点；
4、试用期1-3个月（根据个人能力）转正后享有平均月薪不低于3000元/月收入。
工作时间：
1、国家法定作息时间；
2、周末双休，上9:00下6:00，中午一小时午休时间。
公司招揽综合素质能力贤才，组织完善培训计划，工作经验不足者有老员工培养，并且公司提供全方位的办公环境和设施设备。
待遇优厚，试用期三个月，试用期间上五险一金，周末双休，有餐补，办公环境优越，节日福利，法定节假日~！有良好的发展及晋升空间。
应聘者可投递简历，人事部将在3个工作日内安排面试时间,或在右下角在线预约面试时间，并留下你的姓名+学历+年龄+电话，谢谢合作。
地址：天津塘沽外滩

工作地址：
天津塘沽外滩
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
资深文案
红鹤沟通机构
**********
福利:
**********
职位月薪：8001-10000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：1人
职位类别：广告文案策划
**********
主要工作职责
1）项目文字工作的创意提出、专业指导或实际执行；
2）承担项目执行过程中的文字表现；
3）与美术设计共同完成所负责项目之创意表现，包括稿件或提案说明；
4）与流程制管人员的工作衔接，完稿文字把控；
5）参与项目提案，以语言和书面的形式向客户阐述文案创作思路；
6）对文案提供经验和方法的支持和指导；
7）其他与文字有关的创意工作。
任职资格
1）专科以上学历，文学或艺术相关专业；
2）五年以上相关工作经验；
3）极强的心理洞察力；
4）熟练操作Word PPT，简单操作设计软件；
5）擅于归纳总结概念，文笔犀利独道，讲求修辞话语方式；
6）具备将创意发展为策略的能力；
7）具备丰富的项目实际操作经验。
  工作地址：
天津市南开区南京路309号环球置地广场1001-1003
**********
红鹤沟通机构
公司规模：
100-499人
公司性质：
民营
公司行业：
广告/会展/公关
公司主页：
http://www.chinaflamingo.ncom
公司地址：
北京市朝阳区酒仙桥北路9号恒通国际创新园C8F
查看公司地图
**********
游戏测试助理（五险一金）
天津金珑基科技有限责任公司
五险一金年底双薪加班补助餐补节日福利
**********
福利:
五险一金
年底双薪
加班补助
餐补
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：2人
职位类别：助理/秘书/文员
**********
岗位职责：
1.完成游戏的各项测试任务，确保质量；
2.与需求部门深入沟通，分析测试需求、制定测试计划、设计测试案例；
3.执行测试任务，协调研发人员定位并协助解决问题；
4.BUG跟踪反馈。
应聘条件：
1、能够尽快入职或一个月左右入职；
2、能长期稳定工作
3、年龄18-30岁之间，经验不限，计算机相关专业优先；
4、对计算机互联网行业感兴趣。
待遇：
1、底薪+奖金=4000--6000（根据个人能力提升）
2、五险一金，带薪年假，节日福利，双休，有餐补等；
3、员工可提供住宿（也可就近分配）
4、试用期1-3个月，转正后享有平均月薪不低于3000元/月收入。
工作时间：
1、国家法定作息时间；
2、周末双休，上9:00下6:00，中午一小时午休时间。
工作地址：
天津塘沽新村街营口道泛华国际大厦
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
（塘沽）计算机文员+五险一金+双休+餐补
天津金珑基科技有限责任公司
五险一金年底双薪加班补助餐补节日福利
**********
福利:
五险一金
年底双薪
加班补助
餐补
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：2人
职位类别：电脑操作/打字/录入员
**********
岗位职责：
1、配合部门经理从事辅助的工作（例如文件的整理，报表统计，会议纪要等）；
2、协助技术人员从事OA协同操作，配合技术员做些数据统计，数据分析，写数据分析报告
3、配合部门同事做些辅助类的计算机电脑操作，帮助他们完成工作，减轻他们的工作量和工作负担
4、能够积极配合工作安排；
任职要求：(前期有人带）
1、对新知识有兴趣并有较强的学习能力，计算机或相关专业优先；
2、能够尽快入职、长期稳定工作；
3、年龄18-30岁之间，条件优秀者可相应放宽。不符合条件者勿扰（非中介，非保险）；
工作时间：
1、上班9:00—下班6:00；法定节假日休息；
2、六日双休，五险一金，带薪年假，双休等；
3、员工可提供住宿或就近安排工作；
4、实习期一到三个月，转正后薪资4K--6K不等；
工作地址：
天津塘沽新村街营口道泛华国际大厦
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
办公室文员（双休）
天津金珑基科技有限责任公司
五险一金年底双薪绩效奖金餐补带薪年假节日福利不加班
**********
福利:
五险一金
年底双薪
绩效奖金
餐补
带薪年假
节日福利
不加班
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：2人
职位类别：助理/秘书/文员
**********
岗位职责：
1、及时准确的更新员工通讯录；管理公司网络、邮箱；
2、订阅年度报刊杂志，收发日常报刊杂志及交换邮件；
3、员工考勤系统维护、考勤统计及外出人员管理。
应聘条件：
1、能够尽快入职(或者一个月左右能够到岗工作)；
2、能长期稳定工作；
3、年龄18-28岁之间，经验不限，专业不限（非销售，非保险）；
4、注重个人综合素质及能力，目前正在招收应届生及实习生。
待遇：
1、底薪+奖金=3000-6000（根据个人能力提升）；
2、五险一金，带薪年假，双休，节日福利，有餐补等；
3、可提供住宿或者就近安排工作地点；
4、试用期1-3个月（根据个人能力）转正后享有平均月薪不低于4000元/月收入。
工作时间：
1、国家法定作息时间；
2、周末双休，上9:00下6:00，中午一小时午休时间。
待遇优厚，试用期三个月，试用期间上五险一金，周末双休，有餐补，办公环境优越，节日福利，法定节假日~！有良好的发展及晋升空间。
应聘者可投递简历，人事部将在3个工作日内安排面试时间。

工作地址：
天津塘沽新村街营口道泛华国际大厦
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
WEB前端开发助理+五险一金
天津金珑基科技有限责任公司
五险一金加班补助餐补
**********
福利:
五险一金
加班补助
餐补
**********
职位月薪：4000-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：2人
职位类别：WEB前端开发
**********
任职要求：
1、能够尽快入职(或者一个月左右能够到岗工作)；
2、能长期稳定工作；
3、年龄18-30岁之间，经验不限，专业不限；
4、美国上市集团总公司——注重个人综合素质及能力，目前正在招收应届生及实习生。
待遇：
1、底薪+奖金=3000-6000（根据个人能力提升）；
2、五险一金，带薪年假，双休，节日福利，有餐补等；
3、可提供住宿或者就近安排工作地点；
4、试用期1-3个月（根据个人能力）转正后享有平均月薪不低于3000元/月收入。
工作时间：
1、国家法定作息时间；
2、周末双休，上9:00下6:00，中午一小时午休时间。
公司招揽综合素质能力贤才，组织完善培训计划，工作经验不足者有老员工培养，并且公司提供全方位的办公环境和设施设备。
待遇优厚，试用期三个月，试用期间上五险一金，周末双休，有餐补，办公环境优越，节日福利，法定节假日~！有良好的发展及晋升空间。
应聘者可投递简历，人事部将在3个工作日内安排面试时间,或在右下角在线预约面试时间，并留下你的姓名+学历+年龄+电话，谢谢合作。
工作地址
天津塘沽外滩

工作地址：
天津塘沽外滩
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
培训专员
天津艺点意创科技有限公司
创业公司五险一金带薪年假
**********
福利:
创业公司
五险一金
带薪年假
**********
职位月薪：4500-6000元/月 
工作地点：天津-红桥区
发布日期：最近
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：培训专员/助理
**********
岗位职责：
1、参与调查了解公司内部培训需求，会同上级共同确认需求；
2、协助实施公司培训计划，做好培训记录并对学员意见进行收集反馈；
3、整理各项培训资料、归档及统计相关数据，填写培训报表及其他报表，维护和更新培训档案系统；
4、组织培训材料，开发利用培训辅助设施；协助各相关部门贯彻落实各项培训项目；
5、根据部门任务要求，搜集相关信息，组织相关工作的各项准备工作。
任职要求：
1、大专以上学历，2年以上工作经验；
2、熟悉培训工作流程，能独立开展或主导培训工作；
3、工作严谨、责任心强，善于与人沟通，具有团队合作精神。


工作地址：
天津市红桥区光荣道宝能创业中心A座24层
**********
天津艺点意创科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市红桥区光荣道宝能创业中心A座24层
**********
Java开发工程师助理+五险一金+双休
天津金珑基科技有限责任公司
五险一金加班补助餐补
**********
福利:
五险一金
加班补助
餐补
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：Java开发工程师
**********
任职要求：
1、能够尽快入职(或者一个月左右能够到岗工作)；
2、能长期稳定工作；
3、年龄18-30岁之间，经验不限，专业不限；
4、美国上市集团总公司——注重个人综合素质及能力，目前正在招收应届生及实习生。
待遇：
1、底薪+奖金=3000-6000（根据个人能力提升）；
2、五险一金，带薪年假，双休，节日福利，有餐补等；
3、可提供住宿或者就近安排工作地点；
4、试用期1-3个月（根据个人能力）转正后享有平均月薪不低于3000元/月收入。
工作时间：
1、国家法定作息时间；
2、周末双休，上9:00下6:00，中午一小时午休时间。
公司招揽综合素质能力贤才，组织完善培训计划，工作经验不足者有老员工培养，并且公司提供全方位的办公环境和设施设备。
待遇优厚，试用期三个月，试用期间上五险一金，周末双休，有餐补，办公环境优越，节日福利，法定节假日~！有良好的发展及晋升空间。
应聘者可投递简历，人事部将在3个工作日内安排面试时间,或在右下角在线预约面试时间，并留下你的姓名+学历+年龄+电话，谢谢合作。
工作地址
天津塘沽外滩

工作地址：
天津塘沽外滩
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
诚诚诚！诚聘产品运营，待遇优厚，奖金丰富
天津金珑基科技有限责任公司
创业公司五险一金年底双薪绩效奖金加班补助全勤奖餐补节日福利
**********
福利:
创业公司
五险一金
年底双薪
绩效奖金
加班补助
全勤奖
餐补
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：产品运营
**********
岗位职责：
1、负责制定产品运营策略，根据数据表现策划运营活动。
2、负责相关产品的内容运营，能够洞察网上及社会流行热点。
3、负责产品相关产品的运营工作，主要包括：产品运营数据分析、客服渠道管理、用户反馈整理和跟进，协同产品经理提出产品功能方案、产品发展方案。
4、负责行业观察、竞品分析、定期输出分析报告。
任职要求：
1、能够尽快入职(或者一个月左右能够到岗工作)
2、能长期稳定工作（不招兼职）。          
3、年龄18-30岁之间，经验不限，专业不限
待遇
1、底薪+奖金=3000-6000（根据个人能力提升）
2、五险一金，带薪年假，双休，节日福利，有餐补等；
3、可提供住宿或者就近安排工作地点
4、试用期1-3个月，转正后享有平均月薪不低于4000元/月收入
工作时间：
1、国家法定作息时间
2、周末双休，上9:00下6:00，中午一小时午休时间。
不符合条件者，非诚勿扰
待遇优厚，试用期一到三个月，试用期间上五险一金，周末双休，有餐补，办公环境优越，季度旅游,法定节假日~！有良好的发展及晋升空间
入职后：公司组织完善培训计划，新员工有老员工带领

工作地址：
天津塘沽新村街营口道泛华国际大厦
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
UI设计助理(可应届)+双休
天津金珑基科技有限责任公司
五险一金全勤奖包住餐补节日福利
**********
福利:
五险一金
全勤奖
包住
餐补
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：2人
职位类别：用户界面（UI）设计
**********
应聘条件：
1、能够尽快入职(或者一个月左右能够到岗工作)；
2、能长期稳定工作；
3、年龄18-30岁之间，经验不限，专业不限；
待遇：
1、底薪+奖金=3000-6000（根据个人能力提升）；
2、五险一金，带薪年假，双休，节日福利，有餐补等；
3、可提供住宿或者就近安排工作地点 交通便利；
4、试用期1-3个月（根据个人能力）转正后享有平均月薪不低于3000元/月收入。
工作时间：
1、国家法定作息时间；
2、周末双休，上9:00下6:00，中午一小时午休时间。
公司招揽综合素质能力贤才，组织完善培训计划，工作经验不足者有老员工培养，并且公司提供全方位的办公环境和设施设备。
待遇优厚，试用期三个月，试用期间上五险一金，周末双休，有餐补，办公环境优越，节日福利，法定节假日~！有良好的发展及晋升空间。
应聘者可投递简历，人事部将在3个工作日内安排面试时间。
天津塘沽外滩

工作地址：
天津塘沽外滩
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
塘沽+内勤人员（双休、餐补、节假日福利）
天津金珑基科技有限责任公司
五险一金年底双薪绩效奖金餐补带薪年假节日福利不加班
**********
福利:
五险一金
年底双薪
绩效奖金
餐补
带薪年假
节日福利
不加班
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：3人
职位类别：内勤人员
**********
岗位职责：
1、办公室的财物管理，环境卫生管理及一般事物的管理。
2、负责做好有关会议的记录及会务工作，并根据需要整理会议纪要。
3、完成领导交办的其他临时性工作。
应聘条件：
1、能够尽快入职(或者一个月左右能够到岗工作)；
2、能长期稳定工作；
3、年龄18-30岁之间，经验不限，专业不限（非中介，非保险，非销售）；
4、目前正在招收应届生及实习生。
待遇：
1、底薪+奖金=3000-6000（根据个人能力提升）；
2、五险一金，带薪年假，双休，节日福利，有餐补等；
3、可提供住宿或者就近安排工作地点；
4、试用期1-3个月（根据个人能力）转正后享有平均月薪不低于4000元/月收入。
工作时间：
1、国家法定作息时间；
2、周末双休，上9:00下6:00，中午一小时午休时间。
有意向者可投递简历，人事审核通过会电话联系您，给我们一个机会，也给您一个机会！

工作地址：
天津塘沽新村街营口道泛华国际大厦
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
网站网页设计师助理（住宿+餐补）双休
天津金珑基科技有限责任公司
创业公司五险一金年底双薪绩效奖金加班补助全勤奖餐补节日福利
**********
福利:
创业公司
五险一金
年底双薪
绩效奖金
加班补助
全勤奖
餐补
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：2人
职位类别：助理/秘书/文员
**********
岗位职责： 
1.负责辅助设计师制定设计和整体方案
2.负责产品的制作图片和页面上传 
4.具备较强的学习能力、良好的沟通能力和优秀的团队合作精神 
5.负责现有网页走线提出合理化建议，完善用户体验。
 任职资格：
1、学历不限，专业不限，应届生优先
2、较强的创意，良好的文字表达能力，思维敏捷
3、工作认真，有责任心，踏实肯干，富有团队精神
4、本职位后期往设计师方向发展，从业意向坚定者可放宽专业、基础等要求：

薪资构成：基本工资4000起+奖金+岗位津贴+丰厚年终奖
社会保险：入职即上五险一金
休息时间：5天8小时工作制、朝九晚六，周末双休，法定节假日休息，带薪年假，带薪病假，带薪产假，带薪婚丧假
节日贺礼：传统佳节派发节日礼品以增添节日气氛。
生日派对：过生日的员工，有公司生日派对以表祝福
生活关怀：定期体检，公司设有员工休息室，提供微波炉、饮水机等便捷设备。办公环境：办公环境优美，可提供住宿或者就近安排工作地点。

应聘者可投递简历，人事部将在3个工作日内安排面试时间。

工作地址：
天津塘沽新村街营口道泛华国际大厦
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
底薪4000急招客服专员
天津典藏国一文化艺术交流有限公司
五险一金绩效奖金带薪年假弹性工作员工旅游节日福利
**********
福利:
五险一金
绩效奖金
带薪年假
弹性工作
员工旅游
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津-河东区
发布日期：最近
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：10人
职位类别：客户服务专员/助理
**********
岗位职责： 
1、将公司的活动以电话的方式通知给客户；起到一个邀约客户的作用；
2、公司客服岗位不涉及到任何销售，文职工作；  
任职资格：
1、五官端正，年龄在18-28，性别不限
2、普通话标准，沟通表达能力佳； 
3、良好的执行力和团队合作精神； 
4、熟悉电话客服或客户服务的业务模式,有联通、移动客服工作经验者优先。
薪资待遇：
1.无责任底薪3500-4000+绩效奖金（综合工资6000-8000左右），每周单休，法定节假日带薪休假；
2.在5A级办公楼工作，环境舒适；
3.公司不定期组织旅游和各种团体活动；
4工作氛围较轻松，开心工作，快乐赚钱。
工作地址：
天津市河东区津滨大道万达广场写字楼C座16层
**********
天津典藏国一文化艺术交流有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市河东区万达广场
查看公司地图
**********
微信推广运营+五险一金
天津金珑基科技有限责任公司
五险一金加班补助全勤奖包住餐补带薪年假弹性工作节日福利
**********
福利:
五险一金
加班补助
全勤奖
包住
餐补
带薪年假
弹性工作
节日福利
**********
职位月薪：3000-4000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：2人
职位类别：新媒体运营
**********
岗位职责：
1、负责客户需求的搜集与了解，研究客户产品与品牌的市场营销策略。
2、运用公司微信平台的营销功能结合客户需求进行线上活动及线下活动的策划及执行。
3、策划跟踪微信推广效果并对效果负责，分析数据并反馈，提交报告给公司领导。
4、进行日常的客户满意度调查。
任职要求：
1、能够尽快入职(或者一个月左右能够到岗工作)；
2、能长期稳定工作；
3、年龄18-30岁之间，经验不限，专业不限；
待遇：
1、底薪+奖金=3000-6000（根据个人能力提升）；
2、五险一金，带薪年假，双休，节日福利，有餐补等；
3、可提供住宿或者就近安排工作地点；
4、试用期1-3个月（根据个人能力）转正后享有平均月薪不低于3000元/月收入。
工作时间：
1、国家法定作息时间；
2、周末双休，上9:00下6:00，中午一小时午休时间。

工作地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
计算机助理文员（双休）
天津金珑基科技有限责任公司
五险一金年底双薪绩效奖金餐补带薪年假节日福利不加班
**********
福利:
五险一金
年底双薪
绩效奖金
餐补
带薪年假
节日福利
不加班
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：2人
职位类别：助理/秘书/文员
**********
应聘条件：
1、能够尽快入职或一个月左右入职。
2、能长期稳定工作（实习期至少4个月）。
3、专科及以上学历（优秀者可放宽条件）。
4、年龄18-30岁之间，经验不限，专业不限。
5、注重个人综合素质及能力，目前正在招收应届生及实习生。
待遇：
1、底薪+奖金=3000--8000（根据个人能力提升）
2、五险一金，带薪年假，节日福利，有餐补等；
3、外地员工可提供住宿或（可就近分配）。
4、试用期1-3个月（试用期上五险），转正后享有平均月薪不低于4000元/月收入
工作时间：
1、国家法定作息时间
2、周末双休，上9:00下6:00，中午一小时午休时间。
工作地址：
天津塘沽新村街营口道泛华国际大厦
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
销售
天津市北辰区世纪职业培训学校
五险一金绩效奖金加班补助全勤奖包住餐补员工旅游节日福利
**********
福利:
五险一金
绩效奖金
加班补助
全勤奖
包住
餐补
员工旅游
节日福利
**********
职位月薪：8001-10000元/月 
工作地点：天津-红桥区
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：5人
职位类别：销售代表
**********
正规民办学校，非教育中介
岗位职责：
有团队精神，带过销售团队或是有组建销售团队。
1、负责学校产品的销售及推广；
2、根据市场营销计划，完成部门销售指标；
3、开拓新市场,发展新客户,增加产品销售范围；
4、负责辖区市场信息的收集及竞争对手的分析；
5、负责销售区域内销售活动的策划和执行，完成销售任务；
6、管理维护客户关系以及客户间的长期战略合作计划。
任职资格：
1、大专及以上学历，市场营销等相关专业；
2、3-5年以上销售行业工作经验，教育行业业绩突出者优先；
3、反应敏捷、表达能力强，具有较强的沟通能力及交际技巧，具有亲和力；
4、具备一定的市场分析及判断能力，良好的客户服务意识；
5、有责任心，能承受较大的工作压力；
6、有团队协作精神，有担当，善于挑战。

工作地址：
天津市红桥区金兴科技大厦4楼
查看职位地图
**********
天津市北辰区世纪职业培训学校
公司规模：
20-99人
公司性质：
民营
公司行业：
教育/培训/院校
公司地址：
天津市北辰区京津公路北辰大厦2号楼13层
**********
会展策划设计助理+双休+可实习
天津金珑基科技有限责任公司
每年多次调薪五险一金年终分红餐补带薪年假节日福利不加班
**********
福利:
每年多次调薪
五险一金
年终分红
餐补
带薪年假
节日福利
不加班
**********
职位月薪：3001-5000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：4人
职位类别：其他
**********
应聘条件：（不招兼职）
1、年龄18-30岁之间，性别不限，经验不限，专业不限。
2、有责任心及工作进取心。
3、思维活跃、洞察力强、富有创意，性格开朗，勤奋好学，乐于思考，具有较强的责任心和学习能力。
4、美国上市集团总公司———注重个人综合素质及能力，目前正在招收应届生及实习生
待遇：
1、底薪+奖金=3000-6000（根据个人能力提升）
2、五险一金，带薪年假，节日福利，有餐补等；
3、试用期1-3个月，转正后享有平均月薪不低于3000元/月收入
工作时间：
1、国家法定作息时间
2、周末双休，上9:00下6:00，中午一小时午休时间。
不符合条件者，非诚勿扰
工作地址：
天津塘沽新村街营口道
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
资料管理员（双休餐补）非销售非保险
天津金珑基科技有限责任公司
五险一金年底双薪绩效奖金餐补带薪年假节日福利不加班
**********
福利:
五险一金
年底双薪
绩效奖金
餐补
带薪年假
节日福利
不加班
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：2人
职位类别：图书管理员
**********
岗位职责：
1．负责收集公司分散在各个部门和个人手中的文件、资料集中起来，经过整理、立卷、当档保存； 
2．做好公司立卷档案的鉴定和保存期限； 
3．负责对档案的收进、移交、保管、利用、销毁等情况随时以表册、数字形 
式，进行登记和统计； 
4．负责保管档案系统完整和安全。
福利待遇：
1、试用期1-3个月，试用期期间上五险一金；
2、带薪年假，节日福利，可提供住宿，有餐补，双休等；
3、不加班，不出外勤。
工作时间：
1、国家法定作息时间
2、周末双休，上9:00下6:00，中午一小时午休时间。

工作地址：
天津塘沽新村街营口道泛华国际大厦
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
医学内容编辑
北京纵横无双科技有限公司
**********
福利:
**********
职位月薪：6000-8000元/月 
工作地点：天津-河北区
发布日期：最近
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：文字编辑/组稿
**********
岗位职责：
1、根据公司各内容输出渠道的不同定位，把控医学内容的输出质量和形式。
2、将枯燥的科普知识展现给读者，为网站内容提供专业医学学术支持和服务。
3、关注医疗圈与医生圈动态，配合相关部门进行医疗相关产业布局。
4、负责医学相关宣传文案的编写、整理及更新，并从医学角度配合线上宣传活动。
 任职条件：
1. 医学专业背景，同时在健康医疗网站有工作经验（优先考虑）本科及以上学历。
2. 具有创新思维，有较强的文字撰写和信息采编能力。
3. 有责任心及较强的执行力，具有良好的沟通能力和团队协作意识。
4. 良好的语言表达能力，了解医学专业名词。



工作地址：
河北区曙光路曙光生活广场3层（三号线铁东路地铁站D口）
**********
北京纵横无双科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
互联网/电子商务
公司地址：
北京市海淀区中关村
**********
医学顾问
北京纵横无双科技有限公司
五险一金节日福利
**********
福利:
五险一金
节日福利
**********
职位月薪：6000-8000元/月 
工作地点：天津
发布日期：最近
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：文字编辑/组稿
**********
岗位职责：
1、负责医学专家访谈视频相关文案的编写、整理及更新，了解医学名词。
2、以幽默、清新等风格将枯燥的科普知识展现给读者；为网站内容提供专业医学学术支持和服务。
3、根据公司各内容输出渠道的不同定位，编辑文章，确保内容精良、真实且符合要求。

任职条件：
1、医学专业背景，同时在健康医疗网站有工作经验（优先考虑）大专及以上学历。
2、具有创新思维，有较强的文字撰写和信息采编能力。
3、有责任心及较强的执行力，具有良好的沟通能力和团队协作意识。
4、良好的语言表达能力，了解医学专业名词。
工作地址：
河北区曙光路曙光生活广场3层（三号线铁东路地铁站D口）
**********
北京纵横无双科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
互联网/电子商务
公司地址：
北京市海淀区中关村
**********
原画设计/双休+可实习
天津金珑基科技有限责任公司
每年多次调薪五险一金年终分红餐补带薪年假节日福利不加班
**********
福利:
每年多次调薪
五险一金
年终分红
餐补
带薪年假
节日福利
不加班
**********
职位月薪：3001-5000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：3人
职位类别：原画师
**********
岗位职责：
1、能简单使用，了解 PS,AI,PT 等作图修图软件
2.对设计方面感兴趣，有良好的沟通表达能力，富有创造能力
任职资格：
1.能够尽快入职(或者一个月左右能到岗工作)
2.能长期稳定工作(不招兼职)
3.年龄在18-30岁之间 ，经验不限，专业不限。
4.美国上市集团总公司----注重个人综合素质技及能力，目前正在招收应届毕业生。
岗位福利待遇:
1.底薪+奖金=3000-6000
2.五险一金，带薪年假，双休，节日有福利，有餐补。
3.可提供住宿或者就近安排工作地点
4.试用期1-3个月，转正后享有平均立新不低3000/每个月
5.实习期间有五险一金
6.公司有季度旅游
7.有法定节假日
工作时间：
1.国家法定作息时间
2.周末双休，上9下6，中午一个小时休息时间
3.公司组织完善培训计划，新员工有老员工带领

工作地址：
天津塘沽新村街营口道
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
文案
红鹤沟通机构
**********
福利:
**********
职位月薪：5000-8000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：广告文案策划
**********
主要工作职责
1）项目文字工作的创意提出与实际执行；
2）承担有关平面、立体、印刷、包装、POP等设计上之文字表现；
3）与美术设计共同完成所负责项目之创意表现，包括稿件或提案说明；
4）与流程制管人员的工作衔接，完稿文字把控；
5）与品牌策略人员进行项目具体策略探讨，并进行相关撰文创意；
6）其他与文字有关的创意工作。
 任职资格
1）专科以上学历，文学或艺术相关专业；
2）1-3年以上相关工作经验；
3）极强的心理洞察力；
4）熟练操作Word PPT，简单操作设计软件；
5）擅于归纳总结概念，文笔犀利独道，讲求修辞话语方式；
6）具备将创意发展为策略的能力。
  工作地址：
天津市南开区东马路129号仁恒置地国际中心8层806
**********
红鹤沟通机构
公司规模：
100-499人
公司性质：
民营
公司行业：
广告/会展/公关
公司主页：
http://www.chinaflamingo.ncom
公司地址：
北京市朝阳区酒仙桥北路9号恒通国际创新园C8F
查看公司地图
**********
月薪8000起急招店内销售（有无经验均可）
天津典藏国一文化艺术交流有限公司
五险一金年底双薪带薪年假员工旅游
**********
福利:
五险一金
年底双薪
带薪年假
员工旅游
**********
职位月薪：8001-10000元/月 
工作地点：天津
发布日期：最近
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：6人
职位类别：电话销售
**********
岗位职责： 
1、客户来到公司负责接待，向客户讲解公司的产品知识； 
2、工作环境优越，无需外出；
3、无责任底薪3500+高提成，综合工资在8000-3万上，五险+带薪年假，公司不定期举   行员工旅游，国家法定节假日均可享受带薪休假。
4、负责销售区域内销售活动的策划和执行，完成销售任务； 
5、管理维护客户关系以及客户间的长期战略合作计划。 
任职资格： 
1、高中以上学历，年龄在20-35岁，市场营销等相关专业者优先； 
2、有从事过销售行业工作者优先； 
3、具有亲和力，性格开朗，热爱和人交流；
4、具备一定的市场分析及判断能力，良好的客户服务意识； 
5、有团队协作精神，善于挑战。

工作地址
天津市河东区津滨大道万达广场写字楼C座16层

工作地址：
天津市河东区万达广场C座
**********
天津典藏国一文化艺术交流有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市河东区万达广场
查看公司地图
**********
资料管理员（内勤+可实习待遇优）
天津金珑基科技有限责任公司
每年多次调薪五险一金年终分红餐补带薪年假节日福利不加班
**********
福利:
每年多次调薪
五险一金
年终分红
餐补
带薪年假
节日福利
不加班
**********
职位月薪：3001-5000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：2人
职位类别：其他
**********
岗位职责：
1．负责收集公司分散在各个部门和个人手中的文件、资料集中起来，经过整理、立卷、当档保存； 
2．做好公司立卷档案的鉴定和保存期限； 
3．负责对档案的收进、移交、保管、利用、销毁等情况随时以表册、数字形 
式，进行登记和统计； 
4．负责保管档案系统完整和安全。
福利待遇：
1、试用期1-3个月，试用期期间上五险一金；
2、带薪年假，节日福利，可提供住宿，有餐补，双休等；
3、不加班，不出外勤。
工作时间：
1、国家法定作息时间
2、周末双休，上9:00下6:00，中午一小时午休时间。

工作地址：
天津塘沽新村街营口道
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
软件测试助理（五险一金）
天津金珑基科技有限责任公司
五险一金年底双薪绩效奖金餐补带薪年假节日福利不加班
**********
福利:
五险一金
年底双薪
绩效奖金
餐补
带薪年假
节日福利
不加班
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：3人
职位类别：软件测试
**********
岗位职责：
1、协助测试工程师搭建和维护测试环境；
2、执行测试，并提交缺陷；
3、评审测试文档
4、完成上级领导交代的其他事宜。
任职要求：
1、18-30岁，大专以上学历，理工类专业优先；
2、能长期全职工作（大学实习要求至少四个月）；
3、积极主动、踏实严谨、勤奋好学，热爱测试工作；
4、欢迎应届毕业生加入。
工作时间：
1、国家法定作息时间
2、周末双休，上9:00下6:00，中午一小时午休时间。

工作地址：
天津塘沽新村街营口道泛华国际大厦
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
文档数据管理员（六日双休）
天津金珑基科技有限责任公司
创业公司五险一金年底双薪绩效奖金加班补助全勤奖餐补节日福利
**********
福利:
创业公司
五险一金
年底双薪
绩效奖金
加班补助
全勤奖
餐补
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：文档/资料管理
**********
岗位职责：
1、负责做好公司档案的收集、建档、调阅、管理；
2、负责文件、通知、资料的收集整理及时归档；
3、负责与各部门沟通，办理文件资料转移手续，经过整理，归档保存；
4、完成领导交办的临时性工作。
任职要求：
1、能够尽快入职(或者一个月左右能够到岗工作)
2、能长期稳定工作（不招兼职）。
3、年龄18-30岁之间，经验不限，专业不限，优秀者可适当放宽条件。
待遇
1、底薪+奖金=3000-6000（根据个人能力提升）
2、五险一金，带薪年假，双休，节日福利，有餐补等；
3、可提供住宿或者就近安排工作地点
4、试用期1-3个月，转正后享有平均月薪不低于3000元/月收入
工作时间：
1、国家法定作息时间
2、周末双休，上9:00下6:00，中午一小时午休时间。
不符合条件者，非诚勿扰
待遇优厚，试用期一到三个月，试用期间上五险一金，周末双休，有餐补，办公环境优越，季度旅游,法定节假日~！有良好的发展及晋升空间
入职后：公司组织完善培训计划，新员工有老员工带领

工作地址：
天津塘沽新村街营口道泛华国际大厦
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
高级销售经理
天津艺点意创科技有限公司
五险一金年底双薪绩效奖金带薪年假节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
带薪年假
节日福利
**********
职位月薪：10001-15000元/月 
工作地点：天津-红桥区
发布日期：最近
工作性质：全职
工作经验：5-10年
最低学历：大专
招聘人数：1人
职位类别：大客户销售经理
**********
岗位职责：
1、根据公司的发展战略进行新客户开发和客户关系维护；
2、向客户提供专业、个性化产品推荐服务，帮助客户制定购买方案，最终促成购买意向达成；
3、熟悉传媒公司的业务产品，拥有一定的客户资源；
4、为客户提供最专业的综合性服务，提升客户的满意度；

任职资格：
1、5年以上销售经验，有广告行业背景，能独立完成商务流程；
2、销售导向，拓展业务能力强，有一定的客户资源；
3、具有较强的沟通协调能力，良好的服务意识，敏锐的市场触觉；
工作地址：
天津市红桥区光荣道宝能创业中心A座24层
**********
天津艺点意创科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市红桥区光荣道宝能创业中心A座24层
**********
平面设计师助理+五险一金
天津金珑基科技有限责任公司
五险一金全勤奖包住餐补节日福利
**********
福利:
五险一金
全勤奖
包住
餐补
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：2人
职位类别：平面设计
**********
岗位职责：
1.协助设计人员，查找资料
2.协商设计人员，进行简单的设计
应聘条件：
1、能够尽快入职；
2、能长期稳定工作
3、年龄18-30岁之间，经验不限，专业不限；
待遇：
1、底薪+奖金=3000-6000（根据个人能力提升）；
2、五险一金，带薪年假，双休，节日福利，有餐补等；
3、可提供住宿或者就近安排工作地点；
4.公司地点优  交通便利
4、试用期1-3个月（根据个人能力）转正后享有平均月薪不低于3000元/月收入。
工作时间：
1、国家法定作息时间；
2、周末双休，上9:00下6:00，中午一小时午休时间。


工作地址：
天津塘沽外滩
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
UI设计助理 4K餐补
天津金珑基科技有限责任公司
五险一金绩效奖金加班补助包住餐补带薪年假节日福利
**********
福利:
五险一金
绩效奖金
加班补助
包住
餐补
带薪年假
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：用户界面（UI）设计
**********
任职资格：
1.年龄18-28岁，大专及以上学历，善于与人交流，表达清晰、亲和力，喜欢互联网设计行业；
2.有优秀的学习能力、有较强的组织、协调、执行、沟通能力及人际交往能力；
3.工作踏实稳重，有管理能力，可承担一定压力；
4.设计相关专业优先，转行和无经验者也可；
5.非专业的可以带薪培训.
福利待遇：
1、工作时间：上九下六，8小时工作制，双休，餐补；
2、节假日福利，节假日正常放假；
3、转正后缴纳五险一金，享受带薪年假；法定节假日；
工作地址：
天津
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
python助理人工智能(五险一金零基础可应届)
天津金珑基科技有限责任公司
五险一金加班补助全勤奖包住餐补带薪年假弹性工作节日福利
**********
福利:
五险一金
加班补助
全勤奖
包住
餐补
带薪年假
弹性工作
节日福利
**********
职位月薪：3500-5000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：软件研发工程师
**********
应聘条件：
1、能够尽快入职(或者一个月左右能够到岗工作)；
2、能长期稳定工作
3、年龄18-30岁之间，经验不限，专业不限；
4、可应届 可实习 
待遇：
1、底薪+奖金=3000-5000（根据个人能力提升）；
2、入职有五险一金，带薪年假，双休，节日福利，有餐补等；
3、可提供住宿或者就近安排工作地点；
4、试用期1-3个月（根据个人能力）转正后享有平均月薪不低于3000元/月收入。
工作时间：
1、国家法定作息时间；
2、周末双休，上9:00下6:00，中午一小时午休时间。
工作经验不足者有老员工培养，并且公司提供全方位的办公环境和设施设备，待遇优厚，试用期三个月.
应聘者可投递简历，人事部将在3个工作日内安排面试时间
工作地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
信息专员（滨海新区/非销售待遇优）
天津金珑基科技有限责任公司
每年多次调薪五险一金年终分红餐补带薪年假节日福利不加班
**********
福利:
每年多次调薪
五险一金
年终分红
餐补
带薪年假
节日福利
不加班
**********
职位月薪：2001-4000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：2人
职位类别：其他
**********
岗位职责：
1.负责技术部信息录入，信息统计，数据分析，撰写数据分析报告
2.定期查看数据库，进行数据清理修改，保证数据有效性
3.配合技术员从事些简单的计算机电脑操作，减轻他们的工作量和负担
任职要求：(前期有人带）
1、对新知识有兴趣并有较强的学习能力，计算机或相关专业优先；
2、能够尽快入职、长期稳定工作；
3、年龄18-30岁之间，条件优秀者可相应放宽。不符合条件者勿扰（非中介，非保险）；
工作时间：
1、上班9:00—下班6:00；
2、六日双休，五险一金，带休年假，法定节假日等；
3、外地员工可提供住宿；
4、实习期一到三个月，转正后薪资4K--6K不等；

工作地址：
天津塘沽新村街营口道
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
软件测试员助理+五险一金
天津金珑基科技有限责任公司
五险一金全勤奖包住餐补节日福利
**********
福利:
五险一金
全勤奖
包住
餐补
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：2017-11-26 09:11:44
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：软件工程师
**********
岗位职责：
1、学习能力强，善于思考总结，工作认真、责任心强； 
2、能有协助测试专员完成相关工作。 
应聘条件： 
1、能够尽快入职；
2、能长期稳定工作； 
3、年龄18-30岁之间，经验不限，专业不限；  
待遇： 
1、底薪+奖金=3000-6000（根据个人能力提升）；
2、五险一金，带薪年假，双休，节日福利，有餐补等；
3、可提供住宿或者就近安排工作地点 交通便利；
4、试用期1-3个月（根据个人能力）转正后享有平均月薪不低于3000元/月收入。
 工作时间：
 1、国家法定作息时间；
 2、周末双休，上9:00下6:00，中午一小时午休时间。
待遇优厚，试用期三个月，试用期间上五险一金，周末双休，有餐补，办公环境优越，节日福利，法定节假日~！有良好的发展及晋升空间。
有意者请投递简历 人事将在三个工作日联系您

工作地址：
天津塘沽外滩
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
系统测试助理（应届生）餐补
天津金珑基科技有限责任公司
每年多次调薪五险一金年终分红餐补带薪年假节日福利不加班
**********
福利:
每年多次调薪
五险一金
年终分红
餐补
带薪年假
节日福利
不加班
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：3人
职位类别：其他
**********
岗位职责：
1、协助完成系统特性测试方案和测试用例的执行，写测试报告并对Bug进行跟踪；
2、承担系统测试；
3、协助解决产品在市场应用中遇到的问题；
4、参加产品的各种评测选型；
6、部门安排的其它测试相关工作。
应聘条件：
1、能够尽快入职或一个月左右入职；
2、能长期稳定工作；
3、本科及以上学历；
4、年龄18-28岁之间，经验不限，专业不限；
5、目前正在招收应届生及实习生（实习至少四个月）
待遇：
1、底薪+奖金=4000--6000（根据个人能力提升）
2、五险一金，带薪年假，节日福利，有餐补等；
3、外地员工可提供住宿或（可就近分配）。
4、试用期1-3个月（入职即上五险），转正后享有平均月薪不低于4000元/月收入
工作时间：
1、国家法定作息时间
2、周末双休，上9:00下6:00，中午一小时午休时间。

工作地址：
天津塘沽新村街营口道
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
急聘前台（双休+五险一金）
天津金珑基科技有限责任公司
每年多次调薪五险一金年终分红餐补带薪年假节日福利不加班
**********
福利:
每年多次调薪
五险一金
年终分红
餐补
带薪年假
节日福利
不加班
**********
职位月薪：3500-5000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：中专
招聘人数：2人
职位类别：前台/总机/接待
**********
岗位职责：
1.中专及以上学历，
2.负责公司电话接听、公司文件、资料、合同的核对、归类及管理
3.能熟练使用office等文员办公软件
4.具有良好的沟通、协调能力
5.工作热情、有亲和力和良好的适应能力
6.无经验的应届生、实习生亦可
任职要求：
1.18-32岁，超龄勿投
2.对IT、移动互联网行业感兴趣,愿意长期发展（非销售、非保险岗位）
3.想获得一份有长远发展、稳定、有晋升空间的工作
4.工作仔细认真、责任心强、为人正直
薪资福利：
早9：00--晚18：00，周末双休，不加班，五险一金
底薪+奖金+定期团建+节假日补贴+年假！！！
1、每月组织团队活动
2、实习期期间就给上五险一金
3、带薪年假，法定节假日按国家规定休息
4、员工生日

工作地址：
天津市塘沽区
查看职位地图
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
小程序微信推广（无需经验）
四川泰德普斯网络科技有限公司
不加班弹性工作绩效奖金节日福利
**********
福利:
不加班
弹性工作
绩效奖金
节日福利
**********
职位月薪：2001-4000元/月 
工作地点：天津
发布日期：最近
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：50人
职位类别：微信推广
**********
本公司小程序（名称：掌乐微商城）主要帮助淘宝天猫商家营销推广打造爆款，商家前期为了商品冲销量，在前期会有一定亏本商品，商家找我们公司是为了找更多买家，提高销量打造爆款。我们的小程序汇集了大量非公开的内部折扣商品。
本公司诚招大量推广人员，按单结算提成（约为销售额的10%-20%甚至更多），不看业绩只看收入！
有意者联系HR企业qq 3004410165
工作地址：
不限
查看职位地图
**********
四川泰德普斯网络科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
互联网/电子商务
公司地址：
不限
**********
简单设计助理（双休、五险一金）
天津金珑基科技有限责任公司
五险一金年底双薪绩效奖金餐补带薪年假节日福利不加班
**********
福利:
五险一金
年底双薪
绩效奖金
餐补
带薪年假
节日福利
不加班
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：2人
职位类别：助理/秘书/文员
**********
岗位职责：
1、熟练操作Office办公软件；
2、对智能系统相关工作有兴趣，热爱设计，绘画等；
3、具备勤奋、吃苦的精神和较强的逻辑思维能力，有一定团队合作能力；
4、能够积极配合工作安排；
任职要求：
1、对新知识有兴趣并有较强的学习能力，计算机或相关专业优先；
2、能够尽快入职、长期稳定工作；
3、年龄18-30岁之间，条件优秀者可相应放宽。不符合条件者勿扰（非中介，非保险）；
工作时间：
1、上班9:00—下班6:00；
2、六日双休，五险一金，带休年假，法定节假日等；
3、外地员工可提供住宿；
4、实习期一到三个月，转正后薪资4K--6K不等；

工作地址：
天津塘沽新村街营口道泛华国际大厦
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
办公室文员+待遇优餐补
天津金珑基科技有限责任公司
每年多次调薪五险一金年终分红餐补带薪年假节日福利不加班
**********
福利:
每年多次调薪
五险一金
年终分红
餐补
带薪年假
节日福利
不加班
**********
职位月薪：2001-4000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：内勤人员
**********
岗位职责：
1、及时准确的更新员工通讯录；管理公司网络、邮箱；
2、订阅年度报刊杂志，收发日常报刊杂志及交换邮件；
3、员工考勤系统维护、考勤统计及外出人员管理。
应聘条件：
1、能够尽快入职(或者一个月左右能够到岗工作)；
2、能长期稳定工作（不招兼职）；
4、年龄18-35岁之间，经验不限，专业不限；
5、上市集团总公司——注重个人综合素质及能力，目前正在招收应届生及实习生。
待遇：
1、底薪+奖金=3000-5000（根据个人能力提升）；
2、五险一金，带薪年假，双休，节日福利，有餐补等；
3、可提供住宿或者就近安排工作地点；
4、试用期1-3个月（根据个人能力）转正后享有平均月薪不低于3000元/月收入。
工作时间：
1、国家法定作息时间；
2、周末双休，上9:00下6:00，中午一小时午休时间。
待遇优厚，试用期三个月，试用期间上五险一金，周末双休，有餐补，办公环境优越，节日福利，法定节假日~！有良好的发展及晋升空间。
应聘者可投递简历，人事部将在3个工作日内安排面试时间。
工作地址：
天津塘沽新村街营口道
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
PHP开发工程师/实习生+五险一金
天津金珑基科技有限责任公司
五险一金加班补助全勤奖餐补
**********
福利:
五险一金
加班补助
全勤奖
餐补
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：PHP开发工程师
**********
应聘条件：
1、能够尽快入职(或者一个月左右能够到岗工作)；
2、能长期稳定工作；
3、年龄18-30岁之间，经验不限，专业不限；
待遇：
1、底薪+奖金=3000-6000（根据个人能力提升）；
2、五险一金，带薪年假，双休，节日福利，有餐补等；
3、可提供住宿或者就近安排工作地点；
4、试用期1-3个月（根据个人能力）转正后享有平均月薪不低于3000元/月收入。
工作时间：
1、国家法定作息时间；
2、周末双休，上9:00下6:00，中午一小时午休时间。
公司招揽综合素质能力贤才，组织完善培训计划，工作经验不足者有老员工培养，并且公司提供全方位的办公环境和设施设备。
待遇优厚，试用期三个月，试用期间上五险一金，周末双休，有餐补，办公环境优越，节日福利，法定节假日~！有良好的发展及晋升空间。
应聘者可投递简历，人事部将在3个工作日内安排面试时间,或在右下角在线预约面试时间，并留下你的姓名+学历+年龄+电话，谢谢合作。
地址：天津塘沽外滩
工作地址：
天津塘沽外滩
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
急急急！广告平面设计（五险一金+双休）
天津金珑基科技有限责任公司
五险一金年底双薪绩效奖金全勤奖餐补节日福利创业公司加班补助
**********
福利:
五险一金
年底双薪
绩效奖金
全勤奖
餐补
节日福利
创业公司
加班补助
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：平面设计
**********
岗位职责：
1、负责公司日常宣传、策划设计制作、公司展览会议布置；
2、广告平面设计、制作及其它图文处理；企业宣传资料的设计、制作与创新。
3、协助其他部门人员对设计及美学方面的工作顺利完成；
任职要求：
1、能够尽快入职(或者一个月左右能够到岗工作)
2、能长期稳定工作（不招兼职）。
3、年龄18-28岁之间，经验不限，专业不限
待遇
1、底薪+奖金=3000-6000（根据个人能力提升）
2、五险一金，带薪年假，双休，节日福利，有餐补等；
3、可提供住宿或者就近安排工作地点
4、试用期1-3个月，转正后享有平均月薪不低于4000元/月收入
工作时间：
1、国家法定作息时间
2、周末双休，上9:00下6:00，中午一小时午休时间。
不符合条件者，非诚勿扰
待遇优厚，试用期一到三个月，试用期间上五险一金，周末双休，有餐补，办公环境优越，季度旅游,法定节假日~！有良好的发展及晋升空间
入职后：公司组织完善培训计划，新员工有老员工带领

工作地址：
天津塘沽新村街营口道泛华国际大厦
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
客服助理5K-8K元/月6K招地推专员无销售性质
天津典藏国一文化艺术交流有限公司
**********
福利:
**********
职位月薪：6001-8000元/月 
工作地点：天津-河东区
发布日期：最近
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：客户服务专员/助理
**********
岗位职责：
1、通过传单、礼物形式邀约客户。
2、利用公司提供礼品资源，通过话术沟通邀请客户到店，为市场部提供客户资源（无任何销售性质，传单发放以小组为单位协同进行，发放距离为公司周边商场）
任职要求：
1、年龄20-28 岁，男女不限；
2、高中以上学历，五官端正；
3、普通话标准，具有良好沟通和表达能力并习惯使用礼貌用语；
4、人品端正，责任心强，工作认真、有上进心，目标感强，能够承担工作压力；
5、有地推、电话邀约工作经验（如保险、电话销售、客户等）优先。
薪资待遇：
1、无责任底薪4000+双绩效奖金提成 综合薪水5000-8000
工作地址：
天津市河东区万达广场C座16层
查看职位地图
**********
天津典藏国一文化艺术交流有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市河东区万达广场
**********
急招产品运营专员+餐补+五险一金
天津金珑基科技有限责任公司
每年多次调薪五险一金包住餐补带薪年假节日福利
**********
福利:
每年多次调薪
五险一金
包住
餐补
带薪年假
节日福利
**********
职位月薪：3000-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：3人
职位类别：活动执行
**********
职位描述：
1、根据公司品牌战略推出相关的企划方案；
2、负责组织、策划、统筹各种产品与品牌推广活动，展会等相关活动的策划、执行等；
3、协助实施公司企业文化的传播推广活动；
4、处理相关的公关活动
岗位要求：
1、专科以上学历，具有市场拓展、营销策划、品牌推广经验者优先；
2、具有较高的文案策划写作能力，熟悉市场推广、品牌、活动策划的工作流程；
3、拥有较强的组织协调能力，团队协作能力强；
4、具备创新能力、思维敏捷，善于沟通；
5、熟练使用PPT办公软件
待遇：
1、底薪+奖金=4000--6000（根据个人能力提升）
2、五险一金，带薪年假，节日福利，双休，有餐补等；
3、员工可提供住宿（也可就近分配）。
4、试用期1-3个月（根据个人能力），转正后享有平均月薪不低于3000元/月收入
工作时间：
1、国家法定作息时间
2、周末双休，上9:00下6:00，中午一小时午休时间。

工作地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
急招后勤技术文员3K+待遇优
天津金珑基科技有限责任公司
每年多次调薪五险一金年终分红餐补带薪年假节日福利不加班
**********
福利:
每年多次调薪
五险一金
年终分红
餐补
带薪年假
节日福利
不加班
**********
职位月薪：3001-5000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：2人
职位类别：其他
**********
岗位描述：
1.负责公司技术部文件资料的管理、归类、整理、建档和保管工作
2.负责各技术部门月度、季度、年度统计报表和报告的制作，配合技术部领导完成工作
3.帮助技术人员完成计算机电脑操作，减轻他们的工作量和负担
应聘条件：
1、能够尽快入职或一个月左右入职
2、能长期稳定工作（不招兼职）。
3、年龄18-30岁之间，经验不限，专业不限
4、对计算机互联网行业感兴趣
待遇：
1、底薪+奖金=3000--6000（根据个人能力提升）
2、五险一金，带薪年假，节日福利，双休，有餐补等；
3、员工可提供住宿（也可就近分配）。
4、试用期1-3个月（根据个人能力），转正后享有平均月薪不低于3000元/月收入
工作时间：
1、国家法定作息时间
2、周末双休，上9:00下6:00，中午一小时午休时间。

工作地址：
天津塘沽新村街营口道
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
业务开发副总
青岛山海天文化传媒有限公司
**********
福利:
**********
职位月薪：10000-15000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：1人
职位类别：部门/事业部管理
**********
工作描述：
1、负责太阳能光伏产业园的业务开发工作；
2、负责光伏+（农业、渔业、牧业、旅游观光、田园综合体）招商运营工作；
3、负责所负责区域内各园区板块的规划及运营管理工作；
4、政府各部门对接（农委、发改委、水利、国土、规划、农经、农机等）及关系维护；
5、负责产业园相关项目政策申报工作；
6、负责行业战略客户合作洽谈，客情关系维护工作；
7、负责行业PPP项目的合作洽谈；
8、负责园区运营管理方案、项目合作方案、产业园招商方案等战略指导。
工作地址：
青岛市市南区闽江路172号软件大厦1608室
**********
青岛山海天文化传媒有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
青岛市市南区闽江路172号软件大厦1608室
**********
应届毕业生（销售岗）
天津典藏国一文化艺术交流有限公司
五险一金年底双薪绩效奖金年终分红带薪年假员工旅游节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
年终分红
带薪年假
员工旅游
节日福利
**********
职位月薪：8001-10000元/月 
工作地点：天津-河东区
发布日期：最近
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：10人
职位类别：电话销售
**********
岗位职责： 
1、客户来到公司负责接待，向客户讲解公司的产品知识； 
2、工作环境优越，无需外出；
4、无责任底薪3500+高提成，综合工资在8000-3万上，五险+ 带薪年假，公司不定期举行员工旅游，国家法定节假日均可享受带薪休假。
5、负责销售区域内销售活动的策划和执行，完成销售任务； 
6、管理维护客户关系以及客户间的长期战略合作计划。 
任职资格： 
1、高中以上学历，年龄在20-35之间，市场营销等相关专业者优先； 
2、从事过销售行业工作经者优先； 
3、具有亲和力，性格开朗，热爱和人交流；
4、具备一定的市场分析及判断能力，良好的客户服务意识； 
6、有团队协作精神，善于挑战；
7、混底薪勿扰！
工作地址：
天津市河东区万达广场C座16层
**********
天津典藏国一文化艺术交流有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市河东区万达广场
查看公司地图
**********
游戏测试助理（双休）
天津金珑基科技有限责任公司
每年多次调薪五险一金年终分红餐补带薪年假节日福利不加班
**********
福利:
每年多次调薪
五险一金
年终分红
餐补
带薪年假
节日福利
不加班
**********
职位月薪：3001-5000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：2人
职位类别：游戏设计/开发
**********
岗位职责：
1.完成游戏的各项测试任务，确保质量；
2.与需求部门深入沟通，分析测试需求、制定测试计划、设计测试案例；
3.执行测试任务，协调研发人员定位并协助解决问题；
4.BUG跟踪反馈。
应聘条件：
1、能够尽快入职或一个月左右入职；
2、能长期稳定工作（不招兼职）；
3、年龄18-35岁之间，经验不限，专业不限；
4、对计算机互联网行业感兴趣。
待遇：
1、底薪+奖金=3000--6000（根据个人能力提升）；
2、实习期间有五险一金，带薪年假，节日福利，双休，有餐补等；
3、员工可提供住宿（也可就近分配）；
4、试用期1-3个月，转正后享有平均月薪不低于3000元/月收入。
工作时间：
1、国家法定作息时间
2、周末双休，上9:00下6:00，中午一小时午休时间。
公司招揽综合素质能力贤才，组织完善培训计划，工作经验不足者有老员工培养，并且公司提供全方位的办公环境和设施设备。
面试人员较多，请应聘者先投递简历，人事部将在3个工作日内安排面试时间
工作地址：
天津塘沽新村街营口道
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
3D MAX设计助理（可应届可实习）
天津金珑基科技有限责任公司
创业公司五险一金年底双薪绩效奖金加班补助全勤奖餐补节日福利
**********
福利:
创业公司
五险一金
年底双薪
绩效奖金
加班补助
全勤奖
餐补
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：3人
职位类别：助理/秘书/文员
**********
岗位职责：
1.正确理解公司总体规划理念和客户意图并准确完整地表达呈现设计思想；
2.根据策划和设定，制作所需的3D资源，在把握整体风格的前提下根据原画设计稿进行3D场景建模；
3.负责室内外场景镜头布景、灯光布置、渲染出图等；
4.根据设计方案细化设计图纸；
任职要求：
1、能够尽快入职(或者一个月左右能够到岗工作)
2、能长期稳定工作（不招兼职）。
3、年龄18-28岁之间，经验不限，专业不限
待遇
1、底薪+奖金=3000-6000（根据个人能力提升）
2、五险一金，带薪年假，双休，节日福利，有餐补等；
3、可提供住宿或者就近安排工作地点
4、试用期1-3个月，转正后享有平均月薪不低于3000元/月收入
工作时间：
1、国家法定作息时间
2、周末双休，上9:00下6:00，中午一小时午休时间。
公司招揽综合素质能力贤才，组织完善培训计划，工作经验不足者有老员工培养，并且公司提供全方位的办公环境和设施设备。
待遇优厚，试用期三个月，试用期间上五险一金，周末双休，有餐补，办公环境优越，节日福利，法定节假日~！有良好的发展及晋升空间。

工作地址：
天津塘沽新村街营口道泛华国际大厦
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
设计部办公室文员3K起
天津金珑基科技有限责任公司
每年多次调薪五险一金年终分红餐补带薪年假节日福利不加班
**********
福利:
每年多次调薪
五险一金
年终分红
餐补
带薪年假
节日福利
不加班
**********
职位月薪：3001-5000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：5人
职位类别：其他
**********
岗位职责
1、负责办公室日常事务性工作；负责中心各种文稿的打印、发送，负责中心文件材料的领取；
2、负责中心会议的筹备、各类文件起草工作，负责PPT制作和文字材料的整理。
3、完成设计师交办的其它工作。
岗位要求：
1、大专以上学历；
2、熟悉日常办公软件操作；
3、性格沉稳；
4、工作仔细认真、责任心强、为人正直。
薪资构成：基本工资3000起+奖金+岗位津贴+丰厚年终奖
社会保险：入职即上五险一金
休息时间：5天8小时工作制、朝九晚六，周末双休，法定节假日休息，带薪年假，带薪病假，带薪产假，带薪婚丧假
节日贺礼：传统佳节派发节日礼品以增添节日气氛。
生日派对：过生日的员工，有公司生日派对以表祝福
生活关怀：定期体检，公司设有员工休息室，提供微波炉、饮水机等便捷设备。办公环境：办公环境优美，可提供住宿或者就近安排工作地点。
应聘者可投递简历，人事部将在3个工作日内安排面试时间

工作地址：
天津塘沽新村街营口道
查看职位地图
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
原画师（住宿+餐补）
天津金珑基科技有限责任公司
五险一金绩效奖金加班补助包住餐补带薪年假节日福利
**********
福利:
五险一金
绩效奖金
加班补助
包住
餐补
带薪年假
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：原画师
**********
岗位职责：
1、根据要求，画出相应的漫画人物角色
2、为漫画人物上色
3、具有独立完成角色绘画的能力
4、协助项目主管绘制人物
5、配合产品美术总监制定游戏角色风格，输出角色原画设计模版和规范；
 任职要求：

1、能够使用PS、SAI等绘画软件
2、擅长日漫风格
3、有较强的人体结构把握能力
4、高效完成较为精致的线稿或上色，具备出色的分镜能力
5、有较强的责任心，工作投入度高，配合团队完成目标；
6、有较强的学习能力，主动研究或学习新的技术运用到工作中。
7、实习大学生优先
工作时间：9:00-18:00；
工作地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
销售总监（旅游方向）
天津艺点意创科技有限公司
五险一金绩效奖金加班补助全勤奖带薪年假员工旅游节日福利
**********
福利:
五险一金
绩效奖金
加班补助
全勤奖
带薪年假
员工旅游
节日福利
**********
职位月薪：8000-15000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：1人
职位类别：销售总监
**********
岗位职责：
1.根据公司要求制定符合本区域现状的政府销售与运营策略、规划及实施方案；
2.相关市场的开拓，客户资源的关系维护；
3.对销售目标进行分解，制定销售推进计划，达成销售目标；
4.与区域政府部门、旅游景区等保持良好关系；
5.吃苦耐劳、抗压能力强、市场开拓能力强；
6.组织市场调研与分析，关注行业市场的特点与发展趋势、客户需求变化情况，熟悉公司产品特点，发现销售新模式与新机会；；
7.旅游领域重点大客户挖掘、谈判、签约及解决方案的跟进协调;
8.结果导向，沟通谈判能力强，人际敏感度高，资源整合能力强；
9.接受全国频繁出差；

任职要求：
1.全日制本科学历及以上，30-45周岁； 
2.三年以上的旅游行业或政府类拓展、销售等相关工作经验；
3.对旅游领域、政府机构设置及组织特性有一定了解及关注；
4.熟练掌握市场分析、市场定位的工具与方法；
5.熟练使用 office 等常用办公软件；
6.较强的沟通能力、组织协调能力，专业的领导力，并拥有一定的创新能力、服务意识、
7.学习能力，有责任心，能承受一定的工作压力。
8.有政府资源优先，有品牌策划、咨询相关工作经验优先，旅游领域相关工作经验优先。

工作地址：
天津市红桥区光荣道宝能创业中心A座24层
**********
天津艺点意创科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市红桥区光荣道宝能创业中心A座24层
**********
上市公司8-10K聘咨询师+五险一金
天津众云金泰科技有限公司
五险一金绩效奖金年终分红每年多次调薪带薪年假节日福利餐补员工旅游
**********
福利:
五险一金
绩效奖金
年终分红
每年多次调薪
带薪年假
节日福利
餐补
员工旅游
**********
职位月薪：8001-10000元/月 
工作地点：天津
发布日期：最近
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：3人
职位类别：培训/招生/课程顾问
**********
任职要求：
1、21至36岁，大专及以上学历，热爱销售；
2、工作条理性强，应变能力、协调、沟通控制能力强；
3、学习能力强，抗压力强；
4、熟练使用WORD、EXCEL、PPT办公软件；
5、有教育行业背景者优先考虑。
岗位职责：
1、接待来访者的来访咨询，解答来访者提出的各种问题；
2、为来访者制定合理的课程，提供专业的咨询；
3、准确收集、统计、整理咨询数据；
4、数据的录入与分析；
5、配合其他部门做好相关事宜；
6、完成公司规定的个人月度指标；
7、接受公司安排的个人的专业技能提升。
福利待遇：
1、底薪+提成+绩效奖金+年度绩效奖金＋年终分红＋5险1金+法定假日（10-12W/年）
2、 签订正式劳动合同，完整合规的社会保险和住房公积金以及餐补；
3、 每季度员工聚会+员工生日会+节日礼物；
4、 每年享受国家规定的带薪年假、法定节假日等福利；
5、 丰富的企业文化活动，打造快乐活力的工作氛围

地铁一号线鞍山道A口出来右转直行100米即达！

工作地址：
天津市和平区劝业场街道南京路258号巨贝大厦A座7层701室
查看职位地图
**********
天津众云金泰科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
IT服务(系统/数据/维护)
公司地址：
天津市和平区劝业场街道南京路258号巨贝大厦A座7层701室
**********
文员4K双休+五险一金
天津金珑基科技有限责任公司
每年多次调薪五险一金年终分红餐补带薪年假节日福利不加班
**********
福利:
每年多次调薪
五险一金
年终分红
餐补
带薪年假
节日福利
不加班
**********
职位月薪：3001-5000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：3人
职位类别：其他
**********
岗位职责：
1、起草和修改报告、文稿等；
2、及时准确的更新员工通讯录；管理公司网络、邮箱；
3、负责日常办公用品采购、发放、登记管理，办公室设备管理；
5、员工考勤系统维护、考勤统计及外出人员管理。
任职资格：
1、能够长期工作；
2、能够运用OFFICE等办公软件；
4、工作仔细认真、责任心强、为人正直，具备较强的书面和口头表达能力；
工作时间：
上9点下6点，周末双休。

工作地址：
天津塘沽新村街营口道
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
急聘文员/双休+餐补
天津金珑基科技有限责任公司
每年多次调薪五险一金年终分红餐补带薪年假节日福利不加班
**********
福利:
每年多次调薪
五险一金
年终分红
餐补
带薪年假
节日福利
不加班
**********
职位月薪：2001-4000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：2人
职位类别：内勤人员
**********
待遇：
1、底薪+奖金=3000-6000（根据个人能力提升）；
2、五险一金，带薪年假，双休，节日福利，有餐补等；
3、可提供住宿或者就近安排工作地点；
4、试用期1-3个月（根据个人能力）转正后享有平均月薪不低于3000元/月收入。
工作时间：
1、国家法定作息时间；
2、周末双休，上9:00下6:00，中午一小时午休时间。
待遇优厚，试用期三个月，试用期间上五险一金，周末双休，有餐补，办公环境优越，节日福利，法定节假日~！有良好的发展及晋升空间。

工作地址：
天津塘沽新村街营口道
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
餐饮店长/经理
天津艺点意创科技有限公司
创业公司五险一金带薪年假
**********
福利:
创业公司
五险一金
带薪年假
**********
职位月薪：8001-10000元/月 
工作地点：天津-红桥区
发布日期：最近
工作性质：全职
工作经验：3-5年
最低学历：中专
招聘人数：1人
职位类别：店长/卖场管理
**********
岗位职责：
1、全面主持店面的管理工作，根据餐厅经营战略进行各项营销策略的实施；
2、根据市场需求及情况，完成各项经营指标，达成营业额、门店成本控制等目标；
3、负责制定和完善前厅与后厨的管理制度、服务流程及操作标准；
4、在餐厅层面负责对外沟通以及周边关系维护，进行企划活动的策划和执行，提高品牌形象；
5、门店日常管理工作，包括店员招聘、业务培训、考核、岗位分工、考勤安排与监督、安全等管理。
任职要求：
1、3年以上餐厅管理经验，对餐饮行业有较深入的理解；
2、具备较强的沟通能力与应变能力、执行力与统筹协调能力；
3、热爱餐饮行业，具备强烈的服务意识与责任意识。
餐饮门店地址：天津市南开区城厢中路
工作地址：
天津市红桥区光荣道宝能创业中心A座24层
**********
天津艺点意创科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市红桥区光荣道宝能创业中心A座24层
**********
4K网络安全工程师助理+可应届（奖金餐补）
天津金珑基科技有限责任公司
每年多次调薪五险一金年终分红餐补带薪年假节日福利不加班
**********
福利:
每年多次调薪
五险一金
年终分红
餐补
带薪年假
节日福利
不加班
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：2人
职位类别：其他
**********
应聘条件：
1、招聘长期稳定工作。
2、大专及以上学历，年龄要求在18-30岁之间，一年以下网络安全经验优先。
3、具有良好的沟通能力和敬业精神，可承受工作压力，责任心强，认真仔细，精力充沛，团队精神强，接受理解能力强。
待遇：
1、底薪+奖金=4000-6000（根据个人能力提升）；
2、五险一金，带薪年假，节日福利，双休，有餐补等；
3、员工可提供住宿或就近安排工作；
4、试用期1-3个月，转正后享有平均月薪不低于3000元/月收入。
工作时间：
1、国家法定作息时间；
2、周末双休，上9:00下6:00，中午一小时午休时间。
备注：
公司招揽综合素质能力贤才，组织完善培训计划，工作经验不足者有老员工培养，并且公司提供全方位的办公环境和设施设备。

工作地址：
天津塘沽新村街营口道
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
前台+五险一金+稳定双休
天津金珑基科技有限责任公司
五险一金加班补助全勤奖餐补
**********
福利:
五险一金
加班补助
全勤奖
餐补
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：前台/总机/接待
**********
岗位职责：
1、及时、准确接听/转接电话，记录留言并及时转达；
2、接待来访客人并及时准确通知被访人员；
3、收发公司邮件、报刊、传真和物品，并做好登记管理以及转递工作
应聘条件：
1、能够尽快入职。
2、能长期稳定工作。
3、年龄18-28岁之间，经验不限，专业不限
待遇：
1、底薪+奖金=3000-6000（根据个人能力提升）；
2、五险一金，带薪年假，双休，节日福利，有餐补等；
3、可提供住宿或者就近安排工作地点；
4、试用期1-3个月（根据个人能力）转正后享有平均月薪不低于3000元/月收入。
工作时间：
1、国家法定作息时间；
2、周末双休，上9:00下6:00，中午一小时午休时间。
待遇优厚，试用期间上五险一金，周末双休，有餐补，办公环境优越，节日福利，法定节假日~！有良好的发展及晋升空间。
天津塘沽外滩
工作地址：
天津塘沽外滩
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
市场策划/市场研究专员/经理（上市公司）
天津合富辉煌房地产营销策划有限公司
每年多次调薪五险一金年终分红加班补助交通补助带薪年假员工旅游节日福利
**********
福利:
每年多次调薪
五险一金
年终分红
加班补助
交通补助
带薪年假
员工旅游
节日福利
**********
职位月薪：5000-10000元/月 
工作地点：天津-河西区
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：2人
职位类别：房地产项目策划经理/主管
**********
岗位概述：
1.负责本地区市场调研工作；
2.负责本地区项目的定位管理，包括但不限于编制项目定位报告、项目产品的研发和定位调整、对新地块进行可行性市场定位研究等；
3.负责本地区的各圈层客户研究工作，为销售案场客户拓展提供支持。
4.数据研究、市场调研、客户访谈等研究方法为房地产机构、开发商提供房地产咨询服务。业务类型涉及区域战略开发、住宅、商业策略咨询和设计咨询。
 
岗位职责：
执行咨询项目的相关调研及分析工作；
执行数据整理工作，并提交相关分析报告；
整理和编写研究成果，制作相关咨询报告。
 
岗位要求：
1. 本科以上学历,房地产类、建筑学类、经济类、市场营销类相关专业优先; 
2. 具有优秀的系统思考、逻辑分析和学习能力；
3. 具有敏锐的市场观察力和良好的推动执行力，;
4. 具有良好的沟通能力，积极主动、具有团队合作精神；
5. 思想活跃，擅于总结，富于创意；
6. 能够熟练操作Office办公软件，特别是Excel和PowerPoint。会CAD或其他统计软件者优先；
工作地址：
天津市河西区友谊路5号北方金融大厦10层
查看职位地图
**********
天津合富辉煌房地产营销策划有限公司
公司规模：
100-499人
公司性质：
上市公司
公司行业：
房地产/建筑/建材/工程
公司主页：
http://www.hopefluent.cn
公司地址：
天津市河西区友谊路5号北方金融大厦10层
**********
网络技术客服+五险一金
天津金珑基科技有限责任公司
每年多次调薪五险一金绩效奖金餐补节日福利不加班
**********
福利:
每年多次调薪
五险一金
绩效奖金
餐补
节日福利
不加班
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：3人
职位类别：网络/在线客服
**********
岗位职责：
1.能够尽快入职(或者一个月左右能到岗工作)
2.能长期稳定工作(不招兼职)
3.年龄在18-30岁之间 ，经验不限，专业不限。

岗位福利待遇:
1.底薪+奖金=3000-6000
2.五险一金，带薪年假，双休，节日有福利，有餐补。
3.可提供住宿或者就近安排工作地点
4.试用期1-3个月，转正后享有平均立新不低3000/每个月
5.实习期间有五险一金
6.公司有季度旅游
7.有法定节假日

工作时间：
1.国家法定作息时间
2.周末双休，上9下6，中午一个小时休息时间
3.公司组织完善培训计划，新员工有老员工带领

工作地址：
天津市塘沽区
查看职位地图
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
产品包装设计+双休+五险一金
天津金珑基科技有限责任公司
每年多次调薪五险一金年终分红餐补带薪年假节日福利不加班
**********
福利:
每年多次调薪
五险一金
年终分红
餐补
带薪年假
节日福利
不加班
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：3人
职位类别：包装设计
**********
岗位职责：
1. 负责公司产品内外包装的结构设计、包装样制作；
2. 公司官网及微信公众号的内容设计和制作，包括各类图标、banner设计等；
3. 市场宣传所需的图形设计和印刷品设计等；
4. 结合商品的特性制作相关推广图集，形成图文并茂的描述模板，优化产品信息；
5、配合完成其他上级安排的工作；
任职资格：
1、大专及以上学历，艺术设计、美术相关专业毕业者优先；
2、能够根据公司的策划思路和营销概念，充分理解创意意图并准确体现于创意设计中，完成设计方案；
3、做事认真、细心、负责，能够专心学习技术；
4、优秀的应往届毕业生可适当放宽条件；
上班时间：8小时工作制，六日双休 法定节假日休息
福利待遇：
1、基本工资+奖金，试用期2-3个月，根据工作情况可缩短试用期
2、实习期按天津市标准缴纳五险一金，年假，定期旅游，优越的办公环境
3、享受国家法定节假日，员工生日礼品等福利;
4、丰富多彩的员工活动：员工聚餐、节日晚会、出国旅游活动等等
晋升空间：
公司规模持续扩大，会出现很多管理岗位，明确的晋升途径，充分的发展空间

工作地址：
天津塘沽新村街营口道
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
3D动画设计助理（双休高薪）可应届
天津金珑基科技有限责任公司
五险一金全勤奖包住餐补节日福利
**********
福利:
五险一金
全勤奖
包住
餐补
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：三维/3D设计/制作
**********
岗位职责：
1、对图片资源进行加工处理；
2、运用视频编辑软件，进行视频剪辑、调色、配音等后期处理；
3、二维动画设计制作。
任职资格：
1、18-30周岁，经验不限，专业不限；。
2、工作稳定、轻松，工作时间朝九晚六。
3、有较强的组织、协调、执行、沟通能力及人际交往能力
4、工作踏实、稳定、有管理能力。
其他福利待遇：
1、按天津市标准缴纳五险一金，
2、快速晋升空间，有效地竞聘晋升制度。
3、签订正式劳动合同。
4、每季度员工聚会+员工生日会+节日礼物；
5、每年享受国家规定的带薪年假、法定节假日等福利。
6.公司提供住宿，交通便利
地址：天津塘沽外滩

工作地址：
天津塘沽外滩
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
客户执行
红鹤沟通机构
五险一金绩效奖金带薪年假补充医疗保险定期体检
**********
福利:
五险一金
绩效奖金
带薪年假
补充医疗保险
定期体检
**********
职位月薪：4001-6000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：广告客户代表
**********
岗位职责：
1）处理并执行项目客户日常作业，监控项目传播策略的执行；
2）与客户保持良好的关系，向客户表达创意思路，辅助上级主管进行有效的提案和书面作业，及时催收款项；
3）具备一定策略能力，能够对项目创意提出意见；
4）明晰并有效参与公司流程管理；
5）对市场状况、本项目及竞品状况、客户情况进行信息整理，供总监做策略制定之参考。
 任职要求：
1）大专或以上学历；
2）两年以上房地产行业相关工作经验者优先；
3）熟练使用Word\ Excel\ Powerpoint\Internet。

工作地址：
天津市南开区东马路129号仁恒置地国际中心8层806
**********
红鹤沟通机构
公司规模：
100-499人
公司性质：
民营
公司行业：
广告/会展/公关
公司主页：
http://www.chinaflamingo.ncom
公司地址：
北京市朝阳区酒仙桥北路9号恒通国际创新园C8F
查看公司地图
**********
世界500强企业诚挚招聘
中国平安人寿保险股份有限公司天津市河东支公司
绩效奖金全勤奖带薪年假弹性工作员工旅游节日福利不加班
**********
福利:
绩效奖金
全勤奖
带薪年假
弹性工作
员工旅游
节日福利
不加班
**********
职位月薪：15001-20000元/月 
工作地点：天津-河东区
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：5人
职位类别：销售代表
**********
世界500强企业诚挚招聘

一、薪资待遇：
1：新人训练津贴（高达5400元）+ 业务提成、达成津贴、季度奖、综合金融服务金、续年度服务津贴、继续率奖金、增才奖金，养老金等；（上不封顶）
2：公司提供系统的产品知识培训和销售技巧培训
3：双休、国家法定节假日
4：优秀员工一年两次国内旅游一次国外旅游
5：晋升无阻碍，绩优人员晋升表彰享受荣誉、鲜花、掌声。

二、岗位职责：
1、服务项目:全方位金融产品销售服务、一站式服务、贯穿客户的衣、食、住、行、玩
1．人寿保险（健康、意外、养老、教育基金、投资理财、储蓄分红、财富传承、团体意外险、企业年金等）
2．财产保险（车险、设备险、家庭财产保险、货物运输保险、雇主责任保险、公众责任保险等）
3．推荐证券业务及产品，含股票债券基金等
4．推荐银行业务，如办理信用卡，推荐贷款、介绍理财产品业务等。
5．信托业务及产品信托计划
6．推荐介绍平安陆金所、平安万里通、平安好车、平安好房、平安好医生、网上购物

三、任职资格：
1、高中及以上学历，年龄25岁以上
2、有卓越的目标和理想，能坚持并喜欢挑战的工作
3、具有良好的亲和力、语音富有感染力；
4、具有良好的心理素质及良好的沟通能力；
5、具有积极进取的精神及接受挑战的个性，有一定的抗压能力；
6、热爱保险行业有营销工作热情，责任心强，待人友善；
7、勤奋好学，勇于接受挑战，有自我创业的想法，对销售工作有较高的热情
工作时间：8：30-10：30（双休及法定节假日）

工作地址：
天津市河东区六纬路与大直沽八号路交口万达中心
**********
中国平安人寿保险股份有限公司天津市河东支公司
公司规模：
10000人以上
公司性质：
股份制企业
公司行业：
保险
公司主页：
http://www.pingan.com
公司地址：
天津市河东区十二经路119号润泉公寓底商
查看公司地图
**********
合同管理
天津艺点意创科技有限公司
创业公司五险一金带薪年假
**********
福利:
创业公司
五险一金
带薪年假
**********
职位月薪：3000-5000元/月 
工作地点：天津-红桥区
发布日期：最近
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：销售运营专员/助理
**********
岗位职责：
1、建立合同管理体系,制订合同管理制度；
2、负责合同文本的编号、发放与存档，负责客户档案建立与关系维护；
3、负责审查销售部门合同的条款符合公司规定；
3、加强合同台帐管理、合同文件的管理与归档工作。
任职要求：
1、本科及以上学历，2年以上相关工作经验；
2、工作严谨，认真负责，有较强的组织、协调及沟通能力。

工作地址：
天津市红桥区光荣道宝能创业中心A座24层
**********
天津艺点意创科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市红桥区光荣道宝能创业中心A座24层
**********
销售代表（五险一金＋提供住宿）
天津国信众泰信用服务有限公司
五险一金年底双薪绩效奖金年终分红全勤奖包住带薪年假节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
年终分红
全勤奖
包住
带薪年假
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：10人
职位类别：销售代表
**********
岗位职责：
1、负责企业信用工作会议前企业家的接待与服务；
2、会议现场带领企业家初审并完成与企业家的项目谈判和合同签约；
3、会后辅助企业家提交信用等级申报的资料，进行信用等级申报；
4、信用等级申报过程中的问题指导；
5、客户关系的深入与维护；
任职要求：
1、大专及以上学历，专业不限，可接收应届毕业生；
2、沟通与表达能力佳；
3、形象好，气质佳，阳光、积极、正直；
4、热爱销售，渴望高薪并有高升的意愿


工作地址：
天津市南开区复康路八里台中天大厦A座8层
**********
天津国信众泰信用服务有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
互联网/电子商务
公司主页：
null
公司地址：
天津市南开区复康路八里台中天大厦A座8层
查看公司地图
**********
客户主管
天津市北辰区世纪职业培训学校
五险一金绩效奖金年终分红加班补助包住餐补员工旅游节日福利
**********
福利:
五险一金
绩效奖金
年终分红
加班补助
包住
餐补
员工旅游
节日福利
**********
职位月薪：10001-15000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：2人
职位类别：销售经理
**********
正规民办学校，非教育中介
岗位职责：
有团队精神，带过销售团队或是有组建销售团队。
1、负责学校产品的销售及推广；
2、根据市场营销计划，完成部门销售指标；
3、开拓新市场,发展新客户,增加产品销售范围；
4、负责辖区市场信息的收集及竞争对手的分析；
5、负责销售区域内销售活动的策划和执行，完成销售任务；
6、管理维护客户关系以及客户间的长期战略合作计划。
任职资格：
1、大专及以上学历，市场营销等相关专业；
2、3-5年以上销售行业工作经验，教育行业业绩突出者优先；
3、反应敏捷、表达能力强，具有较强的沟通能力及交际技巧，具有亲和力；
4、具备一定的市场分析及判断能力，良好的客户服务意识；
5、有责任心，能承受较大的工作压力；
6、有团队协作精神，有担当，善于挑战。

上班时间：
9:00-17：30



工作地址：
天津市红桥区金兴科技大厦
**********
天津市北辰区世纪职业培训学校
公司规模：
20-99人
公司性质：
民营
公司行业：
教育/培训/院校
公司地址：
天津市北辰区京津公路北辰大厦2号楼13层
查看公司地图
**********
高薪招聘展厅接待员
天津典藏国一文化艺术交流有限公司
五险一金年底双薪绩效奖金带薪年假员工旅游节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
带薪年假
员工旅游
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：天津
发布日期：最近
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：5人
职位类别：服务员
**********
岗位职责：
1、负责在公司展厅接待来访客户，讲解产品；
2、维护新老客户关系；
3、每年12天带薪病假，法定节假日带薪休假；
4、高底薪3500+高提成，每单提成金额1000~60000之间，
  员工平均工资在8000-3w之间上不封顶；
5、优秀的晋升机制，公司股权激励，员工旅游；
6、客户量大，成单快；
7、全国连锁机构，公司雄厚实力，而本公司在全国业绩排名第一，员工薪资相对同行业处于优厚位置。
无电销、外出性质，无邀约压力。客户主动上门，新客户开发不用愁

任职要求：
1、大专以上学历，条件优秀者学历可放宽；
2、不矫情，有韧性、外地户口者优先录用；
3、真正想要挣钱求发展的，混底薪勿扰。
工作地址：
天津市河东区万达广场
**********
天津典藏国一文化艺术交流有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市河东区万达广场
查看公司地图
**********
中国平安保险销售经理 理财顾问
中国平安人寿保险股份有限公司天津市河东支公司
绩效奖金全勤奖弹性工作补充医疗保险员工旅游节日福利不加班
**********
福利:
绩效奖金
全勤奖
弹性工作
补充医疗保险
员工旅游
节日福利
不加班
**********
职位月薪：10001-15000元/月 
工作地点：天津-河东区
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：5人
职位类别：保险代理/经纪人/客户经理
**********
职位描述：
优才计划”是中国平安重磅推出的人才招募及培养计划。旨在通过“优才计划”，招募一批具有经营意识和管理潜能的优秀人才，专项培养帮助其成长为跟上公司“科技引领个人综合金融“战略的个人综合金融客户经理、国际MDRT会员和擅经营、懂管理的专业团队管理者。
一，基本要求
（1）年龄：25-45周岁
（2）学历：大专及以上学历
（3）身体健康，敢于挑战高收入，无犯罪记录

二，公司待遇及福利：
（1）每天工作时间为：8：00~10：30，双休制，其它时间自由安排；
（2）待遇：新人训练津贴+佣金提成+季度奖+达成奖；
（3）医疗保障，包括：寿险+意外+疾病住院+意外医疗，令你工作无忧；
（4）一年多次国内外免费旅游；
（5）公司不定期的实物奖励，大小奖项拿不停；

三，工作职责描述：
1，人寿保险，如健康、意外、养老、教育金、投资理财、储蓄分红、团体意外险等
2，财产保险，如车险、设备险、家庭财产保险、货物运输保险、雇主责任保险等；
3，银行业务，如平安银行信用卡，贷款等业务；
4，证券业务，如股票、债券等；
5，协助分析客户的保险及财务状况，作出相关的财务建议和保险产品搭配。

四，专业免费培训
1、新人训练：职前培训、从业资格考试培训、岗前培训
2、转正培训： 专题训练、提升训练、拓展训练、讲师训练
3、晋升培训：经营管理技能训练 ,团队管理培训
4、享受平安大学终身免费金融理财培训,全心打造职业经理人


工作地址：
天津市河东区大直沽8号路万达中心
**********
中国平安人寿保险股份有限公司天津市河东支公司
公司规模：
10000人以上
公司性质：
股份制企业
公司行业：
保险
公司主页：
http://www.pingan.com
公司地址：
天津市河东区十二经路119号润泉公寓底商
查看公司地图
**********
平面设计+可培养
天津金珑基科技有限责任公司
创业公司五险一金年底双薪绩效奖金加班补助全勤奖餐补节日福利
**********
福利:
创业公司
五险一金
年底双薪
绩效奖金
加班补助
全勤奖
餐补
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：平面设计
**********
岗位职责：
配合设计总监完成logo、VI、画册等设计
任职资格：
1、了解网页设计和平面软件的使用，会AI、PS等软件；
2、18-28周岁，大专及以上学历，有无经验均可；
（入职有系统培训，欢迎广大应届毕业生投递简历）
3.对艺术及设计具有一定的审美眼光及鉴赏力；
4.态度认真，责任心强，乐观团结。
工作时间：
1、国家法定作息时间
2、周末双休，上9:00下6:00，中午一小时午休时间。

工作地址：
天津塘沽新村街营口道泛华国际大厦
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
财务出纳
天津典藏国一文化艺术交流有限公司
五险一金年底双薪绩效奖金年终分红带薪年假员工旅游节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
年终分红
带薪年假
员工旅游
节日福利
**********
职位月薪：3700-5000元/月 
工作地点：天津
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：出纳员
**********
岗位职责：
1、 负责日常现金及票据的收付、保管及费用报销；
2、 划转、核算内部往来款项，到款确认，及时登记现金、银行日记帐；
3、 现金、银行凭证制作、装订、保管；
4、 固定资产、办公用品、低值易耗品的帐务管理、核对与盘点；
5、 协助会计准备每日、月单据及报表，完成月末结账报税等工作。

任职要求：
1、 会计、财务等相关专业大专以上学历，有会计从业资格证书；
2、 有2年以上出纳经验者优先考虑；
3、 了解国家财经政策和会计、税务法规。

薪资待遇：
试用期薪资3000，转正后3500，
满一年薪资3800，满两年薪资4300，满三年薪资4800，上五险一金。
入职满一年年底享受公司十三薪待遇，不定期组织员工旅游，节日礼物。

工作地址：
天津市河东区万达广场C座16层
**********
天津典藏国一文化艺术交流有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市河东区万达广场
查看公司地图
**********
一手房售楼员/置业顾问/销售代表（北辰区-路劲隽澜湾）高提点
天津合富辉煌房地产营销策划有限公司
五险一金年终分红带薪年假定期体检免费班车员工旅游节日福利
**********
福利:
五险一金
年终分红
带薪年假
定期体检
免费班车
员工旅游
节日福利
**********
职位月薪：10001-15000元/月 
工作地点：天津-北辰区
发布日期：最近
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：25人
职位类别：房地产销售/置业顾问
**********
岗位职责：
1、负责接待到访客户并详细做好客户登记；
2、完成每月个人销售业绩与意向客户跟进；
3、定期做好客户回访与业主维系；
4、定期完成销售日报、周报及月报。
5、项目产品销售工作。
任职要求：
1、1年以上地产销售经验；18-35岁，男女不限；
2、普通话流利，形象气质佳，有亲和力，沟通能力强，主动学习意识强；
3、具备一定的市场分析及判断能力,良好的客户服务意识,热爱地产销售工作；
4、有较强的团队合作精神,有责任心.
5、熟悉并了解北辰版块市场及楼盘。
 薪酬福利：
1、底薪+同行业高额佣金，五险一金，任务奖励，排名奖励。
2、享受公司年度体检、旅游拓展、带薪年假、节日礼品、年终奖等各项福利。


工作地址：
天津市北辰区辰昌路
查看职位地图
**********
天津合富辉煌房地产营销策划有限公司
公司规模：
100-499人
公司性质：
上市公司
公司行业：
房地产/建筑/建材/工程
公司主页：
http://www.hopefluent.cn
公司地址：
天津市河西区友谊路5号北方金融大厦10层
**********
塘沽+PS修图助理（高薪待遇优）可应届
天津金珑基科技有限责任公司
创业公司五险一金年底双薪绩效奖金加班补助全勤奖餐补节日福利
**********
福利:
创业公司
五险一金
年底双薪
绩效奖金
加班补助
全勤奖
餐补
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：4人
职位类别：助理/秘书/文员
**********
岗位职责：
1、对图片进行抠图、排版、美化图片、及商品的上下架；
2、完成公司领导、部门经理安排的其他工作；
3、经验不作严格要求，但学历至少中技，不符合要求勿投。

岗位要求：
1、对ps美工设计感兴趣；
2、具有良好的审美能力和设计创新理念，想象力丰富；
3、富有团队精神、沟通能力和责任感，对待工作认真、负责；
4、经验不限，无基础亦可，可接受转行人员，但要求学习能力好，有同事带
任职要求：
1、对新知识有兴趣并有较强的学习能力，计算机或相关专业优先；
2、能够尽快入职、长期稳定工作；
3、年龄18-28岁之间，条件优秀者可相应放宽。不符合条件者勿扰（非中介，非保险）；
工作时间：
1、上班9:00—下班6:00；中午休息一小时
2、六日双休，五险一金，带薪年假，节日福利，法定节假日等；
3、外地员工可提供住宿；
4、实习期三个月，转正后薪资4K--6K不等；
备注：
现招揽优秀的员工且有良好的发展及晋升空间
欢迎各位应届生前来面试！
2017年，我们公司正处于快速发展期！待遇优厚，欢迎有经验、优秀的有志青年投身加入！
多一次简历投递，多一次面试机会！

工作地址：
天津塘沽新村街营口道泛华国际大厦
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
3D建模师助理+五险一金+双休
天津金珑基科技有限责任公司
五险一金全勤奖包住餐补节日福利
**********
福利:
五险一金
全勤奖
包住
餐补
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：三维/3D设计/制作
**********
岗位职责
1.游戏角色建模
2.游戏场景建模
应聘条件：
1、能够尽快入职(或者一个月左右能够到岗工作)；
2、能长期稳定工作
3、年龄18-30岁之间，经验不限，专业不限；
待遇：
1、底薪+奖金=3000-6000（根据个人能力提升）；
2、五险一金，带薪年假，双休，节日福利，有餐补等；
3、可提供住宿 交通便利；
1、国家法定作息时间；
2、周末双休，上9:00下6:00，中午一小时午休时间。
天津塘沽外滩
工作地址：
天津塘沽外滩
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
双休+设计助理
天津金珑基科技有限责任公司
创业公司五险一金年底双薪绩效奖金加班补助全勤奖餐补节日福利
**********
福利:
创业公司
五险一金
年底双薪
绩效奖金
加班补助
全勤奖
餐补
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：助理/秘书/文员
**********
岗位职责：
配合设计总监完成logo、VI、画册等设计
任职资格：
1、了解网页设计和平面软件的使用，会AI、PS等软件；
2、18-26周岁，大专及以上学历，相关行业一年以下工作经验优先；
（此岗位仅接收吃苦耐劳的应届毕业生，工资面议。）
3.对艺术及设计具有一定的审美眼光及鉴赏力；
4.态度认真，责任心强，乐观团结。
工作时间：
1、国家法定作息时间
2、周末双休，上9:00下6:00，中午一小时午休时间。

工作地址：
天津塘沽新村街营口道泛华国际大厦
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
美术设计实习生+五险一金+双休(可零基础)
天津金珑基科技有限责任公司
五险一金全勤奖包住餐补节日福利
**********
福利:
五险一金
全勤奖
包住
餐补
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：2人
职位类别：美术编辑/美术设计
**********
岗位职责：
1、喜爱设计行业，想获得一份长期稳定且有发展前景的工作。
2. 有无相关基础均可（前期为辅助类岗位，无专业、经验要求），但一定要对设计感兴趣，学习能力强，工作热情高，负有责任感。
3、配合完成其他上级安排的工作；做事认真、细心、负责，能够专心学习技术。
应聘条件：
1、能够尽快入职；
2、能长期稳定工作；
3、年龄18-30岁之间，经验不限，专业不限；
待遇：
1、底薪+奖金=3000-6000（根据个人能力提升）；
2、五险一金，带薪年假，双休，节日福利，有餐补等；
3、可提供住宿或者就近安排工作地点 交通便利；
4、试用期1-3个月（根据个人能力）转正后享有平均月薪不低于4000元/月收入。
工作时间：
1、国家法定作息时间；
2、周末双休，上9:00下6:00，中午一小时午休时间。
公司招揽综合素质能力贤才，组织完善培训计划，工作经验不足者有老员工培养，并且公司提供全方位的办公环境和设施设备。
待遇优厚，试用期三个月，试用期间上五险一金，周末双休，有餐补，办公环境优越，节日福利，法定节假日~！有良好的发展及晋升空间。
应聘者可投递简历，人事部将在3个工作日内安排面试时间。
天津塘沽外滩

工作地址：
天津塘沽外滩
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
【新媒体编辑部】新媒体编辑
天津市峻腾广告有限公司
五险一金绩效奖金加班补助交通补助餐补带薪年假节日福利员工旅游
**********
福利:
五险一金
绩效奖金
加班补助
交通补助
餐补
带薪年假
节日福利
员工旅游
**********
职位月薪：3000-5000元/月 
工作地点：天津-河东区
发布日期：最近
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：2人
职位类别：新媒体运营
**********
1、负责公司宣传推广的活动策划；
2、能够独立创作和完成宣传稿件的规划与撰写；
3、较强的文字功底、文笔流畅，有很好的信息收集、归纳、整理能力和表达能力；
4、擅长软文、硬广等多种文体写作，有报纸、杂志、论坛撰文经验优先；
5、学习新事物快，新闻敏感性强,善于捕捉热点信息；
6、可独立完成自媒体运营管理，撰写自媒体发布内容并持续更新维护；
7、能够熟练操作Excel、Word、PPT等办公软件；
8、具有创造力，热衷学习；

工作地址：
天津市河东区万达写字楼
**********
天津市峻腾广告有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
广告/会展/公关
公司地址：
天津市河东区万达写字楼
查看公司地图
**********
4k网站美工助理+双休+餐补
天津金珑基科技有限责任公司
每年多次调薪五险一金年终分红餐补带薪年假节日福利不加班
**********
福利:
每年多次调薪
五险一金
年终分红
餐补
带薪年假
节日福利
不加班
**********
职位月薪：3001-5000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：5人
职位类别：网页设计/制作/美工
**********
1.18~28岁之间，高中、中专及以上学历，专业不限；
2.热爱设计，对设计有浓厚兴趣，愿意长期从事该行业；
3.学习能力强，工作认真负责，具有团队合作精神及良好的沟通能力；
4.主动性高，耐心细致，能准确表达设计思路，有一定理解分析能力和创造能力；
5.相关专业及有设计相关工作经验者优先考虑。
薪资福利：
公司人力资源部为所有岗位建立成长模式、提供系统化岗位技能提升渠道、提供职业发展通道，入职后每年有2次薪资考核提升机会，根据岗位能力与职责不同，当年年薪4W-6W，三年内平均年薪6W-10W。
薪资构成：基本工资3000起+奖金+岗位津贴+丰厚年终奖
社会保险：试用期即上五险一金
休息时间：5天8小时工作制、朝九晚六，周末双休，法定节假日休息，带薪年假，带薪病假，带薪产假，带薪婚丧假
节日贺礼：传统佳节派发节日礼品以增添节日气氛。
生日派对：过生日的员工，有公司生日派对以表祝福
生活关怀：定期体检，公司提供微波炉、饮水机等便捷设备。
办公环境：办公环境优美，可提供住宿或者就近安排工作地点。
应聘者可投递简历，人事部将在3个工作日内安排面试时间。
工作地址：
天津塘沽新村街营口道
查看职位地图
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）
**********
招聘专员
北京纵横无双科技有限公司
**********
福利:
**********
职位月薪：4001-6000元/月 
工作地点：天津-河北区
发布日期：最近
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：招聘专员/助理
**********
岗位职责
1、组织并实施公司日常招聘工作，主要根据招聘目标完成人才的招聘。
2、招聘流程的优化，与用人部门负责人深入交流具体用人需求，量化录用标准。
3、建立开拓及维护各种招聘渠道，优化企业招聘资源及招聘流程。
4、负责建立企业人才储备库，做好简历管理与信息保密工作。
任职要求：
1、人力资源管理、工商管理相关工作经验，2年以上全职招聘经验，有过RPO与跨区域招聘经验。
2、熟悉各种招聘渠道，并能够根据招聘职位特点，选择恰当的渠道。
3、性格开朗、有朝气、有较强亲和力，服务意识强，可承受一定的工作压力。
4、具有较为扎实的HR专业理论知识，猎头顾问背景为佳。


工作地址：
天津河北区曙光路曙光生活广场3层（三号线铁东路站D口步行五分钟）
**********
北京纵横无双科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
互联网/电子商务
公司地址：
北京市海淀区中关村
**********
网络运营专员4K+
天津金珑基科技有限责任公司
每年多次调薪五险一金年终分红餐补带薪年假节日福利不加班
**********
福利:
每年多次调薪
五险一金
年终分红
餐补
带薪年假
节日福利
不加班
**********
职位月薪：4001-6000元/月 
工作地点：天津-滨海新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：2人
职位类别：网络运营专员/助理
**********
岗位职责：
1、负责官方微信公众号等平台的日常内容的撰写和运营
2、收集、研究网络热点话题，结合新媒体特性，对微信、微博内容的实时调整和更新
3、负责微信、微博大型活动方案的策划、创意、执行、运营以及汇报和总结
任职要求：
1、创意优，执行力强，有良好的策略思考能力
2、思维活跃，工作主动，有责任感，能承受较大的工作压力
3、良好团队合作精神，较强的执行力，观察力和应变能力
4、年龄18-32岁，年龄不符者勿投
福利待遇：
1、底薪+奖金=3000-5000（根据个人能力提升）
2、五险一金，带薪年假，季度旅游，双薪，有餐补等
3、可提供员工宿舍
4、签订正式劳动合同
5、每季度员工聚会+员工生日会+节日礼物
6、高薪收入，依据岗位不同，设立相应的绩效奖励激励机制
7、快速晋升空间，有效地竞聘晋升制度
工作时间：
1、国家法定作息时间
2、周末双休，上9:00下6:00，中午一小时午休时间
2017年，我们公司正处于快速发展期！待遇优厚，欢迎有经验、优秀的有志青年投身加入！
多一次简历投递，多一次面试机会！欢迎各位应届生前来面试！

工作地址：
天津塘沽新村街营口道
**********
天津金珑基科技有限责任公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
广告/会展/公关
公司地址：
天津塘沽新村街营口道（近塘沽大剧院）