电厂项目经理
北京海华同鑫电力设备有限公司
五险一金绩效奖金全勤奖交通补助餐补通讯补贴员工旅游节日福利
**********
福利:
五险一金
绩效奖金
全勤奖
交通补助
餐补
通讯补贴
员工旅游
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：北京-大兴区
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：1人
职位类别：项目经理/项目主管
**********
岗位职责：
 1、熟悉与掌握公司经营的产品知识，负责销售公司产品；
2、负责公司既有客户关系、跟进和维护、开发新客户，开拓新的市场领域；
3、负责公司产品的市场推广，及时搜集并整理市场信息、项目信息；
4、能独立完成与客户的业务接洽、咨询及关系维护；负责销售计划的分解、落实，并进行跟踪与评估；
 任职要求：
1、年龄28岁以上、大学专科及以上学历，机电一体化、化学、环境、电气工程相关专业；
2、熟练使用Word、Excel等各种办公软件，能独立完成各项报表及标书的制作；
3、熟悉电厂采购及招投标流程、熟悉电厂各部门之间关系；
4、3年以上电力行业销售经验，具备良好电力行业人脉关系与资源者优先考虑。
5、工作认真，积极，为人诚实，勤奋，有韧性，有强烈的事业心和责任感，具备良好的人际交往、社会活动能力及公关谈判能力。具有良好的团队协作精神，良好的协调、沟通和把握全局的能力，拥有良好的团队协作精神，注重团队配合，具备有服从团队的意识；
6、 能够适应短期出差；
7、完成领导交办的其他工作；
8、有驾照者优先录用。
 薪资福利待遇
1、 薪资待遇：底薪+绩效奖金+五险+福利补贴
2、享受标准社会保险（养老保险，医疗保险，工伤保险，失业保险，生育保险）。
 备注：
1、上班地点为“北京市大兴区波普中心”；
2、4号线枣园地铁站下即到；
  工作地址：
北京市大兴区波普中心
查看职位地图
**********
北京海华同鑫电力设备有限公司
公司规模：
20人以下
公司性质：
股份制企业
公司行业：
电气/电力/水利
公司地址：
北京市大兴区波普中心
**********
专职司机
京蓝科技股份有限公司
五险一金绩效奖金交通补助餐补通讯补贴带薪年假补充医疗保险定期体检
**********
福利:
五险一金
绩效奖金
交通补助
餐补
通讯补贴
带薪年假
补充医疗保险
定期体检
**********
职位月薪：6001-8000元/月 
工作地点：北京-朝阳区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：机动车司机/驾驶
**********
岗位职责：
1、负责董事长外出等用车工作；
2、负责公司车辆保养、维修和清洁工作；
3、协助处理公司车辆保险、年检办理；
4、领导安排的其他工作。
任职要求：
1、年龄28岁到40岁，C1本，3年以上驾驶经验，驾驶技术娴熟，熟悉北京路况；
2、无不良驾驶记录，无重大事故及交通违章，具有较强的安全意识；
3、懂商务接待礼仪，具有一定的服务意识；
4、保密意识强、责任心强，退役军人优先。
工作地址：
北京市朝阳区望京东园七区保利国际广场17号楼（T2）二层
查看职位地图
**********
京蓝科技股份有限公司
公司规模：
500-999人
公司性质：
上市公司
公司行业：
跨领域经营
公司主页：
//www.kinglandgroup.com/
公司地址：
北京市丰台区广安路9号院3号楼5层
**********
应收应付会计
北京中环博宏环境资源科技有限公司
五险一金补充医疗保险定期体检高温补贴节日福利餐补
**********
福利:
五险一金
补充医疗保险
定期体检
高温补贴
节日福利
餐补
**********
职位月薪：6001-8000元/月 
工作地点：北京
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：2人
职位类别：会计/会计师
**********
岗位职责：
（1）负责应收应付账款统计、并督促收款；
（2）负责分公司项目收款、付款情况的统计；
（3）根据项目进度初审付款合同的支付申请；
（4）根据项目进度初审分公司运营费拨款申请；
（5）根据公司财务制度审核报销单据；
（6）根据项目进度，审核项目开票申请；
（7）负责核算项目毛利情况，并编制excel统计表；
（8）合同管理，负责合同的登记和存档以及印花税的计算和核销；
（9）预算执行情况的比对、分析；
（10）按月和各部门、各分公司进行往来账款的核对，对逾期未收回账款究其原因，并督促收款；
（11）上级领导交办的其他工作。
任职资格：
（1）大学本科以上学历，会计、审计相关专业；
（2）有3年以上正规公司财务工作经验;
（3）熟练使用用友U8财务软件以及word、excel等办公软件；（4）有良好的工作习惯，在工作中善于归纳总结、善于沟通并能对工作题合理化建议；
（5）有责任心、上进心，工作思路清晰，对自己的职业有明确的规划；
（6）有一定的抗压能力。

工作地址：
北京市朝阳区红军营南路甲1号
查看职位地图
**********
北京中环博宏环境资源科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
环保
公司主页：
null
公司地址：
北京市朝阳区红军营南路甲1号
**********
技术总监（架构师PHP）
北京善治合同节水管理网络科技有限公司
创业公司五险一金绩效奖金股票期权餐补带薪年假
**********
福利:
创业公司
五险一金
绩效奖金
股票期权
餐补
带薪年假
**********
职位月薪：20001-30000元/月 
工作地点：北京
发布日期：招聘中
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：1人
职位类别：系统架构设计师
**********
岗位职责：
1. 负责分析、设计和搭建公司相关系统的服务器系统架构，解决开发中各种架构及技术相关问题；
2、负责产品核心框架及功能的开发；
3、解决产品研发过程中的关键技术问题；
4、研究应用架构的发展方向，提出架构改进方案；
5、诊断和解决现行系统可能存在的问题，保证公司系统的安全、稳定、高效率运行；
6、制定相应的设计规范和开发规范；
7、有团队管理经验，负责对技术团队成员的培训及指导；
任职要求：
1、全日制本科及以上学历，5年以上PHP研发经验，优秀的分析、架构设计和文档编写能力,同时有过java开发的经验优先；
2、从事过产品研发，具有全面、深刻架构原理、架构技术，有丰富经验；
3、具有分布式、高并发、高负载、高可用性系统经验；
4、熟悉Linux 操作系统、NOSQL；
5、具有丰富的java服务器方面的编程经验；
6、有较强的技术实施能力和创新能力；
7、良好的抽象思维和逻辑思维能力，独立分析问题和解决问题的能力。
8、具备良好的沟通协作能力、团队合作精神。

工作地址：
北京市朝阳区北辰东路8号汇宾大厦B座1318室
查看职位地图
**********
北京善治合同节水管理网络科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
互联网/电子商务
公司主页：
wsmc-china.com
公司地址：
北京市朝阳区北辰东路8号汇宾大厦B座1318室
**********
会计 出纳（五险一金+双休）
山西蓝天环保设备有限公司
五险一金绩效奖金餐补节日福利
**********
福利:
五险一金
绩效奖金
餐补
节日福利
**********
职位月薪：4000-6000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：3人
职位类别：出纳员
**********
任职要求：
1、 会计、财务等相关专业大专以上学历，有会计从业资格证书；
2、 了解国家财经政策和会计、税务法规，熟悉银行结算业务；
3、 熟悉会计报表的处理，熟练使用财务软件；
4、 善于处理流程性事务、良好的学习能力、独立工作能力和财务分析能力；
5、 工作细致，责任感强，良好的沟通能力、团队精神。
 岗位职责：
1、 负责公司现金、票据及银行存款的保管、出纳和记录；
2、 配合各部门办理电汇、信汇等有关手续；
3、 协助会计做好各种帐务的处理工作；
4、 负责掌管小额现金；
5、 完成上级交给的其它事务性工作。

工作地址：
北京朝阳区立水桥南-北科创业大厦11层
查看职位地图
**********
山西蓝天环保设备有限公司
公司规模：
500-999人
公司性质：
民营
公司行业：
大型设备/机电设备/重工业
公司主页：
www.sxlantian.com
公司地址：
山西省太原市万柏林区迎泽西大街100号国际能源中心30层
**********
实验员3-5名
清华大学环境质量检测中心
五险一金
**********
福利:
五险一金
**********
职位月薪：2001-4000元/月 
工作地点：北京
发布日期：招聘中
工作性质：全职
工作经验：无经验
最低学历：大专
招聘人数：3人
职位类别：其他
**********
岗位职责：
1.按照标准，完成相关检测；
2.按实验流程，跟进相关实验，对实验结果负责；
3.能够独立完成任务，思维敏捷，善于沟通交流；
4.完成领导安排的其他任务；
 岗位要求：
1.熟悉水样品、空气样品检测分析方法，熟练操作常规化学分析仪器；
2.勤奋好学、沟通表达能力良好，能吃苦耐劳；
3.大专及以上学历，化学、环境相关专业；
4.有分析、检测经验，从事检测工作经历者优先。
  待遇：按清华大学合同制人员标准，具体面议。
 有意应聘者请将个人简历发送至ceqt@tsinghua.edu.cn，邮件标题请注明应聘-岗位-姓名;通过初选者将择日安排面试，未通知面试者不再发通知。期间恕不接待来电、来访。
     工作地址：
清华大学环境学院
查看职位地图
**********
清华大学环境质量检测中心
公司规模：
20-99人
公司性质：
事业单位
公司行业：
环保
公司地址：
北京市海淀区清华大学环境节能楼510
**********
ppp项目营销经理（京蓝生态）
京蓝科技股份有限公司
五险一金绩效奖金交通补助餐补通讯补贴带薪年假补充医疗保险定期体检
**********
福利:
五险一金
绩效奖金
交通补助
餐补
通讯补贴
带薪年假
补充医疗保险
定期体检
**********
职位月薪：10001-15000元/月 
工作地点：北京-朝阳区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：2人
职位类别：销售经理
**********
岗位职责：
1、负责农田水利项目申报，立项，可行性研究分析，施工方案完善，跟进项目执行、验收，协助与政府相关部门沟通，协调及接待工作；
2、负责开拓维护农田水利项目政府相关部门的沟通渠道和良好的合作关系；
3、根据公司业务及规划，建立有建设性的、高效的政府关系网络，建立完善与政府机构沟通机制；
4、关注PPP农业水利行业相关动态，能够有效获取领域内的各种资源；
5、领导交办的其他工作。
任职要求：
1、本科及以上学历，公共关系管理、国际政治、市场营销等相关专业等优先；
2、具有良好的文字功底，善于公关类写作；
3、对政府政策和中央部委主要政府部门（农、林、水利）有深入了解，熟悉相关政府职能部门体系和主要部门的工作流程；
4、优秀的人际交往和协调能力，良好的团队合作精神，极强的社会活动能力；
5、形象气质佳，有较高的情商和智商。
【注】因工作需要，会有较多出差任务。
工作地址：
北京市朝阳区望京东园七区保利国际广场17号楼（T2）二层
查看职位地图
**********
京蓝科技股份有限公司
公司规模：
500-999人
公司性质：
上市公司
公司行业：
跨领域经营
公司主页：
//www.kinglandgroup.com/
公司地址：
北京市丰台区广安路9号院3号楼5层
**********
区域销售代表
北京本华科技有限公司
带薪年假员工旅游节日福利五险一金不加班
**********
福利:
带薪年假
员工旅游
节日福利
五险一金
不加班
**********
职位月薪：8001-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：5人
职位类别：销售代表
**********
1、负责向公司现有客户介绍产品、同时了解到客户的需求；
2、根据客户的需求为客户提供报价并签订合同；
3、开拓新市场，在新的市场推广公司的产品，建立品牌知名度；
4、建立新开发市场的客户档案。

任职要求：
1、大专以上学历，年龄20-30岁，应届毕业亦可；
2、热爱销售，富有激情，勇于挑战更高业绩目标;
3、具有敏锐的市场洞察力和客户分析能力，能独立开发客户；
4、具有较强的沟通谈判能力和关系建立能力；
5、性格外向、反应敏捷、表达能力强，具有较强的沟通能力及交际技巧，具有亲和力；
6、具备一定的市场分析及判断能力，良好的客户服务意识；
7、有责任心，能承受工作压力。

薪资福利：
1、无责底薪4K+高销售提成；
2、业绩奖金；
3、公司团建活动较多，每季度都有集体出游和聚餐活动；
4、优秀员工每年还有2次特殊旅行，目的地可以自选；
5、销售冠军次年代表公司参加英国厂家代理商大会，和全球的代理商一起互动或者参加英国厂家提供的厂家培训。

工作地址：
北京市朝阳区亚运村远大中心C座 1605

工作时间：
8:30---;17:30（周末双休，不加班）

乘车路线：
地铁5号线大屯路东西南口出，步行10分钟即到。
地铁15号线安立路D出，步行5分钟即到。
公交车快3、984、运通110等车炎黄艺术馆下车，步行5分钟即到。

工作地址：
北京市朝阳区慧忠路远大中心C座1605
查看职位地图
**********
北京本华科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电气/电力/水利
公司地址：
北京市朝阳区慧忠路远大中心C座1605
**********
销售代表
北京本华科技有限公司
五险一金绩效奖金带薪年假节日福利员工旅游
**********
福利:
五险一金
绩效奖金
带薪年假
节日福利
员工旅游
**********
职位月薪：8001-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：5人
职位类别：销售代表
**********
1、负责向公司现有客户介绍产品、同时了解到客户的需求；
2、根据客户的需求为客户提供报价并签订合同；
3、开拓新市场，在新的市场推广公司的产品，建立品牌知名度；
4、建立新开发市场的客户档案。

任职要求：
1、大专以上学历，年龄20-30岁，应届毕业亦可；
2、热爱销售，富有激情，勇于挑战更高业绩目标;
3、具有敏锐的市场洞察力和客户分析能力，能独立开发客户；
4、具有较强的沟通谈判能力和关系建立能力；
5、性格外向、反应敏捷、表达能力强，具有较强的沟通能力及交际技巧，具有亲和力；
6、具备一定的市场分析及判断能力，良好的客户服务意识；
7、有责任心，能承受工作压力。

薪资福利：
1、无责底薪4k+高销售提成；
2、业绩奖金；
3、公司团建活动较多，每季度都有集体出游和聚餐活动；
4、优秀员工每年还有2次特殊旅行，目的地可以自选；
5、销售冠军次年代表公司参加英国厂家代理商大会，和全球的代理商一起互动或者参加英国厂家提供的厂家培训。

工作地址：
北京市朝阳区亚运村远大中心C座 1605

工作时间：
8:30—17:30（双休）

乘车路线：
地铁5号线大屯路东西南口出，步行10分钟即到。
地铁15号线安立路D出，步行5分钟即到。
公交车快3、984、运通110等车炎黄艺术馆下车，步行5分钟即到。

工作地址：
北京市朝阳区慧忠路远大中心C座1605
查看职位地图
**********
北京本华科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电气/电力/水利
公司地址：
北京市朝阳区慧忠路远大中心C座1605
**********
销售代表
北京百润鸿德环保科技有限公司
创业公司绩效奖金包住弹性工作节日福利不加班员工旅游
**********
福利:
创业公司
绩效奖金
包住
弹性工作
节日福利
不加班
员工旅游
**********
职位月薪：4001-6000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：10人
职位类别：销售代表
**********
基本工资（4500-6000）+业绩提成（5%-33%销售额提成）+冠军奖励（日奖、周奖、月奖）+ 一次性奖励（扫码、抽奖）+团队开拓奖（出差优秀团队奖）+领导奖励（优秀团队领导者奖励）+协同奖励（优秀团队协作者奖励）+导师奖励（培训、奖励）+育人奖励+业绩分红

福利待遇：
（1）公司免费提供住宿
（2）集团公司每年两次以上旅游年会，国内一次、国外一次
（3）端午、中秋、圣诞节、过年都为每位伙伴准备精美礼品
（4）差旅费所有费用公司报销
（5）公司为每位伙伴都免费准备蛋糕生日聚会

 岗位职责：
1、负责向公司现有客户介绍新产品、同时了解到客户的需求；
2、开拓新市场，在新的市场推广公司的产品，建立品牌知名度；
3、维护老顾客，开发新顾客

任职要求：
1、年龄16-28岁，可接受应届生，退伍军人；
2、愿意接受销售，富有激情，勇于挑战高新；
3、口齿清晰，身体健康；
5、有责任心，接受出差。

晋升通道：
销售代表——销售主管——销售总监——销售经理（自己开分公司）

在我们公司：任何人都可以从销售代表晋升为集团公司合伙人，在这里，没有后来者，只有后来居上者。不管先来后到，都有机会晋升为集团公司合伙人。
欢迎加入我们：17343151307（微信同号）

工作地址：
北京市昌平区珠江摩尔国际大厦3号楼
查看职位地图
**********
北京百润鸿德环保科技有限公司
公司规模：
10000人以上
公司性质：
股份制企业
公司行业：
快速消费品（食品/饮料/烟酒/日化）
公司地址：
北京市昌平区珠江摩尔国际大厦3号楼
**********
区域销售经理
北京本华科技有限公司
不加班带薪年假员工旅游节日福利五险一金
**********
福利:
不加班
带薪年假
员工旅游
节日福利
五险一金
**********
职位月薪：8001-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：2人
职位类别：销售经理
**********
1、负责向公司现有客户介绍产品、同时了解到客户的需求；
2、根据客户的需求为客户提供报价并签订合同；
3、开拓新市场，在新的市场推广公司的产品，建立品牌知名度；
4、建立新开发市场的客户档案。

任职要求：
1、大专以上学历，年龄20-30岁，应届毕业亦可；
2、热爱销售，富有激情，勇于挑战更高业绩目标;
3、具有敏锐的市场洞察力和客户分析能力，能独立开发客户；
4、具有较强的沟通谈判能力和关系建立能力；
5、性格外向、反应敏捷、表达能力强，具有较强的沟通能力及交际技巧，具有亲和力；
6、具备一定的市场分析及判断能力，良好的客户服务意识；
7、有责任心，能承受工作压力。

薪资福利：
1、无责底薪4K+高销售提成；
2、业绩奖金；
3、公司团建活动较多，每季度都有集体出游和聚餐活动；
4、优秀员工每年还有2次特殊旅行，目的地可以自选；
5、销售冠军次年代表公司参加英国厂家代理商大会，和全球的代理商一起互动或者参加英国厂家提供的厂家培训。

工作地址：
北京市朝阳区亚运村远大中心C座 1605

工作时间：
8:30—17:30（双休）

乘车路线：
地铁5号线大屯路东西南口出，步行10分钟即到。
地铁15号线安立路D出，步行5分钟即到。
公交车快3、984、运通110等车炎黄艺术馆下车，步行5分钟即到。

工作地址：
北京市朝阳区慧忠路远大中心C座1605
查看职位地图
**********
北京本华科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电气/电力/水利
公司地址：
北京市朝阳区慧忠路远大中心C座1605
**********
（电力工程）电气技术员
北京同方电气工程有限公司
五险一金绩效奖金包吃包住通讯补贴定期体检节日福利
**********
福利:
五险一金
绩效奖金
包吃
包住
通讯补贴
定期体检
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：北京-房山区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：施工员
**********
任职资格：
1、具有电气专业大专以上文化程度及相关资质证书，具有现场技术经验。
2、熟悉并掌握电气施工相关规程及质量安全规程。
3、具备沟通、协调能力。
4、熟练使用办公软件及办公设备。
 工作职责：
1、负责对施工现场技术管理，对施工现场出现的一些施工问题负责及时解决。 
2、读通施工图，参加施工图自审和会审，学习掌握和贯彻工程施工中的各项规章、规范和标准，并严格按照施工图相关规范和施工组织设计的计划要求配合施工。 
3、负责编制施工现场的施工组织设计、技术交底、相应材料的申报。
4、做好对作业班组的技术、质量交底工作，并经常性的检验与指导。  
5、负责工程部工作量的统计、工作量的报表。
此职位工作地点房山区良乡，包吃、住，请考虑情况妥善投递！

工作地址：
北京市房山区良乡西潞南大街5号同方大厦412室
查看职位地图
**********
北京同方电气工程有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电气/电力/水利
公司主页：
www.autotongfang.com
公司地址：
北京市房山区良乡西潞街道南上岗村安琪儿美语幼儿园南100米
**********
销售工程师【战略性新兴产业/上市公司】
北京威派格科技发展有限公司
五险一金绩效奖金交通补助通讯补贴带薪年假定期体检员工旅游节日福利
**********
福利:
五险一金
绩效奖金
交通补助
通讯补贴
带薪年假
定期体检
员工旅游
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：5人
职位类别：销售工程师
**********
一个站在“互联网+”风口上的行业 
工业互联，智联供水新型设备引领产业升级
智慧水务，城市供水管理平台提升水务运营
 一家引领行业发展的企业 
承接国家“十二五”水专项课题
五项建设部行业标准/一项国家标准
二次供水领域74项专利
国际工业互联联盟IIC成员
西门子SIEMENS战略合作伙伴
中国首个工程级水利综合实验平台
工业4.0标准的全新智能化工厂
 岗位职责：
1、对新建/改造类工程项目进行日常拜访，推动客户关系的深入与提升；
2、挖掘客户需求，并提供专业的解决方案，达成合作；
3、技术交流、招投标、合同谈判、收款等工作的开展。
 任职要求：
1、统招本科学历，理工科专业优先。
2、一年以上工业品行业销售经验，且业绩良好。
3、有开发长期合作客户经验者优先。
4、良好的沟通协调与协作能力。
 选择一个前景无限的产业，决定着你未来广阔的发展空间。
选择一个迅速发展的企业，决定着你拥有更多的发展机会。
选择一个行业的龙头企业，决定着你将接受到更好的培养。
选择一个积极向上的团队，决定着你拥有志同道合的伙伴。

选择我们，选择一份值得奋斗一生的事业！
工作地址：
北京市宣武区宣外大街10号庄胜广场中央办公楼北翼11层
**********
北京威派格科技发展有限公司
公司规模：
1000-9999人
公司性质：
上市公司
公司行业：
大型设备/机电设备/重工业
公司主页：
http://www.shwpg.com/
公司地址：
北京市宣武区宣外大街10号庄胜广场中央办公楼北翼11层
**********
市场拓展专员（战略性新兴产业/上市公司）
北京威派格科技发展有限公司
五险一金绩效奖金交通补助通讯补贴带薪年假定期体检员工旅游节日福利
**********
福利:
五险一金
绩效奖金
交通补助
通讯补贴
带薪年假
定期体检
员工旅游
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：4人
职位类别：市场营销专员/助理
**********
一个站在“互联网+”风口上的行业
工业互联，智联供水新型设备引领产业升级。
智慧水务，城市供水管理平台提升水务运营。

一家引领行业发展的企业
承接国家“十二五”水专项课题
五项建设部行业标准/一项国家标准
二次供水领域74项专利
国际工业互联联盟IIC成员
西门子SIEMENS战略合作伙伴
中国首个工程级水利综合实验平台
工业4.0标准的全新智能化工厂

选择你的未来！期待你的加入！

岗位职责：
1、在经理带领下，在设计院开展公司品牌及技术推广；
2、 配合公司销售人员完成公司供水设备（将市政供水加压输送到楼盘高层用户）的销售，包括产品设计入图、召开技术交流会等；
3、市场信息的收集、整理及反馈；
4、组织区域内老客户答谢会和品牌推广会；
5、公司老客户体系的维护。

任职资格：
1、统招本科以上学历，形象良好；
2、具备良好的沟通能力与亲和力；
3、有市场或销售类工作经验者优先。

职业发展通道：
专员→经理→区域经理→分公司副总→分公司总经理

选择一个前景无限的产业，决定着你未来广阔的发展空间。
选择一个迅速发展的企业，决定着你拥有更多的发展机会。
选择一个行业的龙头企业，决定着你将接受到更好的培养。
选择一个积极向上的团队，决定着你拥有志同道合的伙伴。
选择我们，选择一份值得奋斗一生的事业！
工作地址：
北京市宣武区宣外大街10号庄胜广场中央办公楼北翼11层
**********
北京威派格科技发展有限公司
公司规模：
1000-9999人
公司性质：
上市公司
公司行业：
大型设备/机电设备/重工业
公司主页：
http://www.shwpg.com/
公司地址：
北京市宣武区宣外大街10号庄胜广场中央办公楼北翼11层
**********
外派出差
北京奥泰斯通环保科技有限公司
五险一金绩效奖金全勤奖包吃包住员工旅游高温补贴节日福利
**********
福利:
五险一金
绩效奖金
全勤奖
包吃
包住
员工旅游
高温补贴
节日福利
**********
职位月薪：8001-10000元/月 
工作地点：北京-大兴区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：10人
职位类别：销售代表
**********
混底薪者勿扰，能力有多大，公司给予的平台就有多大。 

欢迎你有梦想,有态度,有决心,有行动的有志青年加入我们的销售团队,共同见证自己的成长。
 薪资待遇； 
1、底薪3700起+提成，5000-8000无上限；
（有日奖、周奖、月奖、季度奖励、年度奖励）
3、国家法定假日正常休息，公司提供省内外免费旅游活动。 
4、入职提供免费培训，住宿，优秀者有国内外旅游学习进修机会
5、工作能力强,个人魅力好的优秀者公司将给予巨大的发展空间和晋升渠道。
 岗位要求
1、学历，性别不限，有无经验均可。
2、能够短、中期在外阜工作，公司负责报销差旅费用。
3、有良好的沟通能力和应变能力，具有独立的分析和解决问题的能力。
 面试地点：北京市大兴区绿地缤纷2号楼1单元312室
联系电话：010-80252710  010-80252630 人力资源部
乘车路线：
1、地铁：乘4号线高米店南B2东北口出，步行200米即可。
2、公交：乘坐968路，848路，954路在高米店站下车，步行200米，或乘829、兴53路在缤纷城下车，步行100米即可。
         乘专24路、兴11路、兴36路、兴42路、兴53路高米店南下车，步行100米即可。
工作地址：
北京市大兴区绿地中央广场4号院2号楼1单元312室
**********
北京奥泰斯通环保科技有限公司
公司规模：
10000人以上
公司性质：
股份制企业
公司行业：
环保
公司主页：
北京奥泰斯通环保科技有限公司
公司地址：
北京奥泰斯通环保科技有限公司
查看公司地图
**********
规划设计师（京蓝生态）
京蓝科技股份有限公司
五险一金绩效奖金交通补助餐补通讯补贴带薪年假补充医疗保险定期体检
**********
福利:
五险一金
绩效奖金
交通补助
餐补
通讯补贴
带薪年假
补充医疗保险
定期体检
**********
职位月薪：8001-10000元/月 
工作地点：北京-朝阳区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：2人
职位类别：水利/港口工程技术
**********
岗位职责：
1、负责农业节水灌溉项目前期材料收集，水利相关设计工作
2、实施公司节水灌溉工程项目设计、规划工作，承担项目各阶段设计及校审工作
3、跟进需要进行内外部沟通协调，处理相关技术问题
4、项目现场踏勘、资料收集工作
5、规划项目编制的组织工作，负责成果汇报工作项目地形图测绘；
任职要求：
1、水利水电、农业水土工程、农田水利等专业者优先；
2、本科以上学历，英文口语较好，具有2年以上相关农田水利设计工作经验；
3、熟练使用CAD和office等办公软件；
4、可接受短期出差。
工作地址：
北京市朝阳区望京东园七区保利国际广场17号楼（T2）二层
查看职位地图
**********
京蓝科技股份有限公司
公司规模：
500-999人
公司性质：
上市公司
公司行业：
跨领域经营
公司主页：
//www.kinglandgroup.com/
公司地址：
北京市丰台区广安路9号院3号楼5层
**********
电话客服销售
北京铁骆驼科技有限公司
五险一金包吃包住绩效奖金
**********
福利:
五险一金
包吃
包住
绩效奖金
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：中专
招聘人数：15人
职位类别：电话销售
**********
岗位职责：
1.接受公司统一培训，电话沟通，整理客户信息；
2.耐心与客户沟通，根据客户需求寻找解决方法；
3.及时电话回访，介绍项目内容，邀约客户考察；
4.认真完成领导的任务。

任职要求：
1.勤奋，勤奋，勤奋，从内心是想挣钱的，欢迎加入我们铁骆驼；
2.不抱怨，积极向上，不勾心斗角，我们都是正能量的年轻团队；
3.能长久稳定工作，能有职业规划的优先选择；
4.你有多大才能，就有多少收入，你付出多少汗水，就有足够的回报；
5.20-35岁，男女不限，每周单休，朝九晚六。

薪资待遇：
真实薪资每月5000-20000元（底薪+提成），给你提供好的工作环境，给你一个好的发展空间，期待你能展现自己。

联系人：周经理        电话：15110100696   微信：zw271263542
工作地址
北京市大兴区亦庄经济开发区科创十二路鸿坤·云时代C座8楼

工作地址：
北京市通州区科创十二街鸿坤云时代C座8楼
查看职位地图
**********
北京铁骆驼科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
www.tlt888.cn
公司地址：
北京市大兴区亦庄经济开发区科创十二路鸿坤·云时代C座8楼
**********
招聘电话客服20名
北京铁骆驼科技有限公司
五险一金全勤奖包吃包住带薪年假员工旅游节日福利
**********
福利:
五险一金
全勤奖
包吃
包住
带薪年假
员工旅游
节日福利
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：20人
职位类别：网络/在线客服
**********
岗位职责：
1.接听客户来访电话；
2.整理归类客户需求；
3.介绍和解决基本问题；
任职要求：
1.有耐心，声音有亲和力；
2.接受公司统一培训；
3.18-35岁，男女不限；
4.有客服、销售、导购经验者优先；

薪资待遇：
真实薪资每月5000-10000元（底薪+绩效+奖金），给你提供好的工作环境，给你一个好的发展空间，期待你能展现自己，单休，请考虑好再联系，谢谢！

联系人：周经理        电话：15110100696   微信：zw271263542



工作地址：
北京市大兴区亦庄经济开发区科创十二路鸿坤·云时代C座8楼
查看职位地图
**********
北京铁骆驼科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
www.tlt888.cn
公司地址：
北京市大兴区亦庄经济开发区科创十二路鸿坤·云时代C座8楼
**********
销售经理
上海爱启环境技术工程有限公司
五险一金绩效奖金交通补助通讯补贴带薪年假员工旅游
**********
福利:
五险一金
绩效奖金
交通补助
通讯补贴
带薪年假
员工旅游
**********
职位月薪：8001-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：3人
职位类别：销售经理
**********
岗位职责：
1、 结合公司发展战略，负责所辖区域市场的统筹规划，渠道开发、拓展和关系维护；
2、 负责设计院的开发维护工作；
3、 负责公司产品的讲解、演示与项目方案制定、协调；
4、 负责区域管辖客户相关项目的管理、跟进与促成，定期做项目进度汇总；
5、 负责收集并及时、有效地解决客户的问题，协调所辖区域客户与公司间的良好合作关系；
6、 负责所辖区域销售团队的管理，对销售指标负责；
7、 负责所辖区域销售合同的管理和过程控制，能够有效把控销售各环节，对项目整体负责；
8、 负责商务谈判和投标相关工作，统筹项目的实施、回款及项目订单安装、验收等各环节；
9、 负责与公司职能部门的协调沟通，推进项目进展及执行；
10、配合公司业务/产品的推广工作，并完成公司安排的其他相关工作。
任职要求：
1、 大专及以上学历（（暖通/热能专业毕业生优先）；
2、 30岁以下、1年以上相关工作经验（有销售或市场相关从业经验者优先）；
3、 熟练掌握office、 CAD等办公软件；
4、 性格外向、积极乐观，亲和力强，具备很强的市场敏锐度、优秀的沟通能力和职业素养；
5、 能独挡一面，具备很强的抗压能力、创新能力和团队合作精神。

工作地址：
北京市通州区新华西街58号万达广场C座
查看职位地图
**********
上海爱启环境技术工程有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
环保
公司主页：
http://www.aiqiworld.com/
公司地址：
上海市浦东新区民生路1518号金鹰大厦B栋1601
**********
火速招猎头顾问（资源好，成单快、稳定）
北京瑞彩创新科技有限公司
**********
福利:
**********
职位月薪：6000-12000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：5人
职位类别：猎头顾问/助理
**********
先路猎头专注于为环保行业提供猎头服务，通过十年的努力我们拥有了丰富的人才和客户资源，在行业内也建立了非常好的口碑。
 猎头工作是一份能够提高个人能力，增长个人见识，实现个人价值，提高个人生活质量的有价值的工作，尤其当专注于某个领域成为某个领域的猎头专家时，更是容易获得他人的尊敬。
 环保是当前热点，国家的方针政策是要把环保产业扶持为国家的支柱产业，对于专注于这个行业的猎头来说， 我们不仅将获得良好的个人收益， 也为环保行业的发展做出了贡献。

我们成立已经十年了，公司提供的发展空间很大（目前公司是整个环保领域的人才解决方案供应商，我们提供高端的猎头服务和有全行业领先人才网-绿悠悠环保人才网），我们现在的客户不仅数量可观，关键是质量非常高，客户和项目非常靠谱，非常靠谱，非常靠谱！！！环保本身是这几年和未来非常强劲的产业，我们专注这个行业，资源可利用的多。

薪酬情况：
正常轨迹（第一年9W+；第二年16W+；第三年30W+）；
优秀人才轨迹（第一年15W+；第二年30W+；第三年50W+）；
非人类轨迹（第一年30W+；第二年100W+）。

岗位职责：
1. 获取职位信息，把握客户需求，在系统内录入新职位并报小组负责人形成项目，具体负责所分配到项目的执行，确保进度。 
2. 搜寻人才信息，获取简历、list等，认真填写相关记录，确保系统内资料的完整性，进程的有序、可查性。 
3. 筛选和面试候选人，在系统上完成面试评语，向客户推荐人选。培训和指导助理顾问,参与开拓新客户。领导安排的其他工作。

任职要求：
1、本科以上学历，三年以上工作经验（如能力优秀，这块可以适当放宽要求）；
2、有过招聘、销售、客服工作或兼职实习经验者；
3、有人力资源专业背景，人力资源从业者，对人力资源行业感兴趣的人；
4、有责任心，有感恩心，乐于帮助别人；
5、愿意与他人沟通，并希望在沟通上有所进步，持续经营自己的人脉圈；
6、善于学习，深度了解这个行业和所负责的职能；
7、高执行力，明确的事情要按时完成，说到做到！不达目标不罢休！

工作地址：
北京市海淀区北三环安贞桥西浙江大厦
查看职位地图
**********
北京瑞彩创新科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
专业服务/咨询(财会/法律/人力资源等)
公司主页：
www.xianluren.com
公司地址：
北京市朝阳区北三环安贞桥西浙江大厦
**********
外派出差6k（差旅费全报）
唐山勤领商贸有限公司北京分公司
五险一金绩效奖金包住带薪年假弹性工作员工旅游节日福利
**********
福利:
五险一金
绩效奖金
包住
带薪年假
弹性工作
员工旅游
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：北京-朝阳区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：5人
职位类别：销售代表
**********
因公司业务发展需要,特向社会诚聘销售管理人员
实习期底薪5100+提成+奖金+住宿+报销差旅费+旅游+补助+良好的晋升空间
转正底薪6000+提成+奖金+住宿+报销差旅费+旅游+补助+良好的晋升空间+五险一金
工作内容
1、开发客户，开拓市场，完成销售指标；
2、团队形式出差，负责产品的销售和推广；
3、开拓新市场，发展新客户，增加产品销售范围，完成销售任务；
4、管理维护客户关系以及客户间的长期合作计划。
任职资格：
1、18-27周岁，性格开朗，热爱销售，具有一定的团队协作精神；
2、学历经验不限，退伍军人，应庙毕业者优先；
3、反应敏捷、表达能力强，具有较强的沟通能力及交际技巧，具有亲和力；
4、具备一定的市场分析及判断能力，良好的客户服务意识；
5、有责任心，对待工作认真负责，责任心强，不甘于平凡；
一经录用，本公司将提供业务、外务、人事管理、财务管理、办公管理等系统在职培训。
福利待遇：
1、提供住宿：宿舍整洁、干净配套、设施齐全。
2、每年享受可国内外旅游机会和多次学习机会。（报销出差费用）
3、底薪+提成+奖金+外派出差机会+发展前景+带薪休假
4、综合表现优秀者可派送总部学习、深造
5、提供公平、公开、公正的晋升平台
6、每日、每周、每月、每年优秀员工奖励
7、每周有甜品水果提供（每周次数不等）
8、公司有轻松愉悦的工作环境
晋升空间：
1、晋升空间步骤.销售代表—销售主管—销售总监—销售经理；
2、长远的职业规划：晋升空间较大，发展平台广阔；
3、公司提供晋升平台：只要你有野心、敢于挑战、不断创新，提升不是问题；
因公司每日接收简历量过大，人力资源部审核时间可能延迟，急需应聘者，可来电咨询！
公司地址：北京市朝阳区西大望路soho现代城a座3005
面试时间：星期一至星期六： 下午2-4点。
工作地址：
北京市朝阳区西大望路SOHO现代城A座3005
查看职位地图
**********
唐山勤领商贸有限公司北京分公司
公司规模：
1000-9999人
公司性质：
股份制企业
公司行业：
环保
公司地址：
唐山勤领商贸有限公司北京分公司
**********
百度竞价专员/SEO/SEM网络优化专员
科氏(北京)滤膜科技有限公司
**********
福利:
**********
职位月薪：4000-8000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：SEO/SEM
**********
岗位职责：
1、负责各大搜索引擎后台的管理工作；
2、负责关键字的提炼、标题、创意的撰写工作；
3、实时关注广告效果分析报告，分析同行竞价排名实时调价；
4、 负责关键字的分析和投放；5.进行数据分析，评估关键词质量度，提出关键词的优化方案。
任职资格：
1.踏实、细心、有耐心；
2.对数据敏感，有较强的分析能力；
3.具备一定的沟通能力；
4.对网站的运营推广模式较为熟悉，对网站内容的建设、搜索引擎的优化、网站的推广、网站的咨询整个运营模式有自己的独特见解。

工作地址：
大兴区天华大街2号
查看职位地图
**********
科氏(北京)滤膜科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.kochmembrane.cn/
公司地址：
大兴区庆祥南路29号
**********
自动化工程师（电厂DCS）
北京新叶能源科技有限公司
五险一金全勤奖餐补带薪年假弹性工作定期体检
**********
福利:
五险一金
全勤奖
餐补
带薪年假
弹性工作
定期体检
**********
职位月薪：8000-16000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：5人
职位类别：空调/热能工程师
**********
岗位介绍：
1、主要工作是协助部门研发主管进行火力发电厂优化控制系统等产品的研发、设计；
2、能够熟悉常见的 DCS厂家的系统的组态与逻辑识图， 如 Ovation、 ABB、FOXBORO、和利时、日立等；
3、具备一定的 PLC 开发能力；
4、根据要求与实际情况撰写现场试验方案、报告等；
5、负责产品的现场安装和调试等工作，前期可以在指导下进行图纸设计（AutoCAD、Visio）等。

任职要求：
1、 本科及以上学历，热工、自动化等相关专业；
2、具有电厂热工相关经验优先，能适应出差；
3、条件优异者，薪资面议；
4、如果你是应届生或者没有相关经验的新人，在这里我们相信你一定能够学习到很多新的知识、掌握更多的技能，并将会与公司的发展一起成长。
工作地址：
北京市海淀区中关村北二条13号
**********
北京新叶能源科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电气/电力/水利
公司地址：
北京市海淀区中关村北二条13号
查看公司地图
**********
仪器分析员（北京亦庄分公司）
北京奥达清环境检测有限公司
绩效奖金全勤奖交通补助餐补带薪年假节日福利
**********
福利:
绩效奖金
全勤奖
交通补助
餐补
带薪年假
节日福利
**********
职位月薪：4000-6000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：10人
职位类别：环境监测工程师
**********
岗位职责：
 熟练掌握GC-MS,气相色谱仪，液相色谱仪，原子吸收，原子荧光分光光度计，紫外可见分光光度计，离子色谱仪，ICP-MS, ICP-OES
任职资格:
1、本科及以上学历，应用化学、分析化学相关专业毕业；
2、两年以上GC或GC-MS操作经验，熟悉各种实验室仪器的操作；
3、有职称证优先考虑。

工作地址：
北京市大兴区亦庄凉水河二街8号院大族企业湾3号楼A座6层
查看职位地图
**********
北京奥达清环境检测有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
检验/检测/认证
公司主页：
www.aodaqing.cn
公司地址：
北京市北京经济开发区凉水河二街8号院大族企业湾3号楼6层
**********
急招 外贸业务员（英语熟练 ）
北京通蓝海科技股份有限公司
五险一金绩效奖金节日福利员工旅游交通补助加班补助通讯补贴带薪年假
**********
福利:
五险一金
绩效奖金
节日福利
员工旅游
交通补助
加班补助
通讯补贴
带薪年假
**********
职位月薪：6001-8000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：外贸/贸易专员/助理
**********
岗位职责
1、负责公司产品的销售及推广；
2、根据市场营销计划，完成部门销售指标；
3、开拓新市场,发展新客户,增加产品销售范围；

任职资格
1、熟悉外贸，具有较强的英语听、写 读 说 能力，沟通能力强；
2、1年以上外贸销售行业工作经验。有建材销售经验者优先。
3、性格外向、反应敏捷、表达能力强，具有较强的沟通能力及交际技巧，具有亲和力；
4、具备一定的市场分析及判断能力，良好的客户服务意识；
5、有责任心，能承受较大的工作压力。
 工作时间：周一至周五的早9:00至晚5:30，周六日全休，完全按照国家法定节假日休。
待遇：五险一金
本公司每年可以有一次外出旅游的机会，工作氛围比较和谐轻松，望广大的有志之士加入我们，共同奋斗！
工作地址：
北京市朝阳区安翔北里甲11号北京创业大厦B座1010室
**********
北京通蓝海科技股份有限公司
公司规模：
20-99人
公司性质：
股份制企业
公司行业：
房地产/建筑/建材/工程
公司主页：
www.3dboard.com.cn，www.3dwallpanel.net
公司地址：
北京市朝阳区安翔北里甲11号 北京创业大厦B座1010室
查看公司地图
**********
大客户销售代表【战略性新兴产业】
北京威派格科技发展有限公司
五险一金绩效奖金交通补助通讯补贴带薪年假补充医疗保险定期体检员工旅游
**********
福利:
五险一金
绩效奖金
交通补助
通讯补贴
带薪年假
补充医疗保险
定期体检
员工旅游
**********
职位月薪：6001-8000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：5人
职位类别：销售代表
**********
一个站在“互联网+”风口上的行业
   工业互联，智联供水新型设备引领产业升级。
 智慧水务，城市供水管理平台提升水务运营。
 一家引领行业发展的企业
 承接国家“十二五”水专项课题
五项建设部行业标准/一项国家标准
二次供水领域74项专利
国际工业互联联盟IIC成员
西门子SIEMENS战略合作伙伴
中国首个工程级水利综合实验平台
工业4.0标准的全新智能化工厂
 岗位职责：
1、对新建/改造类工程项目进行日常拜访，推动客户关系的深入与提升；
2、挖掘客户需求，并提供专业的解决方案，达成合作；
3、技术交流、招投标、合同谈判、收款等工作的开展。
 任职要求：
1、统招本科学历，理工科专业优先。
2、一年以上工业品行业销售经验，且业绩良好。
3、有开发长期合作客户经验者优先。
4、良好的沟通协调与协作能力。

选择一个前景无限的产业，决定着你未来广阔的发展空间。
选择一个迅速发展的企业，决定着你拥有更多的发展机会。
选择一个行业的龙头企业，决定着你将接受到更好的培养。
选择一个积极向上的团队，决定着你拥有志同道合的伙伴。
 选择我们，选择一份值得奋斗一生的事业！

工作地址：
北京市宣武区宣外大街10号庄胜广场中央办公楼北翼11层
**********
北京威派格科技发展有限公司
公司规模：
1000-9999人
公司性质：
上市公司
公司行业：
大型设备/机电设备/重工业
公司主页：
http://www.shwpg.com/
公司地址：
北京市宣武区宣外大街10号庄胜广场中央办公楼北翼11层
**********
你的能力+我们的平台（创业型市场推广）
北京百润鸿德环保科技有限公司
创业公司绩效奖金包住带薪年假弹性工作员工旅游节日福利不加班
**********
福利:
创业公司
绩效奖金
包住
带薪年假
弹性工作
员工旅游
节日福利
不加班
**********
职位月薪：6001-8000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：8人
职位类别：市场专员/助理
**********
一、<基本要求>
1.活的，手脚健全的，能说能跳的，年龄不要太大的。
2.想要成为白富美高富帅的。
3.没机会和别人拼爹的。

二、<四不招>
1.视金钱如粪土的。
2.开飞机坦克的。
3.身在曹营心在汉的。
4.这山望着那山高的。

三、<符合以下条件优先录用>
1.生活所迫，为钱所困，自觉生活没质量的。
2.负债累累，百十万不算多的。
3.有房贷、有车贷、最好再有一个私生子的。
4.有销售经验的优先录取。

四、<在我这里>
男的不需要你爸是李刚，女的不必有干爹。只有你对本公司的向往像追你初恋那般热情的！只有你的执行力像城管扫街那般雷厉！那就来吧！

五、<薪资待遇>
打酱油的4500以上，正常做的6000以上，认真做的8000以上，用心做的10000以上，拼命做的无上限，不要命的我都不敢说了，野心不必太大，信心必须够大！一个月拿不到一万两万的，千万别说来过我这里！干的是环保日化快消品,激动的心！颤抖的手你绝对没看错。

六、言归正传：有良好的沟通技能，形象气质为五官端正即可，普通话表达能力较好，年龄18到28岁。不需要有销售类工作经验（有且更好），但要有颗学习上进的心！
公司制度齐全，一年众多节日均有福利，法定节假日均放假。

这么好的福利待遇，你还不来等什么呢,拿起你的手机，抬起你的小手，轻轻的把你简历向我们投递过来，着急的可电话提前联系面试：17343151307（微信同号）

工作地址：
北京市昌平区珠江摩尔国际大厦3号楼
查看职位地图
**********
北京百润鸿德环保科技有限公司
公司规模：
10000人以上
公司性质：
股份制企业
公司行业：
快速消费品（食品/饮料/烟酒/日化）
公司地址：
北京市昌平区珠江摩尔国际大厦3号楼
**********
快消品推广顾问
北京百润鸿德环保科技有限公司
创业公司每年多次调薪绩效奖金包住弹性工作员工旅游节日福利不加班
**********
福利:
创业公司
每年多次调薪
绩效奖金
包住
弹性工作
员工旅游
节日福利
不加班
**********
职位月薪：6001-8000元/月 
工作地点：北京-昌平区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：7人
职位类别：渠道/分销专员
**********
百润鸿德帮你实现自己的人生价值，帮你能够留在北京！
诚聘快消品顾问
薪酬构成：底薪5000+5-33%提成+年终奖+精英留任奖
打酱油：月薪5000+
正常做：月薪8000+
认真做：月薪1W+
勤奋好学悟性强：上万年薪等你来战！

多重奖励：
新人奖、品质奖、价值奖、刺激大奖、职能嘉奖、个人破纪录奖、团队月度奖，冠军奖等等众多奖励 ……
年度海内外旅游（青岛、杭州、江苏、成都、秦皇岛……2018年去哪……等你来！）
做什么呢？
1.新员工入职，熟悉了解产品信息（公司产品种类）；详细了解客户的核心需求，精准匹配合适的产品信息；
2.与客户面对面沟通，通过事业家APP介绍产品信息，通过市场数据分析，进行拜访，回访，促成产品成交等。

不会怎么办？
培训系统：
内部培训+一对一师徒辅导制培养（带薪培训）

不要以为这是虚的，大把真实的案例摆在这里，只要你勤奋、积极正面、好学，百润鸿德欢迎你的加入！！不管是职场小白or成熟的职场人士！
你将获得的是：
★ 轻松过万的月薪，人均十五万的年薪，五十万年薪的机会！
★ 简单正能量、扁平化管理模式，舒适的的办公环境，轻松愉快工作氛围！
★一对一师徒，带薪培训！
★因人制宜，所有岗位均可内部提升！

有人说，你们要求过于严格了
你是什么样的人，你就会遇到什么样的人
人生不搏不精彩，百润鸿德愿意陪你成长
为何不在百润鸿德遇到更好的自己呢？
联系方式：17343151307（朱经理） 微信同号
上班时间：早上八点半到下午六点，周天休息，节假日放假！
工作地址：
北京市昌平区珠江摩尔国际大厦3号楼
查看职位地图
**********
北京百润鸿德环保科技有限公司
公司规模：
10000人以上
公司性质：
股份制企业
公司行业：
快速消费品（食品/饮料/烟酒/日化）
公司地址：
北京市昌平区珠江摩尔国际大厦3号楼
**********
英文教师（亦庄校区）
北京蕴星教育咨询有限公司
五险一金绩效奖金全勤奖包住带薪年假节日福利
**********
福利:
五险一金
绩效奖金
全勤奖
包住
带薪年假
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：北京-大兴区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：5人
职位类别：外语教师
**********
岗位职责：
1.能够全英文授课，并保证教学质量；
1、Can teach in English and ensure the quality of instruction.
2、能够进行教室和教具的日常维护和管理；
2、Do the routine maintenance and management of classrooms and teaching aids.;
3、时常为学员组织课程活动；
3. Frequently organization curriculum activities for students;

4、 能够通过电话教学、日常沟通等方式对学生的学习效果进行跟踪，为家长提供优秀的教学售后服务；4、Track students’ learning progress through telephone teaching, daily communication, and so on. Provide parents with excellent teaching service.
5、同时也欢迎愿意投身教育事业的优秀应届毕业生加入我们！
5、We also welcome excellent graduates who are willing to apply themselves to an educational career. Please join us.
 任职要求：
1、大专及以上学历，英语专业；
1. College or above degree, English Major;
2、一年以上教学或助教工作经验； 
2. Over one year work experience in teaching or teaching assistant;
3、形象气质佳，活泼、开朗，热爱教育工作，喜欢孩子 
3. Presentable, lively, cheerful, love education work，like kids
4.英语口语流利，发音地道； 
4. Fluent oral English and pronunciation accurately;
5、亲和力佳，具有良好的服务意识。 
5. Good affinity and good service consciousness.
***公司为每位教师提供免费住宿、环境优良、步行10分钟；只要你够优秀，够踏实，更多平台为你而定！！！
工作地址：
亦庄经济开发区鹿海园4里博客雅苑9号楼9105室
**********
北京蕴星教育咨询有限公司
公司规模：
1000-9999人
公司性质：
上市公司
公司行业：
教育/培训/院校
公司地址：
朝阳区朝阳北路101号朝阳大悦城
查看公司地图
**********
大区经理
北京豪格科技发展有限公司
每年多次调薪五险一金绩效奖金加班补助全勤奖员工旅游
**********
福利:
每年多次调薪
五险一金
绩效奖金
加班补助
全勤奖
员工旅游
**********
职位月薪：8000-16000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：5人
职位类别：区域销售经理/主管
**********
工作职责：负责北京及华北地区销售及相关业务
任职要求：吃苦耐劳，有责任感
                有销售经验优先考虑
               有净水行业经验优先考虑
                   有一定的管理经


工作地址：
大兴区
查看职位地图
**********
北京豪格科技发展有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
耐用消费品（服饰/纺织/皮革/家具/家电）
公司地址：
南山科技园北区松坪山路5号嘉达研发大楼A栋6层
**********
新媒体运营
驾道科技有限公司
五险一金节日福利餐补定期体检通讯补贴
**********
福利:
五险一金
节日福利
餐补
定期体检
通讯补贴
**********
职位月薪：5000-8500元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：新媒体运营
**********
岗位职责：
1、负责管理公司的微博与微信及公司网站，包括日常内容编辑、发布、维护、管理；
2、负责微博及微信运营策略、活动、话题的制定及执行，带动用户和粉丝数量增长；
3、负责策划、撰稿、实施、评估新闻传播、广告投放、市场活动等；
4、跟踪线上各平台推广效果，分析数据并及时反馈，提升官方公众平台的影响力与活跃度；
5、负责公司的对外联合推广，提高品牌影响力和认知度。

任职要求：
1、本科及以上学历，1年及以上相关工作经验；
2、具备较强的语言编辑能力，能独立撰写新闻稿、策划文案；
3、具备领先的品牌管理理念和市场营销理念，能独立运作媒体；
4、会使用PS等软件，具备基础的设计美工能力；
5、责任心强，有良好的团队合作精神，具有媒体资源者优先。

工作地址：
北京市海淀区中关村南大街1号友谊宾馆雅园公寓
查看职位地图
**********
驾道科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.jiadao31.com/
公司地址：
北京市海淀区中关村南大街1号友谊宾馆雅园63831室
**********
运维工程师
驾道科技有限公司
**********
福利:
**********
职位月薪：7000-13000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：IT技术支持/维护工程师
**********
1、熟悉常用数据库软件及各类网管设备的部署、监控、异常分析；
2、熟悉Linux系统，能够在linux环境下进行软件系统的运维管理；
3、熟悉机房运维，包括UPS、发电机等基础设施运维等；
4、熟悉局域网系统构架管理、TCP/IP、路由器、交换机、防火墙、网络存储、网络安全、数据库备份、网络的组建和维护、数据库、网络设备等的维护管理等工作；
5、有天融信、华为等产品运维经验者优先考虑录用；
6、有较强的自学能力和沟通能力，能不断自我学习以满足项目需要
工作地址：
北京市海淀区中关村南大街1号友谊宾馆雅园公寓
查看职位地图
**********
驾道科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.jiadao31.com/
公司地址：
北京市海淀区中关村南大街1号友谊宾馆雅园63831室
**********
运维工程师（主管）
驾道科技有限公司
五险一金餐补通讯补贴节日福利带薪年假定期体检
**********
福利:
五险一金
餐补
通讯补贴
节日福利
带薪年假
定期体检
**********
职位月薪：15001-20000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：IT技术支持/维护工程师
**********
工作职责
1、负责公司云计算中心机房网络及设备运行维护，包括网络通讯、访问控制、安全防护、设备巡检、设备故障修复等。
2、负责公司云计算中心机房软件及数据库运行维护，包括软件运行监控、软件升级、数据库运行监控、数据备份、数据容灾等。
3、负责公司云平台检测线日常监控，包括检测线软硬件绑定监控、设备校准/自检数据上传、检测视频、检测过程数据智能分析等。
4、负责公司检测线与云平台联网技术支持，包括热线服务电话接听、业务答疑、检测线云检测培训等。
5、团队建设与管理，包括机房运维、检测线联网技术支持、检测线日常监控等人员的招聘、培训及日常管理。

任职资格

1. 3年的大型平台运维经验；精通常用数据库软件及各类网管设备的部署、监控、异常分析；
2．有数据机房等的运维系统架构和机房规划建设经验；
3. 熟悉Linux系统，能够在linux环境下进行软件系统的运维管理；
4. 熟悉机房运维，包括UPS、发电机等基础设施运维等
5、熟悉局域网系统构架管理、TCP/IP、路由器、交换机、防火墙、网络存储、网络安全、数据库备份、网络的组建和维护、数据库、网络设备等的维护管理等工作；
6、 高度的责任心、良好的沟通技巧和团队合作精神；
7、 具备较强的领导力、执行力以及沟通能力，具备强烈的进取心、求知欲及团队管理能力；
8、 具备较强的统筹、分析、综合、归纳和解决问题的能力；



工作地址：
北京市海淀区中关村南大街1号友谊宾馆雅园公寓
查看职位地图
**********
驾道科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.jiadao31.com/
公司地址：
北京市海淀区中关村南大街1号友谊宾馆雅园63831室
**********
技术支持
驭创(北京)环境设备有限公司
五险一金绩效奖金年终分红餐补通讯补贴带薪年假定期体检
**********
福利:
五险一金
绩效奖金
年终分红
餐补
通讯补贴
带薪年假
定期体检
**********
职位月薪：6001-8000元/月 
工作地点：北京-朝阳区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：售前/售后技术支持工程师
**********
岗位职责：
1、MA（煤安认证）/KA（矿安认证）/ISO认证的相关工作，包括工厂厂内实验平台建设的协调跟踪
2、核算制订和编写技术方案，商务报价，授权文件，标书，技术方案的制定，与客户进行技术交流，解答客户技术疑问
3、维护协调客户关系，项目跟踪，商务合同审核和跟踪，协调并协助解决售后服务问题（不出差）
 任职要求：
1、具有团队协作精神，诚实可靠，工作积极负责，身体健康，乐观向上。
2、本科要求1-2年以上相关工作经验。具有售前咨询、标书制作、撰写产品技术方案等工作经验。
3、工科本科及以上学历，最好是机械、暖通、流体、机电工程或机电一体化专业背景。
4、熟练使用AutoCAD软件，会FLUENT软件或Solidworks优先。
5、较强的引导客户需求的能力和方案撰写能力，能够独立负责公司重大项目的招投标和项目招标前的项目支持。
6、具有较强的行业信息搜集能力。
7、 熟练使用Office、PDF等文档办公软件。

工作地点：北京
工作地址：
北京市朝阳区光华路7号汉威大厦西区28层B2室
**********
驭创(北京)环境设备有限公司
公司规模：
20-99人
公司性质：
外商独资
公司行业：
大型设备/机电设备/重工业
公司主页：
www.zitron.com.cn
公司地址：
北京市朝阳区光华路7号汉威大厦西区28层B2室
查看公司地图
**********
财务会计/主管会计/会计
北京同方电气工程有限公司
五险一金绩效奖金包吃包住通讯补贴定期体检节日福利
**********
福利:
五险一金
绩效奖金
包吃
包住
通讯补贴
定期体检
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：北京-房山区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：会计/会计师
**********
任职资格：
1、大专以上学历及3年以上相关工作经验，会计从业资格证书及会计职称证书；2、熟悉国家财务政策法律法规。
3、沟通、协调能力较强，具有良好的服务意识。
4、熟练使用财务软件及其他办公软件及办公设备
5、坚持原则、廉洁自律、保守公司秘密等职业素养。

工作职责：
1、独立建立各公司年度电子账簿；
2、审核出纳填制的财务收支原始凭证；
3、审核物资采购及各项管理费用是否有流程审批；
4、成本费用的核算准确无误、各项税金的计提与上报；
5、及时进行领购发票、开具发票、及保管发票，月底对税控器进行报数授权。
6、收款、付款合同的接收与保管并建立相应的台账（年底进行合同印花税的粘贴）。
7、每月与供货商及客户进行账款核对，随时能给领导提供往来明细。
8、每月对固定资产、库存材料、及库存现金、银行盘点核对与保管责任人进行签字确认。
9、按照统计直报网规定时间进行公司统计报表的填报，并建立统计台账与登记管理工作。
10、对公司的会计凭证、帐薄报表、合同等会计资料定期收集、审查、装订成册，登记编号，按照档案管理办法的规定妥善保管。
11、按时完成每月对内对外的财务报表
12、遵守公司的各项制度


工作地址：
北京市房山区良乡西潞街道南上岗村安琪儿美语幼儿园南100米
查看职位地图
**********
北京同方电气工程有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电气/电力/水利
公司主页：
www.autotongfang.com
公司地址：
北京市房山区良乡西潞街道南上岗村安琪儿美语幼儿园南100米
**********
人事行政岗
北京同方电气工程有限公司
五险一金包吃通讯补贴定期体检节日福利
**********
福利:
五险一金
包吃
通讯补贴
定期体检
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：北京-房山区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：人力资源专员/助理
**********
岗位职责：
1、负责实施企业人才招聘、录用手续、考勤统计、绩效考核、岗位异动、奖惩、辞退、劳动合同、员工档案、住房公积金、社会保险等事宜，并形成报表。
2、负责公司级档案收集、整理、保管、利用、统计、销毁工作，并形成报表。
3、负责组织实施公司培训管理工作。包括员工证件验审、取证、新员工入职培训、年度培训计划的汇总、培训组织协调，并形成培训档案。
4、负责实施企业网站建设与更新、对外接待、同方内部期刊编辑与发行、企业宣传栏、文化墙建设、公司大事纪记录。
5、负责公司合同章、公章的保管，并形成使用台账。
6、负责公司车辆调度、维修保养、车辆保险、用车记录统计、司机安全例会、车用材料采买、车辆档案等，并形成报表。
7、电话费、宽带通、水电费、网站、域名缴费等各项办公费用的缴纳。
8、负责办公设备、办公用品的采买、登记管理、使用、保养、维修及委外印刷。
9、负责实施员工防暑降温、员工生日、劳动保护用品计划、活动用品、实物福利品、员工体检。
10、负责图书资料保管、借阅、整理等工作。
11、负责公司办公电脑、网络、电话的维护工作。
12、完成企业管理部经理临时交办的其他任务。

任职要求：
1、教育背景：人力资源、管理或相关专业专科以上学历。
2、对现代企业人力资源管理模式有系统的了解和实践经验积累，对人力资源管理各个职能模块均有较深入的认识，能够指导各个职能模块的工作；
3、熟悉办公软件及相关的人事管理软件；

工作地址：
北京市房山区良乡西潞街道南上岗村安琪儿美语幼儿园南100米
查看职位地图
**********
北京同方电气工程有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电气/电力/水利
公司主页：
www.autotongfang.com
公司地址：
北京市房山区良乡西潞街道南上岗村安琪儿美语幼儿园南100米
**********
预算员
北京同方电气工程有限公司
五险一金绩效奖金包吃包住通讯补贴定期体检节日福利
**********
福利:
五险一金
绩效奖金
包吃
包住
通讯补贴
定期体检
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：北京-房山区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：工程造价/预结算
**********
任职资格:
1、中专及以上相关学历，持有造价员证书；
2、具有3年以上预算实际工作经验，对建筑材料市场价格熟悉及掌握一般土建或电气工程项目施工工艺做法；
3、熟练编制工程项目预算；
4、熟练使用广联达预算软件、office等办公软件；
5、能够较全面地熟悉施工图纸，了解工程性质、结构形式、各系统的组成、建筑工程相关设备和材料的规格和品种以及新材料新工艺的采用。
 工作职责：
3、负责编制公司对外工程施工预算、施工合同。组织施工合同评审。
4、负责所有工地现场工作量的核实。
5、负责工程项目的人工费、机械费、材料费的审核。
6、负责编制工程劳务分包价格、分包合同以及劳务分包款的结算。
8、负责工程合同预付款、进度款结算办理。
9、负责审核工程洽商、工作量确认单内容等工作。
10、负责编制并上报各工程项目经营数据报表。
7、负责编制公司投标项目商务标、技术明标及投标文件的组卷、装订。组织投标工作。
 
工作地址：
北京市房山区良乡西潞南大街5号同方大厦412室
查看职位地图
**********
北京同方电气工程有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电气/电力/水利
公司主页：
www.autotongfang.com
公司地址：
北京市房山区良乡西潞街道南上岗村安琪儿美语幼儿园南100米
**********
会计
北京同方电气工程有限公司
五险一金包吃通讯补贴定期体检节日福利
**********
福利:
五险一金
包吃
通讯补贴
定期体检
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：会计/会计师
**********
任职资格：
1、大专以上学历及3年以上相关工作经验，会计从业资格证书及会计职称证书；2、熟悉国家财务政策法律法规。
3、沟通、协调能力较强，具有良好的服务意识。
4、熟练使用财务软件及其他办公软件及办公设备
5、坚持原则、廉洁自律、保守公司秘密等职业素养。

工作职责：
1、独立建立各公司年度电子账簿；
2、审核出纳填制的财务收支原始凭证；
3、审核物资采购及各项管理费用是否有流程审批；
4、成本费用的核算准确无误、各项税金的计提与上报；
5、及时进行领购发票、开具发票、及保管发票，月底对税控器进行报数授权。
6、收款、付款合同的接收与保管并建立相应的台账（年底进行合同印花税的粘贴）。
7、每月与供货商及客户进行账款核对，随时能给领导提供往来明细。
8、每月对固定资产、库存材料、及库存现金、银行盘点核对与保管责任人进行签字确认。
9、按照统计直报网规定时间进行公司统计报表的填报，并建立统计台账与登记管理工作。
10、对公司的会计凭证、帐薄报表、合同等会计资料定期收集、审查、装订成册，登记编号，按照档案管理办法的规定妥善保管。
11、按时完成每月对内对外的财务报表
12、遵守公司的各项制度

工作地址：
房山区良乡西潞街道南上岗村
查看职位地图
**********
北京同方电气工程有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电气/电力/水利
公司主页：
www.autotongfang.com
公司地址：
北京市房山区良乡西潞街道南上岗村安琪儿美语幼儿园南100米
**********
电气工程师
北京同方电气工程有限公司
五险一金包吃包住通讯补贴定期体检
**********
福利:
五险一金
包吃
包住
通讯补贴
定期体检
**********
职位月薪：10001-15000元/月 
工作地点：北京-房山区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：电气工程师
**********
任职资格：
1、电气、机电专业、大学本科及以上学历，具有助理工程师或工程师证书。
2、具备三年以上电力电子工程相关工作经验，具有现场施工工程管理，现场协调经验及项目管理经验；
3、掌握电气专业知识，管理和法律知识。
4、有较强的沟通协调能力、领导能力。
5、熟练使用办公软件及办公设备。
工作职责：
1、负责公司技术文件编制、修订。
2、负责施工方案、技术方案、安全措施、图纸、招投标的审核。
3、参与工程成本分析、合同评审。

工作地址：
北京市房山区良乡西潞街道南上岗村安琪儿美语幼儿园南100米
查看职位地图
**********
北京同方电气工程有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电气/电力/水利
公司主页：
www.autotongfang.com
公司地址：
北京市房山区良乡西潞街道南上岗村安琪儿美语幼儿园南100米
**********
施工员
北京同方电气工程有限公司
五险一金绩效奖金包吃包住餐补通讯补贴定期体检节日福利
**********
福利:
五险一金
绩效奖金
包吃
包住
餐补
通讯补贴
定期体检
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：2人
职位类别：建筑施工现场管理
**********
任职资格:
1、具有一定的责任心、身体健康、热爱集体。
3、供电类、电气技术类、机电类专业中专及以上学生
工作职责：
1、按时保质保量的完成所承担施工任务。
2、严格执行技术交底和安全交底要求。
3、配合负责人 做好施工机具维护管理。
4、保证施工过程中的工作安全及文明施工 。
5、对所施工的工作质量负责。  


工作地址：
北京市房山区良乡西潞街道南上岗村安琪儿美语幼儿园南100米
查看职位地图
**********
北京同方电气工程有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电气/电力/水利
公司主页：
www.autotongfang.com
公司地址：
北京市房山区良乡西潞街道南上岗村安琪儿美语幼儿园南100米
**********
人事行政专员
北京同方电气工程有限公司
五险一金包吃定期体检高温补贴节日福利通讯补贴
**********
福利:
五险一金
包吃
定期体检
高温补贴
节日福利
通讯补贴
**********
职位月薪：4001-6000元/月 
工作地点：北京-房山区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：人力资源专员/助理
**********
岗位职责：
1、负责实施企业人才招聘、录用手续、考勤统计、绩效考核、岗位异动、奖惩、辞退、劳动合同、员工档案、住房公积金、社会保险等事宜，并形成报表。
2、负责公司级档案收集、整理、保管、利用、统计、销毁工作，并形成报表。
3、负责组织实施公司培训管理工作。包括员工证件验审、取证、新员工入职培训、年度培训计划的汇总、培训组织协调，并形成培训档案。
4、负责实施企业网站建设与更新、对外接待、同方内部期刊编辑与发行、企业宣传栏、文化墙建设、公司大事纪记录。
5、负责公司合同章、公章的保管，并形成使用台账。
6、负责公司车辆调度、维修保养、车辆保险、用车记录统计、司机安全例会、车用材料采买、车辆档案等，并形成报表。
7、电话费、宽带通、水电费、网站、域名缴费等各项办公费用的缴纳。
8、负责办公设备、办公用品的采买、登记管理、使用、保养、维修及委外印刷。
9、负责实施员工防暑降温、员工生日、劳动保护用品计划、活动用品、实物福利品、员工体检。
10、负责图书资料保管、借阅、整理等工作。
11、负责公司办公电脑、网络、电话的维护工作。
12、完成企业管理部经理临时交办的其他任务。

任职要求：
1、教育背景：人力资源、管理或相关专业专科以上学历。
2、对现代企业人力资源管理模式有系统的了解和实践经验积累，对人力资源管理各个职能模块均有较深入的认识，能够指导各个职能模块的工作；
3、熟悉办公软件及相关的人事管理软件；

工作地址：
北京市房山区良乡西潞街道南上岗村安琪儿美语幼儿园南100米
查看职位地图
**********
北京同方电气工程有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电气/电力/水利
公司主页：
www.autotongfang.com
公司地址：
北京市房山区良乡西潞街道南上岗村安琪儿美语幼儿园南100米
**********
土壤样品分析检测
北京环标科创环境科技发展有限责任公司
五险一金绩效奖金餐补带薪年假定期体检
**********
福利:
五险一金
绩效奖金
餐补
带薪年假
定期体检
**********
职位月薪：4000-7000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：1人
职位类别：环保技术工程师
**********
岗位职责：
1、负责土壤标准样品及质控考核样品的研制和分析；
2、负责实验室间比对和能力验证计划的实施；
3、参与土壤、沉积物等固体标准样品研究与开发；
4、参与本领域科研项目建议与申报；
5、参与环境基体标准样品分析方法的开发和验证。

任职要求：
1、分析化学、环境化学、仪器分析等相关专业，本科及以上；
2、具备化学分析基础，熟悉实验室仪器设备的使用；
3、具有一定土壤分析、研究经验者优先；
4、具有良好的沟通和团队合作能力。
工作地址：
北京市朝阳区育慧南路1号
**********
北京环标科创环境科技发展有限责任公司
公司规模：
20-99人
公司性质：
国企
公司行业：
环保
公司地址：
北京市朝阳区育慧南路1号
**********
文员出纳
山西蓝天环保设备有限公司
五险一金通讯补贴餐补节日福利带薪年假
**********
福利:
五险一金
通讯补贴
餐补
节日福利
带薪年假
**********
职位月薪：2001-4000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：会计助理/文员
**********
1.有出纳经验
2.有文员经验
3.做事认真细心，为人温和。
工作地址：
北京朝阳区立水桥南-北科创业大厦11层
查看职位地图
**********
山西蓝天环保设备有限公司
公司规模：
500-999人
公司性质：
民营
公司行业：
大型设备/机电设备/重工业
公司主页：
www.sxlantian.com
公司地址：
山西省太原市万柏林区迎泽西大街100号国际能源中心30层
**********
急招猎头顾问助理（入门快 资源多 客户好）
北京瑞彩创新科技有限公司
绩效奖金年终分红交通补助通讯补贴带薪年假不加班补充医疗保险员工旅游
**********
福利:
绩效奖金
年终分红
交通补助
通讯补贴
带薪年假
不加班
补充医疗保险
员工旅游
**********
职位月薪：4000-8000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：4人
职位类别：猎头顾问/助理
**********
先路猎头专注于为环保行业提供猎头服务，通过十年的努力我们拥有了丰富的人才和客户资源，在行业内也建立了非常好的口碑。
 猎头工作是一份能够提高个人能力，增长个人见识，实现个人价值，提高个人生活质量的有价值的工作，尤其当专注于某个领域成为某个领域的猎头专家时，更是容易获得他人的尊敬。
 环保是当前热点，国家的方针政策是要把环保产业扶持为国家的支柱产业，对于专注于这个行业的猎头来说， 我们不仅将获得良好的个人收益， 也为环保行业的发展做出了贡献。

我们成立已经十年了，公司提供的发展空间很大（目前公司是整个环保领域的人才解决方案供应商，我们提供高端的猎头服务和有全行业领先人才网-绿悠悠环保人才网），我们现在的客户不仅数量可观，关键是质量非常高，客户和项目非常靠谱，非常靠谱，非常靠谱！！！环保本身是这几年和未来非常强劲的产业，我们专注这个行业，资源可利用的多。

薪酬情况：
正常轨迹（第一年6W+；第二年12W+；第三年20W+）； 
优秀人才轨迹（第一年10W+；第二年20W+；第三年30W+）； 
非人类轨迹（第一年20W+；第二年60W+）。

岗位职责：
 1、 配合猎头顾问的工作，进行项目操作； 
2、通过公司系统和其他资源联系目标人选； 
3、收集目标行业和客户信息 
 4、公司分配的其他任务。 

任职要求： 
1、本科以上学历，一年以上工作经验（如能力优秀，这块可以适当放宽要求）； 
2、对人力资源行业感兴趣的人；
3、良好的沟通能力、学习能力。踏实、勤奋，能够在压力下开展工作； 
4、有过招聘、销售、客服工作或兼职实习经验者更佳；
5、高执行力，明确的事情要按时完成，说到做到！不达目标不罢休！

工作地址：
北京市海淀区北三环安华桥东浙江大厦
**********
北京瑞彩创新科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
专业服务/咨询(财会/法律/人力资源等)
公司主页：
www.xianluren.com
公司地址：
北京市朝阳区北三环安贞桥西浙江大厦
查看公司地图
**********
办公文员
北京立道立德科技有限公司
**********
福利:
**********
职位月薪：4000-6000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：5人
职位类别：助理/秘书/文员
**********
职位要求：会操作电脑，会做ppt、表格等基本办公业务，具备沟通能力，勤快敬业，服从管理，男女不限，年龄38岁以内。
工作地址：
西城区白广路7号
查看职位地图
**********
北京立道立德科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.bjldld.com/
公司地址：
北京市丰台区小屯路9号立高大厦8层
**********
区域销售经理
盛旦节能技术(北京)有限公司
五险一金绩效奖金餐补带薪年假节日福利加班补助通讯补贴交通补助
**********
福利:
五险一金
绩效奖金
餐补
带薪年假
节日福利
加班补助
通讯补贴
交通补助
**********
职位月薪：8001-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：6人
职位类别：销售工程师
**********
职位描述:
1．负责公司光导照明产品的销售、开发新客户；
2．与客户建立良好关系，及时反馈客户信息，满足客户需求，提高客户满意度；
3．制定销售计划、完成销售目标；
4．与设计院、设计师保持良好的关系，定期组织技术交流，推广公司产品；
5．完成季度和年底区域销售任务、按时汇报工作情况；
6．协助公司完善区域设计院合作网络，搜集项目信息，跟进项目进展，实现销售目标。
7、公司交办的其他事项。

任职要求：
1、 大专以上学历，2年以上建材、工程类销售经验；
2、 思路清晰，有较强的表达及沟通能力、具备良好的客户开拓能力；
3、 能承受工作压力，能经常出差。
4、 具备较强的市场分析、营销、推广能力和良好的人际沟通、协调能力，分析和解决问题的能力；
5、 能独立跟进工程项目。
6、 有建筑材料销售经验、有设计院资源者优先考虑。
工作地址：
北京市丰台区南三环东路金城中心601
查看职位地图
**********
盛旦节能技术(北京)有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司主页：
http://www.sundome.com.cn
公司地址：
北京市丰台区南三环东路金城中心601
**********
游玩式销售/可出差+住宿
北京百润鸿德环保科技有限公司
创业公司绩效奖金包住带薪年假弹性工作员工旅游节日福利不加班
**********
福利:
创业公司
绩效奖金
包住
带薪年假
弹性工作
员工旅游
节日福利
不加班
**********
职位月薪：6001-8000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：8人
职位类别：销售代表
**********
薪酬绩效：
基本工资（4500-6000）+业绩提成（5%-33%销售额提成）+冠军奖励（日奖、周奖、月奖）+ 一次性奖励（扫码、抽奖）+团队开拓奖（出差优秀团队奖）+领导奖励（优秀团队领导者奖励）+协同奖励（优秀团队协作者奖励）+导师奖励（培训、奖励）+育人奖励+业绩分红

公司免费提供住宿，小区房，走路上班十几分钟，家电齐全！

岗位职责：
1、根据出差市场营销计划，完成部门销售指标；
2、开拓新市场，了解新市场，发展新客户，增加产品销售范围；
3、维护公司现有老客户，维护公司品牌形象；
4、主要负责公司产品的销售及推广。

任职要求：
1、16-28岁 有志青年、不限男女，不限学历；
2、外向健谈,应变能力强,积极主动,有较好的沟通能力；
3、有上进心,有较强的学习模仿能力；
4、思路清晰,具有良好的沟通应变能力和执行力。

一切差旅费由公司提供。
欢迎致电：朱经理 17343151307（微信同号）
 本公司郑重承诺：所有岗位入职不收取任何费用，公司免费提供岗位技能培训，敬请求职者周知。

工作地址：
北京市昌平区珠江摩尔国际大厦3号楼
查看职位地图
**********
北京百润鸿德环保科技有限公司
公司规模：
10000人以上
公司性质：
股份制企业
公司行业：
快速消费品（食品/饮料/烟酒/日化）
公司地址：
北京市昌平区珠江摩尔国际大厦3号楼
**********
电气造价员/预算员（电力施工）
北京同方电气工程有限公司
五险一金绩效奖金包吃包住通讯补贴定期体检节日福利
**********
福利:
五险一金
绩效奖金
包吃
包住
通讯补贴
定期体检
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：北京-房山区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：工程造价/预结算
**********
任职资格：
1、具有大学专科或以上学历，电气、机电等相关专业；
2、熟练操作广联达软件，熟悉掌握CAD等办公软件；
3、1年以上电力输变电工程（安装和土建）工程造价经验，熟悉电网相关定额和规程，有预算员（安装或土建）证书或造价工程师（安装或土建）证书优先考虑。

岗位职责：
1、负责编制建筑工程量清单及工程标底，参与工程合同的谈判、签订与管理工作；
2、负责对建筑、结构等工程进行施工图预算审核，办理结算手续；
3、负责安装工程设计变更、签证、洽商的审查及造价的审核；
4、熟练掌握安装、市政工程相关知识，对施工工艺和流程有详细的了解；
5、参与现场工程量实测、计算及审核。

工作地址：
北京市房山区良乡西潞街道南上岗安琪儿美语幼儿园南100米
查看职位地图
**********
北京同方电气工程有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电气/电力/水利
公司主页：
www.autotongfang.com
公司地址：
北京市房山区良乡西潞街道南上岗村安琪儿美语幼儿园南100米
**********
现场检测员（北京亦庄分公司）
北京奥达清环境检测有限公司
绩效奖金交通补助餐补带薪年假加班补助全勤奖免费班车员工旅游
**********
福利:
绩效奖金
交通补助
餐补
带薪年假
加班补助
全勤奖
免费班车
员工旅游
**********
职位月薪：3000-5500元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：环保技术工程师
**********
面试地点：北京亦庄  上班地点：亦庄
岗位职责：
 负责环境监测、环境评价等项目的样品采集
 任职要求：
1、大专及以上学历，环境或相关专业毕业；
2、熟练样品采集（如大气、水质、烟尘、土壤、噪声等），熟练操作采样仪器，有相关工作经验优先考虑；
3、有较好的沟通能力，能吃苦耐劳，有团队意识；
4、能够适应短期出差采样；
5、有车人员优先考虑；
6、采样兼职司机。
      公司可提供住宿！

工作地址：
北京市大兴经济开发区亦庄凉水河二街8号院企业湾3号楼A座6层
**********
北京奥达清环境检测有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
检验/检测/认证
公司主页：
www.aodaqing.cn
公司地址：
北京市北京经济开发区凉水河二街8号院大族企业湾3号楼6层
查看公司地图
**********
销售主管
润柏斯特(北京)环保科技发展有限公司
创业公司年底双薪绩效奖金年终分红交通补助通讯补贴带薪年假员工旅游
**********
福利:
创业公司
年底双薪
绩效奖金
年终分红
交通补助
通讯补贴
带薪年假
员工旅游
**********
职位月薪：8001-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：3人
职位类别：销售主管
**********
Skills, Qualifications, Experience技能，资格，经验:
有良好的人际沟通能力，优秀的语言表达能力，能够与顾客建立长期的 工作伙伴关系。
有开发五星级酒店、高档写字楼、机场车站、大型场馆、国家部委和央企总部办公楼、重点科研院所、三甲医院、银行办公楼、高档会所等商业客户直销经验优先；
有开发机械制造、食品制药、军工、电子、IT研发制造、铁路、油田、航天科研和其他世界500强工厂等工业客户直销经验者优先。
有快速消费品或环卫系统直销经验者优先。
具有极强的独立发展客户关系的能力。
具有较强的协调、组织、执行能力。
能以积极乐观的态度适应和面对改变，能接受压力与挑战。
良好的电脑操作技能。
一年以上销售工作经验。
  工作地址：
顺义区顺平路阳光加油站南700米院内
查看职位地图
**********
润柏斯特(北京)环保科技发展有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
环保
公司地址：
顺义区顺平路阳光加油站南700米院内
**********
验收部助理（亦庄分公司）
北京奥达清环境检测有限公司
绩效奖金加班补助交通补助餐补带薪年假员工旅游全勤奖免费班车
**********
福利:
绩效奖金
加班补助
交通补助
餐补
带薪年假
员工旅游
全勤奖
免费班车
**********
职位月薪：4001-6000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：环境监测工程师
**********
岗位职责：
1.从事建设项目竣工环境保护验收工作（现场调查、方案编制、现场检测，验收报告编制，验收申报与审批）。
2.协同检测人员进行现场检测，帮助项目负责人整理项目资料，汇总数据，编制竣工环保验收方案及报告。

任职要求：
专业：环境科学及相关专业
学历：本科及以上
1.诚恳好学、对工作充满热情、服从领导安排、有亲和力、有团队精神。
2.熟练掌握办公软件、专业相关软件。
3.工作积极、认真、负责，有较强的进取精神，善于与人沟通。
4.在学习、工作期间参与过科研及相关项目历者优先。
5.能够适应经常外出现场，有驾照者优先。

工作地址：
北京市北京经济开发区凉水河二街8号院大族企业湾3号楼6层
查看职位地图
**********
北京奥达清环境检测有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
检验/检测/认证
公司主页：
www.aodaqing.cn
公司地址：
北京市北京经济开发区凉水河二街8号院大族企业湾3号楼6层
**********
反渗透膜纳滤膜超滤膜业务经理
科氏(北京)滤膜科技有限公司
通讯补贴年底双薪绩效奖金年终分红交通补助带薪年假节日福利员工旅游
**********
福利:
通讯补贴
年底双薪
绩效奖金
年终分红
交通补助
带薪年假
节日福利
员工旅游
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：10人
职位类别：业务拓展经理/主管
**********
岗位职责：
1、 RO/NF/UF膜产品的市场开发与销售；
2、 制定本区域营销计划、分解销售目标；
3、 配合全国各地代理商开展工作，完成公司业务目标；
4、 直接参与、主持重要客户的业务技术交流、谈判及成交；
5、 督导代理商及老客户业务开展工作，落实本区域货款回收；
6、 控制所辖区域相互竞争、协调客户反馈信息及现场业主等问题。
任职要求：
1、专科以上学历；环境工程、给排水、电厂化学、化工工艺等相关专业优先；
2、1年以上销售工作经验；
3、了解、熟悉反渗透膜/纳滤膜/超滤膜等水处理系统设计者优先考虑；
4、善于掌握市场信息，具有敏锐的市场观察力、判断力；
5、能够独立组织协调工作，能够适应出差。
工作地址：
大兴区天华大街2号
**********
科氏(北京)滤膜科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.kochmembrane.cn/
公司地址：
大兴区庆祥南路29号
查看公司地图
**********
反渗透膜纳滤膜超滤膜大区总监
科氏(北京)滤膜科技有限公司
通讯补贴年底双薪绩效奖金年终分红交通补助带薪年假节日福利员工旅游
**********
福利:
通讯补贴
年底双薪
绩效奖金
年终分红
交通补助
带薪年假
节日福利
员工旅游
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：10人
职位类别：区域销售总监
**********
岗位职责：
1、 RO/NF/UF膜产品的市场开发与销售；
2、 制定本区域营销计划、分解销售目标；
3、 配合全国各地代理商开展工作，完成公司业务目标；
4、 直接参与、主持重要客户的业务技术交流、谈判及成交；
5、 督导代理商及老客户业务开展工作，落实本区域货款回收；
6、 控制所辖区域相互竞争、协调客户反馈信息及现场业主等问题。
任职要求：
1、环境工程、给排水、电厂化学、化工工艺等相关专业；
2、3-5年以上销售工作经验；专科以上学历；
3、了解、熟悉反渗透膜/纳滤膜/超滤膜等水处理系统设计者优先考虑；
4、善于掌握市场信息，具有敏锐的市场观察力、判断力；
5、能够独立组织协调工作，能够适应出差。
工作地址：
大兴区天华大街2号
**********
科氏(北京)滤膜科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.kochmembrane.cn/
公司地址：
大兴区庆祥南路29号
查看公司地图
**********
反渗透膜纳滤膜超滤膜业务主管
科氏(北京)滤膜科技有限公司
通讯补贴年底双薪绩效奖金年终分红交通补助带薪年假节日福利员工旅游
**********
福利:
通讯补贴
年底双薪
绩效奖金
年终分红
交通补助
带薪年假
节日福利
员工旅游
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：10人
职位类别：业务拓展经理/主管
**********
岗位职责：
1、 RO/NF/UF膜产品的市场开发与销售；
2、 制定本区域营销计划、分解销售目标；
3、 配合全国各地代理商开展工作，完成公司业务目标；
4、 直接参与、主持重要客户的业务技术交流、谈判及成交；
5、 督导代理商及老客户业务开展工作，落实本区域货款回收；
6、 控制所辖区域相互竞争、协调客户反馈信息及现场业主等问题。
任职要求：
1、环境工程、给排水、电厂化学、化工工艺等相关专业；
2、专科以上学历；
3、1年以上销售工作经验；
4、了解、熟悉反渗透膜/纳滤膜/超滤膜等水处理系统设计者优先考虑；
5、善于掌握市场信息，具有敏锐的市场观察力、判断力；
6、能够独立组织协调工作，能够适应出差。
工作地址：
大兴区天华大街2号
**********
科氏(北京)滤膜科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.kochmembrane.cn/
公司地址：
大兴区庆祥南路29号
查看公司地图
**********
反渗透膜纳滤膜超滤膜渠道主管
科氏(北京)滤膜科技有限公司
通讯补贴年底双薪绩效奖金年终分红交通补助带薪年假节日福利员工旅游
**********
福利:
通讯补贴
年底双薪
绩效奖金
年终分红
交通补助
带薪年假
节日福利
员工旅游
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：10人
职位类别：渠道/分销经理/主管
**********
岗位职责：
1、 RO/NF/UF膜产品的市场开发与销售；
2、 制定本区域营销计划、分解销售目标；
3、 配合全国各地代理商开展工作，完成公司业务目标；
4、 直接参与、主持重要客户的业务技术交流、谈判及成交；
5、 督导代理商及老客户业务开展工作，落实本区域货款回收；
6、 控制所辖区域相互竞争、协调客户反馈信息及现场业主等问题。
任职要求：
1、环境工程、给排水、电厂化学、化工工艺等相关专业；
2、专科以上学历；1-3年以上销售工作经验；
3、了解、熟悉反渗透膜/纳滤膜/超滤膜等水处理系统设计者优先考虑；
4、善于掌握市场信息，具有敏锐的市场观察力、判断力；
5、能够独立组织协调工作，能够适应出差。
工作地址：
大兴区天华大街2号
**********
科氏(北京)滤膜科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.kochmembrane.cn/
公司地址：
大兴区庆祥南路29号
查看公司地图
**********
反渗透膜纳滤膜超滤膜销售总监
科氏(北京)滤膜科技有限公司
通讯补贴年底双薪绩效奖金年终分红交通补助带薪年假节日福利员工旅游
**********
福利:
通讯补贴
年底双薪
绩效奖金
年终分红
交通补助
带薪年假
节日福利
员工旅游
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：10人
职位类别：销售总监
**********
岗位职责：
1、 RO/NF/UF膜产品的市场开发与销售；
2、 制定本区域营销计划、分解销售目标；
3、 配合全国各地代理商开展工作，完成公司业务目标；
4、 直接参与、主持重要客户的业务技术交流、谈判及成交；
5、 督导代理商及老客户业务开展工作，落实本区域货款回收；
6、 控制所辖区域相互竞争、协调客户反馈信息及现场业主等问题。
任职要求：
1、环境工程、给排水、电厂化学、化工工艺等相关专业；专科以上学历；
2、3年以上销售工作经验；
3、了解、熟悉反渗透膜/纳滤膜/超滤膜等水处理系统设计者优先考虑；
4、善于掌握市场信息，具有敏锐的市场观察力、判断力；
5、能够独立组织协调工作，能够适应出差。
工作地址：
大兴区天华大街2号
**********
科氏(北京)滤膜科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.kochmembrane.cn/
公司地址：
大兴区庆祥南路29号
查看公司地图
**********
反渗透膜纳滤膜超滤膜渠道总监
科氏(北京)滤膜科技有限公司
通讯补贴年底双薪绩效奖金年终分红交通补助带薪年假节日福利员工旅游
**********
福利:
通讯补贴
年底双薪
绩效奖金
年终分红
交通补助
带薪年假
节日福利
员工旅游
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：10人
职位类别：渠道/分销经理/主管
**********
岗位职责：
1、 RO/NF/UF膜产品的市场开发与销售；
2、 制定本区域营销计划、分解销售目标；
3、 配合全国各地代理商开展工作，完成公司业务目标；
4、 直接参与、主持重要客户的业务技术交流、谈判及成交；
5、 督导代理商及老客户业务开展工作，落实本区域货款回收；
6、 控制所辖区域相互竞争、协调客户反馈信息及现场业主等问题。
任职要求：
1、环境工程、给排水、电厂化学、化工工艺等相关专业；
2、专科以上学历；3-5年以上销售工作经验；
3、了解、熟悉反渗透膜/纳滤膜/超滤膜等水处理系统设计者优先考虑；
4、善于掌握市场信息，具有敏锐的市场观察力、判断力；
5、能够独立组织协调工作，能够适应出差。
工作地址：
大兴区天华大街2号
**********
科氏(北京)滤膜科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.kochmembrane.cn/
公司地址：
大兴区庆祥南路29号
查看公司地图
**********
反渗透膜纳滤膜超滤膜大区经理
科氏(北京)滤膜科技有限公司
通讯补贴年底双薪绩效奖金年终分红交通补助带薪年假节日福利员工旅游
**********
福利:
通讯补贴
年底双薪
绩效奖金
年终分红
交通补助
带薪年假
节日福利
员工旅游
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：10人
职位类别：区域销售经理/主管
**********
岗位职责：
1、 RO/NF/UF膜产品的市场开发与销售；
2、 制定本区域营销计划、分解销售目标；
3、 配合全国各地代理商开展工作，完成公司业务目标；
4、 直接参与、主持重要客户的业务技术交流、谈判及成交；
5、 督导代理商及老客户业务开展工作，落实本区域货款回收；
6、 控制所辖区域相互竞争、协调客户反馈信息及现场业主等问题。
任职要求：
1、环境工程、给排水、电厂化学、化工工艺等相关专业；专科以上学历；
2、1-3年以上销售工作经验；
3、了解、熟悉反渗透膜/纳滤膜/超滤膜等水处理系统设计者优先考虑；
4、善于掌握市场信息，具有敏锐的市场观察力、判断力；
5、能够独立组织协调工作，能够适应出差。
工作地址：
大兴区天华大街2号
**********
科氏(北京)滤膜科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.kochmembrane.cn/
公司地址：
大兴区庆祥南路29号
查看公司地图
**********
反渗透膜纳滤膜超滤膜渠道经理
科氏(北京)滤膜科技有限公司
通讯补贴年底双薪绩效奖金年终分红交通补助带薪年假节日福利员工旅游
**********
福利:
通讯补贴
年底双薪
绩效奖金
年终分红
交通补助
带薪年假
节日福利
员工旅游
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：10人
职位类别：渠道/分销经理/主管
**********
岗位职责：
1、 RO/NF/UF膜产品的市场开发与销售；
2、 制定本区域营销计划、分解销售目标；
3、 配合全国各地代理商开展工作，完成公司业务目标；
4、 直接参与、主持重要客户的业务技术交流、谈判及成交；
5、 督导代理商及老客户业务开展工作，落实本区域货款回收；
6、 控制所辖区域相互竞争、协调客户反馈信息及现场业主等问题。
任职要求：
1、环境工程、给排水、电厂化学、化工工艺等相关专业；
2、2年以上销售工作经验；专科以上学历；
3、了解、熟悉反渗透膜/纳滤膜/超滤膜等水处理系统设计者优先考虑；
4、善于掌握市场信息，具有敏锐的市场观察力、判断力；
5、能够独立组织协调工作，能够适应出差。
工作地址：
大兴区天华大街2号
**********
科氏(北京)滤膜科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.kochmembrane.cn/
公司地址：
大兴区庆祥南路29号
查看公司地图
**********
实习生+免费住宿
北京百润鸿德环保科技有限公司
创业公司每年多次调薪绩效奖金包住弹性工作员工旅游节日福利不加班
**********
福利:
创业公司
每年多次调薪
绩效奖金
包住
弹性工作
员工旅游
节日福利
不加班
**********
职位月薪：6001-8000元/月 
工作地点：北京-昌平区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：8人
职位类别：实习生
**********
现公司为了学生，无经验者，退伍军人能有一个锻炼的机会，特计划：
招聘一个团队5-8人

福利待遇：
1.底薪4500+提成+奖金
2.公司免费提供住宿（小区房，上下复式楼，厨房冰箱洗衣机齐全，离公司走路十几分钟）
3.公司高管，总经理免费专业培训
4.每月公费活动，各地特色小吃

岗位职责：
1.协助管理层完成销售计划
2.维护老客户，开发新客户
3.推广公司产品，完成销售，收款，售后整个工作流程

任职要求：
1.年龄不超过26岁，不限经验和学历
2.接受实习生，应届毕业生，退伍军人
3.听从公司领导安排
4.口齿清晰，身体健康

其他事项：
1.公司有人带（一对一，不用担心不会），搭档销售（不用担心资源），游玩式工作（外出工作，时间自由）
2.入职以后，公司有内部培训
3.不压任何工资
4.公司直招，不收取任何费用
联系方式：朱经理：17343151307（微信同号）

工作地址：
北京市昌平区珠江摩尔国际大厦3号楼
查看职位地图
**********
北京百润鸿德环保科技有限公司
公司规模：
10000人以上
公司性质：
股份制企业
公司行业：
快速消费品（食品/饮料/烟酒/日化）
公司地址：
北京市昌平区珠江摩尔国际大厦3号楼
**********
反渗透膜纳滤膜超滤膜大客户销售
科氏(北京)滤膜科技有限公司
通讯补贴年底双薪绩效奖金年终分红交通补助带薪年假节日福利员工旅游
**********
福利:
通讯补贴
年底双薪
绩效奖金
年终分红
交通补助
带薪年假
节日福利
员工旅游
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：10人
职位类别：大客户销售代表
**********
岗位职责：
1、 RO/NF/UF膜产品的市场开发与销售；
2、 制定本区域营销计划、分解销售目标；
3、 配合全国各地代理商开展工作，完成公司业务目标；
4、 直接参与、主持重要客户的业务技术交流、谈判及成交；
5、 督导代理商及老客户业务开展工作，落实本区域货款回收；
6、 控制所辖区域相互竞争、协调客户反馈信息及现场业主等问题。
任职要求：
1、环境工程、给排水、电厂化学、化工工艺等相关专业；
2、专科以上学历；1年以上销售工作经验；
3、了解、熟悉反渗透膜/纳滤膜/超滤膜等水处理系统设计者优先考虑；
4、善于掌握市场信息，具有敏锐的市场观察力、判断力；
5、能够独立组织协调工作，能够适应出差。
工作地址：
大兴区天华大街2号
**********
科氏(北京)滤膜科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.kochmembrane.cn/
公司地址：
大兴区庆祥南路29号
查看公司地图
**********
反渗透膜纳滤膜超滤膜渠道专员
科氏(北京)滤膜科技有限公司
通讯补贴年底双薪绩效奖金年终分红交通补助带薪年假节日福利员工旅游
**********
福利:
通讯补贴
年底双薪
绩效奖金
年终分红
交通补助
带薪年假
节日福利
员工旅游
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：10人
职位类别：业务拓展专员/助理
**********
岗位职责：
1、 RO/NF/UF膜产品的市场开发与销售；
2、 制定本区域营销计划、分解销售目标；
3、 配合全国各地代理商开展工作，完成公司业务目标；
4、 直接参与、主持重要客户的业务技术交流、谈判及成交；
5、 督导代理商及老客户业务开展工作，落实本区域货款回收；
6、 控制所辖区域相互竞争、协调客户反馈信息及现场业主等问题。
任职要求：
1、专科以上学历；环境工程、给排水、电厂化学、化工工艺等相关专业；
2、1年以上销售工作经验；
3、了解、熟悉反渗透膜/纳滤膜/超滤膜等水处理系统设计者优先考虑；
4、善于掌握市场信息，具有敏锐的市场观察力、判断力；
5、能够独立组织协调工作，能够适应出差。
工作地址：
大兴区天华大街2号
**********
科氏(北京)滤膜科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.kochmembrane.cn/
公司地址：
大兴区庆祥南路29号
查看公司地图
**********
反渗透膜纳滤膜超滤膜销售主管
科氏(北京)滤膜科技有限公司
通讯补贴年底双薪绩效奖金年终分红交通补助带薪年假节日福利员工旅游
**********
福利:
通讯补贴
年底双薪
绩效奖金
年终分红
交通补助
带薪年假
节日福利
员工旅游
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：10人
职位类别：销售主管
**********
岗位职责：
1、 RO/NF/UF膜产品的市场开发与销售；
2、 制定本区域营销计划、分解销售目标；
3、 配合全国各地代理商开展工作，完成公司业务目标；
4、 直接参与、主持重要客户的业务技术交流、谈判及成交；
5、 督导代理商及老客户业务开展工作，落实本区域货款回收；
6、 控制所辖区域相互竞争、协调客户反馈信息及现场业主等问题。
任职要求：
1、环境工程、给排水、电厂化学、化工工艺等相关专业；
2、3年以上销售工作经验；专科以上学历；
3、了解、熟悉反渗透膜/纳滤膜/超滤膜等水处理系统设计者优先考虑；
4、善于掌握市场信息，具有敏锐的市场观察力、判断力；
5、能够独立组织协调工作，能够适应出差。
工作地址：
大兴区天华大街2号
**********
科氏(北京)滤膜科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.kochmembrane.cn/
公司地址：
大兴区庆祥南路29号
查看公司地图
**********
SEO网络优化专员
科氏(北京)滤膜科技有限公司
五险一金年底双薪绩效奖金交通补助通讯补贴全勤奖节日福利每年多次调薪
**********
福利:
五险一金
年底双薪
绩效奖金
交通补助
通讯补贴
全勤奖
节日福利
每年多次调薪
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：2人
职位类别：SEO/SEM
**********
岗位职责： 
1.熟悉百度、360等推广竞价规则，优化账户，提高产品曝光率，客户转化率。降低推广经费。
2、充分利用各种网络推广手段完成公司产品的销售及推广,例如百度相关产品、微博、BBS、SNS，论坛，社区等 
3、精通网络营销优化技术和部署技巧，熟悉网络营销手段和策略，提高网站流量和转化率； 
4、负责制定网站的SEO优化方案并带领团队实施； 
5、监控网站关键字，流量，竞争对手等数据并进行分析，有效提升网站权重和搜索引擎排名； 
任职条件： 
1、需要发散思维强，具有敏感、时尚信息嗅觉，擅长撰写时尚性、实效性、可读性，易转载的微博，博文。 
2、相关岗位两年以上工作经验，计算机相关专业大专及以上。

工作地址：
大兴区天华大街2号
**********
科氏(北京)滤膜科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.kochmembrane.cn/
公司地址：
大兴区庆祥南路29号
查看公司地图
**********
水处理化学品研发工程师
科氏(北京)滤膜科技有限公司
五险一金年底双薪绩效奖金交通补助餐补带薪年假每年多次调薪节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
交通补助
餐补
带薪年假
每年多次调薪
节日福利
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：2人
职位类别：水处理工程师
**********
工作职责： 
1、制定研发计划，设计研发路线，完成反渗透药剂、循环水药剂的小试、中试及研发过程； 
2、在公司领导的指导下完成各项研发任务； 
3、工作态度严谨，有研发精神和团队协作精神。 
职位要求： 
1、环境工程、有机化学、应用化学等专业，本科以上学历 
2、掌握有机合成的基本技术、熟悉有机化合物的结构分析； 
3、有较强的国内外文献查阅能力； 
4、有两年以上的工作经验。

工作地址：
大兴区天华大街2号
**********
科氏(北京)滤膜科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.kochmembrane.cn/
公司地址：
大兴区庆祥南路29号
查看公司地图
**********
反渗透膜纳滤膜超滤膜销售代表
科氏(北京)滤膜科技有限公司
通讯补贴年底双薪绩效奖金年终分红交通补助带薪年假节日福利员工旅游
**********
福利:
通讯补贴
年底双薪
绩效奖金
年终分红
交通补助
带薪年假
节日福利
员工旅游
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：10人
职位类别：销售代表
**********
岗位职责：
1、 RO/NF/UF膜产品的市场开发与销售；
2、 制定本区域营销计划、分解销售目标；
3、 配合全国各地代理商开展工作，完成公司业务目标；
4、 直接参与、主持重要客户的业务技术交流、谈判及成交；
5、 督导代理商及老客户业务开展工作，落实本区域货款回收；
6、 控制所辖区域相互竞争、协调客户反馈信息及现场业主等问题。
任职要求：
1、环境工程、给排水、电厂化学、化工工艺等相关专业；
2、1年以上销售工作经验；专科以上学历；
3、了解、熟悉反渗透膜/纳滤膜/超滤膜等水处理系统设计者优先考虑；
4、善于掌握市场信息，具有敏锐的市场观察力、判断力；
5、能够独立组织协调工作，能够适应出差。
工作地址：
大兴区天华大街2号
**********
科氏(北京)滤膜科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.kochmembrane.cn/
公司地址：
大兴区庆祥南路29号
查看公司地图
**********
反渗透膜纳滤膜超滤膜客户代表
科氏(北京)滤膜科技有限公司
通讯补贴年底双薪绩效奖金年终分红交通补助带薪年假节日福利员工旅游
**********
福利:
通讯补贴
年底双薪
绩效奖金
年终分红
交通补助
带薪年假
节日福利
员工旅游
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：10人
职位类别：客户代表
**********
岗位职责：
1、 RO/NF/UF膜产品的市场开发与销售；
2、 制定本区域营销计划、分解销售目标；
3、 配合全国各地代理商开展工作，完成公司业务目标；
4、 直接参与、主持重要客户的业务技术交流、谈判及成交；
5、 督导代理商及老客户业务开展工作，落实本区域货款回收；
6、 控制所辖区域相互竞争、协调客户反馈信息及现场业主等问题。
任职要求：
1、专科及以上学历，环境工程、给排水、电厂化学、化工工艺等相关专业；
2、1年以上销售工作经验；专科以上学历；
3、了解、熟悉反渗透膜/纳滤膜/超滤膜等水处理系统设计者优先考虑；
4、善于掌握市场信息，具有敏锐的市场观察力、判断力；
5、能够独立组织协调工作，能够适应出差。
工作地址：
大兴区天华大街2号
**********
科氏(北京)滤膜科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.kochmembrane.cn/
公司地址：
大兴区庆祥南路29号
查看公司地图
**********
反渗透膜纳滤膜超滤膜业务代表
科氏(北京)滤膜科技有限公司
通讯补贴年底双薪绩效奖金年终分红交通补助带薪年假节日福利员工旅游
**********
福利:
通讯补贴
年底双薪
绩效奖金
年终分红
交通补助
带薪年假
节日福利
员工旅游
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：10人
职位类别：业务拓展专员/助理
**********
岗位职责：
1、 RO/NF/UF膜产品的市场开发与销售；
2、 制定本区域营销计划、分解销售目标；
3、 配合全国各地代理商开展工作，完成公司业务目标；
4、 直接参与、主持重要客户的业务技术交流、谈判及成交；
5、 督导代理商及老客户业务开展工作，落实本区域货款回收；
6、 控制所辖区域相互竞争、协调客户反馈信息及现场业主等问题。
任职要求：
1、大专以上学历，环境工程、给排水、电厂化学、化工工艺等相关专业；
2、1年以上销售工作经验；专科以上学历；
3、了解、熟悉反渗透膜/纳滤膜/超滤膜等水处理系统设计者优先考虑；
4、善于掌握市场信息，具有敏锐的市场观察力、判断力；
5、能够独立组织协调工作，能够适应出差。
工作地址：
大兴区天华大街2号
**********
科氏(北京)滤膜科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.kochmembrane.cn/
公司地址：
大兴区庆祥南路29号
查看公司地图
**********
纯水技术工程师
科氏(北京)滤膜科技有限公司
年底双薪交通补助餐补通讯补贴加班补助年终分红绩效奖金每年多次调薪
**********
福利:
年底双薪
交通补助
餐补
通讯补贴
加班补助
年终分红
绩效奖金
每年多次调薪
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：2人
职位类别：水处理工程师
**********
职位描述：
1．能独立完成脱盐水（膜法处理）系统的方案设计；完成水处理工程的初步设计和施工图设计；
2．能够独立的跟进项目；
3．能够作为项目技术负责人独立完成工程的项目设计备案、施工图纸设计、工艺调试等工作；
4．能够在最小的指导条件下合理地分配工作量和工作流程；
5．了解其他相关专业。
6．熟悉反渗透膜，纳滤膜，超滤膜，水处理专用阻垢剂，清洗剂，杀菌剂，絮凝剂
任职条件
1．给水排水或环境工程专业、本科以上；
2．2年以上膜法处理或给水处理工程设计经验（有设计院或工程公司经验者优先）；
3．能熟练操作AUTOCAD、可独立编制技术文件及工程施工图纸设计；
4．能够独立安装调试系统者优先。

工作地址：
大兴区天华大街2号
**********
科氏(北京)滤膜科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.kochmembrane.cn/
公司地址：
大兴区庆祥南路29号
查看公司地图
**********
水处理药剂销售代表
科氏(北京)滤膜科技有限公司
通讯补贴年底双薪绩效奖金年终分红交通补助带薪年假节日福利员工旅游
**********
福利:
通讯补贴
年底双薪
绩效奖金
年终分红
交通补助
带薪年假
节日福利
员工旅游
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：10人
职位类别：销售代表
**********
岗位职责：
1、 反渗透药剂及循环水药剂的市场开发与销售
2、 制定本区域营销计划、分解销售目标
3、 配合全国各地代理商开展工作，完成公司业务目标
4、 直接参与、主持重要客户的业务技术交流、谈判及成交
5、 督导代理商及老客户业务开展工作，落实本区域货款回收
6、 控制所辖区域相互竞争、协调客户反馈信息及现场业主等问题
任职要求：
1、环境工程、给排水、电厂化学、化工工艺等相关专业；
2、1-3年以上销售工作经验；专科以上学历，
3、了解、熟悉反渗透膜/纳滤膜/超滤膜等水处理系统设计者优先考虑；
4、善于掌握市场信息，具有敏锐的市场观察力、判断力；
5、能够独立组织协调工作，能够适应出差。
工作地址：
大兴区天华大街2号
**********
科氏(北京)滤膜科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.kochmembrane.cn/
公司地址：
大兴区庆祥南路29号
查看公司地图
**********
水处理药剂业务代表
科氏(北京)滤膜科技有限公司
通讯补贴年底双薪绩效奖金年终分红交通补助带薪年假节日福利员工旅游
**********
福利:
通讯补贴
年底双薪
绩效奖金
年终分红
交通补助
带薪年假
节日福利
员工旅游
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：10人
职位类别：业务拓展专员/助理
**********
岗位职责：
1、 反渗透药剂及循环水药剂的市场开发与销售
2、 制定本区域营销计划、分解销售目标
3、 配合全国各地代理商开展工作，完成公司业务目标
4、 直接参与、主持重要客户的业务技术交流、谈判及成交
5、 督导代理商及老客户业务开展工作，落实本区域货款回收
6、 控制所辖区域相互竞争、协调客户反馈信息及现场业主等问题
任职要求：
1、环境工程、给排水、电厂化学、化工工艺等相关专业；
2、专科以上学历，1年以上销售工作经验；
3、了解、熟悉反渗透膜/纳滤膜/超滤膜等水处理系统设计者优先考虑；
4、善于掌握市场信息，具有敏锐的市场观察力、判断力；
5、能够独立组织协调工作，能够适应出差。
工作地址：
大兴区天华大街2号
**********
科氏(北京)滤膜科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.kochmembrane.cn/
公司地址：
大兴区庆祥南路29号
查看公司地图
**********
水处理药剂客户代表
科氏(北京)滤膜科技有限公司
通讯补贴年底双薪绩效奖金年终分红交通补助带薪年假节日福利员工旅游
**********
福利:
通讯补贴
年底双薪
绩效奖金
年终分红
交通补助
带薪年假
节日福利
员工旅游
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：10人
职位类别：客户代表
**********
岗位职责：
1、 反渗透药剂及循环水药剂的市场开发与销售
2、 制定本区域营销计划、分解销售目标
3、 配合全国各地代理商开展工作，完成公司业务目标
4、 直接参与、主持重要客户的业务技术交流、谈判及成交
5、 督导代理商及老客户业务开展工作，落实本区域货款回收
6、 控制所辖区域相互竞争、协调客户反馈信息及现场业主等问题
任职要求：
1、环境工程、给排水、电厂化学、化工工艺等相关专业；
2、1年以上销售工作经验；
3、专科以上学历，
4、了解、熟悉反渗透膜/纳滤膜/超滤膜等水处理系统设计者优先考虑；
5、善于掌握市场信息，具有敏锐的市场观察力、判断力；
6、能够独立组织协调工作，能够适应出差。
工作地址：
大兴区天华大街2号
**********
科氏(北京)滤膜科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.kochmembrane.cn/
公司地址：
大兴区庆祥南路29号
查看公司地图
**********
水处理药剂业务主管
科氏(北京)滤膜科技有限公司
通讯补贴年底双薪绩效奖金年终分红交通补助带薪年假节日福利员工旅游
**********
福利:
通讯补贴
年底双薪
绩效奖金
年终分红
交通补助
带薪年假
节日福利
员工旅游
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：10人
职位类别：业务拓展经理/主管
**********
岗位职责：
1、 反渗透药剂及循环水药剂的市场开发与销售
2、 制定本区域营销计划、分解销售目标
3、 配合全国各地代理商开展工作，完成公司业务目标
4、 直接参与、主持重要客户的业务技术交流、谈判及成交
5、 督导代理商及老客户业务开展工作，落实本区域货款回收
6、 控制所辖区域相互竞争、协调客户反馈信息及现场业主等问题。
任职要求：
1、专科以上学历；环境工程、给排水、电厂化学、化工工艺等相关专业；
2、1年以上销售工作经验。
3、了解、熟悉反渗透膜/纳滤膜/超滤膜等水处理系统设计者优先考虑；
4、善于掌握市场信息，具有敏锐的市场观察力、判断力；
5、能够独立组织协调工作，能够适应出差。
工作地址：
大兴区天华大街2号
**********
科氏(北京)滤膜科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.kochmembrane.cn/
公司地址：
大兴区庆祥南路29号
查看公司地图
**********
水处理药剂大客户销售
科氏(北京)滤膜科技有限公司
通讯补贴年底双薪绩效奖金年终分红交通补助带薪年假节日福利员工旅游
**********
福利:
通讯补贴
年底双薪
绩效奖金
年终分红
交通补助
带薪年假
节日福利
员工旅游
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：10人
职位类别：大客户销售代表
**********
岗位职责：
1、 反渗透药剂及循环水药剂的市场开发与销售。
2、 制定本区域营销计划、分解销售目标
3、 配合全国各地代理商开展工作，完成公司业务目标
4、 直接参与、主持重要客户的业务技术交流、谈判及成交
5、 督导代理商及老客户业务开展工作，落实本区域货款回收
6、 控制所辖区域相互竞争、协调客户反馈信息及现场业主等问题
任职要求：
1、环境工程、给排水、电厂化学、化工工艺等相关专业；
2、1年以上销售工作经验；专科以上学历，
3、了解、熟悉反渗透膜/纳滤膜/超滤膜等水处理系统设计者优先考虑；
4、善于掌握市场信息，具有敏锐的市场观察力、判断力；
5、能够独立组织协调工作，能够适应出差。
工作地址：
大兴区天华大街2号
**********
科氏(北京)滤膜科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.kochmembrane.cn/
公司地址：
大兴区庆祥南路29号
查看公司地图
**********
水处理药剂业务总监
科氏(北京)滤膜科技有限公司
通讯补贴年底双薪绩效奖金年终分红交通补助带薪年假节日福利员工旅游
**********
福利:
通讯补贴
年底双薪
绩效奖金
年终分红
交通补助
带薪年假
节日福利
员工旅游
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：10人
职位类别：业务拓展经理/主管
**********
岗位职责：
1、 反渗透药剂及循环水药剂的市场开发与销售
2、 制定本区域营销计划、分解销售目标
3、 配合全国各地代理商开展工作，完成公司业务目标
4、 直接参与、主持重要客户的业务技术交流、谈判及成交
5、 督导代理商及老客户业务开展工作，落实本区域货款回收。
6、 控制所辖区域相互竞争、协调客户反馈信息及现场业主等问题
任职要求：
1、环境工程、给排水、电厂化学、化工工艺等相关专业；
2、1年以上销售工作经验；专科以上学历；
3、了解、熟悉反渗透膜/纳滤膜/超滤膜等水处理系统设计者优先考虑；
4、善于掌握市场信息，具有敏锐的市场观察力、判断力；
5、能够独立组织协调工作，能够适应出差。
工作地址：
大兴区天华大街2号
**********
科氏(北京)滤膜科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.kochmembrane.cn/
公司地址：
大兴区庆祥南路29号
查看公司地图
**********
销售工程师
上海爱启环境技术工程有限公司
五险一金绩效奖金交通补助通讯补贴弹性工作员工旅游
**********
福利:
五险一金
绩效奖金
交通补助
通讯补贴
弹性工作
员工旅游
**********
职位月薪：8001-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：3人
职位类别：销售工程师
**********
薪资面议
岗位职责：
1、 结合公司发展战略，负责所辖区域市场的统筹规划，渠道开发、拓展和关系维护；
2、 负责设计院的开发维护工作；
3、 负责公司产品的讲解、演示与项目方案制定、协调；
4、 负责区域管辖客户相关项目的管理、跟进与促成，定期做项目进度汇总；
5、 负责收集并及时、有效地解决客户的问题，协调所辖区域客户与公司间的良好合作关系；
6、 负责所辖区域销售团队的管理，对销售指标负责；
7、 负责所辖区域销售合同的管理和过程控制，能够有效把控销售各环节，对项目整体负责；
8、 负责商务谈判和投标相关工作，统筹项目的实施、回款及项目订单安装、验收等各环节；
9、 负责与公司职能部门的协调沟通，推进项目进展及执行；
10、配合公司业务/产品的推广工作，并完成公司安排的其他相关工作。
任职要求：
1、 大专及以上学历（（暖通/热能专业毕业生优先）；
2、 30岁以下、1年以上相关工作经验（有销售或市场相关从业经验者优先）；
3、 熟练掌握office、 CAD等办公软件；
4、 性格外向、积极乐观，亲和力强，具备很强的市场敏锐度、优秀的沟通能力和职业素养；
5、 能独挡一面，具备很强的抗压能力、创新能力和团队合作精神。

工作地址：
北京市通州区新华西街58号万达广场C座
**********
上海爱启环境技术工程有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
环保
公司主页：
http://www.aiqiworld.com/
公司地址：
上海市浦东新区民生路1518号金鹰大厦B栋1601
**********
水处理药剂大区经理
科氏(北京)滤膜科技有限公司
通讯补贴年底双薪绩效奖金年终分红交通补助带薪年假节日福利员工旅游
**********
福利:
通讯补贴
年底双薪
绩效奖金
年终分红
交通补助
带薪年假
节日福利
员工旅游
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：10人
职位类别：区域销售经理/主管
**********
岗位职责：
1、 反渗透药剂及循环水药剂的市场开发与销售。
2、 制定本区域营销计划、分解销售目标。
3、 配合全国各地代理商开展工作，完成公司业务目标；
4、 直接参与、主持重要客户的业务技术交流、谈判及成交。
5、 督导代理商及老客户业务开展工作，落实本区域货款回收。
6、 控制所辖区域相互竞争、协调客户反馈信息及现场业主等问题。
任职要求：
1、环境工程、给排水、电厂化学、化工工艺等相关专业。
2、1年以上销售工作经验；
3、专科以上学历；
4、了解、熟悉反渗透膜/纳滤膜/超滤膜等水处理系统设计者优先考虑。
5、善于掌握市场信息，具有敏锐的市场观察力、判断力；
6、能够独立组织协调工作，能够适应出差。
工作地址：
大兴区天华大街2号
**********
科氏(北京)滤膜科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.kochmembrane.cn/
公司地址：
大兴区庆祥南路29号
查看公司地图
**********
水处理药剂渠道经理
科氏(北京)滤膜科技有限公司
通讯补贴年底双薪绩效奖金年终分红交通补助带薪年假节日福利员工旅游
**********
福利:
通讯补贴
年底双薪
绩效奖金
年终分红
交通补助
带薪年假
节日福利
员工旅游
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：10人
职位类别：销售经理
**********
岗位职责：
1、 反渗透药剂及循环水药剂的市场开发与销售。
2、 制定本区域营销计划、分解销售目标。
3、 配合全国各地代理商开展工作，完成公司业务目标。
4、 直接参与、主持重要客户的业务技术交流、谈判及成交。
5、 督导代理商及老客户业务开展工作，落实本区域货款回收。
6、 控制所辖区域相互竞争、协调客户反馈信息及现场业主等问题。
任职要求：
1、专科以上学历；环境工程、给排水、电厂化学、化工工艺等相关专业。
2、1年以上销售工作经验；
3、了解、熟悉反渗透膜/纳滤膜/超滤膜等水处理系统设计者优先考虑。
4、善于掌握市场信息，具有敏锐的市场观察力、判断力。
5、能够独立组织协调工作，能够适应出差。
工作地址：
大兴区天华大街2号
**********
科氏(北京)滤膜科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.kochmembrane.cn/
公司地址：
大兴区庆祥南路29号
查看公司地图
**********
水处理药剂渠道主管
科氏(北京)滤膜科技有限公司
通讯补贴年底双薪绩效奖金年终分红交通补助带薪年假节日福利员工旅游
**********
福利:
通讯补贴
年底双薪
绩效奖金
年终分红
交通补助
带薪年假
节日福利
员工旅游
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：10人
职位类别：销售主管
**********
岗位职责：
1、 反渗透药剂及循环水药剂的市场开发与销售。
2、 制定本区域营销计划、分解销售目标。
3、 配合全国各地代理商开展工作，完成公司业务目标。
4、 直接参与、主持重要客户的业务技术交流、谈判及成交。
5、 督导代理商及老客户业务开展工作，落实本区域货款回收。
6、 控制所辖区域相互竞争、协调客户反馈信息及现场业主等问题。
任职要求：
1、环境工程、给排水、电厂化学、化工工艺等相关专业；专科以上学历。
2、1年以上销售工作经验；
3、了解、熟悉反渗透膜/纳滤膜/超滤膜等水处理系统设计者优先考虑。
4、善于掌握市场信息，具有敏锐的市场观察力、判断力。
5、能够独立组织协调工作，能够适应出差。
工作地址：
大兴区天华大街2号
**********
科氏(北京)滤膜科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.kochmembrane.cn/
公司地址：
大兴区庆祥南路29号
查看公司地图
**********
水处理药剂片区经理
科氏(北京)滤膜科技有限公司
通讯补贴年底双薪绩效奖金年终分红交通补助带薪年假节日福利员工旅游
**********
福利:
通讯补贴
年底双薪
绩效奖金
年终分红
交通补助
带薪年假
节日福利
员工旅游
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：10人
职位类别：区域销售经理/主管
**********
岗位职责：
1、 反渗透药剂及循环水药剂的市场开发与销售
2、 制定本区域营销计划、分解销售目标
3、 配合全国各地代理商开展工作，完成公司业务目标。
4、 直接参与、主持重要客户的业务技术交流、谈判及成交。
5、 督导代理商及老客户业务开展工作，落实本区域货款回收。
6、 控制所辖区域相互竞争、协调客户反馈信息及现场业主等问题。
任职要求：
1、环境工程、给排水、电厂化学、化工工艺等相关专业。
2、1年以上销售工作经验；专科以上学历。
3、了解、熟悉反渗透膜/纳滤膜/超滤膜等水处理系统设计者优先考虑。
4、善于掌握市场信息，具有敏锐的市场观察力、判断力。
5、能够独立组织协调工作，能够适应出差。
工作地址：
大兴区天华大街2号
**********
科氏(北京)滤膜科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.kochmembrane.cn/
公司地址：
大兴区庆祥南路29号
查看公司地图
**********
水处理化学品---研发工程师
科氏(北京)滤膜科技有限公司
通讯补贴年底双薪绩效奖金年终分红交通补助带薪年假节日福利员工旅游
**********
福利:
通讯补贴
年底双薪
绩效奖金
年终分红
交通补助
带薪年假
节日福利
员工旅游
**********
职位月薪：6000-12000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：2人
职位类别：水处理工程师
**********
工作职责： 
1、制定研发计划，设计研发路线，完成反渗透药剂、循环水药剂的小试、中试及研发过程。
2、在公司领导的指导下完成各项研发任务。
3、工作态度严谨，有研发精神和团队协作精神。 
职位要求： 
1、环境工程、有机化学、应用化学等专业，本科以上学历。
2、掌握有机合成的基本技术、熟悉有机化合物的结构分析。
3、有较强的国内外文献查阅能力。
4、有2年以上的工作经验。
工作地址：
大兴区天华大街2号
**********
科氏(北京)滤膜科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.kochmembrane.cn/
公司地址：
大兴区庆祥南路29号
查看公司地图
**********
水处理药剂渠道总监
科氏(北京)滤膜科技有限公司
通讯补贴年底双薪绩效奖金年终分红交通补助带薪年假节日福利员工旅游
**********
福利:
通讯补贴
年底双薪
绩效奖金
年终分红
交通补助
带薪年假
节日福利
员工旅游
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：10人
职位类别：渠道/分销总监
**********
岗位职责：
1、 反渗透药剂及循环水药剂的市场开发与销售。
2、 制定本区域营销计划、分解销售目标。
3、 配合全国各地代理商开展工作，完成公司业务目标。
4、 直接参与、主持重要客户的业务技术交流、谈判及成交。
5、 督导代理商及老客户业务开展工作，落实本区域货款回收。
6、 控制所辖区域相互竞争、协调客户反馈信息及现场业主等问题。
任职要求：
1、专科以上学历；环境工程、给排水、电厂化学、化工工艺等相关专业；
2、1-3年以上销售工作经验；
3、了解、熟悉反渗透膜/纳滤膜/超滤膜等水处理系统设计者优先考虑；
4、善于掌握市场信息，具有敏锐的市场观察力、判断力；
5、能够独立组织协调工作，能够适应出差。
工作地址：
大兴区天华大街2号
**********
科氏(北京)滤膜科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.kochmembrane.cn/
公司地址：
大兴区庆祥南路29号
查看公司地图
**********
人事行政专员
科氏(北京)滤膜科技有限公司
加班补助每年多次调薪节日福利五险一金
**********
福利:
加班补助
每年多次调薪
节日福利
五险一金
**********
职位月薪：3000-6000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：2人
职位类别：人力资源专员/助理
**********
岗位职责：
1、协助上级建立健全公司招聘、培训、绩效考核等人力资源制度建设；
2、有良好的招聘渠道，独立完成招聘工作；
3、收集相关的劳动用工等人事政策及法规；建立、维护人事档案，办理和更新劳动合同；
4、制定培训计划，开展新老员工培训，联系组织外部培训以及培训效果的跟踪、反馈；
5、负责员工工资结算和年度工资总额申报，办理相应的社会保险等；
6、接待公司来访人员；
7、其他行政辅助工作和公司安排的其他工作。
 任职要求：
1、人力资源或相关专业大专以上学历；
2、一年以上人力资源工作经验，熟悉各种招聘渠道和培训技巧；
3、熟悉人力资源管理各项实务的操作流程，熟悉国家各项劳动人事法规政策，并能实际操作运用；
4、具有良好的职业道德，踏实稳重，工作细心，责任心强，有较强的沟通、协调能力，有团队协作精神；
5、熟练使用相关办公软件。
6、善于沟通、亲和力强、谈吐优雅。

工作地址：
大兴区天华大街2号
查看职位地图
**********
科氏(北京)滤膜科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.kochmembrane.cn/
公司地址：
大兴区庆祥南路29号
**********
技术工程师
盛旦节能技术(北京)有限公司
五险一金加班补助全勤奖餐补带薪年假节日福利通讯补贴交通补助
**********
福利:
五险一金
加班补助
全勤奖
餐补
带薪年假
节日福利
通讯补贴
交通补助
**********
职位月薪：6001-8000元/月 
工作地点：北京-丰台区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：不限
招聘人数：2人
职位类别：土木/土建/结构工程师
**********
岗位职责：

1、负责公司日光照明产品的使用方案规划和深化图纸设计；
2、及时准确地完成项目深化设计方案，必要时对项目进行实地勘测，进行成本控制及施工中的可行性协调；
3、管理、收集公司产品技术资料及档案管理；
4、协助研发人员进行产品升级设计；
5、参与项目投标技术文件制作；
6、协助进行公司专利技术资料整理；


任职要求：
1. 大专及以上学历，建筑设计、土木工程、室内设计等相关专业2年以上设计工作经验；
2、熟悉各种建筑图纸、水电气图纸，有建筑设计、施工图设计、照明相关行业经验者优先；
3. 善于客户沟通，具有较强的图纸和方案设计能力，具备较强的文字功底；
4、熟练使用常用建筑设计软件及办公软件，如 CAD、天正、photoshop、dialux、word、excel等软件。
5、自律性强，工作认真踏实，吃苦耐劳，有良好的团队合作意识。
6、有良好的沟通表达能力，普通话标准；
7、年龄不限，性别不限。

我公司为国家高新技术企业，符合条件的可以办理北京市工作居住证。

工作地址：
北京市丰台区南三环东路金城中心6层
查看职位地图
**********
盛旦节能技术(北京)有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司主页：
http://www.sundome.com.cn
公司地址：
北京市丰台区南三环东路金城中心601
**********
百度推广专员
科氏(北京)滤膜科技有限公司
五险一金年底双薪绩效奖金交通补助带薪年假加班补助节日福利通讯补贴
**********
福利:
五险一金
年底双薪
绩效奖金
交通补助
带薪年假
加班补助
节日福利
通讯补贴
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：2人
职位类别：SEO/SEM
**********
岗位职责：
1.熟悉百度、360等推广竞价规则，优化账户，提高产品曝光率，客户转化率。降低推广经费。
2、充分利用各种网络推广手段完成公司产品的销售及推广,例如百度相关产品、微博、BBS、SNS，论坛，社区等
3、精通网络营销优化技术和部署技巧，熟悉网络营销手段和策略，提高网站流量和转化率；
4、负责制定网站的SEO优化方案并带领团队实施；
5、监控网站关键字，流量，竞争对手等数据并进行分析，有效提升网站权重和搜索引擎排名；
任职条件：
1、需要发散思维强，具有敏感、时尚信息嗅觉，擅长撰写时尚性、实效性、可读性，易转载的微博，博文。
2、相关岗位两年以上工作经验，计算机相关专业大专及以上。

工作地址：
大兴区天华大街2号
查看职位地图
**********
科氏(北京)滤膜科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.kochmembrane.cn/
公司地址：
大兴区庆祥南路29号
**********
业务经理
北京豪格科技发展有限公司
每年多次调薪五险一金绩效奖金加班补助节日福利带薪年假
**********
福利:
每年多次调薪
五险一金
绩效奖金
加班补助
节日福利
带薪年假
**********
职位月薪：6000-12000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：销售代表
**********
1.负责北京及华北地区销售及相关业务
2.吃苦耐劳，有责任感
3.有销售经验优先考虑
4.有净水行业经验优先考虑
5.有一定的管理经

工作地址：
大兴区
查看职位地图
**********
北京豪格科技发展有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
耐用消费品（服饰/纺织/皮革/家具/家电）
公司地址：
南山科技园北区松坪山路5号嘉达研发大楼A栋6层
**********
设计院推广
盛旦节能技术(北京)有限公司
绩效奖金餐补带薪年假五险一金节日福利年终分红加班补助交通补助
**********
福利:
绩效奖金
餐补
带薪年假
五险一金
节日福利
年终分红
加班补助
交通补助
**********
职位月薪：6001-8000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：3人
职位类别：市场营销专员/助理
**********
职位描述:

1、负责工程项目信息筛选（公司既有项目信息），完成既定的项目上图或销售任务；
2、负责建立设计院资源网络，开拓、维持客户渠道，开发新客户；
3、维护企业形象，与设计院建立良好关系以促进销售；
4、与销售人员进行项目协作；
5、负责设计院技术交流会相关工作；
6、公司交予的其他工作。

任职资格：

1、大专以上学历，销售、市场营销、网络营销等相关专业优先。；
2、具备良好的沟通协调及组织能力，有较强的工作主动性和良好的团队协作精神；
3、具备良好的个人品格与职业素养，有较强的责任心；
4、形象端庄大方，举止得体；
5、有相关设计院维护经验及工建项目工作经验者优先；
6、熟悉北京设计院分布，吃苦耐劳。
工作地址：
北京市丰台区南三环东路金城中心601
查看职位地图
**********
盛旦节能技术(北京)有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司主页：
http://www.sundome.com.cn
公司地址：
北京市丰台区南三环东路金城中心601
**********
涂料技术销售工程师 高工资提成奖金福利
北京志盛威华化工有限公司
五险一金绩效奖金交通补助餐补通讯补贴带薪年假定期体检节日福利
**********
福利:
五险一金
绩效奖金
交通补助
餐补
通讯补贴
带薪年假
定期体检
节日福利
**********
职位月薪：10000-20000元/月 
工作地点：北京-丰台区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：5人
职位类别：网络/在线销售
**********
岗位描述：
1、能独立处理和解决销售过程中所遇到各种事情，并有解决困难途径办法；
2、开发客户资源，寻找潜在客户，独立的完成销售，并完成销售目标；
 3、签定销售合同，指导、协调、审核与销售服务有关的帐目和记录，协调运输等事务。
职位要求：
1、专科以上学历，化工、材料、工程类专业毕业，在工程或是涂料行业工作2年以上，有一定的工作经验，特别是对涂料及工程、材料有一定的了解；
2、熟悉了解化工材料常识、工业工况常识、节能知识常识；
3、较好的思维逻辑、语言表达、口齿伶俐及善于沟通的能力；
4、对待事物有很好的亲和力和理解能力，执行力好；
5、熟悉办公软件的操作和使用，英语达到四级以上；
6、具有吃苦耐劳、敬业精神、高度责任精神；
7、有很好的团队合作意识，为人正直真诚，敢于承担责任，完成一定销售指标；
8、长期居住在北京。
办公地址:北京市通州马驹桥联东U谷西二区108。 
联系电话：56370551
网址：
www.zswh.com.cn
符合以上条件者请将简历发送至邮箱zswhuazhaopin@163.com。

工作地址：
北京通州区马驹桥联东U谷西二区108
查看职位地图
**********
北京志盛威华化工有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
石油/石化/化工
公司主页：
http://www.zswh.com.cn/products/p3/29.html
公司地址：
北京市丰台区东铁营横一条路金泰彤翔大厦502-6#
**********
急聘人事专员+实习生+包住+高福利
唐山勤领商贸有限公司北京分公司
五险一金年底双薪包住采暖补贴带薪年假员工旅游高温补贴节日福利
**********
福利:
五险一金
年底双薪
包住
采暖补贴
带薪年假
员工旅游
高温补贴
节日福利
**********
职位月薪：3500-7000元/月 
工作地点：北京-朝阳区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：2人
职位类别：人力资源专员/助理
**********
本公司郑重承诺：所有岗位入职不收取任何费用，住宿不收取任何费用，公司免费提供岗位技能培训，敬请求职者周知。

一、任职要求：
1、女，形象好，气质佳，善于与人交流，年龄在18--27周岁；
2、有相关工作经验，文秘、行政人事管理等相关专业优先考虑；
3、熟悉公文写作格式，熟练运用OFFICE等办公软件；
4、工作仔细认真、责任心强、为人正直；
5、有热情，亲和力强，工作能动性强，认真负责任。 

二、岗位职责：
1、文件整理、打印，报表的收编以及整理；
2、维护招聘渠道，组织、安排面试；
3、办理相关手续（报到，转正，调动，离职）；
4、协助保洁员完成公共办公区、会议室环境的日常维护工作，确保办公区的整洁有序；
5、完成部门经理交代的其它工作；
6、人事相关工作。

三、公司福利
1、免费包食宿，宿舍干净整洁，配套设施齐全，拥有独立的厨房、卫生间、客厅，宿舍距离公司公交就两站地
2、周末单休，国家法定节假日休息（按照国家规定正常放假），休息期间公司人事部会组织多种业余活动；
3、年终大奖，定期聚餐，员工生日，节日礼物，外出旅游；
4、宿舍干净整洁，配套设施齐全。

四、晋升渠道：
行政文员-行政主管--人事助理--人事主管--人事经理

公司地址：北京市朝阳区大望路SOHO现代城A座3005 
乘车路线：地铁1号线14号线大望路站B口出。
面试时间：下午1:30一4:30
联系人事部：010一56172221

工作地址：
唐山勤领商贸有限公司北京分公司
**********
唐山勤领商贸有限公司北京分公司
公司规模：
1000-9999人
公司性质：
股份制企业
公司行业：
环保
公司地址：
唐山勤领商贸有限公司北京分公司
查看公司地图
**********
行政兼出纳
北京中环合创环保科技有限公司
创业公司年终分红餐补带薪年假员工旅游补充医疗保险五险一金
**********
福利:
创业公司
年终分红
餐补
带薪年假
员工旅游
补充医疗保险
五险一金
**********
职位月薪：4001-6000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：中专
招聘人数：1人
职位类别：行政专员/助理
**********
岗位职责：
1、接转电话，接待来访客人, 处理快递单据和统计结算；
3、办公用品与杂物的采购、维护和管理，统计行政费用的使用情况；
3、协助上级主管维护日常办公秩序和办公环境；
4、负责日常收支的管理和核对,办公室基本账务的核对；
5、负责收集和审核原始凭证，保证报销手续及原始单据的合法性、准确性；
6、协助行政部经理完成公司行政事务工作及部门内部日常事务工作
7、协助经理进行内务、安全管理，为其他部门提供及时有效的行政服务
8、每月考勤统计及整理汇报财务。
9、工商、银行、税务相关事项的办理。
10、上级交办的其他临时性工作。
 任职资格：
1、20-35岁，女，形象气质较好；
2、秘书、人力资源、中文、财务、行政、工商管理等专业，1年以上人事行政类相关工作经验；应届毕业生也可接受
3、忠诚敬业、勤劳主动、细致认真、善于沟通，服务意识强，能在压力下工作；
4、具备一定的公文处理能力；
5、熟练使用office办公软件，具备基本的网络知识。

工作地址：
海淀区中关村环保科技园区
**********
北京中环合创环保科技有限公司
公司规模：
20人以下
公司性质：
保密
公司行业：
环保
公司地址：
海淀区紫雀路33号院3号楼3301
**********
储备干部（保温产品设计类）
北京中集精新相能科技有限公司
五险一金绩效奖金包住餐补通讯补贴带薪年假节日福利
**********
福利:
五险一金
绩效奖金
包住
餐补
通讯补贴
带薪年假
节日福利
**********
职位月薪：4000-7000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：4人
职位类别：储备干部
**********
岗位职责：
1、参与设计与优化新型蓄热节能设备与产品；
2、装备样品的开发与制作；
3、验证实验的实施；
4、参与编写相关设计文档，协助完成产品申报；
5、对同类产品进行分析，与相关部门沟通反馈产品存在的问题，解决产品故障，做好产品改进。
任职要求：
1、本科及以上学历，暖通、环境工程、工业设计、机电一体化、环境工程等相关专业；
2、2年以上相关岗位工作经验，会使用CAD或其他三维制图软件；
3、动手能力强，逻辑思维清晰，有上进心；
4、优良的职业操守，
5、2015-2017毕业生。
工作地点：河北燕郊天山国际产业园       可提供住宿
工作地址：
燕郊经济技术开发区化大街151号天山国际39号
**********
北京中集精新相能科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
环保
公司主页：
www.finepe.com
公司地址：
燕郊经济技术开发区京榆大街580号
**********
传感器销售人员
北京东方联优技术开发有限公司
五险一金绩效奖金全勤奖包吃带薪年假定期体检节日福利
**********
福利:
五险一金
绩效奖金
全勤奖
包吃
带薪年假
定期体检
节日福利
**********
职位月薪：3500-5000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：5人
职位类别：销售工程师
**********
工作职责
1、在全国规定的省地范围内开展产品的销售工作；
2、开拓市场、寻找客户资料，掌握市场的需求动态和竞争对手信息；
3、负责向用户提供技术和产品交流和培训；
4、负责与客户的良好沟通及接待、服务；
5、按批准的价格谈判，与客户签订销售合同；
6、完成公司制定的销售计划、工作目标；
  
任职要求
1、大专以上学历，年龄22岁以上，性别不限（欢迎应届生联系）；
2、营销、电气工程专业、化工专业或具有相关工作经验者优先；
3、有良好的沟通能力、逻辑判断能力和灵活处理事情的能力；
4、性格开朗，有敬业和团队精神，乐于学习、敢于创新，追求卓越，敢于接受挑战。

工作地址：
北京市朝阳区北苑路傲城融富中心B座2704
**********
北京东方联优技术开发有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
仪器仪表及工业自动化
公司主页：
www.euro-link.com.cn
公司地址：
北京市朝阳区北苑路奥运媒体村傲城融富中心B座2704室
查看公司地图
**********
仪器仪表销售工程师
北京东方联优技术开发有限公司
五险一金绩效奖金全勤奖包吃交通补助通讯补贴带薪年假定期体检
**********
福利:
五险一金
绩效奖金
全勤奖
包吃
交通补助
通讯补贴
带薪年假
定期体检
**********
职位月薪：4000-8000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：3人
职位类别：销售代表
**********
工作职责
1、  在全国规定的省地范围内开展公司产品的销售工作
2、  系统整合客户资源，建立渠道销售网络，全面负责产品的推广与销售
3、  负责向用户提供技术和产品交流、培训以及安装、调试等服务
4、  协助代理商准备投标文件，按批准的价格谈判和销售

任职要求
1、  有渠道管理经验，有开发市场的能力
2、  有良好的沟通能力、逻辑判断能力和灵活处理事情的能力
3、  有志在仪器仪表行业长期发展，能以良好的心态面对挫折和压力
4、  机电、电气工程、化工、自动化等专业大专以上学历优先考虑
5、  能适应经常出差
6、  工作地点：北京
7、  待遇：面议
工作地址：
北京市朝阳区北苑路奥运村傲城融富中心B座2704室
**********
北京东方联优技术开发有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
仪器仪表及工业自动化
公司主页：
www.euro-link.com.cn
公司地址：
北京市朝阳区北苑路奥运媒体村傲城融富中心B座2704室
查看公司地图
**********
传感器销售工程师
北京东方联优技术开发有限公司
五险一金绩效奖金全勤奖包吃带薪年假定期体检节日福利
**********
福利:
五险一金
绩效奖金
全勤奖
包吃
带薪年假
定期体检
节日福利
**********
职位月薪：3000-6000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：4人
职位类别：销售代表
**********
岗位职责：
1、在全国规定的省地范围内开展产品的销售工作；
2、开拓市场、寻找客户资料，掌握市场的需求动态和竞争对手信息；
3、负责向用户提供技术和产品交流和培训；
4、负责与客户的良好沟通及接待、服务；
5、按批准的价格谈判，与客户签订销售合同；
6、完成公司制定的销售计划、工作目标；

任职要求：
1、大专以上学历，年龄22岁以上，性别不限（欢迎应届生联系）；
2、营销、电气工程专业、化工专业或具有相关工作经验者优先；
3、有良好的沟通能力、逻辑判断能力和灵活处理事情的能力；
4、性格开朗，有敬业和团队精神，乐于学习、敢于创新，追求卓越，敢于接受挑战。

工作地址：
北京市朝阳区北苑路奥运媒体村傲城融富中心B座2704室
**********
北京东方联优技术开发有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
仪器仪表及工业自动化
公司主页：
www.euro-link.com.cn
公司地址：
北京市朝阳区北苑路奥运媒体村傲城融富中心B座2704室
查看公司地图
**********
资料员
北京首建环保有限责任公司
五险一金绩效奖金交通补助通讯补贴采暖补贴定期体检高温补贴节日福利
**********
福利:
五险一金
绩效奖金
交通补助
通讯补贴
采暖补贴
定期体检
高温补贴
节日福利
**********
职位月薪：4500-8000元/月 
工作地点：北京-朝阳区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：工程资料管理
**********
岗位职责：
1） 负责工程项目由开工至竣工的档案收集、编制、整理、归档、借阅等工作；
2） 负责工程资料、图纸的管理，工程文件的处理；
3） 在项目经理指导下编制部分施工记录及验收文件；
4） 设备编号、资料整理，备品备件计划和管理；
4） 制定设备操作规程、培训生产人员。
任职要求： 1.大专及以上学历，一年及以上工作经验，工程、机械等相关专业
2.专业知识扎实的优秀毕业生亦可。
工作地址：
北京市朝阳区高安屯循环经济产业园内
**********
北京首建环保有限责任公司
公司规模：
100-499人
公司性质：
国企
公司行业：
环保
公司地址：
北京市朝阳区高安屯循环经济产业园内
查看公司地图
**********
化学分析员（亦庄公司）
北京奥达清环境检测有限公司
绩效奖金加班补助全勤奖交通补助餐补带薪年假员工旅游免费班车
**********
福利:
绩效奖金
加班补助
全勤奖
交通补助
餐补
带薪年假
员工旅游
免费班车
**********
职位月薪：4000-7000元/月 
工作地点：北京-大兴区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：10人
职位类别：其他
**********
工作职责:
 熟练掌握GC-MS,气相色谱仪，液相色谱仪，原子吸收，原子荧光分光光度计，紫外可见分光光度计，离子色谱仪，ICP-MS, ICP-OES
任职资格:
1、本科及以上学历，应用化学、分析化学相关专业毕业；
2、两年以上GC或GC-MS操作经验，熟悉各种化学分析方法；
3、有职称证优先考虑。

工作地址：
北京市大兴区亦庄凉水河二街8号院3号楼A座6层
**********
北京奥达清环境检测有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
检验/检测/认证
公司主页：
www.aodaqing.cn
公司地址：
北京市北京经济开发区凉水河二街8号院大族企业湾3号楼6层
查看公司地图
**********
运作
北京今圣梅家具制造有限公司
**********
福利:
**********
职位月薪：4001-6000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：不限
招聘人数：1人
职位类别：其他
**********
岗位职责：
1.与工厂或供应商联系完成下单生产；
2.跟踪订单的生产进度以及安排物流运输；
3.协助老板完成其他日常工作
4.制作表单及合同;
5.跟进邮件及老板交代的其他工作;
6.与客户沟通做好售后服务

任职资格：
1、高中及以上学历;
2、较强的沟通协调以及语言表达能力;
3、工作细致、认真、有责任心,较强的沟通能力;
4、熟练使用office办公软件及办公自动化设备;
5. 具有强烈的责任心，良好的团队合作精神.


工作地址：
北京市海淀区增光路27号院增光佳苑2座1单元601、602室
查看职位地图
**********
北京今圣梅家具制造有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
耐用消费品（服饰/纺织/皮革/家具/家电）
公司地址：
北京市海淀区增光路27号院增光佳苑2座1单元601、602室
**********
AGV系统技术开发及应用工程师
机科发展科技股份有限公司
五险一金绩效奖金餐补通讯补贴补充医疗保险定期体检
**********
福利:
五险一金
绩效奖金
餐补
通讯补贴
补充医疗保险
定期体检
**********
职位月薪：4001-6000元/月 
工作地点：北京-海淀区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：4人
职位类别：自动化工程师
**********
岗位职责：
1、AGV系统技术开发及应用工程师：从事单位所采用的AGV系统硬件电路设计，软硬件控制程序设计开发，系统其它应用程序的编写设计工作。
任职要求：
1、机电一体化技术、自动控制技术，电气技术等相关专业全日制本科以上（条件优秀的三年制专科以上且有一定工作经验亦可考虑）；
2、能适应经常出差工作。
工作地址：
北京市海淀区首体南路2号
查看职位地图
**********
机科发展科技股份有限公司
公司规模：
100-499人
公司性质：
国企
公司行业：
大型设备/机电设备/重工业
公司主页：
http://www.mtd.com.cn/
公司地址：
北京市海淀区首体南路2号
**********
平面设计
北京零微科技有限公司
餐补定期体检高温补贴节日福利带薪年假绩效奖金年底双薪五险一金
**********
福利:
餐补
定期体检
高温补贴
节日福利
带薪年假
绩效奖金
年底双薪
五险一金
**********
职位月薪：7000-14000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：2人
职位类别：平面设计
**********
岗位职责：
1、负责平台店铺首页的装修设计，页面布局设计，模块构建设计。
2、负责店铺活动图片，产品促销图片，广告焦点轮播图，以及平台官方活动的图片设计。
3、负责产品细节描述页面的设计和布局。能够根据品牌、产品提出创意设计想法及风格。
4、完成推广和运营人员提出的设计要求和其他设计，根据运营节奏设计并完成相关制作需求。
5、负责店铺的产品的上架，产品的编辑。
6、配合推广人员完成相关的推广设计方案等。
 
B：任职要求：
1、  爱好视觉，对设计有天生的触觉，追求完美。
2、  一年以上电商平台设计经验。
3、  熟悉photoshop等相关设计软件。
4、  有良好的团队合作精神，有耐心， 做事认真细心负责，诚实可靠，能承受一定的工作压力。
工作地址
北京市朝阳区来广营西路8号国创产业园


工作地址：
北京市来广营西路8号国创产业园6号楼507
查看职位地图
**********
北京零微科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
www.lingwei.tech
公司地址：
北京市来广营西路8号国创产业园6号楼507
**********
仓库管理员
科氏(北京)滤膜科技有限公司
通讯补贴年底双薪绩效奖金年终分红交通补助带薪年假节日福利员工旅游
**********
福利:
通讯补贴
年底双薪
绩效奖金
年终分红
交通补助
带薪年假
节日福利
员工旅游
**********
职位月薪：3500-5500元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：10人
职位类别：仓库/物料管理员
**********
岗位职责：
1、遵守公司各项规章制度，负责仓库进、出货、存货管理，样本间进、出货、存货管理，执行物料管理规定；
2、及时、完整、准确登记存货仓库账，序时登记，定期编制存货进出存报表，库存基数预警；
3.、负责仓库存货保管，保证库内存货安全，禁止无关人员及危险物品随意进入仓库；
4、 负责存货日常管理，包括存货分类码放、整理、标识、及进出库调度。要求熟悉存货特性，分类管理，合理摆放，便于物流及安全；
5、按财务要求定期或不定期核对存货入库、出库、结存数量。要求账目清楚、标识清晰、账卡物核对相符。经常对账点数，定期盘点；
6、严格执行存货收发流程及要求，正确、及时办理原料入库、生产领料、完工入库、销售出库、及其他类存货入库出库的开单、收发料和签字手续；
7. 廉洁自律，不得损害公司形象及利益，杜绝商业舞弊行为。
8.根据实际情况需要开车外出发货，把货物送到物流园发专线物流。

任职资格：
1、熟悉计算机知识，懂得基本办公软件使用功能；
2、熟悉供应物资管理办法及物资出入库管理。
3.40岁以内，为男士，有驾照。有2年以上实际驾驶经验。
工作地址：
大兴区天华大街2号
**********
科氏(北京)滤膜科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.kochmembrane.cn/
公司地址：
大兴区庆祥南路29号
查看公司地图
**********
大客户销售代表
天津提帝必环境科技有限公司
五险一金绩效奖金年终分红
**********
福利:
五险一金
绩效奖金
年终分红
**********
职位月薪：7000-8000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：大客户销售代表
**********
一、岗位职责：
1、负责开发房地产、医院、学校、养老院、高端会所、装修等行业客户，推广公司的空气净化产品与解决方案；
2、负责与工程承包商、设计院、装饰装修公司、等利益相关方（行业）建立并保持良好的合作关系，推广公司的产品设备；
3、负责公司现有政府、行业等资源和业务对接，推进和深化合作关系，最终实现业务销售。

二、任职要求：
1、两年以上大客户、大项目业务销售经验，具备大客户销售技巧，熟悉项目操作；
2、优秀的语言表达能力、沟通协调能力、公关能力、独立解决问题的能力；
3、有工程承包商、设计院、装饰装修公司等业务资源者优先。
工作地址：
北京市朝阳区白家庄东里锦湖园公寓B1层
查看职位地图
**********
天津提帝必环境科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
环保
公司主页：
www.tdbvs.com
公司地址：
天津市津南区北闸口镇国家自主创新示范区高营路8号508-45
**********
会计
北京正力润成环保设备有限公司
五险一金包住餐补弹性工作节日福利不加班
**********
福利:
五险一金
包住
餐补
弹性工作
节日福利
不加班
**********
职位月薪：5000-8000元/月 
工作地点：北京-丰台区
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：1人
职位类别：会计/会计师
**********
岗位职责：
1.汇总整理各种原始凭证，独立编制记账凭证，建立登记账簿；
（1）客户应收帐款结算、核销、对帐、报表分析等工作；
（2）供应商应付账款结算、核销、对帐等工作；
（3）确保各种记账凭证的正确性、合法性，做到账证、账账、账表、账实相符；
（4）及时准确提供进、销项税金额、客户及供应商往来款项数额、各种入账费用金额等其它相关信息；
（5）编制完成财务报表、统计报表、税务报表。
2.协助相关部门查询掌握客户及供应商的票款往来情况，随时提供数据，及时发现问题；

任职要求：
1.财务、会计等相关专业，大专及以上学历；
2.会计从业资格证书、有职称者优先考虑；
3.具有扎实的会计基础知识和3年及以上工作经验者；
4.熟悉企业增值税一般纳税人发票的开具和报税流程；
5.能够独立且熟练掌握账务处理，熟悉会计工作流程，熟练掌握办公软件。
6.熟知近期税务及财务方面的规定及政策。
7.具备良好的沟通能力，具有一定的临场应变能力，工作细致认真，责任心强，能承受工作压力。

工作地址：
办公地址：北京市丰台区汉威国际大厦7号楼8M层
**********
北京正力润成环保设备有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
环保
公司主页：
www.bjzlrcfrp.com
公司地址：
办公地址：北京市丰台区汉威国际大厦7号楼VIP四合院东院
查看公司地图
**********
行政前台文员
中环智慧环境有限公司
五险一金年底双薪带薪年假通讯补贴餐补交通补助定期体检节日福利
**********
福利:
五险一金
年底双薪
带薪年假
通讯补贴
餐补
交通补助
定期体检
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：前台/总机/接待
**********
岗位职责：
1、负责公司前台接待工作，负责来访客户的接待、基本咨询和引见；
2、负责公司电话接转、收发传真、文档复印等工作；
3、做好来电咨询工作，重要事项认真记录并传达给相关人员，不遗漏、延误；
4、负责各类办公文档、商务文档、合同协议的录入、排版、打印；
5、日常文书、资料整理及其他一般行政事务；
6、负责公司前台、咨询接待室、会议室的卫生清洁及桌椅摆放，并保持整洁干净；
7、完成其他行政部的日常事务性工作。
任职要求：
1、本科及以上学历，身高165CM以上，形象较佳，具备良好的服务意识，有主动解决问题的意愿及能力；
2、熟悉前台工作流程，熟练使用office办公软件（WORD、EXCEL、PPT）及自动化设备；
3、工作热情积极、细致耐心，具有良好的沟通能力、协调能力、性格开朗、乐于助人；

工作地址：
北京市朝阳区亮马桥路21号枫花园汽车电影院内26号二层
查看职位地图
**********
中环智慧环境有限公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
环保
公司地址：
北京市朝阳区亮马桥路21号枫花园汽车电影院内26号二层
**********
反渗透膜纳滤膜超滤膜销售工程师
科氏(北京)滤膜科技有限公司
年底双薪绩效奖金交通补助通讯补贴带薪年假节日福利员工旅游年终分红
**********
福利:
年底双薪
绩效奖金
交通补助
通讯补贴
带薪年假
节日福利
员工旅游
年终分红
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：10人
职位类别：销售工程师
**********
岗位职责：
1、 RO/NF/UF膜产品的市场开发与销售
2、 制定本区域营销计划、分解销售目标
3、 配合全国各地代理商开展工作，完成公司业务目标
4、 直接参与、主持重要客户的业务技术交流、谈判及成交
5、 督导代理商及老客户业务开展工作，落实本区域货款回收
6、 控制所辖区域相互竞争、协调客户反馈信息及现场业主等问题
任职要求：
1、环境工程、给排水、电厂化学、化工工艺等相关专业；
2、1年以上销售工作经验；专科以上学历，
3、了解、熟悉反渗透膜/纳滤膜/超滤膜等水处理系统设计者优先考虑；
4、善于掌握市场信息，具有敏锐的市场观察力、判断力；
5、能够独立组织协调工作，能够适应出差。

工作地址：
大兴区天华大街2号
**********
科氏(北京)滤膜科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.kochmembrane.cn/
公司地址：
大兴区庆祥南路29号
查看公司地图
**********
人力资源主管
北京新科瑞达电气设备有限公司
创业公司五险一金绩效奖金年终分红包住交通补助节日福利通讯补贴
**********
福利:
创业公司
五险一金
绩效奖金
年终分红
包住
交通补助
节日福利
通讯补贴
**********
职位月薪：5000-10000元/月 
工作地点：北京-海淀区
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：1人
职位类别：人力资源主管
**********
人力资源主管 1人

岗位职责：
1、配合总经理规划公司组织架构，执行人力资源管理制度，负责线上线下人员招聘，组织人员培训与考核。
2、搜集整理市场信息，搜索招标信息，负责网站注册与标书购买；制作标书、签订购销合同及相关文件的存档和管理；
3、协助销售部门工作，传达与执行公司政策，整理客户资料、询价、报价，审核差旅报销、费用预算；
4、领导临时交办的任务。

任职要求：
1、行政或人力资源专业，本科学历，有一定行政与人力资源管理经验。有良好的个人与职业素养；
2、性格活泼，普通话流利，沟通能力强，能承受工作压力；
3、有良好的服务意识及动手能力，对工作积极主动，认真负责；
4、熟练操作office办公软件和办公自动化设备，会制作招投标文件者优先。
（以上办公技能需在应聘现场演练）

面试地址：北京市海淀区上地十街1号辉煌国际广场西6号楼4层417室

工作地址：
北京市海淀区上地十街1号辉煌国际广场西6号楼4层417室
查看职位地图
**********
北京新科瑞达电气设备有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
仪器仪表及工业自动化
公司主页：
www.bjxkrd.com
公司地址：
北京市海淀区上地十街1号辉煌国际广场3号楼6层619室
**********
总助、项目助理
北京奥仕洁清洁设备有限公司
五险一金绩效奖金交通补助餐补房补通讯补贴定期体检员工旅游
**********
福利:
五险一金
绩效奖金
交通补助
餐补
房补
通讯补贴
定期体检
员工旅游
**********
职位月薪：4001-6000元/月 
工作地点：北京-大兴区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：2人
职位类别：销售运营专员/助理
**********
岗位职责：协助销售总经理的运营、销售以及管理工作。

任职要求：1、机电类本科学历或英语专业。
          2、性格外向、能吃苦、有韧性。
          3、身体健康、为人正派，懂礼节。
          4、家庭有烟草行业或教育背景优先！
工作地址：
北京市大兴区旧宫工业园南区甲23号
查看职位地图
**********
北京奥仕洁清洁设备有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
贸易/进出口
公司主页：
http://www.IPC-china.com; www.bjaoshijie.com
公司地址：
北京市大兴区旧宫工业园南区甲23号
**********
电气工程师
机科发展科技股份有限公司
五险一金带薪年假补充医疗保险节日福利
**********
福利:
五险一金
带薪年假
补充医疗保险
节日福利
**********
职位月薪：7000-14000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：硕士
招聘人数：4人
职位类别：自动化工程师
**********
任职要求：
1. 本科以上学历，自动化、机械电子工程、机械工程及自动化、测控技术与仪器等相关专业。
2. 熟练运用Labview，PLC软件。
3. 具有较强的责任心、有较强的学习能力、钻研创新能力，优秀的理解、沟通表达能力及分析问题解决问题的能力。 勤奋、踏实、有耐心、有韧性，能与团队成员很好的合作。
4. 有相关工作经验者优先。
工作地址：
北京市海淀区闵庄路3号清华科技园玉泉慧谷20栋
**********
机科发展科技股份有限公司
公司规模：
100-499人
公司性质：
国企
公司行业：
大型设备/机电设备/重工业
公司主页：
http://www.mtd.com.cn/
公司地址：
北京市海淀区首体南路2号
查看公司地图
**********
大客户经理【战略性新兴产业】
北京威派格科技发展有限公司
五险一金绩效奖金年终分红交通补助带薪年假定期体检员工旅游节日福利
**********
福利:
五险一金
绩效奖金
年终分红
交通补助
带薪年假
定期体检
员工旅游
节日福利
**********
职位月薪：10001-15000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：大客户销售经理
**********
一个站在“互联网+”风口上的行业
   工业互联，智联供水新型设备引领产业升级。
 智慧水务，城市供水管理平台提升水务运营。

一家引领行业发展的企业
 承接国家“十二五”水专项课题
五项建设部行业标准/一项国家标准
二次供水领域74项专利
国际工业互联联盟IIC成员
西门子SIEMENS战略合作伙伴
中国首个工程级水利综合实验平台
工业4.0标准的全新智能化工厂

选择你的未来！期待你的加入！

岗位职责：
1、 负责带领团队开发及拓展大客户/行业客户(地产、高校系统)总部及上级行政主管部门中基层领导的关系；
2、 支持与配合分公司的市场拓展工作（大客户/行业客户总部支持）；
3、 开发运用好大客户/行业客户总部的能量和协会组织来影响及控制；
4、 引导并参与各区域水司及上级行政主管部门关于二次供水会议的申办与召开；
5、 开展有利于大客户/行业客户工作影响力大的品牌推广活动；
6、 协助分公司参加政府、行业协会会议，进行产品讲解、技术交流与品牌推广工作；
7、 协助分公司做好大客户/行业客户总部的关系，操作分公司项目采购形式和数量。

任职资格：
1、 统招本科及以上学历，形象气质良好；
2、 两年以上市场拓展或系统客户开发类管理工作经验；
3、 表达能力强，亲和力强；
4、 积极进取、执着、阳光正派、责任心；
5、 优秀的沟通协调与协作能力；
6、 优秀的学习及系统思考能力。

职业发展通道：
大客户专员→大客户经理→区域大客户经理

选择一个前景无限的产业，决定着你未来广阔的发展空间。
选择一个迅速发展的企业，决定着你拥有更多的发展机会。
选择一个行业的龙头企业，决定着你将接受到更好的培养。
选择一个积极向上的团队，决定着你拥有志同道合的伙伴。

选择我们，选择一份值得奋斗一生的事业！



工作地址：
北京市宣武区宣外大街10号庄胜广场中央办公楼北翼11层
**********
北京威派格科技发展有限公司
公司规模：
1000-9999人
公司性质：
上市公司
公司行业：
大型设备/机电设备/重工业
公司主页：
http://www.shwpg.com/
公司地址：
北京市宣武区宣外大街10号庄胜广场中央办公楼北翼11层
**********
测量审核管理
北京环标科创环境科技发展有限责任公司
五险一金绩效奖金餐补带薪年假定期体检
**********
福利:
五险一金
绩效奖金
餐补
带薪年假
定期体检
**********
职位月薪：4000-7000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：1人
职位类别：环保技术工程师
**********
岗位职责：
1、负责测量审核项目实施；
2、负责客户服务；
3、负责实验室报名与缴费管理；
4、负责实验室发票邮寄等工作；
6、负责测量审核网络服务平台工作；
7、参与能力验证课题研究。

任职要求：
1、环境科学、环境化学、分析化学、仪器分析等相关专业，本科及以上学历；
2、具备化学分析基础，熟练掌握电脑和办公软件的使用；
3、具有财务管理经历者优先。
工作地址：
北京市朝阳区育慧南路1号
**********
北京环标科创环境科技发展有限责任公司
公司规模：
20-99人
公司性质：
国企
公司行业：
环保
公司地址：
北京市朝阳区育慧南路1号
**********
销售工程师
上海明号电器有限公司
五险一金绩效奖金包住交通补助通讯补贴带薪年假员工旅游节日福利
**********
福利:
五险一金
绩效奖金
包住
交通补助
通讯补贴
带薪年假
员工旅游
节日福利
**********
职位月薪：2001-4000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：5人
职位类别：销售工程师
**********
岗位职责：
1、建立客户档案，制定工作方案与计划，按《市场工作手册》开展市场工作
2、负责照明产品市场推广和项目运作，完成销售目标
3、负责已销售产品的售后服务及货款催收工作
4、负责服务现有市场客户并开拓新市场
薪酬福利
1、无责任底薪提成制
2、试用期3000
3、转正后起薪3500-4400+提成（含社保、公积金、商业保险)年薪5万-20万
4、年假、节日费、书本费、医药费、女工费、独生子女费、电话费、可提供住宿等各项福利
5、广阔的晋升空间（业绩决定职称）
可接受外派者，优先考虑
工作地址：
北京市
查看职位地图
**********
上海明号电器有限公司
公司规模：
20-99人
公司性质：
合资
公司行业：
电气/电力/水利
公司主页：
www.minghaodq.com
公司地址：
上海市浦东新区金湘路333号103室（爱立诚大厦）
**********
环境技术工程师（实习）
中环智慧环境有限公司
年底双薪带薪年假通讯补贴餐补交通补助定期体检节日福利
**********
福利:
年底双薪
带薪年假
通讯补贴
餐补
交通补助
定期体检
节日福利
**********
职位月薪：1000-2000元/月 
工作地点：北京
发布日期：最新
工作性质：实习
工作经验：不限
最低学历：本科
招聘人数：10人
职位类别：环保技术工程师
**********
岗位职责：
1、负责分析整理市场营销人员收集的基础数据；
2、负责配合市场营销人员、项目报价人员和项目运营人员进行实地调研；
3、负责项目实施方案汇编。
任职要求：
1、环境工程、环境科学或相关专业，本科及以上学历；
2、具有环卫一体化、转运站、垃圾分类等相关技术、工程工作经验者优先考虑；
3.、可独立或指导下完成技术方案和标书文件的制作；
4、具备较强的归纳统计、独立分析问题和解决问题的能力；具有良好的沟通能力和团队合作精神；
5.、能适应偶尔出差；
6、有市政环卫、基础设施PPP项目运作经验者可优先考虑；

工作地址：
北京市朝阳区亮马桥路21号枫花园汽车电影院内26号二层
查看职位地图
**********
中环智慧环境有限公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
环保
公司地址：
北京市朝阳区亮马桥路21号枫花园汽车电影院内26号二层
**********
研究部-项目主管
全联环境服务业商会
五险一金绩效奖金交通补助采暖补贴带薪年假补充医疗保险定期体检节日福利
**********
福利:
五险一金
绩效奖金
交通补助
采暖补贴
带薪年假
补充医疗保险
定期体检
节日福利
**********
职位月薪：6000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：1人
职位类别：科研人员
**********
岗位职责：
负责环保产业研究工作，着重于环保行业政策演变、产业发展趋势研究等。
任职要求：
1.环境管理、环境保护等相关专业，硕士以上学历（含硕士）；
2.具备一定的环保企业或相关研究机构工作经验
3.具备扎实的专业知识，熟悉环保领域相关产业法律、法规、政策以及PPP、第三方治理模式。
4.具有较强的敬业精神、团队合作精神、科研创新能力和独立工作能力，能够科学高效地完成商会的研究工作；
5.良好的文字功底和沟通能力；
6.了解环保企业，从事过环保行业分析师工作，具有相关研究经验者优先。

工作地址：
北京市朝阳区安慧里四区十五号中国五矿大厦
**********
全联环境服务业商会
公司规模：
20-99人
公司性质：
其它
公司行业：
政府/公共事业/非盈利机构
公司主页：
www.cecc-china.org
公司地址：
北京市朝阳区安慧里四区十五号中国五矿大厦
查看公司地图
**********
客户服务专员
北京奥达清环境检测有限公司
绩效奖金全勤奖交通补助餐补通讯补贴带薪年假员工旅游
**********
福利:
绩效奖金
全勤奖
交通补助
餐补
通讯补贴
带薪年假
员工旅游
**********
职位月薪：3000-4500元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：2人
职位类别：客户服务专员/助理
**********
部门主要职能：
1、重大项目实施方案确定
2、对各项目所需的实施人员和设备进行调配，与各部门一同讨论
3、完善客服流程机制，做好部门协同与沟通（实验室、采样部）
4、跟进进行中的项目与客户及时沟通，与客户讨论完成质量记录反馈
5、定期汇总全部客服服务内容，对项目实施中存在的问题进行汇总并开会讨论。对超期的报告记录其原因，并进行汇总，分类归档，通报
7、总结历年大型项目情况，制定下一年的各区开发计划，与市场部制定时间节点。
8、跟进重要客户为客户做预算，组织招投标工作
 区域客服职能：
1、参与预算和报价、由销售审核并初步制定实施方案
2、编制招标文件、投标文件，确认项目方法是否有资质，若没有及时汇总给主管提出增项
3、拟定合同后交给市场销售审核签字
4、与项目负责人讨论具体实施方案，进行内部讨论确定后外部汇报。
5、下单管理，记录该报告的所属的合同编号、项目和截止日期根据日期催报告，确保可以及时交给环保局。
6、领走报告时及时结算交给市场部人员，交由财务
7、按环保局要求的时间和格式报数，领取报告。交付后与甲方沟通数据及服务质量，并反馈给主管
8、及时总结每个项目在实施过程中的流程问题

 
一般项目客服职能：
1、下单管理（合同编号、报价单编号）
2、检测安排台账管理、催单、超期记录、反馈
3、监测负责人提前联系客户是否具备检测条件，有问题反馈客服，有必要去看现场
4、确认日期、发出报告，填写确认单给财务报告



工作地址：
北京市北京经济开发区凉水河二街8号院3号院A座6层
**********
北京奥达清环境检测有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
检验/检测/认证
公司主页：
www.aodaqing.cn
公司地址：
北京市北京经济开发区凉水河二街8号院大族企业湾3号楼6层
查看公司地图
**********
.水处理药剂销售工程师
科氏(北京)滤膜科技有限公司
年底双薪五险一金交通补助通讯补贴带薪年假年终分红绩效奖金每年多次调薪
**********
福利:
年底双薪
五险一金
交通补助
通讯补贴
带薪年假
年终分红
绩效奖金
每年多次调薪
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：10人
职位类别：大客户销售代表
**********
岗位职责：
1、 反渗透药剂及循环水药剂的市场开发与销售
2、 制定本区域营销计划、分解销售目标
3、 配合全国各地代理商开展工作，完成公司业务目标
4、 直接参与、主持重要客户的业务技术交流、谈判及成交
5、 督导代理商及老客户业务开展工作，落实本区域货款回收
6、 控制所辖区域相互竞争、协调客户反馈信息及现场业主等问题
任职要求：
1、环境工程、给排水、电厂化学、化工工艺等相关专业；
2、1年以上销售工作经验；专科以上学历，
3、了解、熟悉反渗透膜/纳滤膜/超滤膜等水处理系统设计者优先考虑；
4、善于掌握市场信息，具有敏锐的市场观察力、判断力；
5、能够独立组织协调工作，能够适应出差。

工作地址：
大兴区天华大街2号
**********
科氏(北京)滤膜科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.kochmembrane.cn/
公司地址：
大兴区庆祥南路29号
查看公司地图
**********
聘外派出差/销售代表/5100+提成/包住宿
唐山勤领商贸有限公司北京分公司
五险一金年底双薪包住采暖补贴带薪年假员工旅游高温补贴节日福利
**********
福利:
五险一金
年底双薪
包住
采暖补贴
带薪年假
员工旅游
高温补贴
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：6人
职位类别：销售代表
**********
薪资待遇及福利：
1、待遇:试用期底薪5100起+ 业绩提成+ 奖金(日、周、月、年)+五险+季度旅游
转正6000+业绩提成+奖金(日、周、月、年)+五险+季度旅游

(注: 挑战高薪工资 销售价格提成25个点，挑战高薪 直接选择拿高业绩提成 薪资将会达到6000~10000所有提成当天结算） 。

2、福利: 带薪年假 + 国家法定节假日 休息+ 不定期员工活动 + 旅游 +生日关怀 + 年底双薪;

3、入职提供免费培训，免费提供食宿
转正之后公司缴纳五险一金

岗位职责：
1、市场业务，实体销售、团队协作模式。
2、在老客户基础上开发新客户。
3、具有较强的团队工作能力。
不用担心工作不好做，有人带、有培训。

任职要求：
1、有志青年,退伍军人和应届毕业生优先
2、外向健谈,应变能力强,积极主动,有较好的沟通能力。
3、有上进心,有较强的学习模仿能力。
4、思路清晰,具有良好的沟通应变能力和执行力。
5、有创新意识,思维活跃,有工作热忱。
6、对创业有强烈欲望,并能完全展现个人能力者。
*有无经验均可,提供带薪培训。
*性恪开朗,随和,有亲和力和团队合作精神
*有事业心和创业精神者优先 。
* 完善的培训,帮助更快提升。
公司直招  ! ! !

晋升空间：
业务代表----销售队长---销售主管----销售总监--区域总经理
在公司的培训下，职位晋升很快。鼓励员工快速成功，成为公司的销售经理时，公司将为你开出属于你自己的公司，来经营自己的事业。集团公司目前为止已达到600多家公司，欢迎有志向的年轻人。


工作时间：
八小时制 上午8：30-11：50 , 下午14:00-18;00；法定节假日休息。


联系人 : 人事部
联系电话 : 010-56172220 010-56172221
公司地址 : 北京市朝阳区西大望路SOHO现代城A座3005房间

工作地址：
唐山勤领商贸有限公司北京分公司
**********
唐山勤领商贸有限公司北京分公司
公司规模：
1000-9999人
公司性质：
股份制企业
公司行业：
环保
公司地址：
唐山勤领商贸有限公司北京分公司
查看公司地图
**********
销售经理(上市公司/值得奋斗一生的事业)
北京威派格科技发展有限公司
五险一金绩效奖金交通补助通讯补贴带薪年假定期体检员工旅游节日福利
**********
福利:
五险一金
绩效奖金
交通补助
通讯补贴
带薪年假
定期体检
员工旅游
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：2人
职位类别：销售经理
**********
一个站在“互联网+”风口上的行业
工业互联，智联供水新型设备引领产业升级
智慧水务，城市供水管理平台提升水务运营
 一家引领行业发展的企业 
承接国家“十二五”水专项课题
五项建设部行业标准/一项国家标准
二次供水领域74项专利
国际工业互联联盟IIC成员
西门子SIEMENS战略合作伙伴
中国首个工程级水利综合实验平台
工业4.0标准的全新智能化工厂
 岗位职责：
1、带领团队完成我公司二次供水设备向工程项目类客户的销售，完成销售任务；
2、带领团队完成客户关系的深入维护与提升；
3、充分利用我公司综合性的资源和核心竞争力为客户创造价值，赢得与客户的项目合作。
 任职要求：
1、统招本科学历，3年以上销售经验，工业品销售经验者优先考虑；
2、1年以上销售管理经验，带团队人数2人以上；
3、具有良好的调动资源和团队协作能力。
 薪资标准：
薪资执行独立核算制，基本月薪+15%利润核算。
 晋升通道：
销售经理——分公司副总——分公司总经理
 选择一个前景无限的产业，决定着你未来广阔的发展空间。
选择一个迅速发展的企业，决定着你拥有更多的发展机会。
选择一个行业的龙头企业，决定着你将接受到更好的培养。
选择一个积极向上的团队，决定着你拥有志同道合的伙伴。

选择我们，选择一份值得奋斗一生的事业！
工作地址：
北京市宣武区宣外大街10号庄胜广场中央办公楼北翼11层
**********
北京威派格科技发展有限公司
公司规模：
1000-9999人
公司性质：
上市公司
公司行业：
大型设备/机电设备/重工业
公司主页：
http://www.shwpg.com/
公司地址：
北京市宣武区宣外大街10号庄胜广场中央办公楼北翼11层
**********
品牌推广专员【战略性新兴产业】
北京威派格科技发展有限公司
五险一金绩效奖金带薪年假定期体检员工旅游节日福利
**********
福利:
五险一金
绩效奖金
带薪年假
定期体检
员工旅游
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：品牌主管
**********
一个站在“互联网+”风口上的行业
   工业互联，智联供水新型设备引领产业升级。
 智慧水务，城市供水管理平台提升水务运营。
 一家引领行业发展的企业
  承接国家“十二五”水专项课题
 五项建设部行业标准/一项国家标准
 二次供水领域74项专利
 国际工业互联联盟IIC成员
 西门子SIEMENS战略合作伙伴
 中国首个工程级水利综合实验平台
 工业4.0标准的全新智能化工厂

岗位职责：
1、配合制定年度、季度推广计划，并负责贯彻落实；
2、推广过程的组织、监督和效果评估；
3、公司对外发布新闻渠道的维护。
 任职资格：
1、具备团队精神与合作意识、强烈的进取精神与高标准意识，良好的学习能力沟通能力、组织协调能力和社会活动能力；
2、较强的理解能力，优秀的文案写作能力；
3、新闻传播专业优先考虑。

职业发展通道：
品牌专员—品牌主管—品牌经理
 选择一个前景无限的产业，决定着你未来广阔的发展空间。
选择一个迅速发展的企业，决定着你拥有更多的发展机会。
选择一个行业的龙头企业，决定着你将接受到更好的培养。
选择一个积极向上的团队，决定着你拥有志同道合的伙伴。
 选择我们，选择一份值得奋斗一生的事业！

工作地址：
北京市宣武区宣外大街10号庄胜广场中央办公楼北翼11层
**********
北京威派格科技发展有限公司
公司规模：
1000-9999人
公司性质：
上市公司
公司行业：
大型设备/机电设备/重工业
公司主页：
http://www.shwpg.com/
公司地址：
北京市宣武区宣外大街10号庄胜广场中央办公楼北翼11层
**********
SOFC燃料电池模块开发工程师
北京低碳清洁能源研究所
**********
福利:
**********
职位月薪：面议 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：5-10年
最低学历：硕士
招聘人数：1人
职位类别：化工工程师
**********
岗位职责：
负责SOFC模块开发，负责BOP、系统、电池单元设计与开发，协助团队进行hotbox、SOFC控制系统开发；进行电堆热平衡与物质平衡计算，进行模块控制参数和运行参数设计；运行与维护SOFC设备及仪器；进行SOFC电堆测试。
任职要求：
硕士以上学历，化工、热能等相关专业，有SOFC相关知识背景，具有SOFC模块开发、SOFC电堆设计的相关经验，良好的英语读写及交流能力

工作地址：
北京市昌平区未来科技城神华低碳001信箱
**********
北京低碳清洁能源研究所
公司规模：
100-499人
公司性质：
国企
公司行业：
环保
公司地址：
北京市昌平区未来科技城神华低碳001信箱
**********
销售部副总监
天津金屋顶光伏科技有限公司
创业公司绩效奖金股票期权定期体检节日福利弹性工作交通补助五险一金
**********
福利:
创业公司
绩效奖金
股票期权
定期体检
节日福利
弹性工作
交通补助
五险一金
**********
职位月薪：8000-16000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：1人
职位类别：区域销售总监
**********
1、 负责所在区域户用产品的光伏系统业务的市场开拓（北京顺义、平谷为主；）；
2、 负责现所在区域光伏产品的客户开发与维护（北京大兴、通州、密云为主）；
3、 配合销售总监制定公司年度销售指标，提出市场活动规划； 
4、 根据公司业务战略及公司的销售计划，制定营销方案，提升品牌知名度；
5、 进行行业市场分析与研究，为公司制定经营决策提供可靠的市场分析依据；
6、 建立顺畅的客户沟通渠道，主持客户的业务谈判及成交，创建长期、良好、稳固的区域客户关系；
7、管理并培养发展销售团队。
任职资格：
1、本科及以上学历，市场营销等相关专业；
2、掌握市场营销管理知识，具有较强的市场开拓能力、商务谈判能力，具备良好的人际关系协调和沟通能力；
3、具备相关渠道行业销售经验者优先（如热水器、家电、水暖等）；
4、有驾驶执照C本；
5、五年及以上带团队经验；
6、性别，年龄范围：男性，从 28岁到 36 岁。

工作地址：
通州区
查看职位地图
**********
天津金屋顶光伏科技有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
电气/电力/水利
公司主页：
http://www.tianjingoldroof.com/
公司地址：
西青区精武镇学府商务大厦468室
**********
单片机软件工程师
北京宏光星宇科技发展有限公司
五险一金年底双薪绩效奖金包吃员工旅游节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
包吃
员工旅游
节日福利
**********
职位月薪：8001-10000元/月 
工作地点：北京-昌平区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：2人
职位类别：电子技术研发工程师
**********
岗位职责：
1. 负责项目产品维护工作，产品开发工作；
2. 负责项目相关软件文档编写工作；
3. 负责系列产品的软件维护工作。
任职要求：
1. 本科及以上学历，英语良好，能看懂英文资料；
2. 电子、自动化、通信、计算机及相关专业，1-3年相关工作经验；
3. 精通C语言，熟悉51系列单片机、STM32、DSP等开发； 
4. 能够用VC编写上位机软件；
5. 熟练掌握IIC、UART、SPI、CAN等常见接口通讯方式和协议，对AD、DA及传感器编程熟练，熟悉数字电路和模拟电路；
6. 具有良好规范的文档和编程习惯，较强的分析和解决问题能力，有良好的沟通与团队合作精神；
7. 有开关电源开发经验者优先。

工作地址：
北京市昌平区北清路TBD云集中心
查看职位地图
**********
北京宏光星宇科技发展有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
www.hgxykj.cn
公司地址：
北京市昌平区北清路TBD云集中心
**********
单片机软件工程师
北京宏光星宇科技发展有限公司
五险一金年底双薪绩效奖金包吃员工旅游节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
包吃
员工旅游
节日福利
**********
职位月薪：8001-10000元/月 
工作地点：北京-昌平区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：2人
职位类别：电子技术研发工程师
**********
岗位职责：
1. 负责项目产品维护工作，产品开发工作；
2. 负责项目相关软件文档编写工作；
3. 负责系列产品的软件维护工作。
任职要求：
1. 本科及以上学历，英语良好，能看懂英文资料；
2. 电子、自动化、通信、计算机及相关专业，1-3年相关工作经验；
3. 精通C语言，熟悉51系列单片机、STM32、DSP等开发； 
4. 能够用VC编写上位机软件；
5. 熟练掌握IIC、UART、SPI、CAN等常见接口通讯方式和协议，对AD、DA及传感器编程熟练，熟悉数字电路和模拟电路；
6. 具有良好规范的文档和编程习惯，较强的分析和解决问题能力，有良好的沟通与团队合作精神；
7. 有开关电源开发经验者优先。

工作地址：
北京市昌平区北清路TBD云集中心
查看职位地图
**********
北京宏光星宇科技发展有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
www.hgxykj.cn
公司地址：
北京市昌平区北清路TBD云集中心
**********
电源研发工程师
北京宏光星宇科技发展有限公司
五险一金年底双薪绩效奖金加班补助全勤奖带薪年假餐补员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
加班补助
全勤奖
带薪年假
餐补
员工旅游
**********
职位月薪：8001-10000元/月 
工作地点：北京-昌平区
发布日期：2018-03-10 17:27:59
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：2人
职位类别：电子/电器工程师
**********
岗位职责：
1.   能够把握通信电源行业技术发展趋势和业务发展动向。
2.   熟悉高频开关电源开发流程，能主导产品的整个开发过程。
3.   能配合生产部门，解决生产、测试设备疑难故障，对产品工艺、质量控制能提出建设性建议。
4.   有扎实的电子专业技术知识，对电子电路有较强的分析及动手能力，能解决产品开发中的各种技术问题。
岗位要求：
1.  3年以上通信用高频开关电源开发或大功率、高密度军品电源研发工作经验。熟悉开关电源及功率器件的结构、性能、原理、使用方法，有扎实的理论基础和实际工作经验。
2.   本科及以上学历，高频开关电源或电子类相关专业。
3.   年龄35岁以下，有大公司工作背景者优先录用。
4.   熟悉ARM9及嵌入式LINUX操作系统，能熟练地阅读和理解英文文档，有一定的编程能力及驱动编写经验者优先考虑。
5.   熟悉单片机和接口电路、模拟电路、数字电路；熟悉FPGA/DSP者优先考虑。
6.   熟练掌握PROTEL98/99；熟悉Altium Designer或allegro软件者更佳。
7.   精通产品开发流程且具有良好的文档习惯。
8.   具备很强的判断、决策、计划与执行能力；有良好的沟通、协调、组织和团队建设能力及引发能力，能带领团队高效完成项目任务。
9.   热爱管理工作，高度的责任心和工作热情，良好的职业道德

工作地址：
北京市昌平区北七家镇西沙工业园区8号院
查看职位地图
**********
北京宏光星宇科技发展有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
www.hgxykj.cn
公司地址：
北京市昌平区北清路TBD云集中心
**********
培训讲师
北京宏光星宇科技发展有限公司
**********
福利:
**********
职位月薪：6001-8000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：1人
职位类别：通信电源工程师
**********
岗位职责：
1.   熟知产品特点，了解市场需求，制作产品解决方案；
2.   公司产品资料及客户所需产品技术资料制作；
3.   客户和公司人员产品技术培训；
4.   客户现场支撑，配合客户完成所需技术资料；
5.   按时完成公司分配的其他工作。
任职资格：
1.   本科及以上学历，电子、通信或相关专业；
2.   3年及以上通信行业工程技术类工作经验，有培训经验者优先；
3.   熟悉office、CAD等常用软件，有长期WORD和PPT资料制作经验；
4.   能适应出差工作，吃苦耐劳；
5.   积极主动、责任心强，有较好的沟通能力及团队协作能力；
6.   做事有条理，逻辑性好，思维敏锐，品行端正；
7.   有敬业精神，较强的责任心，有解决问题的钻研精神。
8.   善于交流，表达清晰，能与客户保持良好的沟通。
工作地址：
全国
查看职位地图
**********
北京宏光星宇科技发展有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
www.hgxykj.cn
公司地址：
北京市昌平区北清路TBD云集中心
**********
会计
北京宏光星宇科技发展有限公司
五险一金年底双薪绩效奖金全勤奖通讯补贴餐补带薪年假节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
全勤奖
通讯补贴
餐补
带薪年假
节日福利
**********
职位月薪：8001-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：2人
职位类别：会计/会计师
**********
岗位职责：
1. 负责生产成本的核算，认真进行成本、开支的事前审核；  
2. 严格控制成本，促进增产节约，增收节支，提高企业的经济效益；  
3. 负责对生产成本进行监督和管理；督导成本控制及清点存货， 审查原材料的采购；  
4. 认真核对各项原料、物料、成品、在制品收付事项。负责编制 原料转账传票。负责编制车间成本转账传票；  
5. 保管好各种凭证、账簿、报表及有关成本计算资料，防止丢失 或损坏，按月装订并定期归档；  
6. 参与存货的清查盘点工作，企业在财产清查中盘盈、盘亏的资 产，要分别情况进行不同的处理；  
7. 负责编制材料的领用分配表，进行会计核算，实行分口、分类 管理；  
8. 负责核算车间人工工时及绩效管理；  
9. 办理其他与成本计算有关的事项；  
10. 公证和诚实地履行职责，并做好企业的有关保密工作；  
11. 完成领导安排的其他工作。 
 任职要求：
1. 大学专科以上学历，财务、金融等相关专业；
2. 5年以上生产制造企业财务工作经验；
3. 能够熟练使用相关办公软件；
4. 具有较强的逻辑思维能力、判断决策能力、人际沟通能力、计划执行能力。

工作地址：
北京市昌平区北清路TBD云集中心2号楼C座12层
查看职位地图
**********
北京宏光星宇科技发展有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
www.hgxykj.cn
公司地址：
北京市昌平区北清路TBD云集中心
**********
软件工程师
北京宏光星宇科技发展有限公司
五险一金绩效奖金全勤奖包吃带薪年假员工旅游节日福利
**********
福利:
五险一金
绩效奖金
全勤奖
包吃
带薪年假
员工旅游
节日福利
**********
职位月薪：15001-20000元/月 
工作地点：北京-昌平区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：2人
职位类别：嵌入式软件开发
**********
岗位职责：
负责充电桩、逆变器、直流电源等电力电子装置控制系统软件的设计、开发和调试。
任职要求：
1.本科以上学历， 电力电子、自动化、自动控制等相关专业；
2.两年以上电力电子相关的行业嵌入式软件开发工作经验；有电源软件开发经验者优先；
3.熟悉STM32、DSP的开发及应用，掌握嵌入式C语言或C++语言；
4.熟悉嵌入式操作系统编程，掌握RS232，RS485，CAN等通讯基本原理，熟悉常用功率电路的拓扑结构；
5．较好的沟通技巧和团队精神，较强的责任感及进取精神。
6．有DSP相关开发经验者优先。

工作地址：
北京市昌平区北清路TBD云集中心
查看职位地图
**********
北京宏光星宇科技发展有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
www.hgxykj.cn
公司地址：
北京市昌平区北清路TBD云集中心
**********
工程技术人员
北京宏光星宇科技发展有限公司
**********
福利:
**********
职位月薪：4001-6000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：2人
职位类别：通信电源工程师
**********
岗位职责：
1.   产品施工现场勘测、安装督导和故障处理；
2.   产品技术支持和客户服务，客户对产品要求反馈公司；
3.   配合办事处人员协调处理产品相关工程技术事宜；
4.   配合销售人员,深入了解客户需求；根据客户需求，并结合公司产品，设计详细解决方案；
5.   与客户的技术人员进行交流互动，解决客户提出及出现的技术问题；
6.   负责制定实施计划，提出客户使用环境要求，并按照计划的时间、质量要求完成实施，负责培训用户使用产品，常见问题及解答， 电话答疑等；
7.   按时完成公司分配的其他工作。
任职资格：
1.   专科以上学历，电子、通信或相关专业；
2.   2年及以上通信行业工程技术类工作经验者优先；
3.   能适应出差工作，吃苦耐劳；
4.   积极主动、责任心强，有较好的沟通能力及团队协作能力；
5.   做事有条理，逻辑性好，思维敏锐，品行端正；
6.   有敬业精神，较强的责任心，有解决问题的钻研精神。
7.   善于交流，表达清晰，能与客户保持良好的沟通。
工作地址：
全国
查看职位地图
**********
北京宏光星宇科技发展有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
www.hgxykj.cn
公司地址：
北京市昌平区北清路TBD云集中心
**********
工艺工程师
北京宏光星宇科技发展有限公司
五险一金绩效奖金加班补助全勤奖带薪年假员工旅游节日福利
**********
福利:
五险一金
绩效奖金
加班补助
全勤奖
带薪年假
员工旅游
节日福利
**********
职位月薪：8001-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：2人
职位类别：电子/电器工艺/制程工程师
**********
岗位职责：
1) 参与新产品的研发，并从批量生产工艺要求出发，提出设计和改进意见；
2) 设计电源类产品生产工艺、编写作业指导书；
3) 新产品试产的安排、生产指导，现场异常问题的及时排除；
4) 负责装配工艺、导线工艺设计；
5) 负责生产线工装夹具的设计和优化。
 任职要求：
1) 电子类相关专业本科及以上学历；
2) 2年以上电子行业工艺、产品岗位经验；
3) 熟悉PCB A类产品的生产工艺及流程；
4) 会编写生产工艺标准、制定作业指导书；
5) 具有良好的团队协同意识，有较强的沟通能力、分析问题和解决问题的能力。

工作地址：
北京市昌平区北清路TBD云集中心2号楼C座12层1205室
查看职位地图
**********
北京宏光星宇科技发展有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
www.hgxykj.cn
公司地址：
北京市昌平区北清路TBD云集中心
**********
开关电源研发工程师
北京宏光星宇科技发展有限公司
五险一金年底双薪绩效奖金包吃员工旅游节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
包吃
员工旅游
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：北京-昌平区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：3人
职位类别：电池/电源开发
**********
岗位职责：
1. 公司既有通信开关电源产品的优化；
2. 电源产品、监测产品的开发过程中的测试和调试，在测试中不断改进优化参数；
3. 电源产品生产过程中（组装、调试、检验）出现问题的解决，以及出现问题原因的分析和改进；
4. 电源产品在生产、售后、市场过程中的技术支持；
5. 电源产品出现的问题和对应改进措施，进行各种测试和验证实验，并提出最后方案。
任职要求：
1. 电力电子或相关专业本科以上学历，热爱开关电源研发工作；
2. 较强的动手能力，熟悉各种电子元器件的规格及应用；
3. 1KW以上电源开发经验和项目领导经验；
4. 具有各类电源产品设计3年以上相关工作经验；
5. 熟悉产品开发流程；能够与团队一起进行电源产品开发；
6. 为人踏实、自励，责任心强，有较强的团队意识，善于合作。 

工作地址：
北京市昌平区北清路TBD云集中心
查看职位地图
**********
北京宏光星宇科技发展有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
www.hgxykj.cn
公司地址：
北京市昌平区北清路TBD云集中心
**********
在校生 英语专业 老师 助教
北京蕴星教育咨询有限公司
无试用期绩效奖金节日福利
**********
福利:
无试用期
绩效奖金
节日福利
**********
职位月薪：1000-2000元/月 
工作地点：北京-大兴区
发布日期：最新
工作性质：校园
工作经验：无经验
最低学历：不限
招聘人数：10人
职位类别：外语教师
**********
岗位职责：
1、负责向高端客户提供英语学习建议； 
1. Responsible for high-end clients to provide English study suggest
2、负责对已报名的VIP学员进行跟踪服务；
2. Responsible for the registered VIP students tracking service;
3、时常为学员组织课程活动；
3. Frequently organization curriculum activities for students;

任职要求：
1、大专及以上学历，硕士学历或两年以上英语国家留学经历者优先；
1. College or above degree，bachelor degree or above
with two years study in English-speaking country experience is preferred;
2、形象气质佳，活泼、开朗，热爱教育工作，喜欢孩子 
2. Presentable, lively, cheerful, love education work，like
kids
3.英语口语流利，发音地道； 
3. Fluent oral English and pronunciation accurately;
4、亲和力佳，具有良好的服务意识。 
4. Good affinity and good service consciousness
工作地址：
北京市大兴区亦庄博客雅苑底商4号
**********
北京蕴星教育咨询有限公司
公司规模：
1000-9999人
公司性质：
上市公司
公司行业：
教育/培训/院校
公司地址：
朝阳区朝阳北路101号朝阳大悦城
查看公司地图
**********
园林施工员
北京天朗科隆生态科技有限公司
五险一金包吃包住弹性工作
**********
福利:
五险一金
包吃
包住
弹性工作
**********
职位月薪：4001-6000元/月 
工作地点：北京-通州区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：施工员
**********
岗位职责：
1.在项目经理的直接领导下开展工作，贯彻安全第一、预防为主的方针，按规定搞好安全防范措施，把安全工作落到实处，做到讲效益必须讲安全，抓生产首先必须抓安全。
2.编制、组织职工按期开会学习，合理安排、科学引导、顺利完成本工程的各项施工任务。
3.编制工程总进度计划表和月进度计划表及各施工班组的月进度计划表。
4.搞好分项总承包的成本核算（按单项和分部分项）单独及时核算，并将核算结果及时通知承包部的管理人员，以便及时改进施工计划及方案，争创更高效益。 
5.督促施工材料、设备按时进场，并处于合格状态，确保工程顺利进行。
6.参加工程竣工交验，负责工程完好保护。
7.合理调配生产要素，严密组织施工确保工程进度和质量。
8.组织隐蔽工程验收，参加分部分项工程的质量评定。
任职要求：
1、园林、土建、绿化等相关专业，专科以上学历；
2、两年以上现场施工管理经验；具备控制施工质量的检查和监控相关项目现场的工作能力。
3、对工程质量、进度、造价、成本等方面具有一定的把控能力；
4、能很好的处理业主、监理等方面的关系。
5、认同公司企业文化，忠于公司，积极进取，具有很强的团队合作精神；
6、能够服从派往各地工程项目。
7、对CAD软件应用熟练者优先考虑。
工作地址：
北京市通州区台湖镇口子村新村委会东10米
**********
北京天朗科隆生态科技有限公司
公司规模：
20人以下
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://bjtlklcom.s300.gainda.net/
公司地址：
北京市通州区台湖镇口子村新村委会东10米
查看公司地图
**********
渠道销售代表
天津提帝必环境科技有限公司
五险一金绩效奖金
**********
福利:
五险一金
绩效奖金
**********
职位月薪：5000-7000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：2人
职位类别：销售代表
**********
一、岗位职责：
1、负责公司产品的销售及推广，完成年度、季度销售指标；
2、本区域内代理商的开发与维护，支持代理商的业务开展；
3、落实公司各项渠道推广活动在本区域的落地，指导和配合代理商全力执行推广促销活动的实施；
4、完成销售总监部署的市场调查、展会活动等其他临时任务。

二、任职要求：
1、两年以上代理商、经销商、加盟商开发经验；
2、有新风、空调、家装渠道资源优先:；
3、能够随时出差。
工作地址：
北京市朝阳区白家庄东里锦湖园公寓B1层
查看职位地图
**********
天津提帝必环境科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
环保
公司主页：
www.tdbvs.com
公司地址：
天津市津南区北闸口镇国家自主创新示范区高营路8号508-45
**********
财务助理
北京新叶能源科技有限公司
五险一金餐补定期体检节日福利全勤奖弹性工作
**********
福利:
五险一金
餐补
定期体检
节日福利
全勤奖
弹性工作
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：3人
职位类别：财务助理
**********
岗位职责：
 1、配合完成公司办理公司成立、变更、年检等政府机关事宜，以及审计等方面的对外相关工作；；
 2、做好凭证的编制、登记，做到帐证相符、帐表相符；根据计划、预算指标审核各类成本费用支出单据，并报告计划和预算的执行情况。负责会计档案的整理、装订工作。
 3、严格按照公司的财务制度审核单据、结算各项费用；
 4、协助审核记账凭证、核对调整账目、预算分析；
 5、公司财务费用的审核与报销，检查手续的完备性； 
 6、协助财务领导进行其他财务管理事务。
 任职要求：
 1、全日制统招本科及以上学历，会计、财务或相关专业；2年以上企业财务工作经验，具有初级会计师职称。 
 2、为人正直、责任心强、原则性强，沉稳、敬业、细致、耐心；
 3、熟练掌握财务软件和办公软件；
 4、有较强的沟通协调能力和学习能力。
工作地址：
北京市海淀区中关村北二条13号中科科仪
查看职位地图
**********
北京新叶能源科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电气/电力/水利
公司地址：
北京市海淀区中关村北二条13号
**********
环保销售
上海何如自控技术有限公司
五险一金绩效奖金定期体检员工旅游节日福利
**********
福利:
五险一金
绩效奖金
定期体检
员工旅游
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：销售代表
**********
岗位职责：

1、负责公司产品的销售及推广；

2、根据市场营销计划，完成部门销售指标；

3、开拓新市场，发展新客户，增加产品销售范围；

4、负责收集市场信息，掌握竞争对手的市场动态；

5、负责销售区域内销售活动的策划和执行，完成销售任务；

6、管理维护客户关系以及客户间的长期战略合作计划；

7、熟悉项目销售流程，招标流程者优先。



任职要求：

1、大专及以上学历，市场营销等相关专业；

2、1-2年以上销售行业工作经验，有大型设备、仪表仪器、工业自动化、环保等行业销售者优先；

3、善于学习，善于与客户沟通，具有良好的语言表达能力，具备责任感；

4、具备一定的市场分析及判断能力，良好的客户服务意识；

5、有团队协作精神，善于挑战；

6、能适应在外出差； 

7、一经录用公司提供优质的福利及广阔的发展空间。 

工作地址：
北京朝阳区北苑傲城融富中心b座
查看职位地图
**********
上海何如自控技术有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
环保
公司主页：
http://www.herocontrol.cn/
公司地址：
常州市武进高新区西湖路8号津通国际工业园10D
**********
供应商管理及化工设备仪器仪表-采购负责人
波露明(北京)科技有限公司
五险一金年底双薪绩效奖金加班补助包吃包住
**********
福利:
五险一金
年底双薪
绩效奖金
加班补助
包吃
包住
**********
职位月薪：6001-8000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：2人
职位类别：采购专员/助理
**********
我们并不以学历为判断你的唯一依据，但是你总要展示出，你与众不同的地方！

我们希望你，心态年青，有激情，热爱学习、勤奋、具有独立思考的能力，善于沟通，善解人意（能更好的理解问题和用户的需求），有坚持力，不抱怨。

波露明北京科技有限公司，是一个创业型的高科技公司，公司员工大都是年轻人，面向全国先进的技术研发领域，一起不断奔跑。波露明，也是一个学习型的公司，这里没有办公室政治，只有大家的理解和鼓励，支持和陪伴，不断学习，不断超越。

公司主要服务于中石油研究院、中石化研究院、中海油研究院、神华低碳研究院、神华宁煤研究院、大唐研究院、中科研究院、等多个大型国企、高校的重点实验室，主要为各大科研机构提供完整可靠的试验解决方案和试验设备，包括精馏、费托、加氢、烷基化、MTO、MTP、MTG、MTA、MTBE、DMMn、M2PX、MMA、SCR、固定床、流化床和移动床等。各个科研机构在未来的研发中，使用我们生产的各种类型试验设备，对能源进行更好的分析、研究、开发，对环保进行更好的开发、优化等。

我们的业务：
1.研发、设计并生产制造化工领域内，石油化工、加氢精制、润滑油和高级橡胶、煤制油、费托合成、甲醇应用、FCC流化床、固定床、加氢、脱氢、氧化还原、高压微反、聚合反应、费托合成、临界反应、烟气脱销、催化剂评价等中试小试实验装置。

2.根据用户需求，在其相关领域提供完整的解决方案，包括化工工艺、理论研究、化学计算、PID流程图、非标设计、设备选型、加工制造、自控设计、组装联调等。

3.致力于新材料的应用、新型催化剂评价及筛选，新工艺的研发等。


采购专员的岗位职责及要求：

该岗位虽然负责的工作内容较多，但也可以学习到多方面的知识，包括专业技术能力、事物的计划性、执行力、细节、谈判能力、理解力、领导力等，同时可以学习到财务知识、人力资源知识、采购技巧、涉外礼仪等。


作为采购的具体工作：
1、有能力主持（或协助采购主管）化工研发项目的采购全面工作；有石油化工医药的采购经验者优先。
2、根据项目进展计划和施工计划制订采购计划，并督导实施，管理并协助工厂库房的规范化，协助库房降低商品库存。
3、制定本部门的物资管理相关制度，使之规范化，指定采购部与项目部、设计部、商务部的沟通制度，协助各部门和供应商之间进行培训和协调等工作。
4、制定物资采购原则，筛选正规材料供应商，并进行合同签订、战略协议谈判，合同签订，支付款项，验收货品，催缴发票等。
5、做好采购的预测工作，根据资金运作情况，工程材料堆放程度，合理进行预先采购。
6、定期组织员工进行采购业务知识的学习，精通采购业务和技巧，培养采购人员廉洁奉公的情操。
7、遵守采购制度，杜绝不良行为的产生。
8、控制好物资批量进购，避开由于市场不稳定所带来的风险。
9、监控项目物流的状况，控制不合理的物资采购和消费。
10、进行采购收据的规范指导和审批工作，协助财会进行工程的审核及成本的控制。
11、严格按照公司采购流程统筹好各个生产资料、仪器仪表、机械零件、仪表电气等产品采购工作； 
12、积极密切与公司技术负责人、销售人员保持无障碍沟通，确保物品采购符合公司项目的特殊要求； 
13、在主管领导下做好采购谈判和采购合同签订工作；
14、负责开发优势供应商以及保持和维护合作供应商关系； 
15、负责组织供应商的考核与评价； 
16、保持学习的心态，随时了解各种采购物料的技术特点，技术创新，技术发展趋势等，通过对采购设备的学习和了解，持续不断地提高设备采购性价比； 
17、执行其他分派的采购、维修、调换、退换等工作； 
18、遵纪守法，遵守职业道德。

该岗位同时兼顾部分行政工作及采购工作，行政工作包括如下：
1.     协助处理办公室日常办公行政事务
2.     客户资料维护及各项交易文件处理。
3.     协助销售人员，负责产品的报价、合同制作、订单处理汇总、货期确认等；
4.     对产品每月、每季度、半季度、全年的销售数据的整理统计；

任职要求：


1、大专及以上学历；
2、具有良好计算机操作的能力，熟悉ERP或智能操作管理系统更好；
3、良好的沟通能力、良好的谈判能力和成本意识；
4、工作细致认真，责任心强；
5、有良好的职业道德和素养。

热爱化工、机械行业、爱学习，具有独立思考的能力，善于沟通，善解人意（能更好的理解问题和用户的需求），有没有学历都不重要（如果你爱学习，这里都可以学到），勤奋，不抱怨。


具备以下条件将更好：

－ 具有很强的责任心，对自己有比较高的要求

－ 具有完全主动的客户服务意识

－ 具有高效率的常规软件操作能力

－ 具有清晰的逻辑思路与趋势判断

－ 有机合成、化学工艺、精细化工专业

－ 有驾驶执照，并且可以熟练、安全的驾驶小型汽车。

工作地址：
北京市朝阳区安慧北里金利大厦
**********
波露明(北京)科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
石油/石化/化工
公司主页：
www.bloomingtech.net
公司地址：
北京市朝阳区安慧北里金利大厦
查看公司地图
**********
客服专员
润柏斯特(北京)环保科技发展有限公司
创业公司年底双薪绩效奖金带薪年假交通补助员工旅游
**********
福利:
创业公司
年底双薪
绩效奖金
带薪年假
交通补助
员工旅游
**********
职位月薪：4001-6000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：2人
职位类别：客户服务专员/助理
**********
Skills, Qualifications, Experience技能，资格，经验:
 学历：大专以上，正规全日制院校毕业，专业不限。
工作经验：两年及以上工作经验，有客服和电话销售经验优先，
普通话标准，口齿伶俐，语言表达能力强，擅于沟通;
思维敏捷，有良好的销售服务意识，工作耐心细致;
勤奋敬业、责任心强，思路清晰; 有耐心及责任心;
适应压力下工作，有团队合作精神；
熟悉办公软件和网络工具。
   工作地址：
顺义区顺平路阳光加油站南700米院内
查看职位地图
**********
润柏斯特(北京)环保科技发展有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
环保
公司地址：
顺义区顺平路阳光加油站南700米院内
**********
外贸专员 急聘（上市公司 五险一金）
北京通蓝海科技股份有限公司
绩效奖金带薪年假加班补助五险一金住房补贴房补交通补助节日福利
**********
福利:
绩效奖金
带薪年假
加班补助
五险一金
住房补贴
房补
交通补助
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：外贸/贸易专员/助理
**********
岗位职责
1、负责公司产品的销售及推广；
2、根据市场营销计划，完成部门销售指标；
3、开拓新市场,发展新客户,增加产品销售范围；

任职资格
1、熟悉外贸，具有较强的英语听、写 读 说 能力，沟通能力强；
2、1年以上外贸销售行业工作经验。有建材销售经验者优先。
3、性格外向、反应敏捷、表达能力强，具有较强的沟通能力及交际技巧，具有亲和力；
4、具备一定的市场分析及判断能力，良好的客户服务意识；
5、有责任心，能承受较大的工作压力。
 工作时间：周一至周五的早9:00至晚5:30，周六日全休，完全按照国家法定节假日休。
待遇：五险一金，交通补助，住房补贴，加班补贴，带薪年假，季度奖金，节日福利等。
本公司每年可以有一次外出旅游的机会，工作氛围比较和谐轻松，望广大的有志之士加入我们，共同奋斗！
工作地址：
北京市朝阳区安翔北里甲11号北京创业大厦B座1010室
**********
北京通蓝海科技股份有限公司
公司规模：
20-99人
公司性质：
股份制企业
公司行业：
房地产/建筑/建材/工程
公司主页：
www.3dboard.com.cn，www.3dwallpanel.net
公司地址：
北京市朝阳区安翔北里甲11号 北京创业大厦B座1010室
查看公司地图
**********
化工工艺、设计及研发、销售项目经理
波露明(北京)科技有限公司
五险一金年底双薪绩效奖金年终分红加班补助包住餐补带薪年假
**********
福利:
五险一金
年底双薪
绩效奖金
年终分红
加班补助
包住
餐补
带薪年假
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：3人
职位类别：化工项目管理
**********
我们并不是以学历为判断你的唯一依据，但是你总要展示出，你与众不同的地方！

我们希望你，心态年青，有激情，热爱学习、勤奋、具有独立思考的能力，善于沟通，善解人意（能更好的理解问题和用户的需求），有坚持力，不抱怨。

波露明北京科技有限公司，是一个创业型的高科技公司，公司员工大都是年轻人，面向全国先进的技术研发领域，一起不断奔跑。波露明，也是一个学习型的公司，这里没有办公室政治，只有大家的理解和鼓励，支持和陪伴，不断学习，不断超越。

公司主要服务于中石油研究院、中石化研究院、中海油研究院、神华低碳研究院、神华宁煤研究院、大唐研究院、中科研究院、等多个大型国企、高校的重点实验室，主要为各大科研机构提供完整可靠的试验解决方案和试验设备，包括精馏、费托、加氢、烷基化、MTO、MTP、MTG、MTA、MTBE、DMMn、M2PX、MMA、SCR、固定床、流化床和移动床等。各个科研机构在未来的研发中，使用我们生产的各种类型试验设备，对能源进行更好的分析、研究、开发，对环保进行更好的开发、优化等。

我们的业务：
1.研发、设计并生产制造化工领域内，石油化工、加氢精制、润滑油和高级橡胶、煤制油、费托合成、甲醇应用、FCC流化床、固定床、加氢、脱氢、氧化还原、高压微反、聚合反应、费托合成、临界反应、烟气脱销、催化剂评价等中试小试实验装置。

2.根据用户需求，在其相关领域提供完整的解决方案，包括化工工艺、理论研究、化学计算、PID流程图、非标设计、设备选型、加工制造、自控设计、组装联调等。

3.致力于新材料的应用、新型催化剂评价及筛选，新工艺的研发等。


岗位职责：
1、承担项目设计、PID的绘制、核心设备选型、工艺计算、商务沟通交流、报价等
2、投标方案的制作、参与投标，参与流程图的设计，物料平衡计算，化工原理分析等工作
3、参与核心设备选型、仪表选型、非标设计、数据表、控制系统选型、布线图等详细设计文件
4、后续项目跟进，进度控制，采购技术支持，指导或参与设备安装、现场调试
5、编写仪表采购技术规格书，参与供货商调研等工作
任职要求：
1、石油和化工机械或相关专业，大专及以上学历；
2、有一年以上工艺设计经验，熟悉行业标准和设计规范，有设计院背景者优先；
3、从事过石油化工、煤化工设计和有相关设计经验者优先考虑 ；
4、具有研发企业工作经验者优先；
5、熟练使用CAD、SolidWorks制图，掌握设备计算软件及office办公软件；
6、具有独立解决问题的能力，踏实肯干，乐于学习，具有良好的团队意识和企业忠诚度 。




你将会得到的：
丰厚的薪酬，住宿保证，伙食补助，交通补助，通讯补助，社会保险，统一服装，免费体检，带薪年休假，旅游机会，过节费，年底双薪（需评测）。

还有很多，你将学习到
各大院校的教授级专家支持，学习研究院研究领域的创新，几十种化学反应机理，各种化学实验模型，化工工艺需求分析过程，化工行业宝贵经验，PID流程图技巧，非标设计加工经验，设备安装调试经验，催化剂评价筛选经验，和各种化工装置中的独特工艺参数经验等。

所以
具备以下条件将更好！
－ 超强的责任心
－ 完全主动的客户服务意识
－ 高效率的动手工作和设备操作能力
－ 清晰的设计思路与逻辑
－ 有机合成、化学工艺、精细化工等专业
－ 有驾驶证、英语很厉害

波露明（北京）科技有限公司成立于1998年8月，注册资金2000万元，是一家专业从事石油、石化、化工、煤化工、能源、环保、医药等行业的实验室技术服务、中小型试验装置、模试装置以及小型工业装置设计、研发的科技公司，公司积极开拓国内外相关领域的产品渠道，与美国Apache 公司、美国Dynatrol、Swagelok、BROOKS、TESCOM、西门子、霍尼韦尔等多家国际公司建立深厚的合作关系。
公司总部位于北京市朝阳区慧忠北里金利大厦4层，生产基地位于北京市顺义区彩祥东路10号彩园工业区标准厂房工业园6号厂房，现拥有2个独立厂房，总面积达2000余平方米。公司依托于中石油、中石化、中海油、神华低碳、神华宁煤、大唐、中科院、等多个大型国企、高校的重点实验室等重点客户，现逐步发展成了面向全国的专业实验设备供应商。
公司人才结构合理，涵盖了化工工艺、化工机械设计、控制系统、设备选型采购、计算机等专业领域。公司拥有完整的研发、设计、生产、安装及售后服务体系，为企业发展提供了优质的服务。
十余年来，公司一直秉承以用户需求为核心，以优质、专业的服务赢得了众多企业的信赖和好评，与企业之间搭建了一个坚实持久的合作平台。我们相信，通过不懈的努力和追求，一定能成为更多企业信赖的长期合作伙伴。

感谢你阅读到这里，请关注微信号BloomingTech，留言“招聘”，波露明，期待和你一起共创未来。
                   
工作地址：
北京市朝阳区大屯北路金利大厦
查看职位地图
**********
波露明(北京)科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
石油/石化/化工
公司主页：
www.bloomingtech.net
公司地址：
北京市朝阳区安慧北里金利大厦
**********
华北大区市场销售经理
上海中林给水材料有限公司
五险一金绩效奖金年终分红股票期权全勤奖节日福利弹性工作
**********
福利:
五险一金
绩效奖金
年终分红
股票期权
全勤奖
节日福利
弹性工作
**********
职位月薪：10000-15000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：2人
职位类别：销售经理
**********
工作职责：
1.完成区域内季/年度销售任务。
2.收集市场竞争对手相关信息进行分析汇总。
3.开发区域内潜在新客户，了解客户需求后为客户选型报价。
4.维护区域内历史老客户，保持有序的沟通联系。了解老客户的近期项目动向，挖掘新的销售机会。
5.负责区域内的项目报备，进度跟踪，定价投标，订单跟踪，尾款收款等工作。
6.直属领导交待的其它相关工作。
任职资格：
任职要求：
1.理工科大专以上学历或市场营销专业，机械类专业可放宽至中技学历。
2.熟练使用EXCEL，WORD，PPT等办公软件。
3.泵阀管件行业从业3年以上，有环保、石油、化工行业销售经验者优先。
工作地址
北京市,天津市,山东省.河北省,山西省,内蒙古自治区的一部分皆可。
在北京有办公室



工作地址：
上海市浦东新区东方路738号裕安大厦2409、2410、2411室
查看职位地图
**********
上海中林给水材料有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
加工制造（原料加工/模具）
公司主页：
http://www.shzlgs.com
公司地址：
上海市浦东新区东方路738号裕安大厦2409、2410、2411室
**********
技术部经理
北京沃尔德斯水务科技有限公司
五险一金绩效奖金餐补带薪年假节日福利
**********
福利:
五险一金
绩效奖金
餐补
带薪年假
节日福利
**********
职位月薪：10001-15000元/月 
工作地点：北京-门头沟区
发布日期：最新
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：1人
职位类别：水处理工程师
**********
职位描述  
1、主持企业的技术管理工作，不断推进企业的技术进步，总管公司技术系统； 
2、负责公司工艺技术创新与研发，新产品研发前的調研、市场分析； 
3、负责水处理项目工艺总图的设计和全套图纸的审核，环保设备购置的把关； 
4、对工程现场施工给予技术指导； 
5、负责新技术、新工艺、新设备、新材料及先进科技成果的推广和应用。
任职资格：
1、本科或以上学历，环境工程相关专业，年龄35——50岁；
2、在污水处理领域有8年以上工作经验，熟悉通用污水处理工艺，对污水处理行业市场及技术发展有较为全面的理解；
3、担任技术负责人3年以上，有高级技术职称者、有设计院工作经验者优先考虑。

 以上职位供职于北京沃尔德斯水务科技有限公司
公司提供良好的福利待遇：五险一金、餐补、激励性奖金、年休假、年终奖、股权期权等长远激励，达到既定条件员工可办理北京居住证，满足条件的单身员工可安排宿舍； 
我们的基本人才观是：德才并举，以德为先，敬业为本，团队第一。我们不以伯乐慧眼识人，只任骏马竞赛驰骋。
公司提供四个领域的职业发展路径：专业/技术发展路径、项目管理发展路径、职能管理发展路径、综合管理发展路径，各种不同的人才都能找到适合自身的职业发展路径，并且能在不同路径之间循环转变、螺旋式上升。
 这里，既需要环保圈内有经验但仍然渴望更大发展空间的人才，也需要没有太多经验但强烈渴望在创新时代中脱颖而出的年轻人；
 这里，拥有人才和年轻人更需要的成长和舞台，拥有更具竞争力的回报和福利、中长期成长战略以及中长期激励机制；
 这里，追求公司实现有价值的持续增长，追求创业团队实现有形和无形的增值；
只要你，坚信自己拥有非常的成长理想和欲望，并且愿意脚踏实地的去努力，相信你一定能在沃尔德斯的舞台上挥洒汗水和青春，实现梦想！
  
北京沃尔德斯水务科技有限公司
网站：http://www.bjworlds.cn/
地址：北京市门头沟区石龙工业区雅安路6号利德衡大厦A座6层
邮箱：hr@bjworlds.com
北京公司电话：010-52740855/13501025478
宜兴公司电话：0510-80785201

工作地址：
北京市门头沟区石龙工业区雅安路6号利德衡大厦A座6层
查看职位地图
**********
北京沃尔德斯水务科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
环保
公司主页：
http://www.bjworlds.cn/
公司地址：
北京市门头沟区石龙工业区雅安路6号利德衡大厦A座6层
**********
煤化工、石油炼化、精细化工、研发工程师
波露明(北京)科技有限公司
五险一金年底双薪绩效奖金包吃包住通讯补贴定期体检
**********
福利:
五险一金
年底双薪
绩效奖金
包吃
包住
通讯补贴
定期体检
**********
职位月薪：8001-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：5人
职位类别：化工研发工程师
**********
波露明北京科技有限公司，是一个创业型的高科技公司，公司员工大都是年轻人，面向全国先进的技术研发领域，一起不断奔跑。
波露明，也是一个学习型的公司，这里没有办公室政治，只有大家的理解和鼓励，支持和陪伴，不断学习，不断超越。
请关注微信号BloomingTech，留言“招聘”
公司主要服务于中石油研究院、中石化研究院、中海油研究院、神华研究院等多个大型国企的化工研究院，主要为各大科研机构提供完整可靠的试验解决方案和试验设备。各个科研机构在未来的研发中，使用我们生产的各种类型试验设备，对能源进行更好的分析、研究、开发，对环保进行更好的开发、优化等。
我们的业务：
1.研发、设计并生产制造化工领域内，煤制油、MTO、FCC流化床、固定床、加氢、脱氢、氧化还原、高压微反、聚合反应、费托合成、临界反应、烟气脱销、催化剂评价等中试小试实验装置。

2.根据用户需求，在其相关领域提供完整的解决方案，包括化工工艺、理论研究、化学计算、PID流程图、非标设计、设备选型、加工制造、自控设计、组装联调等。

3.致力于新材料的应用、新型催化剂评价及筛选，新工艺的研发等。



岗位要求：

热爱化工行业、具有独立思考的能力，善于沟通，善解人意（能更好的理解问题和用户的需求），具备不断学习的能力，勤奋，不抱怨。

你可能会得到的：

几十种化学反应机理，各种化学实验模型，化工工艺需求分析过程，化工行业宝贵经验，PID流程图技巧，非标设计加工经验，设备安装调试经验，催化剂评价筛选经验，和各种化工装置中的独特工艺参数经验等。


工作职责：

1、承担项目设计、投标方案的制作，参与流程图的设计，化工原理分析等工作

2、参与设备选型、仪表选型、非标设计、数据表、布线图等详细设计文件

2、指导或参与设备安装、现场调试

3、编写仪表采购技术规格书，参与供货商调研等工作


具备以下条件将更好！

－ 超强的责任心

－ 完全主动的客户服务意识

－ 高效率的常规软件操作能力

－ 清晰的设计思路与逻辑

－ 有机合成、化学工艺、精细化工等专业
     波露明（北京）科技有限公司成立于1998年8月，注册资金2000万元，是一家专业从事石油、石化、化工、煤化工、能源、环保、医药等行业的中小型试验装置、模试装置以及小型工业装置的科技公司，公司积极开拓国内外相关领域的产品渠道，与美国Apache 公司、美国Dynatrol、英国MMC 公司等多家国际公司建立深厚的合作关系。
公司总部位于北京市朝阳区慧忠北里金利大厦4层，生产基地位于北京市顺义区彩祥东路10号彩园工业区标准厂房工业园6号厂房，现拥有2个独立厂房，总面积达2000余平方米。公司依托于中石油、辽河油田、大庆油田、油田设计院、中国石油和化工协会、煤化工研究院等重点客户，现逐步发展成了面向全国的专业实验设备供应商。
公司人才结构合理，涵盖了化工工艺、化工机械设计、计算机、自动化控制等专业领域。公司拥有完整的研发、设计、生产、安装及售后服务体系，为企业发展提供了优质的服务。
十余年来，公司一直秉承以用户需求为核心，以优质、专业的服务赢得了众多企业的信赖和好评，与企业之间搭建了一个坚实持久的合作平台。我们相信，通过不懈的努力和追求，一定能成为更多企业信赖的长期合作伙伴。
                   工作地址
北京市顺义区彩祥东路10号彩园工业区标准厂房工业园6号厂房

工作地址：
北京市顺义区彩祥东路10号彩园工业区标准厂房工业园6号厂房
查看职位地图
**********
波露明(北京)科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
石油/石化/化工
公司主页：
www.bloomingtech.net
公司地址：
北京市朝阳区安慧北里金利大厦
**********
销售工程师（北京分公司）
上海同臣环保有限公司
五险一金绩效奖金通讯补贴带薪年假定期体检员工旅游节日福利
**********
福利:
五险一金
绩效奖金
通讯补贴
带薪年假
定期体检
员工旅游
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：北京-朝阳区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：3人
职位类别：销售工程师
**********
任职要求：
1、男女不限，大专以上学历，环境工程或市场营销相关专业
2、熟练操作office办公软件
3、受过市场营销等方面的培训
4、较强的观察力和应变能力、良好的判断力和沟通能力、敬业、勤奋和责任心
5、品德正直、较强的抗压能力，能认同、融入公司的企业文化
6、有水处理设备、成套机械设备或环保行业销售工作经验优先考虑
岗位职责：
1、负责地区水处理设备的一线销售，保证销售目标的达成
2、跟踪地区设计院所、城建院、环科院、市政院、煤炭院、化工院等，做好人际关系
3、经销商的发展与管理
4、项目的前期跟踪、投标、合同及技术协议的签订
5、所在区域的品牌宣传、院所的技术交流，区域展会及产品发布等宣传工作
6、协助办事处经理共同完成销售任务与货款回收。


可登录公司网站查看公司产品相关信息：www.techase.com

员工福利：五险一金、生日礼品、节日红包、集体旅游、年度体检、拓展培训、节日活动等；
薪酬待遇：我们的目标是在与其他同行业相比较时，我们的员工拥有更具竞争力的薪水；
休息休假：严格执行劳动法规定的休息休假制度。除双休日、国家法定假日外，公司员工还可享受年假、婚假等带薪假期；
培训发展：公司内部有各项培训，选派优秀员工参加社会培训，同济大学专业技术培训等；
激励策略：符合公司条件的可以申请同臣环保“无息房贷计划”。
工作地址
北京市朝阳区景华南街1号旺座中心东塔0815室
欢迎扫一扫关注同臣环保官方微信，查看历史消息以了解更多公司信息。微信号：techase
同臣环保是创于上海，源于同济的国家高新技术企业、上海市科技小巨人企业和AAA级守合同重信用企业。同臣环保以“创新，解决环境问题”为使命，作为行业领先的污水、污泥处理设备及技术服务提供商，核心产品技术包括叠螺式污泥脱水机、超高压弹性压榨机和竖片纤维滤布滤池等产品及污水和污泥处理、河湖综合治理等系统解决方案。
      同臣环保倡导具有创业和分享精神的企业文化，致力于成为最具竞争力且令人尊敬的环保企业，一个能激发创造力、充满激情和梦想的创业平台。

工作地址：
北京市朝阳区景华南街1号旺座中心东塔0815室
**********
上海同臣环保有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
环保
公司主页：
http://www.techase.com
公司地址：
上海市杨浦区中山北二路1121号同济科技大厦3楼
查看公司地图
**********
水处理药剂产品代表
科氏(北京)滤膜科技有限公司
通讯补贴年底双薪绩效奖金年终分红交通补助带薪年假节日福利员工旅游
**********
福利:
通讯补贴
年底双薪
绩效奖金
年终分红
交通补助
带薪年假
节日福利
员工旅游
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：10人
职位类别：产品专员/助理
**********
岗位职责：
1、 反渗透药剂及循环水药剂的市场开发与销售
2、 制定本区域营销计划、分解销售目标
3、 配合全国各地代理商开展工作，完成公司业务目标
4、 直接参与、主持重要客户的业务技术交流、谈判及成交
5、 督导代理商及老客户业务开展工作，落实本区域货款回收
6、 控制所辖区域相互竞争、协调客户反馈信息及现场业主等问题
任职要求：
1、专科以上学历；环境工程、给排水、电厂化学、化工工艺等相关专业；
2、1年以上销售工作经验；
3、了解、熟悉反渗透膜/纳滤膜/超滤膜等水处理系统设计者优先考虑；
4、善于掌握市场信息，具有敏锐的市场观察力、判断力；
5、能够独立组织协调工作，能够适应出差。
工作地址：
大兴区天华大街2号
**********
科氏(北京)滤膜科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.kochmembrane.cn/
公司地址：
大兴区庆祥南路29号
查看公司地图
**********
水处理药剂渠道专员
科氏(北京)滤膜科技有限公司
通讯补贴年底双薪绩效奖金年终分红交通补助带薪年假节日福利员工旅游
**********
福利:
通讯补贴
年底双薪
绩效奖金
年终分红
交通补助
带薪年假
节日福利
员工旅游
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：10人
职位类别：渠道/分销专员
**********
岗位职责：
1、 反渗透药剂及循环水药剂的市场开发与销售。
2、 制定本区域营销计划、分解销售目标。
3、 配合全国各地代理商开展工作，完成公司业务目标。
4、 直接参与、主持重要客户的业务技术交流、谈判及成交。
5、 督导代理商及老客户业务开展工作，落实本区域货款回收。
6、 控制所辖区域相互竞争、协调客户反馈信息及现场业主等问题。
任职要求：
1、环境工程、给排水、电厂化学、化工工艺等相关专业；
2、1年以上销售工作经验；专科以上学历；
3、了解、熟悉反渗透膜/纳滤膜/超滤膜等水处理系统设计者优先考虑；
4、善于掌握市场信息，具有敏锐的市场观察力、判断力；
5、能够独立组织协调工作，能够适应出差。
工作地址：
大兴区天华大街2号
**********
科氏(北京)滤膜科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.kochmembrane.cn/
公司地址：
大兴区庆祥南路29号
查看公司地图
**********
园艺师
北京天朗科隆生态科技有限公司
创业公司五险一金绩效奖金包吃包住弹性工作员工旅游节日福利
**********
福利:
创业公司
五险一金
绩效奖金
包吃
包住
弹性工作
员工旅游
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：硕士
招聘人数：2人
职位类别：园艺师
**********
   岗位职责：    
              1.温室内的生产种植管理，制定作物栽培计划，对实施结果进行总结分析，达成种植目标。
              2.负责苗木、花卉等植物的种植及管理；并能编写植物和花卉生长的习性和生长周期。
              3.对苗木、花卉质量、成本率进行有效的控制；熟悉苗木、花卉品种特性和栽培、移植流程并擅长园林植物培育。
              4.负责制定苗木、花卉等植物的种植方案及防治病虫害的管理办法。熟练掌握苗木病虫害防治、苗木修剪造型、杆插、嫁接等技术。
              5.负责生态办公室植物日常维护，浇水，修剪等；负责园艺课程讲师，给顾客讲解植物的维护基本知识；
              6.负责公司或展区内绿植墙的日常维护，并负责研发植物和花卉需求的营养液。
     任职要求：   
             1、园艺、农学相关专业；硕士以上学历。对于植物的管理养护非常了解，服从公司工作安排；
             3、喜欢植物，对植物养护、花艺技术有浓厚的兴趣并非常了解，学习能力强；英语四级以上，能用英文阅读和沟通。
             4.熟悉无土栽培技术，专业功底扎实。热爱园艺事业，品行良好，具有钻研精神。
             5、有良好的职业道德和素养，吃苦耐劳，有耐心及责任心。具备优秀的沟通能力，带领团队协作的精神。
工作地址：
北京市通州区九棵树西路90号弘祥1979文化创意产业园B座8373
查看职位地图
**********
北京天朗科隆生态科技有限公司
公司规模：
20人以下
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://bjtlklcom.s300.gainda.net/
公司地址：
北京市通州区台湖镇口子村新村委会东10米
**********
化工研发、化工分析、化工科研操作
波露明(北京)科技有限公司
五险一金绩效奖金包吃包住餐补通讯补贴带薪年假员工旅游
**********
福利:
五险一金
绩效奖金
包吃
包住
餐补
通讯补贴
带薪年假
员工旅游
**********
职位月薪：6001-8000元/月 
工作地点：北京-顺义区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：30人
职位类别：化学操作
**********
我们并不是以学历为判断你的唯一依据，但是你总要展示出，你与众不同的地方！

我们希望你，心态年青，有激情，热爱学习、勤奋、具有独立思考的能力，善于沟通，善解人意（能更好的理解问题和用户的需求），有坚持力，不抱怨。


波露明北京科技有限公司，是一个创业型的高科技公司，公司员工大都是年轻人，面向全国先进的技术研发领域，一起不断奔跑。波露明，也是一个学习型的公司，这里没有办公室政治，只有大家的理解和鼓励，支持和陪伴，不断学习，不断超越。
请关注微信号BloomingTech，留言“招聘”
公司主要服务于中石油研究院、中石化研究院、中海油研究院、神华研究院等多个大型国企的化工研究院，主要为各大科研机构提供完整可靠的试验解决方案和试验设备。各个科研机构在未来的研发中，使用我们生产的各种类型试验设备，对能源进行更好的分析、研究、开发，对环保进行更好的开发、优化等。

我们的业务：
1.研发、设计并生产制造化工领域内，煤制油、MTO、FCC流化床、固定床、加氢、脱氢、氧化还原、高压微反、聚合反应、费托合成、临界反应、烟气脱销、催化剂评价等中试小试实验装置。

2.根据用户需求，在其相关领域提供完整的解决方案，包括化工工艺、理论研究、化学计算、PID流程图、非标设计、设备选型、加工制造、自控设计、组装联调等。

3.致力于新材料的应用、新型催化剂评价及筛选，新工艺的研发等。


公司待遇及福利
1，部分员工公司安排住宿
2，公司有食堂，可以保证三餐
3，有五险及通讯补助
4，如需加班，有加班补助

岗位职责：
1、对研发的项目进行工艺研究，对分析结果进行计算和汇总
2、对每天的研发任务进行梳理，做出设备运行计划
3、对每天的研发任务进行设备操作，包括装卸催化剂、装卸原料、对设备参数进行调整，对数据进行记录
4、保证物料的用料进度，及时对物料使用量提出要求
5、装置运行调试，临时管线连接，保证设备运行，样品取样，实验分析仪器操作
6、对试验设备区进行巡视，巡检
7、对一般性故障进行维护和维修

任职要求：
1、石油和化工机械或相关专业，大专及以上学历；
2、有一年以上工作经验，熟悉化工行业标准和设计规范，有化工厂工作背景者优先；
3、从事过石油化工、煤化工设备设计、生产、操作经验者优先考虑 ；
4、熟练使用CAD、SolidWorks制图，掌握设备计算软件及office办公软件；
5、具有独立解决问题的能力，踏实肯干，乐于学习，具有良好的团队意识和企业忠诚度 。


以下条件满足更好：
脚踏实地、爱学习，具有独立思考的能力，善于沟通，（能更好的理解问题和用户的需求），有没有学历都不重要（这里可以学到），勤奋，不抱怨。

－ 具有超强的责任心

－ 具有完全主动的客户服务意识

－ 具有高效率的常规软件操作能力

－ 具有清晰的设计思路与逻辑

－ 有机合成、化学工艺、精细化工等专业
波露明（北京）科技有限公司成立于1998年8月，注册资金2000万元，是一家专业从事石油、石化、化工、煤化工、能源、环保、医药等行业的中小型试验装置、模试装置以及小型工业装置的科技公司，公司积极开拓国内外相关领域的产品渠道，与美国Apache 公司、美国Dynatrol、英国MMC 公司等多家国际公司建立深厚的合作关系。
公司总部位于北京市朝阳区慧忠北里金利大厦4层，生产基地位于北京市顺义区彩祥东路10号彩园工业区标准厂房工业园6号厂房，现拥有2个独立厂房，总面积达2000余平方米。公司依托于中石油、辽河油田、大庆油田、油田设计院、中国石油和化工协会、煤化工研究院等重点客户，现逐步发展成了面向全国的专业实验设备供应商。
公司人才结构合理，涵盖了化工工艺、化工机械设计、计算机、自动化控制等专业领域。公司拥有完整的研发、设计、生产、安装及售后服务体系，为企业发展提供了优质的服务。
十余年来，公司一直秉承以用户需求为核心，以优质、专业的服务赢得了众多企业的信赖和好评，与企业之间搭建了一个坚实持久的合作平台。我们相信，通过不懈的努力和追求，一定能成为更多企业信赖的长期合作伙伴。
www.bloomingtech.net

工作地址：
北京市顺义区彩祥东路10号彩园工业区标准厂房工业园6号厂房
查看职位地图
**********
波露明(北京)科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
石油/石化/化工
公司主页：
www.bloomingtech.net
公司地址：
北京市朝阳区安慧北里金利大厦
**********
生产辅助
北京环标科创环境科技发展有限责任公司
五险一金绩效奖金餐补带薪年假定期体检
**********
福利:
五险一金
绩效奖金
餐补
带薪年假
定期体检
**********
职位月薪：4001-6000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：2人
职位类别：普工/操作工
**********
岗位职责：
1、按照要求完成试剂类产品的生产配制，灌封、分装、贴签、运输等工作；
2、负责生产灌封设备的使用、维护和保养；
3、负责工作场所清洁，配制用容器具、实验用品、包装材料的清洗；
4、协助完成生产样品、各种物料、试剂等日常存放与管理；
5、配合其他部门工作及完成上级交办的其他任务。

任职要求：
1、大专及以上学历；
2、45周岁以下，身体健康、吃苦耐劳，有较好的工作责任心，以及沟通、合作能力；
3、有制药、化工等生产设备操作经验者优先考虑。
工作地址：
北京市朝阳区育慧南路1号
**********
北京环标科创环境科技发展有限责任公司
公司规模：
20-99人
公司性质：
国企
公司行业：
环保
公司地址：
北京市朝阳区育慧南路1号
**********
非标设计师、机械设计师
波露明(北京)科技有限公司
五险一金绩效奖金包吃包住餐补通讯补贴带薪年假员工旅游
**********
福利:
五险一金
绩效奖金
包吃
包住
餐补
通讯补贴
带薪年假
员工旅游
**********
职位月薪：6000-12000元/月 
工作地点：北京-昌平区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：3人
职位类别：机械工程师
**********
波露明北京科技有限公司，是一个创业型的高科技公司，公司员工大都是年轻人，面向全国先进的能源技术研发领域，让我们一起不断奔跑。
波露明，也是一个学习型的公司，这里没有办公室政治，只有大家的理解和鼓励，支持和陪伴，不断学习，不断超越。
请关注微信号BloomingTech，留言“招聘”
公司主要服务于中石油研究院、中石化研究院、中海油研究院、神华低碳研究院、神华宁煤研究院、大唐研究院、中科院、等多个大型国企、高校的重点实验室，主要为各大科研机构提供完整可靠的试验解决方案和试验设备，包括精馏、费托、加氢、烷基化、MTO、MTP、MTG、MTA、MTBE、DMMn、M2PX、MMA、SCR、固定床、流化床和移动床等。各个科研机构在未来的研发中，使用我们生产的各种类型试验设备，对能源进行更好的分析、研究、开发，对环保进行更好的开发、优化等。

我们的业务：
1.研发、设计并生产制造化工领域内，石油化工、加氢精制、润滑油和高级橡胶、煤制油、费托合成、甲醇应用、FCC流化床、固定床、加氢、脱氢、氧化还原、高压微反、聚合反应、费托合成、临界反应、烟气脱销、催化剂评价等中试小试实验装置。

2.根据用户需求，在其相关领域提供完整的解决方案，包括化工工艺、理论研究、化学计算、PID流程图、非标设计、设备选型、加工制造、自控设计、组装联调等。

3.致力于新材料的应用、新型催化剂评价及筛选，新工艺的研发等。
岗位职责：
1、从事压力容器设计，完成设备施工设计；
2、熟悉压力容器设计GB150规范、相关知识及标准；
3、参与项目的设计管理、指导和校审工作；
4、熟练使用各类二维三维制图软件，会使用Ansys，Aboquas等有限元分析软件。负责非标设备的详细设计、施工图及竣工图设计；
5、负责装置的三维布局设计，框架加工图设计。
6、具有高级工程师技术职称，持有A类（含A1、A2、A3）压力容器设计审批证书优先录用；

任职要求：
1、石油和化工机械或相关专业，大专及以上学历；
2、有压力容器设计经验，熟悉GB，ASME等设计规范，有设计院背景者优先；
3、从事过油气处理设备设计和有相关设备设计经验者优先考虑 ；
4、具有压力容器制造企业设计工作经验者优先；
4、熟练使用CAD、SolidWorks制图，掌握设备计算软件及office办公软件；
5、具有独立解决问题的能力，踏实肯干，乐于学习，具有良好的团队意识和企业忠诚度 。

我们并不是以学历为判断你的唯一依据，但是你总要展示出，你与众不同的地方！

我们希望你，心态年青，有激情，热爱学习、勤奋、具有独立思考的能力，善于沟通，善解人意（能更好的理解问题和用户的需求），有坚持力，不抱怨。

你将会得到的：
丰厚的薪酬，住宿保证，伙食补助，交通补助，通讯补助，社会保险，统一服装，免费体检，带薪年休假，旅游机会，过节费，年底双薪（需评测）。

还有很多，你将学习到
各大院校的教授级专家支持，学习研究院研究领域的创新，几十种化学反应机理，各种化学实验模型，化工工艺需求分析过程，化工行业宝贵经验，PID流程图技巧，非标设计加工经验，设备安装调试经验，催化剂评价筛选经验，和各种化工装置中的独特工艺参数经验等。

所以
具备以下条件将更好！
－ 超强的责任心
－ 完全主动的客户服务意识
－ 高效率的动手工作和设备操作能力
－ 清晰的设计思路与逻辑
－ 有机合成、化学工艺、精细化工等专业
－ 有驾驶证、英语很厉害


波露明（北京）科技有限公司成立于1998年8月，注册资金2000万元，是一家专业从事石油、石化、化工、煤化工、能源、环保、医药等行业的实验室技术服务、中小型试验装置、模试装置以及小型工业装置设计、研发的科技公司，公司积极开拓国内外相关领域的产品渠道，与美国Apache 公司、美国Dynatrol、Swagelok、BROOKS、TESCOM、西门子、霍尼韦尔等多家国际公司建立深厚的合作关系。
公司总部位于北京市朝阳区慧忠北里金利大厦4层，生产基地位北京市顺义区彩祥东路10号彩园工业区标准厂房工业园6号厂房，现拥有2个独立厂房，总面积达2000余平方米。公司依托于中石油、中石化、中海油、神华低碳、神华宁煤、大唐、中科院、等多个大型国企、高校的重点实验室等重点客户，现逐步发展成了面向全国的专业实验设备供应商。
公司人才结构合理，涵盖了化工工艺、化工机械设计、控制系统、设备选型采购、计算机等专业领域。公司拥有完整的研发、设计、生产、安装及售后服务体系，为企业发展提供了优质的服务。
十余年来，公司一直秉承以用户需求为核心，以优质、专业的服务赢得了众多企业的信赖和好评，与企业之间搭建了一个坚实持久的合作平台。我们相信，通过不懈的努力和追求，一定能成为更多企业信赖的长期合作伙伴。

感谢你阅读到这里，请关注微信号BloomingTech，留言“招聘”，波露明，期待和你一起共创未来。
                   
公司福利：
1、为员工提供五险，年终奖金，优秀员工等奖励；
2、员工可享受带薪年假、带薪病假、法定假日等；
3、公司提供为员工提供免费三餐、话费补助，员工还可享受公司提供的定期体检和不定期的员工旅游；
4、多种形式的岗位培训和晋升空间。

工作地点：
北京市顺义区彩祥东路10号彩园工业区标准厂房工业园6号厂房

工作地址：
北京市顺义区彩祥东路10号彩园工业区标准厂房工业园6号厂房
查看职位地图
**********
波露明(北京)科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
石油/石化/化工
公司主页：
www.bloomingtech.net
公司地址：
北京市朝阳区安慧北里金利大厦
**********
销售行政助理【战略性新兴产业/上市公司】
北京威派格科技发展有限公司
五险一金绩效奖金交通补助通讯补贴带薪年假定期体检员工旅游节日福利
**********
福利:
五险一金
绩效奖金
交通补助
通讯补贴
带薪年假
定期体检
员工旅游
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：1人
职位类别：销售行政专员/助理
**********
一个站在“互联网+”风口上的行业 
工业互联，智联供水新型设备引领产业升级
智慧水务，城市供水管理平台提升水务运营
 一家引领行业发展的企业 
承接国家“十二五”水专项课题
五项建设部行业标准/一项国家标准
二次供水领域74项专利
国际工业互联联盟IIC成员
西门子SIEMENS战略合作伙伴
中国首个工程级水利综合实验平台
工业4.0标准的全新智能化工厂
 岗位职责：
1、协助总经理作好经营服务各项管理并督促、检查落实贯彻执行情况；
2、协助总经理进行团队管理、了解部门经营管理情况并提出处理意见或建议；
3、协助总经理完成数据统计、PPT汇报等文件的制作；
4、协助总经理发起发票报销、费用申请并进行流程跟踪反馈；
5、协助人事经理进行本公司内人事相关工作，如招聘，培训，员工关注等。
6、协调本部门与其他部门日常会议室、电话会议等资源。
 任职要求：
1、统招本科学历，1年以上工作经验；
2、熟练操作office，熟练使用各种办公自动化设备；
3、工作热情积极、性格开朗，具有良好的沟通能力和协调能力。
 晋升通道：
普通助理→专业助理→中级助理→高级助理→主管→经理
 选择一个前景无限的产业，决定着你未来广阔的发展空间。
选择一个迅速发展的企业，决定着你拥有更多的发展机会。
选择一个行业的龙头企业，决定着你将接受到更好的培养。
选择一个积极向上的团队，决定着你拥有志同道合的伙伴。
选择我们，选择一份值得奋斗一生的事业！
工作地址：
北京市宣武区宣外大街10号庄胜广场中央办公楼北翼11层
**********
北京威派格科技发展有限公司
公司规模：
1000-9999人
公司性质：
上市公司
公司行业：
大型设备/机电设备/重工业
公司主页：
http://www.shwpg.com/
公司地址：
北京市宣武区宣外大街10号庄胜广场中央办公楼北翼11层
**********
售后工程师（仪器仪表）
北京新叶能源科技有限公司
五险一金定期体检带薪年假弹性工作全勤奖
**********
福利:
五险一金
定期体检
带薪年假
弹性工作
全勤奖
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：10人
职位类别：机械设备工程师
**********
岗位职责：
1、负责公司仪器仪表产品的现场技术指导安装；
2、负责安装完成后，仪器仪表的调试，并直至正常运行；
3、负责对仪器仪表使用用户的培训工作；
4、负责解答用户提出的公司产品有关的技术咨询及技术服务信息等的全面售后服务。

任职要求：
1、能适应短期出差；
2、热能动力工程、机械设计与制造、机电一体化、电力系统及其自动化等相关专业；
3、有电力系统工作经验者优先。
4、具备良好的口头表述能力和沟通技巧；
5、条件优异者，薪资面议。

工作地址：
北京市昌平区马池口镇
查看职位地图
**********
北京新叶能源科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电气/电力/水利
公司地址：
北京市海淀区中关村北二条13号
**********
售后技术支持管理
亿家净水(武汉)科技有限公司
创业公司年底双薪绩效奖金带薪年假定期体检员工旅游节日福利
**********
福利:
创业公司
年底双薪
绩效奖金
带薪年假
定期体检
员工旅游
节日福利
**********
职位月薪：5000-7000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：售前/售后技术支持管理
**********
岗位职责：
1、服务网点的开拓与维护；
2、服务网点的技术支持及新品的安装培训；
3、服务网点的调整，包含工单价、网点布局、结算方式等；
4、客诉的闭环处理；
5、服务标准化和销售政策的推进。
任职要求：
1、大专及以上学历，两年及以上工作经验；
2、有净水、智能门锁、销售、家电售后经验优先；
3、擅沟通，表达、处理应急事务能力强；
4、团队协作与管理，有较强的抗压能力；
待遇：五险、年终双薪、提供午餐、晚餐和宿舍。
上班时间：9:00-12:00 13:00-18:00
休息时间：大小周制，月度不少于6天。

工作地址：
朝阳区北苑东路20号
查看职位地图
**********
亿家净水(武汉)科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
环保
公司地址：
东湖开发区左岭路117号左岭新城工业园8号楼
**********
PLC、DCS、上位机、下位机自动化控制工程师
波露明(北京)科技有限公司
加班补助包吃包住通讯补贴带薪年假定期体检员工旅游节日福利
**********
福利:
加班补助
包吃
包住
通讯补贴
带薪年假
定期体检
员工旅游
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：北京-昌平区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：5人
职位类别：自动化工程师
**********
公司在化工方面的主要业务有：

1.研发、设计并生产制造化工领域内，煤制油、MTO、FCC流化床、固定床、加氢、脱氢、氧化还原、高压微反、聚合反应、费托合成、临界反应、烟气脱销、催化剂评价等中试小试实验装置。

2.根据用户需求，在其相关领域提供完整的解决方案，包括化工工艺、理论研究、化学计算、
PID流程图、非标设计、设备选型、加工制造、自控设计、自控选型、自控安装调试、系统组装联调等。

3.致力于新材料的应用、新型催化剂评价及筛选，新工艺的研发等。



岗位要求：

热爱自动化行业。热爱化工行业、爱学习，具有独立思考的能力，善于沟通，善解人意（能更好的理解问题和用户的需求），有没有学历都不重要（这里可以学到），勤奋，不抱怨。

你可能会得到的：

充分的学习氛围，自动化基础知识，自控系统原理，化工行业自控装置的选型、设计、安装、调试。温度控制、程序升温，压力控制，流量控制，开关控制，逻辑控制等。自控软件设计、编程，PLC系统和DCS系统控制和集成等。


工作职责：

1、承担项目自控设计、自控方案的制作，参与系统流程的设计

2、参与自控设备选型、仪表选型、控制功能及控制画面的需求整合、控制接线图等详细设计文件

2、指导或参与设备安装、自控安装、现场调试

3、编写设备自控系统说明书，参与供货商调研等工作


你需要具备一定的条件：

1、熟悉DCS系统的原理、组态和维护；熟悉霍尼韦尔的优先。

2、对自动化仪表的调试和生产有一定经验；

3、具有PLC 调试能力，熟练用AUTOCAD，对流量计和电动调节阀的调试和信号采集有一定的经验；

4、具备简单的自动化系统集成或设计或仪器仪表成套设计经验；




必须具备以下条件！

－ 具有超强的责任心

－ 具有完全主动的客户服务意识

－ 具有高效率的常规行业软件操作能力

－ 具有清晰的设计思路与逻辑
工作地址：
北京市朝阳区安慧北里金利大厦
查看职位地图
**********
波露明(北京)科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
石油/石化/化工
公司主页：
www.bloomingtech.net
公司地址：
北京市朝阳区安慧北里金利大厦
**********
财务报告主管【战略性新兴产业】
北京威派格科技发展有限公司
五险一金年终分红带薪年假定期体检员工旅游节日福利
**********
福利:
五险一金
年终分红
带薪年假
定期体检
员工旅游
节日福利
**********
职位月薪：10001-15000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：1人
职位类别：财务分析经理/主管
**********
一个站在“互联网+”风口上的行业
   工业互联，智联供水新型设备引领产业升级。
 智慧水务，城市供水管理平台提升水务运营。
 一家引领行业发展的企业
 承接国家“十二五”水专项课题
五项建设部行业标准/一项国家标准
二次供水领域74项专利
国际工业互联联盟IIC成员
西门子SIEMENS战略合作伙伴
中国首个工程级水利综合实验平台
工业4.0标准的全新智能化工厂
 选择你的未来！期待你的加入！
 职位职责：
1、负责集团会计政策管理；
2、负责集团核算业务的标准化推进；
3、负责配合财务审计工作；
4、负责配合董办做好财务信息披露管理；
5、负责集团会计报表合并管理。
 任职要求：
1、本科以上学历，会计学、财务管理等相关专业；
2、四年以上财务工作经验，其中有上市公司财务报表合并工作经验不低于一年；
3、具备良好职业素养及系统化思考能力、较强的协调沟通能力；
4、能熟练应用EXCEL\WORD\PPT等办公软件；
5、英语四级以上水平。
 职业发展通道：
主管→经理
 选择一个前景无限的产业，决定着你未来广阔的发展空间。
选择一个迅速发展的企业，决定着你拥有更多的发展机会。
选择一个行业的龙头企业，决定着你将接受到更好的培养。
选择一个积极向上的团队，决定着你拥有志同道合的伙伴。
 选择我们，选择一份值得奋斗一生的事业！


工作地址：
北京市宣武区宣外大街10号庄胜广场中央办公楼北翼11层
**********
北京威派格科技发展有限公司
公司规模：
1000-9999人
公司性质：
上市公司
公司行业：
大型设备/机电设备/重工业
公司主页：
http://www.shwpg.com/
公司地址：
北京市宣武区宣外大街10号庄胜广场中央办公楼北翼11层
**********
行政专员
北京华源地质环境工程有限责任公司
**********
福利:
**********
职位月薪：4001-6000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：行政专员/助理
**********
................................................
工作地址：
北京市丰台区南四环西路128号诺德中心2号楼2003室
查看职位地图
**********
北京华源地质环境工程有限责任公司
公司规模：
20-99人
公司性质：
民营
公司行业：
能源/矿产/采掘/冶炼
公司地址：
北京市丰台区南四环西路128号诺德中心2号楼2003室
**********
行政主管
北京华源地质环境工程有限责任公司
**********
福利:
**********
职位月薪：4001-6000元/月 
工作地点：北京-丰台区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：行政经理/主管/办公室主任
**********
1.协助总经理制定公司年度、月度经营计划，参与制定公司重要战略方针、政策；
2.负责建立健全公司各项行政规章制度，参与制定和完善其它管理制度，并组织实施；
3.完善公司的档案管理，编写公司大事记；
4.负责公司内、外部公文、信件、报刊的收、发管理工作；
5.负责公司生产资料、办公用品等的采购、发放以及管理工作，保证及时供应；
6.负责公司的安全、环境卫生、消防管理工作；
7.根据公司要求组织各种会议及大型活动；
8.领导、规范、考核直接下级的工作，审批直接下级的工作计划；
9.负责公司固定资产、生产设备的采购、管理和维修；
10.根据公司规定进行员工奖惩管理；
11.整合各部门提交的报表，做好信息统计，为总经理决策提供参考依据；
12.主持公司形象建设和CIS策划工作；
13.完成总经理交办的其它工作。
     工作地址：
北京市丰台区南四环西路128号诺德中心2003室
查看职位地图
**********
北京华源地质环境工程有限责任公司
公司规模：
20-99人
公司性质：
民营
公司行业：
能源/矿产/采掘/冶炼
公司地址：
北京市丰台区南四环西路128号诺德中心2号楼2003室
**********
人力资源专员
北京华源地质环境工程有限责任公司
**********
福利:
**********
职位月薪：4001-6000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：人力资源专员/助理
**********
。。。。。。。。。。。。。。。。。。。。。。。
工作地址：
北京市丰台区南四环西路128号诺德中心2号楼2003室
查看职位地图
**********
北京华源地质环境工程有限责任公司
公司规模：
20-99人
公司性质：
民营
公司行业：
能源/矿产/采掘/冶炼
公司地址：
北京市丰台区南四环西路128号诺德中心2号楼2003室
**********
会计
北京全华环保技术标准研究中心
五险一金餐补全勤奖定期体检带薪年假
**********
福利:
五险一金
餐补
全勤奖
定期体检
带薪年假
**********
职位月薪：5000-7000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：1人
职位类别：会计/会计师
**********
热爱本职工作，有全局观念、全局思维及细致科学的管理方法。有一定的管理协调能力和大局意识，中共党员优先。
工作地址：
西三旗金燕龙大厦
查看职位地图
**********
北京全华环保技术标准研究中心
公司规模：
20-99人
公司性质：
其它
公司行业：
环保
公司地址：
北京市朝阳区慧忠北里219号华秦大厦西门205
**********
大客户销售经理【战略性新兴产业】
北京威派格科技发展有限公司
五险一金年终分红带薪年假定期体检员工旅游节日福利
**********
福利:
五险一金
年终分红
带薪年假
定期体检
员工旅游
节日福利
**********
职位月薪：10000-13000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：1人
职位类别：大客户销售经理
**********
一个站在“互联网+”风口上的行业
   工业互联，智联供水新型设备引领产业升级。
 智慧水务，城市供水管理平台提升水务运营。
 一家引领行业发展的企业
 承接国家“十二五”水专项课题
五项建设部行业标准/一项国家标准
二次供水领域74项专利
国际工业互联联盟IIC成员
西门子SIEMENS战略合作伙伴
中国首个工程级水利综合实验平台
工业4.0标准的全新智能化工厂
 选择你的未来！期待你的加入！
 岗位职责：
1.带领团队对大型水务投资或运营公司总部进行系统开发和日常维护，运用公司的价值模式，与客户建立长期稳固的合作关系；
2.依托所负责大型水务公司总部资源，支持和配合各地分公司的市场拓展、客户关系维护及合作落地；
3. 组织策划开展有利于大水务系统工作推动的品牌推广（及合作推动）活动。
4. 高层拜访，资源对接，把握并分析客户需求，结合公司合作模式、探讨合作方向，撰写合作方案。
5.负责团队组建和人员的培养，按照公司制度对团队成员进行日常管理与辅导。

任职要求：
1.统招本科及以上学历，形象气质佳；
2.五年以上工作经验，两年以上团队管理经验；
3.有大系统客户开发和维护经验，并应有成功案例；
4.有较强的持续学习能力，悟性高；
5.有较强的分析、总结能力及系统思考力；
6.结果导向、內驱力强，善于自我激励；
7.阳光正派、有激情、责任心强；
8.能够承受高强度工作节奏。

职业发展通道：
大客户经理—大客户总监—分公司总经理--大区经理
 选择一个前景无限的产业，决定着你未来广阔的发展空间。
选择一个迅速发展的企业，决定着你拥有更多的发展机会。
选择一个行业的龙头企业，决定着你将接受到更好的培养。
选择一个积极向上的团队，决定着你拥有志同道合的伙伴。
 选择我们，选择一份值得奋斗一生的事业！
 
工作地址：
北京市宣武区宣外大街10号庄胜广场中央办公楼北翼11层
**********
北京威派格科技发展有限公司
公司规模：
1000-9999人
公司性质：
上市公司
公司行业：
大型设备/机电设备/重工业
公司主页：
http://www.shwpg.com/
公司地址：
北京市宣武区宣外大街10号庄胜广场中央办公楼北翼11层
**********
市场拓展专员【战略性新兴产业】
北京威派格科技发展有限公司
五险一金绩效奖金带薪年假定期体检员工旅游节日福利
**********
福利:
五险一金
绩效奖金
带薪年假
定期体检
员工旅游
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：北京-西城区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：市场营销主管
**********
一个站在“互联网+”风口上的行业
   工业互联，智联供水新型设备引领产业升级。
 智慧水务，城市供水管理平台提升水务运营。
 一家引领行业发展的企业
  承接国家“十二五”水专项课题
 五项建设部行业标准/一项国家标准
 二次供水领域74项专利
 国际工业互联联盟IIC成员
 西门子SIEMENS战略合作伙伴
 中国首个工程级水利综合实验平台
 工业4.0标准的全新智能化工厂
 选择你的未来！期待你的加入！
 岗位职责：
1、开展区域内的品牌建设及推广活动，包括参加业内大型会议、组织公司的合作交流会等；
2、通过调研、考察、交流会等方式提高水务公司对二次供水管理的认知；
3、展示公司的多层次价值，解决城市二次供水管理推进过程中的痛点；
4、负责区域内新产品的技术推广（设计院、行业协会等）。 
 任职资格：
1、统招本科以上学历，形象良好；
2、具备良好的沟通能力与亲和力；
3、有市场或销售类工作经验者优先。
 职业发展通道：
专员—经理—大区总监
 选择一个前景无限的产业，决定着你未来广阔的发展空间。
选择一个迅速发展的企业，决定着你拥有更多的发展机会。
选择一个行业的龙头企业，决定着你将接受到更好的培养。
选择一个积极向上的团队，决定着你拥有志同道合的伙伴。
 选择我们，选择一份值得奋斗一生的事业！

工作地址：
北京市宣武区宣外大街10号庄胜广场中央办公楼北翼11层
**********
北京威派格科技发展有限公司
公司规模：
1000-9999人
公司性质：
上市公司
公司行业：
大型设备/机电设备/重工业
公司主页：
http://www.shwpg.com/
公司地址：
北京市宣武区宣外大街10号庄胜广场中央办公楼北翼11层
**********
销售总监助理【战略性新兴产业】
北京威派格科技发展有限公司
五险一金年终分红带薪年假定期体检员工旅游节日福利
**********
福利:
五险一金
年终分红
带薪年假
定期体检
员工旅游
节日福利
**********
职位月薪：5000-7000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：销售运营专员/助理
**********
一个站在“互联网+”风口上的行业
   工业互联，智联供水新型设备引领产业升级。
 智慧水务，城市供水管理平台提升水务运营。
 一家引领行业发展的企业
 承接国家“十二五”水专项课题
五项建设部行业标准/一项国家标准
二次供水领域74项专利
国际工业互联联盟IIC成员
西门子SIEMENS战略合作伙伴
中国首个工程级水利综合实验平台
工业4.0标准的全新智能化工厂
 选择你的未来！期待你的加入！

岗位职责：
1、 协助总监对部门在制度执行、团队建设等日常运营管理工作进行协调和监督；
2、 及时发现并反馈部门日常管理中存在的问题，并对问题做出分析报告，提出合理化建议；
3、 负责部门各种重要会议的组织、材料准备及会议纪要，负责会议精神的上传下达，监督落实执行情况；
4、 负责部门各类重要市场活动的统筹协调、活动支持及活动后续推进工作的跟进；
5、 负责协调与公司其他部门之间的工作，执行相关的纪律和规定。
 任职资格：
1、统招本科以上学历；
2、两年以上相关岗位工作经验，一年销售或运营管理经验；
3、熟练操作office及各种办公自动化设备；
4、工作热情积极、性格开朗，具有良好的沟通能力和协调能力。

职业发展通道： 
初级总经理助理—中级总经理助理—高级总经理助理
 选择一个前景无限的产业，决定着你未来广阔的发展空间。
选择一个迅速发展的企业，决定着你拥有更多的发展机会。
选择一个行业的龙头企业，决定着你将接受到更好的培养。
选择一个积极向上的团队，决定着你拥有志同道合的伙伴。
 选择我们，选择一份值得奋斗一生的事业！

工作地址：
北京市宣武区宣外大街10号庄胜广场中央办公楼北翼11层
**********
北京威派格科技发展有限公司
公司规模：
1000-9999人
公司性质：
上市公司
公司行业：
大型设备/机电设备/重工业
公司主页：
http://www.shwpg.com/
公司地址：
北京市宣武区宣外大街10号庄胜广场中央办公楼北翼11层
**********
大客户销售【战略性新兴产业】
北京威派格科技发展有限公司
五险一金绩效奖金年终分红带薪年假定期体检员工旅游节日福利
**********
福利:
五险一金
绩效奖金
年终分红
带薪年假
定期体检
员工旅游
节日福利
**********
职位月薪：8001-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：大客户销售代表
**********
一个站在“互联网+”风口上的行业
   工业互联，智联供水新型设备引领产业升级。
 智慧水务，城市供水管理平台提升水务运营。

一家引领行业发展的企业
 承接国家“十二五”水专项课题
五项建设部行业标准/一项国家标准
二次供水领域74项专利
国际工业互联联盟IIC成员
西门子SIEMENS战略合作伙伴
中国首个工程级水利综合实验平台
工业4.0标准的全新智能化工厂

选择你的未来！期待你的加入！


岗位职责：
1、开发与维护各大全国性系统客户（如高校、知名地产集团）的合作关系；
2、支持与配合分公司在具体项目上的拓展工作；
3、在客户集团内部开展技术交流/品牌推广活动；
4、协助分公司参加行业会议等市场推广工作。
 任职资格：
1、 统招本科及以上学历，形象气质良好，亲和力强；
2、 两年以上市场拓展或系统客户开发类工作经验；
3、 良好的沟通协调与协作能力；
4、 学习能力及系统思考能力强。

职业发展通道：
大客户专员→大客户经理→区域大客户经理

选择一个前景无限的产业，决定着你未来广阔的发展空间。
选择一个迅速发展的企业，决定着你拥有更多的发展机会。
选择一个行业的龙头企业，决定着你将接受到更好的培养。
选择一个积极向上的团队，决定着你拥有志同道合的伙伴。

选择我们，选择一份值得奋斗一生的事业！

工作地址：
北京市宣武区宣外大街10号庄胜广场中央办公楼北翼11层
**********
北京威派格科技发展有限公司
公司规模：
1000-9999人
公司性质：
上市公司
公司行业：
大型设备/机电设备/重工业
公司主页：
http://www.shwpg.com/
公司地址：
北京市宣武区宣外大街10号庄胜广场中央办公楼北翼11层
**********
财务核算专员【战略性新兴产业】
北京威派格科技发展有限公司
五险一金绩效奖金年终分红带薪年假定期体检员工旅游节日福利
**********
福利:
五险一金
绩效奖金
年终分红
带薪年假
定期体检
员工旅游
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：无经验
最低学历：本科
招聘人数：3人
职位类别：财务助理
**********
一个站在“互联网+”风口上的行业
  工业互联，智联供水新型设备引领产业升级。
 智慧水务，城市供水管理平台提升水务运营。
 一家引领行业发展的企业
 承接国家“十二五”水专项课题
五项建设部行业标准/一项国家标准
二次供水领域74项专利
国际工业互联联盟IIC成员
西门子SIEMENS战略合作伙伴
中国首个工程级水利综合实验平台
工业4.0标准的全新智能化工厂
 选择你的未来！期待你的加入！

岗位职责：
1、审核各类会计原始单据，编制并审核会计凭证；
2、编制和上报会计报表；积极配合公司各级部门进行分析预测等；
3、统计并分析销售情况，分析公司往来账款；
4、税费分析、税金计算，进行纳税申报；
5、审核公司付款、审核员工借款报销；
6、服从领导安排的其他工作。 

任职要求：
1、财务会计相关专业本科及以上学历；
2、具有良好的服务意识；
3、具备较强的主动学习意识及能力；
4、责任心强，具有良好的表达能力、沟通能力、逻辑思维能力；
5、熟悉常用办公软件，具备较好的文字表达能力；
6、具有吃苦精神，能适应工作强度。

职业发展通道： 
专员—主管—经理

工作地址：
北京市宣武区宣外大街10号庄胜广场中央办公楼北翼11层
**********
北京威派格科技发展有限公司
公司规模：
1000-9999人
公司性质：
上市公司
公司行业：
大型设备/机电设备/重工业
公司主页：
http://www.shwpg.com/
公司地址：
北京市宣武区宣外大街10号庄胜广场中央办公楼北翼11层
**********
技术支持【战略性新兴产业】
北京威派格科技发展有限公司
五险一金绩效奖金带薪年假定期体检员工旅游节日福利
**********
福利:
五险一金
绩效奖金
带薪年假
定期体检
员工旅游
节日福利
**********
职位月薪：5000-7500元/月 
工作地点：北京-西城区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：售前/售后技术支持管理
**********
一个站在“互联网+”风口上的行业
   工业互联，智联供水新型设备引领产业升级。
 智慧水务，城市供水管理平台提升水务运营。
 一家引领行业发展的企业
  承接国家“十二五”水专项课题
 五项建设部行业标准/一项国家标准
 二次供水领域74项专利
 国际工业互联联盟IIC成员
 西门子SIEMENS战略合作伙伴
 中国首个工程级水利综合实验平台
 工业4.0标准的全新智能化工厂
 选择你的未来！期待你的加入！
 岗位职责：
1、大客户售前技术支持；
2、配合销售、市场等部门参与技术答疑、技术交流会和招投标答疑等。
 任职要求：
1、统招本科及以上学历，电气、机电、自动化、通信、机械相关专业；
2、一年以上工作经验；
3、具有工程施工基础经验，熟练autocad制图及相关工程软件基础；
4、阳光正派，积极上进，坚韧有毅力，具备一定抗压能力；
5、可适应短期出差。
 职业发展通道：
初级技术支持—中级技术支持—高级技术支持
 选择一个前景无限的产业，决定着你未来广阔的发展空间。
选择一个迅速发展的企业，决定着你拥有更多的发展机会。
选择一个行业的龙头企业，决定着你将接受到更好的培养。
选择一个积极向上的团队，决定着你拥有志同道合的伙伴。
 选择我们，选择一份值得奋斗一生的事业！
 
工作地址：
北京市宣武区宣外大街10号庄胜广场中央办公楼北翼11层
**********
北京威派格科技发展有限公司
公司规模：
1000-9999人
公司性质：
上市公司
公司行业：
大型设备/机电设备/重工业
公司主页：
http://www.shwpg.com/
公司地址：
北京市宣武区宣外大街10号庄胜广场中央办公楼北翼11层
**********
企划专员【战略性新兴产业】
北京威派格科技发展有限公司
五险一金绩效奖金带薪年假定期体检员工旅游节日福利
**********
福利:
五险一金
绩效奖金
带薪年假
定期体检
员工旅游
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：北京-宣武区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：品牌专员/助理
**********
一个站在“互联网+”风口上的行业
   工业互联，智联供水新型设备引领产业升级。
 智慧水务，城市供水管理平台提升水务运营。

一家引领行业发展的企业
  承接国家“十二五”水专项课题
 五项建设部行业标准/一项国家标准
 二次供水领域74项专利
 国际工业互联联盟IIC成员
 西门子SIEMENS战略合作伙伴
 中国首个工程级水利综合实验平台
 工业4.0标准的全新智能化工厂

选择你的未来！期待你的加入！

岗位职责：
1、负责企业文化建设工作，具体负责文化建设中的策划、组织以及宣传事宜，塑造企业形象，提升企业团队凝聚力；
2、组织各项员工活动，促进企业文化的理解和认可，组织专题宣传活动，支持公司业务和管理方面的创新与变革；
3、与总部保持密切联系，不断更新各地的企业文化宣传内容，参与企业文化方面的培训工作。
 任职资格：
1、具备团队精神与合作意识、强烈的进取精神与高标准意识、良好的学习能力、沟通能力、组织协调能力和社会活动能力；
2、较强的理解能力，熟练的PPT 编辑能力，以及文字写作能力；
3、简单的PS技巧；
 职业发展通道：
企划专员—企划主管—企划经理


选择一个前景无限的产业，决定着你未来广阔的发展空间。
选择一个迅速发展的企业，决定着你拥有更多的发展机会。
选择一个行业的龙头企业，决定着你将接受到更好的培养。
选择一个积极向上的团队，决定着你拥有志同道合的伙伴。

选择我们，选择一份值得奋斗一生的事业！

工作地址：
北京市宣武区宣外大街10号庄胜广场中央办公楼北翼11层
**********
北京威派格科技发展有限公司
公司规模：
1000-9999人
公司性质：
上市公司
公司行业：
大型设备/机电设备/重工业
公司主页：
http://www.shwpg.com/
公司地址：
北京市宣武区宣外大街10号庄胜广场中央办公楼北翼11层
**********
大客户销售专员【战略性新兴产业】
北京威派格科技发展有限公司
五险一金绩效奖金带薪年假定期体检员工旅游节日福利
**********
福利:
五险一金
绩效奖金
带薪年假
定期体检
员工旅游
节日福利
**********
职位月薪：7000-9000元/月 
工作地点：北京-西城区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：大客户销售经理
**********
一个站在“互联网+”风口上的行业
   工业互联，智联供水新型设备引领产业升级。
 智慧水务，城市供水管理平台提升水务运营。
 一家引领行业发展的企业
 承接国家“十二五”水专项课题
五项建设部行业标准/一项国家标准
二次供水领域74项专利
国际工业互联联盟IIC成员
西门子SIEMENS战略合作伙伴
中国首个工程级水利综合实验平台
工业4.0标准的全新智能化工厂
 选择你的未来！期待你的加入！
 岗位职责：
1、负责区域内的系统大客户开发及长期关系维护；
2、透彻理解客户需求与公司资源，负责设计推进策略与合作方案、商业模式，形成深入且持续的客户关系；
3、负责最终的业绩产出并能够不断拓展潜在的商业机会。

任职资格：
1、统招本科以上学历，具备良好的沟通能力与亲和力；
2、具备2年以上销售或客户开发类工作经验且业绩良好。
3、有开发长期合作客户经验者优先。
4、良好的沟通协调与协作能力。
 职业发展通道：
专员—经理—区域经理—分公司总经理
 选择一个前景无限的产业，决定着你未来广阔的发展空间。
选择一个迅速发展的企业，决定着你拥有更多的发展机会。
选择一个行业的龙头企业，决定着你将接受到更好的培养。
选择一个积极向上的团队，决定着你拥有志同道合的伙伴。
 选择我们，选择一份值得奋斗一生的事业！

工作地址：
北京市宣武区宣外大街10号庄胜广场中央办公楼北翼11层
**********
北京威派格科技发展有限公司
公司规模：
1000-9999人
公司性质：
上市公司
公司行业：
大型设备/机电设备/重工业
公司主页：
http://www.shwpg.com/
公司地址：
北京市宣武区宣外大街10号庄胜广场中央办公楼北翼11层
**********
清华大学环境学院岳东北课题组招聘科研助理
水木湛清(北京)环保科技有限公司
**********
福利:
**********
职位月薪：2001-4000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：硕士
招聘人数：2人
职位类别：其他
**********
因科研工作需要，清华大学环境学院岳东北课题组招聘合同制科研助理1-2名。
 工作职责：
1. 参与垃圾处理、废液蒸发处理的科研工作；
2. 相关科研项目的报告撰写；
3. 协助完成有关课题的实施和管理工作。
 任职要求：
1. 具有化学工程、热能工程、环境工程专业的硕士或以上学历，具有科研工作经历者优先；
2. 有较好的文字表达能力、论文写作能力，有较好的英语水平；
3. 有较好的沟通、协调能力和组织能力；
4. 做事高效，责任心强，工作认真，吃苦耐劳。
 待遇条件：
一经录用，执行清华大学合同制人员管理有关规定，具体薪酬面谈。
有意应聘者请于2018年3月31日前将个人简历（个人基本信息、工作或研究经历、参与科研项目及个人贡献简介、成果发表情况等）以附件形式发至yuedb@tsinghua.edu.cn，邮件标题请注明“应聘科研助理——姓名”。通过初选者将收到参加面试的通知，未通过初审者不再另行通知。    
工作地址：
清华大学
查看职位地图
**********
水木湛清(北京)环保科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司地址：
北京市石景山区金顶北路69号金隅国际大厦4层
**********
质控室/质量负责人/质控助理
北京奥达清环境检测有限公司
绩效奖金交通补助餐补带薪年假员工旅游
**********
福利:
绩效奖金
交通补助
餐补
带薪年假
员工旅游
**********
职位月薪：5000-7000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：2人
职位类别：化验/检验
**********
任职资格：
    必须具备本科及以上学历，熟悉《检验检测机构资质认定评审准则》，熟悉质量和技术管理要求，有丰富的质量管理知识和质量管理经验；具有组织管理体系有效运行和持续改进的能力；为人公正公道，办事认真务实，执纪严明
岗位职责：
1、 负责本公司的质量工作，保证本公司管理体系持续有效运行；
2、 组织本公司《质量手册》和《程序文件》的编制、修订、维护和运行，并组织管理体系文件的宣贯；
3、组织编制及批准管理性记录格式；
4、 组织内部审核，负责编制并落实年度内部审核计划，委派内审员，批准内部审核报告和纠正措施；
5、负责组织对不符合项的评价控制，对纠正措施及预防措施进行批准；
6、 负责组织投诉和申诉的处理；
7、负责计划和组织展开新项目评审工作；
8、 负责质量控制工作的监督和质控计划的批准；
9、 参与管理评审，负责编制管理评审计划和评审报告并组织实施；
10、 负责管理性质量记录格式的批准及管理评审的记录保存；
11、对可能存在的检测质量问题安排追溯或及时的反馈；有权终止不符合质量要求的检测活动并对检测事故进行调查。
工作地址：
北京市北京经济开发区凉水河二街8号院大族企业湾3号楼6层
**********
北京奥达清环境检测有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
检验/检测/认证
公司主页：
www.aodaqing.cn
公司地址：
北京市北京经济开发区凉水河二街8号院大族企业湾3号楼6层
查看公司地图
**********
销售专员
北京米微环保科技有限公司
绩效奖金年终分红全勤奖带薪年假创业公司
**********
福利:
绩效奖金
年终分红
全勤奖
带薪年假
创业公司
**********
职位月薪：6001-8000元/月 
工作地点：北京-朝阳区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：销售代表
**********
熟悉产品，爱学习，有责任心，不怕吃苦，有良好的沟通能力，服务老客户，开发新客户，具有独立成交客户的能力!
为广大有梦想有野心的年轻人提供坚实的发展平台！你敢挑战，薪资无上限！


工作地址：
北京市朝阳区来广营西路59号 红星美凯龙1馆5层F8618室
**********
北京米微环保科技有限公司
公司规模：
20-99人
公司性质：
股份制企业
公司行业：
环保
公司主页：
www.mivei.com
公司地址：
北京市朝阳区来广营西路59号 红星美凯龙1馆5层F8618室
查看公司地图
**********
社区业务代表
北京立道立德科技有限公司
**********
福利:
**********
职位月薪：100001-150000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：500人
职位类别：业务拓展专员/助理
**********
面向全国招聘社区业务代表，全世界最幸福的工作！一个吃喝玩乐+赚钱的业务！只要有闲暇时间均可成为全国社区业务代表(限额1000名)！“零”投入,高回报！每天邀请一人到海南三亚旅居，月收入30000一300000元,每天邀请三人到海南三亚旅居，月收入90000一900000元！改变思维模式是当下所有人需要努力的方向！换车换房已不成问题！年薪百万已近在咫尺！
工作地址：
西城区白广路7号
查看职位地图
**********
北京立道立德科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.bjldld.com/
公司地址：
北京市丰台区小屯路9号立高大厦8层
**********
销售内勤
北京宏光星宇科技发展有限公司
五险一金年底双薪绩效奖金全勤奖餐补带薪年假员工旅游节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
全勤奖
餐补
带薪年假
员工旅游
节日福利
**********
职位月薪：3000-6000元/月 
工作地点：北京-昌平区
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：2人
职位类别：销售行政专员/助理
**********
岗位职责：
供应商管理；
合同管理：订单接收、订单交付等；
物流管理：日常办公、成品发货等；
标书制作；
岗位要求：
必须在3年以上相同岗位工作经验；
家住在TBD云集中心附近；
责任心很强、沟通能力很强；
以上条件不符合的请免投简历；
工作地址：
北京市昌平区北清路TBD云集中心2号楼C座12层1205室
查看职位地图
**********
北京宏光星宇科技发展有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
www.hgxykj.cn
公司地址：
北京市昌平区北清路TBD云集中心
**********
反渗透膜纳滤膜超滤膜业务总监
科氏(北京)滤膜科技有限公司
通讯补贴年底双薪绩效奖金年终分红交通补助带薪年假节日福利员工旅游
**********
福利:
通讯补贴
年底双薪
绩效奖金
年终分红
交通补助
带薪年假
节日福利
员工旅游
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：10人
职位类别：客户总监
**********
岗位职责：
1、 RO/NF/UF膜产品的市场开发与销售；
2、 制定本区域营销计划、分解销售目标；
3、 配合全国各地代理商开展工作，完成公司业务目标；
4、 直接参与、主持重要客户的业务技术交流、谈判及成交；
5、 督导代理商及老客户业务开展工作，落实本区域货款回收；
6、 控制所辖区域相互竞争、协调客户反馈信息及现场业主等问题。
任职要求：
1、环境工程、给排水、电厂化学、化工工艺等相关专业；
2、1-3年以上销售工作经验；专科以上学历；
3、了解、熟悉反渗透膜/纳滤膜/超滤膜等水处理系统设计者优先考虑；
4、善于掌握市场信息，具有敏锐的市场观察力、判断力；
5、能够独立组织协调工作，能够适应出差。
工作地址：
大兴区天华大街2号
**********
科氏(北京)滤膜科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.kochmembrane.cn/
公司地址：
大兴区庆祥南路29号
查看公司地图
**********
反渗透膜纳滤膜超滤膜产品代表
科氏(北京)滤膜科技有限公司
通讯补贴年底双薪绩效奖金年终分红交通补助带薪年假节日福利员工旅游
**********
福利:
通讯补贴
年底双薪
绩效奖金
年终分红
交通补助
带薪年假
节日福利
员工旅游
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：10人
职位类别：品牌专员/助理
**********
岗位职责：
1、 RO/NF/UF膜产品的市场开发与销售；
2、 制定本区域营销计划、分解销售目标；
3、 配合全国各地代理商开展工作，完成公司业务目标；
4、 直接参与、主持重要客户的业务技术交流、谈判及成交；
5、 督导代理商及老客户业务开展工作，落实本区域货款回收；
6、 控制所辖区域相互竞争、协调客户反馈信息及现场业主等问题。
任职要求：
1、环境工程、给排水、电厂化学、化工工艺等相关专业；
2、1年以上销售工作经验；
3、专科以上学历；
4、了解、熟悉反渗透膜/纳滤膜/超滤膜等水处理系统设计者优先考虑；
5、善于掌握市场信息，具有敏锐的市场观察力、判断力；
6、能够独立组织协调工作，能够适应出差。
工作地址：
大兴区天华大街2号
**********
科氏(北京)滤膜科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司主页：
http://www.kochmembrane.cn/
公司地址：
大兴区庆祥南路29号
查看公司地图
**********
汽车用品代理商经销商
杭州全赢汽车用品有限公司
年终分红绩效奖金
**********
福利:
年终分红
绩效奖金
**********
职位月薪：15001-20000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：2人
职位类别：经销商
**********
杭州全赢汽车用品有限公司是一家专门从事汽车用品销售的企业。公司以精细化服务的渠道优势、天然健康的品质优势为车用香水市场重新定位，坚持做专业车用香水的金牌产品及服务的提供商。
    杭州全赢汽车用品有限公司自2012年成立以来，是正高速前进在中国汽车香品市场新的生力军，其全力打造的歌浪香品品牌，并已逐渐成为市场的佼佼者。 杭州全赢公司立志成为中国市场上专业车香用品及服务的金牌提供商；公司尊崇“踏实、拼搏、责任”的企业精神，并以诚信、共赢、开创经营理念，创造良好的企业经营环境，以全新的管理模式，高超的生产调配技术，细致周到的服务，卓越的品质为生存根本，我们始终坚持用户至上 用心服务于客户，坚持用自己的服务去打动客户。
我们一直尊循以严苛的产品标准，全赢的渠道合作模式和精细化的运营理念，正即将完成新的跨越。 为全面拓展市场，需有学识、懂市场、能驾驶的您的加入！
面向全国招募市级代理商
代理商招募
如满足下述条件具有优先签约权；
1 未经营车用香水类相关产品；
2 能按照公司服务体系运作市场；
3 具备操作歌浪产品所需的资源（资金、人力等）；
主要业务及产品：公司主要为各地区汽车美容装潢店提供各类汽车用品，其中以歌朗香品为主营产品。
公司支持：
公司提供培训(杭州总部学习)，并将提供全套业务拓展、销售及服务系统的培训，以及样板市场的实操。
欢迎有创业欲望的你加盟。（不是有代理想法的请勿投简历，如有代理需求请致电 ①③⑤〇⑤⑦③⑨②⑦⑨

工作地址：
北京
查看职位地图
**********
杭州全赢汽车用品有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
礼品/玩具/工艺美术/收藏品/奢侈品
公司主页：
www.garonne.com.cn
公司地址：
杭州市金昌路2069号D栋3楼
**********
会计
北京伍舟岩环保科技有限公司
**********
福利:
**********
职位月薪：1000-2000元/月 
工作地点：北京
发布日期：最近
工作性质：兼职
工作经验：5-10年
最低学历：大专
招聘人数：1人
职位类别：会计/会计师
**********
1.按国家统一会计制度规定设置会计科目。
2.及时确认销售收入，正确计算增值税、消项税额。
3.划清费用的开支范围及营业内外收入。
4.认真计算财务成果及各种税金。
5.按财务制度规定正确核算利润分配。
6.按期缴纳各种税款。
7.债权、债务及时登记、及时查清、按月做好财务状况分析。
8.对会计帐目及凭证要按期装订成册，妥善保管。
9.每周保证1~2个日历天坐班工作。
10.认真严谨，工作态度积极。
工作地址：
大兴区枣园红木林南区
查看职位地图
**********
北京伍舟岩环保科技有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
环保
公司主页：
http://www.wuzhouyan.com/
公司地址：
大兴区枣园红木林南区
**********
系统维护工程师(013945)(职位编号：Hanergy013945)
北京汉能光伏投资有限公司
五险一金带薪年假免费班车
**********
福利:
五险一金
带薪年假
免费班车
**********
职位月薪：10001-15000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：5人
职位类别：IT技术支持/维护工程师
**********
岗位职责:
1、参与全球客户服务总部所用的软硬件系统的规划、建设；
2、负责软硬件系统的现场维护工作，确保系统的正常运转；
3、处理系统使用人员的软硬件应用请求，配置和修改系统以满足用户提出的要求；
4、负责软硬件系统的日常运行检查和应急响应，回答用户对系统的相关咨询；
5、对使用人员进行简单的系统应用培训，指导其正确操作；
6、负责系统运行情况分析。

任职要求：
1、计算机，通信等相关专业本科或以上学历，3年以上软硬件维护经验，有在大型呼叫中心、银行或电信部门系统维护经验者优先考虑；
2、需要具备软硬件现场安装，部署，调试，纠错经验；
3、有一定的计算机网络基础知识，有较好的沟通理解能力和强烈的服务意识；
4、英文熟练者优先。
工作地址：
北京朝阳区安立路0-A号（奥森公园北园东门南100米）
**********
北京汉能光伏投资有限公司
公司规模：
10000人以上
公司性质：
上市公司
公司行业：
能源/矿产/采掘/冶炼
公司主页：
null
公司地址：
北京市朝阳区北辰西路8号北辰世纪中心B座
**********
技术支持工程师(013948)(职位编号：Hanergy013948)
北京汉能光伏投资有限公司
五险一金带薪年假免费班车
**********
福利:
五险一金
带薪年假
免费班车
**********
职位月薪：10001-15000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：20人
职位类别：售前/售后技术支持管理
**********
岗位职责:
1、参与内部产品测试；
2、负责企业产品在实施安装和后期维护过程中出现的技术问题；
3、能独立负责项目、用户技术问题的定位、跟踪、处理，并对问题做分类和归档处理；
4、建立并维护知识库；
5、负责把问题解决过程中发现的产品缺陷或用户的有效反馈提供给产品研发部门；
6、负责呼叫中心坐席人员的产品培训；
7、利用企业内外各种资源，满足用户对于产品服务的需求并提高用户对售后服务的满意度和忠诚度。

任职要求：
1、大型生产制造企业售后技术支持相关经验；
2、熟悉光伏组件、逆变器、配电柜等相关产品经验者优先；
3、可以接受全球出差者优先；
4、英文熟练者优先。
工作地址：
北京朝阳区安立路0-A号（奥森公园北园东门南100米）
**********
北京汉能光伏投资有限公司
公司规模：
10000人以上
公司性质：
上市公司
公司行业：
能源/矿产/采掘/冶炼
公司主页：
null
公司地址：
北京市朝阳区北辰西路8号北辰世纪中心B座
**********
清华大学环境学院岳东北课题组招聘博士后
水木湛清(北京)环保科技有限公司
**********
福利:
**********
职位月薪：2001-4000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：博士
招聘人数：2人
职位类别：其他
**********
清华大学环境学院因科研工作需要，现招聘博士后1-2人。
合作导师：岳东北 副教授
拟从事的科研领域：生物质废物资源化
一、应聘条件
1、已获得或即将获得国内外知名高校或研究所博士学位，化学、化工或环境化学相关专业，有一定化学合成研究背景者优先考虑；
2、年龄35岁以下，品学兼优，身体健康；
3、有较好的文字表达能力、论文写作能力，有较好的英语水平；
4、工作认真，责任心强，动手能力强。
二、聘用待遇
工资待遇按清华大学博士后管理规定执行。
三、应聘材料
有意应聘者请于2018年3月31日前将个人简历（含个人基本信息、工作或研究经历、参与科研项目及个人贡献简介、成果发表情况），身份证、学历和学位证书复印件等以附件形式发至yuedb@tsinghua.edu.cn，邮件标题请注明“应聘博士后——姓名”。通过初选者将收到参加面试的通知，未通过初审者不再另行通知。
工作地址：
清华大学
查看职位地图
**********
水木湛清(北京)环保科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
环保
公司地址：
北京市石景山区金顶北路69号金隅国际大厦4层
**********
实习英语老师 助教
北京蕴星教育咨询有限公司
无试用期绩效奖金节日福利
**********
福利:
无试用期
绩效奖金
节日福利
**********
职位月薪：2001-4000元/月 
工作地点：北京-大兴区
发布日期：最新
工作性质：实习
工作经验：无经验
最低学历：不限
招聘人数：5人
职位类别：外语教师
**********
岗位职责：
1、负责向高端客户提供英语学习建议； 
1. Responsible for high-end clients to provide English study suggest
2、负责对已报名的VIP学员进行跟踪服务；
2. Responsible for the registered VIP students tracking service;
3、时常为学员组织课程活动；
3. Frequently organization curriculum activities for students;
 
任职要求：
1、大专及以上学历，硕士学历或两年以上英语国家留学经历者优先；
1. College or above degree，bachelor degree or above
with two years study in English-speaking country experience is preferred;
2、形象气质佳，活泼、开朗，热爱教育工作，喜欢孩子 
2. Presentable, lively, cheerful, love education work，like
kids
3.英语口语流利，发音地道； 
3. Fluent oral English and pronunciation accurately;
4、亲和力佳，具有良好的服务意识。 
4. Good affinity and good service consciousness.
工作地址：
北京市大兴区亦庄博客雅苑底商4号
**********
北京蕴星教育咨询有限公司
公司规模：
1000-9999人
公司性质：
上市公司
公司行业：
教育/培训/院校
公司地址：
朝阳区朝阳北路101号朝阳大悦城
查看公司地图
**********
外教助理（亦庄校区）
北京蕴星教育咨询有限公司
五险一金绩效奖金全勤奖包住带薪年假员工旅游节日福利
**********
福利:
五险一金
绩效奖金
全勤奖
包住
带薪年假
员工旅游
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：5人
职位类别：外语教师
**********
岗位职责：
1、负责向高端客户提供英语学习建议； 
1. Responsible for high-end clients to provide English study suggest
2、负责对已报名的VIP学员进行跟踪服务；
2. Responsible for the registered VIP students tracking service;
3、时常为学员组织课程活动；
3. Frequently organization curriculum activities for students;
4、作为外教与学员之间的桥梁，如遇突发情况，帮助学员调配时间或者调换老师。
4. As a bridge between the foreign teacher and student; In case of emergent
events that help students to allocate time or exchange the teacher.

应届英语专业的毕业生也可以！！！
 任职要求：
1、大专及以上学历，硕士学历或两年以上英语国家留学经历者优先；
1. College or above degree，bachelor degree or above
with two years study in English-speaking country experience is preferred;
2、一年以上教学或助教工作经验； 
2. Over one year work experience in teaching or teaching assistant;
3、形象气质佳，活泼、开朗，热爱教育工作，喜欢孩子 
3. Presentable, lively, cheerful, love education work，like
kids
4.英语口语流利，发音地道； 
4. Fluent oral English and pronunciation accurately;
5、亲和力佳，具有良好的服务意识。 
5. Good affinity and good service consciousness.
***公司为每位教师提供免费住宿、环境优良、步行10分钟；只要你够优秀，够踏实，更多平台为你而定！！！
工作地址：
北京市亦庄经济开发区鹿海园4里博客雅苑9号楼9105室
查看职位地图
**********
北京蕴星教育咨询有限公司
公司规模：
1000-9999人
公司性质：
上市公司
公司行业：
教育/培训/院校
公司地址：
朝阳区朝阳北路101号朝阳大悦城
**********
光学研发工程师
北京新叶能源科技有限公司
五险一金绩效奖金带薪年假弹性工作
**********
福利:
五险一金
绩效奖金
带薪年假
弹性工作
**********
职位月薪：8000-16000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：硕士
招聘人数：2人
职位类别：激光/光电子技术
**********
岗位职责：
1、设计和研发光电类精密仪器仪表；
2、协助研发主管完成新产品的设计及实验；
3、协助研发主管完成精密光电设计，部分机械设计及优化；
4、负责光电仪表产品样机测试及指导现场测试；
5、负责产品标准的制定。
任职要求：
1、光学、光学工程、光通信、光电子、物理电子、微电子等相关专业，硕士及以上学历；
2、具备模电、数电等相关基础知识。
3、熟练的光学实验技能，有激光、光纤光学等实验基础者优先；
4、有光电仪表设计经验，参与过仪器仪表开发相关项目者优先；
5、熟悉C++/C、Matlab、Labview等软件，具有Soliworks或CAD等相关设计经验者优先。

工作地址：
北京市海淀区中关村北二条13号
查看职位地图
**********
北京新叶能源科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电气/电力/水利
公司地址：
北京市海淀区中关村北二条13号
**********
销售经理（底薪+提成）
北京新叶能源科技有限公司
五险一金带薪年假弹性工作节日福利餐补定期体检
**********
福利:
五险一金
带薪年假
弹性工作
节日福利
餐补
定期体检
**********
职位月薪：5000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：5人
职位类别：销售工程师
**********
岗位职责：
1、配合销售总监，实施销售计划；
2、能独立或在公司的支持下销售公司产品；

任职要求：
1、本科以上学历，热能、电子、机械专业优先；
2、熟悉电力节能环保行业者优先；
3、电力行业有客户资源者优先。
工作地址：
北京市海淀区中关村北二条13号中科科仪
查看职位地图
**********
北京新叶能源科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电气/电力/水利
公司地址：
北京市海淀区中关村北二条13号
**********
电力电子工程师（软件方向）
北京低碳清洁能源研究所
绩效奖金交通补助餐补通讯补贴带薪年假补充医疗保险定期体检免费班车
**********
福利:
绩效奖金
交通补助
餐补
通讯补贴
带薪年假
补充医疗保险
定期体检
免费班车
**********
职位月薪：面议 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：硕士
招聘人数：1人
职位类别：电力电子研发工程师
**********
岗位职责：
1. 负责电力电子变换器建模与仿真；
2. 负责电力电子变换器核心控制算法开发；
3. 负责基于DSP的电力电子变换器软件控制程序开发；
4. 负责与硬件工程师配合进行电力电子变换器的调试与测试；
任职要求：
1. 博士毕业，或硕士毕业5年；
2. 电力电子专业毕业；
3. 具有风电/光伏/储能变换器产品控制算法和软件开发经验，有产品开发经验者优先；
4. 具备基于SiC变换器软件开发经验者优先；
5. 具有良好的沟通和协调能力，以及良好的团队合作精神；
6. 具有独立思考和创新能力，自我学习能力强，能够以结果为导向，独立有效完成工作；
7. 熟练掌握电力电子仿真分析软件，如PSCAD、MATLAB、PSIM等；
8. 精通C语言编程，有严谨的编程习惯，熟悉DSP及CCS编程环境；
9. 具有良好的英语口语、写作能力，可以将英语作为工作语言。
工作地址：
北京市昌平区未来科技城神华低碳001信箱
**********
北京低碳清洁能源研究所
公司规模：
100-499人
公司性质：
国企
公司行业：
环保
公司地址：
北京市昌平区未来科技城神华低碳001信箱
**********
投资测算工程师
中环智慧环境有限公司
交通补助餐补通讯补贴带薪年假节日福利定期体检年底双薪五险一金
**********
福利:
交通补助
餐补
通讯补贴
带薪年假
节日福利
定期体检
年底双薪
五险一金
**********
职位月薪：10001-15000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：1人
职位类别：证券/投资项目管理
**********
岗位职责：
1、开展项目投资前期市场调研及市场分析工作，完成调研报告及项目投资可行评估报告。
2、关注公司相关业务行业及企业动态，出具分析报告；
3、协助公司完成重大项目投资决策方案及各类报告；
4、负责根据报价人员和运营人员提交的项目条件进行经济分析，包括投标前的技经测算、中标后的后评价；
5、工程建设中的成本控制，包括概算、预算和决算；
6、负责项目上投委会时协助运营人员阐述项目情况。
任职要求：
1、本科及以上学历；
2、工程经济管理类专业，投资专业（项目投资、固定资产投资方向）；
3、具备较强的决策分析和解决问题能力，具备良好的沟通、协调能力；
4、两年以上项目投资分析工作经验；
5、有市政环卫、基础设施PPP项目运作经验者可优先考虑。
 
工作地址：
北京市朝阳区亮马桥路21号枫花园汽车电影院内26号二层
查看职位地图
**********
中环智慧环境有限公司
公司规模：
20-99人
公司性质：
上市公司
公司行业：
环保
公司地址：
北京市朝阳区亮马桥路21号枫花园汽车电影院内26号二层
**********
工艺工程师（水处理）J10220
博天环境集团股份有限公司
五险一金绩效奖金带薪年假补充医疗保险定期体检员工旅游节日福利
**********
福利:
五险一金
绩效奖金
带薪年假
补充医疗保险
定期体检
员工旅游
节日福利
**********
职位月薪：10001-15000元/月 
工作地点：北京-海淀区
发布日期：最近
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：2人
职位类别：水处理工程师
**********
工作职责：
1.负责提供水处理系统的设计计算书和水处理系统的设计方案及项目执行相关图纸。
2.参与针对客户的技术交流工作。
3.配合客户经理或高级客户经理进行售前技术支持。
4.对产品现场安装调试进行技术支持并解决出现的技术问题，对客户提出的技术问题给与解答。
5.竞争对手技术文件的收集和汇总分析。
6.已经投运的重要或重点产品或系统运行数据的跟踪和整理。
7.负责技术文件资料的制作、整理、归档工作。
8.完成上级领导交办的其他工作任务。

任职资格：
1.本科及以上学历。 
2.环境工程等相关专业。
3.必备专业知识：熟知公司产品设备工艺技术知识和国内外技术标准。
4.必备技能与能力：熟练操作Office办公软件、CAD、3D设计软件，具备良好的沟通能力、分析能力、问题解决能力、责任心、学习能力、关注细节、执行力。
5.5年以上水处理系统设计经验。有MBR、超滤项目经验者优先。
工作地址：
西直门北大街首钢国际大厦12层
**********
博天环境集团股份有限公司
公司规模：
1000-9999人
公司性质：
上市公司
公司行业：
环保
公司主页：
http://www.poten.cn
公司地址：
北京市海淀区西直门北大街60号首钢国际大厦12A
查看公司地图
**********
营销总监J10513
博天环境集团股份有限公司
五险一金绩效奖金带薪年假补充医疗保险定期体检员工旅游节日福利
**********
福利:
五险一金
绩效奖金
带薪年假
补充医疗保险
定期体检
员工旅游
节日福利
**********
职位月薪：10001-15000元/月 
工作地点：北京
发布日期：最近
工作性质：全职
工作经验：10年以上
最低学历：本科
招聘人数：1人
职位类别：销售总监
**********
工作职责：
1.根据公司的年度目标制定市场销售计划，带领团队完成目标；
2.根据客户需求，组织团队安排技术交流，完成售前技术支持；
3.负责跟踪营销部销售合同的货款回收；
4.售后技术问题的汇总并组织技术人员解决；
5.汇总客户档案，针对重点客户制定行动计划；
6.汇总产品销售信息，分析销售数据； 
7.汇总并分析竞争对手市场和技术情报；
8.合理控制销售预算、销售费用、销售范围与销售目标的平衡发展

任职资格：
1.熟悉水处理设备及工程销售渠道，10年以上相关经验，3年以上营销团队管理经验。
2.本科以上学历，给排水、环境工程、工商管理等相关专业。
3.掌握先进的营销方法，对市场战略规划、市场开拓、市场管理、终端维护及品牌建设方面有深入研究与实践经验。
4.具备优秀的领导能力、团队管理能力。
工作地址：
西直门北大街首钢国际大厦12层
**********
博天环境集团股份有限公司
公司规模：
1000-9999人
公司性质：
上市公司
公司行业：
环保
公司主页：
http://www.poten.cn
公司地址：
北京市海淀区西直门北大街60号首钢国际大厦12A
查看公司地图
**********
高级测试工程师
博天环境集团股份有限公司
**********
福利:
**********
职位月薪：10001-15000元/月 
工作地点：北京-海淀区
发布日期：最近
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：1人
职位类别：IT质量管理工程师
**********
职位描述：

1、 负责上线质量保证工作，涉及测试类型：接口、功能、压力、性能、自动化等；
2、 参与需求及概要设计评审，进行测试需求分析，制定测试计划，独立撰写测试用例、测试报告；
3、 进行产品测试，跟进研发测试流程，把控上线质量。


职位要求：
1、3年及以上互联网软件测试经验，1年以上知名互联网企业工作经验。
2、熟悉互联网软件研发测试流程规范、精通系统测试用例设计方法、良好的bug定位分析能力、良好的理解沟通能力。
3、了解常见互联网软件系统架构，能够快速理解系统架构、从测试角度进行系统分析和问题排查。
4、熟练掌握两种以上自动化测试工具和性能测试工具，能够编写测试代码；熟练掌握CI、CD技术，及相关的工具；
5、加分项：有Java或python编程经验、有测试工具或测试脚本开发经验、熟悉持续集成、熟悉分布式系统架构或运维知识、熟悉配置管理知识。
工作地址：
北京市海淀区西直门北大街60号首钢国际大厦12A
查看职位地图
**********
博天环境集团股份有限公司
公司规模：
1000-9999人
公司性质：
上市公司
公司行业：
环保
公司主页：
http://www.poten.cn
公司地址：
北京市海淀区西直门北大街60号首钢国际大厦12A
**********
工艺研发工程师（膜应用）J10483
博天环境集团股份有限公司
五险一金年底双薪绩效奖金通讯补贴带薪年假补充医疗保险定期体检节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
通讯补贴
带薪年假
补充医疗保险
定期体检
节日福利
**********
职位月薪：8000-15000元/月 
工作地点：北京
发布日期：最近
工作性质：全职
工作经验：1-3年
最低学历：硕士
招聘人数：1人
职位类别：环保技术工程师
**********
工作职责：
1.膜系统应用开发工作，新型水处理工艺技术的研发；
2.参与现场技改、研发项目的常用小试、中试的试制协调、运行；
3.配合完成科研课题的申报与执行；
4.集团内部研发项目的立项及实施管理；
5.参与研发技术成果的工程示范及产业化推广相关工作。
6.掌握市场相关新技术动向，参与制定公司研发计划并参与组织研发课题立项。

任职资格：
1.学历要求：硕士及以上学历。
2.专业要求：环境工程、给排水、化学工程等相关专业。
3.必备专业知识：熟知公司产品、设备、工艺技术知识和国内外技术标准。
4.必备技能与能力：熟练操作Office办公软件、CAD、3D设计软件，具备良好的沟通能力、分析能力、问题解决能力、责任心、学习能力、关注细节、执行力。
5.2年以上膜系统研发经验。
工作地址：
西直门北大街60号首钢大厦12层
**********
博天环境集团股份有限公司
公司规模：
1000-9999人
公司性质：
上市公司
公司行业：
环保
公司主页：
http://www.poten.cn
公司地址：
北京市海淀区西直门北大街60号首钢国际大厦12A
查看公司地图
**********
区域销售经理（膜产品及膜法工艺包）
博天环境集团股份有限公司
五险一金年底双薪绩效奖金通讯补贴带薪年假补充医疗保险定期体检节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
通讯补贴
带薪年假
补充医疗保险
定期体检
节日福利
**********
职位月薪：8000-15000元/月 
工作地点：北京
发布日期：最近
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：1人
职位类别：区域销售经理/主管
**********
岗位职责：
1、根据市场营销计划，策划并实施相关的工作，完成超滤膜产品及工艺包销售任务；
2、项目洽谈、项目执行、项目回款工作及项目推进过程中整体协调和管理工作；
3、负责跟踪工程信息，开发建立稳定的客户关系，收集客户资料及项目信息，持续开拓项目资源； 
4、跟踪客户需求，掌握竞争对手的市场动态；
5、针对具体项目，根据客户需求输出可实施的最佳解决方案；
6、完成上级领导交办的其他工作任务；
任职要求：
1、环境工程、市场营销等相关专业；
2、熟悉CAD和投标文件制作；
3、性格开朗，能承受压力，热爱销售工作；
4、能出差、肯吃苦、肯学习，沟通能力强、具有团队合作精神；
5、具有三年以上EPC、水处理工程相关设备销售工作经验。
工作地址：
北京市海淀区西直门北大街60号首钢国际大厦12A
**********
博天环境集团股份有限公司
公司规模：
1000-9999人
公司性质：
上市公司
公司行业：
环保
公司主页：
http://www.poten.cn
公司地址：
北京市海淀区西直门北大街60号首钢国际大厦12A
查看公司地图
**********
行政主管J10631
博天环境集团股份有限公司
五险一金年底双薪绩效奖金带薪年假补充医疗保险定期体检节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
带薪年假
补充医疗保险
定期体检
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：北京
发布日期：招聘中
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：1人
职位类别：行政经理/主管/办公室主任
**********
岗位职责：
1.负责行政管理制度的建立与完善，与下属项目公司对接，确保各项行政制度的实施；
2.做好公司重要客户的接待，协调处理外部相关部门关系；
3.负责本部管理层会务组织，支持团建组织工作；
4.负责行政部日常预算管理；
5.负责本部及监督项目公司固定资产盘点及日常登记管理；
6.负责本部及项目公司车辆和住房日常管理；
7.负责行政文档收集、下发、存档等管理工作；
8.负责日常印章管理工作及监督项目公司印章管理执行情况；
9.执行本部采购支付流程（房租、物业、机票、绿植、办公用品等）；
10.负责本部日常办公后勤保障工作（对接前台、保洁、行政司机）；
11.负责董事长日常行程安排及会议预订；
12.完成上级交办的其他事项。

任职要求：
1.行政管理或企业管理统招本科及以上学历；
2.3年以上行政工作经验，有生产型企业工作经验优先；
3.熟练运用办公软件；
4.有较强的写作能力，可独立起草相关行政文件；
5.掌握基本商务礼仪，优秀的人际沟通能力及协调能力；
6.诚实正直、工作有条理，执行能力强；
7.可接受出差。
工作地址：
北京市海淀区西直门北大街60号首钢国际大厦11层
**********
博天环境集团股份有限公司
公司规模：
1000-9999人
公司性质：
上市公司
公司行业：
环保
公司主页：
http://www.poten.cn
公司地址：
北京市海淀区西直门北大街60号首钢国际大厦12A
查看公司地图
**********
财务经理J10621
博天环境集团股份有限公司
五险一金年底双薪绩效奖金带薪年假补充医疗保险定期体检节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
带薪年假
补充医疗保险
定期体检
节日福利
**********
职位月薪：10001-15000元/月 
工作地点：北京
发布日期：招聘中
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：1人
职位类别：财务经理
**********
岗位职责：
1、完善财务成本控制体系，负责进行成本预测及分析，做好整体公司的年度成本预算工作；
2、审核各公司各项成本支出的合理性，良好的控制各项支出符合预算额度；
3、定期编制成本分析预测及分析报告，分析成本差异，提出相应的改进建议；
4、审核各公司财务报表，出具合并财务报表；
5、配合上级完成其他相关工作。

任职要求：
1、统招本科及以上学历，会计、财务管理、审计等相关专业优先考虑；
2、5年以上财务相关工作经验；
3、1年以上团队管理经验；
4、遵守职业道德，具有团队合作精神，能承受一定的工作压力；
5、能接受短期出差。
工作地址：
北京市海淀区西直门北大街60号首钢国际大厦12A
**********
博天环境集团股份有限公司
公司规模：
1000-9999人
公司性质：
上市公司
公司行业：
环保
公司主页：
http://www.poten.cn
公司地址：
北京市海淀区西直门北大街60号首钢国际大厦12A
查看公司地图
**********
高级营销经理（土壤修复）
博天环境集团股份有限公司
五险一金年底双薪绩效奖金餐补带薪年假补充医疗保险定期体检节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
餐补
带薪年假
补充医疗保险
定期体检
节日福利
**********
职位月薪：10000-20000元/月 
工作地点：北京
发布日期：最近
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：5人
职位类别：业务拓展经理/主管
**********
公司在全国各地均有项目，各地均有此岗位需求，可根据个人意愿及业务需求灵活确定工作地点；
岗位职责：
1. 完成负责区域或行业的土壤修复市场项目信息搜集工作；
2. 根据公司年度考核合同额目标，对获取的土壤修复项目进行跟进，直至最终赢取；
3. 负责针对已有的项目进行公司产品宣导和项目落地工作，建立良好的客户关系；
4. 根据客户需求，组织安排技术交流和技术方案编写等工作；
5. 负责销售项目立项申请，审批后制定销售跟进方案，进行商务洽谈和投标；
6. 负责销售合同的跟踪洽谈、拟定、审核、签订、归档、传递等工作；
7. 建立并完善客户关系管理系统，收集、建立客户数据档案，针对性进行客户关系维护，分析客户反馈信息，与客户进行日常沟通和关系维护；

任职要求：
1.学历要求：本科及以上学历。
2.专业要求：市场营销、环境工程及相关专业。
3.必备专业知识：掌握土壤修复专业基础知识，了解相关设计标准和规范。
4.必备技能与能力：较强的沟通能力、组织协调能力、分析能力。
5.5年以上环保行业营销工作经验，土壤修复行业工作经历或政府营销经验者优先考虑。
工作地址：
北京市海淀区西直门北大街60号首钢国际大厦12A
**********
博天环境集团股份有限公司
公司规模：
1000-9999人
公司性质：
上市公司
公司行业：
环保
公司主页：
http://www.poten.cn
公司地址：
北京市海淀区西直门北大街60号首钢国际大厦12A
查看公司地图
**********
副总经理（土壤修复板块，分管工程项目）
博天环境集团股份有限公司
五险一金年底双薪绩效奖金餐补带薪年假补充医疗保险定期体检节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
餐补
带薪年假
补充医疗保险
定期体检
节日福利
**********
职位月薪：20001-30000元/月 
工作地点：北京
发布日期：最近
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：1人
职位类别：副总裁/副总经理
**********
岗位职责：
1、负责土壤修复项目的实施与全过程管理，负责组建项目执行团队；
2、负责土壤修复项目预算、收入确认和收付款资金管理；
3、负责土壤修复项目的进度、质量、SHE、成本的过程监管工作；
4、负责项目管理人员的日常考核、调配和培训管理；
5、负责协调解决项目执行过程技术、采购、施工等各个环节出现的各项问题；
6、负责配合市场投标工作，组织完成施工技术文件文件的编写工作；
7、完成公司项目控制中心交办的其他专项工作，完成上级领导交办的其它工作任务。
任职要求：
本科及以上学历，环境工程、水利水电工程、给水排水工程、机械电子工程等相关专业；
掌握项目工程相关知识，具备优秀的沟通能力、组织协调能力、分析能力、问题解决能力 、责任心、学习能力；
8年以上水处理项目工作经验，3年以上管理工作经验。土壤修复经历者优先。
工作地址：
北京市海淀区西直门北大街60号首钢国际大厦12A
**********
博天环境集团股份有限公司
公司规模：
1000-9999人
公司性质：
上市公司
公司行业：
环保
公司主页：
http://www.poten.cn
公司地址：
北京市海淀区西直门北大街60号首钢国际大厦12A
查看公司地图
**********
调试运营部经理J10655
博天环境集团股份有限公司
五险一金年底双薪绩效奖金带薪年假补充医疗保险定期体检节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
带薪年假
补充医疗保险
定期体检
节日福利
**********
职位月薪：10001-15000元/月 
工作地点：北京
发布日期：最近
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：1人
职位类别：项目经理/项目主管
**********
岗位职责：
1、负责调试运营部日常管理工作；
2、负责公司项目实施与全过程管理；
3、负责公司项目预算、收入确认和收付款资金管理；
4、负责公司项目的进度、成本、质量、SHE的过程监管工作；
5、负责项目执行人员的日常考核、调配和培训管理；
6、负责协调解决项目执行过程技术、采购、施工等各个环节出现的各项问题；
7、负责配合市场投标工作，组织完成施工技术文件文件的编写工作；


任职要求：
1、本科及以上学历，环境工程、给水排水工程等相关专业；
2、8年以上项目工作经验，4年以上项目管理工作经验，熟悉膜系统优先考虑；
3、具备优秀的团队管理能力，复杂问题的解决能力。

工作地址：
北京市海淀区西直门北大街60号首钢国际大厦12A
**********
博天环境集团股份有限公司
公司规模：
1000-9999人
公司性质：
上市公司
公司行业：
环保
公司主页：
http://www.poten.cn
公司地址：
北京市海淀区西直门北大街60号首钢国际大厦12A
查看公司地图
**********
会计主管
北京低碳清洁能源研究所
绩效奖金交通补助餐补通讯补贴带薪年假补充医疗保险定期体检免费班车
**********
福利:
绩效奖金
交通补助
餐补
通讯补贴
带薪年假
补充医疗保险
定期体检
免费班车
**********
职位月薪：面议 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：1人
职位类别：财务主管/总帐主管
**********
此岗位为北京低碳清洁能源研究所下属子单位新材料公司所招聘。
岗位职责：
1.负责报销单据的审核;
2.负责账务核算;
3.负责报表编制及上报工作；
4.负责财务ERP系统运营维护管理；
5.负责年度预算的编制、汇总、上报、分解、分析、总结等预算相关工作；
6.负责出具内部管理报表，预算管理报表，为管理者提供决策支持信息；
7.负责税务相关事项处理；
8.负责会计核算相关制度的编制；负责预算管理相关制度的编制；
9.负责完善报销工作流程；负责完善预算管理工作流程；
10.负责年度财务决算；负责外部审计、检查的沟通交流、负责各种内部审计检查的沟通交流；
11.与其他各部门工作的沟通协调；
12.负责领导交办的其他工作。

任职要求：
1.财务相关专业本科以上学历，高级会计师、注册会计师优先；
2.具有5年以上相关工作经历，熟练使用相关财务软件，SAP优先,熟悉国资委久其系统优先；
3.北京市户口优先。
4.具有较高的政治素质和较强的执行力，具有良好的职业素养，遵纪守法，勤勉尽责，无不良记录。
5.具有良好的学习能力、较强的沟通协调能力、调查研究能力、团队合作能力和较强的文字功底。
6.具有履行岗位职责所必需的专业知识，熟悉相关政策和法律法规。
7.具有良好的心理素质和能够正常履行职责的身体素质。

工作地址：
北京市昌平区未来科技城神华低碳001信箱
**********
北京低碳清洁能源研究所
公司规模：
100-499人
公司性质：
国企
公司行业：
环保
公司地址：
北京市昌平区未来科技城神华低碳001信箱
**********
化工过程动态模拟与控制 工程师
北京低碳清洁能源研究所
绩效奖金交通补助餐补通讯补贴带薪年假补充医疗保险定期体检免费班车
**********
福利:
绩效奖金
交通补助
餐补
通讯补贴
带薪年假
补充医疗保险
定期体检
免费班车
**********
职位月薪：面议 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：硕士
招聘人数：1人
职位类别：化工工程师
**********
岗位职责：
1.    Responsible for dynamic simulation, control model and algorithm development for chemical processes, improving process performances;
负责化工过程动态模拟、控制模型及算法开发，提高过程性能；
2.    Designing and conducting plans for related experiments, correcting model parameters according to experimental data；
根据需要开展相关实验工作，制定并设计实验方案，根据实验数据进行模型参数修正；
3.    Provide timely, accurate and detailed reports and presentations；
提供准时，准确和详尽的工作报告和汇报。
 任职要求：
1. Ph.D, or experienced Master;
博士或经验丰富的硕士；
 2. Degrees in chemical engineering, automation or related areas;
化工、自动化等专业毕业；
 3.  Very strong knowledge and understanding in process simulation, control and optimization;
深入理解和掌握过程模拟、控制和优化等知识；
 4. Familiar with simulation software such as Simulink, Aspen, understand advanced process control software;
熟悉Simulink, Aspen等模拟软件使用，了解先进过程控制软件；
 5.  Experience with process dynamic simulation, reactor model development , advanced process control or field operation is preferred;
具有过程动态模拟、反应器模型开发、先进过程控制或实际装置运转经验者优先；
 6. Team spirits and good communication and coordination skills;
具有良好的团队精神，以及良好的沟通和协调能力；
 7.  Independent thinking and innovation ability, effectively finishing work and results-oriented ;
具有独立思考和创新能力，能够以结果为导向，独立有效完成工作；
 8.  Strong verbal and written communication skills in both English and Chinese;
熟练掌握英语，英语作为工作语言，无障碍交流。
  工作地址：
北京市昌平区未来科技城神华低碳001信箱
**********
北京低碳清洁能源研究所
公司规模：
100-499人
公司性质：
国企
公司行业：
环保
公司地址：
北京市昌平区未来科技城神华低碳001信箱
**********
水处理 主管／高级工程师
北京低碳清洁能源研究所
**********
福利:
**********
职位月薪：面议 
工作地点：北京
发布日期：2018-03-10 11:09:43
工作性质：全职
工作经验：5-10年
最低学历：硕士
招聘人数：1人
职位类别：水处理工程师
**********
岗位职责：
招聘岗位属于工艺工程中心水处理与分离工程部门，工作内容是参与工业废水处理的关键技术研发、系统放大和工艺包设计工作。主要的研发内容包括概念研发和分析、基础研究、技术开发、概念设计和工程设计等。

任职要求：
1.       硕士以上学历，化工、环境工程等相关专业
2.       5年以上水处理相关工艺设计工作经验
3.       熟悉工业废水处理基本工艺，水处理单元操作，水处理工程设计等
4.       基础知识扎实，有较强的水处理工艺设计能力，能够独立或带领团队完成水处理新技术的分析评价和工艺包设计。
5.       积极向上，对新技术研发和推广富有热情。
6.       可以读写英文文献和技术报告，日常英语口语交流流利
7.       工作敬业认真，具备良好的团队精神，有较强的组织和领导能力。
 符合如下条件者，可优先考虑：
1.       知名水处理相关设计院或工程公司工作经历
2.       在如下领域有丰富经验：水处理工程设计、水处理装置运行等
3.       承担过项目负责人或类似工作
4.       有过独立完成研发任务的经验

工作地址：
北京市昌平区未来科技城神华低碳001信箱
**********
北京低碳清洁能源研究所
公司规模：
100-499人
公司性质：
国企
公司行业：
环保
公司地址：
北京市昌平区未来科技城神华低碳001信箱
**********
质量管理经理J10487
博天环境集团股份有限公司
五险一金绩效奖金带薪年假补充医疗保险定期体检员工旅游节日福利
**********
福利:
五险一金
绩效奖金
带薪年假
补充医疗保险
定期体检
员工旅游
节日福利
**********
职位月薪：6000-12000元/月 
工作地点：北京-密云县
发布日期：最近
工作性质：全职
工作经验：5-10年
最低学历：不限
招聘人数：1人
职位类别：质量管理/测试经理
**********
工作职责：
1.负责公司质量方针、质量目标的贯彻落实，改善公司的质量管理工作；
2.负责公司各种质量管理制度的制定与实施，以及各种质量管理活动的执行与推动；
3.组织质量控制人员、质量检验人员对专业技术知识的学习，建立一支高素质的质量控制、质量检验队伍；
4.负责进料、在制品、成品的质量标准和检验规程的制定与执行，监督指导各项质量检验工作；
5.处理质量异常，协助处理客户投诉与退货的调查、原因分析，并拟定改善措施；
6.组织不合格品的控制，维护和完善不合格品的预防和纠正措施，并予以督导执行；
7.负责检验仪器、量具、实验设备的管理工作；
8.监督、检验质量记录，组织分析质量数据；
9.负责质量管理信息搜集、传达、回复，以及质量成本的分析与控制工作；
10.维护、完善和实施公司质量管理体系，组织编写质量手册等质量文件，并进行审核；
11.组织和协调公司产品的认证工作，负责对原材料供应商的评估；
12.召开现场质量工作会议。


任职资格：
1.化学及相关专业；
2.对质量管理体系熟悉，具备良好的沟通能力、分析能力、问题解决能力及执行能力；
3.本科5年以上生产质量管理经验，硕士3年以上生产质量管理经验；
工作地址：
北京市密云区经济开发区
**********
博天环境集团股份有限公司
公司规模：
1000-9999人
公司性质：
上市公司
公司行业：
环保
公司主页：
http://www.poten.cn
公司地址：
北京市海淀区西直门北大街60号首钢国际大厦12A
查看公司地图
**********
视频编导(广告部)
启迪桑德环境资源股份有限公司
五险一金绩效奖金年终分红餐补通讯补贴定期体检免费班车节日福利
**********
福利:
五险一金
绩效奖金
年终分红
餐补
通讯补贴
定期体检
免费班车
节日福利
**********
职位月薪：7000-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：广告制作执行
**********
任职要求：
1、本科及以上学历；
2、1年或以上相关工作经历。
岗位职责：
1、熟练使用视频编辑软件，对企业视频素材进行粗编以及精编的剪辑；
2、具有一定的文字写作基础；
3、良好摄影、摄像水平及图片、视频后期处理技能，负责专题视频的策划、拍摄及制作；
4、工作积极，良好的沟通协调能力及团队合作精神。
工作地址：
北京市通州区马驹桥金桥科技产业基地启迪桑德园区
**********
启迪桑德环境资源股份有限公司
公司规模：
10000人以上
公司性质：
上市公司
公司行业：
环保
公司主页：
www.tus-sound.com
公司地址：
北京市通州区马驹桥金桥科技产业基地启迪桑德园区
查看公司地图
**********
膜材料研发工程师
博天环境集团股份有限公司
五险一金年底双薪绩效奖金通讯补贴带薪年假补充医疗保险定期体检节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
通讯补贴
带薪年假
补充医疗保险
定期体检
节日福利
**********
职位月薪：10001-15000元/月 
工作地点：北京-密云县
发布日期：最近
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：水处理工程师
**********
岗位职责：
参与水处理膜材料及应用相关项目开发，能独立承担研发项目中膜材料或膜系统应用领域的研发工作

任职要求：
1、硕士研究生毕业，两年以上工作经验，本科有5年以上分离膜行业从业经验；
2、能独立完成试验，输出完整数据报告；
3、高分子、化学工程、环境工程等专业或其它相关专业；
4、有分离膜相关的研发经验或项目参与经验，如有加筋、带衬中空纤维膜，疏水膜应、或热致相法膜开发经验者优先考虑；
5、有良好的沟通能力和团队协作意识；
6、办公地点北京市密云经济开发区。

工作地址：
北京市密云经济开发区
查看职位地图
**********
博天环境集团股份有限公司
公司规模：
1000-9999人
公司性质：
上市公司
公司行业：
环保
公司主页：
http://www.poten.cn
公司地址：
北京市海淀区西直门北大街60号首钢国际大厦12A
**********
工艺设备工程师
启迪桑德环境资源股份有限公司
五险一金年终分红包吃交通补助免费班车员工旅游节日福利不加班
**********
福利:
五险一金
年终分红
包吃
交通补助
免费班车
员工旅游
节日福利
不加班
**********
职位月薪：8001-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：机械设备工程师
**********
岗位职责：
1、负责完成餐厨处理项目前期方案编写、投标书及工程技术方案等；
2、协助项目经理制定项目总体实施计划和方案，制定本专业的详细施工计划和方案；
3、负责施工过程中的技术支持，现场指导、协调、调试、培训；
4、配合业务部门完成项目投标、项目谈判、技术交流、签约等工作；
5、审核安装专业施工图纸，提出合理化建议；
6、完成固废项目建设计划，并配合项目公司和项目部按时完成固废项目建设计划。

任职要求：
1、大专及以上学历，环境工程、机电相关专业；
2、具有5年以上餐厨相关机电安装工作经验；
3、熟悉或了解餐厨项目管理流程；
4、能适应长期出差。
工作地址：
北京市通州区马驹桥金桥科技产业基地启迪桑德园区
**********
启迪桑德环境资源股份有限公司
公司规模：
10000人以上
公司性质：
上市公司
公司行业：
环保
公司主页：
www.tus-sound.com
公司地址：
北京市通州区马驹桥金桥科技产业基地启迪桑德园区
查看公司地图
**********
电力系统工程师
北京低碳清洁能源研究所
绩效奖金交通补助餐补通讯补贴带薪年假补充医疗保险定期体检免费班车
**********
福利:
绩效奖金
交通补助
餐补
通讯补贴
带薪年假
补充医疗保险
定期体检
免费班车
**********
职位月薪：面议 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：硕士
招聘人数：1人
职位类别：电力系统研发工程师
**********
岗位职责：
1. 负责微电网系统的优化配置计算和分析；
2. 负责微电网系统的稳态/暂态分析和继电保护设置；
3. 负责微电网系统经济运行和能量管理策略开发；
 任职要求：
1.博士毕业，或硕士毕业5 年；
2.电气/电力系统自动化、电力电子专业毕业；
3.具有微电网系统研究背景；
4.精通电力系统规划、分析及继电保护等，具有微电网实际项目开发经验者
优先；
5.具有独立思考和创新能力，自我学习能力强，能够以结果为导向，独立有
效完成工作；
6.具有良好的沟通和协调能力，以及良好的团队合作精神；
7.熟悉电力配电网结构和电气设备；
8.熟练掌握Matlab/Simulink，PSCAD 等仿真软件；
9.具有良好的英语口语、写作能力，可以将英语作为工作语言。
工作地址：
北京市昌平区未来科技城神华低碳001信箱
**********
北京低碳清洁能源研究所
公司规模：
100-499人
公司性质：
国企
公司行业：
环保
公司地址：
北京市昌平区未来科技城神华低碳001信箱
**********
质检员
博天环境集团股份有限公司
五险一金包住带薪年假全勤奖补充医疗保险定期体检绩效奖金
**********
福利:
五险一金
包住
带薪年假
全勤奖
补充医疗保险
定期体检
绩效奖金
**********
职位月薪：4001-6000元/月 
工作地点：北京-密云县
发布日期：最近
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：生产物料管理（PMC）
**********
岗位职责：
1.负责外协件、化工原材料的到厂检验，防止不合格物料流入生产；负责来料质量异常的妥善处理。
2.负责检测仪器、设备日常正常使用、维护保养工作；
3.对原材料、外协件检验方法和标准提出改善意见和建议；
4.协助质检主管进行质量分析、数据录入、记录归档等相关事项；
5.做好检验记录，对原材的质量情况进行统计分析，并形成周报，月报，及时报告质检主管；
6.完成直接上级交给的工作。
任职要求：
1.大专以上学历，化工相关专业；
2.一年以上相关的质量检验工作和仪器使用方法等相关工作经验；
3.具有良好的沟通和协调能力；
具有高度的工作热情，工作认真、严谨和负责。
工作地址：
北京市密云区康宝路2号
查看职位地图
**********
博天环境集团股份有限公司
公司规模：
1000-9999人
公司性质：
上市公司
公司行业：
环保
公司主页：
http://www.poten.cn
公司地址：
北京市海淀区西直门北大街60号首钢国际大厦12A
**********
餐厨项目公司负责人
启迪桑德环境资源股份有限公司
五险一金年终分红包吃交通补助免费班车员工旅游节日福利不加班
**********
福利:
五险一金
年终分红
包吃
交通补助
免费班车
员工旅游
节日福利
不加班
**********
职位月薪：20001-30000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：10年以上
最低学历：大专
招聘人数：1人
职位类别：分公司/代表处负责人
**********
岗位职责：
1、组织拟订、修改和实施项目公司的管理政策、制度，以提高项目公司的管理水平；
2、主持编制项目公司、月度管理计划，并督促项目部成固废项目建设计划；
3、配合总公司相关部门对固废建设项目进行过程检查，并监督、检查项目部问题的整改情况；
4、指导项目公司人员分派工作，并指导项目部各项日常工作；
5、协调政府、建设方、监理及各相关方，组织固废项目建设按照计划开展并完成公司建设目标，并对建设人员进行监督考核；
6、完成上级领导临时交办的工作任务。

任职要求：
1、工民建、建筑工程、安装工程、电力工程等相关专业大专以上学历；
2、具有中级及以上，建造师等管理类相关证书；
3、具有8年以上工作经验，5年以上同岗位工作经验，熟悉环保工程固废项目管理；
4、掌握餐厨项目管理流程；
5、具有一定的决策能力、经营管理能力、计划与组织能力、领导能力、指挥能力、控制与协调能力、人员管理能力和项目管理能力。
工作地址：
北京市通州区马驹桥金桥科技产业基地启迪桑德园区
**********
启迪桑德环境资源股份有限公司
公司规模：
10000人以上
公司性质：
上市公司
公司行业：
环保
公司主页：
www.tus-sound.com
公司地址：
北京市通州区马驹桥金桥科技产业基地启迪桑德园区
查看公司地图
**********
总账主管
启迪桑德环境资源股份有限公司
五险一金年终分红包吃交通补助免费班车员工旅游节日福利不加班
**********
福利:
五险一金
年终分红
包吃
交通补助
免费班车
员工旅游
节日福利
不加班
**********
职位月薪：8001-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：1人
职位类别：财务主管/总帐主管
**********
岗位职责：
1、完成项目公司的资金计划的上报、公司各类费用单据的审核，凭证的审核、整理、装订及保管工作；财务报表的审核工作；
2、完成向控股各项目公司传达信息、汇总各类报表；
3、完成各项目公司出纳、会计的招聘工作及财务人员的离职监交工作；对新入职财务人员培训、日常财务工作的指导与监督；

任职要求：
1、会计、财务管理等专业大专及以上学历；
2、具有5年相关项目财务管理工作经验；
3、具有中级职称或注册会计师证书者优先考虑；
4、掌握一定的在建项目财务核算及管理相关业务知识。

附加说明：
1、企业文化好：企业内部学院，经常组织培训，公司办公环境优美，没有加班文化，员工活动多；
2、福利多：员工食堂，公司买单，班车早晚接送，六险一金，在公司工作一定时间后符合条件有相应期权等。
工作地址：
北京市通州区马驹桥金桥科技产业基地启迪桑德园区
**********
启迪桑德环境资源股份有限公司
公司规模：
10000人以上
公司性质：
上市公司
公司行业：
环保
公司主页：
www.tus-sound.com
公司地址：
北京市通州区马驹桥金桥科技产业基地启迪桑德园区
查看公司地图
**********
研发工程师
启迪桑德环境资源股份有限公司
五险一金年底双薪通讯补贴定期体检免费班车员工旅游高温补贴节日福利
**********
福利:
五险一金
年底双薪
通讯补贴
定期体检
免费班车
员工旅游
高温补贴
节日福利
**********
职位月薪：8000-12000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：硕士
招聘人数：3人
职位类别：机械研发工程师
**********
岗位职责：1、环保设备的研发设计2、秸秆厌氧项目研发

任职要求：1、硕士，环境工程专业2、三年以上机械或环保设备研发工作经验，环保设备研发工作经验优先
工作地址：
北京市通州区马驹桥金桥科技产业基地环宇路3号
**********
启迪桑德环境资源股份有限公司
公司规模：
10000人以上
公司性质：
上市公司
公司行业：
环保
公司主页：
www.tus-sound.com
公司地址：
北京市通州区马驹桥金桥科技产业基地启迪桑德园区
查看公司地图
**********
动画制作
北京良业环境技术有限公司
**********
福利:
**********
职位月薪：8001-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：5人
职位类别：多媒体/动画设计
**********
岗位职责：
1、负责相关宣传媒体（如大屏幕、室外LED媒体墙）播放的视频短片制作；
2、根据设计主题需要，熟练使用各种影视后期、剪辑、三维等软件完成相应的成片效果；
3、能独立解决视频中艺术创意、素材搜集、特效制作、音乐等的相关问题。
任职要求：
1、数字影视、动画、广告、美术或相关专业，有工作三年工作经验的；
2、能熟练使用AE、3DS、PS等软件，独立完成项目的剪辑、特效、配音等制作过程；
3、擅长后期合成、剪辑、动画特效。

工作地址：
北京市朝阳区北苑路北北辰新纪元2号楼2102
**********
北京良业环境技术有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司地址：
北京市朝阳区北苑路北北辰泰岳大厦
查看公司地图
**********
项目管理会计
启迪桑德环境资源股份有限公司
五险一金年终分红包吃交通补助免费班车员工旅游节日福利不加班
**********
福利:
五险一金
年终分红
包吃
交通补助
免费班车
员工旅游
节日福利
不加班
**********
职位月薪：8001-10000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：5-10年
最低学历：大专
招聘人数：1人
职位类别：财务主管/总帐主管
**********
岗位职责：
1、完成项目公司的资金计划的上报、公司各类费用单据的审核，凭证的审核、整理、装订及保管工作；财务报表的审核工作；
2、完成向控股各项目公司传达信息、汇总各类报表；
3、完成各项目公司出纳、会计的招聘工作及财务人员的离职监交工作；对新入职财务人员培训、日常财务工作的指导与监督；
4、完成领导安排的其他工作。

任职要求：
1、会计、财务管理等专业大专及以上学历；
2、具有5年相关项目财务管理工作经验；
3、具有中级职称或注册会计师证书者优先考虑；
4、掌握一定的在建项目财务核算及管理相关业务知识。

附加说明：
1、企业文化好：企业内部学院，经常组织培训，公司办公环境优美，没有加班文化，员工活动多；
2、福利多：员工食堂，公司买单，班车早晚接送，六险一金，在公司工作一定时间后符合条件有相应期权等。
工作地址：
北京市通州区马驹桥金桥科技产业基地启迪桑德园区
**********
启迪桑德环境资源股份有限公司
公司规模：
10000人以上
公司性质：
上市公司
公司行业：
环保
公司主页：
www.tus-sound.com
公司地址：
北京市通州区马驹桥金桥科技产业基地启迪桑德园区
查看公司地图
**********
客服
北京清新全家环保科技有限公司
绩效奖金加班补助全勤奖交通补助通讯补贴带薪年假创业公司五险一金
**********
福利:
绩效奖金
加班补助
全勤奖
交通补助
通讯补贴
带薪年假
创业公司
五险一金
**********
职位月薪：4000-8000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：5人
职位类别：其他
**********
1、全职全能客服
2、处理淘宝售前咨询、产品解说、下单工作
3、处理售后投诉，降低因客户退单所造成的赔付率
4、旺旺工作，及时处理线上售后问题，旺旺流程售后问题，安慰客户。对已经流失的客户进行再激活工作，对要流失的客户进行挽留工作
5、可以完成上级交代的案头工作，对互联网客户进行分类制表等工作。
任职要求：
1.客服工作1年以上，同时投诉处理经验1年以上
2、有良好沟通能力及学习能力,注重团队协作；
3、能吃苦耐劳,具备基本的抗压能力，能适应倒班；
4、年龄18-35，男女不限，有电商客服或教育行业经验优先。
5、熟悉售前售后处理流程及熟练掌握售后处理技巧
6、专科以上学历，熟练使用计算机以及办公软件
7、应届生最好是环保、化工专业毕业
工作地址：
朝阳区中国铁建广场d座1508
查看职位地图
**********
北京清新全家环保科技有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
环保
公司地址：
朝阳区中国铁建广场d座1508
**********
电池材料 经理
北京低碳清洁能源研究所
绩效奖金交通补助餐补通讯补贴带薪年假补充医疗保险定期体检免费班车
**********
福利:
绩效奖金
交通补助
餐补
通讯补贴
带薪年假
补充医疗保险
定期体检
免费班车
**********
职位月薪：面议 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：10年以上
最低学历：博士
招聘人数：1人
职位类别：其他
**********
岗位职责：
1 主持研发部门技术及技术管理工作，包括新型电池电极材料开发，中试及放大生产，电池工艺优化，性能评估及应用场景示范。
2. 针对市场需求及技术发展方向，完成项目申请，制定项目计划，带领团队技术攻关，确保项目按时完成。
3. 负责或协助新产品的转化，与市场积极对接，完成产品的示范及市场化。
4. 日常团队建设管理，指导培养团队成员。
 任职要求：
1.  具有丰富锂离子电池材料/电池技术开发经验，博士学历，八年以上相关研发经验。
2.  了解锂离子电池的生产工艺和各种原材料特性，知识面较广，了解领域新技术进展，对电池工艺有深刻的理解，了解锂电池行业技术的发展趋势；
3.  对电池制造工艺了解，熟悉电池制造工艺改善及新工艺的应用；熟悉各种电池体系；
4.  在团队管理方面有较强的领导技巧和才能，善于与人合作；
5.  在学术和工业领域均有历练，在行业中有一定的人脉，有较好的个人综合素质。
6.  优秀的英文读写沟通能力。

工作地址：
北京市昌平区未来科技城神华低碳001信箱
**********
北京低碳清洁能源研究所
公司规模：
100-499人
公司性质：
国企
公司行业：
环保
公司地址：
北京市昌平区未来科技城神华低碳001信箱
**********
清单编制实习生
北京中煤注册安全工程师事务所有限公司
**********
福利:
**********
职位月薪：2001-4000元/月 
工作地点：北京
发布日期：最新
工作性质：实习
工作经验：不限
最低学历：本科
招聘人数：6人
职位类别：实习生
**********
u 项目简介
北京安全生产监督管理局于2018年初委托我公司开展“北京市安全生产事故隐患排查“一企一标准、一岗一清单”编制隐患清单检查项目”，为北京市约100家生产企业提供相关技术咨询服务，指导协助相关生产经营单位（涉及矿山企业、危险化学品企业、工业企业等）制定隐患排查责任制度、隐患排查管理制度、个性化隐患排查自查标准、岗位隐患排查标准编制工作等工作，并计划于2018年9月前完成该项目。
u 项目要求
1、要求本科或研究生在读学生；
2、专业不限，工程类相关专业优先；
3、要求时间相对充裕，能够在项目周期内参与项目各项工作（包括内外部培训、现场调研、方案及报告编写等），并至少为20余家生产经营单位提供相关技术服务；
4、要求工作认真、责任心强，具有较强的组织协调能力，能够服从公司统一部署安排；
5、要求严格遵守执行《中国地方煤矿有限公司“一企一标准、一岗一清单”编制检查项目外聘专业技术人员管理办法》。
u 招聘人数
6人。
u 实习时间
2018年3月至2018年8月（根据项目进度略有调整）
不要求坐班，根据进度按时完成要求的工作量。
u 实习地点
北京。
u 实习待遇
根据个人完成的企业数量计算劳务费。按照完成一家企业给予500元/家计算。
实习结束后，可出具实习证明。
u 其它事项
请有意者将个人简历发至邮箱2047173758@qq.com，联系电话：010-64256424，我们将及时联系您。

工作地址：
东城区安定门外大街200号
**********
北京中煤注册安全工程师事务所有限公司
公司规模：
20-99人
公司性质：
国企
公司行业：
专业服务/咨询(财会/法律/人力资源等)
公司地址：
东城区安定门外大街200号
**********
策划经理
绿景盛世(北京)环境技术服务有限公司
住房补贴五险一金交通补助全勤奖绩效奖金餐补房补通讯补贴
**********
福利:
住房补贴
五险一金
交通补助
全勤奖
绩效奖金
餐补
房补
通讯补贴
**********
职位月薪：8001-10000元/月 
工作地点：北京
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：市场策划/企划经理/主管
**********
1.公司品牌策划，公司项目运行策划、宣传活动等；
2.具备策划方案编撰能力，文字功底强，方案切实可行；
3.思辨清晰、语言表达能力强；
4.具有大数据理念及策划数据项目能力；
工作地址：
北京市东城区东四北大街瑞城亿兴大厦
查看职位地图
**********
绿景盛世(北京)环境技术服务有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
环保
公司主页：
www.lvjingshengshi.com
公司地址：
北京市门头沟区石龙经济开发区永安路20号3号楼B1-6009室
**********
销售人员
北京东方海联科技发展有限公司
住房补贴五险一金绩效奖金通讯补贴交通补助带薪年假节日福利员工旅游
**********
福利:
住房补贴
五险一金
绩效奖金
通讯补贴
交通补助
带薪年假
节日福利
员工旅游
**********
职位月薪：8001-10000元/月 
工作地点：北京
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：5人
职位类别：销售代表
**********
1、年龄35岁以下，大专以上学历，户口性别不限；
2、能单独完成自身任务；
3、制定销售计划，同时能带领团队完成整体任务；
4、开发客户资源，提供良好的售后服务，客户维系、市场分类等相关业务事宜；
5、从事建筑行业销售经验者优先考虑；
6、具有很强的责任心和独立开展工作的能力；
7、有驾照及实际驾驶经验者优先。
福利与待遇：
1.工作时间八小时制：上午8：30-12：00至下午13：00-17：00（无加班统计）
2.享受国家正规休假制度：享受国家规定的节假日；
3.享有年终奖金，年假，差补，不定时聚餐及其他福利；
4.优秀应届毕业生有完善的培训和晋升机会；
5.五险一金。
  工作地址：
北京崇文区夕照寺中街4号星海宏昌大厦A409
查看职位地图
**********
北京东方海联科技发展有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
环保
公司主页：
http://bjdfhl.net
公司地址：
北京崇文区夕照寺中街4号星海宏昌大厦A409
**********
会计
北京清新全家环保科技有限公司
加班补助全勤奖交通补助节日福利带薪年假
**********
福利:
加班补助
全勤奖
交通补助
节日福利
带薪年假
**********
职位月薪：4500-6500元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：会计/会计师
**********
北京清新全家环保科技有限公司，位置位于地铁十三号线北苑站下车500米中国铁建广场，上班时间早9.00—晚18.00。基础底薪4500—6500元，含餐补，交通补助，加班补助，全勤补助。要求对电脑软件（excl、word）使用熟练，复核日常报销凭证，收付日常现金及票据。保管和费用报销。序时准确登记现金、银行日记账，做好对账工作，及时编制银行存款余额调节表。根据薪资制度，做好工资单的复核工作，按时发放员工薪资。学历要求：大专及大专以上。财务相关专业，工作满两年以上。熟悉国家政策，会计法规，了解税务法规和相关税收政策。熟悉银行结算业务和国税报税流程。招聘微信13811422929
工作地址：
朝阳区中国铁建广场d座1508
**********
北京清新全家环保科技有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
环保
公司地址：
朝阳区中国铁建广场d座1508
**********
质量主管(013972)(职位编号：Hanergy013972)
北京汉能光伏投资有限公司
五险一金绩效奖金加班补助免费班车定期体检
**********
福利:
五险一金
绩效奖金
加班补助
免费班车
定期体检
**********
职位月薪：15001-20000元/月 
工作地点：北京
发布日期：最近
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：质量管理/测试主管
**********
岗位职责:
负责装备供应链的全面质量控制；装备供应商开发认证中的质量体系管控；装备的过程品质管控；装备质量的验收及质量异常处理
协助参与相关制度的制定与培训；
执行周、月度计划；
装备质量检验、控制及提升；供应商及全过程质量体系建立及提升；
协助ISO9001，14001，OHSAS18001体系搭建；
收集、分类、统计、分析、处理、传递及应用质量管理信息，并进行综合管控及质量改善；
参与团队活动；
参与部门业务培训，学习新制度，对外组织制度培训；

任职资格:
本科及以上学历，机电一体化、电子类工科专业优先；
3年以上中大型企业相关行业质量管理工作经验；
熟悉质量管理知识，能够熟练运用相关质量工具；
能够熟练使用8D、控制图、QFD等质量分析工具
英语听说读写流利；
工作地址：
北京朝阳区安立路A-0
**********
北京汉能光伏投资有限公司
公司规模：
10000人以上
公司性质：
上市公司
公司行业：
能源/矿产/采掘/冶炼
公司主页：
null
公司地址：
北京市朝阳区北辰西路8号北辰世纪中心B座
**********
知识产权专利管理经理/专家
北京汉能光伏投资有限公司
每年多次调薪五险一金绩效奖金包吃通讯补贴带薪年假免费班车
**********
福利:
每年多次调薪
五险一金
绩效奖金
包吃
通讯补贴
带薪年假
免费班车
**********
职位月薪：15001-20000元/月 
工作地点：北京
发布日期：最近
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：30人
职位类别：知识产权/专利顾问/代理人
**********
岗位职责：
1、根据公司战略规划对不同产品线的产品专利进行趋势分析、技术分析、申请人分析、地域分析等； 
2、挖掘公司产品技术领域的核心专利，结合专利的保护范围给出相应的专利战略布局；
3、负责专利培训工作的组织与实施；对产品经理、技术人员、设计人员进行专利查新、技术交底书的撰写等培训； 
4、负责专利申请的内部审批、技术人员申请专利流程控制，进行专利上报文件内容的审核，提出建议与修改意见；
 5、负责提供涉及知识产权相关权利证明文件，协助法务部开展相关知识产权权利维护、纠纷等工作； 
6、负责专利分析工程师团队的管理；
任职资格：
1、熟悉知识产权相关法律，独立承担过相关知识产权工作且具有相关工作经验3年及以上；
2、熟悉掌握相关的政策、制度、程序、申报系统软件及申办审批流程； 
3、英语六级以上，具有较强的文字表达能力和理解能力；
4、具有良好的沟通协调能力，组织执行能力和团队精神； 
5、光伏、电子行业背景优先。 
工作地址：
北京市朝阳区酒仙桥电通广场
**********
北京汉能光伏投资有限公司
公司规模：
10000人以上
公司性质：
上市公司
公司行业：
能源/矿产/采掘/冶炼
公司主页：
null
公司地址：
北京市朝阳区北辰西路8号北辰世纪中心B座
**********
招聘总监(014184)(职位编号：Hanergy014184)
北京汉能光伏投资有限公司
**********
福利:
**********
职位月薪：30001-50000元/月 
工作地点：北京
发布日期：最近
工作性质：全职
工作经验：10年以上
最低学历：本科
招聘人数：1人
职位类别：人力资源总监
**********
岗位职责:
1、负责公司高端人才招聘，执行干部选拔外部渠道吸引及挖潜；
2、组织和协助公司组织架构设计和岗位设置，组织梳理和完善公司的岗位描述说明书；
3、分析、选择、维护和完善招聘渠道，收集、调研、选择招聘供应商，建立合格招聘供应商资料库，并进行动态管理；
4、改进公司人才选拔体系，完善公司人才储备库，收集、分析行业人才状况，了解业内人员动态；
5、负责重点岗位和中高级人才的甄选、面试以及OFFER沟通发放等；
6、负责定期的招聘报告总结及分析以及招聘策略的制定等；
7、协助上级领导完成其他工作。

任职资格:
1、统招院校本科以上学历，人力资源管理、心理学、管理等相关专业；
2、10年以上大中型企业的人力资源管理相关工作经验，其中至少有8年招聘工作经验，具有高端人才招聘经验者优先考虑；
3、熟悉各种招聘渠道、测评工具和面试技巧，判断力强，洞察力敏锐，能独立完成高级职位的面试工作；
4、具备行业mapping资源及能力，熟悉新能源（光伏）/金融/工业装备等行业或职能模块高管资源者优先；
5、具有优秀的学习能力、强烈的自我激励和开创精神、出色的沟通协调能力。
工作地址：
北京朝阳区安立路0-A号（奥森公园北园东门南100米）
**********
北京汉能光伏投资有限公司
公司规模：
10000人以上
公司性质：
上市公司
公司行业：
能源/矿产/采掘/冶炼
公司主页：
null
公司地址：
北京市朝阳区北辰西路8号北辰世纪中心B座
**********
结构工程师(013831)(职位编号：Hanergy013831)
北京汉能光伏投资有限公司
**********
福利:
**********
职位月薪：15001-20000元/月 
工作地点：北京
发布日期：最近
工作性质：全职
工作经验：5-10年
最低学历：不限
招聘人数：3人
职位类别：土木/土建/结构工程师
**********
岗位职责:
完成项目现场勘测，配合销售经理及经销商进行项目洽谈，解答销售经理及经销商在销售过程中遇到的结构专业相关技术问题；
按时完成组件排布图、结构图、方案、建议书、材料清单等设计工作；
为采购、下单提供必要的技术确认及支持；及时完成安装订单技术审核、确认；
对经销商进行现场安装技术指导，及时解决安装并网过程中结构专业技术问题；
参与项目安装验收工作，参与安装商的考评工作；
根据业务发展需要，做好对经销商、安装商及公司销售经理相关专业技术培训；
处理客户或经销商反馈的售后问题，重点解决结构专业问题；
按时完成上级领导安排的临时工作；

任职资格:
本科以上学历，土木工程、结构设计等相关专业；
3年及以上结构专业设计、施工等工作经验；
精通结构专业相关知识，熟悉工民建、光伏行业规范；熟悉光伏发电系统支架结构和支架基础设计的相关理论，能够对光伏系统结构与建筑屋顶结合方式进行载荷计算及可靠性验算，能够对结构施工图进行审核。
精通CAD绘图、PKPM、3D3S结构设计软件，熟练使用各种办公软件；
具有良好的组织能力、沟通能力、协调能力，较强的现场管理能力，责任心强；
工作地址：
北辰世纪中心B座
**********
北京汉能光伏投资有限公司
公司规模：
10000人以上
公司性质：
上市公司
公司行业：
能源/矿产/采掘/冶炼
公司主页：
null
公司地址：
北京市朝阳区北辰西路8号北辰世纪中心B座
**********
售后支持工程师(014103)(职位编号：Hanergy014103)
北京汉能光伏投资有限公司
**********
福利:
**********
职位月薪：15001-20000元/月 
工作地点：北京
发布日期：0002-01-01 00:00:00
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：30人
职位类别：售前/售后技术支持管理
**********
工作职责
1、 参与内部产品测试 
2、 负责企业产品在实施安装和后期维护过程中出现的技术问题
3、 能独立负责项目、用户技术问题的定位、跟踪、处理，并对问题做分类和归档处理 
4、 建立并维护知识库。
任职资格
1、大型生产制造企业售后技术支持相关经验；
2、熟悉光伏组件、逆变器、配电柜等相关产品经验者优先； 
3、可以接受全球出差者优先； 
4、英文熟练者优先。
工作地址：
北京朝阳区安立路0-A号（奥森公园北园东门南100米）
**********
北京汉能光伏投资有限公司
公司规模：
10000人以上
公司性质：
上市公司
公司行业：
能源/矿产/采掘/冶炼
公司主页：
null
公司地址：
北京市朝阳区北辰西路8号北辰世纪中心B座
**********
自动化工程师(014148)(职位编号：Hanergy014148)
北京汉能光伏投资有限公司
**********
福利:
**********
职位月薪：10001-15000元/月 
工作地点：北京
发布日期：最近
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：1人
职位类别：自动化工程师
**********
岗位职责:
1、明确工艺需求，开发新设备；
2、熟练使用CAD完成自动化设计布局；
3、熟悉Solidworks等绘图软件，与供应商一起完成设备设计方案；
4、熟悉零部件加工制造方法，电气、PLC等连接方法，指导供应商完成设备的设计、制造，实时把控设备制造进度；
5、熟悉二次配接口的类型及连接方式。与厂务工程师对接，协助厂务工程师进行厂房的设计，建造；
6、到工厂完成设备的安装、调试及验收；
7、将设备交付给生产基地，并培训基地操作人员及设备工程师使用和维护设备；
8、处理设备在生产过程中出现的故障；
9、在产品、工艺出现升级更新时，完成设备的升级改造。

任职资格:
1、有2年以上自动化设备经验，熟悉电气、机械相关国家标准；
2、本科及以上学历；
3、熟悉CAD，熟悉电气、机械常见的标准零部件；
4、有电气设计、机械设计基础者优先；
5、有光伏行业从业经验者优先；
6、有电气、机械安装经验，设备故障处理能力强；
7、较好的英语沟通能力；
8、有良好的团队意识及工作责任心。
工作地址：
北京
**********
北京汉能光伏投资有限公司
公司规模：
10000人以上
公司性质：
上市公司
公司行业：
能源/矿产/采掘/冶炼
公司主页：
null
公司地址：
北京市朝阳区北辰西路8号北辰世纪中心B座
**********
大客户销售CEO (014102)(职位编号：Hanergy014102)
北京汉能光伏投资有限公司
**********
福利:
**********
职位月薪：70001-100000元/月 
工作地点：北京
发布日期：最近
工作性质：全职
工作经验：10年以上
最低学历：本科
招聘人数：1人
职位类别：客户总监
**********
岗位职责:
1、根据公司业务发展战略制定薄膜太阳能产品在BIPV（光伏建筑一体化）行业的大客户销售计划；
2、负责开拓国内外BIPV行业的大客户合作资源；
3、与市场部密切合作，拟定市场策略和渠道策略；
4、负责所属销售团队的管理，提高团队整体绩效，完成公司年度销售目标；

任职资格:
1、行业要求：深度了解（包括新型建材、幕墙、建筑一体化）产业格局及经营规律，熟悉品牌商或渠道商人脉。
2、5年以上相关行业拓展经验，有10年以上销售团队管理经验，千万以上单品销售额的成功案例。
3、有激情，有韧劲，良好的沟通及逻辑能力，团队协作能力，能适应高强度工作包括出差。
4、本科及以上学历，相关专业优先，会日常办公软件。
工作地址：
北京北辰
**********
北京汉能光伏投资有限公司
公司规模：
10000人以上
公司性质：
上市公司
公司行业：
能源/矿产/采掘/冶炼
公司主页：
null
公司地址：
北京市朝阳区北辰西路8号北辰世纪中心B座
**********
设备工程师(014140)(职位编号：Hanergy014140)
北京汉能光伏投资有限公司
**********
福利:
**********
职位月薪：10001-15000元/月 
工作地点：北京
发布日期：最近
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：1人
职位类别：电子/电器设备工程师
**********
岗位职责:
1、负责前段设备的装机调试及RAMP UP；
2、负责工艺监控，调试， 问题反馈，工艺参数分析，报告整理；
3、负责制定现场问题点的改善方案；
4、负责前段工艺工程师、技术员的培养、考核；
5、负责提升前段设备的产能；
6、负责前段设备安全、稳定、高效的生产；
7、协助部门经理进行本部门其他日常管理工作；
8、协助完成产品认证等方面工作。

任职资格:
1、本科及以上学历，化学、化工、半导体、材料科学、电子工程等相关专业；
2、5年以上生产线工艺经验、太阳能、TFT或半导体等行业经验优先；
3、熟悉太阳能电池工艺原理及设备结构优先；
4、熟悉太阳能电池材料行业特点,了解工艺设备者优先；
5、熟练使用各种测试设备并对结果数据进行分析处理；
6、丰富的装机调试经验及现场改善经验；
7、具备较强沟通及团队合作能力。
工作地址：
北京
**********
北京汉能光伏投资有限公司
公司规模：
10000人以上
公司性质：
上市公司
公司行业：
能源/矿产/采掘/冶炼
公司主页：
null
公司地址：
北京市朝阳区北辰西路8号北辰世纪中心B座
**********
转移定价高级经理(013969)(职位编号：Hanergy013969)
北京汉能光伏投资有限公司
五险一金绩效奖金包吃带薪年假节日福利
**********
福利:
五险一金
绩效奖金
包吃
带薪年假
节日福利
**********
职位月薪：15000-25000元/月 
工作地点：北京
发布日期：最近
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：1人
职位类别：税务经理/主管
**********
岗位职责:
1、负责汇集和制定境内外公司的税务制度和政策
2、提供公司税务筹划方案
3、制定集团转移定价策略
4、指导业务部门转移定价设定
5、合同审阅
6、负责组织举办税务知识培训及交流活动，提升各业务条线税务管理能力

任职资格:
1、税收、财务管理、会计等相关专业本科及以上学历
2、9年以上的企业财税相关工作经验，3年以上转移定价相关工作经验
3、精通会计、财务管理、税务知识；熟悉国际税法概况，跨国转移定价、常设机构等相关税务处理
4、英语流利
5、有责任感，有良好的组织、协调、沟通能力和团队协作精神，能承受较大工作压力并愿意适当出差
工作地址：
北京市朝阳区安立路0-A号
**********
北京汉能光伏投资有限公司
公司规模：
10000人以上
公司性质：
上市公司
公司行业：
能源/矿产/采掘/冶炼
公司主页：
null
公司地址：
北京市朝阳区北辰西路8号北辰世纪中心B座
**********
省公司总裁
北京汉能光伏投资有限公司
**********
福利:
**********
职位月薪：30001-50000元/月 
工作地点：北京
发布日期：2018-02-28 08:50:37
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：10人
职位类别：首席执行官CEO/总裁/总经理
**********
岗位职责：
1、全面负责所属区域太阳能光伏业务，筛选目标市场长期合作伙伴并建立和维护长期合作关系；
2、根据整体战略目标和规划，完成相应区域太阳能产品销售、品牌推广、服务体系搭建等任务；
带领团队达成销售目标；
3、负责目标市场及太阳能光伏行业研究，负责项目开发、方案设计，项目谈判、项目实施工作，协助完成金融贷款服务；
4、负责日常经营管理工作，团队管理，市场管理，售后服务体系管理等工作。

任职资格：
1、35-45岁之间
2、具有省级及以上区域市场开拓和市场管理的成功经验
3、具有丰富的渠道营销管理经验
4、具有决断力、敏锐的市场判断能力、较好的逻辑思维能力等
5、家电行业/消费类电子行业/太阳能热水器行业/大型渠道商/渠道营销模式企业

工作地址：
全国省分公司
**********
北京汉能光伏投资有限公司
公司规模：
10000人以上
公司性质：
上市公司
公司行业：
能源/矿产/采掘/冶炼
公司主页：
null
公司地址：
北京市朝阳区北辰西路8号北辰世纪中心B座
**********
基金项目助理/专员(013884)(职位编号：Hanergy013884)
北京汉能光伏投资有限公司
五险一金绩效奖金包吃带薪年假节日福利
**********
福利:
五险一金
绩效奖金
包吃
带薪年假
节日福利
**********
职位月薪：6000-10000元/月 
工作地点：北京
发布日期：最近
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：融资专员/助理
**********
岗位职责:
岗位描述：
1. 负责基金及产业园项目前期的数据搜集和相关准备工作，协助完成相关报告，商业计划书等；
2. 搜集、整理拟投资和已投资项目的风险信息，协助上级完成风险控制工作；
3. 对已投资项目的发展和收益情况进行跟进和定期归纳；
4. 协助完成基金的产品设计、备案及后续落地沟通；
5. 协助完成具体项目的推进和落实；
6. 完成领导交办的其他任务；

任职资格:
任职资格：
1. 教育背景：金融、经济、财务等专业本科及以上学历，海外留学及理工类背景优先考虑。
2. 工作经验：具有一年以上企业集团资产管理、融资部门或者基金等金融机构基础工作经验，具有四大、银行、券商及投行基础工作经验者优先考虑。
3. 能力素质：
1） 熟悉基金、银行、证券等行业，有扎实的金融基础理论、财务管理知识；
2） 参与过投、融资项目，熟悉投、融资项目的工作流程和相关手续；
3） 优秀的的信息收集、归纳能力，能够准确的搜集被投资企业或项目经营管理中暴露出来的风险信息；
4） 优秀的沟通协调能力，有与政府机构的沟通协调经验优先考虑；
5）   形象气质佳。
工作地址：
北京市朝阳区安立路0-A号
**********
北京汉能光伏投资有限公司
公司规模：
10000人以上
公司性质：
上市公司
公司行业：
能源/矿产/采掘/冶炼
公司主页：
null
公司地址：
北京市朝阳区北辰西路8号北辰世纪中心B座
**********
产业园财务经理(013979)(职位编号：Hanergy013979)
北京汉能光伏投资有限公司
五险一金绩效奖金包吃带薪年假节日福利
**********
福利:
五险一金
绩效奖金
包吃
带薪年假
节日福利
**********
职位月薪：10001-15000元/月 
工作地点：北京
发布日期：最近
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：30人
职位类别：财务经理
**********
岗位职责:
工作职责
1、负责各项财务制度及流程的宣贯，确保各项管理工作的规范、安全和高效； 1.2完善内部控制流程，做好风险管理各方面工作；
2、财务日常管理 确保资金管理、会计核算、预算管理、税务管理等方面的工作顺利进行；
3、负责对预算报表、资金报表、会计报表、财务分析等财务报表进行审核；
4、做好经营分析，对成本控制的执行情况进行跟踪，及时解决出现的问题；
5、决策支持，对公司经营状况进行阶段性的财务分析与财务预测，并提出财务改进方案；
6、当地关系的维护 负责与当地工商、税务、银行等外部机构保持良好的沟通协调。
注意：此职位需要长期出差至产业园

任职资格:
1、会计学、财务管理等相关专业统招本科以上学历；
2、5年以上财务工作经验
3、具有全面的财务管理、企业经营管理、风险控制等专业知识；
4、熟悉会计核算制度和会计处理方法，并能在日常事务处理中熟练运用；熟悉成本控制；熟悉财务数据处理及分析。
5、中级会计师及以上职称；
工作地址：
北京市朝阳区安立路0-A号
**********
北京汉能光伏投资有限公司
公司规模：
10000人以上
公司性质：
上市公司
公司行业：
能源/矿产/采掘/冶炼
公司主页：
null
公司地址：
北京市朝阳区北辰西路8号北辰世纪中心B座
**********
招聘总监
北京汉能光伏投资有限公司
每年多次调薪五险一金绩效奖金包吃通讯补贴带薪年假免费班车节日福利
**********
福利:
每年多次调薪
五险一金
绩效奖金
包吃
通讯补贴
带薪年假
免费班车
节日福利
**********
职位月薪：50001-70000元/月 
工作地点：北京
发布日期：最近
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：6人
职位类别：人力资源总监
**********
工作职责
1、负责公司高端人才招聘，执行干部选拔外部渠道吸引及挖潜；
 2、组织和协助公司组织架构设计和岗位设置，组织梳理和完善公司的岗位描述说明书；
3、分析、选择、维护和完善招聘渠道，收集、调研、选择招聘供应商，建立合格招聘供应商资料库，并进行动态管理；
4、改进公司人才选拔体系，完善公司人才储备库，收集、分析行业人才状况，了解业内人员动态；
5、负责重点岗位和中高级人才的甄选、面试以及OFFER沟通发放等；
6、负责定期的招聘报告总结及分析以及招聘策略的制定等；
7、协助上级领导完成其他工作。
任职资格
1. 本科以上学历，人力资源管理、心理学、管理等相关专业；
 2. 10年以上大中型企业的人力资源管理相关工作经验，其中至少有8年招聘工作经验，具有高端人才招聘经验者优先考虑；
3. 熟悉各种招聘渠道、测评工具和面试技巧，判断力强，洞察力敏锐，能独立完成高级职位的面试工作；
 4、具备行业mapping资源及能力，熟悉新能源（光伏）/金融/工业装备等行业或职能模块高管资源者优先；
5、具有优秀的学习能力、强烈的自我激励和开创精神、出色的沟通协调能力。

工作地址：
北京市朝阳区北辰西路8号北辰世纪中心B座
**********
北京汉能光伏投资有限公司
公司规模：
10000人以上
公司性质：
上市公司
公司行业：
能源/矿产/采掘/冶炼
公司主页：
null
公司地址：
北京市朝阳区北辰西路8号北辰世纪中心B座
**********
大客户销售总监(014223)(职位编号：Hanergy014223)
北京汉能光伏投资有限公司
**********
福利:
**********
职位月薪：20001-30000元/月 
工作地点：北京
发布日期：最新
工作性质：全职
工作经验：5-10年
最低学历：不限
招聘人数：1人
职位类别：销售总监
**********
岗位职责:
1、根据公司业务发展战略制定薄膜太阳能产品在BIPV（光伏建筑一体化）行业的大客户销售计划；
2、负责开拓国内外BIPV行业的大客户合作资源；
3、与市场部密切合作，拟定市场策略和渠道策略；
4、负责所属销售团队的管理，提高团队整体绩效，完成公司年度销售目标；

任职资格:
1、行业要求：深度了解（包括新型建材、幕墙、建筑一体化）产业格局及经营规律，熟悉品牌商或渠道商人脉。
2、5年以上相关行业拓展经验，有10年以上销售团队管理经验，千万以上单品销售额的成功案例。
3、有激情，有韧劲，良好的沟通及逻辑能力，团队协作能力，能适应高强度工作包括出差。
4、本科及以上学历，相关专业优先，会日常办公软件。
工作地址：
北京/上海
**********
北京汉能光伏投资有限公司
公司规模：
10000人以上
公司性质：
上市公司
公司行业：
能源/矿产/采掘/冶炼
公司主页：
null
公司地址：
北京市朝阳区北辰西路8号北辰世纪中心B座
**********
招聘经理(014101)(职位编号：Hanergy014101)
北京汉能光伏投资有限公司
**********
福利:
**********
职位月薪：10001-15000元/月 
工作地点：北京
发布日期：最近
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：1人
职位类别：招聘经理/主管
**********
岗位职责:
1、依据公司的年度战略规划和各部门的人员需求，进行招聘需求调研，制定招聘计划，并按时间节点完成招聘任务；
2、负责招聘渠道的开发与维护，人才库的完善，管控招聘费用；+
3、负责公司招聘数据的统计分析、汇总预测和调整等工作；
4、负责设计并执行招聘、面试、评估、录取各环节，确保人才质量，满足人才需求；+
5、定期对招聘情况做出详尽的招聘报告并与总部对接；
6、完成领导交办的其他工作。

任职资格:
1、本科及以上学历，人力资源、工商管理类相关专业；
2、具备5年以上招聘工作经验，精通招聘模块工作，具备高端职位操作能力；
3、具有大型企业工作经验，具备新能源行业从业经验者优先，有猎头经验者优先；
4、英文表达流利，有海外留学或工作经验者优先；
5、具备较强的沟通能力及组织协调能力、抗压能力。
工作地址：
北京朝阳区安立路0-A号（奥森公园北园东门南100米）
**********
北京汉能光伏投资有限公司
公司规模：
10000人以上
公司性质：
上市公司
公司行业：
能源/矿产/采掘/冶炼
公司主页：
null
公司地址：
北京市朝阳区北辰西路8号北辰世纪中心B座
**********
整车集成高级经理(013825)(职位编号：Hanergy013825)
北京汉能光伏投资有限公司
**********
福利:
**********
职位月薪：10001-15000元/月 
工作地点：北京
发布日期：最近
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：1人
职位类别：汽车零部件设计师
**********
岗位职责:
1、负责总布置方案设计：运用人机工程学、人因学，根据SAE标准体系确定整车尺寸方案设计等；
2、负责车辆工程可行性计算分析：制定控制曲面质量标准、内外饰装配质量、总布置方案、开发流程等；
3、负责整车性能控制：动力性、经济性、操稳性、制动性、安全性、NVH问题等；
4、负责NVH问题解决：测试、分析工程问题，根据解决经验，进行优化开发流程；
5、负责空调系统性能、电池性能、电机性能控制等热管理；
6、负责运用流体与空气动力学进行水流管理、风阻分析等；
7、负责控制白车身刚度、模态：计算分析、试验，确定技术方案、工作流程；
8、运用疲劳理论，针对整车集成情况进行计算分析，进行整车优化以促进零部件质量提高；
9、负责整车耐久性分析与试验：对整车零部件、系统等进行整车耐久性分析与试验，并根据结论制定优化方案方法；
10、运用外线性、塑性力学、碰撞力学进行整车碰撞分析，根据理论及实践经验，制定改进、提高措施方法等；
11、负责安全约束系统：进行气囊、安全带、安全气帘分析，优化开发流程、进行验证认证等。
12、负责部门组织架构规划、建设与发展；
13、公司内部、外部合作方、供应商等协调沟通。

任职资格:
1、8年以上工作经验，车辆工程、汽车、机械等相关专业本科及以上学历；
2、掌握运用相关体系标准、法律法规、行业技术标准要求进行整车集成控制，具备5年以上整车集成经验；
3、掌握FMVSS、SAE、ISO、GB标准体系，掌握关于整车相关安全、性能等试验、认证的法律法规、行业技术标准要求；
4、熟练掌握office、CATIA、UG、AUTOCAD等工程软件使用技能；具备良好的团队合作精神、严密的逻辑思维、高效沟通能力。
工作地址：
北京市朝阳区安立路0-A号
**********
北京汉能光伏投资有限公司
公司规模：
10000人以上
公司性质：
上市公司
公司行业：
能源/矿产/采掘/冶炼
公司主页：
null
公司地址：
北京市朝阳区北辰西路8号北辰世纪中心B座
**********
电子电气高级经理(013820)(职位编号：Hanergy013820)
北京汉能光伏投资有限公司
**********
福利:
**********
职位月薪：10001-15000元/月 
工作地点：北京
发布日期：最近
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：2人
职位类别：汽车电子工程师
**********
岗位职责:
1、根据整车功能需求、法规和设计要求，制定电子电气整车需求；
2、根据电子电气系统的需求，制定系统级电子电气架构的解决方案；
3、负责制定电子电气的开发策略、技术路线和技术实现；
4、制定验证架构设计目标实现的测试规范与方法；
5、根据相应的测试规范与方法，验证架构设计目标和整车需求目标是否被实现；
6、参与并快速解决各电子电气开发及使用中出现的问题；
7、根据智能网联技术发展需求和趋势，完成智能网联需求研究。

任职资格:
1、本科及以上学历，电气自动化或电子、计算机或通信工程及相关专业；
2、10年以上电子电气方向的技术经验，有主导电子电气架构项目的技术开发工作经验；
3、深刻了解整车电子电气设计原则，不仅满足安全，可靠，法规要求，同时考虑核心技术发展；
4、对车联网、自动驾驶、辅助驾驶等有深刻理解。
工作地址：
北京市朝阳区安立路0-A号
**********
北京汉能光伏投资有限公司
公司规模：
10000人以上
公司性质：
上市公司
公司行业：
能源/矿产/采掘/冶炼
公司主页：
null
公司地址：
北京市朝阳区北辰西路8号北辰世纪中心B座
**********
项目管理高级经理/经理/主管(013715)(职位编号：Hanergy013715)
北京汉能光伏投资有限公司
五险一金餐补弹性工作免费班车
**********
福利:
五险一金
餐补
弹性工作
免费班车
**********
职位月薪：20000-40000元/月 
工作地点：北京
发布日期：最近
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：30人
职位类别：项目经理/项目主管
**********
岗位职责：
1、  负责公司项目管理流程的建设与完善；
2、  负责对项目的实施执行情况予以督导；
3、  负责对所监控项目出现的问题进行闭环管理；
4、  负责对跨事业部项目所需要的资源予以调配推动；
5、  负责对各项目团队进行项目管理指导及项目考核；
6、  负责组织实施公司项目管理领域的知识管理与人才培养。
 任职资格：
1、全日制统招本科以上学历；
2、具备两年以上项目管理工作经验。其中具有工程项目、生产制造项目、研发技术项目或项目交付管理经验者优先考虑；
3、具备PMP项目管理认证资质，曾任职大型企业PMO优先考虑；
4、具备优秀的组织协调能力、沟通能力、适应变革能力、解决问题能力及抗压能力；
5、具备新能源行业或者相关行业经历者优先。

工作地址：
北京市安立路0-A号
**********
北京汉能光伏投资有限公司
公司规模：
10000人以上
公司性质：
上市公司
公司行业：
能源/矿产/采掘/冶炼
公司主页：
null
公司地址：
北京市朝阳区北辰西路8号北辰世纪中心B座
**********
商务合约部经理
中建水务环保有限公司
五险一金绩效奖金交通补助餐补通讯补贴带薪年假
**********
福利:
五险一金
绩效奖金
交通补助
餐补
通讯补贴
带薪年假
**********
职位月薪：15001-20000元/月 
工作地点：北京-丰台区
发布日期：最近
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：1人
职位类别：部门/事业部管理
**********
岗位职责：1、全面负责部门的日常管理工作，包括全面工作。主持部门工作计划、指导、监督和管理。2、负责编制、审核项目的工程成本分析、估算、概、预、结算工作，并对工程成本进行控制。3、负责合同的编制、审核、交底及管理工作，并定期跟踪、检查工程合同的执行情况。4、负责项目开发的成本、效益分析。5、负责监管各个项目执行进程，按项目计划对各项目的工作内容（范围）、进度、成本、结果等地行适时的跟踪、监控、预警警及督促。6、做好采鈠工作的计划、指导、监督和管理。7、对设备的采购过程、进度进行跟踪、督促及监控。8、做好部门团队建设、提高员工业务能力，做好部门整体管理。
 任职要求：全日制（脱产）硕士研究生及以上学历，五年及以上大型建筑施工项目商务合约管理经验；或具有全日制（脱产）大学本科及以上学历，八年及以上大型建筑施工项目商务合约管理经验。
工作地址：
北京市丰台区航丰路13号崇新大厦A座
**********
中建水务环保有限公司
公司规模：
100-499人
公司性质：
国企
公司行业：
环保
公司地址：
北京市丰台区航丰路13号崇新大厦A座
**********
招聘总监/高级经理(013701)(职位编号：Hanergy013701)
北京汉能光伏投资有限公司
**********
福利:
**********
职位月薪：20001-30000元/月 
工作地点：北京
发布日期：最近
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：3人
职位类别：人力资源经理
**********
岗位职责:
1，负责总部HR中心招聘团队管理，高端人才招聘。
2，组织和协助公司组织架构设计和岗位设置，组织梳理和完善公司的岗位描述说明书；
3，分析，选择，维护和完善招聘渠道，收集，调研，选择招聘供应商，建立合格招聘供应商资料库，并进行动态管理；
4，改进公司人才选拨体系，完善公司人才储备库，收集，分析行业人才状况，了解业内人员动态；
5，负责重点岗位和中高级人才的甄选，面试以及OFFER沟通发放等；
6，负责定期的招聘报告总结及分析以及招聘策略的制定等；
7，协助上级领导完成其他工作。

任职资格:
1，统招本科以上学历，人力资源管理，心理学，管理等相关专业；
2，8年以上大中型企业的人力资源管理相关工作经验，其中至少有8年招聘经验者优先考虑；
3，熟悉各种招聘渠道，测评工具和面试技巧，判断力强,洞察力敏锐,能独立完成高级职位的面试工作;
4,具备行业mapping资源及能力，熟悉新能源（光伏）/金融/工业装备等行业或职能模块高管资源优先；
工作地址：
朝阳区北辰世纪中心
**********
北京汉能光伏投资有限公司
公司规模：
10000人以上
公司性质：
上市公司
公司行业：
能源/矿产/采掘/冶炼
公司主页：
null
公司地址：
北京市朝阳区北辰西路8号北辰世纪中心B座
**********
计划主管(014024)(职位编号：Hanergy014024)
北京汉能光伏投资有限公司
五险一金年终分红加班补助全勤奖包吃交通补助定期体检免费班车
**********
福利:
五险一金
年终分红
加班补助
全勤奖
包吃
交通补助
定期体检
免费班车
**********
职位月薪：15001-20000元/月 
工作地点：北京
发布日期：最近
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：1人
职位类别：生产计划
**********
岗位职责:
跟踪各项计划执行情况，并定期形成计划准确率报告；
协调解决计划执行过程中发现的问题，统筹供需平衡，保障供应；
根据供应链的运行情况，提出采购、生产、仓储、物流的能力调整建议；
完成有关的各类报表，提供和保存信息记录。
参与团队活动；
参与部门业务培训，学习供应链知识、学习新制度，对外组织制度培训；

任职资格:
本科及以上学历，经济管理类、理工类专业优先；
3年以上大型公司计划工作经验；
熟悉企业管理知识，熟悉计划、流程等管理知识；
较强的沟通协调能力；
英语听说读写流利。
工作地址：
北京朝阳区安立路A-0
**********
北京汉能光伏投资有限公司
公司规模：
10000人以上
公司性质：
上市公司
公司行业：
能源/矿产/采掘/冶炼
公司主页：
null
公司地址：
北京市朝阳区北辰西路8号北辰世纪中心B座
**********
大客户销售CEO/总裁 （BIPV方向）(014182)(职位编号：Hanergy014182)
北京汉能光伏投资有限公司
五险一金绩效奖金带薪年假补充医疗保险定期体检免费班车员工旅游节日福利
**********
福利:
五险一金
绩效奖金
带薪年假
补充医疗保险
定期体检
免费班车
员工旅游
节日福利
**********
职位月薪：50001-70000元/月 
工作地点：北京
发布日期：最近
工作性质：全职
工作经验：10年以上
最低学历：本科
招聘人数：1人
职位类别：大客户销售代表
**********
岗位职责:
1、根据公司业务发展战略制定薄膜太阳能产品在BIPV（光伏建筑一体化）行业的大客户销售计划；
2、负责开拓国内外BIPV行业的大客户合作资源；
3、与市场部密切合作，拟定市场策略和渠道策略；
4、负责所属销售团队的管理，提高团队整体绩效，完成公司年度销售目标；

任职资格:
"1、行业要求：深度了解（包括新型建材、幕墙、建筑一体化）产业格局及经营规律，熟悉品牌商或渠道商人脉。
2、5年以上相关行业拓展经验，有10年以上销售团队管理经验，千万以上单品销售额的成功案例。
3、有激情，有韧劲，良好的沟通及逻辑能力，团队协作能力，能适应高强度工作包括出差。
4、本科及以上学历，相关专业优先，会日常办公软件。
工作地址：
北京朝阳区安立路0-A号（奥森公园北园东门南100米）
**********
北京汉能光伏投资有限公司
公司规模：
10000人以上
公司性质：
上市公司
公司行业：
能源/矿产/采掘/冶炼
公司主页：
null
公司地址：
北京市朝阳区北辰西路8号北辰世纪中心B座
**********
计划运营经理/总监(013630)(职位编号：Hanergy013630)
北京汉能光伏投资有限公司
**********
福利:
**********
职位月薪：15001-20000元/月 
工作地点：北京
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：硕士
招聘人数：1人
职位类别：技术研发工程师
**********
岗位职责:
1、负责根据公司战略发展目标，组织和制定部门工作计划和部门项目工作管理。
2、完成领导交办的其他工作。

任职资格:
1、理工科专业，材料学相关专业研究生毕业（优先），英语六级以上，两年及以上工作经验。
2、制造业、战略运营类、咨询机构相关工作背景。
工作地址：
北京市电通创意广场（酒仙桥）
**********
北京汉能光伏投资有限公司
公司规模：
10000人以上
公司性质：
上市公司
公司行业：
能源/矿产/采掘/冶炼
公司主页：
null
公司地址：
北京市朝阳区北辰西路8号北辰世纪中心B座