诚招项目顾问
北京铁骆驼科技有限公司
加班补助绩效奖金包住餐补通讯补贴
**********
福利:
加班补助
绩效奖金
包住
餐补
通讯补贴
**********
职位月薪：6001-8000元/月 
工作地点：上海
发布日期：最近
工作性质：全职
工作经验：不限
最低学历：中专
招聘人数：10人
职位类别：销售代表
**********
1.接受公司统一培训，电话沟通，整理客户信息；
2.耐心与客户沟通，根据客户需求寻找解决方法；
3.及时电话回访，介绍项目内容，邀约客户考察；
4.认真完成领导的任务。
任职要求：
1.勤奋，勤奋，勤奋，从内心是想挣钱的，欢迎加入我们铁骆驼；
2.不抱怨，积极向上，不勾心斗角，我们都是正能量的年轻团队；
3.能长久稳定工作，能有职业规划的优先选择；
4.你有多大才能，就有多少收入，你付出多少汗水，就有足够的回报；
5.20-35岁，男女不限，每周单休，朝九晚六。
薪资待遇：
真实薪资每月5000-20000元（底薪+提成），给你提供好的工作环境，给你一个好的发展空间，期待你能展现自己。
联系人：张女士        电话：18672540166
工作地址：
上海市宝山区红林路2号
查看职位地图
**********
北京铁骆驼科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
www.tlt888.cn
公司地址：
北京市大兴区亦庄经济开发区科创十二路鸿坤·云时代C座8楼
**********
技术开发（线圈设计）
日本东静工业株式会社上海代表处
**********
福利:
**********
职位月薪：6001-8000元/月 
工作地点：上海-徐汇区
发布日期：最近
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：变压器与磁电工程师
**********
1.大专以上，理工科(电气及电子相关专业优先)
2.从事电子变压器，电感研发工作1年以上
3.男性，35岁以下
4.能简单使用英语和日语交流者优先
5.熟练运用Autocad或其它作图软件
6.工作积极主动，合作性良好，具备一定的团队精神
7.自信且有能力者，薪水可面谈

工作地址：
上海市徐汇区龙华西路585号A栋904室 华富大厦
查看职位地图
**********
日本东静工业株式会社上海代表处
公司规模：
20人以下
公司性质：
代表处
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.to-ind.co.jp
公司地址：
上海市徐汇区龙华西路585号A栋904室 华富大厦
**********
实习生
VENTURE ELECTRONICS SHANGHAI (万特电子)
**********
福利:
**********
职位月薪：2001-4000元/月 
工作地点：上海
发布日期：2018-03-05 14:16:24
工作性质：实习
工作经验：不限
最低学历：大专
招聘人数：8人
职位类别：实习生
**********
1）财务助理
岗位要求：
大专或大专以上应届毕业生
具有良好的沟通协调能力
工作积极、责任心强
岗位职责：
付款（复印整理付款材料）
整理已付未付表并E-MAIL给相关人员
快递收发以及相关的联系工作

2）采购工程师助理
岗位要求：
专科或本科以上学历应届毕业生，英语良好
具有良好的沟通协调能力及团队合作
工作积极、责任心强
岗位职责：
熟悉办公软件；
协助Procurement Engineer完成相关工作，如报表、项目跟进等
电子行业优先考虑

3）工艺技术员
岗位要求：
大专或大专以上应届毕业生，主修机电一体化专业，电子或其它工科专业
具有良好的学习能力和动手能力
工作积极、责任心强，能独立解决问题
英语四级以上，能熟练应用OFFICE软件和CAD
协助工程师优化PCBA生产工艺和生产品质的提升；
协助工程师为新产品导入制作SMT工艺控制流程和操作指导书；
处理客户ECO，BOM和AVL；
为产线员工提供岗位培训；
监控并调整工艺设定与流程文件相一致以便达到稳定的SMT工艺制程控制

4）质量工程师助理
岗位要求：
本科以上学历应届毕业生，英语良好
机械设计或电子相关专业， ***优先；
具有良好的沟通协调能力及团队合作
熟练使用办公软件，比如Word，Excel， PPT 等
能承受压力，乐于学习
工作积极、责任心强
岗位职责：
处理日常产线发生的质量问题；
处理客户投诉， 8D回复；
内部改进措施的跟踪、确认，反馈等；
相关检验作业指导书的制作、更新；
培训IPQC， 对IPQC日常工作绩效确认等。

5）SQE助理
岗位要求：
专科或本强科以上学历应届毕业生，英语良好
具有良好的沟通协调能力及团队合作
工作积极、责任心
岗位职责：
熟悉办公软件；
协助SQE完成相关工作，如报表、项目跟进等
电子行业优先考虑

6）计划员助理
岗位要求：
专科或本科以上学历应届毕业生，英语良好
具有良好的沟通协调能力及团队合作
工作积极、责任心强
岗位职责：
熟悉办公软件；
协助Planner完成相关工作，如报表、项目跟进等

7）采购助理
岗位要求：
专科或本科以上学历应届毕业生，英语良好
具有良好的沟通协调能力及团队合作
工作积极、责任心强
岗位职责：
熟悉办公软件；
协助上级完成相关工作，如报表、项目跟进等

8）物流助理
岗位要求：
专科或本科以上学历应届毕业生，英语良好
具有良好的沟通协调能力及团队合作
工作积极、责任心强
岗位职责：
熟悉办公软件；
协助上级完成相关工作，如报表、项目跟进等
工作地址：
桂桥路1201号T52-11
**********
VENTURE ELECTRONICS SHANGHAI (万特电子)
公司规模：
1000-9999人
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.venture.com.sg
公司地址：
桂桥路1201号T52-11
查看公司地图
**********
工艺技术员 Process Technician
VENTURE ELECTRONICS SHANGHAI (万特电子)
**********
福利:
**********
职位月薪：4001-6000元/月 
工作地点：上海
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：其他
**********
岗位职责：
1）设备的保养
2)换线
3）编程
4）提高产能
 任职要求：
1）熟悉电脑操作
2）熟悉波峰焊操作

Responsibilities and Authority
1.Maintenance of equipment
2.Change Line
3.Programme
4.Increase production capacity
Core Skills:
1.Familiar with computer
2.Familiar with wave soldering operation
工作地址：
桂桥路1201号T52-11
**********
VENTURE ELECTRONICS SHANGHAI (万特电子)
公司规模：
1000-9999人
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.venture.com.sg
公司地址：
桂桥路1201号T52-11
查看公司地图
**********
销售业务代表/客户代表
上海普莹照明有限公司
五险一金绩效奖金交通补助通讯补贴弹性工作员工旅游
**********
福利:
五险一金
绩效奖金
交通补助
通讯补贴
弹性工作
员工旅游
**********
职位月薪：10000-20000元/月 
工作地点：上海
发布日期：2018-03-10 19:45:06
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：销售经理
**********
岗位职责：
1、销售职位，负责灯具产品的销售及客户维护工作，具有1年及以上照明或销售工作经验（特别优秀者可以不考虑工作经验)。

2、对照明产品有一定了解，熟悉相关产品的性能及技术参数

3、负责其功能领域内主要目标和计划，制定、参与或协助领导执行客户开发与维护计划，定期拜访老客户、开发新客户

4、分析客户需求，维护与指定公司关键顾客的关系，寻求机会发展新的业务

5、熟悉照明工程招投标流程；参与项目投标文件编制，投标书并参与照明工程项目的招投标工作及合同洽谈。管理、参与和跟进项目进展

6、建立管理数据库，跟踪分析相关信息；向公司提供市场资讯及所属客户信息

7、适应短期出差,及时完成上级交待的各项任务。


任职要求：
1、专科及以上学历，照明、市场营销、工程设计等相关专业（特别优秀者可放宽学历要求）

2、熟练使用办公软件，文字表达能力强

3、性格外向，吃苦耐劳，责任心强，具有较强较强的沟通能力、公关能力、语言表达能力、应变能力和谈判能力；具备良好的客户服务意识，良好的品牌及营销策划能力

4、善于交流，注重仪表和礼仪，关注细节

5、年龄35岁以下

6、有照明行业从业经历者优先录用
工作地址：
徐汇区龙漕路200弄28号宏润大厦901-902
**********
上海普莹照明有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司主页：
www.spoorin-lighting.com
公司地址：
徐汇区龙漕路200弄28号宏润大厦901-902
查看公司地图
**********
体系工程师 System Engineer
VENTURE ELECTRONICS SHANGHAI (万特电子)
**********
福利:
**********
职位月薪：8001-10000元/月 
工作地点：上海
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：其他
**********
岗位职责:
1)管理体系的建立和认证,ISO / TS16949、ISO9001和ISO14001等。
2)协调内部和外部系统和过程及产品审核。
3)协调和监控体系流程更改/改进。
4)实现、促进和评估工作质量管理体系的有效性/ EMS包括培训持续改进。
5)培训,促进员工质量要求,意识。
6)维护系统和报告包括行动计划跟踪和效果评估。
7)在原有的基础上进行质量评审。
8)监督管理系统文档的制定包括程序和工作指示。
9)负责公司范围内的文档组织控制。
10完成质量经理安排的其他任务
经验要求:
1)至少2年经验,系统工程师在制造工厂。
2)经验在新管理系统设置过程
Responsibilities and Authority:
1)Take lead of management system set up and certification, such as ISO/TS16949, ISO9001 and ISO14001.
2)Coordinate internal and external system & process & product audits.
3)Coordinate and monitor process change/improvement.
4)Implement, promote and assess effectiveness of plant-wide QMS/EMS including training for ongoing improvements.
5)To train and promote employees quality requirement, awareness.
6)Maintain the system and reporting including action plan follow-up and effectiveness review.
7)Conduct quality review on an on-going basis.
8)Oversees the formulation of management systems documentation including procedures and work instructions.
9)In charge of plant-wide documentation control.
10)Other tasks assigned by quality manager
Experience:
1)At least 2 years experience as system engineer in manufacturing plants.
2)Experience on new management system set-up process
  工作地址：
桂桥路1201号T52-11
**********
VENTURE ELECTRONICS SHANGHAI (万特电子)
公司规模：
1000-9999人
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.venture.com.sg
公司地址：
桂桥路1201号T52-11
查看公司地图
**********
采购工程师 Procurement Engineer
VENTURE ELECTRONICS SHANGHAI (万特电子)
**********
福利:
**********
职位月薪：6001-8000元/月 
工作地点：上海
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：其他
**********
岗位职责：
1）供应商开发、评估和选择
2）支持新产品询价
3）供应商品质管理
4）供应商关系管理，供应商绩效评审
5）成本竞争力的研究和制造技术
 任职要求：
处理相关产品的工程知识，熟悉采购相关的职能。
有研发支持经验者优先考虑，良好的采购和质量运作知识。
良好的英文读写能力。能够根据业务环境的变化快速调整优先级。

Responsibilities and Authority
 -        Supply base development supplier scouting evaluation and selection
-        RFQS support to new products.
-        Post MR cost reductions planning
-        Supplier quality management
-        Negotiation, Altemate source and redesign
-        Suppliers relationships management, supplier performance review
-        Cost competitive studies, Industrial benchmard and manufacturing technology update
 Core Skills:
 -        Process deep engineering knowledge in the related commodity: ME commodity. Sound knowledge of procurement related functions.
-        Previous R&D support experience will be an added advantage. Good knowledge of purchasing and quality operations with ability to improve processes and implement pllicies to enhance effectiveness of the department.
-        Proficient in written and spoken english. Able to prioritize rapidly in response to changing business enviroment and manage high stree. Possess strong project management skills. Good team work. Eyes for detail and must feedback event if it is against the prevailing system approach.
  工作地址：
桂桥路1201号T52-11
**********
VENTURE ELECTRONICS SHANGHAI (万特电子)
公司规模：
1000-9999人
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.venture.com.sg
公司地址：
桂桥路1201号T52-11
查看公司地图
**********
工艺工程师 Process Engineer
VENTURE ELECTRONICS SHANGHAI (万特电子)
**********
福利:
**********
职位月薪：8001-10000元/月 
工作地点：上海
发布日期：2018-03-05 14:16:24
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：其他
**********
岗位职责：
1.熟悉SMT、波峰焊和镀膜工艺。
2.负责设计、安装和调试生产设备。
3.在项目启动阶段，开发过程流程图，PFMEA，过程指令，DFM。
4.执行DFM分析，开发新的固定/工具，包括模板和波浪托盘等，
5.负责通过工艺改进程序和生产线上的工艺监控来维持和优化产品的生产过程质量和过程质量。
6.包括数据收集、分析和过程监控的图表
7.分配的其他工作
岗位要求：
1.能承受一定的压力

也非常欢迎踏实努力的应届毕业生投简历！
Responsibilities and Authority
1.To be an ECN coordinator, leading ECN analysis, system uploading, implementing, and monitoring, organize ECN weekly meeting.
2.Well knowledge of SMT, Wave Soldering and Coating process.
3.Responsible for design, install and debug the production fixture.
4.Develop Process Flow Chart, PFMEA, Process Instruction, DFM during project initiation stage.
5.Perform the DFM analysis and develop new fixture/tools including stencil and wave pallet etc.,
6.Responsible in sustaining and optimizing process yields and process quality of the products through process improvement programs and process monitoring on production lines.
7.includes data collection, analysis, and charting of process monitoring
8.Other assigned tasks.
Experience:
- Able to work under Pressure.
工作地址：
桂桥路1201号T52-11
**********
VENTURE ELECTRONICS SHANGHAI (万特电子)
公司规模：
1000-9999人
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.venture.com.sg
公司地址：
桂桥路1201号T52-11
查看公司地图
**********
电商平台运营专员
上海指南针信息技术有限公司
五险一金绩效奖金加班补助包吃包住带薪年假弹性工作节日福利
**********
福利:
五险一金
绩效奖金
加班补助
包吃
包住
带薪年假
弹性工作
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：上海-闵行区
发布日期：招聘中
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：电子商务专员/助理
**********
岗位职责：
1、维护公司年度/季度商品，库存及补货.
2、负责公司商品的上下架，图片的编辑修改及产品价格的更新。
3、负责对上架商品名称，价格，数量等相关的复核；
4、确保产品详情展示的完整性以及禁止出现广告违禁词，配合活动进行选品规划与报名；
5、关注各大电商平台活动和竞品动态，市场变化。
6、对平台的畅销、滞销商品分析，及时合理调配、促销、补货；
任职要求：
1、大专及以上学历，2年以上电商行业从业经验，健康品类运营者优先
2、逻辑思维能力强，执行力强，
3、极强的抗压能力、高度的工作投入
4、具备良好的计算机知识，了解互联网产品的整体运作流程

工作地址：
上海市闵行区黎安路1187号5号楼
**********
上海指南针信息技术有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
互联网/电子商务
公司地址：
上海市闵行区黎安路1187号5号楼
查看公司地图
**********
高级质量工程师Senior QA Engineer
VENTURE ELECTRONICS SHANGHAI (万特电子)
**********
福利:
**********
职位月薪：10001-15000元/月 
工作地点：上海
发布日期：招聘中
工作性质：全职
工作经验：10年以上
最低学历：大专
招聘人数：1人
职位类别：质量管理/测试工程师
**********
岗位职责： 
-       确保生产制造符合客户的规范和要求
-       确保实施过程中审计
-       识别和评估产品质量问题并与制造工程师、测试工程师、生产主管和IQC一起制定纠正措施
-       确保质量记录的正确维护
-       与客户就所有质量相关问题保持联系
-       开展内部质量会议
-       培训过程中质量审计并收集数据，绘制图表和反馈意见
-       准备公司标准操作程序和检查表
-       确保测量仪器和测试设备的适当校准，当它们校准到期时要采取必要的行动
-       确保ESD在生产线处于准确位置
-       分析、建议和实施纠正措施计划以解决质量问题
-       每周开展质量会议并推动质量改进计划
-       执行公司指定的其他职责
 任职要求：
-       最好有至少10年左右的经验在制造业，有SAP数据库管理经验以及对SPC、FMEA、Poka Yoke、ISO 9000、AS9100、TS16949、6西格玛程序和其他建立的管理系统有良好了解更好
-        能够独立、自律
-        反应快，可靠，能与各级人员很好的交流互动
-        较强人际交往能力、 团队合作精神

RESPONSIBILITIES:
-      Ensure that products manufactured conformed to customer specification and requirements
-      Ensure that In-process audits are carried out
-      Identify and evaluate the products quality problems and work with the Manufacturing Engineer , Test Engineer (if applicable),Production Supervisor and IQC Engineer to develop corrective actions
- Ensure proper maintenance of the quality record at QA
- Liaise with customers on all Quality related issues
- Hold Internal Quality meeting
- Train QA In-process Audit Inspectors to collect data,plot Charts and feedback for actions
- Prepare Venture Standard Operating Procedure (Inspection) and checklist
- Ensure the measuring instrument and test equipments are duly calibrated and necessary actions to be taken when measuring instrument and test equipments calibrated are found to be expired
- Ensure ESD is in-place in the production
- Analysis, propose and implement corrective action plans to resolve quality issues
- Conduct weekly Quality meetings and drive quality improvement plans
- Perform any other duties as assigned by the Company
REQUIREMENTS:
- Sound knowledge of SPC, FMEA, Poka Yoke, ISO 9000, AS9100, TS16949,  6 Sigma programs and other established management systems will be advantageous
- Able to work independently with minimum supervision
- Resourceful, responsive, reliable and ability to interact with people at all levels
- Strong interpersonal, team player
工作地址：
桂桥路1201号T52-11
查看职位地图
**********
VENTURE ELECTRONICS SHANGHAI (万特电子)
公司规模：
1000-9999人
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.venture.com.sg
公司地址：
桂桥路1201号T52-11
**********
ICT测试技术员 ICT Test Technician
VENTURE ELECTRONICS SHANGHAI (万特电子)
**********
福利:
**********
职位月薪：6001-8000元/月 
工作地点：上海
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：其他
**********
岗位职责：
1.有维修PCBA板的经验
2.熟悉一种以上ICT测试设备(HP3070优先)，能够处理与解决ICT产线异常问题
3.1年以上ICT测试工作经验；熟悉电子电路，熟悉Agilent3070 等测试机及测试原理。有生产线技术支持者优先考虑
4.熟悉机型操作、保养、维护
5.态度端正、能吃苦耐劳，并能服从安排，有团队精神。
6.负责FCT/ICT/FP设备硬件维护保养，及飞针测试操作，程式调试及优化
7.不良反馈处理，不良品分析
8.对ICT机台及治具维护、维修、保养等。
 任职要求：
ICT或FCT维护经验

Skills:
1.Experience in the maintenance of PCBA
2. Familiar with more than one ICT test device (HP3070 priority) can deal with and solve the problem
3. Familiar with the operation, maintenance and maintenance of the model
4. Good attitude, hard work, obedience to arrangement, team spirit
5. Adverse feedback treatment and analysis of defective products
6. Maintenance, maintenance, maintenance, and maintenance of ICT platform and fixture
 Experience:
ICTorFCT maintenance Experience
工作地址：
桂桥路1201号T52-11
**********
VENTURE ELECTRONICS SHANGHAI (万特电子)
公司规模：
1000-9999人
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.venture.com.sg
公司地址：
桂桥路1201号T52-11
查看公司地图
**********
ICT测试工程师 ICT Test Engineer
VENTURE ELECTRONICS SHANGHAI (万特电子)
**********
福利:
**********
职位月薪：8001-10000元/月 
工作地点：上海
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：其他
**********
岗位职责：
1)为指定的客户提供一个专用的产品内容专家,测试解决方案的实现、项目的支持和诊断的支持.
2)维护ISO所有机器预防性维护工作的正确记录
3)负责新项目/设备的建立和管理
4)作为所有测试相关问题的主要接口,检查可测试性的所有程序集,与客户和设计设施进行交互，以改进测试访问、覆盖
5)为新客户或现有客户提供准确的测试报价
 任职要求：
1)电子工程专业，在工程类职位上有至少3年工作经验
2)良好的口头和书面沟通能力和人际交往能力,主动性工作和判断能力
3）能够改善测试方法、提供满足产品需要的硬件和软件
工作地址：
桂桥路1201号T52-11
**********
VENTURE ELECTRONICS SHANGHAI (万特电子)
公司规模：
1000-9999人
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.venture.com.sg
公司地址：
桂桥路1201号T52-11
查看公司地图
**********
初级硬件测试工程师（一部）
儒竞艾默生环境优化技术(上海)有限公司
五险一金年底双薪包住交通补助餐补通讯补贴带薪年假节日福利
**********
福利:
五险一金
年底双薪
包住
交通补助
餐补
通讯补贴
带薪年假
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：上海-杨浦区
发布日期：最新
工作性质：全职
工作经验：1年以下
最低学历：本科
招聘人数：1人
职位类别：硬件测试
**********
工作职责：
1、编制软/硬件测试用例，完成测试后提交测试报告；
2、定型前产品的送样测试和维修；
3、完成焓差测试、EMC测试等；
4、搭建测试平台、维护测试室设备、工具、配件等；
5、样机试制。

任职要求：
1、机电、测控、仪器仪表、自动控制、电子工程等电子类相关专业本科学历，有1年软件/硬件测试经验者优先考虑；
2、熟悉测试规范和常用测试工具，能根据需求说明书、软件概要设计说明书和软件详细设计说明书进行测试用例编写，并进行软件单元测试工作；
3、具有较强的学习能力、良好的沟通能力与团队协作能力；
4、有空调电控测试经验优先。

工作地址：
上海市杨浦区国权北路1688号湾谷科技园B5栋12楼
查看职位地图
**********
儒竞艾默生环境优化技术(上海)有限公司
公司规模：
100-499人
公司性质：
合资
公司行业：
电子技术/半导体/集成电路
公司主页：
www.ruking-emerson.com
公司地址：
上海市杨浦区国权北路1688号湾谷科技园B5栋12楼
**********
业务助理
上海中泰消防科技有限公司
五险一金年底双薪绩效奖金包吃
**********
福利:
五险一金
年底双薪
绩效奖金
包吃
**********
职位月薪：4001-6000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：助理/秘书/文员
**********
岗位职责：
1、协助业务完成投标等资料的准备；
2、配合业务完成各合约备案及流程扭转工作；
3、负责工程文档原件的收集、归档、管理，包括资审文件、招投标文件、中标通知书、合同及竣工文档的扫描；
4、负责业务部门日常进出款工作，及时处理日常发生的业务问题；
5、领导要求的其他工作。

任职要求：
1、熟练使用Word、Excel、Photoshop等办公软件。
2、沟通表达能力强，做事认真负责，有责任心。
3、大专以上学历，可接受应届生、有无工作经验均可。


工作地址：
普陀区中江路888号8楼
**********
上海中泰消防科技有限公司
公司规模：
20-99人
公司性质：
合资
公司行业：
互联网/电子商务
公司主页：
null
公司地址：
南京西路399号明天广场2F
查看公司地图
**********
变频器软件开发工程师（一部）
儒竞艾默生环境优化技术(上海)有限公司
五险一金年底双薪包住交通补助餐补通讯补贴带薪年假节日福利
**********
福利:
五险一金
年底双薪
包住
交通补助
餐补
通讯补贴
带薪年假
节日福利
**********
职位月薪：10001-15000元/月 
工作地点：上海-杨浦区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：嵌入式软件开发
**********
工作职责：
1、负责变频器等相关产品的软件研发工作；
2、协助项目负责人编制功能规格书，技术方案等；
3、编写软件方案、流程图等与软件相关的技术文件；
4、编制、调试项目中的软件，解决内部测试和客户测试时遇到的软件问题。

任职要求：
1、研究生毕业有变频器及相关产品研发经验者优先，或者应届毕业生课题为变频调速相关者；
2、有一定的电力电子产品控制软件开发经验；熟悉控制理论和电路知识，具备较好的数学基础和抽象、分析能力；
3、精通DSP/MCU应用，C编程和Matlab仿真等技能；
4、具备较好的工作、思维习惯和中英文表达能力，能独立思考和解决问题，勤奋认真，善于团队合作。

工作地址：
上海市杨浦区国权北路1688号湾谷科技园B5栋12楼
查看职位地图
**********
儒竞艾默生环境优化技术(上海)有限公司
公司规模：
100-499人
公司性质：
合资
公司行业：
电子技术/半导体/集成电路
公司主页：
www.ruking-emerson.com
公司地址：
上海市杨浦区国权北路1688号湾谷科技园B5栋12楼
**********
高级硬件工程师（一部）
儒竞艾默生环境优化技术(上海)有限公司
五险一金绩效奖金包吃包住餐补通讯补贴带薪年假免费班车
**********
福利:
五险一金
绩效奖金
包吃
包住
餐补
通讯补贴
带薪年假
免费班车
**********
职位月薪：15001-20000元/月 
工作地点：上海-杨浦区
发布日期：最新
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：1人
职位类别：高级硬件工程师
**********
岗位职责：
1、协助项目负责人编制功能规格书，技术方案等；
2、设计硬件方案、原理图、PCB等技术文件；
3、调试硬件，解决内部测试和客户测试时遇到的硬件问题；
4、生产和试制时到生产线上现场解决突发问题，努力完善设计，使产品便于生产；
5、协助测试编制硬件测试方案，审核硬件测试报告；
6、新元器件选型及测试方案制定。

任职要求： 
1、精通电路设计，PCB布板。电路调试，能熟练使用电路设计软件 ；
2、精通应用常用电子元器件（例如：IGBT、IPM、PIM、driver IC），熟悉检查各种元器件材料 ；
3、精通常用的硬件设计工具，调试仪器仪表（示波器，信号发生器等）的使用方法 ；
4、5年以上变频器产品的开发工作经验 ；
5、能够自行设计并独立开发完整的电子产品。

请符合要求的候选人积极投递，不符合要求或者无诚意者勿扰。有兴趣请直接投递，合适我们会先电话联系。谢绝直接电话或者直接上门拜访。
工作地址：
上海市杨浦区国权北路1688号湾谷科技园B5栋12楼
查看职位地图
**********
儒竞艾默生环境优化技术(上海)有限公司
公司规模：
100-499人
公司性质：
合资
公司行业：
电子技术/半导体/集成电路
公司主页：
www.ruking-emerson.com
公司地址：
上海市杨浦区国权北路1688号湾谷科技园B5栋12楼
**********
SMT技术员
VENTURE ELECTRONICS SHANGHAI (万特电子)
**********
福利:
**********
职位月薪：6001-8000元/月 
工作地点：上海
发布日期：招聘中
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：其他
**********
Responsible for SMT equipment current maintenance
Follow up on the quality of SMT product line products 、 Exception handling and feedback
Improvement of waste material in production 、Equipment exception handling
Line and adjustment of SMT production equipment
      SMT设备的日常保养与维护、
      SMT产线产品品质状况的跟进及异常处理和反馈
      生产抛料的改善，设备异常的处理
     SMT生产设备的转线和调整
工作地址：
桂桥路1201号T52-11
查看职位地图
**********
VENTURE ELECTRONICS SHANGHAI (万特电子)
公司规模：
1000-9999人
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.venture.com.sg
公司地址：
桂桥路1201号T52-11
**********
急聘：办公室文员/行政助理/后勤人员/文秘
上海卉刻电子商务有限公司
每年多次调薪五险一金带薪年假员工旅游14薪
**********
福利:
每年多次调薪
五险一金
带薪年假
员工旅游
14薪
**********
职位月薪：4001-6000元/月 
工作地点：上海-宝山区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：3人
职位类别：助理/秘书/文员
**********
岗位职责：
1、及时准确的更新员工通讯录；管理公司网络、邮箱；
2、负责日常办公用品采购、发放、登记管理，办公室设备管理；
3、订阅年度报刊杂志，收发日常报刊杂志及交换邮件；
4、员工考勤系统维护、考勤统计及外出人员管理。

任职资格：
1、大专及以上学历，无经验亦可，欢迎应届生；
2、熟悉办公室行政管理知识及工作流程，熟练运用OFFICE等办公软件；
3、工作仔细认真、责任心强、为人正直，具备较强的书面和口头表达能力；
薪资待遇： 
薪资5000+年终奖+带薪年假+免费下午茶+全勤奖
工作地址：
上海-宝山区
**********
上海卉刻电子商务有限公司
公司规模：
100-499人
公司性质：
合资
公司行业：
互联网/电子商务
公司地址：
上海市金山工业区亭卫公路6558号5幢6397室
查看公司地图
**********
行政管理
上海中泰消防科技有限公司
五险一金每年多次调薪绩效奖金
**********
福利:
五险一金
每年多次调薪
绩效奖金
**********
职位月薪：4001-6000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：1人
职位类别：其他
**********
岗位职责：
1、 负责办公室日常办公制度维护、管理。
2、 负责办公室各部门办公后勤保障工作。
3、 负责对全体办公人员（各部门）进行日常考勤。
4、 处理公司对外接待工作。
5、 协助总经理处理行政外部事务。
6、 按照公司行政管理制度处理其他相关事务。

工作地址：
芙蓉江路533号
查看职位地图
**********
上海中泰消防科技有限公司
公司规模：
20-99人
公司性质：
合资
公司行业：
互联网/电子商务
公司主页：
null
公司地址：
南京西路399号明天广场2F
**********
技术销售
技硕贸易(上海)有限公司
五险一金绩效奖金带薪年假补充医疗保险定期体检通讯补贴
**********
福利:
五险一金
绩效奖金
带薪年假
补充医疗保险
定期体检
通讯补贴
**********
职位月薪：6000-10000元/月 
工作地点：上海
发布日期：最近
工作性质：全职
工作经验：1年以下
最低学历：大专
招聘人数：2人
职位类别：销售工程师
**********
工作概要：
根据给定的销售目标和销售地区开发新应用并维护老客户。

工作职责：
与技术销售经理密切合作
开发新的应用以及新客户
维持现有客户的当前销售
识别市场和客户
提高公司名称和声誉
对客户进行销售和技术咨询
定期提交销售报告
需要出差拜访客户，积极参与销售活动

学历要求：
化学/材料/聚合物/电子工程或任何相关领域的学士学位

工作经验：
1〜2年。欢迎应届毕业生申请。

其他要求：
快速学习，勤奋，自律，自学和自我激励
能够与各级客户进行谈判
提出产品建议并提供技术支持
良好的计算机（Windows和MS Office）和英语沟通能力
良好的人际关系，良好的解决问题的能力和强大的团队合作精神

工作地址：
上海市闸北区共和新路3088号祥腾财富广场9号楼1002室
查看职位地图
**********
技硕贸易(上海)有限公司
公司规模：
20人以下
公司性质：
外商独资
公司行业：
贸易/进出口
公司主页：
www.padhesive.com.cn
公司地址：
上海市闸北区共和新路3088号祥腾财富广场9号楼1002室
**********
工资5500/包食宿+报销路费
达利(上海)电脑有限公司
五险一金包住包吃全勤奖年底双薪绩效奖金带薪年假节日福利
**********
福利:
五险一金
包住
包吃
全勤奖
年底双薪
绩效奖金
带薪年假
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：100人
职位类别：普工/操作工
**********
大量招募  天天面试，

年后正月十五之前入职的新员可奖励1500-3500工资额外补贴
面试成功当天安排食宿
保障：免费发放工作服。（面试直接来工厂）
优势：坐式工作,厂房内有中央空调，不穿无尘服，订单多，加班多。
晋升：近期入职岗位好、工资高、 晋升和发展空间大、还没工作的您速速联系我们。
【招聘岗位】仓管、物料员、稽核员、维修、ME、OP、OQC、SQE、FE1、制程、作业员
二．薪资待遇；
1，薪资待遇一一一（月综合工资4800-5500元左右，每个月10号发工资）。
2，食宿情况一一一(公司提供不收费，当天进厂分宿舍）。
3，加班费算法：2430元，(平时加班1.5倍；周末加班2倍；国定假日3倍)
4，加班工资平时加班21.1元/小时；
5，周末加班32.4元/小时小时；
6，国定假日加班41.8元/小时；
7，中班津贴 10元/天,夜班津贴15元/天；
8，年终奖金 — 每年春节前按当年度工作绩效及整体贡献发放年终奖。
9，综合工资的高低取决于加班时数的多少，一般综合工资在4800-5500元左右.
工作时间
（1）工作时间：早上8点上班 — 中午吃饭休息1小时 — 17点下班；
（2）加班时间：周一至周五（17点 — 20点）；双休日和法定假日上班（8点——20点）算加班。
（3）公司常年订单稳定，保证平时加班以及周末加班；加班与否随个人意愿，公司不管控加班，不强制加班；
6、加薪晋升：针对优秀员工，将依其工作绩效及领导潜能，逐步向上提升为领班﹑组长及课长职务(生产部门所有领导职务不外招,均內部提拔)，且公司提供训练与津贴；
有朋友一起来公司上班的，可以优先安排同一部门，同一宿舍。
友情提示！车站旁边，行骗之人较多，请注意保管自己的财务！不要随便跟陌生人交谈。到站后，请按照我们指定的路线到达公司，请勿听信中介忽悠，以免上当受骗。
工作地址：
上海市松江出口加工区
查看职位地图
**********
达利(上海)电脑有限公司
公司规模：
10000人以上
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
https://baike.baidu.com/item/%E8%BE%BE%E5%88%A9%EF%BC%88%E4%B8%8A%E6%B5%B7%EF%BC
公司地址：
上海市浦东南路29号
**********
猎头顾问
上海英擎企业管理咨询有限公司
五险一金年底双薪绩效奖金年终分红房补员工旅游节日福利每年多次调薪
**********
福利:
五险一金
年底双薪
绩效奖金
年终分红
房补
员工旅游
节日福利
每年多次调薪
**********
职位月薪：6000-12000元/月 
工作地点：上海-浦东新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：2人
职位类别：猎头顾问/助理
**********
岗位职责：
1. 充分理解客户需求，完成客户岗位职责的分析并制定完善的人才寻访方案；
2. 寻访目标候选人，负责甄选、面试、评估候选人，为候选人提供专业的职业规划帮 助，帮助其找到最优的职业发展路线；
3. 向客户提供专业化、标准化以及系统的人才推荐报告；
4. 协调和推动客户进一步安排候选人的面试并及时反馈面试结果
任职要求：
1. 本科以上学历，无猎头经验者亦可；
2. 较强的学习能力、优秀的执行力；
3. 能够承受工作压力。

工作地址：
上海市浦东新区张江高科龙东大道666弄1号楼301
**********
上海英擎企业管理咨询有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
专业服务/咨询(财会/法律/人力资源等)
公司地址：
上海市浦东新区张江高科龙东大道666弄1号楼301
查看公司地图
**********
上海电子厂月薪5500包吃住
上海欧光电子科技有限公司
五险一金年底双薪绩效奖金年终分红加班补助全勤奖包吃餐补
**********
福利:
五险一金
年底双薪
绩效奖金
年终分红
加班补助
全勤奖
包吃
餐补
**********
职位月薪：6001-8000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：63人
职位类别：普工/操作工
**********
招聘岗位，普工操作工，包装组装工，检测员物料员，维修人员，仓管，。报名热线，13501940935杜助理，微信同号
薪资结构。金额(元) 说明；
1，薪资待遇-----（月综合工资4500-6500元左右，每个月10号发工资）。
2，食宿情况------(提供食宿，当天进厂分宿舍）.
3，基本工资2520元，8小时双休）8小时以外都算加班，加班有加班费！
4，加班费算法：平时加班1.5倍；周末加班2倍；国定假日3倍
5，加班工资平时加,1.5倍 20。95元/小时；
6，周末加班2倍 27.93元/小时小时；
7，国定假日加班3倍 41.90元/小时；
8，夜班津贴9元/天；
9，年终奖金 — 每年春节前按当年度工作绩效及整体贡献发放年终奖。
10，综合工资的高低取决于加班时数的多少，一般综合工资在4500-6500元左右。
二．福利待遇；
1.保险：公司依法为员工缴纳保险
2.休假：员工依法享受国家法定节假日、婚假、丧假、产假、带薪年休假等
3.贴心的福利：生日礼券、结婚礼金、生育津贴等；
4.各项便利设施：室内篮(羽)球场、网吧、图书馆、韵律教室、便利商店、邮局、各式美食餐厅等。
三．伙食住宿；
1.公司提供食宿（一日三餐）生活区内设有大型员工餐厅。
2.公司为员工提供宿舍，园区外及园区内宿舍皆采取小区式管理，配备宿舍管理员及安保。免水电费。所有宿舍均提供独立的冷暖空调，二十四小时供应洗浴热水及饮用水。
四．招聘条件；
1、18-35周岁。
2、认真学习、遵守企业规章制度，可尽快融入企业氛围。
3、持有效身份证件。（持有效二代身份证）。
4，身体健康，没有犯罪前科。
五. 工作时间；
1、正常工作时间：每天8小时，五休二
2、加班时间：平时每日加班不超过3小时，每周至少休息1天。
3、公司执行白晚班两班制。
请按照我们的指定路线请来面试

报名方式：姓名+身份证号+面试日期+发至13661522104

工作地址：
上海市浦东新区中桥学校
查看职位地图
**********
上海欧光电子科技有限公司
公司规模：
10000人以上
公司性质：
合资
公司行业：
加工制造（原料加工/模具）
公司地址：
上海市浦东新区金科路
**********
名企直聘物料/质检/操作工
上海华硕高科技有限公司
五险一金年底双薪绩效奖金全勤奖加班补助包吃包住免费班车
**********
福利:
五险一金
年底双薪
绩效奖金
全勤奖
加班补助
包吃
包住
免费班车
**********
职位月薪：6001-8000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：69人
职位类别：普工/操作工
**********
报名方式：17349768702常彩彩 同微信 可加微信了解求职问题。
郑重声明：
官方免费直招火热报名中，快乐工作，幸福生活，期待你的加入，让我们的生活从此开始闪“硕”！
报名，面试不收费、先面试后体检！确定面试成功后需参加体检（体检费50元，需个人承担）。
声明：公司招聘无任何额外费用，在官方报名后，请勿在其他地方报名，以免系统冲突无法安排面试！
报名方式：17349768702常彩彩 同微信 可加微信了解求职问题。
招聘岗位：
普工、技工、QC质检、电脑维修、物料员等多岗位，根据生产需求随机安排岗位！
薪资待遇
1、薪资架构：岗位工资（2430元）+其他福利（50—210元）+综合绩效奖金（100—300元）+加班费+旺季奖金+职位技能奖；综合加班工资3900-5500元；
2、平时加班20.95元/小时；周末加班27.93元/小时；国定假日加班41.90元/小时；
3、夜班津贴9元/天；
4、年终奖金：2000-8000元，每年春节前按当年度工作绩效及整体贡献发放年终奖。
福利待遇
1、保险：公司统一为每一位员工购买相关保险；
2、休假：员工享受法定节假日、婚假、丧假、产假、带薪年休假；
3、贴心的福利：生日礼券；
4、活动：球类比赛、艺文表演；
5、便利设施：室内篮(羽)球场、网吧、图书馆、便利商店、邮局、各式美食餐厅等。
招聘要求
1、男女不限：年满16-45周岁，认识26个英文字母；
2、无大面积纹身、烟疤、无重大手术史和传染性疾病；
3、认真学习、遵守企业规章制度，可尽快融入企业氛围；
4、持有二代有效身份证件，无犯罪记录。
岗位工作职责
工作内容：主要从事高科技电子产品的生产；
工作时间：每周工作5天，每天8小时工作制，超出部分安加班计算工资，每天加班不超过3小时。
宿舍环境：
员工当天面试安排住宿，宿舍8人间，宿舍区设有免费WIFI、冷暖空调、24小时供应热水、独立卫浴间、个人专属储物柜、影视厅娱乐听、自动售卖机等方便员工生活的生活设备。。
友情提示！
车站周边，行骗之人较多，请注意防范、保管自己的个人信息和财物！不要随便跟陌生人交谈、不要将自己的身份证轻易交给陌生人、远离主动上前跟你搭话的人；我们面试无需手机关机请保持手机通畅。到站后，请按照通知路线前往面试中心或及时联系我们的招募客服乘车前往面试中心！

工作地址：
上海市浦东新区秀沿路3768号
查看职位地图
**********
上海华硕高科技有限公司
公司规模：
10000人以上
公司性质：
国企
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.asus.com.cn/About_ASUS/Origin-of-the-Name-ASUS
公司地址：
上海市浦东新区秀沿路3768号
**********
销售工程师
上海海赋机电设备有限公司
五险一金绩效奖金餐补通讯补贴带薪年假定期体检员工旅游加班补助
**********
福利:
五险一金
绩效奖金
餐补
通讯补贴
带薪年假
定期体检
员工旅游
加班补助
**********
职位月薪：7000-12000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：2人
职位类别：销售工程师
**********
要求： 
1）身体健康，大学专科及以上学历毕业； 
2）一年以上相关经验，具有机电产品销售经验者优先； 
3）有上进心，责任心强，善于学习，工作勤奋，具有良好的团队合作精神； 
4）具有良好的表达能力，善于沟通，能熟练使用OFFICE等办公软件； 

岗位描述： 
1）根据公司的销售目标协助完成预订销售任务； 
2）能广泛回访终端客户，建立并维护长期良好的客户关系； 
3）能识别客户需求，推荐解决方案和积极创造销售机会；
工作地址：
嘉定区沪宜公路1101号南翔智地越界产业园
查看职位地图
**********
上海海赋机电设备有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
大型设备/机电设备/重工业
公司地址：
嘉定区沪宜公路1101号南翔智地越界产业园
**********
省级销售经理
上海辰光医疗科技股份有限公司
**********
福利:
**********
职位月薪：6001-8000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：5人
职位类别：区域销售经理/主管
**********
1、在区域内医院进行公司产品（磁共振射频线圈、7.0T动物实验系统等）的销售推广工作，完成销售任务；
2、建立渠道销售网络，维护管理经销商并提供产品知识培训；
3、负责区域内客户信息的收集、整理；
4、及时反馈市场需求信息，竞争对手情况和客户反馈意见等市场信息；
5、维护新老客户，负责区域内销售回款；

要求：1、3年以上销售经验，熟悉医院工作模式及医疗器械类产品销售经验优先；
      2、专科以上学历；
      3、较强的语言沟通能力，善于维护客户关系，具有突发事件处理能力；
      4、适应出差，能承受较大的工作压力。
薪资：工资+绩效奖金+提成+年终奖

工作地址：
上海市青浦区华青路1269号
**********
上海辰光医疗科技股份有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
医疗设备/器械
公司主页：
http://www.shanghaicg.net
公司地址：
上海市青浦区华青路1269号
查看公司地图
**********
医疗器械销售代表
上海辰光医疗科技股份有限公司
**********
福利:
**********
职位月薪：5000-8000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：无经验
最低学历：大专
招聘人数：1人
职位类别：医疗器械推广
**********
1、负责MRI整机、磁共振射频探测器（线圈）及其他影像设备的销售，MRI系统维保销售；
2、区域经销商的建立、考核及管理；
3、产品宣传及经销商的培训；


要求：1、热爱销售工作；
      2、较强的沟通交际能力、学习能力、抗压能力；
      3、适应出差；
工作地址：
上海市青浦区华青路1269号
**********
上海辰光医疗科技股份有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
医疗设备/器械
公司主页：
http://www.shanghaicg.net
公司地址：
上海市青浦区华青路1269号
查看公司地图
**********
研发助理（二部）
儒竞艾默生环境优化技术(上海)有限公司
五险一金绩效奖金加班补助包住餐补带薪年假免费班车员工旅游
**********
福利:
五险一金
绩效奖金
加班补助
包住
餐补
带薪年假
免费班车
员工旅游
**********
职位月薪：4001-6000元/月 
工作地点：上海-杨浦区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：1人
职位类别：项目专员/助理
**********
职责描述：
1. 将研发工程师设计的BOM物料清单输入系统；
2. 更新CAD结构图纸，文档归档整理；
3. 和工厂的沟通交互；
4. 上级安排的其他任务。

任职要求：
1. 熟悉应用常用电子元器件；
2. 自动化类、电力电子类专业；
3. 严格遵守公司规定，有良好的职业习惯；
4. 1-2年相关行业工作经验或优秀应届毕业生。
工作地址：
上海市杨浦区国权北路1688号湾谷科技园B5栋12楼
查看职位地图
**********
儒竞艾默生环境优化技术(上海)有限公司
公司规模：
100-499人
公司性质：
合资
公司行业：
电子技术/半导体/集成电路
公司主页：
www.ruking-emerson.com
公司地址：
上海市杨浦区国权北路1688号湾谷科技园B5栋12楼
**********
市场营销专员
上海苍穹环保技术有限公司
五险一金绩效奖金带薪年假不加班
**********
福利:
五险一金
绩效奖金
带薪年假
不加班
**********
职位月薪：4001-6000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：5人
职位类别：市场营销专员/助理
**********
岗位基本职责：
负责线上、线下的市场营销策划、产品宣传、品牌建设与维护、客户关系维护，完成领导交办的工作。

岗位专业要求：
大专以上学历，专业不限。具有2年以上市场营销工作相关经验。特别优秀者要求可适当下降。

岗位能力要求：
1、执行力强，具有较强的责任心。
2、善于沟通协调，具有团队合作精神。
3、擅长产品的线上、线下宣传推广，具有市场营销、品牌建设、客户服务等相关工作经验。
4、熟练使用办公软件，具有较强的ppt制作能力。

其他任职要求（必须满足）：
身体健康，年龄在45岁以下，已定居上海。

工作时间：
周一至周五，上午8:30-12:00，下午13:00-17:00。
工作地址：
上海市江场三路301号3楼（市北高新园区内）
**********
上海苍穹环保技术有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
环保
公司主页：
http://www.scqair.cn
公司地址：
上海市江场三路301号3楼（近江场西路，市北高新园区内）
查看公司地图
**********
新工厂普工，操作工，维修包装，仓库管理
上海君硕电子科技有限公司
五险一金全勤奖包吃员工旅游节日福利带薪年假餐补包住
**********
福利:
五险一金
全勤奖
包吃
员工旅游
节日福利
带薪年假
餐补
包住
**********
职位月薪：4600-7500元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：118人
职位类别：普工/操作工
**********
公司大量免费招聘正式工/拎包入住 /当天安排住宿。
报名电话  15021920182  微信同号  杜经理
【保障】：免费发放工作服。
【福利】：缴纳五险一金、入职和厂家签订劳动合同、属于正式厂方员工。
【惊喜】：公司单身的年轻姑娘小伙较多，公司为单身的员工一年举行联谊晚会及开办兴趣社团。
【优势】：坐式工作占80%，厂房内有中央空调，不穿无尘服，订单多，加班多
【晋升】：近期入职岗位好、工资高、 晋升和发展空间大、还没工作的您速速联系我们招募组
—— 注意：工作地点【上海市浦东新区康桥工业园区】——
【工资待遇】
全勤奖金：200
绩效奖金：180-300
岗位津贴：150-210
年终奖金；3000-10000
夜班津贴9/天
加班费:正常工作时间(8小 时/日)以外的劳动时间均算加班时间。
平时:20.95元/小时(1.5倍)
双休日:27.93元/小时(2倍)
国家法定日:41.90元/小时(3倍)
底薪2430+加班+全勤奖+绩效+职位补助 月薪4500元-6000元
【工作描述】
工作内容：主要从事生产苹果系列产品。
岗位内容：不穿无尘服，对身体无任何危害、没工作经验可以培训上岗。
工作时间：正常工作时间为5天8小时，公司执行白晚班两班制。
加班时间：平时每日8小时工作制度，做五休二或做六休一，其余都按加班费用计算，中间含吃饭休息一小时。
【工作要求】
1、年龄：18-45周岁，男女不限
2、学历：学历不限
3、健康：女身高150cm以上，男身高155cm以上，无传染疾病或精神疾病
【住宿情况】
宿舍配有保安、宿管24小时值班
凡是从网上报名入职的员工宿舍择优，为6-8人间，宿舍设有空调，热水器，独立卫生间，独立阳台，无线网。有班车免费接送
【伙食情况】
生活区内设大型餐厅和西餐厅，有南北方各地特色、中西方美食，满足多样化的用餐需求，早餐供应各类面点、蛋类、粥类，中餐和晚餐可选择四菜一汤（2大荤,一小荤，二素菜一汤）
【晋升机会】
根据个人能力及表现可以通过自荐和提拔两种渠道提升为组长、主管、文员、另外【人事部、行政部、财务部、工程部等】也从基层挑选踏实能干的优秀员工
【休闲设施】
公司内设健身房、舞蹈室、美妆室、银行、邮局、超市、美发室，图书馆、、网吧、体育馆、足球场、溜冰场、桌球、棋牌等
【贴心服务】
公司提供免费心理咨询服务，倾听员工工作、生活及情感中遇到的挫折、帮助、开导员工
【其他福利】
生活小区：提供环境优美的宿舍，可容纳15000人的大型生活区
【面试所需】
个人生活用品、个人一寸照片6张，黑色水笔1支、一个本子（需要填写个人简历和培训）

工作地址：
浦东新区康桥工业区
查看职位地图
**********
上海君硕电子科技有限公司
公司规模：
10000人以上
公司性质：
合资
公司行业：
加工制造（原料加工/模具）
公司地址：
浦东新区
**********
采购专员/外贸专员 月度奖金+住宿
上海卉刻电子商务有限公司
每年多次调薪五险一金绩效奖金年终分红包住带薪年假节日福利
**********
福利:
每年多次调薪
五险一金
绩效奖金
年终分红
包住
带薪年假
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：上海-闵行区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：2人
职位类别：采购专员/助理
**********
岗位职责：
1、执行采购订单和采购合同，落实具体采购流程；
2、负责采购订单制作、确认、安排发货及跟踪到货日期；
3、执行并完善成本降低及控制方案；
4、开发、评审、管理供应商，维护与其关系；
5、填写有关采购表格，提交采购分析和总结报告；
6、完成采购主管安排的其它工作。

任职资格：
1、大专及以上学历；
2、无经验亦可；
3、熟悉采购流程，良好的沟通能力、谈判能力和成本意识；
4、工作细致认真，责任心强，思维敏捷，具有较强的团队合作精神，
工作地址：
上海-闵行区
**********
上海卉刻电子商务有限公司
公司规模：
100-499人
公司性质：
合资
公司行业：
互联网/电子商务
公司地址：
上海市金山工业区亭卫公路6558号5幢6397室
查看公司地图
**********
设计人员
上海勇电照明有限公司
五险一金绩效奖金加班补助餐补带薪年假员工旅游高温补贴节日福利
**********
福利:
五险一金
绩效奖金
加班补助
餐补
带薪年假
员工旅游
高温补贴
节日福利
**********
职位月薪：2001-4000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：2人
职位类别：平面设计经理/主管
**********
任职要求：
1、女，高中及以上学历，年龄在22-30岁间；
2、有创新意识，有激情、上进心，有较强的语言表达能力，具备吃苦耐劳的精神。
3、能够熟练操作Photoshop、Flash、CAD等设计软件。
4、有夜景设计经验者优先考虑。

工作地址：
闸北区江场西路538号601室
**********
上海勇电照明有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司地址：
闸北区江场西路538号601室
查看公司地图
**********
上海浦东电子厂，直招普工操作工，包吃住
上海欧光电子科技有限公司
五险一金包住年底双薪绩效奖金加班补助全勤奖包吃员工旅游
**********
福利:
五险一金
包住
年底双薪
绩效奖金
加班补助
全勤奖
包吃
员工旅游
**********
职位月薪：5500-6500元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：无经验
最低学历：不限
招聘人数：128人
职位类别：普工/操作工
**********
招聘岗位，普工操作工，包装组装工，检测员物料员，维修人员，仓管，
。报名热线，13501940935 杜助理，微信同号
薪资结构。金额(元) 说明；
1，薪资待遇-----（月综合工资4500-6500元左右，每个月10号发工资）。
2，食宿情况------(提供食宿，当天进厂分宿舍）.
3，基本工资2430元，8小时）8小时以外都算加班，加班有加班费！
4，加班费算法：平时加班1.5倍；周末加班2倍；国定假日3倍
5，加班工资平时加,1.5倍 21。95元/小时；
6，周末加班2倍 27.93元/小时小时；
7，国定假日加班3倍 41.90元/小时；
8，夜班津贴9元/天；
9，年终奖金 — 每年春节前按当年度工作绩效及整体贡献发放年终奖。
10，综合工资的高低取决于加班时数的多少，一般综合工资在4500-6500元左右。
二．福利待遇；
1.保险：公司依法为员工缴纳保险
2.休假：员工依法享受国家法定节假日、婚假、丧假、产假、带薪年休假等
3.贴心的福利：生日礼券、结婚礼金、生育津贴等；
4.各项便利设施：室内篮(羽)球场、网吧、图书馆、韵律教室、便利商店、邮局、各式美食餐厅等。
三．伙食住宿；
1.公司提供食宿（一日三餐）生活区内设有大型员工餐厅。
2.公司为员工提供宿舍，园区外及园区内宿舍皆采取小区式管理，配备宿舍管理员及安保。免水电费。所有宿舍均提供独立的冷暖空调，二十四小时供应洗浴热水及饮用水。
四．招聘条件；
1、18-35周岁。
2、认真学习、遵守企业规章制度，可尽快融入企业氛围。
3、持有效身份证件。（持有效二代身份证）。
4，身体健康，没有犯罪前科。
五. 工作时间；
1、正常工作时间：每天8小时，五休二
2、加班时间：平时每日加班不超过3小时，每周至少休息1天。
3、公司执行白晚班两班制。
请按照我们的指定路线请来面试

报名方式：姓名+身份证号+面试日期+发至13501940935

工作地址：
上海市浦东新区川周公路2788
查看职位地图
**********
上海欧光电子科技有限公司
公司规模：
10000人以上
公司性质：
合资
公司行业：
加工制造（原料加工/模具）
公司地址：
上海市浦东新区金科路
**********
招聘电子厂，普工操作工
上海君硕电子科技有限公司
五险一金年底双薪包住餐补员工旅游加班补助绩效奖金全勤奖
**********
福利:
五险一金
年底双薪
包住
餐补
员工旅游
加班补助
绩效奖金
全勤奖
**********
职位月薪：5500-6500元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：108人
职位类别：普工/操作工
**********
报名电话 15021920182杜经理  微信同号
招聘职位:
操作工 （200）名；仓库管理员（20）名；物料员（10）名；质检员（40）名；产线文员（10）名；设备维修保养员（5）名；储备干部（2）名；CAD学徒（10）名；办公文员（5）名；保安（10）名
一、薪资待遇
(月综合平均薪资:4500-6000元)
1、薪资构成：底薪+津贴（年资津贴+岗位津贴）+加班费+团队奖金；
2、基本底薪：第一个月2500，第二个月转正后2700；全勤奖金：200元/月；技能津贴：300-600/月；
3、夜班津贴：18元/班；岗位津贴：300-800/月；季度奖金：300-2000/元；
4、月综合平均薪资:4500-6000元；公司给每位员工缴纳五险一金；
5、加班：正常工作日1.5倍；周六周末2倍；国家法定假节日3倍；
6、工作时间早8：00-晚17:00；夜班晚20:00--早5：00
7、带薪休假7天起，每两年增加1天，
8、为员工提供多种培训机会，提升员工各方面的能力；
二、饮食住宿与福利
1、公司对员工提供住宿及床上四件套，宿舍环境舒适4-8人间，空调，24小时热水，无线网。
2、工作餐：早餐有包子，油条，馒头，豆浆，稀饭，水饺等。午餐及晚餐四菜一汤，两荤两素，保障员工营养均衡。
3、厂内生活区有网吧，篮球场，健身房，KTV，桌球，乒乓球，舞蹈房，图书室，便利店；
4、定期举行活动（旅游，聚餐，公司文化节，单身联谊等）；
5、节假日公司有免费班车,方便员工假日出行。
6、转正后为员工提供如下福利金:结婚喜庆礼金、生育礼金、丧葬礼金、困难救助金、独生子女补助金、生日礼金。
三、招聘条件
1、男女：年满16-40周岁、
2、认真学习、遵守企业规章制度，可尽快融入业氛围；
3、持二代有效身份证件。
4、身上不能有超大纹身，不能有犯罪记录。
四、工作职责
1、每天从事电子组装方面的工作；
2、上班时间为正常8个小时制，超过的算加班；
3、休息时间为每周休息一天，保证你们的身体放松；
4、企业分为两班倒，白班和晚班，一般为坐式工作，站式工作比较少。
工作地址：
浦东新区康桥工业区
查看职位地图
**********
上海君硕电子科技有限公司
公司规模：
10000人以上
公司性质：
合资
公司行业：
加工制造（原料加工/模具）
公司地址：
浦东新区
**********
招商总监
上海开皇实业有限公司
创业公司五险一金包吃弹性工作节日福利定期体检包住绩效奖金
**********
福利:
创业公司
五险一金
包吃
弹性工作
节日福利
定期体检
包住
绩效奖金
**********
职位月薪：15000-25000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：2人
职位类别：销售总监
**********
岗位职责：
1. 参与制定公司总体招商战略及目标，根据公司总体战略目标制定所辖地区招商加盟拓展的年、季、月度计划并执行；
2. 招商指标达成。负责完成公司下达的招商任务，围绕招商目标和招商战略，制定切实可行的招商策略、推进方案、落地计划，带领招商团队完成招商指标；
3. 签约成交率。根据公司的要求进行招商进线转化，完成进化转化目标；
4. 负责部门团队建设，并通过激励以及淘汰机制，有效保证招商团队的活力；
5. 负责安排部门内各岗位人员的培训，保证部门招商人员的签约成交率；
6. 负责部门内的绩效考核，并有序开展绩效面谈，以保证团队沟通的畅通；
7. 上级领导安排的其他工作。
 任职资格：
1. 具备市场营销知识、熟悉加盟行业，招商行业,了解同行相关品牌的运作模式和优劣势；
2. 具备良好的表达和沟通能力，能准确把握客户的真实想法，耐心热情、有亲和力、开拓精神、团队合作精神和责任心；
3. 具有丰富的招商谈判经验，
4.五年以上品牌招商、加盟招商、市场开发相关工作经验；
5. 有一定抗压能力；
6. 大专以上，市场营销、管理专业优先；
薪资福利：
1、固定薪资+绩效+年终奖；具体面议，根据能力提要求；
2、周末双休：上班时间为周一到周五（9:00-18:00，)；
3、享有国家法定节假日以及带薪年假、婚假、产假等各项法律法规规定的假期；
4、公司还提供生日福利、过节福利、免费体检,免费提够工作餐
5、与公司签订正式劳动合同，享受国家规定的五险一金（养老、失业、医疗、生育、工伤、住房公积金）

工作地址：
长宁区剑河路888弄B-22
查看职位地图
**********
上海开皇实业有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
互联网/电子商务
公司主页：
http://www.bintutu.com/index.html
公司地址：
长宁区剑河路888弄B-22
**********
销售专员
上海开皇实业有限公司
创业公司每年多次调薪五险一金绩效奖金包吃节日福利定期体检
**********
福利:
创业公司
每年多次调薪
五险一金
绩效奖金
包吃
节日福利
定期体检
**********
职位月薪：4500-6500元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：5人
职位类别：电话销售
**********
岗位职责：
1. 拓展客户，与意向客户进行加盟代理前期沟通；
2. 邀约意向客户来公司总部考察与培训；
3. 来访客户全程协助接待、销售洽谈与谈判、意向与正式加盟合同的签订。
4. 签约客户的后续执行沟通服务；
5. 具备较强的分析能力、表达能力、沟通能力、应变能力等。
任职要求：
1.20-30岁，大专以上，欢迎有志于挑战自我，挑战高薪者；
2.形象气质良好、心态积极、性格外向、喜欢与人沟通；
3.具备良好的自我管理和抗压能力；
4.认同公司的企业文化和价值观；
5.具有电话销售或招商销售工作经验者优先考虑。
福利：绩效奖金，五险一金，包吃，带薪年假，节日福利 , 免费体检 ,8小时双休
薪资：底薪+高额提成
 我们的平台：
如果你是千里马，这里将是任你驰骋的疆场。公正公平的福利待遇，开明活跃的公司氛围，友好团结的领导同事，前途无量的发展前景，在这里，价值会得到充分的发挥。只要你是一个努力的充满激情和梦想的人，相信你会融入我们，并和我们一起创造辉煌！
工作时间：周一-周五（9:00-18:00）
工作地址:长宁区剑河路888弄B22



工作地址：
长宁区剑河路888弄B-22
查看职位地图
**********
上海开皇实业有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
互联网/电子商务
公司主页：
http://www.bintutu.com/index.html
公司地址：
长宁区剑河路888弄B-22
**********
招商专员——销售方向
上海开皇实业有限公司
创业公司五险一金绩效奖金年终分红包吃弹性工作定期体检节日福利
**********
福利:
创业公司
五险一金
绩效奖金
年终分红
包吃
弹性工作
定期体检
节日福利
**********
职位月薪：4500-6500元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1年以下
最低学历：不限
招聘人数：5人
职位类别：电话销售
**********
岗位职责：
1. 拓展客户，与意向客户进行加盟代理前期沟通；
2. 邀约意向客户来公司总部考察与培训；
3. 来访客户全程协助接待、销售洽谈与谈判、意向与正式加盟合同的签订。
4. 签约客户的后续执行沟通服务；
5. 具备较强的分析能力、表达能力、沟通能力、应变能力等。
任职要求：
1.20-30岁，大专以上，欢迎有志于挑战自我，挑战高薪者；
2.形象气质良好、心态积极、性格外向、喜欢与人沟通；
3.具备良好的自我管理和抗压能力；
4.认同公司的企业文化和价值观；
5.具有电话销售或招商销售工作经验者优先考虑。
6.底薪+高额提成


工作地址：
长宁区剑河路888弄B-22
查看职位地图
**********
上海开皇实业有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
互联网/电子商务
公司主页：
http://www.bintutu.com/index.html
公司地址：
长宁区剑河路888弄B-22
**********
采购专员
上海誉光光电科技有限公司
五险一金绩效奖金年终分红交通补助节日福利
**********
福利:
五险一金
绩效奖金
年终分红
交通补助
节日福利
**********
职位月薪：3000-6000元/月 
工作地点：上海-浦东新区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：5人
职位类别：采购专员/助理
**********
岗位描述：
1、开发、拓展、维护与客户的业务，建立和维护客户档案；
2、维护好内部资源，与客户保持良好联系，提高客户满意度；
3、收集和分析市场数据，并定期反馈最新信息；
4、准备采购合同、报价单等文件；
5、良好的客户服务意识，能承受较大的工作压力和强度；
6、有较强的语言表达和沟通协调能力；
7、性格开朗，责任心强，较强的协调能力及执行力；
8、工作积极、热心主动、头脑思维活跃、学习能力强。
 福利待遇：
1、底薪+业务提成+补贴+年终奖金；
2、完善福利体系：
1）实行五天工作制、享受国定假期；
2）五险一金；
3）公司设有出差补贴、节日福利等等。
    我司现有良好的团队建设和团队氛围，对员工也有很好的激励措施。欢迎您的加入，大家一起努力、一起奋斗！

工作地址：
上海市浦东新区绣川路581号绿地东海岸A座1603室
**********
上海誉光光电科技有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.yuphoton.com
公司地址：
上海市浦东新区绣川路581号绿地东海岸A座1603室
查看公司地图
**********
销售代表
锐利贸易集团有限公司
五险一金绩效奖金餐补加班补助通讯补贴节日福利
**********
福利:
五险一金
绩效奖金
餐补
加班补助
通讯补贴
节日福利
**********
职位月薪：5000-8000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：3人
职位类别：渠道/分销专员
**********
岗位职责：
1、负责公司产品的销售及推广；
2、根据市场营销计划，完成部门销售指标；
3、开拓新市场,发展新客户,增加产品销售范围；
4、负责辖区市场信息的收集及竞争对手的分析；
5、负责销售区域内销售活动的策划和执行，完成销售任务；
6、管理维护客户关系以及客户间的长期战略合作计划。
任职资格：
1.专科及以上学历，市场营销等相关专业优先；
2.1年及以上快消品行业工作经验，业绩突出者优先；
3.认真细致，性格外向、反应敏捷、表达能力强，具有较强的沟通能力及交际技巧，具有亲和力；
4.具备一定的市场分析及判断能力，良好的客户服务意识；
5.有责任心，能承受较大的工作压力，有良好的团队服务意识；
6.办公软件应用熟练（esp. Word，Excel，PPT）。

薪资福利：
1.合理优厚的薪金：基本工资+考核工资+绩效工资等；
2.优厚的福利体系：养老保险、医疗保险、生育保险、工伤保险、失业保险及住房公积金；
3.多元化培训课程：带薪岗前培训，在职个人提升计划；

工作地址：
浦东新区曹路镇上川路1499号
查看职位地图
**********
锐利贸易集团有限公司
公司规模：
100-499人
公司性质：
合资
公司行业：
快速消费品（食品/饮料/烟酒/日化）
公司主页：
http://www.rlmy.com.cn/
公司地址：
浦东新区曹路镇上川路1499号
**********
单片机工程师
上海实邦电子科技有限公司
五险一金绩效奖金加班补助包住餐补定期体检员工旅游节日福利
**********
福利:
五险一金
绩效奖金
加班补助
包住
餐补
定期体检
员工旅游
节日福利
**********
职位月薪：5000-9000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：2人
职位类别：电子/电器工程师
**********
职位描述:

要求对单片机行业非常感兴趣，愿意将单片机开发作为自己未来的事业之路。

具体要求：

能熟练使用画图软件工具；
有较强的c语言（或汇编语言）功底；
能熟练使用常用的调试工具（万用表、示波器、信号发生器、电源等）；
有较强的学习能力、能吃苦耐劳、较强的自律意识；
至少掌握任意一个系列的一款单片机（如：51系列、pic系列、avr系列、msp430系列、winbond、sonix、freescale、ARM等均可）。

（公司可提供1~3年的住宿，有需求者，请提前告知）
工作地址：
上海市浦东新区金桥金湘路345号1502-1506室
**********
上海实邦电子科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
www.shbelec.com
公司地址：
上海市浦东新区金桥金湘路345号1502-1506室
查看公司地图
**********
销售服务工程师
上海德灿电子有限公司
五险一金年底双薪绩效奖金通讯补贴带薪年假
**********
福利:
五险一金
年底双薪
绩效奖金
通讯补贴
带薪年假
**********
职位月薪：6001-8000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：2人
职位类别：销售工程师
**********
岗位职责
1、负责所辖区域的三防漆、灌封胶和胶黏剂产品销售任务；
2、负责销售区域内销售活动的策划和执行，完成销售指标；
3、开拓新市场,发展新客户,增加产品销售范围；
4、维护及增进已有客户关系；
5、完成部分技术支持工作,与客户进行技术交流；
6、负责收集市场和行业信息,加深了解。

任职资格
1、本科及以上学历，化工或者营销类相关专业；
2、1年以上销售工作经验,有三防漆、油漆、涂料、灌封胶三防漆喷涂设备和灌封胶灌封设备销售经历者优先；  
3、熟悉该行业产品市场，有相应产品销售经验，了解行业市场和技术；
4、具备较强的客户沟通能力和较高的商务处理能力，具有良好的团队协作精神；
5、学习能力强，有挑战精神。
6、有驾照者优先考虑。

工作地址：
上海市徐汇区漕宝路103号1214室
查看职位地图
**********
上海德灿电子有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.decan.com.cn
公司地址：
上海市徐汇区漕宝路103号1214室
**********
财务助理
上海德灿电子有限公司
年底双薪五险一金带薪年假通讯补贴
**********
福利:
年底双薪
五险一金
带薪年假
通讯补贴
**********
职位月薪：5000-6500元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：财务助理
**********
财务助理
1协助公司会计负责编制公司会计凭证，审核、装订及保管各类会计凭证，登记及保管各类帐簿。
2根据公司发货物流记录开具增值税专用发票，记录发票信息，并跟客户定期对账和催款。
3协助管理物流记录和收发货有关事务。
4 管理办公室有关的事务。
5 公司合同、文档管理和资料翻译。
6 及时处理公司领导交办的其他事项。
 任职要求：
1必须有会计上岗证和1年以上实际会计工作经验
2熟悉有关会计法规和财务会计制度。
3国家六级以上英语水平。
4正规大学本科以上学历  （非自考学历）
工作地址：
上海市徐汇区漕宝路103号1214室
查看职位地图
**********
上海德灿电子有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.decan.com.cn
公司地址：
上海市徐汇区漕宝路103号1214室
**********
质检工程师
上海苍穹环保技术有限公司
五险一金绩效奖金加班补助带薪年假节日福利高温补贴
**********
福利:
五险一金
绩效奖金
加班补助
带薪年假
节日福利
高温补贴
**********
职位月薪：4001-6000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：4人
职位类别：质量管理/测试工程师
**********
岗位基本职责：
负责物料及产品的质量检验；对质量异常情况提出质疑、分析原因、提出处理意见、跟踪处理情况，并及时向领导汇报。开展生产过程中的质量监管，做好相关记录。负责客户端的异常处理。协助编制与修订产品质量文件，以及其他质量管理相关的工作。

岗位专业要求：
大专及以上学历，电子、电气、机电一体化、机械、暖通相关专业。特别优秀者要求可适当下降。

岗位能力：
1、工作认真负责，严谨细致，有较强的分析解决问题能力。
2、具有良好的学习能力和动手能力。
3、善于沟通，富有团队合作精神。
4、熟悉运用质量管理工具及方法，熟练使用office办公软件。
5、具有2年左右相关工作经验。
6、年龄在45岁以下。

基本薪资（视实际能力）：
4000-6000/月
工作地址：
上海市江场三路301号3楼（市北高新园区内）
查看职位地图
**********
上海苍穹环保技术有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
环保
公司主页：
http://www.scqair.cn
公司地址：
上海市江场三路301号3楼（近江场西路，市北高新园区内）
**********
商务助理
上海海赋机电设备有限公司
五险一金餐补带薪年假员工旅游
**********
福利:
五险一金
餐补
带薪年假
员工旅游
**********
职位月薪：4001-6000元/月 
工作地点：上海-嘉定区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：商务专员/助理
**********
岗位职责：
1）负责公司日常的商务及销售支持工作；
2）协助财务人员做好公司的日常财务支持工作；
3）公司领导交办的其余日常工作。

任职要求：
1）身体健康，大学专科及以上学历毕业；
2）一年以上相关经验，具有工业领域从业经验者优先；
3）责任心强，善于学习，工作勤奋，富有合作精神；
4）具有良好的表达能力，善于沟通，能熟练使用OFFICE等办公软件。

福利待遇：
1）充满机遇的职业发展前景；
2）有竞争力的收入；
3）规范的福利制度，提供五险一金，带薪年假；
4）周末双休及国家法定假期；
5）有餐补。

工作地址：
嘉定区沪宜公路1101号南翔智地越界产业园
**********
上海海赋机电设备有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
大型设备/机电设备/重工业
公司地址：
嘉定区沪宜公路1101号南翔智地越界产业园
查看公司地图
**********
Java初级开发工程师+无经验亦可
上海茁云科技服务有限公司
五险一金年底双薪绩效奖金全勤奖弹性工作补充医疗保险员工旅游节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
全勤奖
弹性工作
补充医疗保险
员工旅游
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：6人
职位类别：Java开发工程师
**********
现由于集团及合作伙伴（华为、腾讯、百度、阿里巴巴等）的发展需要，面向社会招聘期望在IT业发展的伙伴，让我们给予彼此一个机会！

应聘要求：
1、 18-30岁之间、大专（往届或2018届）；
2、计算机、理工类、机械、机电、电气专业毕业者优先；
3、对IT互联网行业感兴趣，想加入IT行业，了解一定的编程语言（例如JAVA、c#、php等）有良好的沟通能力、学习能力、接受能力及较好的综合素质；
4、无经验或者应届生有同事带

岗位职责:
1、 辅助开发工程师进行系统的功能定义,程序设计；
2、 根据设计文档或需求说明辅助完成代码编写，调试，测试和维护；
3、 配合项目经理完成相关任务目标。

薪酬福利
公司按照市场化原则，提供业内富有竞争力的薪酬，吸纳和保有优秀人才。
1、市场化：在行业内保持富有竞争力的薪酬水平，与公司在各地的市场地位相一致。
2、因岗而异：薪酬体现不同岗位在决策责任、影响范围、资格要求等方面的特性。
3、成果分享：公司获得的每一个进步都和广大职员的努力密切相关，公司发展的同时要让员工分享成功的果实。
4、均衡内外部报酬：关注薪酬等外部报酬的同时，亦不忽略对工作的胜任感、成就感、责任感和个人成长等内部报酬。

员工活动
1、活动经费：公司和各业务部门通过集体活动使大家在娱乐中增强彼此的默契并建立和谐的关系。公司每年会拨付相应的活动经费，另外也会根据各部门业绩考核期内业绩完成情况，给予适当追加员工活动经费。
2、员工俱乐部：公司成立了员工俱乐部，员工俱乐部是公司全体员工开展文娱活动的实际载体，由人力资源部管辖。公司希望不仅工作本身能够给员工带来快乐和成就感，我们更鼓励员工在工作之外追求身心的健康，追求家庭和睦，追求个人生活内容的极大丰富。

工作时间
1、周一至周五，早上9：00-下午17:00，周末双休；
2、针对连续工作满1年的员工提供带薪5天年假；
3、国家法定节假日正常休息；

请勿重复投递！
（基础薄弱者可通过后天的学习弥补，重点是要耐心肯学，对该行业有兴趣）
工作地址：
上海市
查看职位地图
**********
上海茁云科技服务有限公司
公司规模：
10000人以上
公司性质：
上市公司
公司行业：
计算机软件
公司地址：
上海市浦东新区商城路887号波特营创意园A1栋1楼（近世纪大道）
**********
Java初级开发+项目提成
上海茁云科技服务有限公司
五险一金年底双薪绩效奖金全勤奖弹性工作补充医疗保险员工旅游节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
全勤奖
弹性工作
补充医疗保险
员工旅游
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：10人
职位类别：Java开发工程师
**********
岗位描述
1、在Java开发工程师的带领下定期完成量化的工作要求；
2、能独立处理和解决所负责的任务；
3、根据java开发进度和任务分配，完成相应模块软件的开发任务；
4、无经验可提供岗前实训；
招聘要求
1、大专及以上学历；
2、热爱软件开发行业，善于学习和总结分析；
3、做事认真、细心、负责，能够专心学习技术；
4、有良好的工作态度和团队合作精神；
5、年龄18-28岁。 
薪酬福利
公司按照市场化原则，提供业内富有竞争力的薪酬，吸纳和保有优秀人才。
1、市场化：在行业内保持富有竞争力的薪酬水平，与公司在各地的市场地位相一致。
2、因岗而异：薪酬体现不同岗位在决策责任、影响范围、资格要求等方面的特性。
3、成果分享：公司获得的每一个进步都和广大职员的努力密切相关，公司发展的同时要让员工分享成功的果实。
4、均衡内外部报酬：关注薪酬等外部报酬的同时，亦不忽略对工作的胜任感、成就感、责任感和个人成长等内部报酬。

员工活动：
1、活动经费：公司和各业务部门通过集体活动使大家在娱乐中增强彼此的默契并建立和谐的关系。公司每年会拨付相应的活动经费，另外也会根据各部门业绩考核期内业绩完成情况，给予适当追加员工活动经费。
2、员工俱乐部：公司成立了员工俱乐部，员工俱乐部是公司全体员工开展文娱活动的实际载体，由人力资源部管辖。公司希望不仅工作本身能够给员工带来快乐和成就感，我们更鼓励员工在工作之外追求身心的健康，追求家庭和睦，追求个人生活内容的极大丰富。

工作时间：
1、周一至周五，早上9：00-下午17:00，周末双休；
2、针对连续工作满1年的员工提供带薪5天年假；
3、国家法定节假日正常休息；

请勿重复投递！
（基础薄弱者可通过后天的学习弥补，重点是要耐心肯学，对该行业有兴趣）
工作地址：
上海市
查看职位地图
**********
上海茁云科技服务有限公司
公司规模：
10000人以上
公司性质：
上市公司
公司行业：
计算机软件
公司地址：
上海市浦东新区商城路887号波特营创意园A1栋1楼（近世纪大道）
**********
医疗器械销售代表-华南区域
上海辰光医疗科技股份有限公司
**********
福利:
**********
职位月薪：4001-6000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：无经验
最低学历：大专
招聘人数：1人
职位类别：医疗器械推广
**********
1、在区域内医院进行公司产品（磁共振射频线圈、7.0T动物实验系统等）的销售推广工作，完成销售任务；
2、建立渠道销售网络，维护管理经销商并提供产品知识培训；
3、负责区域内客户信息的收集、整理；
4、及时反馈市场需求信息，竞争对手情况和客户反馈意见等市场信息；
5、维护新老客户，负责区域内销售回款；

要求：1、1年以上销售经验，熟悉医院工作模式及医疗器械类产品销售经验优先；
      2、专科以上学历；
      3、较强的语言沟通能力，善于维护客户关系，具有突发事件处理能力；
      4、适应出差，能承受较大的工作压力。
薪资：工资+绩效奖金+提成+年终奖
工作地址：
上海市青浦区华青路1269号
**********
上海辰光医疗科技股份有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
医疗设备/器械
公司主页：
http://www.shanghaicg.net
公司地址：
上海市青浦区华青路1269号
查看公司地图
**********
销售工程师
上海誉光光电科技有限公司
五险一金绩效奖金年终分红交通补助节日福利
**********
福利:
五险一金
绩效奖金
年终分红
交通补助
节日福利
**********
职位月薪：10001-15000元/月 
工作地点：上海-浦东新区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：5人
职位类别：销售工程师
**********
岗位描述：
1、半导体、LED领域设备、材料的销售；
2、通过各渠道及有利方式开发新客户，进行客户关系管理，完成公司制定的销售指标；
3、维护好内部资源，与客户保持良好联系，提高客户满意度；
4、收集和分析市场数据、客户信息，了解客户的问题和需求，并定期反馈最新信息；
5、不断总结知识和技能，提升对行业的认知和研究；
6、能适应出差，按时完成上司交办的其它工作任务。
 岗位要求：
1、有工业品销售经验优先；
2、电子、机械专业背景优先；
3、具备一定的市场分析及判断能力，良好的客户服务意识；
4、可以独立开拓客户，有较强的语言表达和沟通协调能力；
5、性格开朗，责任心强，较强的协调能力及执行力；
6、工作积极、主动，学习能力强，能承受较大的工作压力和强度。
 福利待遇：
1、底薪+业务提成+补贴+年终奖金；
2、完善福利体系：
1）实行五天工作制、享受国定假期；
2）五险一金；
3）公司提供出差补贴、交通补贴、节日福利、年终奖金等等。
     我司现有良好的团队建设和团队氛围，对员工也有很好的激励措施。欢迎您的加入，大家一起努力、一起奋斗！

工作地址：
上海市浦东新区绣川路581号绿地东海岸A座1603室
查看职位地图
**********
上海誉光光电科技有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.yuphoton.com
公司地址：
上海市浦东新区绣川路581号绿地东海岸A座1603室
**********
外贸销售
上海凌加智能科技有限公司
**********
福利:
**********
职位月薪：4001-6000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：2人
职位类别：外贸/贸易专员/助理
**********
工作职责：
       1.熟练操作阿里巴巴平台，能独立回复询盘，熟悉外贸业务各个环节。
        2.充分利用各种网络营销平台及展会开发新客户。
        3.对已有客户进行跟踪维护。
        4熟练掌握销售技巧，具备一定的商务谈判能力。

任职要求：
1.大专及以上学历，国际贸易、商务英语等先关专业毕业。
2.一年以上外贸相关领域工作经验。
3.了解外贸业务流程，熟悉外贸业务及出口各环节。
4.具备良好的英语听说读写能力，CET6级及以上，熟练运用各种办公软件。
5.具备良好的沟通、协调及执行能力，工作踏实认真、应对快捷敏锐，责任心强。


工作地址：
上海市闵行区剑川路951号2号楼409-410
查看职位地图
**********
上海凌加智能科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
www.shlinkplus.com;www.linkplustec.com
公司地址：
上海市闵行区剑川路951号2号楼409-410
**********
外贸专员
上海凌加智能科技有限公司
**********
福利:
**********
职位月薪：4001-6000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：2人
职位类别：外贸/贸易专员/助理
**********
工作职责：
      1.熟练操作阿里巴巴平台，能独立回复询盘，熟悉外贸业务各个环节。
       2.充分利用各种网络营销平台及展会开发新客户。
       3.对已有客户进行跟踪维护。
       4熟练掌握销售技巧，具备一定的商务谈判能力。

任职要求：
1.大专及以上学历，国际贸易、商务英语等先关专业毕业。
2.一年以上外贸相关领域工作经验。
3.了解外贸业务流程，熟悉外贸业务及出口各环节。
4.具备良好的英语听说读写能力，CET6级及以上，熟练运用各种办公软件。
5.具备良好的沟通、协调及执行能力，工作踏实认真、应对快捷敏锐，责任心强。


工作地址：
上海市闵行区剑川路951号2号楼409-410
查看职位地图
**********
上海凌加智能科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
www.shlinkplus.com;www.linkplustec.com
公司地址：
上海市闵行区剑川路951号2号楼409-410
**********
新风控制器销售经理(多元化)
上海凌加智能科技有限公司
五险一金绩效奖金股票期权
**********
福利:
五险一金
绩效奖金
股票期权
**********
职位月薪：10001-15000元/月 
工作地点：上海-闵行区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：3人
职位类别：业务拓展经理/主管
**********
岗位职责：
1、销售公司的新风系统控制器，新风系统，空气净化器，传感器等等智能产品；
2、根据公司销售计划，有效开拓客户资源；
3、通过电话、网络及上门拜访等方式收集潜在客户信息，开拓客户资源；
4、建立、拓展并维护客户关系，完善客户关系管理体系；
5、维护与重要客户间的良好合作，并深入挖掘更多的合作机会。
任职要求：
1、大专（含）以上，有建材行业如：空调、新风、地暖、热水器、太阳能等工作经验者；
2、对销售工作有积极热情，有赚钱欲望，有吃苦耐劳精神；
3、执行能力强，对于工作一丝不苟，有极强的团队协作精神；
4、具备很强的销售能力，并能组建带领销售团队；
5、性格平和，头脑灵活，思路清楚，世事洞明，人情练达。
6、具有团队协作精神，愿意与公司共同成长。
 待遇：
1、底薪+高提成 转正后年薪10-30万；
2、合伙人制度，让你成为自己的老板；
3、青春就要敢打敢拼，只要你有兴趣有信心，我们都欢迎你的加入。

工作地址：
上海市闵行区剑川路951号2号楼409-410
**********
上海凌加智能科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
www.shlinkplus.com;www.linkplustec.com
公司地址：
上海市闵行区剑川路951号2号楼409-410
查看公司地图
**********
嵌入式/单片机软件开发工程师
上海凌加智能科技有限公司
五险一金创业公司股票期权
**********
福利:
五险一金
创业公司
股票期权
**********
职位月薪：6001-8000元/月 
工作地点：上海-闵行区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：软件工程师
**********
岗位职责：
1、电子、计算机、自动化相关专业本科或本科以上，有2年以上嵌入式软件开发经验，能够独立完成所负责的模块开发，在校生可择优录取；
2、熟练掌握主流微处理器，如c8051、stm8、stm32等；
3、熟练掌握C，C++语言，有丰富的编程经验；
4、熟悉各种总线协议和通讯接口，如CAN、I2C、SPI、RS232、USB等；
5、熟悉嵌入式操作系统，如Linux、uC/OS；
7、具有较好的文档撰写能力，代码维护能力；
8、具备良好的创意、灵活的思维，具有勤奋学习、爱岗敬业、团结合作的精神，恪守职业道德。
9、有智能家居行业的开发经验者优先录取；
10、能够独立发现问题、分析问题和解决问题；
11、对数字电路和模拟电路基础知识有一定的掌握，能够看得懂电路并根据电路编写相应的MCU驱动程序。
任职要求：
1、对公司开发的产品进行嵌入式软件的编程和开发；
2、对公司已有的程序进行测试和完善，并进行二次开发；
3、根据领导的要求不断改进和完善产品；
4、同时参与硬件的调试等工作；
5、对工作认真负责，为人忠厚善良，有责任心，喜欢学习新知识；
6、具有良好的团队合作精神，愿意承担责任；
7、专业要求：计算机、自动化、电子以及电信相关专业；
8、愿意在创业公司工作，具有抗压能力，愿意加班，与公司一同成长。
工作地址：
上海市闵行区剑川路951号2号楼
**********
上海凌加智能科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
www.shlinkplus.com;www.linkplustec.com
公司地址：
上海市闵行区剑川路951号2号楼409-410
查看公司地图
**********
单片机软件开发
上海凌加智能科技有限公司
五险一金股票期权
**********
福利:
五险一金
股票期权
**********
职位月薪：8001-10000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：3人
职位类别：嵌入式软件开发
**********
工作职责：
1、 负责嵌入式电子产品的软硬件系统设计与调试；
2、负责公司硬件产品的嵌入式软件开发，主要基于STM32系和STM8列单片机；
3、负责公司硬件产品的开发和调试。
任职资格：
1、 专科及以上学历，计算机、电子类、自动控制、通信等相关专业毕业；
2、 熟悉stm32和stm8单片机的电路和程序设计；
3、 熟练外围接口电路设计；
4、具备焊接调试布板基本技能；
5、熟悉多任务系统者优先。
工作地址：
上海市闵行区剑川路951号2号楼409-410
查看职位地图
**********
上海凌加智能科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
www.shlinkplus.com;www.linkplustec.com
公司地址：
上海市闵行区剑川路951号2号楼409-410
**********
技术工程师（产品开发、质量管理）
上海苍穹环保技术有限公司
带薪年假加班补助绩效奖金五险一金节日福利不加班
**********
福利:
带薪年假
加班补助
绩效奖金
五险一金
节日福利
不加班
**********
职位月薪：4000-8000元/月 
工作地点：上海-静安区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：10人
职位类别：电器研发工程师
**********
岗位基本职责：
参与产品开发、技术文件编制；开展项目技术方案设计和技术风险管控；质量管理；给予销售技术支持。

岗位专业要求：
本科学历，电子、电气、机电一体化、机械、暖通相关专业。特别优秀者要求可适当降低。

岗位能力：
1、具有良好的学习能力和动手能力。
2、工作认真负责，踏实进取。
3、善于沟通，富有团队合作精神。
4、能熟练运用CAD、UG等制图软件。
5、具有3年左右相关工作经验。

其他必须满足的要求：
年龄在45岁以下。
工作地址：
上海市江场三路301号3楼（市北高新园区内）
查看职位地图
**********
上海苍穹环保技术有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
环保
公司主页：
http://www.scqair.cn
公司地址：
上海市江场三路301号3楼（近江场西路，市北高新园区内）
**********
酒店智能化销售总监
上海紫光乐联物联网科技有限公司
五险一金绩效奖金股票期权包住交通补助通讯补贴带薪年假定期体检
**********
福利:
五险一金
绩效奖金
股票期权
包住
交通补助
通讯补贴
带薪年假
定期体检
**********
职位月薪：6000-12000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：不限
招聘人数：1人
职位类别：业务拓展专员/助理
**********
岗位职责：
1.负责智能家居在酒店行业的推广销售；
2.熟悉了解酒店客控系统、深知酒店类工程相关流程及资源协调，与客户顺利沟通相关信息；
3.独立策划实施销售项目；
4.洞察市场与用户，维护与开拓有效的客户关系。
任职资格：
1.本科及以上学历（有相关经验者可放宽至全日制大专），市场营销相关专业，线下营销实践经验及市场团队管理能力；
2.同行业3年以上工作经验，具有酒店管理专业、酒店用品销售、OTA工作经验、酒店用品销售经验优先；
3.极强的工作执行力和计划性，具备良好的沟通表达能力、谈判能力，具有丰富的业界人际资源者优先；
4.接受长短途出差。
工作地址：
青浦区华隆路1777号B栋、河南省郑州市
**********
上海紫光乐联物联网科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.unisiot.com
公司地址：
浦东新区张江集电港科技领袖之都27幢
查看公司地图
**********
硬件工程师
上海云杉信息科技有限公司
五险一金交通补助弹性工作节日福利餐补年底双薪
**********
福利:
五险一金
交通补助
弹性工作
节日福利
餐补
年底双薪
**********
职位月薪：8000-15000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：2人
职位类别：硬件工程师
**********
职位描述:硬件工程师，应用工程师，

岗位职责：
1、根据项目需求完成电路图的设计和BOM制定；
2、制定布线规则，熟悉PCB  LAYOUT，有多层板布板经验，有高频板布板经验
3、能焊接调试自己设计的电路和pcb板，进行相关的设计完善和修改；
4、负责器件选型、评估和验证；
5、产品导入的技术支持，解决产品在生产、测试和应用过程中的相关问题；
6、相关产品文档的编写，包括设计规范，生产工艺文件等；
7、参与硬件成本控制、风险控制和质量控制；
8、有电子产品生产相关经验，能协助指导试生产和小批量生产。


任职要求：
1、嵌入式电子产品相关经验；
2、熟悉各类模拟、数字电路，熟悉常用元器件特性，有完成消费电子相关产品硬件整机设计的经验；
3、有三年以上独立多层板PCB-Layout设计经验，熟悉Altium designer/PADS、CAM350等EDA软件；
4、具有产品导入和生产相关经验者优先考虑；
5、较强的学习能力和合作精神，积极主动优先考虑；

工作地址：
浦东新区向城路58号东方国际科技大厦9楼
查看职位地图
**********
上海云杉信息科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司地址：
浦东新区向城路58号东方国际科技大厦9楼
**********
智能产品销售经理
上海凌加智能科技有限公司
五险一金绩效奖金股票期权
**********
福利:
五险一金
绩效奖金
股票期权
**********
职位月薪：10001-15000元/月 
工作地点：上海-闵行区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：2人
职位类别：销售工程师
**********
岗位职责：
1、销售公司所开发的产品，包括新风系统控制器，新风系统，空气净化器，空气质量检测、传感器等等智能产品；
2、根据公司销售计划，有效开拓客户资源；
3、通过电话、网络等方式收集潜在客户信息对比较有意向的上门拜访，为客户演示其所需要的产品；
4、建立、拓展并维护客户关系，完善客户关系管理体系；
5、开拓更多的销售渠道，如代理商、代工厂、装修公司等。
任职要求：
1、大专（含）以上，有建材行业如：空调、新风、地暖、热水器、太阳能等工作经验者；
2、对销售工作有积极热情，有赚钱欲望，有吃苦耐劳精神；
3、执行能力强，对于工作一丝不苟，有极强的团队协作精神；
4、具备很强的销售能力，并能组建带领销售团队；
5、性格平和，头脑灵活，思路清楚，世事洞明，人情练达。
6、具有团队协作精神，愿意与公司共同成长。
 待遇：
1、底薪+高提成 转正后年薪10-30万；
2、合伙人制度，让你成为自己的老板；
3、青春就要敢打敢拼，只要你有兴趣有信心，我们都欢迎你的加入。

工作地址：
上海市闵行区剑川路951号2号楼409-410
**********
上海凌加智能科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
www.shlinkplus.com;www.linkplustec.com
公司地址：
上海市闵行区剑川路951号2号楼409-410
查看公司地图
**********
上海电子厂普工/操作工/月6千包吃住
上海卓硕电子科技有限公司
无试用期五险一金年底双薪绩效奖金加班补助全勤奖包吃包住
**********
福利:
无试用期
五险一金
年底双薪
绩效奖金
加班补助
全勤奖
包吃
包住
**********
职位月薪：4700-6000元/月 
工作地点：上海
发布日期：最近
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：125人
职位类别：普工/操作工
**********
昌硕科技（上海）有限公司
昌硕科技（上海）有限公司位于上海浦东新区康桥镇康桥工业区、是整个区域内规模最大，实力最强、知名度最高的企业之一！连续8年雄居大陆出口200强榜首；2010年位居《财富》2010年全球企业500强第112名。主要从事苹果手机加工、生产以及维修；能够接受加班多的求职者、请认真阅读招工信息。
=================================
联系人：李永 ：177-0173-3564 （微信同号）
联系人：李永 ：177-0173-3564（微信同号）
【报名方式】：
编辑短信姓名+身份证号发送至：177-0173-3564 （李科长）、信息录入公司系统后，可优先安置宿舍、分配岗位。【全程免费、保留车票报销路费】
=================================
【薪资待遇】
薪资结构:基本工资+生产奖金+久任奖金+加班费综合工资：4700-6000元。
1、基本工资：2450元 平时加班：21.00元/小时
2、生产奖金：300-500 周末加班：28元/小时
3、久任奖金300-500元 法定假日：42.00元/小时
4、中夜班津贴6-9元/天，夜班津贴9元/天
5、年终奖：1500-3000元（工资每月10号打卡形式发放）
=================================
【招聘职位】
(职位)：普工、包装、物料、维修员等多个岗位。
(年龄)：18一45周岁以下，有无工作经验均可；
(学历)：初中以上学历均可，会背默26个英文字母；
(健康)：身心健康、无色盲、无传染性或精神疾病；
(包吃包住)、当天面试，带好行李及身份证原件，分配宿舍.
=================================
【工作时间】
1、工作时间：每两星期休1天、每天8小时，周六日加班。
2、加班时间：平时每日加班3小时，两星期休1天。
3、8小以为都算加班，公司执行白晚班两班制。
【伙食住宿】
【住】;免费住宿6-8人间，独立卫生间、空调、饮水机、宽带；
【食】;免费提供员工套餐，聘请厨师来自新东方八大菜系齐全；
【衣】;坐着上班、不穿无尘服，免费发放夏、冬季各两套工作服；
=================================
A、【报名方式】：
编辑短信姓名+身份证号发送至：177-0173-3564 （李科长）、公司录取信息后，方便求职者优先分配宿舍，优先安置岗位。
B、【入职资料】
①、二代身份证原件 ②体检费50元 ③身份证正反复印件6张 ④1寸照片6张 ⑤生活用品及行李
C、【入职流程】
1、面试;体检;安排宿舍;次日8:30-9:00公司报到;制作厂牌;新人培训;正式上岗
(若下午15:30之后抵达公司可先行安排宿舍)
=================================
【乘车路线】
上海火车站：乘坐地铁1号线到徐家汇-换乘地铁11/16号线到罗山路站（2/3号口出）、马路对面乘坐张南专线到康桥路汇丽集团下车即到（3站）
虹桥火车站：乘坐地铁2号线到龙阳路站-换乘地铁16号线到罗山路站（2/3号口出）、马路对面乘坐张南专线到康桥路汇丽集团下车即到（3站）
上海南站：乘坐南南线（22站）到康桥东路汇丽集团下车即到。
=================================
【注意事项】：注意防范地铁口非法黄牛搭讪、以免造成经济损失，影响入职。到站前提前联系177-0173-3564（李科长）报备入职。


工作地址：
上海浦东新区康桥镇康桥工业园
查看职位地图
**********
上海卓硕电子科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司地址：
上海浦东新区康桥镇康桥工业园
**********
华为业务线java/WEB软件开发工程师
上海茁云科技服务有限公司
五险一金年底双薪绩效奖金全勤奖弹性工作补充医疗保险员工旅游节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
全勤奖
弹性工作
补充医疗保险
员工旅游
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：10人
职位类别：Java开发工程师
**********
公司总部设于香港，运营总部位于北京，目前公司已在中国北京、上海、深圳、大连、西安等国内21个城市以及美国西雅图、普林斯顿、英国伦敦、日本东京等34个城市设有分支机构。公司拥有国际化的资本平台和管理团队，股东包括微软（Microsoft）、Greater Pacific Capital（GPC）、华为、交银国际等。

现由于集团及合作伙伴（华为、腾讯、百度、阿里巴巴等）的发展需要，面向社会招聘期望在IT业发展的伙伴，让我们给予彼此一个机会！

岗位要求：
1、根据手机软件设计规范，进行手机应用程序开发和手机视频播放器开发；
2、进行手机游戏开发；
3、基于MTK、展讯等平台实现手机应用软件模块，客户项目集成和现场技术支持；
4、编写手机应用软件的概要设计和详细设计文档；
5、开展手机应用软件的测试和编写测试报告；
6、协助市场人员推广手机应用软件。
7.应届毕业生可适当放宽条件
任职资格：
1.大专及以上学历，2017届、2018届毕业生，软件工程、计算机等专业优先，有相关基础的其他专业亦可，逻辑思维能力强的理工科专业学生亦可；
2.沟通能力佳，有团队意识；
3.热爱计算机软件开发行业，认可的品牌文化；
4.善于学习和总结分析，有良好的工作态度和团队合作精神；
后期发展方向：
软件、开发、编程、维护、测试 系统架构等，三年内平均年薪十五万到二十五万。
工作时间：
早8:30-17:30 双休 法定假日休息，带薪年假，六险一金（含商业保险）
面试流程及要求：
1、收到面试通知，请带好个人简历及可以证明是你本人的相关证件，前来面试。2、面试流程为：笔试+面试。笔试内容分为逻辑思维题+专业技术题（没有专业基础的学员可以选择面试方向笔试题目，只填写逻辑思维测试部分）

投递简历后，我们将对您的简历进行初步刷选，符合要求的应聘者我们将于3个工作日内电话通知面试时间及地点。

工作地址：
上海市
查看职位地图
**********
上海茁云科技服务有限公司
公司规模：
10000人以上
公司性质：
上市公司
公司行业：
计算机软件
公司地址：
上海市浦东新区商城路887号波特营创意园A1栋1楼（近世纪大道）
**********
测试工程师
上海电驱动股份有限公司
免息房贷股票期权绩效奖金五险一金免费班车定期体检员工旅游高温补贴
**********
福利:
免息房贷
股票期权
绩效奖金
五险一金
免费班车
定期体检
员工旅游
高温补贴
**********
职位月薪：4001-6000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：5人
职位类别：系统测试
**********
1. 负责电机/控制器系统的测试工作；
2. 负责实验数据的处理及编写测试报告；
3. 负责记录测试过程数据及问题总结，并整理归档；
4. 负责电机/控制器系统整车调试、技术支持；
5. 负责实验现场及出差现场问题的查找，并及时解决相关问题；
6. 负责统计考核电机及控制器测试合格率；
7. 保质保量按时完成上级领导安排的工作任务；
8. 按时完成月工作报告；
上级领导交办的其他事宜。

工作地址：
上海市嘉定区恒裕路300号（近百安公路）
查看职位地图
**********
上海电驱动股份有限公司
公司规模：
500-999人
公司性质：
股份制企业
公司行业：
汽车/摩托车
公司主页：
www.chinaedrive.com
公司地址：
上海市嘉定区恒裕路300号（近百安公路）
**********
机械工程师
上海电驱动股份有限公司
五险一金免息房贷定期体检免费班车员工旅游高温补贴节日福利股票期权
**********
福利:
五险一金
免息房贷
定期体检
免费班车
员工旅游
高温补贴
节日福利
股票期权
**********
职位月薪：10001-15000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：机械工程师
**********
1. 保质、保量、按时完成上级领导安排的工作任务，并配合项目主管，做好结构方面工作；
2. 负责产品的模具设计、评审、校对、审核、会签等工作。
3. 负责量产控制器和控制器产品的控制器结构文件的编制（DFMEA、特殊特性清单等）；
4. 负责结构设计文件等相关资料的编制、整理、归档工作；
5. 参与产品施工及生产跟随，解决制作过程中发生的相关结构问题；
6. 按时工作报告；
完成上级领导交办的其他事宜。

工作地址：
上海市嘉定区恒裕路300号（近百安公路）
查看职位地图
**********
上海电驱动股份有限公司
公司规模：
500-999人
公司性质：
股份制企业
公司行业：
汽车/摩托车
公司主页：
www.chinaedrive.com
公司地址：
上海市嘉定区恒裕路300号（近百安公路）
**********
采购工程师
上海电驱动股份有限公司
节日福利高温补贴员工旅游免费班车定期体检带薪年假绩效奖金五险一金
**********
福利:
节日福利
高温补贴
员工旅游
免费班车
定期体检
带薪年假
绩效奖金
五险一金
**********
职位月薪：8001-10000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：采购经理/主管
**********
1. 进行前期评审，提供建设性改善意见。
2. 跟踪新项目采购实施过程中的问题，提出解决措施并执行。
3. 不断总结整理项目采购经验，在采购部内进行交流，为后续项目提供参考性建议。
4. 采购成本管理，使采购成本达成公司目标。
5. 评估物料采购申请数量，确认交期，在合格供应商目录内选择供应商。
6. 按照项目跟单员和采购经理的要求对分配到的物料进度负责；
7. 供应商生产过程问题的沟通解决；
8. 供应商选择推荐，询价议价，跟踪PPAP批准；
9. 设变图纸与供应商沟通，设变评估，及库存的收集统计；
10. 供应商退货补货处理及供应商相关业务的管理；
11. 来料不良、异常单的处理；
12. 采购物料的库存量控制；
主管领导安排的其它工作。

工作地址：
聊城市经济开发区庐山路28号
查看职位地图
**********
上海电驱动股份有限公司
公司规模：
500-999人
公司性质：
股份制企业
公司行业：
汽车/摩托车
公司主页：
www.chinaedrive.com
公司地址：
上海市嘉定区恒裕路300号（近百安公路）
**********
项目质量工程师
上海电驱动股份有限公司
节日福利高温补贴员工旅游免费班车定期体检带薪年假餐补绩效奖金
**********
福利:
节日福利
高温补贴
员工旅游
免费班车
定期体检
带薪年假
餐补
绩效奖金
**********
职位月薪：8001-10000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：质量管理/测试主管
**********
1． 负责新产品开发过程的跟踪；
2． 参与新产品开发的立项、新产品质量目标的制定、产品设计、工艺制定、评审、验证和确认各阶段目标的跟踪和确认；
3． 参与新产品图纸、技术标准及特殊特性清单和试制阶段控制计划的识别；
4． 配合工艺部门对供货总成检具方案的确认和制作过程的跟踪和验收；
5． 负责新产品试制各阶段不良问题（设计、零部件、工艺和工装）的收集并建立新产品开发问题库，发布各阶段不良问题点至相关责任部门，并进行整改跟踪和确认；
6． 负责制定供货总成（电机、控制器）检查基准书，并编制检验规程和指导成品检验员检查；
7． 负责对新产品进行测量系统分析（MSA）和新产品生产能力的评估（计算CPK值）
8． 负责PPAP文件包提交资料的准备工作；
上级安排的其他临时任务。

工作地址：
上海市嘉定区恒裕路300号（近百安公路）
查看职位地图
**********
上海电驱动股份有限公司
公司规模：
500-999人
公司性质：
股份制企业
公司行业：
汽车/摩托车
公司主页：
www.chinaedrive.com
公司地址：
上海市嘉定区恒裕路300号（近百安公路）
**********
测试工程师
上海电驱动股份有限公司
免息房贷股票期权绩效奖金五险一金免费班车定期体检员工旅游高温补贴
**********
福利:
免息房贷
股票期权
绩效奖金
五险一金
免费班车
定期体检
员工旅游
高温补贴
**********
职位月薪：4001-6000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：5人
职位类别：系统测试
**********
1. 负责电机/控制器系统的测试工作；
2. 负责实验数据的处理及编写测试报告；
3. 负责记录测试过程数据及问题总结，并整理归档；
4. 负责电机/控制器系统整车调试、技术支持；
5. 负责实验现场及出差现场问题的查找，并及时解决相关问题；
6. 负责统计考核电机及控制器测试合格率；
7. 保质保量按时完成上级领导安排的工作任务；
8. 按时完成月工作报告；
上级领导交办的其他事宜。

工作地址：
上海市嘉定区恒裕路300号（近百安公路）
查看职位地图
**********
上海电驱动股份有限公司
公司规模：
500-999人
公司性质：
股份制企业
公司行业：
汽车/摩托车
公司主页：
www.chinaedrive.com
公司地址：
上海市嘉定区恒裕路300号（近百安公路）
**********
工艺工程师
上海电驱动股份有限公司
免息房贷五险一金绩效奖金股票期权餐补员工旅游免费班车高温补贴
**********
福利:
免息房贷
五险一金
绩效奖金
股票期权
餐补
员工旅游
免费班车
高温补贴
**********
职位月薪：8000-10000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：工艺/制程工程师
**********
1. 参与产品图纸的量产工艺性、可靠性的审查；
2. 参与产品量产过程设计、验证；
3. 负责产品制程所需二类工装夹具的设计、验证；
4. 负责编制、优化工艺技术文件（包含PFMEA、CP、工艺流程图、SOP、技术规范以及产品制造BOM、配料清单等），并指导实施；
5. 负责解决产品批量生产过程中遇到的工艺路线、工艺方法等方面引起的制程质量、效能等各类问题；
6. 负责编制具体产品的材料定额和工时定额；
7. 负责设计变更后工艺技术输出资料、文件的相应变更管理，并跟踪检查变更后的实际实施过程，预防相应错误的发生；
8. 负责生产现场的施工指导、工艺纪律监督、检查工作，对违反工艺纪律的要及时予以纠正，并跟踪整改；
按要求完成公司或部门临时安排的其它相关工作。

工作地址：
上海市嘉定区恒裕路300号（近百安公路）
查看职位地图
**********
上海电驱动股份有限公司
公司规模：
500-999人
公司性质：
股份制企业
公司行业：
汽车/摩托车
公司主页：
www.chinaedrive.com
公司地址：
上海市嘉定区恒裕路300号（近百安公路）
**********
实习--猎头助理顾问
上海英擎企业管理咨询有限公司
五险一金年底双薪绩效奖金年终分红房补节日福利带薪年假员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
年终分红
房补
节日福利
带薪年假
员工旅游
**********
职位月薪：4000-8000元/月 
工作地点：上海
发布日期：最新
工作性质：实习
工作经验：无经验
最低学历：不限
招聘人数：5人
职位类别：猎头顾问/助理
**********
1. 充分理解客户需求，完成客户岗位职责的分析并制定完善的人才寻访方案；

2. 寻访目标候选人，负责甄选、面试、评估候选人，为候选人提供专业的职业规划帮 助，帮助其找到最优的职业发展路线；

3. 向客户提供专业化、标准化以及系统的人才推荐报告；

4. 协调和推动客户进一步安排候选人的面试并及时反馈面试结果

任职要求：

1. 本科学历，无猎头经验者亦可；

2. 较强的学习能力、优秀的执行力；

3. 能够承受工作压力。
4. 每周至少能来4天

工作地址：
上海市浦东新区张江高科龙东大道666弄
**********
上海英擎企业管理咨询有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
专业服务/咨询(财会/法律/人力资源等)
公司地址：
上海市浦东新区张江高科龙东大道666弄1号楼301
查看公司地图
**********
诚邀外贸业务员公司培训
上海好贝模型科技有限公司
五险一金绩效奖金带薪年假员工旅游节日福利
**********
福利:
五险一金
绩效奖金
带薪年假
员工旅游
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：上海-宝山区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：外贸/贸易专员/助理
**********
岗位职责：
1）收发客户的邮件，维护老客户，开发新客户。
2）根据客户的询盘进行报价，制定PI，跟单，发货，及后期维护。
3）接待外籍客户参观工厂，参加国内及国外的各种展会。
任职要求：
1）大学专科或以上，英语4级及以上，国际贸易或商务英语相关专业优先；
2）一年以上外贸电子商务行业从业经验；
3）良好的客户沟通及谈判技巧，具备一定英语函电、口语能力能够通过电子商务网络平 台独立开发国外客户；
4）具有独立用谷歌、B2B、邮件等网络工具开发客户的能力，使用2年以上者优先；
5）性格外向，内外部沟通能力强，团队意识强；
6）充满活力，富有激情，对工作认真负责；
7）具有强烈的进取心、责任心，熟悉出口业务基本流程。
薪资待遇：基本工资+业绩提成+绩效奖金+团队奖金+年终奖金
每年展会：一次国外德国展会、一次行业北京国际展会，一次行业上海国际展会
工作时间：周一至周五早上9：00至晚上18：00（午休时间：12：00-13：00）
工作地点：上海市宝山区陆翔路111号1号楼712
乘车路线：地铁7号线顾村公园站下，3号口出即可
公司福利待遇：
提供良好的工作环境、有竞争力的薪酬和机遇与挑战并存的激励机制。
1）提供专业的岗前产品知识及业务流程培训
2）员工享有各种福利假期：法定节日、带薪年假、婚假、产假等；
3）为员工缴纳五险一金
4）公司按当年经济状况发放年终奖
5）为鼓励员工有良好的出勤率，设立全勤奖
6）完善的员工职业生涯规划以及专业的培训
7）每年组织员工旅游、员工聚餐等活动
在这里有家庭的温暖，有学校的学习培养，有荣誉与激励，有完善升迁规划。只要你足够的努力，就有足够的回报，我们提供给你绽放的舞台。
工作地址：
上海市宝山区陆翔路111号1号楼712室
**********
上海好贝模型科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
贸易/进出口
公司主页：
www.maytech.cn
公司地址：
上海市宝山区陆翔路111号1号楼712室
查看公司地图
**********
应届电子工程师(职位编号：002)
上海实邦电子科技有限公司
**********
福利:
**********
职位月薪：3000-6000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：2人
职位类别：电子/电器工程师
**********
职位描述:

本职位应届毕业生，要求能来公司实习。

要求对单片机行业非常感兴趣，愿意将单片机开发作为自己未来的事业之路。

具体要求：

能熟练使用绘图软件工具；
有较强的c语言（或汇编语言）功底；
能使用常用的调试工具（万用表、示波器、信号发生器、电源等）；
有较强的学习能力、能吃苦耐劳、较强的自律意识；
至少掌握任意一个系列的一款单片机（如：51系列、pic系列、avr系列、ti32系列、winbond、sonix、freescale、ARM等均可）。

参加过电子设计大赛等活动的优先考虑。
（公司可提供1~3年的住宿，有需求者，请提前告知）
工作地址：
上海市浦东新区金桥金湘路345号1502-1506室
查看职位地图
**********
上海实邦电子科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
www.shbelec.com
公司地址：
上海市浦东新区金桥金湘路345号1502-1506室
**********
猎头顾问
上海英擎企业管理咨询有限公司
每年多次调薪五险一金年底双薪绩效奖金年终分红餐补通讯补贴
**********
福利:
每年多次调薪
五险一金
年底双薪
绩效奖金
年终分红
餐补
通讯补贴
**********
职位月薪：5000-10000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：2人
职位类别：猎头顾问/助理
**********
岗位职责：
1. 和客户沟通职位需求，重复理解客户需求，完成客户岗位职责的分析并制定完善的人才寻访方案；
2. 寻访目标候选人，负责甄选、面试、评估候选人，为候选人提供专业的职业规划帮 助，帮助其找到最优的职业发展路线；
3. 向客户提供专业化、标准化以及系统的人才推荐报告；
4. 协调和推动客户进一步安排候选人的面试并及时反馈面试结果。

任职要求：
1. 本科以上学历，有一定的社会实践或工作经验；年龄30岁以下
2. 较强的学习能力、优秀的执行力；
3. 能够承受工作压力。

综合年薪10W以上
工作地址
上海市浦东新区张江高科龙东大道666弄  靠近张江地铁站。
别墅内办公，中午有阿姨做饭


  
工作地址：
上海市浦东新区张江高科龙东大道666弄
**********
上海英擎企业管理咨询有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
专业服务/咨询(财会/法律/人力资源等)
公司地址：
上海市浦东新区张江高科龙东大道666弄1号楼301
查看公司地图
**********
办公室助理
上海德灿电子有限公司
五险一金年底双薪绩效奖金通讯补贴带薪年假
**********
福利:
五险一金
年底双薪
绩效奖金
通讯补贴
带薪年假
**********
职位月薪：6001-8000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：2人
职位类别：行政专员/助理
**********
岗位职责：
1管理办公室各项事务。
2 跟踪部分客户沟通业务进展情况，及时反馈给公司管理层。
3及时审阅和处理公司对外的合同及其它文件。
4跟踪货物进口和管理物流运作状况。
5起草公司文件和对外沟通的邮件
6安排领导差旅行程和接待客户和合作方
7完成公司领导交办的其它事务
  要求：
1       正规大学本科以上学历，化学、管理、法律、英语、中文专业优先考虑。
2头脑反应敏捷，记忆力好，思路清晰。
3有一定财务技术或者有会计上岗证者优先考虑。
4具有一定的英语水平和口语能力，英语六级。
5具有较强的写作能力和口头表达能力。

工作地址：
上海市徐汇区漕宝路103号1214室
查看职位地图
**********
上海德灿电子有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.decan.com.cn
公司地址：
上海市徐汇区漕宝路103号1214室
**********
销售人员
上海勇电照明有限公司
五险一金绩效奖金交通补助餐补带薪年假员工旅游高温补贴节日福利
**********
福利:
五险一金
绩效奖金
交通补助
餐补
带薪年假
员工旅游
高温补贴
节日福利
**********
职位月薪：4000-8000元/月 
工作地点：上海-静安区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：15人
职位类别：销售代表
**********
1、40周岁以下。
2、有较强的语言表达能力、人际沟通能力、团队合作精神、独立工作能力和协调能力，有独立的思维能力。
3、能承受较大的工作压力，有优秀的客户开发能力和销售技巧，具有开拓精神，富有韧性，以结果为导向。
4、有一年销售经验者优先。
5、能适应长期出差者优先考虑。
6、熟悉和掌握公司经营的产品知识与业务；利用相关渠道和资源，建立与客户的良好关系，实现企业销售目标.

工作地址：
静安区江场西路538号601室
**********
上海勇电照明有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
房地产/建筑/建材/工程
公司地址：
闸北区江场西路538号601室
查看公司地图
**********
线上咨询师（课程顾问/月薪10-20k）
上海游瞿信息科技有限公司
每年多次调薪带薪年假节日福利绩效奖金免费班车员工旅游
**********
福利:
每年多次调薪
带薪年假
节日福利
绩效奖金
免费班车
员工旅游
**********
职位月薪：15001-20000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：5人
职位类别：电话销售
**********
改变，就从现在开始，从你开始！请准备好释放你的力量，加入海同科技！众志成城，我们将拥有改变未来的力量！
如果你：
.热爱教育培训事业；
.喜欢与人沟通，拥有出色的沟通技巧和能力；
.渴望丰厚的奖金收入，专注自己的目标并坚持不懈；
.具有良好的团队合作意识，并具有强烈的责任感与客户服务意识；
.想要有更宽阔的长期职业发展；
那，请加入我们！

我们提供：
1.完善的入职培训和职业晋升机制！
2.透明公开优于同行业的薪资水平！
3.享受国家法定节假日，丰厚的节假日福利！
4.带薪年假！
5.丰厚的年终奖！
6.优秀员工奖等等！
7.杰出员工有参与公司股权激励方案的机会，参与年底分红！
 工作时间：9：00—18：00，做五休二，不加班。
欢迎优秀的应届毕业生投递简历！
岗位职责：
1、根据公司提供的客户信息（由市场部门SEM开发），以面对面的形式接待客户，针对客户的背景、程度及要求进行需求分析，运用专业知识，提供客户课程服务咨询；
2、帮助客户建立合理可行的学习计划；
3、根据客户需求进行产品的销售及推广，维护客户关系；
4、准确收集、统计、整理咨询数据，回访潜在客户； 
5、定期参加业务能力提升培训； 
6、协助市场工作。
任职资格：
1、 年龄22-30岁，大专以上学历；
2、 沟通应变能力强，始终保持专业亲切的顾问形象；
3、 有培训行业经验或顾问式销售经验者优先考虑；
4、 欢迎优秀的应届毕业生投递简历！
 【培训体系】
1、 新人阶段：专业的培训师带教+专业营销技能培训+丰富产品知识培训；
2、 成长阶段：每周专业的营销课程培训+职业素养培训。

【职位晋升】
1、 课程顾问—课程顾问主管—课程顾问经理—销售总监—副中心校长—中心校长；
2、公司招募职位以内部竞选员工优先，存在其他部门发展通道。
 【工作地点】
截止到目前，海同科技在上海有多家学习中心，您的工作地点可根据您的住址选择就近安排。我们的中心分布在浦东新区和徐汇区。
我们真诚的邀请你参加我们的团队，你也可以把这个好机会分享给你的朋友们。


工作地址：
浦东新区张衡路180号2号楼2楼
查看职位地图
**********
上海游瞿信息科技有限公司
公司规模：
100-499人
公司性质：
其它
公司行业：
计算机软件
公司地址：
上海市嘉定区真南路4268号2幢J816室
**********
IT课程顾问（做五休二/张江/底薪5-8k）
上海游瞿信息科技有限公司
每年多次调薪节日福利员工旅游免费班车带薪年假
**********
福利:
每年多次调薪
节日福利
员工旅游
免费班车
带薪年假
**********
职位月薪：10001-15000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：5人
职位类别：培训/招生/课程顾问
**********
改变，就从现在开始，从你开始！请准备好释放你的力量，加入海同科技！众志成城，我们将拥有改变未来的力量！
如果你：
.热爱教育培训事业；
.喜欢与人沟通，拥有出色的沟通技巧和能力；
.渴望丰厚的奖金收入，专注自己的目标并坚持不懈；
.具有良好的团队合作意识，并具有强烈的责任感与客户服务意识；
.想要有更宽阔的长期职业发展；
那，请加入我们！

我们提供：
1.完善的入职培训和职业晋升机制！
2.透明公开优于同行业的薪资水平！
3.享受国家法定节假日，丰厚的节假日福利！
4.带薪年假！
5.丰厚的年终奖！
6.优秀员工奖等等！
7.杰出员工有参与公司股权激励方案的机会，参与年底分红！
工作时间：9：00—18：00，做五休二，不加班。
欢迎优秀的应届毕业生投递简历！
岗位职责：
1、根据公司提供的客户信息（由在线客服、公开课平台开发提供资源），以电话及网络的形式接待客户，针对客户的背景、程度及要求进行需求分析，运用专业知识，提供客户课程服务咨询；
2、帮助客户建立合理可行的学习计划；
3、根据客户需求进行产品的销售及推广，维护客户关系；
4、准确收集、统计、整理咨询数据，回访潜在客户；
5、定期参加业务能力提升培训；
6、协助市场工作。
任职资格：
1、 年龄22-30岁，大专以上学历；
2、 沟通应变能力强，始终保持专业亲切的顾问形象；
3、 有培训行业经验或顾问式销售经验者优先考虑；
4、 欢迎优秀的应届毕业生投递简历！
【培训体系】
1、 新人阶段：专业的培训师带教+专业营销技能培训+丰富产品知识培训；
2、 成长阶段：每周专业的营销课程培训+职业素养培训。

【职位晋升】
1、 课程顾问—课程顾问主管—课程顾问经理—销售总监—副中心校长—中心校长；
2、公司招募职位以内部竞选员工优先，存在其他部门发展通道。
【工作地点】
截止到目前，海同科技在上海有多家学习中心，您的工作地点可根据您的住址选择就近安排。我们的中心分布在浦东新区和徐汇区。
我们真诚的邀请你参加我们的团队，你也可以把这个好机会分享给你的朋友们。


工作地址：
浦东新区张衡路180号2号楼2楼
查看职位地图
**********
上海游瞿信息科技有限公司
公司规模：
100-499人
公司性质：
其它
公司行业：
计算机软件
公司地址：
上海市嘉定区真南路4268号2幢J816室
**********
高校课程顾问（咨询师/月薪10-20k）
上海游瞿信息科技有限公司
每年多次调薪带薪年假节日福利绩效奖金免费班车员工旅游
**********
福利:
每年多次调薪
带薪年假
节日福利
绩效奖金
免费班车
员工旅游
**********
职位月薪：15001-20000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：5人
职位类别：电话销售
**********
改变，就从现在开始，从你开始！请准备好释放你的力量，加入海同科技！众志成城，我们将拥有改变未来的力量！
如果你：
.热爱教育培训事业；
.喜欢与人沟通，拥有出色的沟通技巧和能力；
.渴望丰厚的奖金收入，专注自己的目标并坚持不懈；
.具有良好的团队合作意识，并具有强烈的责任感与客户服务意识；
.想要有更宽阔的长期职业发展；
那，请加入我们！

我们提供：
1.完善的入职培训和职业晋升机制！
2.透明公开优于同行业的薪资水平！
3.享受国家法定节假日，丰厚的节假日福利！
4.带薪年假！
5.丰厚的年终奖！
6.优秀员工奖等等！
7.杰出员工有参与公司股权激励方案的机会，参与年底分红！
工作时间：9：00—18：00，做五休二，不加班。
欢迎优秀的应届毕业生投递简历！
岗位职责：
1、根据公司提供的客户信息（由市场部门SEM开发），以面对面的形式接待客户，针对客户的背景、程度及要求进行需求分析，运用专业知识，提供客户课程服务咨询；
2、帮助客户建立合理可行的学习计划；
3、根据客户需求进行产品的销售及推广，维护客户关系；
4、准确收集、统计、整理咨询数据，回访潜在客户；
5、定期参加业务能力提升培训；
6、协助市场工作。
任职资格：
1、 年龄22-30岁，大专以上学历；
2、 沟通应变能力强，始终保持专业亲切的顾问形象；
3、 有培训行业经验或顾问式销售经验者优先考虑；
4、 欢迎优秀的应届毕业生投递简历！
【培训体系】
1、 新人阶段：专业的培训师带教+专业营销技能培训+丰富产品知识培训；
2、 成长阶段：每周专业的营销课程培训+职业素养培训。

【职位晋升】
1、 课程顾问—课程顾问主管—课程顾问经理—销售总监—副中心校长—中心校长；
2、公司招募职位以内部竞选员工优先，存在其他部门发展通道。
【工作地点】
截止到目前，海同科技在上海有多家学习中心，您的工作地点可根据您的住址选择就近安排。我们的中心分布在浦东新区和徐汇区。
我们真诚的邀请你参加我们的团队，你也可以把这个好机会分享给你的朋友们。


工作地址：
浦东新区张衡路180号2号楼2楼
查看职位地图
**********
上海游瞿信息科技有限公司
公司规模：
100-499人
公司性质：
其它
公司行业：
计算机软件
公司地址：
上海市嘉定区真南路4268号2幢J816室
**********
销售经理（销售渠道管理与支持）
上海苍穹环保技术有限公司
绩效奖金带薪年假五险一金节日福利不加班
**********
福利:
绩效奖金
带薪年假
五险一金
节日福利
不加班
**********
职位月薪：3000-5000元/月 
工作地点：上海-静安区
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：8人
职位类别：销售代表
**********
岗位基本职责：
开拓市场，维护客户关系，开发代理商，开展销售渠道管理和销售支持，参与品牌建设，完成领导交办的工作。

岗位专业要求：
大专以上学历，专业不限。具有3年以上销售相关工作经验。特别优秀者要求可适当下降。

岗位能力要求：
1、逻辑思维清晰，语言表达能力强。
2、执行力强，富有进取心。
3、善于沟通协调，具有团队合作精神。
4、擅长线上、线下产品营销推广及客户关系维护。
5、熟练使用办公软件，具有较强的ppt制作和演讲能力。
6、有渠道资源者优先考虑。

岗位其他要求（必须满足）：
身体健康，年龄在45岁以下，已定居上海。

薪资：
底薪+提成，多劳多得。

工作地址：
江场三路301号3楼（市北高新园区内）
查看职位地图
**********
上海苍穹环保技术有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
环保
公司主页：
http://www.scqair.cn
公司地址：
上海市江场三路301号3楼（近江场西路，市北高新园区内）
**********
外贸业务员
上海凌加智能科技有限公司
**********
福利:
**********
职位月薪：4001-6000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：2人
职位类别：外贸/贸易专员/助理
**********
岗位职责：
1、负责国际市场对外联络业务，向国外客商推广公司，开发市场，及时处理客人的询盘及各种需求。为客户提供主动、热情、满意、周到的服务。
2、负责外贸定单在企业内部计划、生产、包装、运输等过程的跟踪;
3、按外贸要求传递相关的客户要求,制作和办理各种结汇所需单据;
4、负责国际来宾的接待和公司内部翻译工作;
5、负责公司各网站平台的日常维护和信息更新;能熟练操作B2B平台，搭建B2B推广平台，同时通过其他网络营销方式进行业务推广，增加产品曝光机率，获取询盘;开发客户获取订单。
6、通过电话及邮件与客户沟通订单数量、价格、货期、货款等问题。整理各种表格数据并录入系统，交给工厂安排生产。
7、负责信息搜集、整理，包括市场信息、客户信息、合作伙伴信息等;
任职要求：
1、基本要求：热爱外贸事业，敢于挑战自我，挑战高薪，能吃苦耐劳，勤奋务实，积极主动，具有良好的团队合作精神，拥有高度的执行力，能承受较强的工作压力，稳定性强。立志长期从事外贸行业。
2、学历专业要求：本科及以上学历，国际贸易、市场营销及相关专业，其他专业英语优秀也可，男女不限；
3、专业素质要求： 优秀的英文听说读写能力，能够快速熟练地书写商务英文信函，口语良好； 精通外贸流程，能够掌握从寻找客户到最后交单退税的一个整体流程。 熟知对外贸易规章、政策；报关、货运、保险、检验等手续；各国关税制度以及非关税方面的规定；国际汇兑、支付方面的知识。 熟悉国际贸易法律、法规、公约与惯例等。
 四、经验要求：具有一年以上外贸或者跟单经验


工作地址：
上海市闵行区剑川路951号2号楼409-410
查看职位地图
**********
上海凌加智能科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
www.shlinkplus.com;www.linkplustec.com
公司地址：
上海市闵行区剑川路951号2号楼409-410
**********
销售助理内勤
深圳市宇宙光电子有限公司
五险一金定期体检员工旅游不加班
**********
福利:
五险一金
定期体检
员工旅游
不加班
**********
职位月薪：2001-4000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：销售行政专员/助理
**********
岗位职责：
1、整理订单及客户往来工作邮件、报告等资料的整理、归档；
2、各类报表的编制及文件资料的整理；
3、销售助理类，配合销售部门的相关工作。
4、完成上级安排的其他工作。

任职要求：
1、大专及以上学历，工作经验不限，可接受应届毕业生；
2、能熟练使用办公软件；
3、做事认真、仔细、负责。
4、上班地点：上海市长宁区水城南路37号

工作地址：
长宁区水城南路37号万科北楼601室
查看职位地图
**********
深圳市宇宙光电子有限公司
公司规模：
20-99人
公司性质：
港澳台公司
公司行业：
电子技术/半导体/集成电路
公司地址：
深圳市福田区滨河大道5003号爱地大厦东座6楼602
**********
销售代表
上海海赋机电设备有限公司
五险一金餐补通讯补贴带薪年假员工旅游定期体检绩效奖金节日福利
**********
福利:
五险一金
餐补
通讯补贴
带薪年假
员工旅游
定期体检
绩效奖金
节日福利
**********
职位月薪：6000-12000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：2人
职位类别：销售代表
**********
要求： 
1）身体健康，大学专科及以上学历毕业； 
2）一年以上相关经验，具有机电产品销售经验者优先； 
3）有上进心，责任心强，善于学习，工作勤奋，具有良好的团队合作精神； 
4）具有良好的表达能力，善于沟通，能熟练使用OFFICE等办公软件； 

岗位描述： 
1）根据公司的销售目标协助完成预订销售任务； 
2）能广泛回访终端客户，建立并维护长期良好的客户关系； 
3）能识别客户需求，推荐解决方案和积极创造销售机会；
工作地址
嘉定区沪宜公路1101号南翔智地越界产业园

工作地址：
嘉定区沪宜公路1101号南翔智地越界产业园
查看职位地图
**********
上海海赋机电设备有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
大型设备/机电设备/重工业
公司地址：
嘉定区沪宜公路1101号南翔智地越界产业园
**********
业务拓展专员
上海誉光光电科技有限公司
五险一金绩效奖金年终分红交通补助节日福利
**********
福利:
五险一金
绩效奖金
年终分红
交通补助
节日福利
**********
职位月薪：3000-6000元/月 
工作地点：上海-浦东新区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：5人
职位类别：业务拓展专员/助理
**********
岗位描述：
1、半导体、LED领域设备、材料的销售；
2、开发新客户，拓展与老客户的业务，建立和维护更新新老客户档案；
3、维护好内部资源，与客户保持良好联系，提高客户满意度；
4、收集和分析市场数据，并定期反馈最新信息；
5、准备销售合同、报价单等文件；
 岗位要求：
1、有工业品销售经验优先
2、电子、机械专业背景优先
3、良好的客户服务意识，能承受较大的工作压力和强度；
4、可以独立开拓客户，有较强的语言表达和沟通协调能力；
5、性格开朗，责任心强，较强的协调能力及执行力；
6、工作积极、热心主动、头脑思维活跃、学习能力强。
 福利待遇：
1、底薪+业务提成+补贴+年终奖金；
2、完善福利体系：
1）实行五天工作制、享受国定假期；
2）五险一金；
3）公司提供出差补贴、交通补贴、节日福利、年终奖金等等。
     我司现有良好的团队建设和团队氛围，对员工也有很好的激励措施。欢迎您的加入，大家一起努力、一起奋斗！


工作地址：
上海市浦东新区绣川路581号绿地东海岸A座1603室
查看职位地图
**********
上海誉光光电科技有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.yuphoton.com
公司地址：
上海市浦东新区绣川路581号绿地东海岸A座1603室
**********
Business Assistant/商务助理
蔚视科贸易(上海)有限公司
年底双薪五险一金绩效奖金加班补助带薪年假定期体检
**********
福利:
年底双薪
五险一金
绩效奖金
加班补助
带薪年假
定期体检
**********
职位月薪：6001-8000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：商务专员/助理
**********
工作职责：
处理公司内部订单所有流程
根据客户或公司要求在ERP系统中创建所有内部及外部的所需的订单相关文件
独立地追踪及完成订单相关步骤并做好相应记录
以英文或中文与各利益相关者保持良好的沟通，并以专业友好的态度的向客户或公司内部员工及管理者提供订单详情信息
根据管理部要求处理其他行政事务

任职要求：
良好的英语沟通能力
熟练办公软件（Word, Excel）
两年及以上工作经验
大专及以上学历
良好的服务态度及商务沟通技巧
细心谨慎且有条理的工作习惯
曾在国际贸易,技术生产类公司任职过订单处理,销售助理,客户服务等工作的优先考虑
熟悉ERP操作系统的优先考虑
对于各国文化有着良好的接受能力及求知欲

  工作地址：
长宁区凯旋路1010号D栋2楼
**********
蔚视科贸易(上海)有限公司
公司规模：
20-99人
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.viscom.com
公司地址：
长宁区凯旋路1010号D栋2楼
查看公司地图
**********
EMC测试工程师（测试中心）
儒竞艾默生环境优化技术(上海)有限公司
五险一金年底双薪包住交通补助餐补通讯补贴带薪年假节日福利
**********
福利:
五险一金
年底双薪
包住
交通补助
餐补
通讯补贴
带薪年假
节日福利
**********
职位月薪：8001-10000元/月 
工作地点：上海-宝山区
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：1人
职位类别：测试/可靠性工程师
**********
工作职责：
1、变频器、汽车电子产品的EMS、EMI测试工作；
2、编制测试用例、编写测试报告、审核测试报告；
3、EMS、EMI实验室的日常管理；
4、第三方EMC委外测试工作。

技能&经验要求：
技能要求：
1、具备基础的电力电子产品硬件知识，能够看懂硬件原理图及电路图；
2、熟悉主流的EMC测试设备的操作和维护，具备简单的故障排查能力；
3、熟悉EN55014、CISPER16、CISPER25、IEC61000-4等EMC测试标准；
4、熟悉研发测试流程和ISO17025实验室质量管理体系；
5、良好的英文听说读写能力。

经验要求：
1、电力电子、电气、自动化等相关工科专业；
2、3~5年汽车电子或变频器类产品EMC测试经验；
3、熟悉EMS、EMI设备的使用、维护；
4、熟悉TS16949、ISO17025体系；
5、具有汽车电子或变频器产品研发实验室工作经验者优先考虑。

工作地址：
上海市宝山区金勺路1515号宝临电气工业园区A1南楼
查看职位地图
**********
儒竞艾默生环境优化技术(上海)有限公司
公司规模：
100-499人
公司性质：
合资
公司行业：
电子技术/半导体/集成电路
公司主页：
www.ruking-emerson.com
公司地址：
上海市杨浦区国权北路1688号湾谷科技园B5栋12楼
**********
销售工程师
上海谱幂精密仪器科技有限公司
创业公司五险一金年底双薪绩效奖金带薪年假员工旅游
**********
福利:
创业公司
五险一金
年底双薪
绩效奖金
带薪年假
员工旅游
**********
职位月薪：8001-10000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：1人
职位类别：销售工程师
**********
岗位职责： 
1、负责公司江浙沪区域高校研究院所客户的维护和开发；
2、积极完成所在区域的销售额指标，扩大公司产品区域占有率；
3、与客户保持良好沟通，实时把握客户需求；
4、学习和了解公司新产品，并配合市场部完成新品推广；对客户进行初步的产品调试的初步指导。
5、收集客户反馈信息和用户意见，配合技术部做好技术支持和服务。
6、了解和学习科研用到的前沿材料，及时并反馈给市场部。
任职要求：
 1、本科及以上学历，理工科背景佳；
 2、思路清晰，逻辑性强，对数字敏感，具备一定的数据分析、总结归纳能力，精通excel等办公软件； 3、诚实认真、勤奋踏实、性格开朗，沟通、理解能力强，工作积极主动，具有良好的团队合作意识及敬业精神。
4、在校期间，有销售实践或社团活动经验者优先。
工作地址：
上海市杨浦区国霞路258号绿地双创中心903（三门路地铁站）
查看职位地图
**********
上海谱幂精密仪器科技有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
学术/科研
公司地址：
上海市杨浦区国霞路258号复旦绿地双创中心903
**********
招普工仓管长白班6K起
上海顶特电子科技有限公司
五险一金年底双薪包吃包住节日福利绩效奖金全勤奖
**********
福利:
五险一金
年底双薪
包吃
包住
节日福利
绩效奖金
全勤奖
**********
职位月薪：4001-6000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：36人
职位类别：普工/操作工
**********
上海良信电器招聘简章
招聘职位：质检，机修工，普工，仓管，技术员，文员。
一.薪资待遇：
基本工资（底薪）2850
生产奖金 100-500 ，全勤奖300
年终奖金 ：每年春节前按当年度工作绩效及整体贡献发放年终奖金 1000-8000不等。
工资发放：每10号准时发放
综合工资的高低取决于加班时数和在职奖金，一般综合工资在4500-7000元左右。
二．福利待遇
1.保险：公司依法为公司员工缴纳上海市城鎮職工社會保险；
2.休假：员工依法享受国家法定节假日、婚假、丧假、产假、带薪年休假等；
3.贴心的福利：生日礼券、结婚礼金、生育津贴等；
4.年度各项公司大型活动及丰富多样的社团活动：晚会、运动会、球类比赛、艺文表演；
5.各项便利设施：室内篮(羽)球场、网吧、图书馆、韵律教室、便利商店、邮局、各式美食餐厅等。
三．伙食住宿
1.包吃（每月提供360的伙食补助），一天3餐，提供住宿，生活区内设有大型员工餐厅，可满足多样化的用餐需求；
2.員工宿舍每房每月水电费分摊，从员工每月薪资中扣除，所有宿舍均提供独立的冷暖空调，二十四小时供应洗浴热水及饮用水。
四．招聘条件（重点）
1、18-36周岁以上，学历不限；
2、持有效二代身份证件，身份证不在有效期内不能进厂。
六. 工作时间
1、正常工作时间：每天8小时，做六休一
2、加班时间：平时每日加班3个小时，每周至少休息1天；
五.公司简介：
上海良信电器股份有限公司创建于1999年，是由一批多年从事技术开发、技术管理的电器专业人员联合组建的民营股份制企业。公司坐落于上海浦东新区，年发展速度快，被誉为行业内值得关注的黑马。我们欢迎你的加入！
招聘处贺主管13162897587微信同步

工作地址：
上海市浦东新区申江南路
查看职位地图
**********
上海顶特电子科技有限公司
公司规模：
500-999人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司地址：
上海市浦东新区康桥工业园区
**********
销售工程师
北京三宝兴业视觉技术有限公司
五险一金年底双薪绩效奖金带薪年假补充医疗保险定期体检员工旅游节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
带薪年假
补充医疗保险
定期体检
员工旅游
节日福利
**********
职位月薪：10001-15000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：不限
招聘人数：2人
职位类别：销售工程师
**********
岗位要求：
1、从事工业自动化销售2-3年工作经验；
2、有视觉行业工作经验者优先；
3、良好的英语水平，大学英语四级以上；
4、本科以上学历，计算机、电子信息工程，机电一体化等相关专业；
5、熟悉科学成像知识, 光谱激光方面的知识；
6、熟悉机器视觉行业或图像处理方面；
7、良好的沟通能力及协作精神；
8、具备独立开拓新客户，推广新产品的意识；
9、具有团队合作精神，沟通能力强，有责任感，工作积极，能承受压力。

  工作地址：
上海市浦东新区张衡路500弄1号楼706室
**********
北京三宝兴业视觉技术有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.mvlz.com/
公司地址：
北京市海淀区永泰庄北路1号院东升国际创业园5号楼2层
**********
普工
上海苍穹环保技术有限公司
五险一金带薪年假加班补助节日福利高温补贴住房补贴绩效奖金定期体检
**********
福利:
五险一金
带薪年假
加班补助
节日福利
高温补贴
住房补贴
绩效奖金
定期体检
**********
职位月薪：3100-4200元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：不限
招聘人数：10人
职位类别：普工/操作工
**********
上班时间：
周一至周五，上午8:00-12:00，下午13:00-17:00。

任职资格：
1、年龄在20-45岁，身体健康。
2、工作认真负责，具有团队合作精神。
3、具有较强的动手能力和学习能力。
4、具有工地电工或空调安装的工作经验者优先考虑。
5、持有在有效期内的电工上岗证者优先考虑。
工作地址：
江场三路301号3楼（近江场西路，市北高新园区内）
查看职位地图
**********
上海苍穹环保技术有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
环保
公司主页：
http://www.scqair.cn
公司地址：
上海市江场三路301号3楼（近江场西路，市北高新园区内）
**********
市场专员
上海谱幂精密仪器科技有限公司
创业公司五险一金年底双薪绩效奖金带薪年假加班补助员工旅游
**********
福利:
创业公司
五险一金
年底双薪
绩效奖金
带薪年假
加班补助
员工旅游
**********
职位月薪：6001-8000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：1人
职位类别：市场专员/助理
**********
职位描述：
岗位职责：
1、负责准备公司的宣传资料;
2、熟知产品，并能对产品进行分类，培训销售及代理商 ；
3、协助销售进行市场活动和展会的举办 ;
4、维护公司的网站数据，以及微信平台的管理更新 ;
任职要求：
1、本科及以上学历，理工科背景, 物理及相关背景尤佳；
2、思路清晰，逻辑性强，对数字敏感，具备一定的数据分析、总结归纳能力。
3、具有创新精神。
4、具备一定的审美能力及领导能力。公司将给予员工每年两周的带薪假期。
工作时间：8小时弹性工作制 
工作地址：
上海市杨浦区国霞路258号绿地双创中心903（三门路地铁站）
查看职位地图
**********
上海谱幂精密仪器科技有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
学术/科研
公司地址：
上海市杨浦区国霞路258号复旦绿地双创中心903
**********
销售工程师(底薪8000~10000）
港德电子有限公司
五险一金年底双薪绩效奖金股票期权员工旅游节日福利带薪年假定期体检
**********
福利:
五险一金
年底双薪
绩效奖金
股票期权
员工旅游
节日福利
带薪年假
定期体检
**********
职位月薪：8000-10000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：2人
职位类别：销售工程师
**********
岗位职责：
1、负责公司所代理的知名品牌电子元器件产品的销售（被动电子元器件、二三级管、半导体IC、液晶屏等）。
2、开拓新市场,发展新客户,开拓产品销售范围、提升客户端的订单份额。
3、维护及增进已有客户关系，与客户的研发、采购、资源等部门人员进行产品、技术交流。
4、及时收集市场和行业的信息，掌握客户需求的变动，协助PM做好预测和备货，确保货款的及时回收。

任职要求：
1、口齿伶俐，积极主动，诚实，勤快，有进取心。
2、有2年以上同行业电子元器件、半导体器件代理商、分销商销售工作经验。
3、大专及以上学历，电子类或市场营销类专业。
4、富有开拓精神和良好的团队合作意识,具有高度的工作责任感,良好的心里承受力，良好学习领悟能力和语言表达沟通能力，以促成和客户建立融洽合作关系。
5、熟悉操作办公软件(MS Office)。

工作地址：
浦东新区东方路800号2403A室
查看职位地图
**********
港德电子有限公司
公司规模：
20-99人
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司地址：
上海市浦东新区东方路800号宝安大厦2403A室
**********
网络推广专员
上海宝宫电子科技有限公司
年底双薪五险一金带薪年假
**********
福利:
年底双薪
五险一金
带薪年假
**********
职位月薪：5000-7000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：外贸/贸易专员/助理
**********
岗位职责：
负责阿里巴巴国际站的运营、公司官网、所有网络平台的市场推广。
1.   熟悉阿里巴巴后台运作，以及各种阿里巴巴工具和平台规则；
2.   产品/关键字：负责阿里巴巴产品发布、维护、关键词策略，挖掘产品亮点与卖点，搜集行业关键字，通过专业的优化信息、处理产品图片提升产品及店铺效果，提高产品曝光率，提升产品点击率及店铺整体流量和转化率；
3.   定价：通过外贸直通车对产品进行合理定价，提升曝光率，吸引潜在目标客户；监控数据后台，掌握最新定价动态，确保产品排名靠前；
4.   RFQ：及时（24小时之内）回复客户询盘，以及针对公司产品情况针对性的进行RFQs报价；
5.   数据分析：分析产品曝光点击率，从而优化产品定价，以获得最精准的曝光；监测阿里巴巴后台运营数据，并定期提交运营分析报告，提出合理化建议；
6.   市场信息：搜集网络上各同行及竞争产品的动态信息，分析把握市场和用户需求；
7.   团队合作：与团队其它部门协同作战，协调工作安排，达到客户服务高满意度；
8.   拓宽销售宣传渠道，如：facebook, twitter, linkedin, youtube（视频）等等社交平台；
9.   品牌推广：负责公司官网、微信平台、所有网络推广平台的维护和更新，产品说明书的英文化工作和上传、关键词开发、优化排名，开发潜在客户，持续提升品牌建设；
10.  完成上级交给的其它工作任务。
任职资格：
1.   大专学历及以上，国际贸易、英语或相关专业；
2.   熟练电脑，英语四级以上，英语听说读写熟练；
3.   有阿里巴巴国际站运营管理经验，一年或以上国际平台工作经验；
4.   具备一定的方案写作能力和数据分析能力，能独立进行运营文案的撰写；
5.   有一定的美术、摄影功底，会应用Photoshop等软件；
6.   有志于网络推广、外贸行业，有极大兴趣和热情，愿意在这个领域长期发展；
7.   做人诚实守信，做事脚踏实地，谦虚好学，良好的团队合作精神和高度责任感！
只要你有梦想和坚持，这个平台将为你而设！

工作地址：
普陀区胶州路941号长久大厦1904
查看职位地图
**********
上海宝宫电子科技有限公司
公司规模：
20-99人
公司性质：
合资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.boarden.com.cn
公司地址：
普陀区胶州路941号长久大厦1904
**********
采购助理
上海谱幂精密仪器科技有限公司
创业公司五险一金年底双薪加班补助员工旅游带薪年假
**********
福利:
创业公司
五险一金
年底双薪
加班补助
员工旅游
带薪年假
**********
职位月薪：4001-6000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：1人
职位类别：采购专员/助理
**********
岗位职责：
1、负责公司供应商的维护。
2、积极配合其它部门的工作
3、采购跟单；
4、学习和了解公司新产品；
5、了解和学习科研用到的前沿材料
任职要求：
1、本科及以上学历，理工科背景佳；
2、思路清晰，逻辑性强，对数字敏感，具备一定的数据分析、总结归纳能力，精通excel等办公软件；
3、诚实认真、勤奋踏实、性格开朗，沟通、理解能力强，工作积极主动，具有良好的团队合作意识及敬业精神。
  工作地址：
上海市杨浦区国霞路258号绿地双创中心903（三门路地铁站）
查看职位地图
**********
上海谱幂精密仪器科技有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
学术/科研
公司地址：
上海市杨浦区国霞路258号复旦绿地双创中心903
**********
胶印机机长
上海精麟电子科技有限公司
绩效奖金包吃通讯补贴员工旅游节日福利
**********
福利:
绩效奖金
包吃
通讯补贴
员工旅游
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：上海-浦东新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：印刷操作
**********
岗位职责：
 有UV印刷经验操作4色以上机器者优先
任职要求：
有UV印刷经验操作4色以上机器者优先
工作地址：
浦东新区航头镇沪南路5583号
查看职位地图
**********
上海精麟电子科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
null
公司地址：
浦东新区航头镇沪南路5583号
**********
销售工程师/经理
上海宝宫电子科技有限公司
五险一金年底双薪带薪年假
**********
福利:
五险一金
年底双薪
带薪年假
**********
职位月薪：5000-10000元/月 
工作地点：上海-普陀区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：3人
职位类别：销售工程师
**********
职位描述：
1、电子相关专业，大专以上学历；
2、1年以上电子行业相关销售经验和同行工作过的优先考虑；
3、在安防、通讯、汽车电子、工业控制、电源、LED灯以及消费类电子等行业工作过的优先考虑;
4、为人正直诚信，积极热情，吃苦耐劳、具备很强的职业操守及敬业精神。

员工福利：
基本工资：底薪+补贴
薪酬体系：提供就有竞争力的提成+奖金+13薪
绩效奖金：充分体现多劳多得和团队合作精神，员工既要依靠团体，又能发挥自己的潜力。
保险保障：按照国家规定缴纳
工作时间：双休和国家规定假期，业务人员弹性工作制。
培训发展：公司秉承与员工共同发展的理念，关注个人的职业生涯与公司的长期发展结合的原则，提供完善的培训计划。

企业优势：技术型公司、创新型公司、一站式服务
企业宗旨：使电子电路运行更安全、更可靠
企业远景：成为全球电路保护行业领导品牌
企业口号：电路保护问题，宝宫帮您解决

发展平台：公司在行业有深厚的品牌基础，同时又处于高速发展的阶段，每位新人都有学习和成长的机会，公司提供优秀的发展平台。

企业文化：外企文化和中国文化相辅相成，既提供人性化的管理，又充分发挥个人的主观能动性，人际关系温馨和睦，平等简单，又充满激情。
工作地址：
上海普陀区胶州路941号长久大厦1904
查看职位地图
**********
上海宝宫电子科技有限公司
公司规模：
20-99人
公司性质：
合资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.boarden.com.cn
公司地址：
普陀区胶州路941号长久大厦1904
**********
测试工程师
上海兆富电子科技有限公司
五险一金年底双薪餐补带薪年假员工旅游高温补贴
**********
福利:
五险一金
年底双薪
餐补
带薪年假
员工旅游
高温补贴
**********
职位月薪：3000-5000元/月 
工作地点：上海-嘉定区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：2人
职位类别：测试/可靠性工程师
**********
岗位职责：
1、对公司产品按照企业标准等进行相关测试和产品质量把关。
2、对故障产品进行故障分析与修复。
3、 根据项目需要编写可测性需求、测试计划、测试方案、测试设计。
4、 对产品测试结果进行分析和总结，对产品功能的合理性提出建议或实施方案。
5、完善产品的测试方法。
6、 及时完成交办的其他事项。
任职要求：
1）电子信息、自动化控制专业等硬件相关专业本科以上学历；
2）掌握基本的测试理论和测试技能；
3）能熟练使用示波器、频谱仪、射频信号源等各种专业仪器；
4）做事有耐心、细心和责任心，有良好的沟通协调能力，有较强的学习能力，有上进心。
工作地址：
上海市嘉定区蕰北公路1755弄1号楼
查看职位地图
**********
上海兆富电子科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司地址：
上海市嘉定区南翔镇藴北公路1755弄1号
**********
平面设计
上海真智电子标签技术有限公司
五险一金餐补交通补助通讯补贴带薪年假节日福利员工旅游定期体检
**********
福利:
五险一金
餐补
交通补助
通讯补贴
带薪年假
节日福利
员工旅游
定期体检
**********
职位月薪：4001-6000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：平面设计
**********
岗位职责：
1.负责公司互联网广告品牌传播等创意的平面设计（包括海报、产品手册、网站页面、平面媒体以及其他宣传物料的设计）；
2.负责公司对外日常企业宣传及平面广告、产品DM、活动宣传册的平面设计；
3.负责公司市场推广活动等的企划方案图文创意设计；
任职要求：
1、美术、设计类专业相关背景，大专及以上学历；
2、精通制图软件：photoshop、AI、CoreDraw、flash、Illustrator等专业绘图软件；
3、有成熟、成功的产品案例；
4、有较强的图标界面设计功底和设计创意；
5、熟悉手机客户端的设计流程，具有很好的平面设计能力；
6、工作积极主动，善于沟通，有较强的团队合作精神；
7、富有丰富的想象力，造型能力，良好的色彩感悟力。

工作地址：
上海市宜山路1768号205室
查看职位地图
**********
上海真智电子标签技术有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
贸易/进出口
公司主页：
http://www.rsmart.com.cn/default.asp
公司地址：
上海市宜山路1768号205室
**********
销售助理
雷莫电子(上海)有限公司
年底双薪交通补助不加班员工旅游免费班车包吃带薪年假五险一金
**********
福利:
年底双薪
交通补助
不加班
员工旅游
免费班车
包吃
带薪年假
五险一金
**********
职位月薪：6001-8000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：3人
职位类别：销售行政专员/助理
**********
雷莫（LEMO）连接器 
销售助理
工作地点：上海
工作职责
-- 完成销售工程师要求的产品报价单、制作定单；
-- 跟进销售订单的备货与发货，核对发票/应收款等售后工作；
-- 负责各类销售指标的月度、季度、年度统计报表并按时提交销售总监。
-- 接听记录客户的咨询电话；负责公司文档处理；
要求
-- 大学以上学历；欢迎应届毕业生应聘；
-- 较强的独立工作能力、领悟能力、沟通协调能力及语言表达能力；
-- 具备一定的英文听、说、读、写能力；
-- 有耐心，责任心强、有良好的团队合作精神和敬业精神、具备良好的职业道德；

雷莫公司将与中国一起长期发展并迅速成长，我们诚邀您加入雷莫中国公司。欲了解公司详情请登陆我们的网站：www.lemo-china.com ,

工作地址：
上海市浦东新区金滇路18号E幢第一层
查看职位地图
**********
雷莫电子(上海)有限公司
公司规模：
100-499人
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司地址：
上海市浦东新区金滇路18号E幢第一层
**********
外贸销售经理
上海真智电子标签技术有限公司
五险一金绩效奖金带薪年假定期体检员工旅游节日福利不加班餐补
**********
福利:
五险一金
绩效奖金
带薪年假
定期体检
员工旅游
节日福利
不加班
餐补
**********
职位月薪：10001-15000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：2人
职位类别：销售经理
**********
职位描述：
²         负责公司国外智能卡及RFID市场的业务拓展、销售执行及客户服务
²         协助市场部，利用电子商务等手段，积极开展外贸的市场推广工作
²         管理、培养、帮忙、服务新老客户,与客户同发展、共成长
²         制定营销计划、寻找潜在客户、开发客户资源、创造客户价值、完成销售目标
²         带领、帮助并扶植新员工的成长、打造并推动一支强有战斗力的营销及客服团队.
²         扩大公司产品在海外的市场份额；提升公司品牌RealSmart在全球的影响力；提升中国供应商在海外的信誉度
 岗位要求：
²         专科及以上学历，工科、市场营销、传媒等专业优先
²         英语听说能力熟练，会西班牙语、法语等小语种优先
²         有远大的理想及事业抱负; 喜欢思考问题、乐于助人.
²         对电子商务及推广工作有一定的认识或工作经验者优先
²         性格开朗，良好的口头、书面沟通能力; 具备独立工作的能力
²         有智能卡、RFID电子标签或芯片行业的销售及服务工作经验者优先
²         思路清晰，擅长团队协作，有带领团队开拓目标市场的潜力和培养与客户长期合作的能力
²         Office办公软件熟练, PowerPoint、Excel熟练者优先；会用ACDSEE或PS等进行简单的图片处理
²         具有强烈责任心和进取心，具备高度工作热情，能够承受一定的工作压力、具备吃苦耐劳的工作精神
²         具备较强的市场分析、营销、推广能力和良好的人际沟通、协调能力，分析和解决问题的能力

工作地址：
上海市宜山路1768号205室
查看职位地图
**********
上海真智电子标签技术有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
贸易/进出口
公司主页：
http://www.rsmart.com.cn/default.asp
公司地址：
上海市宜山路1768号205室
**********
Senior Sales Executive/高级销售主管
维兰德金属(上海)有限公司 Wieland Metals (Shanghai) Limited
带薪年假弹性工作补充医疗保险免费班车员工旅游
**********
福利:
带薪年假
弹性工作
补充医疗保险
免费班车
员工旅游
**********
职位月薪：10000-16000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：1人
职位类别：销售主管
**********
岗位职责：
1.Sales and marketing of the business unit copper alloy strips & profiles, including:
(1) Evaluate sales data to support Management in the yearly and strategic planning.
(2)(Re)activate previous or potential customers: New projects/business opportunities/potential customers
explore.
(3) Continous contact to customers on-the-spot, organize visit report and monthly sales report.
(4) Coordinate internal/external visitors.
(5) Monitor AR and assure payment get back to account in time.
(6) Training new sales people in the department.
2.Assure stock control and ensure stable supply to the market.
3.Identify relevant customers/ opportunities and establish market intelligence.
4.Claim Management.
 任职要求：
1.Experience: Min 5 sales & marketing experience in manufacturing company, regional sales and marketing experience in leadframe, power, connector ,semiconductor or car industry preferred.
2.Qualification: Degree in Marketing, Technical Engineering, Business, Trade or equivalent.
3.Skills: MS Office, presentation skills,biz sense.
4.Personality: Willingness to travel, well trained communication skills and analytical thinking abilities. Must be a teamplayer, task-oriented & able to work under pressure.
5.Language: Good command of oral & written English.
6.Japanese or German speaking is referrable
  工作地址：
上海市外高桥保税区富特中路399号
查看职位地图
**********
维兰德金属(上海)有限公司 Wieland Metals (Shanghai) Limited
公司规模：
100-499人
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.wieland.com.cn
公司地址：
上海市外高桥保税区富特中路399号/深圳市龙华新区大浪社区浩盛隆工业区
**********
(Sr.)Technical Marketing Engineer
维兰德金属(上海)有限公司 Wieland Metals (Shanghai) Limited
五险一金餐补带薪年假弹性工作补充医疗保险定期体检免费班车员工旅游
**********
福利:
五险一金
餐补
带薪年假
弹性工作
补充医疗保险
定期体检
免费班车
员工旅游
**********
职位月薪：10000-20000元/月 
工作地点：上海-浦东新区
发布日期：最新
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：1人
职位类别：业务拓展经理/主管
**********
岗位职责：
 (A) Business Development & Account Penetration
(1) To identify suitable targets & spearhead account engagement
(2) To reach the effective contact windows at the customers' end
(3) To hold regular customer engagement meetings
(4) To conduct wide-audience & focused-account marketing activities
(5) To formulate & create customer retention techniques/aids
(B) Market Intelligence
(1) To seek front-end business information from customers
(2) To engage personnel at all levels & functional departments
(3) To understand customers' current focus & future action plans
(4) To gather information on competition strength/weakness & activities
(C) Market Survey & Trend Analysis
(1) To study new devices, specifications & influencing market changes
(2) To gather information on future roadmaps, market needs & trends
(3) To translate product requirements into Wieland material demand
(D) Demand Creation & Design-In
(1) To influence decisions in design & material selection authorities
(2) To secure opportunities in early design/alloy selection involvement
(3) To reinforce value-selling through regular design exchanges
(4) To enforce comprehensive & regular reporting of front-end activities
(E) Application Engineering
(1) To understand product, components, material & process needs
(2) To champion product qualification activities in projects/programs
(F) Technical Support
(1) To manage response to all engineering enquiries from customers
(2) To conduct trainings and provide technology updates to Wieland team
(G) Quality Matter Facilitation
(1) To provide containment & resolution support in key quality issues
(2) To participate in Wieland engineering/production issue resolutions
任职要求：
Experience: 
* Minimum 2 years of front-line (direct) management of customers with a good mix of responsibilities spanning  from application engineering, technical services, business development & marketing work.  
*Knowledge of copper & copper alloys, metal business & manufacturing experiences with good customer network  in the connector, IC/semi-conductor/lead frame, hi-speed stamping, automotive component & equivalent markets preferred.       
*University degree or equivalent, majoring in material science, metallurgy, mechanical engineering or equivalent engineering disciplines.       
*Diploma in engineering with suitable industrial experience would be considered.   
*Strong presentation skills in English & Chinese languages, especially good ability in articulation, for the purpose of  wide audience technical presentations. Able to effectively execute engineering coordination / exchanges with external & internal customers in both languages is mandatory.  
*Proficiency in Microsoft Office, Lotus Notes, product design tools & SAP preferred.  
*Out-going with a passion to serve customers.
*English & Chinese languages. Good writing, reading & speaking abilities in both languages.
工作地址：
上海市外高桥保税区富特中路399号
查看职位地图
**********
维兰德金属(上海)有限公司 Wieland Metals (Shanghai) Limited
公司规模：
100-499人
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.wieland.com.cn
公司地址：
上海市外高桥保税区富特中路399号/深圳市龙华新区大浪社区浩盛隆工业区
**********
招商经理
上海开皇实业有限公司
创业公司五险一金包吃交通补助节日福利定期体检
**********
福利:
创业公司
五险一金
包吃
交通补助
节日福利
定期体检
**********
职位月薪：8000-15000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：5人
职位类别：招商经理
**********
岗位职责：
1.负责公司的渠道招商工作，潜在客户的开发、联络、维护工作，完成招商任务；
2.管理招商团队，完成招商团队任务，收集辖区市场信息，并及时反馈；
3.根据安排独立进行业务谈判，促成意向客户成功合作并签订合同；
4.协调已签约客户前期的市场启动和市场运作；
5.完成上级交办任务。
任职要求：
1.25-35岁，大专以上，有成功的招商经验和渠道招商团队管理经验；
2.性格外向，良好的沟通能力，谈判能力，有强烈的事业心和责任心；
3.良好协调能力和团队管理能力，敏锐的判断能力及商业谈判技巧，能承担较大压力；
福利：绩效奖金，五险一金，工作餐，带薪年假，节日福利, 免费体检
薪资：底薪8K_1.5k+高额提成

我们的平台：
如果你是千里马，这里将是任你驰骋的疆场。公正公平的福利待遇，开明活跃的公司氛围，友好团结的领导同事，前途无量的发展前景，在这里，价值会得到充分的发挥。只要你是一个努力的充满激情和梦想的人，相信你会融入我们，并和我们一起创造辉煌！

工作地址：
长宁区剑河路888弄B-22
查看职位地图
**********
上海开皇实业有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
互联网/电子商务
公司主页：
http://www.bintutu.com/index.html
公司地址：
长宁区剑河路888弄B-22
**********
采购主管
上海小管家电器实业有限公司
节日福利高温补贴员工旅游餐补带薪年假
**********
福利:
节日福利
高温补贴
员工旅游
餐补
带薪年假
**********
职位月薪：6001-8000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：2人
职位类别：采购经理/主管
**********
职位描述：
公司主要提供智能家居家装产品相关的产品和服务，主要包括智能开关，智能灯具，智能建材，智能家具，智能软装，智能安防等产品。
1、收集市场需求，结合公司策略，能准确提炼出可以用于公司商品的开发计划，并及时开发规划新产品。
2、对产品开发过程进行管理，有效把握产品开发节奏，对市场变化快速做出反映。
3、负责供应商开发、谈判比价，争取对公司有利的合作条款。
5、协助部门处理日常性事务。  
职位要求：
1、专科以上，具有二年商品采购，供应商开发谈判工作经验；
2、具备较强的学习分析能力，了解市场资讯，能独立思考和解决问题，善于工作的统筹规划；
3、具备良好的协调、沟通表达及理解能力，达到预期目标；
4、能熟练运用Office软件（word\execl\ppt）；
5、有智能产品，装修建材采购经验者优先考虑。

工作地址：
上海黄浦区北京东路666号C区904
查看职位地图
**********
上海小管家电器实业有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
互联网/电子商务
公司主页：
www.shxgj.com
公司地址：
上海黄浦区北京东路666号C区904
**********
VC++ 软件工程师
上海仁昊电子科技有限公司
五险一金绩效奖金全勤奖餐补带薪年假高温补贴员工旅游
**********
福利:
五险一金
绩效奖金
全勤奖
餐补
带薪年假
高温补贴
员工旅游
**********
职位月薪：4000-8000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：2人
职位类别：软件工程师
**********
职位职责：
1、  按照研发经理要求编写代码。
2、  维护公司现有的产品代码。
3、  编写与软件相关的设计开发文件。
4、  对软件进行测试。
 职位要求
1、  计算机专业大专及以上学历
2、  熟悉C++语言，有良好的编程习惯。
3、  熟悉 MFC 程序开发，WINDOWS API 开发
4、  对数据库有所了解。
有移动应用、web开发经验或者相关知识者优先。

工作地址：
上海市宝山区园康路300号C栋2楼
查看职位地图
**********
上海仁昊电子科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.shrhdz.com.cn/
公司地址：
上海市宝山区园康路300号C栋2楼
**********
出纳
上海六盛电机有限公司
五险一金加班补助餐补通讯补贴免费班车
**********
福利:
五险一金
加班补助
餐补
通讯补贴
免费班车
**********
职位月薪：4001-6000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：出纳员
**********
岗位职责：
1、按规定每日登记现金日记账和银行存款日记账。
2、根据记账凭证报销内容收付现金。
3、每日负责盘清库存现金，核对现金日记账，按规定程序保管现金，保证库存现金及有价证券安全。
4、保管好各种空白支票、票据、印鉴。
5、负责接收各项银行到款进账凭证，并传递到有关的制单人员。
6、完成部门领导交办的其他任务。
岗位要求：
1、大专及以上学历，会计、金融等相关专业；
2、沟通能力佳,普通话标准,有较强的责任心，工作认真仔细；
3、持有会计上岗证，有相关工作经验；


工作地址：
上海市浦东新区康梧路200号
**********
上海六盛电机有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司地址：
上海市浦东新区康梧路200号
查看公司地图
**********
进出口专员
上海真智电子标签技术有限公司
绩效奖金交通补助餐补带薪年假节日福利高温补贴员工旅游定期体检
**********
福利:
绩效奖金
交通补助
餐补
带薪年假
节日福利
高温补贴
员工旅游
定期体检
**********
职位月薪：4001-6000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：2人
职位类别：物流专员/助理
**********
任职要求：
1、大专或同等学历以上，国际贸易、物流、等相关专业优先。
2、工作经验：1年-2年 ( 有相关工作经验者优先),具有进出口单证操作经验者优先。有意愿从事进出口物流业务的应届生亦可考虑
3、思维严谨，个性稳重，工作细致认真，谦虚谨慎，善于学习，具有良好的团队协作精神。
4、能熟练运用Office办公软件。
5、公共英语三级或英语四级，外语良好者优先。
岗位描述：
1、进出口单据制作，存档及备份。
2、进出口货物追踪，反馈及问题处理
3、国外客户出口货物信息对接
4、出入库单据填写
5、出运信息表登记及数据汇总。
工作地址：
上海市宜山路1768号205室
查看职位地图
**********
上海真智电子标签技术有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
贸易/进出口
公司主页：
http://www.rsmart.com.cn/default.asp
公司地址：
上海市宜山路1768号205室
**********
硬件工程师
上海仁昊电子科技有限公司
五险一金加班补助全勤奖餐补带薪年假定期体检员工旅游高温补贴
**********
福利:
五险一金
加班补助
全勤奖
餐补
带薪年假
定期体检
员工旅游
高温补贴
**********
职位月薪：4000-7000元/月 
工作地点：上海-宝山区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：3人
职位类别：硬件工程师
**********
1、大专以上学历，电子或自动控制专业；
2、具有两年以上相关工作经验；
3、熟练使用C语言；
4、能熟练运用Protel等软件，可以独立完成电子电路及单片机的应用设计；
5、英语良好，有较强的学习能力；

工作地址：
上海市宝山区园康路300号C栋2楼
查看职位地图
**********
上海仁昊电子科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.shrhdz.com.cn/
公司地址：
上海市宝山区园康路300号C栋2楼
**********
采购经理
上海六盛电机有限公司
五险一金加班补助餐补节日福利
**********
福利:
五险一金
加班补助
餐补
节日福利
**********
职位月薪：10001-15000元/月 
工作地点：上海-浦东新区
发布日期：最新
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：1人
职位类别：采购经理/主管
**********
岗位职责：
1、制定并完善公司采购与供应商管理制度、工作流程，建立供应商管理评估体系；
2、负责组织对供应商质量体系的审核，负责采购计划的制定及采购过程的跟踪；
3、负责采购成本的控制，建立中长期供货渠道；
4、负责产品的询价、比价、议价及谈判，采购合同的签订和应付款的审查工作；
5、负责收集分析国内外市场信息，及时控制和协调供需各业务环节，及时预警可能的高库存或缺货风险并协调改善；
6、负责部门的日常管理工作及部门员工的管理、指导、培训及评估；

任职要求：
1、大专以上学历，机械、电子、物流等相关专业。
2、5年以上制造业同等岗位工作经验，熟悉电子产品零部件采购；
3、综合协调能力强，能承受较强的工作压力；
4、精通供应商开发、管理，并具有很强的沟通协调能力、谈判能力、说服能力以及团队管理能力。

工作地址：
上海市浦东新区康梧路200号
查看职位地图
**********
上海六盛电机有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司地址：
上海市浦东新区康梧路200号
**********
财务助理
上海六盛电机有限公司
五险一金加班补助餐补通讯补贴免费班车带薪年假
**********
福利:
五险一金
加班补助
餐补
通讯补贴
免费班车
带薪年假
**********
职位月薪：4001-6000元/月 
工作地点：上海-浦东新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：财务助理
**********
1、按规定每日登记现金日记账和银行存款日记账。
2、根据记账凭证报销内容收付现金。
3、每日负责盘清库存现金，核对现金日记账，按规定程序保管现金，保证库存现金及有价证券安全。
4、保管好各种空白支票、票据、印鉴。
5、负责接收各项银行到款进账凭证，并传递到有关的制单人员。
6、完成每月薪资计算及发放。
6、完成部门领导交办的其他任务。
岗位要求：
1、大专及以上学历，会计、金融等相关专业；
2、沟通能力佳,有较强的责任心，工作认真仔细；
3、持有会计上岗证，有相关工作经验优先考虑；


工作地址：
上海市浦东新区康梧路200号
**********
上海六盛电机有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司地址：
上海市浦东新区康梧路200号
查看公司地图
**********
售前/售后技术支持工程师
上海海赋机电设备有限公司
五险一金绩效奖金加班补助餐补通讯补贴带薪年假定期体检员工旅游
**********
福利:
五险一金
绩效奖金
加班补助
餐补
通讯补贴
带薪年假
定期体检
员工旅游
**********
职位月薪：6001-8000元/月 
工作地点：上海-嘉定区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：售前/售后技术支持工程师
**********
要求：

       1）大学专科及以上学历，自动化及其相关专业毕业；

       2）具有机床或自动化领域产品调试或维修经验；

       3）责任心强，善于学习，努力钻研技术，工作勤奋，富有合作精神；

       4）具有良好的表达能力，善于沟通，良好的客户服务意识；

       5）英语读写流畅，可以比较顺畅的阅读英文资料；

       6）独立工作能力强，能够经常出差。
  岗位描述：

       1）负责公司日常的售前、售后技术支持及产品维修工作，

       2）负责公司所售产品的现场安装调试及维修；

       3）负责公司所售产品的售前及售后技术支持，解答用户疑问，帮助用户选型。
  工作地址：
嘉定区沪宜公路1101号南翔智地越界产业园
查看职位地图
**********
上海海赋机电设备有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
大型设备/机电设备/重工业
公司地址：
嘉定区沪宜公路1101号南翔智地越界产业园
**********
线上咨询师（课程顾问/做五休二/底薪5-7k）
上海航傲信息科技有限公司
无试用期每年多次调薪带薪年假绩效奖金免费班车员工旅游节日福利
**********
福利:
无试用期
每年多次调薪
带薪年假
绩效奖金
免费班车
员工旅游
节日福利
**********
职位月薪：10001-15000元/月 
工作地点：上海-浦东新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：5人
职位类别：电话销售
**********
公司提供精准数据，，客户在公司的在线教育平台注册过账户，非扫白数据）
岗位职责：
1、 通过电话及网上咨询的方式针对客户的背景及需求进行挖掘和分析，客户问题详细解答，对课程做出准确推荐；
2、主动努力回访，有效沟通，解决客户的问题；
3、根据客户需求制定个性化的学习计划；
4、根据公司制定的销售目标，配合团队完成销售任务；
5、建立和维护客户关系；
 6、做五休二，朝九晚六；园区班车接送上下班。
岗位要求：
1、热爱教育事业，拥有高度的工作热情，开朗自信，普通话标准流利； 
2、专科及以上学历，二年以上销售经验优先，有在线教育销售经验优先，熟悉培训行业流程优先；
3、具备出色的电话沟通技巧及熟练的网络交流，讲话有条理，思路清晰有耐心，亲和力强；
4、具备吃苦精神且上进心强，有责任感及良好的团队合作意识，敢于挑战高薪； 
5、具备销售意识，能承受工作压力，积极主动，能有效合理安排时间并保证既定目标的实现。
6、有教育行业销售经验者优先录用，例如：课程顾问，续约专员等销售类的岗位。
上海找个工作很容易，找类似的工作也很容易，但是如果你想在一年或一年半内升职，从一个一线成长为一个主管，我可以负责的告诉你：能在上海给你这样机会的公司不多。如果你来上海是为了追求发展和蜕变的，那么我希望你至少给自己，也给我们公司一个机会，各位朋友来上海不光是为了生存对吧，想在这么短的时间里有一个机会是千金难买的，那还犹豫什么？现在就行动吧！欢迎投递！

工作地址：
浦东新区张衡路180号2号楼2楼
查看职位地图
**********
上海航傲信息科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司地址：
上海徐汇区漕溪路
**********
田中贵金属--管理部担当-日语n2以上
轶甲新材料科技(上海)有限公司
交通补助餐补带薪年假定期体检员工旅游节日福利
**********
福利:
交通补助
餐补
带薪年假
定期体检
员工旅游
节日福利
**********
职位月薪：5000-6000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：出纳员
**********
田中贵金属(上海)有限公司招募

岗位职责：現金出納、発票発行、税務関連、庶務等
 必要条件：
女性
上海人
N2以上
会計従業資格証
Excel能力
25－28歳
経験者優先し、管理業務に興味があり、やる気のある方希望
処遇・待遇は当社規定に準じます。

工作地址
上海市徐汇区虹桥路3号港汇中心二座2806室
田中贵金属(上海)有限公司

田中贵金属(上海)有限公司  与 轶甲新材料科技(上海)有限公司   同为日本田中贵金属集团在中国开设的独资公司。
  工作地址：
上海市徐汇区虹桥路3号港汇中心二座 2806室
查看职位地图
**********
轶甲新材料科技(上海)有限公司
公司规模：
20人以下
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
null
公司地址：
上海市奉贤区目华北路388号第一幢368室
**********
销售助理
上海德灿电子有限公司
年底双薪五险一金带薪年假通讯补贴交通补助
**********
福利:
年底双薪
五险一金
带薪年假
通讯补贴
交通补助
**********
职位月薪：5500-7000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：2人
职位类别：区域销售专员/助理
**********
销售及行政助理
 1管理办公室各项事务。
2 跟踪部分客户沟通业务进展情况，及时反馈给公司管理层。
3及时审阅和处理公司对外的合同及其它文件。
4跟踪货物进口和管理物流运作状况。
5起草公司文件和对外沟通的邮件
6安排领导差旅行程和接待客户和合作方
7完成公司领导交办的其它事务
  要求：
1 正规大学本科以上学历，化学、管理、法律、英语、中文专业优先考虑。
2 头脑反应敏捷，记忆力好，思路清晰。
3 具有一定的英语水平和口语能力，英语六级。
4 具有较强的写作能力和口头表达能力。
公司会考虑此职位应聘者将来发展空间，因此需要有很强的学习和领悟能力。
 
工作地址：
上海市徐汇区漕宝路103号1214室
查看职位地图
**********
上海德灿电子有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.decan.com.cn
公司地址：
上海市徐汇区漕宝路103号1214室
**********
销售工程师（上海）
厦门大恒科技有限公司
五险一金年底双薪绩效奖金带薪年假节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
带薪年假
节日福利
**********
职位月薪：6000-10000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：3人
职位类别：销售工程师
**********
岗位职责：
1、负责设计院上图，项目跟踪，电气成套厂维护等相关工作，并承担区域经理制定的各项销售指标；
2、发展，并支持代理商的销售和市场工作，组织产品推广会，负责货款的及时回收；
3、与KA客户保持良好的合作关系，并开发有潜力的目标市场；
4、针对特定的OEM或ODM客户，了解客户需求，协助公司提供定制产品；
5、建立客户资料卡及客户档案，及时填写相关销售报表、工作报告等；
6、积极组织，参与团队建设活动；
7、按时完成区域经理临时交办的其他事务性工作；
任职要求：
1、电气自动化、市场营销、企业管理或相关专业专科以上学历；2年以上销售工作经验或电气专业应届生；
2、能够在压力下有效的开展工作，具备销售人员的培养潜力；
3、熟练操作办公软件；
4、可考虑优秀的消防，文艺转业军人；
工作地址：
上海
查看职位地图
**********
厦门大恒科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.taihang.cc
公司地址：
厦门市火炬高新区（翔安）产业区同龙二路573号
**********
VCU软件工程师
上海电驱动股份有限公司
免息房贷节日福利高温补贴员工旅游免费班车定期体检股票期权五险一金
**********
福利:
免息房贷
节日福利
高温补贴
员工旅游
免费班车
定期体检
股票期权
五险一金
**********
职位月薪：15001-20000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：1人
职位类别：电子技术研发工程师
**********
1. 保质、保量、按时完成上级领导安排的工作任务，并配合项目主管，做好软件方面工作；
2. 负责软件的开发与项目的管理，制定及审核软件开发方案及项目的报价，包括制定开发时间进度计划，产品需求需求分析,定义产品软件性能及功能需求规格书；
3. 监督与控制项目的进度以确保产品按时按质送样；
4. 负责软件的开发与系统的集成，包括进行软件架构的设计，制定规范要求并确保组员的正确实施，对系统的稳定性负责；
5. 负责或监督项目软件的配置与版本管理；
6. 负责软件架构及单元模块的设计与编程及软件维护调试.
7. 配合硬件工程师完成项目详细方案制定和实施；
按ISO/TS16949体系标准及软件开发流程体系的要求，完成设计各阶段软件开发文档资料归档工作。

工作地址：
上海市嘉定区恒裕路300号（近百安公路）
查看职位地图
**********
上海电驱动股份有限公司
公司规模：
500-999人
公司性质：
股份制企业
公司行业：
汽车/摩托车
公司主页：
www.chinaedrive.com
公司地址：
上海市嘉定区恒裕路300号（近百安公路）
**********
技术服务工程师
上海德灿电子有限公司
年底双薪通讯补贴交通补助带薪年假
**********
福利:
年底双薪
通讯补贴
交通补助
带薪年假
**********
职位月薪：5500-7000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：1人
职位类别：售前/售后技术支持工程师
**********
技术服务工程师
 岗位职责
1、负责所辖区域的三防漆和灌封胶产品技术支持；
2、维护及增进已有客户关系；
3、完成部分技术支持工作,与客户进行技术交流；
4、负责收集市场和行业信息,加深了解市场。

任职资格
1、本科及以上学历，化工或者营销类相关专业；
2、2年以上化工产品工作经验,有三防漆、油漆、涂料和灌封胶销售工程师经历者优先；
3、熟悉该行业产品市场，有化学制品的产品知识和技术；
4、具备较强的客户沟通能力和应变能力，具有良好的团队协作精神；
5、学习能力强，有挑战精神。
6、有驾照者优先考虑。

工作地址：
上海市徐汇区漕宝路103号1214室
查看职位地图
**********
上海德灿电子有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.decan.com.cn
公司地址：
上海市徐汇区漕宝路103号1214室
**********
软件工程师
上海兆富电子科技有限公司
五险一金绩效奖金加班补助全勤奖带薪年假高温补贴
**********
福利:
五险一金
绩效奖金
加班补助
全勤奖
带薪年假
高温补贴
**********
职位月薪：6000-10000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：2人
职位类别：软件工程师
**********
岗位要求：
1.精通C#语言，熟悉不同的开发方式，包括ASP.NET、Windows Form、Web Services(WCF)、DLL等。
2.精通SQL Server数据库。
3.能迅速、准确的把握开发需求，并转化为实际的软件功能。
4.具有良好的编程习惯，代码清晰、可读性强，并且易扩展。
5.至少具有2年以上开发经验。
 岗位职能： 
1、根据项目需求独立定制开发相关软件； 
2、完成项目文档及其它相关工作。

工作地址：
上海市嘉定区南翔镇藴北公路1755弄1号
查看职位地图
**********
上海兆富电子科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司地址：
上海市嘉定区南翔镇藴北公路1755弄1号
**********
人力资源专员
派洽精密仪器（上海）有限公司
**********
福利:
**********
职位月薪：4001-6000元/月 
工作地点：上海-浦东新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：人力资源专员/助理
**********
任职要求：
1.大专学历，人资专业毕业，具有人资培训经验或人资工作经验者佳； 
2.其它：文笔较好，良好的沟通协调能力，工作责任心强。
岗位要求：
1.　掌握并熟练运用人力资源管理六大模块独立开展工作； 
2.　编制人事行政制度类文件，并规范化管理； 
3.　推进培训开展； 
4.公司企业文化建设：①组织公司内部员工活动。 ②建立员工与管理层的沟通渠道，吸引员工关心公司事务并参与管理。③负责企业宣传工作。 
5.员工日常工作考核、绩效考核、员工升职、降职、转岗、离职、工伤、劳资纠纷等工作。 
6.完成上级领导交办的其它任务

工作地址：
1) 上海浦东新区莲溪路1280号
查看职位地图
**********
派洽精密仪器（上海）有限公司
公司规模：
20-99人
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.petracarbon.com.cn
公司地址：
1) 上海浦东新区莲溪路1280号
**********
电子商务
汉唐高强防潮电子(上海)有限公司
补充医疗保险五险一金不加班节日福利员工旅游绩效奖金带薪年假全勤奖
**********
福利:
补充医疗保险
五险一金
不加班
节日福利
员工旅游
绩效奖金
带薪年假
全勤奖
**********
职位月薪：4001-6000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：2人
职位类别：电子商务专员/助理
**********
任职要求：
1、大专及以上学历，电子商务等相关专业；
2、熟悉淘宝平台，天猫规则和操作流程， 可以简单使用修图软件；
3、有丰富的网络营销经验和CRM经验，可以指导客服工作。
工作地址：
徐汇区宜山路425号光启城908
查看职位地图
**********
汉唐高强防潮电子(上海)有限公司
公司规模：
20-99人
公司性质：
港澳台公司
公司行业：
电子技术/半导体/集成电路
公司地址：
徐汇区宜山路425号908
**********
市场销售专员
深圳市航纬电子有限公司
**********
福利:
**********
职位月薪：6001-8000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：销售工程师
**********
岗位职责：
1.处理公司移交的客户报价以及订单制作，定期联系并拜访客户。
2.协助业务人员进行订单制作，跟单，样品寄送，为销售部提供帮助。
3.处理制作业务员交给的报表，单椐，文件，资料等。
4.可接受长期出差或驻外。
任职要求：
1.仪表整齐大方，普通话标准流利。
2.工作细致、认真、有责任心，具备良好的团队合作意识。
3.具备良好的沟通能力及人际交往能力，自信乐观，亲和力强。
加入我们，你将拥有：
1、月工资：底薪+提成+保险+社保+电话补贴+年底奖金；
2、假期：除享受国家法定节日（元旦，五一，十一等）外，补充额外的休假，婚假，产假；
3、工作时间：每周 五天7.5小时制；公司有定期销售和产品培训；
4、办公环境：南山区科技园北区甲级写字楼，办公环境舒适；
5、精神文化：不定期组织员工旅游和文体活动，增强员工归属感；每年公司组织一/两次国内外旅游。
6、身心关怀：公司关心员工身体健康，每年免费为员工进行体检.

工作地址：
深圳市南山区高新技术园北区清华紫光信息港C310
**********
深圳市航纬电子有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.navhk.com/index.asp
公司地址：
深圳市南山区高新技术园北区清华紫光信息港C310
查看公司地图
**********
销售应用工程师
王氏港建贸易(上海)有限公司
**********
福利:
**********
职位月薪：7000-12000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：2人
职位类别：售前/售后技术支持工程师
**********
1、  电子类机械类专业专科以上
2、  3-5年以上光绘机维修应用工作经验，
3、  良好的沟通协调能力，能承受工作中的压力，能经常出差
4、  性格稳重，善于处理任何突发事件
5、 熟练运用电脑（WORD.EXCEL.及PPT）
6、 英语CET6级以上，听说读写流利， 能出国培训

工作地址：
上海金沙江路1340弄172支弄14号1号楼
查看职位地图
**********
王氏港建贸易(上海)有限公司
公司规模：
20-99人
公司性质：
外商独资
公司行业：
加工制造（原料加工/模具）
公司主页：
http://www.wkk.com.hk
公司地址：
上海金沙江路1340弄172支弄14号1号楼
**********
医疗器械产品研发工程师
上海翊科精密挤出技术有限公司
创业公司五险一金绩效奖金股票期权包住带薪年假员工旅游节日福利
**********
福利:
创业公司
五险一金
绩效奖金
股票期权
包住
带薪年假
员工旅游
节日福利
**********
职位月薪：20001-30000元/月 
工作地点：上海-浦东新区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：5人
职位类别：医疗器械研发
**********
1.       项目开发工程师 若干
岗位职责：医疗器械（高值耗材OEM）产品的研发，产品涉及消化内科，心脑/外周血管，泌尿科等。
 任职要求：1.    高分子材料专业/机械设计类本科学历，硕士研究生学历优先
           2.    3年以上相关医疗器械的研发与设计经验；
           3.    具有丰富的项目管理经验和技能优先。      

工作地址：
上海市浦东新区瑞庆路528号24幢乙一层
查看职位地图
**********
上海翊科精密挤出技术有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
www.ecoprecision.com.cn
公司地址：
上海市浦东新区瑞庆路528号24幢乙一层
**********
销售经理
总友智能科技(上海)有限公司
五险一金绩效奖金交通补助带薪年假节日福利
**********
福利:
五险一金
绩效奖金
交通补助
带薪年假
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：3人
职位类别：销售经理
**********
销售工作职责；
1.负责公司CAD/PLM/MES/以及行业套装软件产品推广销售工作。
2.在所负责的区域或行业内开发客户，与客户建立良好关系，并充分挖掘客户需求。
3.达成公司分配的年度销售任务，包括合同额，回款等。

工作要求： 
1.大专以上学历，制造及产品设计类、计算机科学或信息管理相关专业。
2.一年以上管理软件销售经验，对制造业有较深的理解。
3.有CAD/PLM/ERP/MES等类似行业软件销售经验者优先。
4.具有较强的市场开拓能力和项目销售能力，有独立开发客户与项目组织能力者为佳。
5.熟悉制造企业预算申请和采购流程。
6.具有良好的沟通表达能力，较好的引导和感染能力。
7.优秀的自我学习能力，具有较强的共赢意识和团队合作精神。
工作地址：
上海市宝山区水产路1269号吴淞口创业园313室
**********
总友智能科技(上海)有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
计算机软件
公司地址：
上海市宝山区水产路1269号吴淞口创业园313室
**********
客服专员
上海祥门智能科技有限公司
五险一金绩效奖金全勤奖通讯补贴带薪年假员工旅游高温补贴节日福利
**********
福利:
五险一金
绩效奖金
全勤奖
通讯补贴
带薪年假
员工旅游
高温补贴
节日福利
**********
职位月薪：3500-7000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：中技
招聘人数：2人
职位类别：客户服务专员/助理
**********
工作内容：
1、在公司负责电话指导或电脑远程帮客户解决软硬件产品的安装、调试及维护工作；
2、处理客户的服务请求，配合销售人员对客户的售前、售后疑问进行电话解答；
3、产品测试，用户产品培训；
职位要求：
1、女性，21-35周岁，计算机、机电或者相关理工科专业毕业，中专及以上学历，优秀的应届毕业生也行；
2、具有2年以上的工作经验，有银行保险电信等行业客服经验的优先录用；有过弱电、安防、一卡通从业经验优先录取。
3、会CAD软件制图；了解SQL数据库
4、善于沟通并维护客户关系，责任心强；
5、服从领导安排，

工作地址：
松江区江田东路259号
查看职位地图
**********
上海祥门智能科技有限公司
公司规模：
20-99人
公司性质：
合资
公司行业：
通信/电信运营、增值服务
公司主页：
www.xiangmen.net.cn
公司地址：
松江区江田东路259号4栋
**********
前台行政
上海捷盟信息科技有限公司
年底双薪全勤奖带薪年假定期体检五险一金员工旅游节日福利
**********
福利:
年底双薪
全勤奖
带薪年假
定期体检
五险一金
员工旅游
节日福利
**********
职位月薪：3000-5000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：前台/总机/接待
**********
工作职责:
1、负责公司前台接待及电话接转；
2、收发传真，复印文档，收发信件、报刊、文件等；
3、及时更新和管理员工通讯地址和电话号码等联系信息；
4、受理会议室预约，协调会议时间，下发会议通知，布置会议室；
5、负责订水、订报，信件、包裹的安排及与快递公司的联系；
6、负责各级主管交办出差安排等各项工作；
7、完成上级交给的其它事务性工作。

任职资格:
1、熟悉前台工作流程，熟练使用各种办公自动化设备；
2、工作热情积极、细致耐心，具有良好的沟通能力、协调能力，性格开朗，相貌端正，待人热诚；
3、熟练使用相关办公软件。
工作地址：
上海市浦东新区金豫路251号2号楼408
查看职位地图
**********
上海捷盟信息科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
www.geunion.com.cn
公司地址：
上海市浦东新区金海路1000号18号楼西区4楼
**********
售后技术支持工程师
北京百联长通科技有限公司
五险一金带薪年假弹性工作节日福利
**********
福利:
五险一金
带薪年假
弹性工作
节日福利
**********
职位月薪：4000-8000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：售前/售后技术支持工程师
**********
任职要求
1、电子、电气相关专业；
2、工作积极主动，责任心强；
3、较强的独立分析问题和解决问题的能力；
4、有售后工作经验者优先。
工作描述
1、负责对客户进行技术指导与沟通，售前、售后的技术支持工作；
2、为公司的售前、客服团队提供产品技术类问题的支持工作；
3、与客户沟通，解决产品部署、使用方面的技术问题；
4、有良好的服务意识和职业态度，对服务的价值有深刻理解；
5、整理客户的反馈信息，与研发人员沟通，更好的优化产品；
6、收集、分析客户需求，并根据客户需求制定相应的技术解决方案

工作地址：
浦东德林路
查看职位地图
**********
北京百联长通科技有限公司
公司规模：
20人以下
公司性质：
其它
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.hardcan.com
公司地址：
北京市大兴区亦庄经济技术开发区
**********
电镀工程师
轶甲新材料科技(上海)有限公司
加班补助交通补助餐补带薪年假
**********
福利:
加班补助
交通补助
餐补
带薪年假
**********
职位月薪：4000-6000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：不限
招聘人数：1人
职位类别：半导体技术
**********
岗位职责：电镀工程师

任职要求：
1，在PCB电镀行业有经验者优先考虑。
2，对电镀行业熟悉
3，能适应加班
4，动手能力强、逻辑性强，有较强的表达能力，为人热忱，踏实。
5，对问题有较强的总结能力和跟进能力。

工作地点：松江上海市松江区民强路550号

工作地址：
上海市松江区民强路550号
**********
轶甲新材料科技(上海)有限公司
公司规模：
20人以下
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
null
公司地址：
上海市奉贤区目华北路388号第一幢368室
查看公司地图
**********
活动策划执行
上海指南针信息技术有限公司
五险一金绩效奖金加班补助包吃节日福利
**********
福利:
五险一金
绩效奖金
加班补助
包吃
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：2人
职位类别：活动策划
**********
1、负责公司各项目、产品以及阶段性活动做出对应的策划方案、设计和撰写工作；
2、对公司业务的特点有清晰的认知和理解，做出有价值足够吸引市场的文案；
3、整合各方资源，完成包括活动策划、执行、运营、监督和后期收尾等整体活动流程的相关工作；
4、日常微信平台的管理和维护
5、定期做好公司品牌、产品宣传等维护工作；
6、协助上级完成各类宣传页面、广告设计及平面宣传资料的策划及文案工作;
7、协助上级完成各类内容素材的营销包装，达到最大的推广宣传效果;
8、完成上级交给的其它事务性工作。

任职要求：
1、形象得体，专科及以上学历，中文学、新闻学、广告等相关专业优先；
2、有一定的相关工作经验，对市场需求、行业优势挖掘等方面有一定的把握；
3、时刻关注热点，具敏锐的市场洞察力，文字功底深厚，能够独立思考、有创新意识及新颖独创的发散能力；
4、具有较强的团队合作精神以及服务协作意识；
5、办公软件操作较为熟练，PPT运用、Excel表格操作能力较好；
6、性格较外向，喜欢探索新鲜事物，善于沟通及交流。
7、有健康管理或医疗相关行业经验者优先。



工作地址：
上海市闵行区黎安路1187号5号楼
查看职位地图
**********
上海指南针信息技术有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
互联网/电子商务
公司地址：
上海市闵行区黎安路1187号5号楼
**********
淘宝美工
上海涌申电子信息科技有限公司
全勤奖加班补助绩效奖金五险一金餐补定期体检员工旅游节日福利
**********
福利:
全勤奖
加班补助
绩效奖金
五险一金
餐补
定期体检
员工旅游
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：上海-静安区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：3人
职位类别：平面设计
**********
岗位职责：
1、产品美化、编辑、促销广告设计、宣传品设计；
2、图片处理、网页美工，网页设计，网店模板设计；
3、处理日常商品图片，更新产品页面，设计产品页面风格，日常网页内容的更新与维护；
4、编辑公司各种产品的文字介绍，按照公司指示及时上传公司各种新品，更新网店相关内容；
5、负责策划，设计网店产品在重大节日的促销图片，网店装修；
6、满足公司其他部门所提出的美工方面的需求。
任职要求：
1、平面设计或摄影相关专业专科以上学历，优秀应届生可考虑；
2、熟练使用PS，DW，有相关网店美工经验1年以上；
3、思维敏捷，想象力丰富，积极主动，工作认真，富有团队精神。
4、有较好的美术基础和审美能力，可以独立进行网店装修新品设计。

工作地址：
上海市静安区江场西路299弄中铁中环广场6号楼501-502室
查看职位地图
**********
上海涌申电子信息科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
贸易/进出口
公司地址：
上海市闸北区江场西路299弄中铁中环广场6号楼501-502室
**********
办公室助理
上海卓岱电子科技有限公司
绩效奖金年底双薪餐补五险一金
**********
福利:
绩效奖金
年底双薪
餐补
五险一金
**********
职位月薪：4001-6000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：中专
招聘人数：1人
职位类别：行政专员/助理
**********
岗位职责：
        1，办公室资料整理。
        2，收发货管理。
        3，文档资料编辑及管理等
           4，其它办公室相关事宜。

任职要求：
        1，能熟练应用办公自动化软件。
        2，有电子工厂生产线工作经历优先。
 
工作地址：
上海市闵行区春申路2525号3幢238室
查看职位地图
**********
上海卓岱电子科技有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司地址：
上海市闵行区春申路2525号3幢466室
**********
测试工程师
上海伊诺尔实业集团有限公司
五险一金年底双薪包吃高温补贴节日福利定期体检
**********
福利:
五险一金
年底双薪
包吃
高温补贴
节日福利
定期体检
**********
职位月薪：8000-10000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：1人
职位类别：测试/可靠性工程师
**********
工作职责：
1．根据产品要求编写测试程式，并进行调试验证。
2．解决测试工序出现的异常。
3．测试相关改善及技术提升。
 任职要求：
1．本科及以上学历
2．计算机、电子、通信相关专业
3．会C语言及Java编程
4．有无尘车间工作经验、智能卡测试经验、熟悉通讯协议者优先

备注：本职位为集团下属子公司上海伊诺尔信息技术有限公司技术部岗位。

工作地址：
上海虹梅南路1755号
查看职位地图
**********
上海伊诺尔实业集团有限公司
公司规模：
500-999人
公司性质：
合资
公司行业：
印刷/包装/造纸
公司主页：
http://www.eternal.com.cn/
公司地址：
上海虹梅南路1755号
**********
高级硬件工程师
擎声自动化科技(上海)有限公司
五险一金免费班车节日福利
**********
福利:
五险一金
免费班车
节日福利
**********
职位月薪：8001-10000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：1人
职位类别：高级硬件工程师
**********
工作职责

1、根据产品设计报告，完成符合功能和性能要求的逻辑设计
2、根据逻辑设计说明书， 设计详细的原理图和PCB图
3、负责元器件的选型与评估
4、编写调试程序，测试或协助测试开发的硬件设备，确保其按设计要求正常运行
5、编写项目文档、质量记录以及其他有关文档
6、维护管理或协助管理所开发的硬件

任职要求
1、学历要求：本科以上学历，自动化，测控技术与仪器，电子信息及相关专业
2、工作经验：３年以上相关工作经验，有电机驱动相关工作者优先
3、专业能力：精通数字电路，模拟电路，熟练使用绘图软件（Cadence,Protel）等， 精通C语言，能利用C语言熟练编程；有FPGA/ARM开发经验
4、较强的沟通、学习能力，良好的团队合作精神，勤奋、有责任心，能承受一定的工作压力

工作地址：
上海市杨浦区翔殷路128号上海理工大学国家大学科技园12号楼2楼
查看职位地图
**********
擎声自动化科技(上海)有限公司
公司规模：
20-99人
公司性质：
股份制企业
公司行业：
仪器仪表及工业自动化
公司地址：
上海市杨浦区翔殷路128号上海理工大学国家大学科技园12号楼2楼
**********
组装工
擎声自动化科技(上海)有限公司
**********
福利:
**********
职位月薪：3500-4500元/月 
工作地点：上海-杨浦区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：组装工
**********
任职要求：
1.优秀的团队意识，良好的沟通协调能力。
2.思维敏捷，动手能力强，能吃苦，坚强的意志。
3.有耐心，工作勤奋，积极进取，服从工作分配。
工作地址：
上海市杨浦区翔殷路128号上海理工大学国家大学科技园12号楼2楼
**********
擎声自动化科技(上海)有限公司
公司规模：
20-99人
公司性质：
股份制企业
公司行业：
仪器仪表及工业自动化
公司地址：
上海市杨浦区翔殷路128号上海理工大学国家大学科技园12号楼2楼
查看公司地图
**********
技术支持工程师
擎声自动化科技(上海)有限公司
五险一金免费班车节日福利
**********
福利:
五险一金
免费班车
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：电气工程师
**********
工作职责
1、了解产品相关技术，培养敏锐的市场判别能力
2、整合客户资源，发掘新客户，掌握客户需求，建立和维护良好的客户关系
3、负责产品以及原材料的技术支持，配合采购人员完成技术确认
4、负责产品的测试


任职要求
1、学历要求：本科以上学历，自动化，测控技术与仪器，电子信息及相关专业
2、工作经验：2年以上相关工作经验
3、专业能力：熟悉各类电子器件，有线束加工经验者优先
4、较强的沟通、学习能力，良好的团队合作精神，勤奋、有责任心，能承受一定的工作压力力

工作地址：
上海市杨浦区翔殷路128号上海理工大学国家大学科技园12号楼2楼
**********
擎声自动化科技(上海)有限公司
公司规模：
20-99人
公司性质：
股份制企业
公司行业：
仪器仪表及工业自动化
公司地址：
上海市杨浦区翔殷路128号上海理工大学国家大学科技园12号楼2楼
查看公司地图
**********
市场经理
擎声自动化科技(上海)有限公司
五险一金创业公司年底双薪绩效奖金
**********
福利:
五险一金
创业公司
年底双薪
绩效奖金
**********
职位月薪：10001-15000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：1人
职位类别：市场总监
**********
任职要求：
1. 自动化、电机等相关专业，本科以上学历；
2. 5年以上从事自动化、电机、驱动等市场营销工作经验，2年以上管理经验；
3. 精通相关行业产品的市场行情和发展趋势，并熟悉相关领域国际贸易的实际操作；
4. 学习能力强，对于未涉足的相近行业和领域，能制定合理的计划，并很快地开展工作；
5. 能流利使用英语进行口头和书面交流；
6. 沟通能力强，具有良好的团队合作精神与责任心，品行端正。
 岗位职责：
1. 收集和整理相关行业有价值市场信息，分析产业状况及发展，形成报告，为项目立项提供依据；
2. 分析市场趋势和提炼市场需求，并转化成产品的功能和性能指标，指导产品开发；
3. 提供产品推广和商务策划支持，指导重点产品的销售推广，促进销售部门实现销售目标；
4. 组建团队，对新产品制定营销策略和计划，在国内外市场销售；
5、公司交办的相关事务。
工作地址：
上海市杨浦区翔殷路128号上海理工大学国家大学科技园12号楼2楼
查看职位地图
**********
擎声自动化科技(上海)有限公司
公司规模：
20-99人
公司性质：
股份制企业
公司行业：
仪器仪表及工业自动化
公司地址：
上海市杨浦区翔殷路128号上海理工大学国家大学科技园12号楼2楼
**********
销售工程师
擎声自动化科技(上海)有限公司
**********
福利:
**********
职位月薪：8001-10000元/月 
工作地点：上海-杨浦区
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：不限
招聘人数：1人
职位类别：销售工程师
**********
岗位职责：
1．学习与掌握线束相关产品与技术知识，培养敏锐的市场能力
2．整合客户资源，全面负责产品的推广与销售
3．掌握客户需求，制定销售目标与策略，完成上级下达的任务指标
4．稳固老客户，发掘新客户，建立和维护良好的客户关系
 
任职要求
1、学历要求：本科以上学历，自动化，机械设计制造及相关专业
2、工作经验：3年以上相关工作经验
3、专业能力：熟悉线束及连接器，了解行业应用
4、较强的沟通、学习能力，良好的团队合作精神，勤奋、有责任心，能承受一定的工作压力，能经常出差

工作地址：
上海市杨浦区翔殷路128号上海理工大学国家大学科技园12号楼2楼
查看职位地图
**********
擎声自动化科技(上海)有限公司
公司规模：
20-99人
公司性质：
股份制企业
公司行业：
仪器仪表及工业自动化
公司地址：
上海市杨浦区翔殷路128号上海理工大学国家大学科技园12号楼2楼
**********
机械工程师
擎声自动化科技(上海)有限公司
**********
福利:
**********
职位月薪：8001-10000元/月 
工作地点：上海-杨浦区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：机械工程师
**********
岗位职责：
1、开发与设计机械零部件，绘制产品装配图及零部件图
2、负责客户和外部设计的数据审核和工程图纸审核，发现问题提出修改建议和具体更
改措施，使之更加合理化、标准化
3、负责与生产部门、模具加工部门及模具制造商协调落实产品设计意图和具体工艺要
求
4、不得透露公司核心技术和专利产品，严格遵守与公司签订的保密协议

任职要求：
1、教育背景:机械或相关专业本科以上学历
2、工作经验:5年以上机械设计经验，电机行业经验者优先；
3、技能技巧:熟悉产品的制造工艺、加工工艺；熟悉机械部件的设计；熟练应用SolidWorks、AutoCAD等应用软件；具有良好的FEA知识和实际应用经验；
4、具有良好的团队精神和较强的协调能力；良好的沟通、组织管理能力；动手能力强，吃苦耐劳
工作地址
上海市杨浦区翔殷路128号上海理工大学国家大学科技园12号楼2楼

工作地址：
上海市杨浦区翔殷路128号上海理工大学国家大学科技园12号楼2楼
查看职位地图
**********
擎声自动化科技(上海)有限公司
公司规模：
20-99人
公司性质：
股份制企业
公司行业：
仪器仪表及工业自动化
公司地址：
上海市杨浦区翔殷路128号上海理工大学国家大学科技园12号楼2楼
**********
总经理助理
擎声自动化科技(上海)有限公司
创业公司五险一金带薪年假定期体检
**********
福利:
创业公司
五险一金
带薪年假
定期体检
**********
职位月薪：6001-8000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：总裁助理/总经理助理
**********
岗位职责：
 1、在总经理领导下负责办公室的全面工作，努力作好总经理的参谋助手，起到承上启下的作用，认真做到全方位服务。
2、在总经理领导下负责企业具体管理工作的布置、实施、检查、督促、落实执行情况。
3、协助总经理作好经营服务各项管理并督促、检查落实贯彻执行情况。
4、协助总经理调查研究、了解公司经营管理情况并提出处理意见或建议，供总经理决策。
5、做好总经理办公会议和其他会议的组织工作和会议纪录。做好决议、决定等文件的起草、发布。
6、做好企业内外文件的发放、登记、传递、催办、立卷、归档工作。
  任职要求：
 1、形象气质好，管理相关专业。
2、2年以上相关岗位工作经验。
3、工作认真、细致、谨慎，责任心强，有工作激情，善于学习，能迅速掌握与公司业务有关的各种知识。
4、良好的团队协作精神，为人诚实可靠、品行端正；工作有条理性、逻辑性，良好的职业素养和职业操守。
5、很强的计划性和实施执行的能力、具备解决复杂问题的能力、独立工作能力、工作推进能力，能承受较大工作压力。
6、做事踏实细心、严谨自律、有条理性，具有极强的责任心和敬业精神。
7、熟悉常用办公软件，具有一定的文字功底。
工作地址：
上海市杨浦区翔殷路128号上海理工大学国家大学科技园12号楼2楼
查看职位地图
**********
擎声自动化科技(上海)有限公司
公司规模：
20-99人
公司性质：
股份制企业
公司行业：
仪器仪表及工业自动化
公司地址：
上海市杨浦区翔殷路128号上海理工大学国家大学科技园12号楼2楼
**********
电商运营专员
上海涌申电子信息科技有限公司
全勤奖绩效奖金五险一金餐补带薪年假员工旅游定期体检
**********
福利:
全勤奖
绩效奖金
五险一金
餐补
带薪年假
员工旅游
定期体检
**********
职位月薪：4001-6000元/月 
工作地点：上海-静安区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：3人
职位类别：电子商务专员/助理
**********
工作内容：
工作涉及电商平台：淘宝、京东、东方cj等
1、 负责商品的上架、宝贝详情页面优化
2、 负责宝贝排名的优化，提升自然搜索流量
3、 运用淘宝、京东等电商平台各种促销工具，比如满减、满送、优惠券、限时打折、搭配套餐等，设置商品促销，提高成交转化率
4、 负责淘宝、京东、东方购物等站内各种活动的报名和执行，例如淘抢购、淘金币、聚划算、闪购等；
5、 负责平台站内外各种渠道的推广引流
6、 定期对店铺PV、UV、转化率等各项数据进行分析；定期针对推广效果进行跟踪、评估，并提交推广效果的统计分析报表，及时提出营销改进措施
岗位要求：
1、 1年以上店铺运营经验
2、 熟悉淘宝规则，有淘宝网店运营及推广经验，精通数据的分析与运用
3、 熟练使用各平台营销工具
4、具有较强的组织、策划、协调能力，了解消费者心理需求
5、
做六休一.转正五险一金.员工旅游.加班补贴（8：30-17：00上班时间）
有意者请电话咨询或加微信:15026588053 吴小姐

工作地址：
上海市静安区江场西路299弄中铁中环广场6号楼501-502室
查看职位地图
**********
上海涌申电子信息科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
贸易/进出口
公司地址：
上海市闸北区江场西路299弄中铁中环广场6号楼501-502室
**********
现场支援
汉旸(西安)机电安装工程有限公司上海办事处
**********
福利:
**********
职位月薪：6001-8000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：建筑施工现场管理
**********
岗位职责：负责现场化学管道设计，安装跟进，协调处理

任职要求：
1、会韩语优先
2、会CAD制图以及简单的办公室操作软件
3、能适应适当的出差
4、会韩语的优秀半导体化学专业学生也予以考虑

工作地址：
上海市闵行区宜山路2016号合川大厦5楼H室
**********
汉旸(西安)机电安装工程有限公司上海办事处
公司规模：
20-99人
公司性质：
外商独资
公司行业：
大型设备/机电设备/重工业
公司地址：
上海市闵行区宜山路2016号合川大厦5楼H室
查看公司地图
**********
财务经理
总友智能科技(上海)有限公司
五险一金带薪年假节日福利
**********
福利:
五险一金
带薪年假
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：1人
职位类别：财务经理
**********
岗位职责：
1、负责公司资金运作管理、日常财务管理与分析、筹资方略等。
2、负责项目成本核算与控制。
3、按时提供财务报告和必要的财务分析，并确保这些报告可靠、准确。
4、组织制定财务方面的管理制度及有关规定，并监督执行
5、管理与银行、税务、工商及其他机构的关系，并及时办理公司与其之间的业务往来。

任职要求：
1、本科以上，会计学、财务管理专业
2、5年以上财务管理工作经验。具有全面的财务专业知识、账务处理及财务管理经验。
3、精通国家财税法律规范，具备优秀的丰富的财会项目分析处理经验。为人正直、责任心强、作风严谨、工作仔细认真；有良好的职业道德。
4、有较强的语言文字能力和沟通协调能力；有良好的纪律性、团队合作以及开拓创新精神。
5、有IT公司财务经验为优先。
工作地址：
上海市宝山区水产路1269号吴淞口创业园313室
**********
总友智能科技(上海)有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
计算机软件
公司地址：
上海市宝山区水产路1269号吴淞口创业园313室
**********
前台/行政助理
上海东软载波微电子有限公司
五险一金
**********
福利:
五险一金
**********
职位月薪：4000-6000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：前台/总机/接待
**********
岗位职责：
 1、履行前台职能，负责接待和总机接转；
2、负责收发前台传真、邮件；
3、负责订购报刊、杂志，并及时收发；
4、负责与快递公司的联系，收发快递；
5、负责办公用品的采购、盘点、发放管理工作；
6、负责员工的考勤统计；
7、负责为员工预订机票，协助安排业务招待；
8、负责相关行政供应商的维护管理以及行政费用的结帐事宜；
9、负责会议室使用的安排；
10、协助公共区域的环境维护与安全管理，和公共行政设备的日常管理；
11、完成公司交待的其它事务性工作。

任职要求：
1、身高1.60CM以上，形象好，气质佳，普通话标准，掌握一定的商务礼仪；
2、熟练使用常用办公软件（如Word、Excel等），有一定的文字功底；
3、乐观开朗，具有亲和力；
4、吃苦耐劳，有责任心，具较强的服务意识和团队意识，沟通协调能力强，快速反应能力佳。
工作地址：
上海东软载波微电子有限公司
查看职位地图
**********
上海东软载波微电子有限公司
公司规模：
20-99人
公司性质：
合资
公司行业：
电子技术/半导体/集成电路
公司地址：
上海东软载波微电子有限公司
**********
财务副经理
上海沃巴弗电子科技有限公司
**********
福利:
**********
职位月薪：8001-10000元/月 
工作地点：上海-闵行区
发布日期：最新
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：1人
职位类别：财务经理
**********
岗位职责：
1、日常财务核算工作；
2、核算会计报表，财务报告；
3、协助财务总监及财务经理开展财务部内外沟通与协调工作；
4、完成总经理安排的其他工作；

任职要求：
1、持有中级会计师资格证；
2、熟悉经济法及相关法律；
3、有5年以上的财务核算经验；
4、有2年以上的财务管理经验；
5、有较强的沟通协调能力；
6、为人正直，有责任心；
工作地址：
上海市闵行区莲花南路2129弄118-5号
**********
上海沃巴弗电子科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
汽车/摩托车
公司地址：
上海市闵行区莲花南路2129弄118-5号
查看公司地图
**********
财务总监
上海沃巴弗电子科技有限公司
**********
福利:
**********
职位月薪：15001-20000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：5-10年
最低学历：本科
招聘人数：1人
职位类别：财务总监
**********
岗位职责：
1、 组织领导公司的财务、成本、投融资、预算、会计核算及监督、财务分析等方面的工作。
2、 主持建立和完善财务管理制度和相关工作程序，制定和管理税收政策方案及程序。
3、 掌握公司财务状况、经营成果和资金变动情况，拟订或规划资金筹措和资本运作方案。
4、 组织拟定公司年度预算大纲及财务预算，并提交董事会审议。
5、 审核融资计划，报上级批准后组织实施。
6、 组织编制预算、财务收支计划、成本费用计划、信贷计划、财务报告和会计报表等。
7、 负责组织实施内部审计并配合外部审计工作。
8、 参与集团重大投融资决策，优化资本结构和资本配置。
9、 审定财务、会计、审计等财务负责人的任免、晋升、调动、奖惩事项。
10、 协调公司同银行、工商、税务等部门的关系。
岗位要求：
1、 本科以上学历，有注册会计师资格者优先。
2、 10年以上财务管理工作经验，5年以上大型企业财务负责人工作经验，最好有操作企业海外上市工作经验。
3、 熟悉会计、审计、税务、财务管理、会计电算化、相关法律法规。
4、 熟练掌握高级财务管理软件和办公软件。
5、 出色的财务分析、融资和资金管理能力。
6、 良好的组织、协调能力，良好的表达能力和团队合作精神。
任职要求：
1、协助董事长制定公司战略，并主持公司财务战略规划的制定；
2、建立科学、系统符合企业实际情况的财务核算体系和财务监控体系，进行有效的内部控制；
3、制定公司资金运营计划，监督资金管理报告和预、决算，制定公司的会计核算方案和税收筹划方案；
4、参与对重大投资项目和经营活动的风险评估、指导、跟踪和财务风险控制；
5、为企业生产经营、业务发展及对外投资等事项提供专业的财务分析和决策依据； 6、定期与投资方或股东沟通收支状况，维护与投资方或股东的关系；
7、协调公司同银行、工商、税务等政府部门的关系，维护公司利益；
工作地址：
上海市闵行区莲花南路2129弄118-5号
**********
上海沃巴弗电子科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
汽车/摩托车
公司地址：
上海市闵行区莲花南路2129弄118-5号
查看公司地图
**********
总账会计
上海沃巴弗电子科技有限公司
**********
福利:
**********
职位月薪：6001-8000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：5-10年
最低学历：大专
招聘人数：1人
职位类别：财务主管/总帐主管
**********
岗位职责：
1、 负责公司的账务核算工作，根据行业与业务内容按会计准则规定设置会计科目、会计凭证和会计账簿
2、 做好原始凭证的录入工作
3、 对其他岗位会计填制凭证进行审核。
4、 负责应收帐款管理及销售业务会计核算。
5、 正确划分各种费用，能够按不同的要求提供费用数据。
6、 按时完成月、季、年各种会计、统计、税务报表，保证数据的准确性和及时性。
7、 每个月及时做好会计每个阶段的税务申报工作。能规划未来审计所需要的各种资料和前  瞻性。
 8、 保管好财务各种资料。
9、财务部按排的其他工作
任职要求：
1、 会计专业 ，大专以上学历, 5年以上会计核算工作经验，能完成全盘帐务处理。
2、 熟悉使用过金碟财务软件及ERP；熟练操作excel、word等办公软件。
3、 具有较强逻辑分析能力以及数据敏感性，能统筹安排工作。
4、 能准确进行财务核算、审核结转，独立编制财务表报，做出分析
工作地址：
上海市闵行区莲花南路2129弄118-5号
**********
上海沃巴弗电子科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
汽车/摩托车
公司地址：
上海市闵行区莲花南路2129弄118-5号
查看公司地图
**********
电子技术研发部经理
上海沃巴弗电子科技有限公司
五险一金绩效奖金包吃节日福利
**********
福利:
五险一金
绩效奖金
包吃
节日福利
**********
职位月薪：15001-20000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：5-10年
最低学历：大专
招聘人数：1人
职位类别：电子技术研发工程师
**********
岗位职责：

1、完成本部门的日常组织建设和管理工作，协助制定合理的绩效激励政策；
2、带领部门开发团队完成项目开发工作，实时监督项目进展情况，协助处理项目难点；
3、参与公司各传感器设计项目的立项、Spec定义以及设计方案的确定；
4、根据设计任务书要求，完成传感器产品的软件或硬件设计实现；
5、根据工作计划的指导，完成设计与测试，对设计项目的进度和质量负责，并承担具体的技术任务；
6、 对设计、测试中发现的问题进行详细分析和准确定位，与相关人员讨论解决方案；
7、 提出对产品的进一步改进的建议，并评估改进方案是否合理；
8、 协助并提供必要的需求信息至相关部门，配合完成接口功能的确定；配合客户支持部门给予客户必要的技术支持；  
任职资格： 
1、8年以上项目设计经验，电子信息、自动化等相关专业。
2、熟悉单片机及软硬件设计，有多个项目的独立担当经验和开发团队管理经验。
3、较强沟通表达能力、分析与判断能力、组织协调能力、计划制定与控制能力；
4、具有较强抗压能力、环境适用能力、学习能力、团队管理能力。
5、熟悉TS16949质量管理体系或汽车电子电气功能安全标准IS026262者优先；
6、熟悉传感器技术及产品开发者优先；
工作地址：
上海市闵行区莲花南路2129弄118-5号
**********
上海沃巴弗电子科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
汽车/摩托车
公司地址：
上海市闵行区莲花南路2129弄118-5号
查看公司地图
**********
电子维修工程师
上海直川电子科技有限公司
五险一金年底双薪绩效奖金加班补助全勤奖带薪年假定期体检节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
加班补助
全勤奖
带薪年假
定期体检
节日福利
**********
职位月薪：4000-8000元/月 
工作地点：上海-闵行区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：电子/电器维修/保养
**********
岗位职责：
1.负责日常生产中出现的不良品、成品检验中出现的不良品的维修及原因分析;
2.负责客户返厂产品的维修、分析,必要时同客户沟通返厂产品的使用情况,详细解答客户使用过程中的问题;
3.负责填写、整理不良品的送修单，做好维修记录，并对不良统计进行问题分析;
4.协助品质工程师完成一些产品的测试、试验及验证工作
5.协助工艺工程师完成一些功能测试工装的制作、维修及改进工作;
6.完成主管安排的其他的工作;
任职要求：
1.能熟练运用word、excel等常用办公软件。
2.电子专业，有一定的电子线路基础知识，能看懂原理图、PCB图。
3.两年以上的电子产品维修经验，能够熟练使用Altium designer或Protel 99se。
4.工作认真负责,任劳任怨;
5.有团队协作精神,服从工作安排;
6.工作积极上进,有学习精神.

工作地址：
上海闵行区灯辉路1128号
查看职位地图
**********
上海直川电子科技有限公司
公司规模：
100-499人
公司性质：
股份制企业
公司行业：
电子技术/半导体/集成电路
公司主页：
www.zc-sensor.com
公司地址：
上海闵行区灯辉路1128号
**********
产品开发总监
爱义思(上海)科技发展有限公司
创业公司五险一金绩效奖金年终分红交通补助带薪年假节日福利定期体检
**********
福利:
创业公司
五险一金
绩效奖金
年终分红
交通补助
带薪年假
节日福利
定期体检
**********
职位月薪：15001-20000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：5-10年
最低学历：硕士
招聘人数：1人
职位类别：电子技术研发工程师
**********
我们寻找的不仅仅是战斗员，也是指挥员，更是一个志同道合的事业伙伴！只要你有能力、有志向、有良好的世界观、价值观、人生观，那就来吧！
合伙人合作方式：1、技术入股    2、资金加技术入股3、基本薪酬价期权
任职要求：
1、年龄：30-45岁，电子信息工程相关专业，5年以上嵌入式系统开发经验，熟悉Linux/单片机/Dsp；精通C、C++语言编程，学习能力较强，熟悉产品开发流程，精通基于ARM平台开发。熟悉网络通讯编程技术（串行、TCP/IP）、人机交互界面编程，有智能家居、可穿戴设备控制电路及软件编程技术者优先。
2、熟悉数字、模拟电路、32位单片机、PID控制输出、WI-FI通信模块组网、各类传感器应用等多种电路拓扑结构，具有扎实的电路分析理论知识和实际设计经验，和完成技术研发任务的实际经验。
3、熟悉使用通用仪器，能够独立完成电路PCB设计、制作、调试以及测试验证工作。
4、具有强烈的创业欲望，有创新意识，思维敏捷活跃，动手能力强，极端痴迷于人工智能产品。
5、有老板心态，有团队意识、有责任心和吃苦耐劳的敬业精神，认同公司文化、发展方向和价值观。

工作地址：
杨浦区国和路490号金宏商务大厦12层
查看职位地图
**********
爱义思(上海)科技发展有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
互联网/电子商务
公司主页：
www.aceistar.com
公司地址：
杨浦区国和路490号金宏商务大厦12层
**********
音频算法工程师
爱义思(上海)科技发展有限公司
五险一金年底双薪绩效奖金全勤奖带薪年假定期体检员工旅游节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
全勤奖
带薪年假
定期体检
员工旅游
节日福利
**********
职位月薪：6000-12000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：硕士
招聘人数：5人
职位类别：语音/视频/图形开发
**********
岗位职责：
1、声音识别分类的算法验证及实现。
2、对算法持续改进，提高识别率。
任职要求：
具有音频算法研究和开发经验，具备扎实的算法基础；
熟悉声学环境回声消除、噪声抑制、麦克风阵列等技术，具备扎实的算法基础；了解常用语音编码标准。
具有声音识别MFCC、HMM、LPC算法方面的知识和经验，有神经元算法/机器学习方面的经验优先。
熟练使用matlab工具验证算法，掌握android、linux等一种操作系统并可使使用C++/JAVA实现算法。
硕士以上学历，声学、信号处理相关专业，英语6级以上。

工作地址：
杨浦区国和路490号金宏商务大厦12层
查看职位地图
**********
爱义思(上海)科技发展有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
互联网/电子商务
公司主页：
www.aceistar.com
公司地址：
杨浦区国和路490号金宏商务大厦12层
**********
嵌入LINUX软件工程师
爱义思(上海)科技发展有限公司
五险一金年底双薪绩效奖金全勤奖带薪年假定期体检员工旅游节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
全勤奖
带薪年假
定期体检
员工旅游
节日福利
**********
职位月薪：7000-12000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：5人
职位类别：嵌入式软件开发
**********
岗位职责：
1. 根据产品定位，细化软件需求，制定软件功能规格书和软件流程图，完成软件产品的方案选型和开发；
2. 能独立完成软件开发与测试；

任职要求：
能看懂硬件原理图，能使用基本仪器仪表等辅助调试工具；
熟悉嵌入式ARM/MIPS体系结构之一，了解UART、I2C、SPI、USB、以太网等外设的结构和工作原理。
具备软件方面的扎实基础，精通C/C++程序开发语言，有良好的代码编写风格。
熟悉linux操作系统，熟练使用GNU toolchain工具链和buildroot软件开发环境，会编写bash/make等常用脚本文件。掌握uboot、kernel的软件移植，BSP层面的驱动编写及调试。
至少参与过一个完整的嵌入式系统的软件编写及调试工作，熟悉软件开发流程、设计模式、体系结构，代码书写格式规范;
具有良好的沟通能力和团队合作精神，工作积极主动并注重细节。
本科及以上学历，软件、信息、电子等相关专业；
英语良好，能流畅阅读文档。
具有2年及以上电力相关行业或相关工作经验；
有OpenWRT开发经验者优先。
 
工作地址：
杨浦区国和路490号金宏商务大厦12层
查看职位地图
**********
爱义思(上海)科技发展有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
互联网/电子商务
公司主页：
www.aceistar.com
公司地址：
杨浦区国和路490号金宏商务大厦12层
**********
结构工程师
爱义思(上海)科技发展有限公司
创业公司五险一金绩效奖金年终分红餐补定期体检节日福利全勤奖
**********
福利:
创业公司
五险一金
绩效奖金
年终分红
餐补
定期体检
节日福利
全勤奖
**********
职位月薪：6001-8000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：3人
职位类别：机械结构工程师
**********
任职资格
1、熟悉一般电子产品结构设计；
2、熟悉内部堆叠设计方法和理念；
3、熟悉塑胶和常见金属零件的结构设计；
4、熟练掌握PRO/E(Creo),SolidWorks，CATIA, AUTO CAD等任何一种三维设计软件；
5、熟悉塑胶模具、五金件，具备一定的材料、表面加工处理及工艺知识
6、有较强的责任心，良好团队协作能力、沟通能力、谦虚踏实，能吃苦，愿加班。

工作地址：
杨浦区国和路490号金宏商务大厦12层
查看职位地图
**********
爱义思(上海)科技发展有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
互联网/电子商务
公司主页：
www.aceistar.com
公司地址：
杨浦区国和路490号金宏商务大厦12层
**********
设备维修
上海精麟电子科技有限公司
包吃包住绩效奖金加班补助
**********
福利:
包吃
包住
绩效奖金
加班补助
**********
职位月薪：4001-6000元/月 
工作地点：上海-浦东新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：2人
职位类别：机修工
**********
岗位职责：
认真执行各项设备管理制度，服从设备主管的领导，做好班内各项工作。
负责分管机台的维护和日常维修，做好保养，保证设备安全正常运行。
检查督促分管机台操作者正确合理使用好设备、认真执行操作规程、做好设备定期维护保养。
任职要求：初中或初中以上学历，从事一年以上设备维护，听从主管要求，每天维护好设备，确保设备的正常运转
工作地址：
浦东新区航头镇沪南路5583号
查看职位地图
**********
上海精麟电子科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
null
公司地址：
浦东新区航头镇沪南路5583号
**********
仓管
上海精麟电子科技有限公司
绩效奖金包吃通讯补贴员工旅游节日福利
**********
福利:
绩效奖金
包吃
通讯补贴
员工旅游
节日福利
**********
职位月薪：2001-4000元/月 
工作地点：上海-浦东新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：仓库/物料管理员
**********
岗位职责：
负责产成品的入库及出库手续的办理，核对货物与单据的准确性，做好保管工作，并与商务部及生产中心配合货运调度工作；负责原材料出入库单录入输出，并审核生产部门所下施工单及领料单的合理性，防止重复发料、浪费等情况的发生。
任职要求：
掌握用电脑管理仓库工作的基本技能；熟悉仓库的场地、架位和材料；严格按规定管理仓库；具有较强的责任心
工作地址：
浦东新区航头镇沪南路5583号
查看职位地图
**********
上海精麟电子科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
null
公司地址：
浦东新区航头镇沪南路5583号
**********
会计
爱义思(上海)科技发展有限公司
五险一金年底双薪绩效奖金全勤奖带薪年假定期体检员工旅游节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
全勤奖
带薪年假
定期体检
员工旅游
节日福利
**********
职位月薪：5000-6000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：1人
职位类别：会计/会计师
**********
任职要求：
1、财经会计类专业，3年以上会计工作经验
2、熟悉新的税法法规，合理筹划公司税务
3、熟悉高新技术企业加计扣除，熟悉企业所得税汇算清缴，熟悉增值税即征即退。
4、熟悉电商，具有相关会计证书（上岗证和初级职称）
5、熟悉金蝶财务软件及各类办公软件，熟悉开票系统。
6、熟悉一般社保业务。
7、能月内到岗。
工作地址：
上海市杨浦区国和路490号金宏商务大厦
查看职位地图
**********
爱义思(上海)科技发展有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
互联网/电子商务
公司主页：
www.aceistar.com
公司地址：
杨浦区国和路490号金宏商务大厦12层
**********
区域销售经理
上海鸿隆电子技术有限公司
五险一金年底双薪绩效奖金餐补通讯补贴带薪年假定期体检员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
餐补
通讯补贴
带薪年假
定期体检
员工旅游
**********
职位月薪：8001-10000元/月 
工作地点：上海-普陀区
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：1人
职位类别：销售代表
**********
岗位职责：
1、 了解和发掘客户需求，宣传推广公司的产品；
2、 负责销售区域内营销策略的执行完成销售任务；
3、 开拓新市场，发展新客户；
4、 提供市场趋势、需求变化、竞争对手和客户反馈方面的准确信息；
5、 维护及增进已有客户的良好关系； 
6、 直接参与客户的业务谈判及成交；
7、 协调好与其他部门的合作；
8、 广阔的职业能力提升平台，公平的晋升机制，从中挑选优秀员工作为储备干部，担任各区域负责人。
 任职资格：
1、 专科以上学历，具有相关销售经验者优先；
2、 热爱销售工作，性格开朗、坦诚、自信、乐观、思维活跃；
3、 善于沟通、反应灵敏，具有较强的语言表达能力、分析和解决问题的能力；
4、 具备较强的工作积极性和主动服务意识，有较强的责任心、进取心；
5、 能够适应出差；
6、沪籍优先。

交通：地铁3、4、13号线金沙江路站5号出口对面



工作地址：
上海市中山北路3553号伸大厦1915室
**********
上海鸿隆电子技术有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
汽车/摩托车
公司主页：
http://www.honglong.cn
公司地址：
上海市中山北路3553号19楼
查看公司地图
**********
销售工程师
上海齐聪电子有限公司
**********
福利:
**********
职位月薪：4001-6000元/月 
工作地点：上海-闵行区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：3人
职位类别：销售经理
**********
齐聪电子欢迎你!
1.大专以上学历，有行业经验者优先，能力突出者中专学历亦可。
2.勤奋踏实，为人正派，思维敏捷。
3.试用期后，要求能熟练配合公司工作安排。
4.男女不限，户籍不限。
5. 有电话销售经验者优先.
6.上班地点： 上海市莘庄工业区申富路128号2号楼

工作地址：
上海市莘庄工业区申富路128号2号楼109室
查看职位地图
**********
上海齐聪电子有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
互联网/电子商务
公司主页：
www.shqicong.com
公司地址：
上海市莘庄工业区申富路128号2号楼109室
**********
销售助理
上海齐聪电子有限公司
**********
福利:
**********
职位月薪：4001-6000元/月 
工作地点：上海-闵行区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：3人
职位类别：销售经理
**********
齐聪电子欢迎你!
1.大专以上学历，有行业经验者优先，能力突出者中专学历亦可。
2.勤奋踏实，为人正派，思维敏捷。
3.试用期后，要求能熟练配合公司工作安排。
4.男女不限，户籍不限。
5. 有电话销售经验者优先.
6.上班地点：上海市莘庄工业区申富路128号2号楼
工作地址：
上海市莘庄工业区申富路128号
查看职位地图
**********
上海齐聪电子有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
互联网/电子商务
公司主页：
www.shqicong.com
公司地址：
上海市莘庄工业区申富路128号2号楼109室
**********
机电/机械/弱电工程师
上海霄岳通信工程有限公司
五险一金交通补助餐补通讯补贴带薪年假节日福利高温补贴定期体检
**********
福利:
五险一金
交通补助
餐补
通讯补贴
带薪年假
节日福利
高温补贴
定期体检
**********
职位月薪：4001-6000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：3人
职位类别：智能大厦/布线/弱电/安防
**********
职位要求：
1、 年龄20-35岁，电气类、机电类、电子信息类，等相关专业毕业。大专以上学历，一年以上工作经验者优先录用。可接受优秀本科应届生实习。
2、能熟练使用OFFICE套件、AutoCAD、Photoshop等制图软件，有项目现场安装、调试经验者优先。
3、有一定的英文水平，通过大学四、六级者优先；学习、沟通能力强，在试用期间能快速熟悉产品并应用到项目的系统设计中。
4、协调能力强，能胜任项目运做中的招投标、项目执行及售后服务的工作。
5、责任心、执行力强，能适应出差（含境外）、外派驻外等工作安排者优先。
注：人不在上海的，一周内无法到上海来面试的，请勿投简历！


工作地址：
上海市莲花路2080弄50号综合楼4楼
查看职位地图
**********
上海霄岳通信工程有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
通信/电信运营、增值服务
公司地址：
上海市莲花路2080弄50号综合楼4楼
**********
前台
上海强平机器人科技有限公司
五险一金带薪年假员工旅游节日福利
**********
福利:
五险一金
带薪年假
员工旅游
节日福利
**********
职位月薪：3000-5000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：1人
职位类别：教学/教务管理人员
**********
岗位职责：
1. 完成学员考勤，统计学员剩余课时。
2. 更新学员升班、换班资料，协助更新课表。
3. 试听学员登记并协助安排课程。
4. 完成门店人员考勤统计。
5. 独立完成教师KPI数据分析。
6. 统计并分析教师出勤率。
7. 采购物品入库与仓库盘点。
8. 销售合同信息统计与整理。
9. 统计并分析协助销售率。

任职要求：
1. 大专以上学历，文秘类相关专业；
2. 了解前台工作流程，熟练使用各种办公自动化设备；
3. 工作热情积极、细致耐心，具有良好的沟通能力、协调能力，性格开朗，相貌端正，待人热诚；
4. 熟练使用相关办公软件。
    工作地址：
上海市杨浦区殷行路1280号01（东）栋505室强平机器人
**********
上海强平机器人科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
学术/科研
公司主页：
www.qiangping-robot.com
公司地址：
上海市宝山大华、金沙江路真北路、松江大学城
查看公司地图
**********
销售经理
汉唐高强防潮电子(上海)有限公司
全勤奖五险一金带薪年假不加班节日福利员工旅游补充医疗保险绩效奖金
**********
福利:
全勤奖
五险一金
带薪年假
不加班
节日福利
员工旅游
补充医疗保险
绩效奖金
**********
职位月薪：6001-8000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：大专
招聘人数：3人
职位类别：销售经理
**********
任职要求：
1．专科以上学历；
2. 有三年以上电子机械设备相关行业的销售实战经验(电子厂及制造产品销售经验者优先)；
3. 善于沟通，有较强的语言表达能力, 具有敏锐的市场洞察力和准确的客户分析能力,灵活熟练的谈判技巧；具有较强的执行力；
4、具备一定的市场分析及判断能力，良好的客户服务意识；
5、有责任心，开拓能力强，上进心强，勇于不断迎接新挑战能承受较大的工作压力。
  工作地址：
徐汇区宜山路425号光启城908
查看职位地图
**********
汉唐高强防潮电子(上海)有限公司
公司规模：
20-99人
公司性质：
港澳台公司
公司行业：
电子技术/半导体/集成电路
公司地址：
徐汇区宜山路425号908
**********
高薪IT课程顾问/张江/周末双休/8-15k
上海航傲信息科技有限公司
无试用期每年多次调薪绩效奖金带薪年假免费班车员工旅游节日福利
**********
福利:
无试用期
每年多次调薪
绩效奖金
带薪年假
免费班车
员工旅游
节日福利
**********
职位月薪：10001-15000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：培训/招生/课程顾问
**********
改变，就从现在开始，从你开始！请准备好释放你的力量，加入海同科技！众志成城，我们将拥有改变未来的力量！
如果你：
.热爱教育培训事业；
.喜欢与人沟通，拥有出色的沟通技巧和能力；
.渴望丰厚的奖金收入，专注自己的目标并坚持不懈；
.具有良好的团队合作意识，并具有强烈的责任感与客户服务意识；
.想要有更宽阔的长期职业发展；
那，请加入我们！

我们提供：
1.完善的入职培训和职业晋升机制！
2.透明公开优于同行业的薪资水平！
3.享受国家法定节假日，丰厚的节假日福利！
4.带薪年假！
5.丰厚的年终奖！
6.优秀员工奖等等！
7.杰出员工有参与公司股权激励方案的机会，参与年底分红！
 工作时间：9：00—18：00，做五休二，不加班。
欢迎优秀的应届毕业生投递简历！
岗位职责：
1、根据公司提供的客户信息（由市场部门SEM开发），以面对面的形式接待客户，针对客户的背景、程度及要求进行需求分析，运用专业知识，提供客户课程服务咨询；
2、帮助客户建立合理可行的学习计划；
3、根据客户需求进行产品的销售及推广，维护客户关系；
4、准确收集、统计、整理咨询数据，回访潜在客户； 
5、定期参加业务能力提升培训； 
6、协助市场工作。
任职资格：
1、 年龄22-30岁，大专以上学历；
2、 沟通应变能力强，始终保持专业亲切的顾问形象；
3、 有培训行业经验或顾问式销售经验者优先考虑；
4、 欢迎优秀的应届毕业生投递简历！
 【培训体系】
1、 新人阶段：专业的培训师带教+专业营销技能培训+丰富产品知识培训；
2、 成长阶段：每周专业的营销课程培训+职业素养培训。

【职位晋升】
1、 课程顾问—课程顾问主管—课程顾问经理—销售总监—副中心校长—中心校长；
2、公司招募职位以内部竞选员工优先，存在其他部门发展通道。
 【工作地点】
截止到目前，海同科技在上海有多家学习中心，您的工作地点可根据您的住址选择就近安排。我们的中心分布在浦东新区和徐汇区。
我们真诚的邀请你参加我们的团队，你也可以把这个好机会分享给你的朋友们。


工作地址：
浦东新区张衡路180号2号楼2楼
**********
上海航傲信息科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司地址：
上海徐汇区漕溪路
**********
营销主管
上海拓牛智能科技有限公司
五险一金股票期权带薪年假弹性工作创业公司绩效奖金
**********
福利:
五险一金
股票期权
带薪年假
弹性工作
创业公司
绩效奖金
**********
职位月薪：15000-30000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：10人
职位类别：市场营销主管
**********
岗位职责：
1．负责组织产品线上销售营销策略、营销策划、推广方法等
2．负责组织制定网络营销工作计划并组织实施
3．负责组织网络业务推广，执行公司各项政策，完成公司下达的销售目标
4．负责制定公司网络品牌发展战略、品牌建设及市场调研等工作，
5．负责网络营销渠道的建立与规范工作，建设一只有战斗力的销售队伍
6．负责组织客户服务与售后服务支持工作并对服务效果进行评价
7．根据公司市场战略，积极挖掘老客户新需求，并开拓新市场和新客户，发展客户关系，扩大公司业务量
8．负责做好对下属人员的管理工作
9．完成上级临时交办的工作
任职要求：
1. 互联网、市场营销等相关专业专科及以上学历；
2. 3年以上互联网营销的实战经验；精通互联网产品、网络营销及各种推广方式
3. 有营销思维和团队管理能力、能够承受快节奏的销售和管理压力，勇于承担工作重担
4. 具备较强的创新与市场分析、营销、推广能力，项目执行能力，分析与解决问题的能力，具有敏锐的市场洞察力，有很好的协调能力和语言表达能力，有亲和力和感染力，注重团队精神；
5. 熟悉互联网或电子商务公司工作流程，熟悉O2O等新兴行业，；
6. 执行力强，谈判能力强，善于沟通协调；
7. 思维活跃，善于创新，能够不定时给出创新方案，推动销售；

工作地址：
张江国创中心
**********
上海拓牛智能科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
家居/室内设计/装饰装潢
公司地址：
张江国创中心
查看公司地图
**********
软件研发/上市公司/福利待遇好W
上海于晓软件技术有限公司
五险一金年底双薪绩效奖金全勤奖交通补助通讯补贴带薪年假员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
全勤奖
交通补助
通讯补贴
带薪年假
员工旅游
**********
职位月薪：6001-8000元/月 
工作地点：上海-徐汇区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：5人
职位类别：软件工程师
**********
任职要求：
1、热爱计算机行业，计划长期在IT行业内工作发展；
2、好学、细心，喜欢发现事物当中的不足，责任心强；
3、对测试开发感兴趣，零基础应届生者可带薪实训； 
4、协助完成公司项目的测试任务，保证测试的质量；    
5、学历不限，专业不限，有无经验均可。
 工作时间:
9:00-12:00,13:00-18:00，每天工作8小时制，无加班。
 福利待遇：
1、均薪6K,公司提供五险一金（综合医保），五天工作制，享有国家规定的法定假期、带薪年休假等福利待遇；
2、各种奖金及奖励；
3、公司每月，每季度，每年及各节日里定期开展各式各样的文体活动、评优活动，倡导健康向上的企业文化；
 
工作地址：
上海徐汇漕河泾
查看职位地图
**********
上海于晓软件技术有限公司
公司规模：
500-999人
公司性质：
股份制企业
公司行业：
计算机软件
公司地址：
**********
初级电气工程师w
上海于晓软件技术有限公司
年底双薪绩效奖金年终分红定期体检弹性工作带薪年假员工旅游
**********
福利:
年底双薪
绩效奖金
年终分红
定期体检
弹性工作
带薪年假
员工旅游
**********
职位月薪：6001-8000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：3人
职位类别：电气工程师
**********
任职要求；
1.大专及以上学历，专业不限，
2.喜欢计算机网络类的工作，
3.工作态度认真，细心，负责，乐意与身边的人交流，有一定的学习能力和语言表达能力，有较强的团队合作精神，
4.有实际的工作经验或者作品
5.能够尽快入职，长期稳定的工作下去优先考虑。
只要你足够优秀，这些你都可以拥有；成功录用后你将获得的薪资福利；
1.薪酬=基本工资（6K）+绩效+五险+公积金+餐补+房补+交通补助；
2.国家法定假日全休，春节假期在15日左右，享受婚假，产假等福利。
3.丰富的员工活动，每月一次，丰富的下午茶，水果等
4.新员工享受一个月左右的带薪培训，每年年度优秀员工，还可获得一次全程报销费用的旅游机会。
5.高额的年终奖金，每位员工都会有年终奖金，服务公司时间越长，年终奖金会越高，逐年递增
6.享受每周双休，朝九晚六的工作时间，带薪年假，节假日发放大型商场购物卡等。

工作地址：
徐汇漕河泾虹梅路2007号1号楼9楼
查看职位地图
**********
上海于晓软件技术有限公司
公司规模：
500-999人
公司性质：
股份制企业
公司行业：
计算机软件
公司地址：
**********
网络工程师/维护+6k W
上海于晓软件技术有限公司
五险一金年底双薪绩效奖金全勤奖交通补助通讯补贴带薪年假员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
全勤奖
交通补助
通讯补贴
带薪年假
员工旅游
**********
职位月薪：6001-8000元/月 
工作地点：上海-徐汇区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：5人
职位类别：网络工程师
**********
任职要求：
1、学历要求：大专及大专以上学历，专业不限；
2、需具备较强的逻辑思维能力，可接收0基础，项目经理统一安排技术辅导；
3、年龄要求20-30岁，无不良记录，具有良好的团队精神和责任感；
4、对互联网、软件编程感兴趣，想在IT行业深入发展。（喜欢玩游戏者优先）
待遇：
1、假期：朝九晚五，周未双休，法定节假日休息；
2、福利：公司提供住宿，享受五险、带薪年假福利待遇；
3、薪资：转正后7000-8000/月（基本工资+项目提成+补助+奖金）。

工作地址：
上海徐汇漕河泾
查看职位地图
**********
上海于晓软件技术有限公司
公司规模：
500-999人
公司性质：
股份制企业
公司行业：
计算机软件
公司地址：
**********
初级硬件工程师w
上海于晓软件技术有限公司
年底双薪绩效奖金年终分红定期体检弹性工作带薪年假员工旅游
**********
福利:
年底双薪
绩效奖金
年终分红
定期体检
弹性工作
带薪年假
员工旅游
**********
职位月薪：6001-8000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：3人
职位类别：硬件工程师
**********
岗位职责：
1.有无相关工作经验均可，可接收应届生；
2.有良好的沟通能力和表达能力；
3.学习能力强，有良好逻辑思维能力；
任职要求：
1、可接受应届毕业生，实习生；
2、相关专业优先考虑；
3、有责任感，良好的团队协助精神；
4、有无经验均可。一经录用，待遇优厚！
5、20-30岁，超龄勿扰。不符合条件者勿扰（非中介，非保险）
条件优秀者可相应放宽。入职后签订劳动就业合同，五险一金+双休法定假日,有良好的晋升空间

工作地址：
徐汇漕河泾虹梅路2007号1号楼9楼
查看职位地图
**********
上海于晓软件技术有限公司
公司规模：
500-999人
公司性质：
股份制企业
公司行业：
计算机软件
公司地址：
**********
工业工程师/五险一金助理岗W
上海于晓软件技术有限公司
五险一金年底双薪绩效奖金全勤奖交通补助通讯补贴带薪年假员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
全勤奖
交通补助
通讯补贴
带薪年假
员工旅游
**********
职位月薪：6001-8000元/月 
工作地点：上海-徐汇区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：5人
职位类别：工业工程师
**********
职位管理：
1.灵活应变，协助部门工程师完成工作；
2.学习能力强，工作热情高，富有责任感，工作认真、细致、敬业，责任心强；
3.20-30岁之间，无性别要求；
4.理工科相关专业可优先考虑；

公司福利：
1、外地员工可提供住宿，工作时间早9-晚5，双休
2、工作时间：早9-晚5，双休，法定假日休息，带薪年假
3、签订正式劳动合同，从试用期开始缴纳五险一金；
4、日常补贴（话费、工作餐、交通费补贴）;
5、正式员工享受十三薪及年终奖；
6、待遇：实习工资面议，转正6k起；
7、每年享受国家规定的带薪年假、法定节假日等福利；

工作地址：
上海徐汇漕河泾
查看职位地图
**********
上海于晓软件技术有限公司
公司规模：
500-999人
公司性质：
股份制企业
公司行业：
计算机软件
公司地址：
**********
软件测试/IT方向+6k起W
上海于晓软件技术有限公司
五险一金年底双薪绩效奖金全勤奖交通补助通讯补贴带薪年假员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
全勤奖
交通补助
通讯补贴
带薪年假
员工旅游
**********
职位月薪：6001-8000元/月 
工作地点：上海-黄浦区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：5人
职位类别：软件测试
**********
岗位职责：
1. 根据测试用例的要求对软件进行功能性测试并记录bug并提交
2.将bug整理出测试文档并提交给相关人员，实时跟踪bug。
3.编写测试报告，对整个项目进行维护跟踪处
 任职要求：
①应往届理工科毕业生，对IT行业不感兴趣者，勿投；
②大学所学专业：计算机（网络）、电子信息、软件工程、（电气）自动化、测控、通信、机电等。有计算机语言者优先；
③接受转行求职人员，由项目经理指导工作，但要求勤奋好学，积极主动；
④有无经验均可；
福利待遇：
①入职即缴纳五险一金；
②带薪休假（年假，婚假，丧假，病假，培训假等）
②丰富的业余集体活动（拓展，旅游，聚餐，年会等）；

工作地址：
上海市黄浦区
查看职位地图
**********
上海于晓软件技术有限公司
公司规模：
500-999人
公司性质：
股份制企业
公司行业：
计算机软件
公司地址：
**********
IT技术助理/双休+五险一金 W
上海于晓软件技术有限公司
五险一金年底双薪绩效奖金全勤奖交通补助通讯补贴带薪年假员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
全勤奖
交通补助
通讯补贴
带薪年假
员工旅游
**********
职位月薪：6001-8000元/月 
工作地点：上海-黄浦区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：5人
职位类别：IT技术文员/助理
**********
任职要求：
1、大专及以上学历，专业不限，有工作经验者优先；
2、对互联网软件行业有较大的求知欲及良好的学习精神，想在软件行业发展；
3、前期老带新，要求能吃苦耐劳，协助做辅助性工作；

薪资福利：
1、转正底薪6000-8000，7.5小时制，周末双休；
2、国家法定五险一金及带薪假期；
3、办公环境舒适，地理位置优越，地铁口及公交站附近；
4、公司定期组织员工旅游及户外活动；
公司并且给应往届生提供实训岗位。

工作地址：
上海市黄浦区
查看职位地图
**********
上海于晓软件技术有限公司
公司规模：
500-999人
公司性质：
股份制企业
公司行业：
计算机软件
公司地址：
**********
软件测试（五险一金+双休）W
上海于晓软件技术有限公司
五险一金年底双薪绩效奖金全勤奖交通补助通讯补贴带薪年假员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
全勤奖
交通补助
通讯补贴
带薪年假
员工旅游
**********
职位月薪：6001-8000元/月 
工作地点：上海-黄浦区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：5人
职位类别：软件测试
**********
安装测试软件，试运行该软件，在运行过程中发现软件存在的错误及缺陷，及时反馈给相关技术部门。
任职资格：
1、20～30岁之间，有无经验皆可；
2、全日制大专及以上学历，理工科优先考虑；
3、看好互联网行业，能够长期稳定发展；
 福利待遇：
有竞争力的薪酬：正式入职后均薪7K,外加项目提成与绩效；
完善的培训体系：优秀员工有机会获得高阶培训，有良好的晋升空间；
完整的福利制度：做五休二、五险一金、法定节假日、带薪病假、带薪年假、年终奖等；
 发展方向：软件测试、游戏测试、系统测试、功能测试、软件测试架构设计师、测试经理、高级软件测试工程师等等；

工作地址：
上海市黄浦区
查看职位地图
**********
上海于晓软件技术有限公司
公司规模：
500-999人
公司性质：
股份制企业
公司行业：
计算机软件
公司地址：
**********
游戏测试（五险一金+双休）W
上海于晓软件技术有限公司
五险一金年底双薪绩效奖金全勤奖交通补助通讯补贴带薪年假员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
全勤奖
交通补助
通讯补贴
带薪年假
员工旅游
**********
职位月薪：6001-8000元/月 
工作地点：上海-黄浦区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：5人
职位类别：游戏测试
**********
职位条件：
1、喜欢计算机，互联网，IT等行业， 想获得一份长期稳定且有发展前景的工作；
2、细心，有强烈的责任心和上进心；
3、理工类专科优先，自觉能定性较强者；
4、学习能力强，有较强的沟通能力，有较强的理解，逻辑分析能力，能够理解以及处理复杂逻辑；
5、有较强的团队合作精神，有责任心；
6、年龄20到30岁，超龄勿扰；
薪资待遇：
1、试用期一个月，试用期综合工资5000，转正后综合工资6000-9500 （可面议）；
2、公司缴纳五险一金，签订正式合同
3、逢年过节发放节日礼品，聚餐等；
4、按季度组织省外出旅游等；
5、定期体检等；
6、按季度评比出优秀员工进行培养和加薪（必要时晋升）；
7、公司工作环境优雅、氛围好，同事关系融洽，生日派对、聚餐等活动丰富；
8、公司注重员工培养，给予晋升机会，管理层主要员工中培养、提拔
9.高额的年终奖金，每位员工都会有年终奖金，服务公司时间越长，年终奖金会越高，逐年递增

工作地址：
上海市黄浦区
查看职位地图
**********
上海于晓软件技术有限公司
公司规模：
500-999人
公司性质：
股份制企业
公司行业：
计算机软件
公司地址：
**********
硬件测试/双休+五险一金W
上海于晓软件技术有限公司
五险一金年底双薪绩效奖金全勤奖交通补助通讯补贴带薪年假员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
全勤奖
交通补助
通讯补贴
带薪年假
员工旅游
**********
职位月薪：6001-8000元/月 
工作地点：上海-黄浦区
发布日期：2018-03-10 15:18:00
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：5人
职位类别：硬件工程师
**********
任职资格：
1、大专及大专以上学历，经验专业不限，年龄20-30岁，可接受实习生。
    2、意向从事IT方面工作优先。
    3、熟悉互联网络，熟练使用网络交流工具和各种办公软件；
4、具有良好学习能力和团队合作精神。
 福利待遇：
1、岗前实训
入职参加岗前实训，掌握岗位必须具备的工作技能。
2、五险一金，含交补、话补、加班补助；
3、员工旅游+每季度员工聚会+员工生日会+节日礼物，丰富的业余集体活动（拓展，旅游，聚餐，年会等）；
4、每年享受国家规定的带薪年假、法定节假日等福利；
5、丰富的企业文化活动，打造快乐活力的工作氛围；
工作时间：
双休，朝九晚六，中午休息一个小时，带薪年假，国家法定节假日正常休息。

工作地址：
上海市黄浦区云南北路59号六合大厦15楼
查看职位地图
**********
上海于晓软件技术有限公司
公司规模：
500-999人
公司性质：
股份制企业
公司行业：
计算机软件
公司地址：
**********
移动通信/双休+五险一金W
上海于晓软件技术有限公司
五险一金年底双薪绩效奖金全勤奖交通补助通讯补贴带薪年假员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
全勤奖
交通补助
通讯补贴
带薪年假
员工旅游
**********
职位月薪：6001-8000元/月 
工作地点：上海-黄浦区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：5人
职位类别：移动通信工程师
**********
任职要求：
1、具备一定的计算机基础；
2、良好语言表达和沟通能力，具备团队思维；
3、有较好的沟通、协调能力和分析能力；细致、负责的工作态度；
入职后签订劳动就业合同，五险一金+双休法定假日,有良好的晋升空间
 福利待遇：
五险一金、过节礼物、定期部门活动
双休+法定节假日正常放假、8小时工作制、带薪年假、婚假等

工作地址：
上海市黄浦区
查看职位地图
**********
上海于晓软件技术有限公司
公司规模：
500-999人
公司性质：
股份制企业
公司行业：
计算机软件
公司地址：
**********
机电专业不限经验/开发+6k起 w
上海于晓软件技术有限公司
五险一金年底双薪绩效奖金全勤奖交通补助通讯补贴带薪年假员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
全勤奖
交通补助
通讯补贴
带薪年假
员工旅游
**********
职位月薪：6001-8000元/月 
工作地点：上海-徐汇区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：5人
职位类别：机电工程师
**********
岗位要求:
1.大专及以上学历，理工科相关专业，20-30岁之间;
2.工作积极主动，学习能力强，具有较强的执行力和团队协作精神。
公司福利：
1、薪酬体系：薪酬=基本工资+绩效+项目提成+生活补贴（均薪7K）；
2、健全的福利制度：五险一金（养老、医疗、事业、生育、工伤）、餐补、通讯补贴等；
3、员工活动：每年必备集体旅行，年会（各种福利发放），公司出资定期进行团队建设；
4、节假日福利：春节，端午节，中秋节、春节、结婚礼金，生日慰问，夏日高温福利等。
5、年终奖：年终双薪绝对不是问题，更有年终分红、期权等着你们来拿。
6、培训：不仅有外部专业大师丰富你的知识，更有内部交流分享机制；
7、晋升机制：在这不看你的年纪，不论你的专业，只要你勤奋好学，积极上进，一切职位皆有可能！

工作地址：
上海徐汇漕河泾
查看职位地图
**********
上海于晓软件技术有限公司
公司规模：
500-999人
公司性质：
股份制企业
公司行业：
计算机软件
公司地址：
**********
日语销售助理
上海中卡智能卡有限公司
**********
福利:
**********
职位月薪：4001-6000元/月 
工作地点：上海-浦东新区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：销售行政专员/助理
**********
岗位职责：
1、负责跟踪订单执行，在客户与工厂之间传递信息。
2、完成客户的接待工作。
3、整理部门销售文档和客户资料，以及其他上级交代的任务。
任职要求：
1、大专以上学历，日语二级及以上（有二级日语证书），听说读写熟练。
2、熟练应用办公软件Word、Excel、PowerPoint。
3、性格外向，表达能力强，具有较强的沟通能力和亲和力。
4、具备良好的客户服务意识，不惧挑战，敬业、勤恳，具有团队精神。
工作地址：
上海市浦东新区川沙路6999号川沙国际精工园B区19号楼
查看职位地图
**********
上海中卡智能卡有限公司
公司规模：
100-499人
公司性质：
合资
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.chinacardgroup.com.cn
公司地址：
上海市浦东新区川沙路6999号川沙国际精工园B区19号楼
**********
储备技术专员7000(职位编号：7)
上海博为峰软件技术股份有限公司
五险一金年底双薪绩效奖金交通补助餐补通讯补贴带薪年假定期体检
**********
福利:
五险一金
年底双薪
绩效奖金
交通补助
餐补
通讯补贴
带薪年假
定期体检
**********
职位月薪：6001-8000元/月 
工作地点：上海-徐汇区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：5人
职位类别：系统测试
**********
任职资格：
1、20～30岁之间，全日制大专及以上学历；
2、计算机或相关专业（理工科为主），接纳无经验但好学的人才； 
3、具有较强的逻辑分析能力和学习能力，良好的沟通表达能力，敏锐的观察力，较强的团队协作意识； 
公司福利：
1、薪酬体系：薪酬=基本工资+绩效+项目提成+生活补贴（均薪6K）；
2、健全的福利制度：五险一金（养老、医疗、事业、生育、工伤）、餐补、通讯补贴等；
3、员工活动：每年必备集体旅行，年会（各种福利发放），公司出资定期进行团队建设；
4、节假日福利：春节，端午节，中秋节、春节、结婚礼金，生日慰问，夏日高温福利等。
5、年终奖：年终双薪绝对不是问题，更有年终分红、期权等着你们来拿。
6、培训：不仅有外部专业大师丰富你的知识，更有内部交流分享机制；
7、奖励晋升机制：在这不看你的年纪，只要你勤奋好学，积极上进，一切职位皆有可能！

工作地址：
上海徐汇漕河泾虹梅路2007号1号楼9楼
**********
上海博为峰软件技术股份有限公司
公司规模：
500-999人
公司性质：
上市公司
公司行业：
计算机软件
公司地址：
上海市黄浦区云南北路59号六合大厦1510室
**********
工业工程师（技术稳定岗）(职位编号：1)
上海博为峰软件技术股份有限公司
五险一金年底双薪绩效奖金全勤奖交通补助通讯补贴带薪年假员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
全勤奖
交通补助
通讯补贴
带薪年假
员工旅游
**********
职位月薪：6001-8000元/月 
工作地点：上海-徐汇区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：4人
职位类别：工业工程师
**********
岗位职责：
1、对计算机感兴趣，并想进入该行业进行长远发展；
2、好学，细心，有良好的逻辑思维能力及分析能力；
3、工作态度积极认真，愿意从实习开始；
4、听从上级安排，认真贯彻上级安排的相关工作。
 任职资格：
1、大专及以上学历，相关专业优先考虑；
2、从事该行业1年以上，可接受应届毕业生，实习生；
3、责任心强，学习能力强，具备良好的团队协助精神；
4、热爱该行业，并打算在此行业长期发展。
  薪资待遇：
1、在成熟的运营管理机制下，为在职员工提供入职前带薪培训；
2、试用期：3个月，优秀者可提前转正；
3、正式入职可享有月薪不低于5000-8000元/月收入，三年内平均年薪十万以上；
4、公司工作环境优雅、氛围好，同事关系融洽，生日派对、聚餐等活动丰富；
5、公司注重员工培养，给予晋升机会，管理层在主要员工中培养、提拔。
    工作时间：早9：00-18：00 ，双休，提供住宿，法定假日按国家规定执行！

工作地址：
上海徐汇漕河泾虹梅路2007号1号楼9楼
**********
上海博为峰软件技术股份有限公司
公司规模：
500-999人
公司性质：
上市公司
公司行业：
计算机软件
公司地址：
上海市黄浦区云南北路59号六合大厦1510室
**********
电气工程师（开发方向）(职位编号：7)
上海博为峰软件技术股份有限公司
五险一金年底双薪绩效奖金交通补助餐补通讯补贴带薪年假定期体检
**********
福利:
五险一金
年底双薪
绩效奖金
交通补助
餐补
通讯补贴
带薪年假
定期体检
**********
职位月薪：6001-8000元/月 
工作地点：上海-徐汇区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：5人
职位类别：电气工程师
**********
任职要求：
1：正规院校毕业，大专及以上学历，专业不限.
2：思路清晰，善于思考，有良好的逻辑思维能力，能独立分析和解决问题，具有创新意识，为人正直，责任心强 ，有良好的团队协作精神和服务意识。
3：工作认真细心负责，有良好的学习能力和沟通及表达能力，会简单的电脑操作基础，对计算机感兴趣，热爱IT行业者优先。
4：有无经验均可，欢迎应届毕业生加入。


福利待遇：
工作时间：周一至周五 9:00-18:00，周末双休，国家法定节假日放假。
1、试用期一个月，试用期综合工资5000，转正后综合工资6000-7500 （可面议）；
2、公司缴纳五险一金，签订正式合同
3、逢年过节发放节日礼品，聚餐等；
4、按季度组织省外出旅游等；
5、定期体检等；
6、按季度评比出优秀员工进行培养和加薪（必要时晋升）；
7、公司工作环境优雅、氛围好，同事关系融洽，生日派对、聚餐等活动丰富；
8、公司注重员工培养，给予晋升机会，管理层主要员工中培养、提拔
9.高额的年终奖金，每位员工都会有年终奖金，服务公司时间越长，年终奖金会越高，逐年递增
 
工作地址：
上海徐汇漕河泾虹梅路2007号1号楼9楼
**********
上海博为峰软件技术股份有限公司
公司规模：
500-999人
公司性质：
上市公司
公司行业：
计算机软件
公司地址：
上海市黄浦区云南北路59号六合大厦1510室
**********
技术助理（上市公司）(职位编号：7)
上海博为峰软件技术股份有限公司
五险一金年底双薪绩效奖金交通补助餐补通讯补贴带薪年假定期体检
**********
福利:
五险一金
年底双薪
绩效奖金
交通补助
餐补
通讯补贴
带薪年假
定期体检
**********
职位月薪：6001-8000元/月 
工作地点：上海-黄浦区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：4人
职位类别：施工员
**********
岗位要求:
1.大专及以上学历，理工科相关专业，20-30岁之间;
2.工作积极主动，学习能力强，具有较强的执行力和团队协作精神。
公司福利：
1、薪酬体系：薪酬=基本工资+绩效+项目提成+生活补贴（均薪7K）；
2、健全的福利制度：五险一金（养老、医疗、事业、生育、工伤）、餐补、通讯补贴等；
3、员工活动：每年必备集体旅行，年会（各种福利发放），公司出资定期进行团队建设；
4、节假日福利：春节，端午节，中秋节、春节、结婚礼金，生日慰问，夏日高温福利等。
5、年终奖：年终双薪绝对不是问题，更有年终分红、期权等着你们来拿。
6、培训：不仅有外部专业大师丰富你的知识，更有内部交流分享机制；
7、晋升机制：在这不看你的年纪，不论你的专业，只要你勤奋好学，积极上进，一切职位皆有可能！

工作地址：
上海市黄浦区云南北路59号六合大厦1510室
**********
上海博为峰软件技术股份有限公司
公司规模：
500-999人
公司性质：
上市公司
公司行业：
计算机软件
公司地址：
上海市黄浦区云南北路59号六合大厦1510室
**********
名企/软件测试/6k(职位编号：10)
上海博为峰软件技术股份有限公司
五险一金年底双薪绩效奖金加班补助全勤奖交通补助餐补通讯补贴
**********
福利:
五险一金
年底双薪
绩效奖金
加班补助
全勤奖
交通补助
餐补
通讯补贴
**********
职位月薪：6001-8000元/月 
工作地点：上海-黄浦区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：4人
职位类别：软件测试
**********
岗位职责：
安装测试软件，试运行该软件，在运行过程中发现软件存在的错误及缺陷，及时反馈给相关技术部门。
任职资格：
1、20～30岁之间，有无经验皆可；
2、全日制大专及以上学历，理工科优先考虑；
3、看好互联网行业，能够长期稳定发展；
福利待遇：
1、正式入职后均薪6K，外加五险一金及项目提成，交通补贴；
2、公司将为新员工提供全面系统的零基础实训，提升员工的专业技能。
3、朝九晚六，周末双休，无加班。国家法定节假日带薪休假；
                                                                                                                                    发展方向：软件测试、游戏测试、系统测试、功能测试、软件测试架构设计师、测试经理、高级软件测试工程师等等；
面试流程：收到面试通知—带好相关证件前往面试—到公司进行笔试{基础逻辑测试及基础测试（无专业基础不必做）}—部门负责人进行最终面谈—通过即可入职

工作地址：
上海市黄浦区云南北路59号六合大厦1510室
**********
上海博为峰软件技术股份有限公司
公司规模：
500-999人
公司性质：
上市公司
公司行业：
计算机软件
公司地址：
上海市黄浦区云南北路59号六合大厦1510室
**********
系统管理员（7000起）(职位编号：4)
上海博为峰软件技术股份有限公司
五险一金年底双薪绩效奖金交通补助餐补通讯补贴带薪年假定期体检
**********
福利:
五险一金
年底双薪
绩效奖金
交通补助
餐补
通讯补贴
带薪年假
定期体检
**********
职位月薪：6001-8000元/月 
工作地点：上海-徐汇区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：3人
职位类别：系统管理员
**********
职位管理：
1.灵活应变，协助部门工程师完成工作；
2.学习能力强，工作热情高，富有责任感，工作认真、细致、敬业，责任心强；
3.20-30岁之间，无性别要求；
4.计算机相关专业可优先考虑；
公司福利：
1、外地员工可提供住宿，工作时间早9-晚5，双休
2、工作时间：早9-晚5，双休，法定假日休息，带薪年假
3、签订正式劳动合同，从试用期开始缴纳五险一金；
4、日常补贴（话费、工作餐、交通费补贴）;
5、正式员工享受十三薪及年终奖；
6、待遇：实习工资面议，转正6k起；
7、每年享受国家规定的带薪年假、法定节假日等福利；
 
工作地址：
上海徐汇漕河泾虹梅路2007号1号楼9楼
**********
上海博为峰软件技术股份有限公司
公司规模：
500-999人
公司性质：
上市公司
公司行业：
计算机软件
公司地址：
上海市黄浦区云南北路59号六合大厦1510室
**********
技术支持（零基础可培养）(职位编号：13)
上海博为峰软件技术股份有限公司
年底双薪绩效奖金年终分红交通补助餐补通讯补贴带薪年假定期体检
**********
福利:
年底双薪
绩效奖金
年终分红
交通补助
餐补
通讯补贴
带薪年假
定期体检
**********
职位月薪：6001-8000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：3人
职位类别：质量管理/测试工程师
**********
岗位说明：
针对新员工专业不符及理论知识项目经验不足情况，公司会提供零基础岗前实训，主要是软件测试、 开发，每周双休；实训结束后正式转正上岗。任职要求：
1.应往届理工科毕业生，有志于在IT行业发展。
2.计算机（网络）、电子信息、软件工程、机械 （电气）自动化、测控、生仪、机电等专业
3. 能够尽快入职，长期稳定的工作
4. 条件优秀者可相应放宽。不符合条件者勿扰（非中介，非保险）
5. 大专及以上学历，年龄18-30岁。不符者请勿投 
入职后签订劳动就业合同，入职薪资 5-8k，入职后公司提供五险一金、十三薪、项目奖金、年终奖金、旅游、培训、带薪年假等;五险一金+双休法定假日,有良好的晋升空间。
 6.20-30岁超龄勿扰。男女不限。
上班时间：9:00-17:30 做五休二 公司不提倡加班

工作地址：
上海徐汇漕河泾虹梅路2007号1号楼9楼
**********
上海博为峰软件技术股份有限公司
公司规模：
500-999人
公司性质：
上市公司
公司行业：
计算机软件
公司地址：
上海市黄浦区云南北路59号六合大厦1510室
**********
质量管理员(专科即可)(职位编号：5)
上海博为峰软件技术股份有限公司
五险一金年底双薪绩效奖金交通补助餐补通讯补贴带薪年假定期体检
**********
福利:
五险一金
年底双薪
绩效奖金
交通补助
餐补
通讯补贴
带薪年假
定期体检
**********
职位月薪：6001-8000元/月 
工作地点：上海-徐汇区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：5人
职位类别：汽车质量管理/检验检测
**********
岗位要求:
1.大专及以上学历，理工科相关专业，20-30岁之间;
2.工作积极主动，学习能力强，具有较强的执行力和团队协作精神。
公司福利：
1、薪酬体系：薪酬=基本工资+绩效+项目提成+生活补贴（均薪7K）；
2、健全的福利制度：五险一金（养老、医疗、事业、生育、工伤）、餐补、通讯补贴等；
3、员工活动：每年必备集体旅行，年会（各种福利发放），公司出资定期进行团队建设；
4、节假日福利：春节，端午节，中秋节、春节、结婚礼金，生日慰问，夏日高温福利等。
5、年终奖：年终双薪绝对不是问题，更有年终分红、期权等着你们来拿。
6、培训：不仅有外部专业大师丰富你的知识，更有内部交流分享机制；
7、晋升机制：在这不看你的年纪，不论你的专业，只要你勤奋好学，积极上进，一切职位皆有可能！

工作地址：
上海徐汇漕河泾虹梅路2007号1号楼9楼
**********
上海博为峰软件技术股份有限公司
公司规模：
500-999人
公司性质：
上市公司
公司行业：
计算机软件
公司地址：
上海市黄浦区云南北路59号六合大厦1510室
**********
测试助理（周末双休+6k）(职位编号：7)
上海博为峰软件技术股份有限公司
五险一金年底双薪绩效奖金交通补助餐补通讯补贴带薪年假定期体检
**********
福利:
五险一金
年底双薪
绩效奖金
交通补助
餐补
通讯补贴
带薪年假
定期体检
**********
职位月薪：6001-8000元/月 
工作地点：上海-黄浦区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：3人
职位类别：软件测试
**********
任职要求：
1、热爱计算机行业，计划长期在IT行业内工作发展；
2、好学、细心，喜欢发现事物当中的不足，责任心强；
3、对测试开发感兴趣，零基础应届生者可带薪实训； 
4、协助完成公司项目的测试任务，保证测试的质量；    
5、学历不限，专业不限，有无经验均可。
 工作时间:
9:00-12:00,13:00-18:00，每天工作8小时制，无加班。
福利待遇：
1、均薪6K,公司提供五险一金（综合医保），五天工作制，享有国家规定的法定假期、带薪年休假等福利待遇；
2、各种奖金及奖励；
3、公司每月，每季度，每年及各节日里定期开展各式各样的文体活动、评优活动，倡导健康向上的企业文化；

工作地址：
上海市黄浦区云南北路59号六合大厦1510室
**********
上海博为峰软件技术股份有限公司
公司规模：
500-999人
公司性质：
上市公司
公司行业：
计算机软件
公司地址：
上海市黄浦区云南北路59号六合大厦1510室
**********
课程顾问
上海强平机器人科技有限公司
创业公司每年多次调薪五险一金年底双薪绩效奖金股票期权弹性工作员工旅游
**********
福利:
创业公司
每年多次调薪
五险一金
年底双薪
绩效奖金
股票期权
弹性工作
员工旅游
**********
职位月薪：10001-15000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：4人
职位类别：销售代表
**********
岗位职责：
1、跟踪销售机会，预约客户到门店体验；
2、与客户洽谈，并促进签约；
3、跟踪到店未签约客户，争取客户的再次光顾签约；
4、维护现有客户关系，实现续约；
5、开拓合作渠道，发展更多的销售机会。

任职要求：
1、形象良好，热情大方，沟通能力强；
2、热爱销售工作，喜欢与人打交道；
3、目的性强，有韧性，抗挫折、抗打击能力强；
4、渴望实现目标，喜欢挑战自己，赚更多的钱；
5、善于学习，了解公司及产品的特点，熟悉产品与商务条款，清楚与竞争对手的差异性；
5、善于倾听和思考，发掘客户的痛点，为客户建议课程方案；
6、有较强的组织性、纪律性；
7、能够适应服务行业的工作时间安排（周六、日需要上班，休息日在周间）

工作地址：
上海市宝山大华、金沙江路真北路、松江大学城
查看职位地图
**********
上海强平机器人科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
学术/科研
公司主页：
www.qiangping-robot.com
公司地址：
上海市宝山大华、金沙江路真北路、松江大学城
**********
课程顾问
上海强平机器人科技有限公司
五险一金绩效奖金年终分红带薪年假节日福利
**********
福利:
五险一金
绩效奖金
年终分红
带薪年假
节日福利
**********
职位月薪：5000-10000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：不限
招聘人数：5人
职位类别：教学/教务管理人员
**********
工作职责：
1. 独立完成月度课程销售任务，跟进课程费用的支付流程。
2. 积极推进在读学员的推荐转介绍，并达成课程销售。
3. 根据公司的活动策划，组织并实施活动推广工作。
4. 接听家长咨询电话并邀约来访、接待Walk-in来访家长，为家长提供专业的课程体系讲解，设计符合学生所需要的专业化、个性化的课程体系，并达成课程销售。
5. 负责与客户进行电话沟通，预约意向学员参加校区公开体验课，并达成课程销售。
6. 与学生建立良好的关系，帮助学生完成学习目标。维护学员数据库。
7. 保持与现有客户的沟通，做好后期服务维系，并做好续费工作。

职位要求：
1.沟通能力强，喜欢小孩，愿意与孩子沟通；
2.年龄在22-30岁，大专以上学历，可视情况调整；
3.有培训机构或外企销售相关岗位相关工作经验者优先；

【薪资福利】
 该职位全职工作属于公司正式员工编制，一经录用将享有
1、 每三个月通过业绩考核者，晋升管道畅通
2、 签订正式劳动合同，完整合规的社会保险和住房公积金
3、 员工旅游+员工聚会+节日礼物
4、 每年享受国家规定的带薪年假、法定节假日等福利

 工作地点：
大华店（总部）：上海市宝山区大华一路210号嘉年华大厦701
江湾城店：殷行路1280号01（东）栋505室强平机器人
南方商城店：古方路18号南方休闲商务大厦302
118广场店：普陀区金沙江路1685号118广场3楼
工作地址：
上海市宝山区大华一路210号嘉年华大厦701
查看职位地图
**********
上海强平机器人科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
学术/科研
公司主页：
www.qiangping-robot.com
公司地址：
上海市宝山大华、金沙江路真北路、松江大学城
**********
外贸业务员
上海翊科精密挤出技术有限公司
五险一金年底双薪绩效奖金年终分红通讯补贴员工旅游节日福利股票期权
**********
福利:
五险一金
年底双薪
绩效奖金
年终分红
通讯补贴
员工旅游
节日福利
股票期权
**********
职位月薪：6001-8000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：2人
职位类别：业务拓展专员/助理
**********
岗位职责：
1.通过第三方专业平台如Alibaba,google 发布公司生产的各种医疗导管产品信息，
   回复客户的询盘，为客户提供各种专业的导管解决方案最终达成合作目的。
2.参加亚洲，欧洲和美洲的各种专业展会，在展会上推广公司产品和形象，建立相应的
   销售渠道和服务机制，提供更好的客户产品体验。
任职条件：
1）  本科以上学历，国际贸易或高分子材料等相关专业；
2）  相貌端正，熟悉国际市场业务拓展及国际贸易流程；
3）  英语6级以上，英文书写、口语优异。
4）  优良的沟通能力、积极的开拓意识和极强的团队协作精神；
5）  严谨的工作态度，积极主动，高度的工作责任感与独立完成工作的能力。
6） 待遇底薪（6000+）+高比例提成+提供住宿，五险一金。
   工作地址：
上海市浦东新区瑞庆路528号24幢乙一层
**********
上海翊科精密挤出技术有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
www.ecoprecision.com.cn
公司地址：
上海市浦东新区瑞庆路528号24幢乙一层
查看公司地图
**********
课程顾问（做五休二/年薪20k+/B轮融资）
上海航傲信息科技有限公司
无试用期每年多次调薪绩效奖金带薪年假免费班车员工旅游节日福利
**********
福利:
无试用期
每年多次调薪
绩效奖金
带薪年假
免费班车
员工旅游
节日福利
**********
职位月薪：10001-15000元/月 
工作地点：上海-浦东新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：5人
职位类别：培训/招生/课程顾问
**********
岗位职责：
1、根据公司提供的客户信息（由市场部门SEM开发），针对客户的背景、程度及要求进行需求分析，运用专业知识，提供客户课程服务咨询；
2、帮助客户建立合理可行的学习计划；
3、根据客户需求进行产品的销售及推广，维护客户关系；
4、准确收集、统计、整理咨询数据，回访潜在客户； 
5、定期参加业务培训； 
6、协助市场工作。 

任职资格： 
1、年龄22－30岁，大专以上学历，形象佳，； 
2、有一年以上教育培训行业工作经验，或有一年以上销售经验，或有志向在教育培训行业发展；
3、热爱教育事业和销售岗位；
4、热情、真诚、耐心，充满朝气，有高度的上进心和责任感； 
5、普通话标准，思维敏捷，语言组织表达能力强，谈吐大方得体； 
6、有较强的团队意识，能承受工作压力； 
7、有电子、通讯、IT行业知识背景者优先。 

该职位全职工作属于公司正式员工编制，一经录用将享有：
1.优越的工作环境和便捷的地理位置。
2.保底薪资+绩效奖金+提成；4000-6000元/月+提成（平均月薪资10000-20000元；TOPCC平均月薪资30000元以上）；
3.一经录用即签订正式劳动合同；
4.完善的培训体系。
5.职业发展空间巨大，可晋升为咨询主管，咨询经理，或转为，班主任，助教，就业老师；


公司在浦东张江高科和徐汇近上海体育馆均设立有分公司，员工可以择近上班。


上海找个工作很容易，找类似的工作也很容易，但是如果你想在一年或一年半内升职，从一个一线成长为一个主管，我可以负责的告诉你：能在上海给你这样机会的公司不多。如果你来上海是为了追求发展和蜕变的，那么我希望你至少给自己，也给我们公司一个机会，各位朋友来上海不光是为了生存对吧，想在这么短的时间里有一个机会是千金难买的，那还犹豫什么？现在就行动吧！欢迎投递！


工作地址：
浦东新区张衡路180号2号楼2楼
**********
上海航傲信息科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司地址：
上海徐汇区漕溪路
**********
客服
上海日仪电子有限公司
五险一金绩效奖金交通补助餐补通讯补贴带薪年假员工旅游节日福利
**********
福利:
五险一金
绩效奖金
交通补助
餐补
通讯补贴
带薪年假
员工旅游
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：客户服务专员/助理
**********
岗位职责：
对客户的信息及时处理,能很好的与客户进行中英文交流,具有良好的沟通表达能力。 

任职要求：
1. 大学本科以上学历，英语4-6级。
2. 有良好的客户服务意识，踏实肯干。工作态度积极认真，能承受工作压力。
3. 英语、听说读写流利，熟练运用excel。

工作地址：
四平路775号1号楼513
**********
上海日仪电子有限公司
公司规模：
20-99人
公司性质：
合资
公司行业：
电子技术/半导体/集成电路
公司地址：
四平路775号1号楼513
查看公司地图
**********
销售工程师、销售代表[上海-静安区]
后芮驷(上海)电子有限公司
五险一金年底双薪交通补助餐补通讯补贴带薪年假员工旅游节日福利
**********
福利:
五险一金
年底双薪
交通补助
餐补
通讯补贴
带薪年假
员工旅游
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：上海-静安区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：2人
职位类别：销售工程师
**********
职位描述：
1、负责接插件的产品销售任务，完成销售指标；
2、开拓新市场,发展新客户,增加产品销售范围；
3、维护及增进已有客户关系；
4、完成部分技术支持工作,与客户进行技术交流；
5、负责收集市场和行业信息,加深了解。

岗位要求：
1、专科及以上学历；
2、26周岁以下，男女不限，相貌端正；
3、0~2年销售工作经验,有销售连接器经验者优先；
4、熟悉该行业产品市场，有相应产品销售经验；
5、具备较强的客户沟通能力和较高的商务处理能力，具有良好的团队协作精神；
6、学习能力强，有挑战精神。
7、有一定英语基础，能阅读、书写等。

工作地址：
上海市静安区共和新路2449号506室
查看职位地图
**********
后芮驷(上海)电子有限公司
公司规模：
20人以下
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司地址：
上海市静安区共和新路2449号506室
**********
少儿机器人老师
上海强平机器人科技有限公司
创业公司每年多次调薪五险一金年底双薪绩效奖金股票期权弹性工作员工旅游
**********
福利:
创业公司
每年多次调薪
五险一金
年底双薪
绩效奖金
股票期权
弹性工作
员工旅游
**********
职位月薪：8001-10000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：4人
职位类别：培训/招生/课程顾问
**********
岗位职责：
1、按照教务管理要求形成每周所有科技教学活动的设计方案；
2、高质量地执行教学活动方案；
3、跟踪学员的学习状态，与学员家长保持积极互动，提升学员的学习兴趣和学习效果、以及家长对教学服务的满意度。

任职要求：
1、理工科背景，机械、电子、计算机、通信、软件、自动化等专业优先考虑；
2、性格外向，形象良好，乐于沟通；
3、有较强的组织性、纪律性，具有一定的活动组织管理能力；
4、能够适应服务行业的工作时间安排（周六、日需要上班，休息日在周间）。

工作地址：
上海市宝山大华、金沙江路真北路、松江大学城
查看职位地图
**********
上海强平机器人科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
学术/科研
公司主页：
www.qiangping-robot.com
公司地址：
上海市宝山大华、金沙江路真北路、松江大学城
**********
结构工程师
厦门容大合众电子科技有限公司
五险一金年底双薪绩效奖金定期体检员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
定期体检
员工旅游
**********
职位月薪：5000-10000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：2人
职位类别：工业设计
**********
基本要求与职责：
1.本科以上学历，机电一体化及机械设计与制造类专业；
2.了解产品开发流程，精通PRO_E、等设计软件；
3.了解模具结构,熟悉电子产品生产工艺等产品结构设计相关知识；
4.熟悉产品ID设计；
5.能参与或独立完成新产品整机结构设计，协助开发项目管理。

工作地址：
厦门市湖里区高崎北三路高崎工业园195号
查看职位地图
**********
厦门容大合众电子科技有限公司
公司规模：
500-999人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.rongtatech.com/cn/default.aspx
公司地址：
厦门市湖里区高崎北三路高崎工业园195号
**********
文员
上海精麟电子科技有限公司
五险一金包吃包住
**********
福利:
五险一金
包吃
包住
**********
职位月薪：2001-4000元/月 
工作地点：上海-浦东新区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：助理/秘书/文员
**********
岗位职责：
负责公司报表统计、核算、等相关工作
任职要求：
有责任心，有上进心，工作负责，熟悉电脑，各种办公软件


工作地址：
浦东新区航头镇沪南路5583号
查看职位地图
**********
上海精麟电子科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
null
公司地址：
浦东新区航头镇沪南路5583号
**********
加工中心操作工
上海誉光光电科技有限公司
五险一金绩效奖金交通补助节日福利
**********
福利:
五险一金
绩效奖金
交通补助
节日福利
**********
职位月薪：4500-7000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：中专
招聘人数：1人
职位类别：数控操作
**********
岗位职责：
1、根据图纸要求编制简单工艺路线；
2、根据加工工艺进行加工中心或数控车床编程、调试、及数控机床操作；
3、对小批量加工件有简易工装夹具制作经验；
4、根据图纸及工艺要求，按时高效、独立完成生产计划任务， 并对产品进行自检；
5、必要时需要到供应商处进行质量抽查与管理；
6、完成领导安排的其他工作。
 岗位要求：
1、中技或中专以上学历，机械类专业，持数控中级证书者佳；
2、3年或以上数控加工中心或数控车床操作经验；
3、能看懂机械加工图纸，具备相关材料和热处理常识；
4、了解机加工工艺并会CNC编程，如会使用UG 或MASTERCAM、CAXA, CAD更佳；
5、熟悉刀具使用、了解刀具的切削参数，熟悉相关长度类检具的使用；
6、能独立完成产品的调试、简单工装夹具制作，其他工装夹具的更换与设置；
7、工作责任心强，敬业、诚实守信，有潜质提升成为班组长乃至车间生产管理；
8、本岗位将在上海或苏州工作。
  我司现有良好的团队建设和团队氛围，对员工也有很好的激励措施。欢迎您的加入，大家一起努力、一起奋斗！
工作地址：
上海市浦东新区绣川路581号绿地东海岸A座1603室
查看职位地图
**********
上海誉光光电科技有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.yuphoton.com
公司地址：
上海市浦东新区绣川路581号绿地东海岸A座1603室
**********
幼教老师
上海强平机器人科技有限公司
创业公司每年多次调薪五险一金年底双薪绩效奖金股票期权弹性工作员工旅游
**********
福利:
创业公司
每年多次调薪
五险一金
年底双薪
绩效奖金
股票期权
弹性工作
员工旅游
**********
职位月薪：6001-8000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：4人
职位类别：幼教
**********
岗位职责：
1、根据公司服务管理要求，准备幼教课程活动方案；
2、高质量地执行课程活动方案；
3、与学员家长保持良好的沟通，为家长提供儿童发展的建议。

任职要求：
1、形象良好，活泼开朗，普通话标准；
2、喜欢与幼儿打交道，善于引导幼儿完成课程活动；
3、能够熟练使用Office软件；
4、有幼教相关资质证明者优先考虑。
5、有较强的组织性、纪律性，具有一定的活动组织管理能力；
6、能够适应服务行业的工作时间安排（周六、日需要上班，休息日在周间）

工作地址：
上海市宝山大华、金沙江路真北路、松江大学城
查看职位地图
**********
上海强平机器人科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
学术/科研
公司主页：
www.qiangping-robot.com
公司地址：
上海市宝山大华、金沙江路真北路、松江大学城
**********
印刷二手
上海精麟电子科技有限公司
**********
福利:
**********
职位月薪：4001-6000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：其他
**********
岗位职责：能操作三菱印刷机

任职要求：有相关工作经验
工作地址：
浦东新区航头镇沪南路5583号
查看职位地图
**********
上海精麟电子科技有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
null
公司地址：
浦东新区航头镇沪南路5583号
**********
模具工程师/技术岗+双休 w
上海于晓软件技术有限公司
五险一金年底双薪绩效奖金全勤奖交通补助通讯补贴带薪年假员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
全勤奖
交通补助
通讯补贴
带薪年假
员工旅游
**********
职位月薪：6001-8000元/月 
工作地点：上海-徐汇区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：5人
职位类别：模具工程师
**********
职位要求：
1.理工科相关专业，有无相关工作经验均可，可接受应届生；
2.性格开朗、积极上进、责任心强，沟通能力强，具备团队合作精神；
3.做事严谨踏实，责任心强，善于学习总结以及分析、解决能力；
4.能尽快入职者；
5.年龄20-30岁，超龄勿扰。
工作时间：9:00-18:00 午休1个半小时
福利待遇：
1.试用期一个月，试用期综合工资6000，转正后综合工资6500-8500 （可面议）；
2.实习期满后会通过考核，考核通过可转为正式员工
3.8小时工作制、周末双休、法定节假日正常休息
4.公司有完善的考核机制、晋升机制、加薪机制

工作地址：
上海徐汇漕河泾
查看职位地图
**********
上海于晓软件技术有限公司
公司规模：
500-999人
公司性质：
股份制企业
公司行业：
计算机软件
公司地址：
**********
机电工程师（应往届都可）(职位编号：10)
上海博为峰软件技术股份有限公司
五险一金年底双薪绩效奖金全勤奖交通补助通讯补贴带薪年假员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
全勤奖
交通补助
通讯补贴
带薪年假
员工旅游
**********
职位月薪：6001-8000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：4人
职位类别：机电工程师
**********
任职资格:
1、大专及以上学历，理工科相关专业优先； 
2、良好的综合素质，严谨的逻辑思维能力，有志于从事专业的软件相关工作；
3、有无软件相关工作经验者均可，欢迎优秀的应届大学毕业生；
4.20-30岁超龄勿扰。男女不限。
对IT行业充满热情，工作细致认真并富有耐心；
喜欢技术工作，具备较强的逻辑分析能力和钻研精神；
工作职责：
完成部分技术文档的编辑、撰写工作
分析并解决软件测试过程中的问题
对软件项目进行测试，做好错误记录并提交
完成工程师安排的其他技术相关的任务，每日进行工作汇报

工作地址：
上海徐汇漕河泾虹梅路2007号1号楼9楼
**********
上海博为峰软件技术股份有限公司
公司规模：
500-999人
公司性质：
上市公司
公司行业：
计算机软件
公司地址：
上海市黄浦区云南北路59号六合大厦1510室
**********
软件工程师
上海捷盟信息科技有限公司
绩效奖金全勤奖带薪年假节日福利定期体检员工旅游五险一金
**********
福利:
绩效奖金
全勤奖
带薪年假
节日福利
定期体检
员工旅游
五险一金
**********
职位月薪：4001-6000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：不限
招聘人数：2人
职位类别：软件工程师
**********
一：熟练掌握C/C++开发语言,掌握面向对象的开发思想,了解常用的设计模式
有网络编程经验优先,熟悉掌握Socket编程,对TCP/IP协议有充分的理解
精通视频通信技术和网站的实现技术与架构；
熟悉视频和音频编码标准，如MPEG-2、MPEG-4、H.264、AVS等；
熟悉基于H.264的采集优化，渲染和前后处理，音视频网络传输Qos反馈 仲裁机制优先；
精通视频采集、编码/转码/解码，熟练使用 ffmpeg/gstreamer/dshow 等软件包并能进行二次开发；精通 TCP/UDP，熟悉RTSP/RTMP/HLS/WebRTC等网络流媒体服务、视频直播/点播应用开发；熟悉WINDOWS应用程序/插件,对WINDOWS操作系统有一定的了解,对Windows Service,DLL开发,内核开发,应用层钩子,COM组件的编写熟练；具有独立分析解决问题的能力。
（薪酬：6-20万）工作地点：上海

工作地址：
上海市浦东新区金豫路251号2号楼408
查看职位地图
**********
上海捷盟信息科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
www.geunion.com.cn
公司地址：
上海市浦东新区金海路1000号18号楼西区4楼
**********
销售经理
上海捷盟信息科技有限公司
绩效奖金五险一金交通补助通讯补贴节日福利带薪年假全勤奖员工旅游
**********
福利:
绩效奖金
五险一金
交通补助
通讯补贴
节日福利
带薪年假
全勤奖
员工旅游
**********
职位月薪：4001-6000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：5人
职位类别：销售经理
**********
我们能给的不只是一份高薪酬工作，梦想、健康、娱乐、机遇…
更是海阔天空任你翱翔的空间
我们的要求并不高
捷盟最宽广的就是胸怀
宽广到有时我们都怀疑到自己的底线在哪里
你说你不了解捷盟？没关系，我来告诉你
他是一个“奋进”的公司，面对的客户都是国内顶尖的甲方，涵盖了政府、医疗、金融、电力、教育、交通、军队等众多行业
他是一个“年轻”的公司 ，从老板到员工都是朝气蓬勃
他是一个“科技”的公司，每年都能自主研发创新产品获得上海国际创新创业大奖…
当然，还有你关心的…
13薪，绩效奖金，年终奖金，节假日福利，生日福利，培训，五险一金，年度旅游，年度体检，双休，朝九晚五等基本操作不再复述，确保样样都有。
任职要求：

有较强的口头表达能力，思路敏捷，良好的人际沟通能力，责任心强，肯吃苦耐劳，做事富有激情和主动性，诚实可信、富有团队合作精神。乐于学习、敢于创新、追求卓越，敢于接受挑战，有强烈的实现自我价值的欲望，百折不饶的拼搏精神及敏捷、灵活的才智。（薪酬：5-20万）工作地点：上海 北京 西安




工作地址：
上海市浦东新区金豫路251号2号楼408
查看职位地图
**********
上海捷盟信息科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
www.geunion.com.cn
公司地址：
上海市浦东新区金海路1000号18号楼西区4楼
**********
行政助理
上海芯奇实业有限公司
五险一金绩效奖金餐补带薪年假员工旅游高温补贴节日福利
**********
福利:
五险一金
绩效奖金
餐补
带薪年假
员工旅游
高温补贴
节日福利
**********
职位月薪：3000-5000元/月 
工作地点：上海-宝山区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：助理/秘书/文员
**********
岗位职责：
1、负责每天订单的审核；
2、负责每月与客户的对账，催款；
3、协助销售人员做好其他事宜；
4、完成领导交办的其他事项。

任职要求：
1、反应敏捷、表达能力强，具有较强的沟通能力，具有亲和力； 
2、具备良好的客户服务意识； 
3、能吃苦耐劳，有目标有远大抱负；
4、有相关经验者优先考虑。
工作时间：做五休二，9：00-17:30
面试地点：上海市淞兴西路258号半岛1919文化创意园五号楼105室，3号线附近

工作地址：
上海市宝山区淞兴西路258号半岛1919文化创意园五号楼105室
查看职位地图
**********
上海芯奇实业有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司地址：
上海市宝山区淞兴西路258号半岛1919文化创意园五号楼105室
**********
SMT服务工程师
旭义普国际贸易(上海)有限公司
五险一金年底双薪带薪年假员工旅游
**********
福利:
五险一金
年底双薪
带薪年假
员工旅游
**********
职位月薪：6000-7000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：电子/电器工程师
**********
职责描述：
负责SMT及周边设备的安装调试、维修保养和客户培训工作；
为客户提供技术支持，响应客户的维修服务需求；
与客户以及供应商的技术部门对接，解决设备使用中遇到的问题；
配合销售团队在产品应用、问题分析、技术改进等方面提供技术支持；
协助其他部门同事做好备品采购和库存管理；
开展技术巡访，拜访客户，与客户保持良好关系。
 
任职条件：
大专以上学历，机械、电子、工业自动化类相关专业；
三年以上SMT设备维护工作经验，精通SMT工艺流程及相关设备；
善于沟通，具备团队合作精神；
具有系统分析问题，独立处理问题的能力；
能适应经常短途出差；
能看懂普通英文资料，有一定英语沟通能力者优先。
工作地址：
上海市北京东路668号科技京城东楼27楼A1室
查看职位地图
**********
旭义普国际贸易(上海)有限公司
公司规模：
20人以下
公司性质：
外商独资
公司行业：
贸易/进出口
公司主页：
www.sip-technology.com
公司地址：
上海市北京东路668号科技京城东楼27楼A1室
**********
电路维修技术员（大专以上）(职位编号：11)
上海博为峰软件技术股份有限公司
**********
福利:
**********
职位月薪：6001-8000元/月 
工作地点：上海-黄浦区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：5人
职位类别：普工/操作工
**********
岗位要求:
1.大专及以上学历，理工科相关专业，20-30岁之间;
2.工作积极主动，学习能力强，具有较强的执行力和团队协作精神。
公司福利：
1、薪酬体系：薪酬=基本工资+绩效+项目提成+生活补贴（均薪7K）；
2、健全的福利制度：五险一金（养老、医疗、事业、生育、工伤）、餐补、通讯补贴等；
3、员工活动：每年必备集体旅行，年会（各种福利发放），公司出资定期进行团队建设；
4、节假日福利：春节，端午节，中秋节、春节、结婚礼金，生日慰问，夏日高温福利等。
5、年终奖：年终双薪绝对不是问题，更有年终分红、期权等着你们来拿。

工作地址：
上海徐汇漕河泾虹梅路2007号1号楼9楼
**********
上海博为峰软件技术股份有限公司
公司规模：
500-999人
公司性质：
上市公司
公司行业：
计算机软件
公司地址：
上海市黄浦区云南北路59号六合大厦1510室
**********
华东区域经理
北京铭瑞欣科控制技术有限公司
创业公司五险一金绩效奖金年终分红交通补助餐补通讯补贴员工旅游
**********
福利:
创业公司
五险一金
绩效奖金
年终分红
交通补助
餐补
通讯补贴
员工旅游
**********
职位月薪：5000-10000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：销售主管
**********
1、中专以上学历，男女不限；
2、23-40岁
3、工作地点：北京、上海、江苏、浙江、安徽；
4、从事过销售工作或希望从事销售工作；
5、有工业设备或电气产品销售工作者优先；
6、有驾照者优先；
7、无需坐班。

工作地址：
北京、上海、江苏、浙江、安徽
**********
北京铭瑞欣科控制技术有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
仪器仪表及工业自动化
公司主页：
www.bjmrct.com
公司地址：
北京市丰台区科学城星火路11号蓝谷科技大厦B座405
查看公司地图
**********
销售总监
上海捷盟信息科技有限公司
五险一金绩效奖金全勤奖交通补助通讯补贴带薪年假员工旅游节日福利
**********
福利:
五险一金
绩效奖金
全勤奖
交通补助
通讯补贴
带薪年假
员工旅游
节日福利
**********
职位月薪：8001-10000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：5-10年
最低学历：不限
招聘人数：1人
职位类别：销售总监
**********
岗位职责：
1、按照公司要求，拓展经销商及终端客户销售；
2、管理销售团队改变工作方法，提升工作业绩；
3、做好部门内部管理工作。  
4、独立完成商务谈判，独立策划合作方案，执行合作，规划工作计划并能够按照进度执行；  
5、组织协调公司内外资源，协助公司运营、拓展目标达成。
任职要求：
1、有五年以上政企卫等行业销售管理经验，对行业有一定的理解和认识，提供以往业绩成果证明；
2、具有创业精神，具有良好的沟通能力及丰富的销售经验。取得过良好的销售业绩，服务过重点行业客户的优先考虑；
3、自我约束力强，具备销售狼性，团队合作意识（薪酬：10-50万）

工作地址：上海市浦东新区金豫路251号2号楼408
工作时间：周一至周五（9：00-18：00）
工作地址：
上海市浦东新区金豫路251号2号楼408
查看职位地图
**********
上海捷盟信息科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
www.geunion.com.cn
公司地址：
上海市浦东新区金海路1000号18号楼西区4楼
**********
技术部门专员/双休+五险一金(职位编号：13)
上海博为峰软件技术股份有限公司
五险一金年底双薪绩效奖金全勤奖交通补助通讯补贴带薪年假员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
全勤奖
交通补助
通讯补贴
带薪年假
员工旅游
**********
职位月薪：6001-8000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：3人
职位类别：储备干部
**********
任职要求：
1、大专及以上学历，专业不限，有工作经验者优先；
2、对互联网软件行业有较大的求知欲及良好的学习精神，想在软件行业发展；
3、前期老带新，要求能吃苦耐劳，协助做辅助性工作；
4、后期积极参与相应模块的设计、开发、编程任务。
薪资福利：
1、转正底薪6000-8000，7.5小时制，周末双休；
2、国家法定五险一金及带薪假期；
3、办公环境舒适，地理位置优越，地铁口及公交站附近；
4、公司定期组织员工旅游及户外活动；
公司并且给应往届生提供实训岗位。


工作地址：
上海徐汇漕河泾虹梅路2007号1号楼9楼
**********
上海博为峰软件技术股份有限公司
公司规模：
500-999人
公司性质：
上市公司
公司行业：
计算机软件
公司地址：
上海市黄浦区云南北路59号六合大厦1510室
**********
分校区副校长
上海强平机器人科技有限公司
五险一金绩效奖金年终分红节日福利
**********
福利:
五险一金
绩效奖金
年终分红
节日福利
**********
职位月薪：6000-10000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：校长/副校长
**********
岗位职责：副校长工作职责，该岗位是一个储备校长岗位，希望能在半年左右的储备期，正式成长为校区校长职位。
1，负责南方分校区的招生和营销宣传地推工作；
2，承担分校区日常运营工作，包括学生上课安排，家长接待，课后消课等；
3，统筹管理学生课程交付质量和续费工作；
任职要求：
1，教育培训行业经验者优先考虑；
2，沟通交流能力强，亲和力强，能与家长很好的沟通；
3，具备一定的销售技巧和市场活动策划能力；
4，具备一定的谈单和谈市场合作能力；
工作地址：
上海市闵行古方路18号南方休闲商务大厦302
查看职位地图
**********
上海强平机器人科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
学术/科研
公司主页：
www.qiangping-robot.com
公司地址：
上海市宝山大华、金沙江路真北路、松江大学城
**********
财务
旭义普国际贸易(上海)有限公司
**********
福利:
**********
职位月薪：4001-6000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：财务助理
**********
岗位职责：
1. 协助主管完成日常事务性工作，协助处理帐务；
2. 负责公司开票、协助出口退税申报工作；
3. 协助财会文件的准备、归档和保管；
4. 负责与银行、税务等部门的对外联络；
5. 协调和督促业务及相关部门配合好进出口业务相关工作；
6. 办公室其他事务.
岗位要求：
1. 财务会计或相关专业大专以上学历；
2. 较好的会计基础知识和一定的英语能力，1年以上财务工作经历；
3. 熟悉外贸行业财务核算要求，熟练运用财务软件和办公软件；
4. 良好的综合素质，擅长沟通和协调，有团队合作精神并能承受工作压力.
工作地址：
上海市北京东路668号科技京城东楼27楼A1室
**********
旭义普国际贸易(上海)有限公司
公司规模：
20人以下
公司性质：
外商独资
公司行业：
贸易/进出口
公司主页：
www.sip-technology.com
公司地址：
上海市北京东路668号科技京城东楼27楼A1室
查看公司地图
**********
硬件开发工程师
上海兆富电子科技有限公司
五险一金绩效奖金餐补带薪年假高温补贴节日福利包吃
**********
福利:
五险一金
绩效奖金
餐补
带薪年假
高温补贴
节日福利
包吃
**********
职位月薪：4000-7000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：2人
职位类别：嵌入式硬件开发
**********
硬件工程师—主要负责各类产品的硬件设计工作
职位描述：
1、嵌入式硬件开发，低层驱动软件开发；
2、数电、模电等相关电路单元设计；
3、完成电路原理图、PCB设计、相关软件设计、调试；
4、完成项目设计相关文档。
招聘要求：
1、本科以上，至少1年以上工作经验；
2、丰富的单片机等嵌入式硬件、软件设计经验；
3、熟练使用Protel 99SE或AD6进行原理图、PCB设计；
4、丰富的模电、数电设计、调试经验；
5、熟练使用C语言进行嵌入式软件编程、调试；
6、具有以下经验者优先考虑：
  熟练使用ATMEL AVR、TI MSP430单片机、ARM；
  熟悉RF设计、应用；
  熟悉相关通讯接口：RS485，RS232，I2C，SPI，CAN，USB，以太网；
工作地址：
上海市嘉定区蕰北公路1755弄1号楼
**********
上海兆富电子科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司地址：
上海市嘉定区南翔镇藴北公路1755弄1号
查看公司地图
**********
嵌入式软件开发工程师
阿黛凯检测技术(上海)有限公司
五险一金交通补助餐补定期体检免费班车员工旅游高温补贴节日福利
**********
福利:
五险一金
交通补助
餐补
定期体检
免费班车
员工旅游
高温补贴
节日福利
**********
职位月薪：12000-13000元/月 
工作地点：上海-松江区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：嵌入式软件开发
**********
岗位职责：
1、熟练常用开发语言，负责新产品的嵌入式软件开发和设计（单片机应用软件），底层驱动软件设计与实现，并能独立完成；
2、单片机驱动及协议应用的开发（常用通讯协议：CAN总线\MODBUS\TCP等）、移植、调试和维护；
3、完成上级交给的其它事物性工作。
任职要求：
1、大学本科及以上，计算机、电子信息类、自动化控制（弱电）相关专业，2年以上相关工作经验，单片机应用软件开发熟练者优先，良好的英文读写能力；
2、具备良好的沟通能力、学习能力和团队合作精神精神。

工作地址：
松江区九亭镇健鹏路98号
查看职位地图
**********
阿黛凯检测技术(上海)有限公司
公司规模：
20-99人
公司性质：
外商独资
公司行业：
仪器仪表及工业自动化
公司主页：
https://www.ateq.com
公司地址：
上海市松江区九亭镇健鹏路98号1幢厂房
**********
Firmware Engineer嵌入式软件工程师
芯迪半导体科技(上海)有限公司
**********
福利:
**********
职位月薪：10001-15000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：1人
职位类别：嵌入式软件开发
**********
Job Descriptions
  1. Evaluate firmware requirements
2.      2. Design and implement firmware according to the software specifications
3.      3.Hardware board bring-up
4.       4.Work with sales and marketing teams to provide technical support to customer
Qualification
  1. Proficient in C and debugging skills in embedded system
2.      2.  Proficient in C and debugging skills in embedded system
3.      3. Familiar with Makefile, ARM assemble langaunge, a cript language (perl/python), java is a plus
4.      4.  Experience with SCM tool (SVN, Git..)
5.      5. Familiar with open source development environment (GCC toolchain,..)
6.       6. Familiar with ARM processor architecture
7.       7.Familiar with a RTOS (ucos, ecos, etc..) and know how it works
8.       8. Knowledge on TCPIP protocols and peripheral interfaces (RS232/I2C/SPI/RGMII)
9.       9. Knowledge of PLC communication system, digital circuit is a plus
10.    10.Good teamwork, Self-motivated, and willing to accept new challenges with new technologies
11.    11.Proficiency in English communication

工作地址：
上海市浦东新区芳甸路1155号1806室
**********
芯迪半导体科技(上海)有限公司
公司规模：
20-99人
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
www.xingtera.com
公司地址：
上海市浦东新区芳甸路1155号1806室
查看公司地图
**********
行政文员
上海楚岳实业有限公司
包吃包住房补带薪年假弹性工作节日福利
**********
福利:
包吃
包住
房补
带薪年假
弹性工作
节日福利
**********
职位月薪：2001-4000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：行政专员/助理
**********
岗位职责： 
1.负责访客、来宾的接待、引见；
2. 负责公司电话转接、信函的收转发工作，做好工作信息的记录、整理、建档；
3. 负责公司办公用品、常用耗材的采购跟进、落实，每周、月底汇整办公费用明细；
4. 负责公司内厂车出车安排，积极协调各部门的用车信息，做到既满足出车需求，又能节约成本，每周、月底汇整行车记录、外叫车明细并呈报；
公司提供食宿。


工作地址：
上海市松江区沪松公路3866号
**********
上海楚岳实业有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
http://chuyuein.com/
公司地址：
上海市松江区沪松公路3866号
查看公司地图
**********
商用厨具规划设计师
合肥顺昌分布式能源综合应用技术有限公司
五险一金年底双薪绩效奖金加班补助包吃包住员工旅游节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
加班补助
包吃
包住
员工旅游
节日福利
**********
职位月薪：8001-10000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：不限
招聘人数：2人
职位类别：CAD设计/制图
**********
岗位职责
1、负责厨房内平面规划设计
2、水、电、气接驳点系统图、排烟系统图及设备清单规格整理。
3、上级安排的其它工作事务。
任职要求：
1、性别不限，大专以上学历。
2、熟练使用CAD、OFFICE等办公软件。
3、5年以上工作经验，从事过厨房平面设计优先。
4、工作细心，吃苦耐劳，认真负责。

工作地址：
合肥市桃花工业园祝融路与长古路交叉口向西100米 1、234路公交，到繁华新园站下，沿祝融路往北走10米，再沿长古路向西走130米即为顺昌企业。2、80路公交车，到繁祝路口站下，繁华大道往东走60米，右转，沿祝融路走440米，往西沿长古路走130米即顺昌企业
**********
合肥顺昌分布式能源综合应用技术有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
www.cnjsc.com
公司地址：
合肥市桃花工业园祝融路与长古路交叉口向西100米 1、234路公交，到繁华新园站下，沿祝融路往北走10米，再沿长古路向西走130米即为顺昌企业。2、80路公交车，到繁祝路口站下，繁华大道往东走60米，右转，沿祝融路走440米，往西沿长古路走130米即顺昌企业
**********
销售代表
厦门优贝达电子科技有限公司
绩效奖金加班补助全勤奖餐补通讯补贴员工旅游交通补助
**********
福利:
绩效奖金
加班补助
全勤奖
餐补
通讯补贴
员工旅游
交通补助
**********
职位月薪：8001-10000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：5人
职位类别：销售代表
**********
一、岗位职责：
1、主动开拓新市场，发展新客户，维护老客户；
2、建立好客户档案，积极了解客户需求，及时合理的帮助客户解决问题，树立企业形象；
3、执行公司的销售策略及政策，根据公司制定的业务指标，定时定量地完成客户开发及产品运营销售任务；
4、充分挖掘自身工作潜力，收集一线营销信息，用户意见，当地市场信息，对公司提出参考意见；
二、岗位要求：
1、大专及以上学历，有一年以上销售工作经验，优秀应届生可优先考虑；
2、具备较强的表达及沟通协调能力，拥有良好的学习能力和应变力；
3、对工作认真负责，具备一定的抗压能力；
4、性格开朗有亲和力，有良好的服务意识和团队合作能力。
三、薪资福利：
该职位提供底薪+提成+年终奖，转正后缴纳五险；
公司定期组织岗位培训，员工不断得到提升；
公司每年举办员工旅游；
公司活动：中秋博饼，年终尾牙，不定时聚餐等其他户外活动
工作时间：5天8小时制，双休，法定节假日按照国家规定执行
工作地址：
上海市宝山区共和新路4995弄3号楼615室
查看职位地图
**********
厦门优贝达电子科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
通信/电信/网络设备
公司主页：
www.ubeida.com
公司地址：
厦门市集美区杏林内中里7号A栋2楼
**********
销售总监
成都市晶林科技有限公司
绩效奖金股票期权餐补带薪年假弹性工作员工旅游节日福利
**********
福利:
绩效奖金
股票期权
餐补
带薪年假
弹性工作
员工旅游
节日福利
**********
职位月薪：10000-20000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：不限
招聘人数：1人
职位类别：销售总监
**********
岗位职责：
1、制定公司营销策略和目标并带领团队组织实施；负责拓展相关产品市场领域，提高公司产品与服务在该领域行业市场占有率，完成公司年度营销目标；
2、负责开拓大客户渠道，客户分析，建立客户关系，挖掘用户需求；
3、分析行业发展趋势，收集各种市场信息及竞争对手情况，进行相关销售数据分析以及市场预测；
4、及时把握行业动态，为企业提供业务发展战略依据；
5、控制销售团队预算、销售费用、销售范围与销售目标的平衡发展；优化销售流程，降低销售成本，组织货款回笼。

任职要求：
1、年龄40岁以下，电子、计算机等理工科相关专业；
2、熟悉集成电路及产品销售模式，具备3年以上车载、安防或工业监测行业销售与团队管理经验；
3、熟悉车载、安防及工业监控系统和产品，熟悉相关知识和市场动态，有红外热成像产品行业经验者优先；
4、对营销战略、策略有深入的研究并有出色的团队销售业绩及市场；
5、热爱销售工作，具有较强的市场拓展、策划与产品推广能力，善交际，具有良好的沟通和谈判能力；
6、强烈的进取心，乐观豁达，具有开拓精神和良好的团队合作意识；能适应出差；
7、薪资面议。

工作地址：
上海
查看职位地图
**********
成都市晶林科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司地址：
成都市高新南区天府四街66号航兴国际广场1号楼704
**********
Hardware Engineer硬件工程师
芯迪半导体科技(上海)有限公司
**********
福利:
**********
职位月薪：10001-15000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：硬件工程师
**********
Job Descriptions
1.Design demo systems or reference platform for Xingtera’s products
·      2.. Finish hardware design according to customer requirement
·      3.Provide support for company software and FAE from hardware point
·      4. Support customer hardware design, FAEs, Sales teams, and mass productions and so on.
·      Qualification
 1. 1-3 years hardware board design experience
·    2. Familiar with embedded micro-controller system
·    3.Familiar with debug tools such as oscilloscopes, Spectrum Analyzer, etc.
·    4. Self-motivated and highly ambitious
·    5.  Rich experience on using soldering tools
·    6. Familiar with EDA tools, such as Capture CIS, CAM350 and so on
·    7.Experience in products manufacturing is strongly preferred
·    8. Proficiency in English communication
·   
工作地址：
上海市浦东新区芳甸路1155号1806室
**********
芯迪半导体科技(上海)有限公司
公司规模：
20-99人
公司性质：
外商独资
公司行业：
电子技术/半导体/集成电路
公司主页：
www.xingtera.com
公司地址：
上海市浦东新区芳甸路1155号1806室
查看公司地图
**********
图像处理工程师
上海融军科技有限公司
五险一金带薪年假员工旅游节日福利
**********
福利:
五险一金
带薪年假
员工旅游
节日福利
**********
职位月薪：8333-16666元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：硕士
招聘人数：1人
职位类别：软件工程师
**********
岗位职责： 1）负责图形图像定位、分割、识别算法的研究，根据业务特点优化算法； 2）研究图像特征检测的识别，包括算法实现、试验、优化等； 3）收集行业内新的技术、算法，提高现有系统对图形图像识别的效率与准确率； 4）负责对已有系统图形图像处理算法的提升。 任职资格： 1）2年以上相关工作经验； 2）熟悉图像分析方法，理解常用图像特征提取算法的原理； 3）了解常见开源库Open CV等，熟练使用c和c++，能进行计算机图像处理和识别方面的软件编程； 4）最好能掌握遥感处理、GIS、模式识别、数字图像处理相关理论，熟练使用GIS软件/ARCVIEW/ARCGIS/MAP/NFO之一，了解正射校正、影像融合、信息提取等遥感图像处理手段； 5）沟通和组织能力强，团队协作能力佳； 6）做事认真负责踏实、态度谨慎、对工作要求精益求精； 7）创新能力强、抗压能力强、能协调好工作和生活。 注：工作地点：浦西漕河泾开发区
所属部门：上海融军科技有限公司
部门人数：
汇报对象：
工作地址：
浦西漕河泾开发区
查看职位地图
**********
上海融军科技有限公司
公司规模：
20-99人
公司性质：
其它
公司行业：
电子技术/半导体/集成电路
公司主页：
null
公司地址：
注册地址：浦东新区临港
**********
急急急 招商专员 (周末双休)
上海开皇实业有限公司
五险一金年底双薪绩效奖金年终分红包吃节日福利定期体检
**********
福利:
五险一金
年底双薪
绩效奖金
年终分红
包吃
节日福利
定期体检
**********
职位月薪：5000-10000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：无经验
最低学历：中专
招聘人数：5人
职位类别：招商专员
**********
公司介绍:
“宾兔兔”鞋网 是为广大鞋类用户找到更适合更舒适鞋品的在线购买平台。
我们开创的是新型的鞋类零售模式！专注于发布新品鞋类的电商平台，使用更智能化的定制鞋类选品算法，导航精准，品类标准完善，高度自定义的服务设定。3D扫描设计的新科技量脚体验，上门服务排队机制，以及覆盖全国各大城市、县镇、商圈、社区的专业上门服务团队。成为用户首选的鞋类购买和定制的平台。

     “宾兔兔”鞋网将在新零售方式的基础上，凭借自身具备的鞋品定制业务能力，打造一个专业多功能型商业平台，平台正式开启个人定制、家庭定制、企业员工定制、特殊职业定制、单件定制、手工定制等一系列定制服务需求，满足不同用户群体的个性化追求。
岗位任职要求：
1.年龄20岁到30岁之间，学历中专及以上学历，能力优秀者适当放宽
2.有无工作经验都可，(有专人才带教指导)应届毕业生优先
3.熟悉销售的流程优先考虑，具备优秀的客户开发能力
3.性格乐观开朗，善于学习和表达，富有正能量。
 工作内容：
1. 学习公司项目知识。
2. 搜集客户资料开发新客户，维护老客户。
3. 有效沟通及时了解客户需求与客户建立长期合作关系。完成销售业绩。
薪资待遇：
1.底薪5K-6.5K+高额绩效奖+年终奖+高提成
2.工作时间9:00—18:.0,双休，工作氛围轻松自由。
3.不定期国内国外旅游，聚餐等，业余生活丰富
4.五险一金，带薪年假，婚假等法定规定的假期都有，免费体检节日福利,不加班！
5.全面专业的员工培训以及职业规划，只要能力优秀就能迅速晋升！
 我们的平台： 如果你是千里马，这里将是任你驰骋的疆场。公正公平的福利待遇，开明活跃的公司氛围，友好团结的领导同事，前途无量的发展前景，在这里，价值会得到充分的发挥。只要你是一个努力的充满激情和梦想的人，相信你会融入我们，并和我们一起创造辉煌！

工作地址：
长宁区剑河路888弄B-22
查看职位地图
**********
上海开皇实业有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
互联网/电子商务
公司主页：
http://www.bintutu.com/index.html
公司地址：
长宁区剑河路888弄B-22
**********
电话销售
上海开皇实业有限公司
创业公司绩效奖金年终分红包吃定期体检节日福利五险一金带薪年假
**********
福利:
创业公司
绩效奖金
年终分红
包吃
定期体检
节日福利
五险一金
带薪年假
**********
职位月薪：4500-6500元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1年以下
最低学历：大专
招聘人数：1人
职位类别：电话销售
**********
岗位职责：
1. 拓展客户，与意向客户进行加盟代理前期沟通；
2. 邀约意向客户来公司总部考察与培训；
3. 来访客户全程协助接待、销售洽谈与谈判、意向与正式加盟合同的签订。
4. 签约客户的后续执行沟通服务；
5. 具备较强的分析能力、表达能力、沟通能力、应变能力等。
任职要求：
1.20-30岁，大专以上，欢迎有志于挑战自我，挑战高薪者；
2.形象气质良好、心态积极、性格外向、喜欢与人沟通；
3.具备良好的自我管理和抗压能力；
4.认同公司的企业文化和价值观；
5.具有电话销售或招商销售工作经验者优先考虑
福利：绩效奖金，五险一金，包吃，带薪年假，节日福利 , 免费体检 ,8小时双休
薪资：底薪+高额提成
 我们的平台：
如果你是千里马，这里将是任你驰骋的疆场。公正公平的福利待遇，开明活跃的公司氛围，友好团结的领导同事，前途无量的发展前景，在这里，价值会得到充分的发挥。只要你是一个努力的充满激情和梦想的人，相信你会融入我们，并和我们一起创造辉煌！
工作时间：周一-周五（9:00-18:00）
工作地址:长宁区剑河路888弄B22


工作地址：
长宁区剑河路888弄B-22
查看职位地图
**********
上海开皇实业有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
互联网/电子商务
公司主页：
http://www.bintutu.com/index.html
公司地址：
长宁区剑河路888弄B-22
**********
实验室设备工程师（测试中心）
儒竞艾默生环境优化技术(上海)有限公司
五险一金年底双薪包住交通补助餐补通讯补贴带薪年假节日福利
**********
福利:
五险一金
年底双薪
包住
交通补助
餐补
通讯补贴
带薪年假
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：上海-宝山区
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：中专
招聘人数：1人
职位类别：电子/电器维修/保养
**********
工作职责：
1、研发实验室设备的验收、日常管理、维护保养、故障排查、整理盘点；
2、制定测量设备的计量校准计划、期间核查计划，并推动执行；
3、参与产品研发阶段的EMC、环境可靠性、功能性能测试工作；
4、实验室配电改造、优化。

经验要求：
1、电力电子、电气、机械、自动化等相关工科专业；
2、3年以上设备管理工作经验；
3、熟悉EMC、环境、振动等实验室设备的验收、盘点、维护、保养；
4、熟悉测量设备的计量校准和期间核查；
5、具有电力电子产品环境可靠性、EMC、功能、性能测试经验者优先考虑；
6、熟悉ISO17025体系者优先考虑。

技能要求：
1、具备专业的电气、电工知识和初步的设备故障排查能力；
2、较强的动手能力，能够完成简单测试工装治具的设计和制作；
3、熟悉环境试验箱、振动测试机、程控电源、测试台架等设备的维护保养方法；
4、熟悉设备计量校准和期间核查的程序和方法；
5、出色的沟通协调能力和独立分析解决问题的能力；
6、持有电工证。

工作地址：
上海市宝山区金勺路1515号宝临电气工业园区A1南楼
查看职位地图
**********
儒竞艾默生环境优化技术(上海)有限公司
公司规模：
100-499人
公司性质：
合资
公司行业：
电子技术/半导体/集成电路
公司主页：
www.ruking-emerson.com
公司地址：
上海市杨浦区国权北路1688号湾谷科技园B5栋12楼
**********
测试工程师（测试中心）
儒竞艾默生环境优化技术(上海)有限公司
五险一金年底双薪包住交通补助餐补通讯补贴带薪年假节日福利
**********
福利:
五险一金
年底双薪
包住
交通补助
餐补
通讯补贴
带薪年假
节日福利
**********
职位月薪：6001-8000元/月 
工作地点：上海-宝山区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：测试/可靠性工程师
**********
工作职责：
1、参与产品研发阶段的EMC、环境可靠性、功能性能测试工作；
2、负责研发实验室测试样机的管理，仓库配件、工具、耗材的采购和管理；
3、外部测试委托的受理和登记；
4、其它上级主管安排的实验室日常事务。

技能要求：
1、电力电子、电气、机械、自动化等相关工科专业毕业，具备初步的电力电子知识；
2、严谨、认真的工作态度；
3、良好的沟通协调能力。

经验要求：
1、电力电子、电气、机械、自动化等相关工科专业大专以上学历；
2、1年以上测试工作经验，专业匹配的优秀应届毕业生亦可考虑；
3、具有电力电子产品环境可靠性、EMC、功能、性能测试经验者优先考虑；
4、熟悉ISO17025体系者优先考虑。

工作地址：
上海市宝山区金勺路1515号宝临电气工业园区
查看职位地图
**********
儒竞艾默生环境优化技术(上海)有限公司
公司规模：
100-499人
公司性质：
合资
公司行业：
电子技术/半导体/集成电路
公司主页：
www.ruking-emerson.com
公司地址：
上海市杨浦区国权北路1688号湾谷科技园B5栋12楼
**********
建筑转高薪IT行业（双休）(职位编号：10)
上海博为峰软件技术股份有限公司
五险一金年底双薪绩效奖金全勤奖交通补助通讯补贴带薪年假员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
全勤奖
交通补助
通讯补贴
带薪年假
员工旅游
**********
职位月薪：6001-8000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：4人
职位类别：建筑工程师
**********
岗位职责：
1、对计算机行业有兴趣，并想从事该行业。
2、想从事一份高稳定、高收入的行业，少加班、少出差。
3、喜欢吸收新知识，对于未知的事物充满好奇心。
4、善于发现工作中出现的问题，并能独立解决。
 应聘条件：
1、能够尽快入职，长期稳定工作。
2、20-30岁超龄勿扰，男女不限。
入职后签订劳动就业合同，五险一金+双休法假日,有良好的晋升空间。
 职位要求：
1、专科及专科以上学历，理工科相关专业优先，接受转行，专业不限。
2、逻辑思维强，对IT行业有兴趣。
3、有良好沟通能力和学习能力。
4、有无相关经验均可，应往届都可。
5、具有良好的表达能力和沟通能力，具有良好的团队合作精神，工作责任心强，善于学习。
 公司福利：双休、五险一金、年度体检、节日福利、13薪等。
 工作时间: 早9:00至晚17:30，周末双休。
面试时请携带本人身份证和最高学历证书。

工作地址：
上海徐汇漕河泾虹梅路2007号1号楼9楼
**********
上海博为峰软件技术股份有限公司
公司规模：
500-999人
公司性质：
上市公司
公司行业：
计算机软件
公司地址：
上海市黄浦区云南北路59号六合大厦1510室
**********
上海德重科技有限公司
上海德重科技有限公司
五险一金餐补通讯补贴带薪年假定期体检
**********
福利:
五险一金
餐补
通讯补贴
带薪年假
定期体检
**********
职位月薪：10000-16000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：3-5年
最低学历：本科
招聘人数：1人
职位类别：机械工程师
**********
岗位职责：1、熟悉机械零件的设计加工工艺，熟练运用CAD、SW等三维设计软件制作数字样品模型和虚拟              装配等产品推荐。
          2、与客户进行技术交流，了解客户需求，为客户提供解决方案。
         3、与电气工程师配合完成产品设计和项目开发等相关工作。
         4、协助技术助理整理归档各类技术和项目文档。
           5、有效协调处理项目现场产生的各类问题。
任职要求：1、大专及以上学历，机械相关专业。
          2、对非标自动化设备的设计和零配件选型有四年以上的工作经验。
          3、能独立完成项目相关的机械绘图与设计工作。
          4、有较强的学习能力和沟通表达能力，条理性清晰。
          5、工作认真负责、严谨细致、抗压性强，有良好的创新精神和团队合作意识。











             工作地址：
上海市虹口区广纪路738号明珠创意产业园2幢3楼
查看职位地图
**********
上海德重科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
仪器仪表及工业自动化
公司主页：
http://www.dezon.com
公司地址：
上海市虹口区广纪路738号明珠创意产业园2幢3楼
**********
技术文档专员/稳定文职(职位编号：1)
上海博为峰软件技术股份有限公司
五险一金年底双薪绩效奖金全勤奖交通补助通讯补贴带薪年假员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
全勤奖
交通补助
通讯补贴
带薪年假
员工旅游
**********
职位月薪：6001-8000元/月 
工作地点：上海-黄浦区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：5人
职位类别：其他
**********
工作内容：
1、根据测试用例的详细步骤，执行测试用例，执行结果记录和bug记录；
2、通过不断测试、追踪，直到被测软件达到测试需求要求，并没有重大bug；
3、扮演用户角色以尽可能提升用户体验、软件发布。
 任职资格：
1、20～30岁之间，全日制大专及以上学历；
2、计算机或相关专业（理工科为主），接纳无经验但好学的人才； 
3、具有较强的逻辑分析能力和学习能力，良好的沟通表达能力，敏锐的观察力，较强的团队协作意识； 
公司福利：
1、薪酬体系：薪酬=基本工资+绩效+项目提成+生活补贴（均薪6K）；
2、健全的福利制度：五险一金（养老、医疗、事业、生育、工伤）、餐补、通讯补贴等；
3、员工活动：每年必备集体旅行，年会（各种福利发放），公司出资定期进行团队建设；
4、节假日福利：春节，端午节，中秋节、春节、结婚礼金，生日慰问，夏日高温福利等。
5、年终奖：年终双薪绝对不是问题，更有年终分红、期权等着你们来拿。
6、培训：不仅有外部专业大师丰富你的知识，更有内部交流分享机制；
7、奖励晋升机制：在这不看你的年纪，只要你勤奋好学，积极上进，一切职位皆有可能！
                                                                                                                                    发展方向：软件测试、游戏测试、系统测试、功能测试、软件测试架构设计师、测试经理、高级软件测试工程师等等；

工作地址：
上海市黄浦区云南北路59号六合大厦1510室
**********
上海博为峰软件技术股份有限公司
公司规模：
500-999人
公司性质：
上市公司
公司行业：
计算机软件
公司地址：
上海市黄浦区云南北路59号六合大厦1510室
**********
销售工程师
上海日仪电子有限公司
五险一金绩效奖金交通补助通讯补贴带薪年假节日福利餐补
**********
福利:
五险一金
绩效奖金
交通补助
通讯补贴
带薪年假
节日福利
餐补
**********
职位月薪：6001-8000元/月 
工作地点：上海-虹口区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：2人
职位类别：销售代表
**********
岗位职责：
 1、熟悉与掌握公司经营的产品知识与业务，广泛接触行业客户，多渠道收集客户市场项目信息，甄别筛选有效项目信息；
2、利用相关渠道和资源，开拓和维护与客户的良好关系；
3、与客户进行技术交流，在服务工程师的配合下完成技术方案，促进双方项目意向达成；
4、负责商务议价及谈判，促进签订项目合同并对合同条款进行审核；
5、在项目合同签订后，负责合同跟踪的后期工作；
6、按规定定期完成市场销售总结，积极做好内部工作沟通；
7、在项目实施阶段，协助项目管理人员做好客户沟通工作。
 任职资格:
1、两年以上销售工作经验,有外企销售工程师经历者优先； 
2、具备市场信息分析整理能力；具备市场经验和敏感的市场观察力，分析力；
3、熟悉光机电设备及相关产品者优先；
4、独立工作能力和团队合作精神；
5、工作细致、认真负责，具有敬业精神；
6、具备良好的英文应用能力优先；
7、年龄在24-35岁之间，能适应偶尔出差。

工作地址：
四平路775号1号楼513
**********
上海日仪电子有限公司
公司规模：
20-99人
公司性质：
合资
公司行业：
电子技术/半导体/集成电路
公司地址：
四平路775号1号楼513
查看公司地图
**********
技术支持工程师（提供住宿）
上海祎睿图像科技有限公司
五险一金年底双薪包住带薪年假弹性工作定期体检员工旅游
**********
福利:
五险一金
年底双薪
包住
带薪年假
弹性工作
定期体检
员工旅游
**********
职位月薪：3000-6000元/月 
工作地点：上海-松江区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：2人
职位类别：售前/售后技术支持工程师
**********
负责在客户现场安装调试机器视觉和机器人视觉相关系统，负责公司内部软件硬件测试和实验等。

岗位职责：
1.帮助客户解决产品使用中遇到的技术问题，提供售前/售后技术支持工作；并负责客户技术投诉问题的追踪与处理；
2.总结归纳常见问题，收集客户需求，分析产品的优缺点，以及建议改良方向；
3.为客户做产品培训和技术知识培训；

任职要求：
1.大专以上学历，计算机，电子，自动化，机电一体化，机械相关理工科专业；
2.一年以上工作经验，对机器人，机器视觉有一定的了解；
3.熟悉机械图和电气图的相关知识，能看懂机械图和电气图纸；
4.能适应长三角城市经常性出差；
5.具有自主分析与解决问题的能力，善于沟通，有亲和力，有良好的理解力和语言表达能力；
6.具有较好的文字表达，信息收集、归纳、整理能力；

公司可提供住宿。

工作地址：
上海市松江工业区江田东路185号宏亿科技园9号楼410室
**********
上海祎睿图像科技有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
仪器仪表及工业自动化
公司主页：
www.yeerui.com
公司地址：
上海市松江工业区江田东路185号宏亿科技园9号楼410室
查看公司地图
**********
焓差测试员（测试中心）
儒竞艾默生环境优化技术(上海)有限公司
五险一金年底双薪包住交通补助餐补通讯补贴带薪年假节日福利
**********
福利:
五险一金
年底双薪
包住
交通补助
餐补
通讯补贴
带薪年假
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：上海-宝山区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：测试/可靠性工程师
**********
工作职责：
1、执行空调焓差测试，搭建测试平台，编写测试报告；
2、焓差实验室的日常管理和维护保养；
3、参与产品功能、性能、可靠性测试的执行。

技能要求：
1、熟悉焓差实验室构造和原理，熟悉空调系统工作原理；
2、具备暖通、制冷领域理论知识；
3、具有较强的动手能力。

经验要求：
1、暖通制冷、热能、电气、自动化等相关工科专业大专以上学历；
2、一年以上空调焓差实验室工作经验。暖通制冷专业应届毕业生也可考虑；
3、熟悉空调系统工作原理。

工作地址：
上海市宝山区金勺路1515号宝临电气工业园区A1南楼
查看职位地图
**********
儒竞艾默生环境优化技术(上海)有限公司
公司规模：
100-499人
公司性质：
合资
公司行业：
电子技术/半导体/集成电路
公司主页：
www.ruking-emerson.com
公司地址：
上海市杨浦区国权北路1688号湾谷科技园B5栋12楼
**********
电子厂高薪招聘普工操作工包吃住
上海炽硕信息科技有限公司
全勤奖包吃节日福利加班补助带薪年假绩效奖金每年多次调薪五险一金
**********
福利:
全勤奖
包吃
节日福利
加班补助
带薪年假
绩效奖金
每年多次调薪
五险一金
**********
职位月薪：6001-8000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：99人
职位类别：普工/操作工
**********
郑重声明《厂区招聘，绝无任何费用！请求职者谨慎以免上当受骗》
欢迎加微信咨询；17621259850
招聘热线: 176-2125-9850张助理

一、招聘条件
1、年龄要求18-45周岁，初中以上会写26个英文字母2年制（含）以上中专、技校、职高、普高的在校学生；
2、身高160cm以上，身高145cm以上，矫正视力均需0.4以上；
3、认真学习、遵守企业规章制度，可尽快融入企业氛围；
4、持有效身份证件(须为二代身份证原件，临时的也可以），只有户籍证明或复印件不可以参加招聘)。
二、薪资待遇
薪资结构:基本工资+生产奖金+久任奖金+加班费=4500-6000元
1、基本工资：2430元
2、生产奖金：300-500每月由单位主管根据个人绩效表现评定发放
3、久任奖金300-500到职一个月后加350元;
4、加班费：(平时加班1.5倍/周末加班2倍/国定假日3倍)
平时加班：20.95元/小时（1.5倍）
周末加班：27.93元/小时（2.0倍)
法定假日：41.9元/小时（3.0倍）
5、中夜班津贴6-9元/天，中班津贴6元/天,夜班津贴9元/天
6、年终奖金——每年春节前按当年度工作绩效及整体贡献发放年终奖：2000—5000
综合工资的高低取决于加班时数的多少，一般综合工资在,4600-6000元左右。
三、福利待遇
1、保险：公司依法为公司员工缴纳上海五险一金；
2、休假：员工依法享受国家法定节假日、婚假、丧假、产假、带薪年休假等；
3、贴心的福利：生日礼券、结婚礼金、生育津贴等；
4、年度各项公司大型活动及丰富多样的社团活动：晚会、运动会、球类比赛、艺文表演；
5、各项便利设施：室内篮(羽)球场、网吧、图书馆、韵律教室、便利商店、邮局、各式美食餐厅等。
四、伙食住宿
1、公司提供伙食补贴400元/月，当月未用金额在薪资中发放，超额自负。生活区内设有大型员工餐厅，可满足多样化的用餐需求；
2、公司为员工提供宿舍，园区外及园区内宿舍皆采取小区式管理，配备宿舍管理员及安保。
3、公共卫浴之宿舍免住宿费，电费及清洁费固定每月25元/人；独立卫浴之宿舍，每房每月提供50度的免费用电额度，超出部分由舍员共同分摊，从员工每月薪资中扣除，免水费。所有宿舍均提供独立的冷暖空调，无线网等，二十四小时供应洗浴热水及饮用水。
五、工作时间
1、正常工作时间：每天8小时，每周5天；
2、加班时间：平时每日加班不超过3小时，每周至少休息1天；
3、公司执行白晚班两班制。
六、入职流程
由驻厂老师带队前往公司面试报到——录取信息——分发宿舍并放置行李——制作识别卡——新人培训——分发厂服及部门——部门岗前培训——正式上岗
乘车路线：
线路一：上海南站或上海火车站,乘坐地铁1号到徐家汇-转11号线到康新公路2号出口下车，联系我们到面试中心
欢迎加微信咨询；17621788839
招聘热线： 176-2125-9850张助理
官网火热报名中，快乐工作，幸福生活！
郑重声明《厂区招聘无需缴纳任何费用请求职要谨慎以免上当受骗》

工作地址
上海浦东新区康桥工业区

工作地址：
上海市浦东新区康桥工业区
查看职位地图
**********
上海炽硕信息科技有限公司
公司规模：
1000-9999人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司地址：
上海市浦东新区康桥工业区
**********
出纳员
上海伊诺尔实业集团有限公司
五险一金包吃高温补贴节日福利定期体检
**********
福利:
五险一金
包吃
高温补贴
节日福利
定期体检
**********
职位月薪：4000-5000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：出纳员
**********
1、会计、财务等相关专业中专以上学历，有会计从业资格证书；
2、了解国家财经政策和会计、税务法规，熟悉银行结算业务；
3、熟悉会计报表的处理，熟练使用财务软件；
4、善于处理流程性事务、良好的学习能力、独立工作能力和财务分析能力；
5、工作细致，责任感强，良好的沟通能力、团队精神。
6、本地上海户口

工作地址：
上海虹梅南路1755号
查看职位地图
**********
上海伊诺尔实业集团有限公司
公司规模：
500-999人
公司性质：
合资
公司行业：
印刷/包装/造纸
公司主页：
http://www.eternal.com.cn/
公司地址：
上海虹梅南路1755号
**********
销售代表
汉唐高强防潮电子(上海)有限公司
五险一金年底双薪绩效奖金全勤奖补充医疗保险带薪年假节日福利员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
全勤奖
补充医疗保险
带薪年假
节日福利
员工旅游
**********
职位月薪：5000-6000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：中技
招聘人数：5人
职位类别：销售代表
**********
任职要求：
1、专科及以上学历，计算机、机械电子工程等相关专业，底薪+提成；
2、有建立团队、培养领导团队的相关经验;两年以上销售工作经验(电子厂设备及制造产品销售经验者优先)；
3、性格开朗、表达能力强，具有较强的沟通能力及交际技巧，具有亲和力，有敬业精神、能吃苦耐劳；
4、具备一定的市场分析及判断能力，良好的客户服务意识；
5、有责任心，开拓能力强，上进心强，勇于不断迎接新挑战能承受较大的工作压力
  工作地址：
徐汇区宜山路425号光启城908
查看职位地图
**********
汉唐高强防潮电子(上海)有限公司
公司规模：
20-99人
公司性质：
港澳台公司
公司行业：
电子技术/半导体/集成电路
公司地址：
徐汇区宜山路425号908
**********
外贸业务员
汉唐高强防潮电子(上海)有限公司
五险一金补充医疗保险带薪年假不加班节日福利员工旅游绩效奖金全勤奖
**********
福利:
五险一金
补充医疗保险
带薪年假
不加班
节日福利
员工旅游
绩效奖金
全勤奖
**********
职位月薪：4001-6000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：2人
职位类别：外贸/贸易经理/主管
**********
1. 有外贸二年以上经验，听、说、读、写英文能力最佳者优先考虑；
2. 熟悉产品，对产品有所掌握，并能独立分析其组成和给予准确的报价 ；
3. 熟悉产品在市场上的定位,能独立开发客户，对外贸流程了解，对产品的规格、质量等都能给客户及时的答复；
4. 生产过程应跟踪、验货，做到质量保证；
5. 及时通知客户和货代有关货物装运的情况
  工作地址：
徐汇区宜山路425号光启城908
查看职位地图
**********
汉唐高强防潮电子(上海)有限公司
公司规模：
20-99人
公司性质：
港澳台公司
公司行业：
电子技术/半导体/集成电路
公司地址：
徐汇区宜山路425号908
**********
课程销售
上海强平机器人科技有限公司
创业公司每年多次调薪五险一金年底双薪绩效奖金股票期权弹性工作员工旅游
**********
福利:
创业公司
每年多次调薪
五险一金
年底双薪
绩效奖金
股票期权
弹性工作
员工旅游
**********
职位月薪：10001-15000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：6人
职位类别：销售代表
**********
岗位职责：
1、跟踪销售机会，预约客户到门店体验；
2、与客户洽谈，并促进签约；
3、跟踪到店未签约客户，争取客户的再次光顾签约；
4、维护现有客户关系，实现续约；
5、开拓合作渠道，发展更多的销售机会。

任职要求：
1、形象良好，热情大方，沟通能力强；
2、热爱销售工作，喜欢与人打交道；
3、目的性强，有韧性，抗挫折、抗打击能力强；
4、渴望实现目标，喜欢挑战自己，赚更多的钱。
5、有较强的组织性、纪律性；
6、能够适应服务行业的工作时间安排（周六、日需要上班，休息日在周间）

工作地址：
上海市宝山大华、金沙江路真北路、松江大学城
查看职位地图
**********
上海强平机器人科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
学术/科研
公司主页：
www.qiangping-robot.com
公司地址：
上海市宝山大华、金沙江路真北路、松江大学城
**********
客户代表
汉唐高强防潮电子(上海)有限公司
全勤奖绩效奖金五险一金带薪年假员工旅游节日福利不加班补充医疗保险
**********
福利:
全勤奖
绩效奖金
五险一金
带薪年假
员工旅游
节日福利
不加班
补充医疗保险
**********
职位月薪：5000-6000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：中技
招聘人数：3人
职位类别：销售代表
**********
任职要求：
1、专科及以上学历，计算机、机械电子工程等相关专业，底薪+提成；
2、有建立团队、培养领导团队的相关经验;两年以上销售工作经验(电子厂设备及制造产品销售经验者优先)；
3、性格开朗、表达能力强，具有较强的沟通能力及交际技巧，具有亲和力，有敬业精神、能吃苦耐劳；
4、具备一定的市场分析及判断能力，良好的客户服务意识；
  工作地址：
徐汇区宜山路425号光启城908
查看职位地图
**********
汉唐高强防潮电子(上海)有限公司
公司规模：
20-99人
公司性质：
港澳台公司
公司行业：
电子技术/半导体/集成电路
公司地址：
徐汇区宜山路425号908
**********
商用厨具钣金结构设计
合肥顺昌分布式能源综合应用技术有限公司
五险一金年底双薪绩效奖金包吃包住通讯补贴员工旅游节日福利
**********
福利:
五险一金
年底双薪
绩效奖金
包吃
包住
通讯补贴
员工旅游
节日福利
**********
职位月薪：10001-15000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：5-10年
最低学历：大专
招聘人数：1人
职位类别：机械制图员
**********
岗位职责：
1、负责厨具产品的结构、材料、电器、五金配件等的标准模块的设计，有商用厨房工程项目设计跟进操作经验。
2、负责跟踪新工程项目结构图纸和下料、折弯图纸，解决工程现场非标件产品的结构工艺问题。
3、商用厨房燃气灶具类、白钢件类产品结构图、展开下料、折弯图。

任职要求：
1、性别不限，有商用厨具行业钣金结构设计从业经验3年以上。
2、责任心强，能接受加班，因行业特殊性，会有加班，但工资会含加班费用的。
3、有在厨房工程公司任职或有五星级酒店厨具、学校及机关单位食堂结构设计工作经验者优先。
薪资水平：职位月薪仅供参考，具体薪资待遇面议。
 员工福利：
1、签订劳动合同，购买五险；
2、提供专业的培训学习机会，良好晋升空间；
3、提供食宿，年休假，生日会，过节费和年终奖等；
4、五天工作制，双休。
 工作地址及联系方式：
工作地点：经开区桃花工业园长古路与祝融路交口西50米
公交线路： 
1、234路公交，到繁华新园站下，站台西侧即是顺昌企业。
2、80路公交车，到繁祝路口站下，沿祝融路北行400米，长古路交口西50米即到顺昌企业。
联系人/联系方式：朱先生    0551-63413388-8013  13645698226

工作地址：
合肥市桃花工业园祝融路与长古路交叉口向西100米 1、234路公交，到繁华新园站下，沿祝融路往北走10米，再沿长古路向西走130米即为顺昌企业。2、80路公交车，到繁祝路口站下，繁华大道往东走60米，右转，沿祝融路走440米，往西沿长古路走130米即顺昌企业
**********
合肥顺昌分布式能源综合应用技术有限公司
公司规模：
100-499人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
www.cnjsc.com
公司地址：
合肥市桃花工业园祝融路与长古路交叉口向西100米 1、234路公交，到繁华新园站下，沿祝融路往北走10米，再沿长古路向西走130米即为顺昌企业。2、80路公交车，到繁祝路口站下，繁华大道往东走60米，右转，沿祝融路走440米，往西沿长古路走130米即顺昌企业
**********
跨境电商运营经理
上海未来伙伴机器人有限公司
节日福利
**********
福利:
节日福利
**********
职位月薪：10000-15000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：本科
招聘人数：1人
职位类别：电子商务经理/主管
**********
工作职责： 1、负责公司跨境电子商务英文国家的运营工作 2、负责公司跨境电子商务网店、APP多平台的整体产品运营，制定产品活动策划、方案和计划并组织执行，根据用户不同的需求，制定运营策略、方案和活动； 3、运用各种新媒体渠道和异业合作手段，对产品及平台进行营销推广，维护平台的客户资源及时提供市场反馈； 4、统计、分析网店、APP平台各类数据（市场、产品、策划执行效果等），对公司运营决策提供支撑； 5、分析和改进并参与公司网站平台的品牌、产品的推广，实现公司既定目标，对网店及App运营推广及产品销售业绩负责。 任职资格： 1.二年年以上跨境电子商务行业背景经验，英语听说读写流利 2.具有很强的沟通协调和项目管理能力； 3.具备良好的沟通协调能力和创业精神，富有责任心和工作激情。组织并完成公司整体业务计划；建立公司内部信息系统；负责协调各部门工作，建立有效的团队协作机制；维持并开拓各方面的外部关系；管理并激励所属部门的工作业绩效。 4.丰富的互联网产品运营管理经验，良好的市场开发及营销能力。 5.善于内外沟通与团队合作、有团队管理经验，高度的责任感、心理承压能力强。
所属部门：销售部门
部门人数：
汇报对象：
工作地址：
合川路2555号科技绿洲三期五2号楼
查看职位地图
**********
上海未来伙伴机器人有限公司
公司规模：
500-999人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.grandar.com
公司地址：
上海市钦州北路1122号90栋8楼
**********
电子技工/技术员 双休包住宿加社保
上海光洋欧克电子科技发展有限公司
包住餐补五险一金加班补助
**********
福利:
包住
餐补
五险一金
加班补助
**********
职位月薪：2800-4500元/月 
工作地点：上海-静安区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：高中
招聘人数：10人
职位类别：电路工程师/技术员
**********
电子技工/技术员: 若干
1.性别不限.
2.中专或同等以上学历,学过家电维修、传感器、工业自动化、应用电子技术、仪器仪表等专业。
3.有电子电器及家电维修的经验,熟练使用电烙铁,数字万用表，示波器等操作工具.
4.动手能力强,上手快,有团队合作精神.
待遇:第一年底薪按技术水平定2800-4500/月(逐年按10-20%递增) +餐补(264/月)+包住宿（可提供公司宿舍)+社保+双休+（如加班：加班工资及工作餐另加）
有传感器对口生产及研发者待遇可面议。
工作地址：
江场三路307号
查看职位地图
**********
上海光洋欧克电子科技发展有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司主页：
http://www.cn-gy.com/
公司地址：
闸北区江场三路307号
**********
仪器仪表销售
上海玛辛电气有限公司
五险一金绩效奖金不加班节日福利弹性工作创业公司
**********
福利:
五险一金
绩效奖金
不加班
节日福利
弹性工作
创业公司
**********
职位月薪：5000-8000元/月 
工作地点：上海-虹口区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：中专
招聘人数：3人
职位类别：销售代表
**********
岗位职责：
1、开拓新市场,发展客户,增加产品销售范围；
2、负责所辖区域的产品销售任务；
3、负责项目跟进，维护及增进已有客户关系等事宜；
4、完成部分技术支持工作,与客户进行技术交流；
5、负责销售区域内销售活动的策划和执行，完成销售指标；
6、产品交付、款项进度等跟进与解决。
7、负责收集市场和行业信息,加深了解。

任职要求：
1、中专以上学历，电子，电气，机电 仪器仪表专业优先考虑；
2、至少1年以上销售经验，有行业背景者优先；
3、男女不限，退伍军人优先；
4、有客观的评判能力以及决策力；
5、外向型性格、自信心较强、语言表达清晰、善于与人沟通；
6、较强的学习能力和自我管理能力；
7、品行端正，有良好的职业操守，吃苦耐劳；
8、工作地点：虹口区
9、五险一金，薪酬面议（工资+提成）； 国家法定带薪年假、企业带薪年假
10、公司会给每位新员工进行基础培训、专业培训和深度提升培训

热情欢迎对自己有要求，愿成就个人辉煌事业的各位同仁！敬侯您的简历

工作地址：
上海市天宝路578号飘鹰世纪大厦6层619室
查看职位地图
**********
上海玛辛电气有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司地址：
上海市天宝路578号飘鹰世纪大厦6层619室
**********
乐高机器人讲师
上海强平机器人科技有限公司
五险一金绩效奖金带薪年假弹性工作员工旅游高温补贴节日福利
**********
福利:
五险一金
绩效奖金
带薪年假
弹性工作
员工旅游
高温补贴
节日福利
**********
职位月薪：4001-6000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：不限
招聘人数：10人
职位类别：培训师/讲师
**********
岗位要求：有亲和力、耐心、责任感强；踏实肯干，热爱教育事业；了解乐高高年龄段编程课程，电子电路物理基础知识扎实，有相关机器人培训教育机构实习或工作经验者优先；
薪资待遇：底薪+课时+提成、五险一金、法定年休、季度奖金、带队去国外参加比赛的机会
更多机会：您可以接触并学习到国际上最先进的科技教育理念和方法；在富有挑战性的科学课堂锻炼自己的教学能力；有机会参与外省市的科技支教活动；有机会参加上海地区的科技教育论坛及相关学术活动
工作地点：
大华店（总部）：上海市宝山区大华一路210号嘉年华大厦701
江湾城店：殷行路1280号01（东）栋505室强平机器人
南方商城店：古方路18号南方休闲商务大厦302
118广场店：普陀区金沙江路1685号118广场3楼
  工作地址：
上海市普陀区大华一路210号嘉年华大厦701室
查看职位地图
**********
上海强平机器人科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
学术/科研
公司主页：
www.qiangping-robot.com
公司地址：
上海市宝山大华、金沙江路真北路、松江大学城
**********
操作岗位/6k起+双休W
上海于晓软件技术有限公司
五险一金年底双薪绩效奖金全勤奖交通补助通讯补贴带薪年假员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
全勤奖
交通补助
通讯补贴
带薪年假
员工旅游
**********
职位月薪：6001-8000元/月 
工作地点：上海-黄浦区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：5人
职位类别：普工/操作工
**********
岗位要求:
1.大专及以上学历，理工科相关专业，20-30岁之间;
2.工作积极主动，学习能力强，具有较强的执行力和团队协作精神。
公司福利：
1、薪酬体系：薪酬=基本工资+绩效+项目提成+生活补贴（均薪6K）；
2、健全的福利制度：五险一金（养老、医疗、事业、生育、工伤）、餐补、通讯补贴等；
3、员工活动：每年必备集体旅行，年会（各种福利发放），公司出资定期进行团队建设；
4、节假日福利：春节，端午节，中秋节、春节、结婚礼金，生日慰问，夏日高温福利等。
5、年终奖：年终双薪绝对不是问题，更有年终分红、期权等着你们来拿。
6、培训：不仅有外部专业大师丰富你的知识，更有内部交流分享机制；
7、晋升机制：在这不看你的年纪，不论你的专业，只要你勤奋好学，积极上进，一切职位皆有可能！
 
工作地址：
上海市黄浦区
查看职位地图
**********
上海于晓软件技术有限公司
公司规模：
500-999人
公司性质：
股份制企业
公司行业：
计算机软件
公司地址：
**********
汽车维修工程师/高薪岗(职位编号：1)
上海博为峰软件技术股份有限公司
五险一金年底双薪绩效奖金全勤奖交通补助通讯补贴带薪年假员工旅游
**********
福利:
五险一金
年底双薪
绩效奖金
全勤奖
交通补助
通讯补贴
带薪年假
员工旅游
**********
职位月薪：6001-8000元/月 
工作地点：上海-徐汇区
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：5人
职位类别：汽车维修/保养
**********
岗位要求：
1、大专及以上学历具有上进心;
2、致力于计算机行业发展,对计算机与互联网行业感兴趣；
3，具有一定的计算机理论与基础，擅长玩游戏的优先。
应聘条件：
1，优秀的学习能力，擅长团队合作；
2，年龄：20-30岁，不符合条件勿扰。
 薪资福利：月薪6000+绩效，双休，朝九晚六，五险一金，每日10元餐补，节日生日福利，丰厚年终奖等。
 公司发展：公司内部主管经理均为普通员工提拔，且在全国30多个城市均有分公司，有巨大发展潜力。

工作地址：
上海徐汇漕河泾虹梅路2007号1号楼9楼
**********
上海博为峰软件技术股份有限公司
公司规模：
500-999人
公司性质：
上市公司
公司行业：
计算机软件
公司地址：
上海市黄浦区云南北路59号六合大厦1510室
**********
科技活动老师
上海强平机器人科技有限公司
创业公司每年多次调薪五险一金年底双薪绩效奖金股票期权弹性工作员工旅游
**********
福利:
创业公司
每年多次调薪
五险一金
年底双薪
绩效奖金
股票期权
弹性工作
员工旅游
**********
职位月薪：8001-10000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：本科
招聘人数：6人
职位类别：教学/教务管理人员
**********
岗位职责：
1、按照教务管理要求形成每周所有科技教学活动的设计方案；
2、高质量地执行教学活动方案；
3、跟踪学员的学习状态，与学员家长保持积极互动，提升学员的学习兴趣和学习效果、以及家长对教学服务的满意度。

任职要求：
1、理工科背景，机械、电子、计算机、通信、软件、自动化等专业优先考虑；
2、性格外向，形象良好，乐于沟通；
3、有较强的组织性、纪律性，具有一定的活动组织管理能力；
4、能够适应服务行业的工作时间安排（周六、日需要上班，休息日在周间）。



工作地址：
上海市大华、金沙江路、松江大学城
**********
上海强平机器人科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
学术/科研
公司主页：
www.qiangping-robot.com
公司地址：
上海市宝山大华、金沙江路真北路、松江大学城
查看公司地图
**********
地推小时工
上海强平机器人科技有限公司
节日福利
**********
福利:
节日福利
**********
职位月薪：2001-4000元/月 
工作地点：上海-宝山区
发布日期：最新
工作性质：兼职
工作经验：不限
最低学历：不限
招聘人数：1人
职位类别：培训/招生/课程顾问
**********
岗位职责：发宣传单页以及拿名单

任职要求：平时去幼儿园周边发单页，周六周日在大华一路嘉年华周边商圈发单页以及拿名单为主
工作地址：
上海市宝山区大华一路210号虎城嘉年华701室强平机器人
查看职位地图
**********
上海强平机器人科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
学术/科研
公司主页：
www.qiangping-robot.com
公司地址：
上海市宝山大华、金沙江路真北路、松江大学城
**********
销售代表
上海祎睿图像科技有限公司
五险一金绩效奖金包住带薪年假弹性工作定期体检员工旅游
**********
福利:
五险一金
绩效奖金
包住
带薪年假
弹性工作
定期体检
员工旅游
**********
职位月薪：4001-6000元/月 
工作地点：上海-松江区
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：2人
职位类别：销售代表
**********
岗位职责：
1、负责推广销售公司研发与代理的机器视觉及机器人相关产品，能够针对不同行业做市场分析，制定销售计划；
2、对重要客户进行开拓，沟通与管理，制定合作方案；
3、负责区域内市场信息的收集及竞争对手的分析；
4、在目标领域，围绕公司战略，深入开拓市场。

任职要求：
1、计算机/电子信息/机电一体化/机械自动化等工科类相关专业，大专以上学历；
2、热爱销售工作，工作勤奋，积极热忱，具备一定的销售谈判技巧，有较强的人际沟通能力和客户亲和力；
3、具有良好的学习能力，分析和解决问题的能力，能承受较强的压力；
4、有一定市场营销工作经验，机器视觉，机器人，自动化相关领域从业者优先；
5、有3C，包装，食品医疗等行业经验者优先；

公司目前拥有自主研发的机器视觉定位及对位系统、外观检查系统等产品，应用于3C，液晶，丝网印刷，金属加工，包装医疗等多个行业，产品成熟稳定，并可扩展机器人与自动化集成一起推广，应用前景广阔。薪资待遇为底薪加高提成，公司有宿舍可负责住宿，诚邀有能力与有志之士共图发展。
工作地址：
上海市松江工业区江田东路185号宏亿科技园9号楼410室
**********
上海祎睿图像科技有限公司
公司规模：
20人以下
公司性质：
民营
公司行业：
仪器仪表及工业自动化
公司主页：
www.yeerui.com
公司地址：
上海市松江工业区江田东路185号宏亿科技园9号楼410室
查看公司地图
**********
区域销售工程师/主管1
深圳市嘉昱机电有限公司
五险一金绩效奖金交通补助节日福利员工旅游
**********
福利:
五险一金
绩效奖金
交通补助
节日福利
员工旅游
**********
职位月薪：4000-8000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：销售代表
**********
职位职责：
1.负责上海及周边区域的行业目标客户的收集与开拓
2.约客户拜访，展示我们的公司实力和产品优势
3.争取产品试用机会
4.跟进客户项目，达到成功购买；
5.货款回收，商务谈判
6.定期向总公司领导以书面方式汇报工作
7.搜集竞争对手的信息，书面反馈总公司
8.领导安排其他的任务
要求：
1.电子电路有一定的认识，自动化专业优先
2.专业大专以上，口齿清晰，口头表达能力强
3. 强烈的成交意愿
4. 良好的团队合作能力和沟通能力，服从公司的任务安排和管理
5. 敬业爱岗，能和公司一起发展
6，有伺服驱动器销售经验者优先

工作地址：
上海市闵行区颛桥镇银都路好世凤凰城31-101
查看职位地图
**********
深圳市嘉昱机电有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司地址：
深圳市宝安区新安街道宝安26号
**********
销售工程师/销售代表
深圳市嘉昱机电有限公司
五险一金绩效奖金交通补助节日福利员工旅游
**********
福利:
五险一金
绩效奖金
交通补助
节日福利
员工旅游
**********
职位月薪：4000-8000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：大客户销售代表
**********
职位职责：
1.约客户拜访，展示我们的公司实力和产品优势
2.负责上海及周边区域的行业目标客户的收集与开拓
3.争取产品试用机会
4.跟进客户项目，达到成功购买；
5.货款回收，商务谈判
6.定期向总公司领导以书面方式汇报工作
7.搜集竞争对手的信息，书面反馈总公司
8.领导安排其他的任务
要求：
1.电子电路有一定的认识，自动化专业优先
2.专业大专以上，口齿清晰，口头表达能力强
3. 强烈的成交意愿
4. 良好的团队合作能力和沟通能力，服从公司的任务安排和管理
5. 敬业爱岗，能和公司一起发展
6，有伺服驱动器销售经验者优先

工作地址：
上海市闵行区颛桥镇银都路好世凤凰城31-101
查看职位地图
**********
深圳市嘉昱机电有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司地址：
深圳市宝安区新安街道宝安26号
**********
销售工程师/主管/销售代表
深圳市嘉昱机电有限公司
五险一金绩效奖金交通补助节日福利员工旅游
**********
福利:
五险一金
绩效奖金
交通补助
节日福利
员工旅游
**********
职位月薪：4000-8000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：销售工程师
**********
职位职责：
1.负责上海及周边区域的行业目标客户的收集与开拓
2.约客户拜访，展示我们的公司实力和产品优势
3.争取产品试用机会
4.跟进客户项目，达到成功购买；
5.货款回收，商务谈判
6.定期向总公司领导以书面方式汇报工作
7.搜集竞争对手的信息，书面反馈总公司
8.领导安排其他的任务
要求：
1.专业大专以上，口齿清晰，口头表达能力强
2.电子电路有一定的认识，自动化专业优先
3. 强烈的成交意愿
4. 良好的团队合作能力和沟通能力，服从公司的任务安排和管理
5. 敬业爱岗，能和公司一起发展
6，有伺服驱动器销售经验者优先

工作地址：
上海市闵行区颛桥镇银都路好世凤凰城31-101
查看职位地图
**********
深圳市嘉昱机电有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司地址：
深圳市宝安区新安街道宝安26号
**********
商务经理
上海诺时实验设备科技有限公司
五险一金交通补助餐补房补通讯补贴节日福利高温补贴
**********
福利:
五险一金
交通补助
餐补
房补
通讯补贴
节日福利
高温补贴
**********
职位月薪：2001-4000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：不限
最低学历：大专
招聘人数：3人
职位类别：助理/秘书/文员
**********
岗位职责：负责上海办事处的商务一切事宜；招投标工作；公司网站后台的管理及操作等。
岗位要求：熟练掌握CAD工具基本办公软件及；思维灵活；会开车。
工作地址：
浦东新区长清路1200弄36号
**********
上海诺时实验设备科技有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
大型设备/机电设备/重工业
公司主页：
http://www.shnuoshi.com/
公司地址：
上海市青浦区重固镇北青公路6725弄6号3幢-5室
**********
暖通/空调/地暖/门店销售工程师
上海雅鸣制冷设备工程有限公司
**********
福利:
**********
职位月薪：4001-6000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：不限
招聘人数：5人
职位类别：空调工程/设计
**********
岗位职责：
1、负责中央空调、地暖、新风、水处理产品在上海地区的销售；
2、负责装潢装修公司、设计师渠道、企业员工内购、家博会和高端小区渠道的开拓、开发、管理与维护；
3、具备中央空调、地暖、地源热泵等独立的客户开发能力，及有较强的客户沟通能力，及高度的团队合作精神；
4、独立销售能力强，能独立安排销售工作；
5、 熟悉上海市场暖通空调行业情况（或者在其他行业的佼佼者，暖通知识可以由公司培训）； 
6、 有较强的沟通能力，对客户有亲和力； 
7、工作认真勤劳；
8、工作时间弹性。
9、能吃苦耐劳，服上级从安排，有较强责任心，工作仔细认真；
10、有正确的价值观，为人正直，诚实守信，良好的道德品质、职业操守和工作态度；
11、管理客户关系，完成销售任务；
12、了解和发掘客户需求及购买愿望，介绍自己产品的优点和特色；
13、收集潜在客户资料；
 任职要求：
1、大专及以上学历，市场营销等相关专业；
2、1-2年以上销售行业工作经验，业绩突出者优先；
3、反应敏捷、表达能力强，具有较强的沟通能力及交际技巧，具有亲和力；
4、具备一定的市场分析及判断能力，良好的客户服务意识；
5、有责任心，能承受较大的工作压力；
6、有团队协作精神，善于挑战。
 福利待遇：
1、底薪+高提成+项目奖金（年薪上不封顶、优秀销售10万以上）
2、表现优异者，公司提供完善的升职空间 
 面试地址：
总部：上海市杨浦区政立路816号
吴工程师 13331876888

工作地址：
杨浦区政立路816号
查看职位地图
**********
上海雅鸣制冷设备工程有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司地址：
上海市杨浦区政立路816号
**********
暖通或弱电工程师
上海雅鸣制冷设备工程有限公司
**********
福利:
**********
职位月薪：4001-6000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：不限
招聘人数：2人
职位类别：空调工程/设计
**********
岗位职责：
1、 及时发现本专业的技术风险，并制定整改方案。
2、 根据时间节点拟定该专业全国性的大修设备解剖方案。
3、 根据客户需求，拟定该专业的技术改造方案，并促成方案的落地。
4、 及时处理设备突发状况以及该专业的疑难杂症，并制定预防措施。
5、 开发本专业的设备维修、维保类培训课程，并完成授课。
6、 协调区域内各城市的技术资源，并完成资源调配。
7、 优化现有的作业流程，提高现场效率。
8、 推动新产品、新技术的运用，并能成功运用于现场工作中。
9、 为公司提供法律、法规、行业规范的支持，并能规避相关法律风险。
10、能接受频繁出差。 
任职资格：
1、 本科学历，中级及以上职称或设备类技师职业技能等级证书。
2、具有设备故障突发情况应急处理能力，以及与客户开展技术交流、方案讨论的能力。
3、具有敏锐的风险意识，抗压能力强，在该专业技术上能够独挡一面。

工作地址：
杨浦区政立路816号
查看职位地图
**********
上海雅鸣制冷设备工程有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司地址：
上海市杨浦区政立路816号
**********
销售代表
深圳市嘉昱机电有限公司
五险一金绩效奖金交通补助节日福利员工旅游
**********
福利:
五险一金
绩效奖金
交通补助
节日福利
员工旅游
**********
职位月薪：4000-8000元/月 
工作地点：上海
发布日期：最新
工作性质：全职
工作经验：1-3年
最低学历：大专
招聘人数：1人
职位类别：销售代表
**********
职位职责：
1.争取产品试用机会
2.约客户拜访，展示我们的公司实力和产品优势
3.负责上海及周边区域的行业目标客户的收集与开拓
4.跟进客户项目，达到成功购买；
5.货款回收，商务谈判
6.定期向总公司领导以书面方式汇报工作
7.搜集竞争对手的信息，书面反馈总公司
8.领导安排其他的任务
要求：
1.电子电路有一定的认识，自动化专业优先
2.专业大专以上，口齿清晰，口头表达能力强
3. 强烈的成交意愿
4. 良好的团队合作能力和沟通能力，服从公司的任务安排和管理
5. 敬业爱岗，能和公司一起发展
6，有伺服驱动器销售经验者优先

工作地址：
上海市闵行区颛桥镇银都路好世凤凰城31-101
查看职位地图
**********
深圳市嘉昱机电有限公司
公司规模：
20-99人
公司性质：
民营
公司行业：
电子技术/半导体/集成电路
公司地址：
深圳市宝安区新安街道宝安26号